Repository getsentry/sentry, pull requests merged in 2019-02, with the labels that each got.

#11837 fix(discover): Defer autorunning queries until tags are loaded
  src/sentry/static/sentry/app/views/organizationDiscover/discover.jsx
  src/sentry/static/sentry/app/views/organizationDiscover/index.jsx
  tests/js/spec/views/organizationDiscover/discover.spec.jsx
  tests/js/spec/views/organizationDiscover/index.spec.jsx
Labels: Type: Bug

#11905 fix: Fix organization switching for non Sentry 10 users
  src/sentry/static/sentry/app/components/sidebar/sidebarDropdown/switchOrganization.jsx
Labels: Type: Bug

#11923 fix(issues): Fix group activity item component
  src/sentry/static/sentry/app/views/groupDetails/shared/groupActivity.jsx
  tests/js/spec/views/groupActivity/index.spec.jsx
Labels: Type: Bug

#11826 ref(service-hooks): Add ServiceHookProject table
  src/sentry/api/endpoints/project_servicehooks.py
  src/sentry/mediators/sentry_app_installations/creator.py
  src/sentry/mediators/service_hooks/creator.py
  src/sentry/mediators/service_hooks/updater.py
  src/sentry/models/servicehook.py
  src/sentry/south_migrations/0462_auto__add_servicehookproject.py
  src/sentry/testutils/fixtures.py
  tests/sentry/api/bases/test_sentryapps.py
  tests/sentry/api/endpoints/test_organization_sentry_app_installation_details.py
  tests/sentry/api/endpoints/test_organization_sentry_app_installations.py
  tests/sentry/api/endpoints/test_project_servicehooks.py
  tests/sentry/api/endpoints/test_sentry_app_authorizations.py
  tests/sentry/auth/test_access.py
  tests/sentry/mediators/sentry_app_installations/test_creator.py
  tests/sentry/mediators/sentry_app_installations/test_destroyer.py
  tests/sentry/mediators/sentry_app_installations/test_installation_notifier.py
  tests/sentry/mediators/service_hooks/test_creator.py
  tests/sentry/mediators/service_hooks/test_updater.py
  tests/sentry/tasks/test_sentry_apps.py
Labels: Impact: Migration

#11868 feat(monitors): Initial UI
  bin/load-mocks
  src/sentry/api/base.py
  src/sentry/api/bases/monitor.py
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/api/endpoints/monitor_details.py
  src/sentry/api/endpoints/monitor_stats.py
  src/sentry/api/endpoints/organization_monitors.py
  src/sentry/api/serializers/models/monitor.py
  src/sentry/api/urls.py
  src/sentry/models/monitor.py
  src/sentry/models/monitorcheckin.py
  src/sentry/static/sentry/app/components/issueList.jsx
  src/sentry/static/sentry/app/components/organizations/globalSelectionHeader/globalSelectionHeader.jsx
  src/sentry/static/sentry/app/components/sidebar/index.jsx
  src/sentry/static/sentry/app/routes.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/checkInIcon.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/details.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/edit.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/index.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/monitorCheckIns.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/monitorHeader.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/monitorIcon.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/monitorIssues.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/monitorStats.jsx
  src/sentry/static/sentry/app/views/organizationMonitors/monitors.jsx
  src/sentry/static/sentry/less/components/charts.less
  src/sentry/static/sentry/less/shared-components.less
  src/sentry/tsdb/base.py
  src/south/management/commands/testserver.py
  tests/acceptance/__init__.py
  tests/js/spec/views/userFeedback/__snapshots__/organizationUserFeedback.spec.jsx.snap
  tests/sentry/api/endpoints/test_monitor_details.py
  tests/sentry/api/endpoints/test_organization_monitors.py
  tests/snuba/__init__.py
  tests/snuba/api/__init__.py
  tests/snuba/api/endpoints/__init__.py
  tests/snuba/api/serializers/__init__.py
  tests/snuba/tagstore/__init__.py
  tests/snuba/tsdb/__init__.py
Labels: WIP

#11151 feat(integrations): Update Comment Sync
  src/sentry/api/bases/group.py
  src/sentry/api/endpoints/group_notes.py
  src/sentry/api/endpoints/group_notes_details.py
  src/sentry/api/serializers/rest_framework/group_notes.py
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/issues.py
  src/sentry/integrations/jira/client.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/vsts/integration.py
  src/sentry/integrations/vsts/issues.py
  src/sentry/tasks/integrations.py
  tests/sentry/api/endpoints/test_group_notes.py
  tests/sentry/api/endpoints/test_group_notes_details.py
  tests/sentry/integrations/jira/test_integration.py
  tests/sentry/integrations/vsts/test_integration.py
Labels: Component: Integrations

#11571 feat(dashboards): Dashboard Details Endpoint (put method).
  src/sentry/api/bases/dashboard.py
  src/sentry/api/endpoints/organization_dashboard_details.py
  src/sentry/api/endpoints/organization_dashboard_widgets.py
  src/sentry/api/serializers/rest_framework/widget.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
Labels: Component: API

#12083 feat(serializers): Added environment names to ProjectSummarySerializer.
  .vscode/settings.json
  src/sentry/api/serializers/models/project.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/serializers/test_project.py
Labels: Component: API

#12096 fix(issues): Fix group url
  src/sentry/models/group.py
Labels: Type: Bug

#12125 fix(integrations): Change Jira's `sync_assignee_outbound` search for user emails in a case insensitive manner.
  src/sentry/integrations/jira/integration.py
  tests/sentry/integrations/jira/test_integration.py
Labels: Component: Integrations

#12181 fix: Fix global selection persistence
  src/sentry/static/sentry/app/stores/globalSelectionStore.jsx
Labels: Type: Bug

#12187 fix: Fix avatar chooser component
  src/sentry/static/sentry/app/components/avatarChooser.jsx
Labels: Type: Bug
