Repository getsentry/sentry, pull requests merged in 2020-03, with the labels that each got.

#17514 fix(workflow/projectCreation): UI
  src/sentry/api/endpoints/project_agnostic_rule_conditions.py
  src/sentry/static/sentry/app/types/index.tsx
  src/sentry/static/sentry/app/views/projectInstall/createProject.jsx
  src/sentry/static/sentry/app/views/projectInstall/issueAlertOptions.tsx
  src/sentry/static/sentry/app/views/projectInstall/newProject.jsx
  tests/js/spec/views/projectInstall/createProject.spec.jsx
  tests/js/spec/views/projectInstall/issueAlertOptions.spec.jsx
  tests/sentry/api/endpoints/test_project_agnostic_rule_conditions.py
Labels: Do Not Merge

#17480 ref(pagerduty): Update to version 2
  src/sentry/integrations/pagerduty/integration.py
Labels: On hold

#17815 fix(settings): Update copy in Data Privacy settings page
  src/sentry/static/sentry/app/views/settings/components/dataPrivacyRulesPanel/dataPrivacyRulesPanel.tsx
  src/sentry/static/sentry/app/views/settings/organizationSecurityAndPrivacy/organizationSecurityAndPrivacyContent.tsx
  src/sentry/static/sentry/app/views/settings/projectDataPrivacy/projectDataPrivacyContent.tsx
Labels: Component: UI, Impact: Small

#17929 fix(ui): Preserve whitespace in alert messages
  src/sentry/static/sentry/app/components/alert.tsx
  src/sentry/static/sentry/app/components/events/sdkUpdates.jsx
  tests/js/spec/components/__snapshots__/confirmDelete.spec.jsx.snap
  tests/js/spec/components/events/__snapshots__/sdkUpdates.spec.jsx.snap
  tests/js/spec/views/projectPlugins/__snapshots__/projectPlugins.spec.jsx.snap
Labels: Component: UI
