Repository getsentry/sentry, pull requests merged in 2020-01, with the labels that each got.

#16281 fix(audit-logs) - Adding ACL to the audit logs endpoint
  src/sentry/api/bases/organization.py
  src/sentry/api/endpoints/organization_auditlogs.py
Labels: Security

#16339 fix(issues): Remove fingerprint for RouteErrors
  src/sentry/static/sentry/app/views/routeError.jsx
Labels: Component: Issues, Impact: Small

#16327 fix: Suppress unexpected Type Error in capturing RouteError
  src/sentry/static/sentry/app/views/routeError.jsx
Labels: Component: Issues, Impact: Small, Type: Bug

#16564 fix(deletion): Fix group deletion
  src/sentry/runner/commands/cleanup.py
Labels: Type: Bug

#16418 fix(GlobalSelectionHeader): Fix switch org bug
  src/sentry/static/sentry/app/components/organizations/globalSelectionHeader/index.jsx
  tests/acceptance/test_organization_switch.py
Labels: Component: UI, Impact: Small, Type: Bug

#16670 tests(async-csv): Add working tests for backend routes
  tests/sentry/api/endpoints/test_data_export.py
  tests/sentry/api/endpoints/test_data_export_details.py
Labels: WIP
