Repository getsentry/sentry, pull requests merged in 2020-10, with the labels that each got.

#21126 build(docker): Start building Python 3 images
  docker/Dockerfile
  docker/cloudbuild.yaml
Labels: Do Not Merge

#21356 feat(ui): Add support for custom event/group title
  src/sentry/static/sentry/app/components/eventOrGroupTitle.tsx
  src/sentry/static/sentry/app/components/issueLink.tsx
  src/sentry/static/sentry/app/components/issues/compactIssue.jsx
  src/sentry/static/sentry/app/utils/events.tsx
  src/sentry/static/sentry/app/views/eventsV2/eventDetails/content.tsx
  src/sentry/static/sentry/app/views/eventsV2/results.tsx
  src/sentry/static/sentry/app/views/eventsV2/utils.tsx
  src/sentry/static/sentry/app/views/organizationGroupDetails/groupDetails.tsx
  src/sentry/static/sentry/app/views/organizationGroupDetails/header.jsx
  tests/js/spec/components/eventOrGroupHeader.spec.jsx
  tests/js/spec/components/eventOrGroupTitle.spec.jsx
Labels: WIP

#14913 fix(accounts): Prevent Referer leak on password reset page
  src/sentry/web/decorators.py
  src/sentry/web/frontend/accounts.py
  tests/sentry/web/frontend/test_accounts.py
Labels: Hacktoberfest
