Repository getsentry/sentry, pull requests merged in 2021-10, with the labels that each got.

#28884 ref(integrations): Don't fetch done statuses twice
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/issues.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/vsts/issues.py
  tests/sentry/integrations/jira_server/__init__.py
  tests/sentry/integrations/jira_server/test_integration.py
  tests/sentry/integrations/jira_server/test_search.py
  tests/sentry/integrations/jira_server/test_webhooks.py
  tests/sentry/integrations/jira_server/testutils.py
  tests/sentry/integrations/vsts/test_issues.py
Labels: Component: Notifications, Team: Ecosystem

#28659 feat(alert-rules): Properly save alert rules with UI components
  src/sentry/api/endpoints/project_rule_details.py
  src/sentry/api/endpoints/project_rules.py
  src/sentry/api/endpoints/project_rules_configuration.py
  src/sentry/api/serializers/models/sentry_app_component.py
  src/sentry/constants.py
  src/sentry/mediators/alert_rule_actions/__init__.py
  src/sentry/mediators/alert_rule_actions/creator.py
  src/sentry/rules/actions/notify_event_sentry_app.py
  src/sentry/rules/actions/notify_event_service.py
  tests/sentry/api/endpoints/test_project_rule_details.py
  tests/sentry/api/endpoints/test_project_rules.py
  tests/sentry/api/endpoints/test_project_rules_configuration.py
  tests/sentry/rules/actions/test_notify_event_sentry_app.py
Labels: Component: Integrations, Team: Ecosystem

#28971 feat(notifications): Parsed Versions
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/templates/sentry/emails/activity/release.html
  src/sentry/templates/sentry/emails/activity/release.txt
  src/sentry/web/frontend/debug/debug_new_release_email.py
  tests/acceptance/test_emails.py
  tests/fixtures/emails/release.txt
  tests/sentry/notifications/test_notifications.py
Labels: Component: Notifications, Team: Ecosystem

#28906 feat(integrations): Make `sync_status_inbound` a Task
  src/sentry/integrations/issues.py
  src/sentry/tasks/integrations.py
  tests/sentry/integrations/jira/test_webhooks.py
  tests/sentry/integrations/jira_server/test_webhooks.py
  tests/sentry/integrations/test_issues.py
  tests/sentry/integrations/vsts/test_webhooks.py
Labels: Component: Integrations, Team: Ecosystem

#28764 feat(alert-rules): Append new alert rule payload for issue alerts w/ ui components
  src/sentry/rules/actions/notify_event_sentry_app.py
  src/sentry/tasks/sentry_apps.py
  static/app/views/organizationIntegrations/sentryAppExternalForm.tsx
  tests/js/spec/views/alerts/issueRuleEditor/ruleNode.spec.jsx
  tests/js/spec/views/alerts/issueRuleEditor/sentryAppRuleModal.spec.jsx
  tests/sentry/rules/actions/test_notify_event_sentry_app.py
  tests/sentry/tasks/test_sentry_apps.py
Labels: Component: Integrations, Team: Ecosystem

#28672 Revert "feat(dev): Upgrade kafka and zookeeper to support Apple M1 (#…
  .github/actions/setup-sentry/action.yml
  src/sentry/conf/server.py
Labels: Component: Developer Environment

#28614 ref(utils): Split `email` utils into files
  src/sentry/security/emails.py
  src/sentry/security/utils.py
  src/sentry/utils/__init__.py
  src/sentry/utils/email.py
  src/sentry/utils/email/__init__.py
  src/sentry/utils/email/address.py
  src/sentry/utils/email/backend.py
  src/sentry/utils/email/faker.py
  src/sentry/utils/email/list_resolver.py
  src/sentry/utils/email/manager.py
  src/sentry/utils/email/message_builder.py
  src/sentry/utils/email/send.py
  src/sentry/utils/email/signer.py
  src/sentry/web/forms/fields.py
  tests/sentry/api/endpoints/test_user_authenticator_details.py
  tests/sentry/api/endpoints/test_user_authenticator_enroll.py
  tests/sentry/models/test_organization.py
  tests/sentry/security/__init__.py
  tests/sentry/security/test_utils.py
  tests/sentry/utils/email/test_address.py
  tests/sentry/utils/email/test_backend.py
  tests/sentry/utils/email/test_list_resolver.py
  tests/sentry/utils/email/test_message_builder.py
  tests/sentry/utils/email/test_send_mail.py
Labels: Team: Ecosystem

#29052 ref(teamwork): Shadow deprecate teamwork plugin
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/endpoints/organization_plugins_configs.py
  src/sentry/api/endpoints/project_plugin_details.py
  src/sentry/api/serializers/models/plugin.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/web/frontend/group_plugin_action.py
  static/app/views/settings/project/navigationConfiguration.tsx
  tests/sentry/api/endpoints/test_project_plugin_details.py
Labels: Component: Integrations, Team: Ecosystem

#28781 ref(slack): Utils Directory
  mypy.ini
  src/sentry/integrations/msteams/utils.py
  src/sentry/integrations/slack/__init__.py
  src/sentry/integrations/slack/endpoints/action.py
  src/sentry/integrations/slack/endpoints/command.py
  src/sentry/integrations/slack/endpoints/event.py
  src/sentry/integrations/slack/integration.py
  src/sentry/integrations/slack/requests/__init__.py
  src/sentry/integrations/slack/requests/base.py
  src/sentry/integrations/slack/requests/command.py
  src/sentry/integrations/slack/requests/event.py
  src/sentry/integrations/slack/tasks.py
  src/sentry/integrations/slack/unfurl/discover.py
  src/sentry/integrations/slack/util/__init__.py
  src/sentry/integrations/slack/utils.py
  src/sentry/integrations/slack/utils/__init__.py
  src/sentry/integrations/slack/utils/auth.py
  src/sentry/integrations/slack/utils/channel.py
  src/sentry/integrations/slack/utils/notifications.py
  src/sentry/integrations/slack/utils/users.py
  src/sentry/integrations/slack/views/__init__.py
  src/sentry/integrations/slack/views/link_identity.py
  src/sentry/integrations/slack/views/link_team.py
  src/sentry/integrations/slack/views/unlink_identity.py
  src/sentry/integrations/slack/views/unlink_team.py
  src/sentry/integrations/utils/__init__.py
  src/sentry/models/externalactor.py
  src/sentry/models/organizationmember.py
  src/sentry/models/team.py
  src/sentry/utils/urls.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_serializers.py
  tests/sentry/incidents/test_subscription_processor.py
  tests/sentry/integrations/slack/endpoints/test_commands.py
  tests/sentry/integrations/slack/test_integration.py
  tests/sentry/integrations/slack/test_message_builder.py
  tests/sentry/integrations/slack/test_requests.py
  tests/sentry/integrations/slack/test_tasks.py
  tests/sentry/integrations/slack/test_utils.py
  tests/sentry/utils/test_urls.py
Labels: Component: Integrations, Team: Ecosystem

#29102 ref(lint): Fix typos
  src/sentry/api/endpoints/event_file_committers.py
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/endpoints/organization_code_mappings.py
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/api/endpoints/organization_events_trends.py
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/endpoints/project_stacktrace_link.py
  src/sentry/auth/providers/saml2/forms.py
  src/sentry/conf/server.py
  src/sentry/db/models/fields/array.py
  src/sentry/db/postgres/creation.py
  src/sentry/demo/data_population.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/subscription_processor.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/models/grouphistory.py
  src/sentry/models/groupmeta.py
  src/sentry/runner/commands/devserver.py
  src/sentry/search/events/base.py
  src/sentry/search/snuba/executors.py
  src/sentry/sentry_metrics/indexer/indexer_consumer.py
  src/sentry/snuba/discover.py
  src/sentry/snuba/sessions.py
  src/sentry/stacktraces/processing.py
  src/sentry/testutils/factories.py
  src/sentry/utils/batching_kafka_consumer.py
  src/sentry/utils/jwt.py
  src/sentry/utils/kvstore/cache.py
  src/sentry/utils/snuba.py
  src/sentry/web/frontend/debug/debug_codeowners_request_mail.py
Labels: Team: Ecosystem

#29084 feat(dev): Use newer kafka & zookeeper images to support Apple arm64
  .github/actions/setup-sentry/action.yml
  src/sentry/conf/server.py
Labels: Component: Developer Environment

#29117 Revert "fix(dev): Use full path for Kafka container (#28724)"
  src/sentry/conf/server.py
Labels: Component: Developer Environment

#29582 fix(jira): Only use CDN verification if key_id is presented
  src/sentry/integrations/atlassian_connect.py
  src/sentry/integrations/jira/installed.py
  tests/sentry/integrations/jira/test_installed.py
  tests/sentry/integrations/jira/test_uninstalled.py
Labels: Component: Integrations, Team: Ecosystem

#29658 feat(ci): Optimizations for dev env workflow
  .github/actions/setup-python/action.yml
  .github/workflows/development-environment.yml
  .github/workflows/python-deps.yml
  scripts/lib.sh
Labels: Component: CI

#29678 ref(types): Use python 3.8 types in `sentry.notifications`
  src/sentry/digests/notifications.py
  src/sentry/digests/utilities.py
  src/sentry/mail/notifications.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/manager.py
  src/sentry/notifications/notifications/activity/assigned.py
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/notifications/activity/new_processing_issues.py
  src/sentry/notifications/notifications/activity/note.py
  src/sentry/notifications/notifications/activity/regression.py
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/notifications/activity/resolved.py
  src/sentry/notifications/notifications/activity/resolved_in_release.py
  src/sentry/notifications/notifications/activity/unassigned.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/digest.py
  src/sentry/notifications/notifications/organization_request.py
  src/sentry/notifications/notifications/rules.py
  src/sentry/notifications/notifications/user_report.py
  src/sentry/notifications/notify.py
  src/sentry/notifications/utils/digest.py
  src/sentry/notifications/utils/legacy_mappings.py
  src/sentry/notifications/utils/participants.py
Labels: Component: Notifications, Team: Ecosystem

#29680 ref(str): Use f-strings
  src/sentry/digests/backends/redis.py
  src/sentry/digests/notifications.py
  src/sentry/digests/utilities.py
  src/sentry/integrations/bitbucket/integration.py
  src/sentry/integrations/bitbucket/search.py
  src/sentry/integrations/bitbucket_server/client.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/integrations/jira/client.py
  src/sentry/integrations/pagerduty/integration.py
  src/sentry/integrations/slack/unfurl/discover.py
  src/sentry/integrations/vercel/integration.py
  src/sentry/integrations/vsts/search.py
  src/sentry/tasks/digests.py
Labels: Team: Ecosystem
