Repository getsentry/sentry, pull requests merged in 2021-02, with the labels that each got.

#23615 build(pre-commit): Add shellcheck pre-commit
  .github/file-filters.yml
  .pre-commit-config.yaml
Labels: Component: Developer Environment

#23691 build(pre-commit): Only run ShellCheck checks on files under scripts
  .pre-commit-config.yaml
  scripts/bump-version.sh
  scripts/ensure-venv.sh
  scripts/post-release.sh
Labels: Component: Developer Environment

#23688 ci(feature): Cache Brew files and use Catalina instead of Big Sur
  .github/workflows/development-environment.yml
  Brewfile
Labels: Component: Developer Environment

#23625 build(vscode): Recommend ShellCheck extension for VS Code
  .vscode/extensions.json
Labels: Component: Developer Environment

#23730 build(ci): Add Yarn cache to development environment workflow
  .github/workflows/development-environment.yml
Labels: Component: Developer Environment

#23002 build(dev): Add libxslt to Brewfile
  Brewfile
Labels: Component: Developer Environment

#23596 google upgrade, take 2
  .github/workflows/development-environment.yml
  Makefile
  docker/Dockerfile
  requirements-base.txt
  src/sentry/filestore/gcs.py
  src/sentry/utils/pytest/sentry.py
Labels: Do Not Merge

#23732 ci: Remove Brew cache
  .github/workflows/development-environment.yml
Labels: Component: Developer Environment

#23775 build(fix): Do not restrict using latest version of pip
  Makefile
Labels: Component: Developer Environment

#23628 build(pyenv) - Fully configure pyenv to work
  .github/workflows/development-environment.yml
  Makefile
  scripts/pyenv_setup.sh
Labels: Component: Developer Environment

#23797 build(ci): Create backend build changes file filter and include Makefile
  .github/file-filters.yml
Labels: Component: Developer Environment

#23703 ci(dev_env): Test development environment on Big Sur and Ubuntu
  .github/workflows/development-environment.yml
Labels: Component: Developer Environment

#23840 build(ci): make install-py-dev to install wheel
  Makefile
  scripts/pyenv_setup.sh
Labels: Component: Developer Environment

#23795 build(ci): CI and local dev should upgrade pip the same way
  .github/actions/setup-pip/action.yml
  .github/workflows/acceptance.yml
  .github/workflows/api-docs-test.yml
  .github/workflows/backend-lint.yml
  .github/workflows/backend-test.yml
  .github/workflows/development-environment.yml
  .github/workflows/snuba-integration-test.yml
  Makefile
  scripts/pyenv_setup.sh
Labels: Component: Developer Environment

#23951 ci: Do not use yarn eslint against yml file
  .github/file-filters.yml
Labels: Component: Developer Environment

#23679 ref(js): Use `fetch` in API client
  src/sentry/static/sentry/app/__mocks__/api.tsx
  src/sentry/static/sentry/app/api.tsx
  src/sentry/static/sentry/app/bootstrap.tsx
  src/sentry/static/sentry/app/utils/ajaxCsrfSetup.tsx
  tests/js/spec/api.spec.jsx
Labels: Status: Accepted

#23954 ci: Rectify pip version being pinned
  Makefile
Labels: Component: Developer Environment

#23939 build(ci): Upgrade GH runners to Ubuntu 20
  .github/workflows/acceptance.yml
  .github/workflows/api-docs-test.yml
  .github/workflows/backend-lint.yml
  .github/workflows/backend-test.yml
  .github/workflows/check-if-migration-is-required.yml
  .github/workflows/command-line-test.yml
  .github/workflows/getsentry-dispatch.yml
  .github/workflows/js-build-and-lint.yml
  .github/workflows/migrations.yml
  .github/workflows/plugins-test.yml
  .github/workflows/relay-integration-test.yml
  .github/workflows/sentry-pull-request-bot.yml
  .github/workflows/snuba-integration-test.yml
  .github/workflows/symbolicator-integration-test.yml
  .github/workflows/visual-diff.yml
Labels: Component: Developer Environment

#23891 build(dev_env): Use SYSTEM_VERSION_COMPAT for old versions of pip in Big Sur
  Makefile
  scripts/lib.sh
  scripts/pyenv_setup.sh
  scripts/python.sh
Labels: Component: Developer Environment

#24000 ref(codeowners): Update on_delete for FK in ProjectCodeOwners table
  migrations_lockfile.txt
  src/sentry/deletions/defaults/project.py
  src/sentry/migrations/0164_add_protect_on_delete_codeowners.py
  src/sentry/models/projectcodeowners.py
Labels: Impact: Migration

#23300 chore: add #23197 squash commit to git blame ignore
  .git-blame-ignore-revs
Labels: Status: Stale

#24095 dev_env(feat): Support getsentry calling scripts within sentry
  Makefile
  scripts/bootstrap-py3-venv
  scripts/python.sh
Labels: Component: Developer Environment

#24005 build(dev_env): Exact version match for Python base requirements
  requirements-base.txt
Labels: Component: Developer Environment
