Repository getsentry/sentry, pull requests merged in 2021-03, with the labels that each got.

#24127 ci(feat): Workflow to prevent modified migrations
  .github/file-filters.yml
  .github/workflows/migrations.yml
Labels: Component: CI

#24309 build: Update python-dateutil
  requirements-base.txt
Labels: Component: Developer Environment

#24182 direnv(feat): Report direnv issues
  .envrc
Labels: Component: Developer Environment

#24402 dev_env(feat): Notify engineers how to get pyenv configured correctly
  .envrc
Labels: Component: Developer Environment

#24457 dev_env(clean_up): Remove BIG_SUR block from Makefile
  Makefile
Labels: Component: Developer Environment

#23240 perf(ui): Lazy load react-date-range
  src/sentry/static/sentry/app/components/organizations/timeRangeSelector/dateRange/dateRangeWrapper.tsx
  src/sentry/static/sentry/app/components/organizations/timeRangeSelector/dateRange/index.tsx
  src/sentry/static/sentry/app/components/organizations/timeRangeSelector/index.tsx
  src/sentry/static/sentry/app/views/settings/components/forms/calendarField.tsx
  src/sentry/static/sentry/app/views/settings/components/forms/datePickerField.tsx
  tests/js/spec/components/organizations/timeRangeSelector/dateRange.spec.jsx
Labels: Status: Accepted

#24431 direnv(feat): Report "guided steps" as well as errors
  .envrc
Labels: Component: Developer Environment

#24432 feat(codeowners): Always trace CodeOwners related endpoints
  src/sentry/utils/sdk.py
Labels: Team: Ecosystem

#24504 ref(codeowners): Merge feature flags into 1 flag
  src/sentry/api/endpoints/external_team.py
  src/sentry/api/endpoints/external_user.py
  src/sentry/api/endpoints/project_codeowners.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/endpoints/test_external_team.py
  tests/sentry/api/endpoints/test_external_team_details.py
  tests/sentry/api/endpoints/test_external_user.py
  tests/sentry/api/endpoints/test_external_user_details.py
  tests/sentry/api/endpoints/test_project_codeowners.py
  tests/sentry/api/endpoints/test_project_codeowners_details.py
Labels: Team: Ecosystem

#24394 ci(feat): Test various Python versions
  .github/workflows/python-versions.yml
  requirements-base.txt
Labels: Component: Developer Environment

#24403 dev_env(fix): Delete log file generated by direnv
  .envrc
Labels: Component: Developer Environment

#24475 feat(workflow): Add support to filter alerts by name
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
Labels: WIP

#24405 feat(integrations): Dual Write Notification Preferences
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/api/endpoints/user_notification_fine_tuning.py
  src/sentry/api/serializers/models/group.py
  src/sentry/api/serializers/models/user_notifications.py
  src/sentry/mail/activity/release.py
  src/sentry/models/groupsubscription.py
  src/sentry/models/notificationsetting.py
  src/sentry/models/useroption.py
  src/sentry/notifications/__init__.py
  src/sentry/notifications/legacy_mappings.py
  src/sentry/notifications/manager.py
  src/sentry/notifications/types.py
  src/sentry/trash/__init__.py
  tests/sentry/api/endpoints/test_user_notification_details.py
  tests/sentry/api/serializers/test_group.py
  tests/sentry/mail/activity/test_release.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/models/test_groupsubscription.py
  tests/snuba/api/serializers/test_group.py
Labels: Component: Notifications, Team: Ecosystem

#24258 ref(integrations): Dual Write Usages
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/api/endpoints/user_notification_fine_tuning.py
  src/sentry/api/serializers/models/user_notifications.py
  src/sentry/models/groupsubscription.py
  src/sentry/models/project.py
  src/sentry/models/user.py
  src/sentry/models/useroption.py
  src/sentry/notifications/manager.py
  src/sentry/web/frontend/accounts.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/api/endpoints/test_user_notification_details.py
  tests/sentry/api/endpoints/test_user_notification_fine_tuning.py
  tests/sentry/api/serializers/test_group.py
  tests/sentry/incidents/test_action_handlers.py
  tests/sentry/mail/activity/test_release.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/models/test_groupsubscription.py
  tests/sentry/models/test_project.py
  tests/snuba/api/serializers/test_group.py
Labels: Component: Notifications, Team: Ecosystem

#24009 test(js): fix up empty jest snapshot renders
  src/sentry/static/sentry/app/components/avatar/actorAvatar.tsx
  tests/js/spec/components/avatar/actorAvatar.spec.jsx
  tests/js/spec/components/externalLink.spec.jsx
  tests/js/spec/components/globalModal.spec.jsx
  tests/js/spec/components/modals/diffModal.spec.jsx
  tests/js/spec/components/sidebar/index.spec.jsx
  tests/js/spec/components/toolbarHeader.spec.jsx
Labels: Status: In Progress

#24512 sentry_runner(feat): Report development issues
  .envrc
  src/sentry/runner/__init__.py
Labels: Component: Developer Environment

#24630 fix(ui): Show right issue stats based on filter parameters
  src/sentry/static/sentry/app/components/stream/group.tsx
Labels: Team: Workflow

#24449 feat(notification platform): Copy UserOptions to NotificationSettings
  migrations_lockfile.txt
  src/sentry/migrations/0181_copy_useroptions_to_notificationsettings.py
Labels: Component: Notifications, Do Not Merge, Team: Ecosystem

#24627 ref(tests): DRY mock_uuid classes
  src/sentry/testutils/cases.py
  tests/sentry/analytics/test_event.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_organization_repository_details.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/api/endpoints/test_project_rules.py
  tests/sentry/api/endpoints/test_project_transfer.py
  tests/sentry/api/endpoints/test_team_details.py
  tests/sentry/db/test_mixin.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_index.py
  tests/sentry/integrations/vercel/test_integration.py
  tests/sentry_plugins/amazon_sqs/test_plugin.py
  tests/snuba/api/endpoints/test_organization_group_index.py
  tests/snuba/api/endpoints/test_project_group_index.py
Labels: Team: Ecosystem

#24629 fix(alerts): Fix incident fetch on alert details change
  src/sentry/static/sentry/app/views/alerts/rules/details/index.tsx
Labels: Team: Workflow

#24409 feat(codeowners): Evaluate CodeOwner rules alongside IssuerOwner rules
  src/sentry/models/projectcodeowners.py
  src/sentry/models/projectownership.py
  tests/sentry/models/test_projectownership.py
Labels: Team: Ecosystem

#24681 direnv(feat): Support GNU and BSD mktemp
  .envrc
Labels: Component: Developer Environment

#24628 ref(tests): Clean up tests with get_valid_response
  src/sentry/testutils/asserts.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_api_authorizations.py
  tests/sentry/api/endpoints/test_organization_index.py
  tests/sentry/api/endpoints/test_organization_projects.py
  tests/sentry/api/endpoints/test_organization_teams.py
  tests/sentry/api/endpoints/test_organization_user_details.py
  tests/sentry/api/endpoints/test_organization_user_teams.py
  tests/sentry/api/endpoints/test_project_filter_details.py
  tests/sentry/api/endpoints/test_project_filters.py
  tests/sentry/api/endpoints/test_project_index.py
  tests/sentry/api/endpoints/test_project_team_details.py
  tests/sentry/api/endpoints/test_project_teams.py
  tests/sentry/api/endpoints/test_project_user_details.py
  tests/sentry/api/endpoints/test_team_details.py
  tests/sentry/api/endpoints/test_user_emails_confirm.py
  tests/sentry/api/endpoints/test_user_identity_details.py
  tests/sentry/api/endpoints/test_user_index.py
  tests/sentry/api/endpoints/test_user_ips.py
  tests/sentry/api/endpoints/test_user_organizations.py
  tests/sentry/api/endpoints/test_user_password.py
  tests/sentry/api/endpoints/test_user_social_identities_index.py
  tests/sentry/api/endpoints/test_user_social_identity_details.py
  tests/sentry/api/endpoints/test_user_subscriptions.py
  tests/snuba/api/endpoints/test_project_tags.py
Labels: Team: Ecosystem

#24682 ref(codeowners): Do not create dummy issue owner record
  src/sentry/api/endpoints/project_codeowners.py
  tests/sentry/api/endpoints/test_project_codeowners.py
Labels: Team: Ecosystem

#24085 feat(alerts): Add incident activity to alert rule details
  src/sentry/api/serializers/models/incident.py
  src/sentry/incidents/endpoints/organization_incident_index.py
  src/sentry/static/sentry/app/views/alerts/rules/details/body.tsx
  src/sentry/static/sentry/app/views/alerts/rules/details/metricChart.tsx
  src/sentry/static/sentry/app/views/alerts/rules/details/timeline.tsx
  src/sentry/static/sentry/app/views/alerts/types.tsx
  src/sentry/static/sentry/app/views/alerts/utils/index.tsx
  tests/sentry/incidents/endpoints/test_organization_incident_details.py
Labels: Team: Workflow

#24532 build(feat): Report make develop errors to Sentry.io
  .github/workflows/development-environment.yml
  Makefile
  scripts/do.sh
  scripts/lib.sh
  scripts/python.sh
Labels: Component: Developer Environment

#24758 fix(notifications): Fix Dual Write
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/notifications/legacy_mappings.py
Labels: Component: Notifications, Team: Ecosystem

#24750 fix(notifications): Notification Settings as Strings
  src/sentry/api/serializers/models/user_notifications.py
  src/sentry/static/sentry/app/views/settings/account/accountNotificationFineTuning.tsx
  src/sentry/static/sentry/app/views/settings/account/notifications/fields.tsx
  tests/sentry/api/endpoints/test_user_notification_fine_tuning.py
Labels: Component: Notifications, Team: Ecosystem

#23325 test(symbolication): Add tests for DIF candidates
  tests/symbolicator/snapshots/SymbolicatorResolvingIntegrationTest/test_resolving_with_candidates_sentry_source.pysnap
  tests/symbolicator/test_payload_full.py
Labels: Status: In Progress, Status: Stale

#24540 build(feat): More make targets reporting to Sentry.io
  Makefile
  scripts/do.sh
  scripts/lib.sh
  scripts/pyenv_setup.sh
Labels: Component: Developer Environment

#24762 fix(migrations): Fix NotificationSettings
  src/sentry/migrations/0183_copy_useroptions_to_notificationsettings_2.py
Labels: Component: Notifications, Team: Ecosystem

#24360 feat(integrations): Bulk Remove Settings
  src/sentry/api/endpoints/organization_group_index.py
  src/sentry/deletions/defaults/organization.py
  src/sentry/interfaces/stacktrace.py
  src/sentry/mail/activity/new_processing_issues.py
  src/sentry/mail/adapter.py
  src/sentry/management/commands/check_notifications.py
  src/sentry/models/groupsubscription.py
  src/sentry/models/organization.py
  src/sentry/models/project.py
  src/sentry/models/team.py
  src/sentry/models/user.py
  src/sentry/notifications/legacy_mappings.py
  src/sentry/notifications/manager.py
  src/sentry/notifications/notify.py
  src/sentry/plugins/bases/notify.py
  src/sentry/utils/email.py
  tests/sentry/api/endpoints/test_user_notification_details.py
  tests/sentry/api/endpoints/test_user_notification_fine_tuning.py
  tests/sentry/models/test_groupsubscription.py
  tests/sentry/models/test_notificationsetting.py
Labels: Component: Notifications, Team: Ecosystem

#24694 feat(notifications): Add Reads to NotificationSettingsManager
  mypy.ini
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/api/endpoints/user_notification_fine_tuning.py
  src/sentry/api/serializers/models/user_notifications.py
  src/sentry/models/groupsubscription.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/legacy_mappings.py
  src/sentry/notifications/manager.py
  src/sentry/notifications/notify.py
  tests/sentry/api/endpoints/test_user_notification_details.py
  tests/sentry/api/endpoints/test_user_notification_fine_tuning.py
  tests/sentry/models/test_groupsubscription.py
  tests/symbolicator/test_minidump_full.py
Labels: Component: Notifications, Team: Ecosystem

#24563 build(feat): Make target to initialize Docker & run make bootstrap in CI
  .github/workflows/development-environment.yml
  scripts/lib.sh
Labels: Component: CI, Component: Developer Environment

#24853 ref(tests): Clean Organization Endpoint Tests
  src/sentry/api/urls.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_index.py
  tests/sentry/api/endpoints/test_onboarding.py
  tests/sentry/api/endpoints/test_organization_activity.py
  tests/sentry/api/endpoints/test_organization_api_key_details.py
  tests/sentry/api/endpoints/test_organization_api_key_index.py
  tests/sentry/api/endpoints/test_organization_auditlogs.py
  tests/sentry/api/endpoints/test_organization_auth_providers.py
  tests/sentry/api/endpoints/test_organization_avatar.py
  tests/sentry/api/endpoints/test_organization_config_integrations.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_organization_index.py
  tests/sentry/api/endpoints/test_organization_join_request.py
  tests/sentry/api/endpoints/test_organization_member_details.py
  tests/sentry/api/endpoints/test_organization_monitors.py
  tests/sentry/api/endpoints/test_organization_processingissues.py
Labels: Team: Ecosystem
