Repository getsentry/sentry, pull requests merged in 2022-09, with the labels that each got.

#38375 fix(snowflake): Remove ff for Snowflake for orgs
  src/sentry/models/organization.py
Labels: Scope: Backend

#38380 feat(sampling): Improve experience for unsupported use cases [TET-350]
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/samplingProjectIncompatibleAlert.tsx
  static/app/views/settings/project/server-side-sampling/samplingPromo.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.tsx
  tests/acceptance/test_project_settings_sampling.py
Labels: Scope: Frontend, Scope: Backend

#38362 test(perf): Add more performance issue detection test data
  tests/sentry/utils/performance_issues/events/n-plus-one-in-rails-index-view.json
  tests/sentry/utils/performance_issues/events/no-issue-in-django-detail-view.json
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38385 ref(metrics): Refactor metrics layer tests to their own package
  tests/sentry/snuba/metrics/test_metrics_layer/__init__.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_release_health.py
Labels: Scope: Backend

#38381 feat(sampling): Do not display Specify Client Rate Modal if on new SDK [TET-349]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.tsx
Labels: Scope: Frontend

#38384 feat(sampling): Add already updated projects to the affected array [TET-348]
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.spec.tsx
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.tsx
Labels: Scope: Frontend

#38386 feat(sampling): Make client sample rate modal more inviting
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
Labels: Scope: Frontend

#38296 types(breadcrumb): update crumb
  static/app/types/breadcrumbs.tsx
Labels: Scope: Frontend

#38295 types(menulistitem): use interface
  static/app/components/menuListItem.tsx
  static/app/types/core.tsx
Labels: Scope: Frontend

#38298 fix(types): colorChip
  docs-ui/components/colorChip.tsx
Labels: Scope: Frontend

#37988 chore(discover): Remove deprecated endpoint
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/urls.py
  src/sentry/apidocs/public_exclusion_list.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#38336 fix(replays): 404 if bad replay id
  src/sentry/replays/endpoints/project_replay_recording_segment_details.py
  src/sentry/replays/endpoints/project_replay_recording_segment_index.py
  tests/sentry/replays/test_project_replay_recording_segment_index.py
Labels: Scope: Backend

#38389 feat(perf): Improve permissions and auditing on options endpoint
  src/sentry/api/endpoints/system_options.py
  src/sentry/conf/server.py
  tests/sentry/api/endpoints/test_system_options.py
  tests/sentry/api/endpoints/test_user_permissions_config.py
Labels: Scope: Backend

#38390 fix(replays): Take the saved playback speed options as default when reloading
  static/app/components/replays/replayContext.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#38333 ref(projectSettings): Use <TextCopyInput /> for debug shell command
  static/app/views/settings/project/projectProcessingIssues.tsx
Labels: Scope: Frontend

#38334 fix(replays): Truncate the middle UrlWalker segment when it is not a summary
  static/app/components/replays/walker/chevronDividedList.tsx
  static/app/components/replays/walker/splitCrumbs.tsx
Labels: Scope: Frontend

#38360 feat(performance-issues): Add search fields
  static/app/stores/tagStore.tsx
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#37946 feat: Only show tags tooltip if the tag value overflows the container
  static/app/components/tagsTableRow.tsx
Labels: Scope: Frontend

#38394 ref(js): Remove unused `EventStore`
  static/app/stores/eventStore.tsx
Labels: Scope: Frontend

#38095 fix(replays): Improve console row hovering
  static/app/utils/replays/getBreadcrumb.tsx
  static/app/views/replays/detail/console/consoleMessage.tsx
  static/app/views/replays/detail/console/index.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#38395 ref(js): Remove DebugMetaActions
  static/app/components/events/interfaces/debugMeta/index.tsx
  static/app/components/events/interfaces/frame/line.tsx
  static/app/components/events/interfaces/frame/lineV2/native.tsx
  static/app/components/events/interfaces/frame/lineV2/nativeV2.tsx
  static/app/components/events/interfaces/nativeFrame.tsx
  static/app/stores/debugMetaStore.tsx
Labels: Scope: Frontend

#38396 feat(perf-issues): Add new options to control detection/creation
  src/sentry/options/defaults.py
Labels: Scope: Backend

#38398 ref(stores): Remove duplicate `getStateTags` method
  static/app/components/smartSearchBar/index.spec.jsx
  static/app/stores/tagStore.spec.jsx
  static/app/stores/tagStore.tsx
  static/app/utils/withTags.tsx
  static/app/views/issueList/searchBar.spec.jsx
Labels: Scope: Frontend

#38359 feat(discover): Adds custom performance metrics field and unit meta to events-stats response
  src/sentry/snuba/discover.py
  tests/snuba/api/endpoints/test_organization_events_stats_mep.py
Labels: Scope: Backend

#38388 fix(discover): Fix error.handled not grouping properly
  src/sentry/search/events/datasets/discover.py
  tests/sentry/snuba/test_discover_query.py
  tests/snuba/api/endpoints/test_organization_events.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
Labels: Scope: Backend

#38397 ref(stores): Remove makeSafeRefluxStore from non-listening stores
  static/app/components/actions/resolve.spec.jsx
  static/app/components/assigneeSelector.spec.jsx
  static/app/components/customResolutionModal.spec.jsx
  static/app/components/globalModal/globalModal.spec.jsx
  static/app/components/group/suggestedOwners.spec.jsx
  static/app/components/hook.spec.jsx
  static/app/components/modals/sudoModal.spec.jsx
  static/app/components/organizations/environmentSelector.spec.tsx
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingModal.spec.tsx
  static/app/components/stream/streamGroup.spec.jsx
  static/app/stores/committerStore.tsx
  static/app/stores/configStore.tsx
  static/app/stores/externalIssueStore.tsx
  static/app/stores/formSearchStore.tsx
  static/app/stores/groupStore.tsx
  static/app/stores/groupingStore.spec.jsx
  static/app/stores/groupingStore.tsx
  static/app/stores/hookStore.tsx
  static/app/stores/memberListStore.tsx
  static/app/stores/modalStore.tsx
  static/app/stores/organizationEnvironmentsStore.spec.jsx
  static/app/stores/organizationEnvironmentsStore.tsx
  static/app/stores/preferencesStore.tsx
  static/app/stores/releaseStore.tsx
  static/app/stores/repositoryStore.tsx
  static/app/stores/savedSearchesStore.tsx
  static/app/stores/sdkUpdatesStore.tsx
  static/app/stores/sentryAppComponentsStore.tsx
  static/app/stores/sentryAppInstallationsStore.tsx
  static/app/stores/serverSideSamplingStore.tsx
  static/app/stores/sidebarPanelStore.tsx
  static/app/stores/tagStore.tsx
  static/app/utils/useCommitters.spec.tsx
  static/app/utils/withConfig.spec.jsx
  static/app/utils/withRepositories.spec.jsx
  static/app/utils/withSentryAppComponents.spec.jsx
  static/app/views/admin/installWizard.spec.jsx
  static/app/views/dashboardsV2/dashboard.spec.tsx
  static/app/views/issueList/overview.polling.spec.jsx
  static/app/views/issueList/overview.spec.jsx
  static/app/views/organizationGroupDetails/actions/actions.spec.tsx
  static/app/views/organizationGroupDetails/groupActivity.spec.jsx
  static/app/views/organizationGroupDetails/groupEventDetails/groupEventDetails.spec.tsx
  static/app/views/organizationGroupDetails/groupEventDetails/groupEventDetailsContainer.spec.tsx
  static/app/views/organizationGroupDetails/groupMerged/groupMergedView.spec.jsx
  static/app/views/organizationIntegrations/integrationCodeMappings.spec.jsx
  static/app/views/settings/project/projectOwnership/ownershipInput.spec.jsx
Labels: Scope: Frontend

#38320 chore(features): Remove performance-extraneous-spans-poc
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#38241 chore: Sort reserved organization slugs
  src/sentry/constants.py
Labels: Scope: Backend

#38400 ref(js): Improve form model comments
  static/app/components/forms/model.tsx
Labels: Scope: Frontend

#38402 fix(vercel): Add $schema to vercel.json
  vercel.json
Labels: Scope: Frontend

#38399 test(ui): Remove duplicate ExceptionMechanism test
  static/app/components/events/interfaces/crashContent/exception/mechanism.spec.jsx
Labels: Scope: Frontend

#38316 feat(replays): Upgrade `@sentry/replay` to 0.5.9
  package.json
  yarn.lock
Labels: Scope: Frontend

#38387 fix(teamfilter): account for null onchange
  static/app/views/alerts/list/rules/teamFilter.tsx
Labels: Scope: Frontend

#38340 feat(profiling): use static to determine empty profile
  static/app/components/profiling/FlamegraphWarnings.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/profile/profile.spec.tsx
  static/app/utils/profiling/profile/profile.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#38403 ref(js): Convert ApiForm to a FC
  static/app/components/forms/apiForm.tsx
Labels: Scope: Frontend

#37702 fix(profiling): disable 0 sample threads in selector
  static/app/components/profiling/threadSelector.tsx
Labels: Scope: Frontend, Scope: Backend

#38331 ref(replays): Refactor how we show user name/email/etc to use the displayName field
  static/app/components/replays/header/detailsPageBreadcrumbs.tsx
  static/app/utils/replays/replayDataUtils.tsx
  static/app/views/replays/replayTable.tsx
  static/app/views/replays/types.tsx
Labels: Scope: Frontend

#38410 feat(replays): Add support for querying multiple replays by id
  src/sentry/replays/lib/query.py
  src/sentry/replays/query.py
  tests/sentry/replays/test_organization_replay_index.py
Labels: Scope: Backend

#38369 fix(issues): Remove margin on issues stream graph
  static/app/components/stream/group.tsx
Labels: Scope: Frontend

#38411 fix(docs): point to profiling landing page
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingModal.tsx
Labels: Scope: Frontend

#38246 ref(sampling): Address CR fedback from GH-38236
  static/app/actionCreators/serverSideSampling.tsx
  static/app/stores/serverSideSamplingStore.spec.tsx
  static/app/stores/serverSideSamplingStore.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/samplingBreakdown.spec.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.spec.tsx
Labels: Scope: Frontend

#38300 ref(sessions): Remove deprecated get_filter usage [TET-226]
  src/sentry/release_health/duplex.py
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/base.py
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/sessions.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/sessions_v2.py
  src/sentry/utils/snuba.py
  tests/snuba/api/endpoints/test_organization_sessions.py
  tests/snuba/sessions/test_sessions_v2.py
Labels: Scope: Backend

#38425 fix(event-grouping-information): Fix tooltip's content overflowing - [ISSUE-1582]
  static/app/components/events/groupingInfo/groupingVariant.tsx
  static/app/components/events/interfaces/keyValueList/index.tsx
Labels: Scope: Frontend

#38257 feat(metrics): Add a service interface for the cardinality limiter
  src/sentry/ratelimits/cardinality.py
Labels: Scope: Backend

#38427 fix(autocomplete): Fix values overflowing - [TET-353]
  static/app/components/forms/selectField.tsx
Labels: Scope: Frontend

#38426 feat(sampling): Improve activate toggle [TET-340]
  static/app/views/settings/project/server-side-sampling/rule.spec.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: Scope: Frontend

#38304 ref(utils): Add typing to sentry.utils.hashlib
  mypy.ini
  src/sentry/utils/hashlib.py
Labels: Scope: Backend

#38431 Revert "ref(sessions): Remove deprecated get_filter usage [TET-226]"
  src/sentry/release_health/duplex.py
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/base.py
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/sessions.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/sessions_v2.py
  src/sentry/utils/snuba.py
  tests/snuba/api/endpoints/test_organization_sessions.py
  tests/snuba/sessions/test_sessions_v2.py
Labels: Scope: Backend

#38437 fix(profiling): Handle empty payloads
  src/sentry/profiles/consumer.py
Labels: Scope: Backend

#38430 ref(metrics-indexer): Move FetchTypeExt and Metadata to namedtuple
  src/sentry/sentry_metrics/indexer/base.py
Labels: Scope: Backend

#38440 ref(sampling): Remove skip from acceptance tests - [TET-351]
  tests/acceptance/test_project_settings_sampling.py
Labels: Scope: Backend

#38342 fix(onboarding): check indexed access
  static/app/views/onboarding/targetedOnboarding/onboarding.tsx
Labels: Scope: Frontend

#38444 chore(deps): Bump sentry-sdk to 1.9.8
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#38438 ref(sessions): Remove deprecated get_filter usage [TET-226 TET-354]
  src/sentry/api/endpoints/organization_sessions.py
  src/sentry/release_health/duplex.py
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/base.py
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/semver_and_stage_aliases.py
  src/sentry/search/events/datasets/sessions.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/sessions_v2.py
  src/sentry/utils/snuba.py
  tests/snuba/api/endpoints/test_organization_sessions.py
  tests/snuba/sessions/test_sessions_v2.py
Labels: Scope: Backend

#38432 fix(metrics-indexer): Fix dependency on undefined set iteration order.
  src/sentry/ratelimits/sliding_windows.py
Labels: Scope: Backend

#38451 fix(sessions): Suppress issues sent from invalid search filters
  src/sentry/api/endpoints/organization_sessions.py
  src/sentry/release_health/duplex.py
Labels: Scope: Backend

#38453 feat(sampling): Add more platforms to the allowlist
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
  tests/sentry/api/endpoints/test_organization_dynamic_sampling_sdk_versions.py
Labels: Scope: Backend

#38452 ref(audit-log): log raw dynamic sampling changes - [TET-341]
  src/sentry/api/endpoints/project_details.py
Labels: Scope: Backend

#38412 feat(perf-issues): Add perf-issues options to settings
  static/app/views/admin/adminSettings.tsx
  static/app/views/admin/options.tsx
Labels: Scope: Frontend

#38446 feat(metrics-indexer): Add settings for cardinality limiter [sns-1651]
  src/sentry/conf/server.py
  src/sentry/options/defaults.py
Labels: Scope: Backend

#38459 feat(perf-issues): Add span evidence section
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/performance/index.tsx
Labels: Scope: Frontend

#38458 ref(perf-issues): Also use new option rate for detection
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38370 feat(replays): Record analytics on replay details pageload
  static/app/utils/analytics/replayAnalyticsEvents.tsx
  static/app/utils/analytics/trackAdvancedAnalyticsEvent.tsx
  static/app/utils/replays/hooks/useReplayLayout.tsx
  static/app/utils/replays/hooks/useReplayPageview.tsx
  static/app/utils/replays/hooks/useSplitPanelTracking.tsx
  static/app/utils/replays/hooks/useTimeout.tsx
  static/app/views/replays/detail/layout/splitPanel.tsx
  static/app/views/replays/details.tsx
  static/app/views/replays/replayTable.tsx
Labels: Scope: Frontend

#38448 fix(replays): Html snippets highlighting
  static/app/components/htmlCode.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#38308 feat(perf-issues) Integrate detection into save transaction pipeline
  src/sentry/event_manager.py
  src/sentry/models/group.py
  src/sentry/tasks/store.py
  src/sentry/types/issues.py
  src/sentry/utils/performance_issues/performance_detection.py
  src/sentry/utils/performance_issues/performance_span_issue.py
  tests/sentry/api/test_issue_search.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38278 feat: Support events and transactions topics being on seperate clusters
  src/sentry/eventstream/kafka/backend.py
  tests/snuba/eventstream/test_eventstream.py
Labels: Scope: Backend

#38357 ref(smartSearchBar): Use <Overlay />
  static/app/components/smartSearchBar/searchBarDatePicker.tsx
  static/app/components/smartSearchBar/searchBarFlyout.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
Labels: Scope: Frontend

#38365 ref(issues): Convert IssueListActions to FC
  static/app/stores/selectedGroupStore.tsx
  static/app/views/issueList/actions.spec.jsx
  static/app/views/issueList/actions/index.tsx
  static/app/views/issueList/overview.polling.spec.jsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#38165 feat(replays): Add filters to Network Table
  static/app/views/replays/detail/domMutations/index.tsx
  static/app/views/replays/detail/network/index.tsx
  static/app/views/replays/detail/network/utils.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#38361 fix: Load query sets to avoid pickling for async function
  src/sentry/models/team.py
  src/sentry/notifications/notifications/activity/release.py
Labels: Scope: Backend

#38424 ref(hybrid): Adapt silo scripts to getsentry
  scripts/silo/add_silo_decorators.py
  scripts/silo/audit_silo_decorators.py
  scripts/silo/decorate_models_by_relation.py
  scripts/silo/decorate_unit_tests.py
  src/sentry/utils/silo/__init__.py
  src/sentry/utils/silo/add_silo_decorators.py
  src/sentry/utils/silo/audit_silo_decorators.py
  src/sentry/utils/silo/common.py
  src/sentry/utils/silo/decorate_models_by_relation.py
  src/sentry/utils/silo/decorate_unit_tests.py
Labels: Scope: Backend

#38285 ref(ui): Allow title to be used for tooltips in ActionLink
  static/app/components/actions/actionLink.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
  static/app/components/events/interfaces/debugMeta/debugImageDetails/candidate/actions.tsx
  static/app/components/integrationExternalMappings.tsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/issueList/actions/reviewAction.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/projectDebugFiles/sources/customRepositories/actions.tsx
Labels: Scope: Frontend

#38470 feat(perf-issues): Add perf issue creation rate option
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/serializers/models/project.py
  src/sentry/projectoptions/defaults.py
Labels: Scope: Backend

#38472 feat(perf-issues): Issue creation project option UI
  static/app/components/forms/controls/rangeSlider/index.tsx
  static/app/views/settings/projectPerformance/projectPerformance.spec.jsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#38373 feat(perf issues): Add type and category to serializer
  src/sentry/api/serializers/models/group.py
  tests/snuba/api/endpoints/test_group_details.py
Labels: Scope: Backend

#38471 fix(textareaControl): Allow react-autosize-textarea to freely control the height
  static/app/components/forms/controls/textarea.tsx
Labels: Scope: Frontend

#38480 types(perf-issues): Add frontend types for issue category and type
  static/app/types/group.tsx
Labels: Scope: Frontend

#38481 fix(replays): decompress whole file instead of chunking
  src/sentry/replays/endpoints/project_replay_recording_segment_index.py
Labels: Scope: Backend

#38485 fix(dashboards): Fix missing feature flag checks in dashboards
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/widgetCard/index.tsx
Labels: Scope: Frontend

#38469 refs(event_manager): Change `EventManager` jobs to have a list of groups rather than a single group
  src/sentry/event_manager.py
  tests/sentry/event_manager/test_hierarchical_hashes.py
  tests/sentry/event_manager/test_save_aggregate.py
Labels: Scope: Backend

#38482 chore(analytics) : convert discover analytics
  static/app/utils/analytics/discoverAnalyticsEvents.tsx
  static/app/views/eventsV2/banner.tsx
  static/app/views/eventsV2/landing.tsx
  static/app/views/eventsV2/queryList.tsx
  static/app/views/eventsV2/table/columnEditCollection.tsx
  static/app/views/eventsV2/tags.tsx
Labels: Scope: Frontend

#38143 feat(perf_issues): Add `GroupEvent` and split some functionality in `Event` into a base class.
  src/sentry/eventstore/models.py
  src/sentry/eventstream/snuba.py
  tests/sentry/eventstore/test_models.py
  tests/snuba/eventstream/test_eventstream.py
Labels: Scope: Backend

#38393 fix(replays): Fix query for replays on issues details
  static/app/views/organizationGroupDetails/groupDetails.tsx
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.tsx
  static/app/views/organizationGroupDetails/groupReplays/index.tsx
  static/app/views/organizationGroupDetails/header.tsx
Labels: Scope: Frontend

#38422 feat(apidocs): Added the framework for schema tests
  tests/sentry/apidocs/__init__.py
  tests/sentry/apidocs/test_schema.py
Labels: Scope: Backend

#38504 fix(sampling): Update stepper to show 3/3
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
Labels: Scope: Frontend

#38506 chore(sampling): Add analytics to the specify client rate modal
  static/app/utils/analytics/samplingAnalyticsEvents.tsx
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.tsx
Labels: Scope: Frontend

#38379 feat(platforms): Add Svelte as a platform (Backend)
  src/sentry/utils/platform_categories.py
Labels: Scope: Backend

#37909 feat(platforms): Add Svelte as a platform
  fixtures/integration-docs/_platforms.json
  fixtures/integration-docs/javascript-svelte.json
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/data/platformCategories.tsx
Labels: Scope: Frontend

#38510 fix(shared-issue): Add Organization Context Provider to shared page as the content is using useOrganization
  static/app/views/sharedGroupDetails/index.tsx
Labels: Scope: Frontend

#38255 ref: use internal pypi
  .github/actions/setup-sentry/action.yml
  .github/workflows/backend.yml
  .github/workflows/development-environment.yml
  Brewfile
  docker/Dockerfile
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-dev-only-frozen.txt
  requirements-dev.txt
  requirements-frozen.txt
  scripts/lib.sh
  setup.py
  tools/freeze_requirements.py
  tools/lint_requirements.py
Labels: Scope: Backend

#38493 chore(replays): remove custom rls on segment index details
  src/sentry/replays/endpoints/project_replay_recording_segment_details.py
Labels: Scope: Backend

#38494 feat: Upgrade sentry-replay to 0.5.11
  package.json
  yarn.lock
Labels: Scope: Frontend

#38372 feat(perf-issues): Add N+1 DB Span detector
  src/sentry/models/group.py
  src/sentry/types/issues.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38299 types(charts): remove instance getter
  static/app/types/echarts.tsx
Labels: Scope: Frontend

#38429 ref: Move new cardinality limiter to namedtuples [sns-1651]
  src/sentry/ratelimits/cardinality.py
Labels: Scope: Backend

#38420 feat(replays): Add support for OR and AND conditions
  src/sentry/replays/lib/query.py
  tests/sentry/replays/test_organization_replay_index.py
Labels: Scope: Backend

#38518 feat(perf-issues): Add 'issueSupports' helper
  static/app/types/group.tsx
  static/app/utils/groupCapabilities.tsx
Labels: Scope: Frontend

#38498 feat(performance_issues): Add rate limiter for performance issue creation
  src/sentry/conf/server.py
  src/sentry/event_manager.py
Labels: Scope: Backend

#38512 ref(perf-issue): Remodel span evidence section
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/performance/index.tsx
  static/app/components/events/interfaces/spans/embeddedSpanTree.tsx
  static/app/types/event.tsx
  static/app/views/organizationGroupDetails/eventToolbar.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
Labels: Scope: Frontend

#38505 red(breadcrumbs): Add timezone to the time tooltip
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/time/utils.tsx
Labels: Scope: Frontend

#38507 ref(time-range-format-function): Update the logic to display trailing zero after the decimal point
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/events/interfaces/spans/utils.spec.tsx
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/views/performance/traceDetails/transactionDetail.tsx
Labels: Scope: Frontend

#38288 feat(hybrid): Scripts for silo mode decorators
  mypy.ini
  scripts/silo/__init__.py
  scripts/silo/add_silo_decorators.py
  scripts/silo/all_decorators.sh
  scripts/silo/audit_silo_decorators.py
  scripts/silo/decorate_models_by_relation.py
  scripts/silo/decorate_unit_tests.py
  src/sentry/conf/server.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/silo.py
  src/sentry/utils/silo/__init__.py
  src/sentry/utils/silo/add_silo_decorators.py
  src/sentry/utils/silo/audit_silo_decorators.py
  src/sentry/utils/silo/common.py
  src/sentry/utils/silo/decorate_models_by_relation.py
  src/sentry/utils/silo/decorate_unit_tests.py
  tests/sentry/test_silo.py
Labels: Scope: Backend

#38464 feat(profiling): resolve project and org ids
  static/app/components/profiling/FrameStack/profileDetails.tsx
  static/app/stores/organizationsStore.tsx
Labels: Scope: Frontend

#38516 fix(dashboards): Fixes orderby getting lost for issue widgets when editing
  static/app/views/dashboardsV2/widgetBuilder/utils.tsx
Labels: Scope: Frontend

#38522 feat(dashboards): allow opening Custom Perf Metric widgets in discover
  static/app/views/dashboardsV2/widgetCard/widgetCard.spec.tsx
  static/app/views/dashboardsV2/widgetCard/widgetCardContextMenu.tsx
Labels: Scope: Frontend

#37802 feat(indexer-spanner): Implementation of core api's
  src/sentry/sentry_metrics/indexer/cloudspanner/cloudspanner.py
  src/sentry/sentry_metrics/indexer/cloudspanner/cloudspanner_model.py
  tests/sentry/sentry_metrics/test_cloudspanner.py
Labels: Scope: Backend

#38499 ref(js): Remove useless GroupCheckBox
  static/app/components/stream/group.tsx
  static/app/components/stream/groupCheckBox.tsx
Labels: Scope: Frontend

#38488 ref(perf-issues): Disable delete and discard & delete options in perf issues
  static/app/types/group.tsx
  static/app/views/organizationGroupDetails/actions/actions.spec.tsx
  static/app/views/organizationGroupDetails/actions/index.tsx
  static/app/views/organizationGroupDetails/groupDetails.spec.jsx
Labels: Scope: Frontend

#38364 fix(issues): Apply tint only when marking reviewed
  static/app/components/stream/group.tsx
  static/app/components/stream/streamGroup.spec.jsx
Labels: Scope: Frontend

#38327 ref(orgSettings): Use <TextCopyInput /> to display member invite link
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
Labels: Scope: Frontend

#38527 feat(perf-issues): Add settings endpoint for detector options
  src/sentry/api/endpoints/project_performance_issue_settings.py
  src/sentry/api/urls.py
  src/sentry/projectoptions/defaults.py
  tests/sentry/api/endpoints/test_project_performance_issue_settings.py
Labels: Scope: Backend

#38486 feat(discover): Event detail page context menu for custom perf metrics
  static/app/components/events/eventCustomPerformanceMetrics.spec.tsx
  static/app/components/events/eventCustomPerformanceMetrics.tsx
  static/app/views/performance/transactionDetails/content.tsx
Labels: Scope: Frontend

#38274 feat(perf issues): Return prev/next for transaction events
  src/sentry/api/endpoints/project_event_details.py
  src/sentry/api/serializers/models/event.py
  src/sentry/eventstore/models.py
  src/sentry/eventstore/snuba/backend.py
  tests/sentry/eventstore/snuba/test_backend.py
  tests/snuba/api/endpoints/test_project_event_details.py
Labels: Scope: Backend

#38530 ref(perf issues): Update search syntax
  src/sentry/api/issue_search.py
  src/sentry/api/serializers/models/group.py
  src/sentry/search/snuba/backend.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#38513 fix(replays): Sorting null and undefined values in the Network Table
  static/app/views/replays/detail/network/utils.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#38533 fix(selectedGroupStore): Correct shift behavior for unselect
  static/app/stores/selectedGroupStore.spec.tsx
  static/app/stores/selectedGroupStore.tsx
Labels: Scope: Frontend

#38496 fix(replays): Fix replay query on the Transaction/Replays list page
  static/app/utils/replays/fetchReplayList.tsx
  static/app/utils/replays/hooks/useReplayList.tsx
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.tsx
  static/app/views/performance/transactionSummary/transactionReplays/content.tsx
  static/app/views/performance/transactionSummary/transactionReplays/index.tsx
  static/app/views/performance/transactionSummary/transactionReplays/useReplaysFromTransaction.tsx
  static/app/views/replays/replays.tsx
Labels: Scope: Frontend

#38537 ref(ui): Simplify GroupLevel tooltip
  static/app/components/eventOrGroupHeader.tsx
Labels: Scope: Frontend

#38538 ref(issues): Remove data section borders
  static/app/components/clippedBox.tsx
  static/app/components/events/eventDataSection.tsx
  static/app/components/events/eventTagsAndScreenshot/index.tsx
  static/app/components/events/styles.tsx
  static/app/views/organizationGroupDetails/groupEventDetails/groupEventDetails.tsx
  static/less/group-detail.less
Labels: Scope: Frontend

#38528 feat(perf-issues): Detector settings UI
  static/app/components/forms/type.tsx
  static/app/views/settings/projectPerformance/projectPerformance.spec.jsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#38489 feat(eventstream): Add `kafka.send-project-transactions-to-new-topic` option
  src/sentry/options/defaults.py
Labels: Scope: Backend

#38541 ref(issues): Standardize header styles
  static/app/components/events/eventDataSection.tsx
  static/app/components/events/styles.tsx
Labels: Scope: Frontend

#38319 feat(perf-issues) Update perf group creation
  src/sentry/event_manager.py
  src/sentry/models/group.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/performance_issues/test_performance_issues.py
  tests/sentry/utils/performance_issues/events/n-plus-one-in-django-index-view.json
Labels: Scope: Backend

#38543 fix(copy): tags tooltip copy
  static/app/components/events/eventTagsAndScreenshot/tags.tsx
Labels: Scope: Frontend

#38162 feat(perf-issues): retrieve seen_stats for transaction/performance data
  src/sentry/api/serializers/models/group.py
  src/sentry/api/serializers/models/group_stream.py
  src/sentry/snuba/referrer.py
  src/sentry/tagstore/base.py
  src/sentry/tagstore/snuba/backend.py
  tests/sentry/api/serializers/test_group.py
  tests/sentry/api/serializers/test_group_stream.py
  tests/snuba/tagstore/test_tagstore_backend.py
Labels: Scope: Backend

#38374 feat(perf-issues): add performance-issue support to the GroupDetails endpoint
  src/sentry/api/endpoints/group_details.py
  src/sentry/tsdb/base.py
  src/sentry/tsdb/snuba.py
  tests/snuba/tsdb/test_tsdb_backend.py
Labels: Scope: Backend

#38509 feat(metrics): Support field aliasing on metrics layer [TET-322 TET-356]
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/naming_layer/mapping.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/metrics/query_builder.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/snuba/metrics/fields/test_base.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_release_health.py
  tests/sentry/snuba/metrics/test_query_builder.py
Labels: Scope: Backend

#38556 fix(perf-issues): detect using all db spans
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/events/n-plus-one-in-django-index-view-activerecord.json
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38558 feat(metrics): Adds aliasing behaviour to GroupBy [TET-357 TET-320]
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/metrics/query_builder.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_query.py
  tests/sentry/snuba/metrics/test_query_builder.py
Labels: Scope: Backend

#38562 Revert "fix(perf-issues): Only consider select queries for N+1 detector (#38554)
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/events/n-plus-one-in-django-new-view-updates.json
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38567 feat(dashboards): Widget Viewer Custom Perf Metrics dont disable open in discover button
  static/app/components/modals/widgetViewerModal.spec.tsx
  static/app/components/modals/widgetViewerModal.tsx
Labels: Scope: Frontend

#38557 fix(perf-issues): Use repeating query as N+1 issue description
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/performance_issues/test_performance_issues.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#38565 ref(metrics): Adds extra test for aliasing
  tests/sentry/snuba/metrics/test_metrics_layer/test_release_health.py
Labels: Scope: Backend

#38483 feat(issue-stream): Disable merge and delete actions when performance issues are selected
  fixtures/js-stubs/group.js
  static/app/types/group.tsx
  static/app/views/issueList/actions.spec.jsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/issueList/actions/reviewAction.tsx
  static/app/views/organizationGroupDetails/actions/index.tsx
Labels: Scope: Frontend

#38545 fix(ui): Set cursor default for disabled menu items
  static/app/components/menuListItem.tsx
Labels: Scope: Frontend

#38570 feat(issue_search): Allow issue search to run only on Postgres
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/search/snuba/executors.py
  tests/snuba/api/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#38569 fix(perf-issues): Add space between performance issue type and description
  src/sentry/event_manager.py
  tests/sentry/performance_issues/test_performance_issues.py
Labels: Scope: Backend

#38560 fix(strictclick): fix crash
  static/app/components/strictClick.tsx
Labels: Scope: Frontend

#38544 ref(debugFiles): Get input padding from theme
  static/app/components/modals/debugFileCustomRepository/http.tsx
Labels: Scope: Frontend

#38539 feat(ui): Support 'unknown' level
  static/app/components/eventOrGroupHeader.tsx
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/types/event.tsx
  static/app/utils/theme.tsx
Labels: Scope: Frontend

#38534 feat(superuser): Require u2f on superuser access form BE
  src/sentry/api/endpoints/auth_index.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/web/client_config.py
  tests/sentry/api/endpoints/test_auth_index.py
Labels: Scope: Backend

#38540 ref(perf-issues): Disable ignore dropdown options
  static/app/components/actions/ignore.spec.jsx
  static/app/components/actions/ignore.tsx
  static/app/components/customIgnoreCountModal.tsx
  static/app/utils/groupCapabilities.tsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/organizationGroupDetails/actions/index.tsx
Labels: Scope: Frontend

#38487 feat(eventstream): Support moving events by project ID to new transactions topic
  src/sentry/conf/server.py
  src/sentry/eventstream/kafka/backend.py
  src/sentry/killswitches.py
  tests/snuba/eventstream/test_eventstream.py
Labels: Scope: Backend

#38582 ref(ui): Remove trash StyledErrorLevel
  static/app/components/events/eventMessage.tsx
Labels: Scope: Frontend

#38455 fix(metrics): Fix startup crash in parallel indexer [sns-1490]
  src/sentry/sentry_metrics/consumers/indexer/processing.py
  tests/sentry/sentry_metrics/test_parallel_indexer.py
Labels: Scope: Backend

#38585 ref(ui): Fix performance issues check for group details header
  static/app/views/organizationGroupDetails/header.tsx
Labels: Scope: Frontend

#38586 ref(js): Improve group capability checking fn name
  static/app/utils/groupCapabilities.tsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/organizationGroupDetails/actions/index.tsx
Labels: Scope: Frontend

#38579 ref(inputStyles): Mark as deprecated
  static/app/styles/deprecatedInput.tsx
Labels: Scope: Frontend

#38587 ref(js): Minor code cleanup
  static/app/views/organizationGroupDetails/header.tsx
Labels: Scope: Frontend

#38590 fix(perf-issues): Correct capability checking in group actions
  static/app/views/organizationGroupDetails/actions/index.tsx
Labels: Scope: Frontend
