Repository getsentry/sentry, pull requests merged in 2022-08, with the labels that each got.

#37253 fix: Remove unused metric [INGEST-1380]
  src/sentry/sentry_metrics/consumers/indexer/batch.py
Labels: Scope: Backend

#37286 fix(sampling): tagValueAutocomplete not being reloaded - [TET-295]
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/tagValueAutocomplete.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.spec.tsx
Labels: Scope: Frontend

#37288 fix(stack-trace-header): Render 'raw' option for all platforms
  static/app/components/events/traceEventDataSection.tsx
  tests/js/spec/components/events/interfaces/threadsV2.spec.tsx
Labels: Scope: Frontend

#37173 feat(metrics_indexer): Add writes limiter + fixes to sliding windows rate limiter [INGEST-1380]
  src/sentry/conf/server.py
  src/sentry/options/defaults.py
  src/sentry/ratelimits/sliding_windows.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/indexer/ratelimiters.py
  tests/sentry/ratelimits/test_sliding_windows.py
  tests/sentry/sentry_metrics/test_ratelimiters.py
Labels: Scope: Backend

#37271 ref(dropdownMenuItem): Fix exhaustive-deps lint warning
  static/app/components/dropdownMenuItemV2.tsx
Labels: Scope: Frontend

#37189 ref(replays): Compatibility layer between v0 events and v1 replay api
  static/app/components/performance/waterfall/utils.tsx
  static/app/components/replays/breadcrumbs/gridlines.tsx
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx
  static/app/components/replays/breadcrumbs/replayTimelineSpans.tsx
  static/app/components/replays/header/detailsPageBreadcrumbs.tsx
  static/app/components/replays/player/scrubber.tsx
  static/app/components/replays/player/scrubberMouseTracking.tsx
  static/app/components/replays/playerRelativeTime.tsx
  static/app/components/replays/replayController.tsx
  static/app/components/replays/replayCurrentUrl.tsx
  static/app/components/replays/utils.tsx
  static/app/components/replays/walker/splitCrumbs.tsx
  static/app/components/replays/walker/urlWalker.tsx
  static/app/utils/replays/getCurrentUrl.tsx
  static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx
  static/app/utils/replays/replayDataUtils.tsx
  static/app/utils/replays/replayReader.tsx
  static/app/views/replays/detail/breadcrumbs/breadcrumbItem.tsx
  static/app/views/replays/detail/breadcrumbs/index.tsx
  static/app/views/replays/detail/console/consoleMessage.tsx
  static/app/views/replays/detail/console/index.tsx
  static/app/views/replays/detail/domMutations/index.tsx
  static/app/views/replays/detail/eventMetaData.tsx
  static/app/views/replays/detail/focusArea.tsx
  static/app/views/replays/detail/memoryChart.tsx
  static/app/views/replays/detail/network/index.tsx
  static/app/views/replays/detail/page.tsx
  static/app/views/replays/detail/tagPanel.tsx
  static/app/views/replays/detail/trace.tsx
  static/app/views/replays/details.tsx
  static/app/views/replays/types.tsx
  tests/js/spec/components/replays/utils.spec.tsx
  tests/js/spec/utils/replays/getCurrentUrl.spec.tsx
  tests/js/spec/utils/replays/replayDataUtils.spec.tsx
Labels: Scope: Frontend

#37296 fix(replays): Do duration calculation in the correct order
  static/app/utils/replays/replayReader.tsx
Labels: Scope: Frontend

#37258 ref(notifications): Add provider argument to notification methods
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/integrations/slack/message_builder/notifications/base.py
  src/sentry/integrations/slack/notifications.py
  src/sentry/notifications/notifications/activity/assigned.py
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/notifications/activity/new_processing_issues.py
  src/sentry/notifications/notifications/activity/note.py
  src/sentry/notifications/notifications/activity/regression.py
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/notifications/activity/release_summary.py
  src/sentry/notifications/notifications/activity/resolved_in_release.py
  src/sentry/notifications/notifications/activity/unassigned.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/digest.py
  src/sentry/notifications/notifications/integration_nudge.py
  src/sentry/notifications/notifications/organization_request/abstract_invite_request.py
  src/sentry/notifications/notifications/organization_request/base.py
  src/sentry/notifications/notifications/organization_request/integration_request.py
  src/sentry/notifications/notifications/organization_request/invite_request.py
  src/sentry/notifications/notifications/organization_request/join_request.py
  src/sentry/notifications/notifications/rules.py
  src/sentry/notifications/notifications/strategies/role_based_recipient_strategy.py
  src/sentry/notifications/notifications/user_report.py
  src/sentry/testutils/helpers/notifications.py
  tests/sentry/integrations/slack/notifications/test_assigned.py
  tests/sentry/mail/activity/test_release_summary.py
Labels: Scope: Backend

#37289 ref: upgrade flake8 to 5.0.2
  requirements-dev-frozen.txt
  requirements-dev-only-frozen.txt
  requirements-dev.txt
  setup.cfg
Labels: Scope: Backend

#37285 ref: upgrade mistune to 2.0.4
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#37162 ref(replays): change consumers to use segment_id header
  src/sentry/conf/server.py
  src/sentry/replays/consumers/recording/process_recording.py
  src/sentry/replays/consumers/recording/types.py
  src/sentry/replays/endpoints/project_replay_recording_segment_details.py
  src/sentry/replays/endpoints/project_replay_recording_segment_index.py
  src/sentry/replays/migrations/0002_rename_to_segment_id.py
  src/sentry/replays/models.py
  src/sentry/replays/serializers.py
  tests/sentry/replays/consumers/recording_consumer/test_consumer.py
  tests/sentry/replays/test_project_replay_recording_segment_details.py
  tests/sentry/replays/test_project_replay_recording_segment_index.py
Labels: Scope: Backend

#37074 ref(notifications): Get title link based on provider
  src/sentry/integrations/message_builder.py
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/integrations/slack/message_builder/notifications/base.py
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/notifications/activity/new_processing_issues.py
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/notifications/activity/release_summary.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/digest.py
  src/sentry/notifications/notifications/integration_nudge.py
  src/sentry/notifications/notifications/organization_request/base.py
Labels: Scope: Backend

#37209 fix(ui): Preserve labels on Sentry App alert rule actions select fields
  static/app/components/forms/selectAsyncField.tsx
  static/app/views/organizationIntegrations/sentryAppExternalForm.tsx
  tests/js/spec/views/alerts/issueRules/sentryAppRuleModal.spec.jsx
Labels: Scope: Frontend

#37305 feat(replays): new replays table column
  static/app/components/replays/replayHighlight.tsx
  static/app/views/replays/replayTable.tsx
  static/app/views/replays/replays.tsx
  static/app/views/replays/types.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#36481 feat(search): Filter descriptions and keywords alongside the field key
  static/app/components/smartSearchBar/index.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
  static/app/components/smartSearchBar/utils.tsx
  static/app/utils/fields/index.ts
  tests/js/spec/components/events/searchBar.spec.jsx
  tests/js/spec/components/smartSearchBar/index.spec.jsx
  tests/js/spec/components/smartSearchBar/utils.spec.tsx
Labels: Scope: Frontend

#36933 feat(msteams): Add notifications message builder
  src/sentry/integrations/msteams/card_builder/block.py
  src/sentry/integrations/msteams/card_builder/issues.py
  src/sentry/integrations/msteams/card_builder/notifications.py
  src/sentry/testutils/helpers/notifications.py
  tests/sentry/integrations/msteams/test_message_builder.py
Labels: Scope: Backend

#37039 feat(msteams): Add personal notifications
  src/sentry/api/bases/external_actor.py
  src/sentry/integrations/msteams/__init__.py
  src/sentry/integrations/msteams/notifications.py
  src/sentry/integrations/msteams/utils.py
  src/sentry/models/notificationsetting.py
  src/sentry/notifications/defaults.py
  src/sentry/notifications/helpers.py
  src/sentry/testutils/cases.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  tests/sentry/integrations/msteams/notifications/test_note.py
  tests/sentry/integrations/msteams/test_notifications.py
  tests/sentry/notifications/test_utils.py
  tests/sentry/notifications/utils/test_get_fallback_settings.py
  tests/sentry/notifications/utils/test_get_setting_mapping_from_mapping.py
Labels: Scope: Backend

#37322 feat(alerts): Pass dataset for metrics performance alerts
  static/app/views/alerts/rules/metric/details/metricChart.tsx
Labels: Scope: Frontend

#37324 test(ui): Convert group activity to RTL
  tests/js/spec/views/organizationGroupDetails/groupActivity.spec.jsx
Labels: Scope: Frontend

#37293 feat(sampling): Increase max hour events [TET-238]
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToSampleRates.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToSampleRates.spec.tsx
Labels: Scope: Frontend

#37281 ref(tests): Do not set up database unnecessarily
  tests/sentry/sentry_metrics/test_base_indexer.py
  tests/sentry/sentry_metrics/test_postgres_indexer.py
Labels: Scope: Backend

#37335 fix(stack-trace-header): Full stack trace toggle not enabled
  static/app/components/events/traceEventDataSection.tsx
Labels: Scope: Frontend

#37251 feat(sampling): Add specify client modal - [TET-279]
  static/app/utils/analytics/samplingAnalyticsEvents.tsx
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToSeries.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
Labels: Scope: Frontend

#37171 feat(metrics_indexer): Make string IDs returned by indexer nullable, handle them [INGEST-1380]
  src/sentry/conf/server.py
  src/sentry/options/defaults.py
  src/sentry/ratelimits/sliding_windows.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/sentry_metrics/indexer/base.py
  src/sentry/sentry_metrics/indexer/mock.py
  src/sentry/sentry_metrics/indexer/postgres_v2.py
  src/sentry/sentry_metrics/indexer/ratelimiters.py
  tests/sentry/ratelimits/test_sliding_windows.py
  tests/sentry/sentry_metrics/test_batch.py
  tests/sentry/sentry_metrics/test_multiprocess_steps.py
  tests/sentry/sentry_metrics/test_ratelimiters.py
Labels: Scope: Backend

#37337 feat(sampling): Add 10% steps to the sample rate inputs [TET-305]
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/specifyClientRateModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
Labels: Scope: Frontend

#37280 feat(sampling): Add specify current client sample rate unit test - [TET-279]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/specifyClientRateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToSeries.spec.tsx
Labels: Scope: Frontend

#37340 feat(perf): Add option for performance detection
  src/sentry/options/defaults.py
Labels: Scope: Backend

#37339 ref(message-interface): Replace getMeta (proxy) with _meta object - [TET-144]
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/message.tsx
  tests/js/spec/components/events/interfaces/message.spec.tsx
Labels: Scope: Frontend

#37198 feat(dashboards): Replace dashboard-custom-measurement-widgets feature flag in frontend
  static/app/utils/customMeasurements/customMeasurementsProvider.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/eventsV2/eventDetails/content.tsx
  static/app/views/performance/transactionDetails/content.tsx
  tests/js/spec/utils/useCustomMeasurements.spec.tsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
Labels: Scope: Frontend

#37329 test(ui): Convert screenshot tests to RTL
  tests/js/spec/views/accountAuthorization.spec.jsx
  tests/js/spec/views/accountSubscriptions.spec.jsx
  tests/js/spec/views/settings/organizationApiKeyDetailsView.spec.jsx
Labels: Scope: Frontend

#37186 feat(profiling): Allow selection of function types
  static/app/utils/profiling/hooks/useFunctions.tsx
  static/app/views/profiling/profileSummary/content.tsx
  tests/js/spec/utils/profiling/hooks/useFunctions.spec.tsx
Labels: Scope: Frontend

#37069 feat(profiling): Add proxy to profiling stats endpoint
  src/sentry/api/endpoints/organization_profiling_profiles.py
  src/sentry/api/endpoints/project_profiling_profile.py
  src/sentry/api/urls.py
  src/sentry/utils/profiling.py
Labels: Scope: Backend

#37262 feat(ui): Change API request exceptions to use `cause` property
  static/app/api.tsx
  static/app/utils/requestError/createRequestError.tsx
  static/app/utils/requestError/requestError.tsx
Labels: Scope: Frontend

#37342 feat(perf): Add perf issue (only detection) to ingest
  src/sentry/tasks/performance_detection.py
  src/sentry/tasks/store.py
  tests/sentry/tasks/test_performance_detection.py
Labels: Scope: Backend

#37341 feat(mep): Add UI to handle metrics rollout
  static/app/components/smartSearchBar/index.tsx
  static/app/utils/discover/eventView.tsx
  static/app/utils/discover/genericDiscoverQuery.tsx
  static/app/utils/performance/contexts/metricsEnhancedSetting.tsx
  static/app/views/performance/content.tsx
  static/app/views/performance/landing/index.tsx
  static/app/views/performance/landing/metricsDataSwitcher.tsx
  static/app/views/performance/landing/metricsDataSwitcherAlert.tsx
  static/app/views/performance/landing/views/backendView.tsx
  static/app/views/performance/landing/views/frontendOtherView.tsx
  static/app/views/performance/landing/views/frontendPageloadView.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.tsx
  static/app/views/performance/landing/widgets/utils.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  static/app/views/performance/table.tsx
  static/app/views/performance/utils.tsx
  tests/js/sentry-test/performance/initializePerformanceData.ts
  tests/js/spec/views/performance/landing/index.spec.tsx
  tests/js/spec/views/performance/landing/metricsDataSwitcher.spec.tsx
  tests/js/spec/views/performance/landing/widgets/widgetContainer.spec.tsx
  tests/js/spec/views/performance/table.spec.tsx
Labels: Scope: Frontend

#37331 test(ui): Convert bulk controller to RTL
  tests/js/spec/components/bulkController/bulkNotice.spec.jsx
  tests/js/spec/components/bulkController/index.spec.tsx
Labels: Scope: Frontend

#37351 ref: re-enable codecov with `continue-on-error` and frozen
  .github/actions/artifacts/action.yml
  tools/pin_github_action.py
Labels: Scope: Backend

#37299 ref(replays): Use `<ReplaysFeatureBadge />` in all the places
  static/app/components/replays/header/detailsPageBreadcrumbs.tsx
  static/app/components/replays/replaysFeatureBadge.tsx
  static/app/views/organizationGroupDetails/header.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/replays/replays.tsx
Labels: Scope: Frontend

#37356 feat(mobile-events): remove unused has mobile events endpoint
  src/sentry/api/endpoints/organization_has_mobile_app_events.py
  src/sentry/api/urls.py
  src/sentry/apidocs/public_exclusion_list.py
  tests/sentry/api/endpoints/test_organization_has_mobile_app_events.py
Labels: Scope: Backend

#37313 Sentry Functions: Webhooks Migrations
  migrations_lockfile.txt
  src/sentry/api/endpoints/organization_sentry_function.py
  src/sentry/api/serializers/models/sentry_function.py
  src/sentry/migrations/0310_sentry_functions_add_webhooks.py
  src/sentry/models/sentryfunction.py
Labels: Scope: Backend

#37357 feat(alerts): remove default action experiment
  static/app/data/experimentConfig.tsx
  static/app/types/hooks.tsx
  static/app/views/alerts/rules/issue/index.tsx
Labels: Scope: Frontend

#37287 feat(profiling): persist layout preferences in storage
  static/app/components/profiling/FrameStack/frameStack.tsx
  static/app/components/profiling/profilingFlamechartLayout.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphPreferences.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/index.tsx
  static/app/views/profiling/profileFlamegraph.tsx
Labels: Scope: Frontend

#37291 feat(profiling): set selected border on zoomed frame
  static/app/components/profiling/FrameStack/frameStackContextMenu.tsx
  static/app/components/profiling/FrameStack/frameStackTable.tsx
Labels: Scope: Frontend

#37292 feat(profiling): set min width for table
  static/app/components/profiling/profilingFlamechartLayout.tsx
Labels: Scope: Frontend

#37261 fix(SCIM): Exclude SCIM enabled orgs from delete_expired
  src/sentry/models/organizationmember.py
  tests/sentry/models/test_organizationmember.py
Labels: Scope: Backend

#37367 ref: Add comment about assumption currently made by eventstream
  src/sentry/eventstream/kafka/backend.py
Labels: Scope: Backend

#37306 fix(profiling): use state for canvas bounds
  static/app/components/profiling/flamegraph.tsx
Labels: Scope: Frontend

#37220 feat(msteams): Assigned and unassigned activity notifications
  src/sentry/integrations/msteams/card_builder/notifications.py
  src/sentry/integrations/msteams/notifications.py
  tests/sentry/integrations/msteams/notifications/test_assigned.py
  tests/sentry/integrations/msteams/notifications/test_unassigned.py
Labels: Scope: Backend

#37360 fix(profiling): Retry the request if vroom returns a bad gateway error
  src/sentry/utils/profiling.py
Labels: Scope: Backend

#37267 feat(discover): Metrics Query Builder always query 90 days for metrics when constructing custom_measurement_map
  src/sentry/search/events/builder.py
  tests/snuba/api/endpoints/test_organization_events_stats_mep.py
Labels: Scope: Backend

#37301 feat(auditlog): Remove versioning from endpoint
  src/sentry/api/endpoints/organization_auditlogs.py
  tests/sentry/api/endpoints/test_organization_auditlogs.py
Labels: Scope: Backend

#37323 feat(active-release): separate out active release notification away from issue alerts
  src/sentry/analytics/events/active_release_notification_sent.py
  src/sentry/api/endpoints/project_agnostic_rule_conditions.py
  src/sentry/api/endpoints/project_rules_configuration.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/mail/actions.py
  src/sentry/mail/adapter.py
  src/sentry/mail/notifications.py
  src/sentry/notifications/notifications/active_release.py
  src/sentry/notifications/notifications/rules.py
  src/sentry/notifications/utils/participants.py
  src/sentry/plugins/bases/notify.py
  src/sentry/rules/processor.py
  tests/sentry/integrations/slack/notifications/test_active_release.py
  tests/sentry/integrations/slack/test_message_builder.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/rules/test_processor.py
Labels: Scope: Backend

#37371 fix(dashboard-filters): Fix manage page params not triggering redirect
  static/app/views/dashboardsV2/orgDashboards.tsx
  tests/js/spec/views/dashboardsV2/orgDashboards.spec.tsx
Labels: Scope: Frontend

#37235 fix(releases): block the creation of Releases with empty version
  src/sentry/event_manager.py
  src/sentry/models/release.py
  src/sentry/receivers/releases.py
  src/sentry/release_health/tasks.py
  tests/sentry/api/endpoints/test_organization_releases.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/models/test_release.py
Labels: Scope: Backend

#37373 fix(replays): Adjust Replay list table columns in Issue Summary and Transaction Summary
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.tsx
  static/app/views/performance/transactionSummary/transactionReplays/content.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#37275 fix(mep): Remove threshold from mep config
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#37065 fix(mep): User misery renderer
  static/app/components/userMisery.tsx
Labels: Scope: Frontend

#37381 feat(mep): Rename sampled to indexed
  static/app/views/dashboardsV2/widgetCard/widgetCardContextMenu.tsx
  tests/js/spec/views/dashboardsV2/widgetCard.spec.tsx
Labels: Scope: Frontend

#37297 feat(replays): Render DOM Events as a list
  static/app/views/replays/detail/domMutations/index.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#36167 feat(notifications): Add notification settings option for msteams
  static/app/components/forms/selectField.tsx
  static/app/views/settings/account/notifications/constants.tsx
  static/app/views/settings/account/notifications/fields2.tsx
  static/app/views/settings/account/notifications/notificationSettingsByType.tsx
  static/app/views/settings/account/notifications/utils.tsx
  tests/js/spec/utils/settings/notifications/backfill.spec.tsx
  tests/js/spec/utils/settings/notifications/testUtils.spec.tsx
  tests/js/spec/views/settings/account/notifications/notificationSettingsByType.spec.tsx
Labels: Scope: Frontend

#37320 ref(issues): Revert padding changes to DataSection
  static/app/components/events/eventEntries.tsx
  static/app/components/events/styles.tsx
  static/app/views/organizationGroupDetails/eventToolbar.tsx
Labels: Scope: Frontend

#37219 ref(calendar): Extract date pickers into reusable components
  docs-ui/stories/components/calendar.stories.js
  static/app/components/calendar/calendarStylesWrapper.tsx
  static/app/components/calendar/datePicker.tsx
  static/app/components/calendar/dateRangePicker.tsx
  static/app/components/calendar/index.tsx
  static/app/components/forms/datePickerField.tsx
  static/app/components/organizations/timeRangeSelector/dateRange/index.tsx
Labels: Scope: Frontend

#37363 feat(dashboard): Fetch releases on filter
  static/app/utils/releases/releasesProvider.tsx
  static/app/views/dashboardsV2/releasesSelectControl.tsx
  tests/js/spec/views/dashboardsV2/releasesSelectControl.spec.tsx
Labels: Scope: Frontend

#36749 feat(msteams): Allow personal installation for Sentry for MS Teams
  src/sentry/integrations/msteams/actions/notification.py
  src/sentry/integrations/msteams/card_builder/installation.py
  src/sentry/integrations/msteams/card_builder/utils.py
  src/sentry/integrations/msteams/integration.py
  src/sentry/integrations/msteams/webhook.py
  tests/sentry/integrations/msteams/test_integration.py
  tests/sentry/integrations/msteams/test_message_builder.py
  tests/sentry/integrations/msteams/test_webhook.py
Labels: Scope: Frontend, Scope: Backend

#36988 ref: upgrade grpcio to a version which is built for 3.10
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#37312 Sentry Functions: Frontend Webhook Integration
  static/app/types/integrations.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryFunctionDetails.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryFunctionSubscriptions.tsx
Labels: Scope: Frontend

#37302 ref(replay): Use CompactSelect for ChooseLayout dropdown
  static/app/views/replays/detail/layout/chooseLayout.tsx
Labels: Scope: Frontend

#37396 fix(active-release): Return list releases from suspect-releases
  src/sentry/api/endpoints/group_suspect_releases.py
  tests/sentry/api/endpoints/test_group_suspect_releases.py
Labels: Scope: Backend

#37080 ref(styles): Use 14px font size for body element
  static/app/components/breadcrumbs.tsx
  static/app/components/eventOrGroupTitle.tsx
  static/app/components/scoreCard.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/less/base.less
Labels: Scope: Frontend

#37309 feat(active-release): Add suspect releases to issue details
  static/app/components/group/seenInfo.tsx
  static/app/components/group/sidebar.tsx
  static/app/components/group/suspectReleases.tsx
  tests/js/spec/components/group/suspectReleases.spec.jsx
Labels: Scope: Frontend

#37310 ref(dropdownControl): Remove V1
  docs-ui/stories/components/dropdownControl.stories.js
  static/app/components/actions/ignore.tsx
  static/app/components/actions/resolve.tsx
  static/app/components/dropdownButton.tsx
  static/app/components/dropdownButtonV2.tsx
  static/app/components/dropdownControl.tsx
  static/app/components/dropdownMenuControl.tsx
  static/app/components/dropdownMenuItem.tsx
  static/app/components/dropdownMenuSection.tsx
  static/app/components/dropdownMenuV2.tsx
  static/app/components/environmentPageFilter.tsx
  static/app/components/events/interfaces/searchBarAction.tsx
  static/app/components/forms/compactSelect.tsx
  static/app/components/organizations/pageFilterBar.tsx
  static/app/components/performanceOnboarding/sidebar.tsx
  static/app/components/projectPageFilter.tsx
  static/app/views/alerts/list/rules/row.tsx
  static/app/views/dashboardsV2/manage/dashboardList.tsx
  static/app/views/dashboardsV2/widgetCard/widgetCardContextMenu.tsx
  static/app/views/eventsV2/queryList.tsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/issueList/savedSearchTab.tsx
  static/app/views/organizationGroupDetails/actions/index.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.tsx
  static/app/views/performance/vitalDetail/vitalDetailContent.tsx
  static/app/views/releases/detail/header/releaseActions.tsx
  tests/acceptance/test_organization_dashboards.py
Labels: Scope: Frontend, Scope: Backend

#37401 fix(perf): Fix perf issue detection
  src/sentry/tasks/performance_detection.py
  tests/sentry/tasks/test_performance_detection.py
Labels: Scope: Backend

#37402 fix(msteams): Handle special characters
  src/sentry/integrations/msteams/card_builder/block.py
  src/sentry/integrations/msteams/card_builder/utils.py
  tests/sentry/integrations/msteams/notifications/test_assigned.py
  tests/sentry/integrations/msteams/notifications/test_note.py
  tests/sentry/integrations/msteams/notifications/test_unassigned.py
  tests/sentry/integrations/msteams/test_message_builder.py
Labels: Scope: Backend

#37023 fix(hybrid-cloud): Do not bork at subdomain middleware if the host name is not RFC 1034/1035 compliant
  src/sentry/middleware/subdomain.py
  tests/sentry/middleware/test_subdomain.py
Labels: Scope: Backend

#37349 ref(extra-data): Replace getMeta (proxy) with _meta object - [TET-144]
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventExtraData/eventDataContent.tsx
  static/app/components/events/eventExtraData/getEventExtraDataKnownData.tsx
  static/app/components/events/eventExtraData/index.tsx
  tests/js/spec/components/events/eventExtraData.spec.tsx
Labels: Scope: Frontend

#37330 feat(metrics): Bring back computed measurements [INGEST-1531]
  src/sentry/relay/config/__init__.py
  src/sentry/sentry_metrics/indexer/strings.py
  src/sentry/snuba/metrics/naming_layer/mri.py
  tests/relay_integration/test_metrics_extraction.py
  tests/sentry/relay/snapshots/test_config/test_project_config_with_breakdown/with_metrics.pysnap
Labels: Scope: Backend

#37338 feat(sampling): Transaction breakdown loader
  static/app/views/settings/project/server-side-sampling/samplingBreakdown.tsx
Labels: Scope: Frontend

#37352 feat(profiling): Add endpoint to proxy raw_profile request to the vroom service
  src/sentry/api/endpoints/project_profiling_profile.py
  src/sentry/api/urls.py
  src/sentry/apidocs/public_exclusion_list.py
Labels: Scope: Backend

#37174 feat(metrics_indexer): Wire up the writes limiter to postgres [INGEST-1380]
  src/sentry/sentry_metrics/indexer/postgres_v2.py
  tests/sentry/sentry_metrics/test_postgres_indexer.py
Labels: Scope: Backend

#32802 feat(runner): Add staff and superadmin argument for create user
  src/sentry/runner/commands/createuser.py
Labels: Status: In Progress, Scope: Backend

#36703 ref(poc): composition
  static/app/components/events/interfaces/exceptionV2.tsx
  static/app/components/events/interfaces/stackTraceV2.tsx
  static/app/components/events/interfaces/threads/index.tsx
  static/app/components/events/interfaces/threadsV2.tsx
  static/app/components/events/traceEventDataSection.tsx
Labels: Scope: Frontend

#37372 feat(js): Add React ErrorBoundary componentStack to errors
  static/app/components/errorBoundary.tsx
Labels: Scope: Frontend

#37344 ref(csp-interface): Replace getMeta (proxy) with _meta object - [TET-144]
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/csp/content.tsx
  static/app/components/events/interfaces/csp/help/index.tsx
  static/app/components/events/interfaces/csp/index.tsx
  tests/js/spec/components/events/interfaces/csp.spec.tsx
Labels: Scope: Frontend

#37298 ref(profiling): flamegraph -> flamechart
  static/app/components/profiling/FrameStack/frameStackContextMenu.tsx
  static/app/components/profiling/breadcrumb.tsx
  static/app/components/profiling/functionsTable.tsx
  static/app/components/profiling/legacyFunctionsTable.tsx
  static/app/components/profiling/profileHeader.tsx
  static/app/routes.tsx
  static/app/utils/profiling/routes.tsx
  static/app/views/performance/transactionDetails/transactionToProfileButton.tsx
  static/app/views/profiling/landing/profilingScatterChart.tsx
  static/app/views/profiling/profileDetails.tsx
  static/app/views/profiling/profileFlamechart.tsx
  tests/js/spec/components/profiling/breadcrumb.spec.tsx
Labels: Scope: Frontend

#37345 ref(package-data): Replace getMeta (proxy) with _meta object - [TET-144]
  static/app/components/events/eventEntries.tsx
  static/app/components/events/packageData.tsx
  tests/js/spec/components/events/packageData.spec.tsx
Labels: Scope: Frontend

#37387 test(dashboards): Skip flaky big number resize test
  tests/acceptance/test_organization_dashboards.py
Labels: Scope: Backend

#37408 ref(projectconfig): Remove acks_late on celery tasks
  src/sentry/tasks/relay.py
Labels: Scope: Backend

#37118 feat(profiling): add select project step
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingModal.tsx
  tests/js/spec/components/profiling/profilingOnboarding/profilingOnboarding.spec.tsx
  tests/js/spec/components/profiling/profilingOnboarding/profilingOnboardingModal.spec.tsx
Labels: Scope: Frontend

#37421 fix(dashboard): Remove save/cancel CTAs on Dashboard template
  static/app/views/dashboardsV2/detail.tsx
  static/app/views/dashboardsV2/filtersBar.tsx
  tests/js/spec/views/dashboardsV2/gridLayout/detail.spec.jsx
Labels: Scope: Frontend

#37422 chore(dashboard): Update releases widget data availability date
  static/app/views/dashboardsV2/widgetCard/index.tsx
Labels: Scope: Frontend

#37382 fix(dashboard-filters): Allow saving with All Projects
  src/sentry/api/serializers/models/dashboard.py
  src/sentry/api/serializers/rest_framework/dashboard.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
Labels: Scope: Backend

#37423 Revert "ref(extra-data): Replace getMeta (proxy) with _meta object - [TET-144]"
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventExtraData/eventDataContent.tsx
  static/app/components/events/eventExtraData/eventExtraData.tsx
  static/app/components/events/eventExtraData/getEventExtraDataKnownData.tsx
  tests/js/spec/components/events/eventExtraData.spec.tsx
Labels: Scope: Frontend

#37395 fix(dashboard): Clear search condition on release dropdown close
  static/app/views/dashboardsV2/releasesSelectControl.tsx
  tests/js/spec/views/dashboardsV2/releasesSelectControl.spec.tsx
Labels: Scope: Frontend

#37383 fix(discover-metrics): Update sort on multiple env filters
  src/sentry/search/events/builder.py
  tests/snuba/api/endpoints/test_organization_events_stats_mep.py
Labels: Scope: Backend

#37204 feat(dashboard): Display selected custom performance metric even if no longer valid in selected time range
  static/app/views/eventsV2/table/queryField.tsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
Labels: Scope: Frontend

#37328 test(ui): Convert group events to RTL
  tests/js/spec/views/organizationGroupDetails/groupEvents.spec.jsx
Labels: Scope: Frontend

#37326 test(ui): Convert group event entries to RTL
  static/app/components/events/errorItem.tsx
  tests/js/spec/views/organizationGroupDetails/groupEventEntries.spec.tsx
Labels: Scope: Frontend

#37425 fix(perf): Fix perf issue tag names
  src/sentry/tasks/performance_detection.py
  tests/sentry/tasks/test_performance_detection.py
Labels: Scope: Backend

#37032 fix(config): Ensure lastOrganization is an org that exists
  src/sentry/web/client_config.py
  tests/sentry/web/test_api.py
Labels: Scope: Backend

#37390 feat(replays): URLWalker will show up to three urls without summary
  static/app/components/replays/walker/splitCrumbs.tsx
Labels: Scope: Frontend

#37394 fix(replays): Reset the `currentTime` whenever the player re-mounts
  static/app/components/replays/replayContext.tsx
Labels: Scope: Frontend

#37424 fix(profiling): update font sizes
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/components/profiling/FrameStack/frameStackTableRow.tsx
  static/app/components/profiling/boundTooltip.tsx
Labels: Scope: Frontend

#37406 feat(sampling): Render sampling modals asap [TET-302]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
Labels: Scope: Frontend

#37315 fix(replays): Use Tooltip in Network Table "Path" column
  static/app/views/replays/detail/network/index.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#37206 feat(menuListItem): Add size prop
  docs-ui/stories/components/form-fields.stories.js
  static/app/components/dropdownMenuControl.tsx
  static/app/components/dropdownMenuItem.tsx
  static/app/components/events/interfaces/searchBarAction.tsx
  static/app/components/forms/compactSelect.tsx
  static/app/components/forms/selectControl.tsx
  static/app/components/forms/selectField.tsx
  static/app/components/forms/selectOption.tsx
  static/app/components/menuListItem.tsx
  static/app/utils/theme.tsx
Labels: Scope: Frontend

#37311 feat(search): Parse timezone info in datetime queries
  src/sentry/search/utils.py
  tests/sentry/search/test_utils.py
Labels: Scope: Backend

#37386 feat(eventstore): Add method to retrieve transactions
  src/sentry/eventstore/base.py
  src/sentry/eventstore/snuba/backend.py
  tests/sentry/eventstore/snuba/test_backend.py
Labels: Scope: Backend

#37161 ref(globalsdkupdatealert): update hook deps
  static/app/components/globalSdkUpdateAlert.tsx
Labels: Scope: Frontend

#37380 fix(vitals): bug when changing vital
  static/app/views/performance/vitalDetail/vitalsComparison.tsx
Labels: Scope: Frontend

#37417 fix(metrics): Actually write back rate limits [INGEST-1380]
  src/sentry/ratelimits/sliding_windows.py
  src/sentry/sentry_metrics/indexer/postgres_v2.py
  src/sentry/sentry_metrics/indexer/ratelimiters.py
  tests/sentry/ratelimits/test_sliding_windows.py
  tests/sentry/sentry_metrics/test_postgres_indexer.py
Labels: Scope: Backend

#37429 fix(mep): Fix counts and pagination on landing
  static/app/views/performance/landing/metricsDataSwitcher.tsx
Labels: Scope: Frontend

#37191 feat(profiling): add upload symbols step
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingModal.tsx
Labels: Scope: Frontend

#37348 feat(perf-issue): Add perf issue chart sections
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/performance/durationChart.tsx
  static/app/components/events/interfaces/performance/index.tsx
  static/app/components/events/interfaces/performance/spanCountChart.tsx
  static/app/components/events/interfaces/spans/embeddedSpanTree.tsx
  static/app/types/event.tsx
  static/app/utils/performance/histogram/spanCountHistogramQuery.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
Labels: Scope: Frontend

#36889 feat(issues): Move event context out of tags
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventTagsAndScreenshot/index.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
  static/app/components/events/eventTagsAndScreenshot/tags.tsx
  static/app/views/eventsV2/eventDetails/content.tsx
  static/app/views/performance/transactionDetails/content.tsx
  static/app/views/sharedGroupDetails/index.tsx
Labels: Scope: Frontend

#37388 ref: Run prettier through the fixture jsons
  fixtures/artifact_bundle/manifest.json
  fixtures/cloudflare/oauth-login-webhook.json
  fixtures/cloudflare/option-change-account-webhook.json
  fixtures/cloudflare/preview-webhook-authenticated.json
  fixtures/cloudflare/preview-webhook.json
  fixtures/integration-docs/go-http.json
  fixtures/integration-docs/python-fastapi.json
  fixtures/integration-docs/starlette.json
  fixtures/integrations/jira/stubs/createmeta_response.json
  fixtures/integrations/jira/stubs/edit_issue_assignee_missing_payload.json
  fixtures/integrations/jira/stubs/edit_issue_assignee_payload.json
  fixtures/integrations/jira/stubs/edit_issue_no_assignee_payload.json
  fixtures/integrations/jira/stubs/edit_issue_status_payload.json
  fixtures/integrations/jira/stubs/fetch_issue_create_meta.json
  fixtures/integrations/jira/stubs/get_issue_response.json
  fixtures/integrations/jira/stubs/issue_fields_response.json
  fixtures/integrations/jira/stubs/issue_types_response.json
  fixtures/integrations/jira/stubs/jira_server_user.json
  fixtures/integrations/jira/stubs/priorities_response.json
  fixtures/integrations/jira/stubs/search_response.json
  fixtures/integrations/jira/stubs/transition_response.json
  fixtures/integrations/jira/stubs/user_search_response.json
  fixtures/integrations/jira/stubs/versions_response.json
  fixtures/profiles/valid_android_profile.json
  fixtures/profiles/valid_ios_profile.json
  fixtures/search-syntax/duration_aggregate_op_breakdowns_filter.json
  fixtures/search-syntax/numeric_aggregate_op_breakdowns_filter.json
Labels: Scope: Frontend, Scope: Backend

#37420 fix(profiling): Add profiling summary into flamechart breadcrumbs
  static/app/components/profiling/breadcrumb.tsx
  static/app/components/profiling/profileHeader.tsx
  tests/js/spec/components/profiling/breadcrumb.spec.tsx
Labels: Scope: Frontend

#37391 feat(profiling): Update profiling landing charts
  static/app/types/organization.tsx
  static/app/utils/profiling/hooks/useProfileStats.tsx
  static/app/views/profiling/content.tsx
  static/app/views/profiling/landing/profileCharts.tsx
Labels: Scope: Frontend

#37441 fix(perf): Fix perf issue units
  src/sentry/tasks/performance_detection.py
  tests/sentry/tasks/test_performance_detection.py
Labels: Scope: Backend

#37426 fix(msteams): Add missing analytics
  src/sentry/integrations/msteams/notifications.py
Labels: Scope: Backend

#37398 feat(msteams): Add alert rule notification
  src/sentry/integrations/msteams/card_builder/notifications.py
  src/sentry/integrations/msteams/notifications.py
  src/sentry/testutils/cases.py
  tests/sentry/integrations/msteams/notifications/test_issue_alert.py
Labels: Scope: Backend

#37431 feat(workflow): Remove `duplicate-alert-rule` flag
  static/app/views/alerts/create.tsx
  static/app/views/alerts/list/rules/index.tsx
  static/app/views/alerts/list/rules/row.tsx
  static/app/views/alerts/rules/issue/index.tsx
  tests/js/spec/views/alerts/issueRules/issueRuleEditor.spec.jsx
  tests/js/spec/views/alerts/metricRules/duplicate.spec.tsx
  tests/js/spec/views/alerts/rules/index.spec.jsx
Labels: Scope: Frontend

#37438 fix(alerts): Allow mep-rollout-flag to enable metric dataset
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
  tests/js/spec/views/alerts/metricRules/ruleForm.spec.jsx
Labels: Scope: Frontend

#37430 refactor(replays): useCrumbHandlers utility
  static/app/utils/replays/hooks/useCrumbHandlers.tsx
  static/app/views/replays/detail/breadcrumbs/index.tsx
  static/app/views/replays/detail/domMutations/index.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#37444 feat(profiling): Make flamegraph view the default
  static/app/components/profiling/profilesTable.tsx
Labels: Scope: Frontend

#37446 fix(metrics): Do not crash when limiting all strings in a message [INGEST-1380]
  src/sentry/runner/commands/run.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/sentry_metrics/indexer/postgres_v2.py
  tests/sentry/sentry_metrics/test_postgres_indexer.py
Labels: Scope: Backend

#37385 fix(dashboards): adds indexed badge to dashboard template preview mode
  static/app/views/dashboardsV2/widgetCard/widgetCardContextMenu.tsx
  tests/js/spec/views/dashboardsV2/widgetCard.spec.tsx
Labels: Scope: Frontend

#37445 feat(dashboards): updates widget builder Custom Perf Metrics and Indexed Event Data banner links
  static/app/views/dashboardsV2/widgetCard/index.tsx
Labels: Scope: Frontend

#37321 feat(slack-notifications): adds backfill for slack notification settings
  migrations_lockfile.txt
  src/sentry/migrations/0311_backfill_slack_settings.py
  tests/sentry/migrations/test_0311_backfill_slack_settings.py
Labels: Scope: Backend

#37437 fix(rh-widgets): Throw an error if RH widget queries are beyond July 12
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/sortableWidget.tsx
  static/app/views/dashboardsV2/widgetCard/index.tsx
  tests/js/spec/components/modals/widgetViewerModal.spec.tsx
  tests/js/spec/views/dashboardsV2/releaseWidgetQueries.spec.tsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
Labels: Scope: Frontend

#37452 fix(msteams): Add analytics event
  src/sentry/integrations/msteams/__init__.py
  src/sentry/integrations/msteams/analytics.py
  src/sentry/integrations/msteams/notifications.py
Labels: Scope: Backend

#37449 fix(eventstore): Expose get_unfetched_transactions
  src/sentry/eventstore/base.py
Labels: Scope: Backend

#37392 fix(counter): Fix minor linting violation
  src/sentry/models/counter.py
Labels: Scope: Backend

#37435 feat(mep): Allow mep alerts to be enabled via `mep-rollout-flag` as well.
  src/sentry/incidents/serializers/alert_rule.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Scope: Backend

#37416 ref(sampling): Do not display specify client rate modal if no groups
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
Labels: Scope: Frontend

#37411 test(metrics): Reenable MetricsExtractionTest [INGEST-1520]
  tests/relay_integration/test_metrics_extraction.py
Labels: Scope: Backend

#37350 ref(event-sdk): Replace getMeta (proxy) with _meta object - [TET-144]
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventSdk.tsx
  tests/js/spec/components/events/eventSdk.spec.tsx
Labels: Scope: Frontend

#37295 feat(dynamic-sampling): Add `isSendingSource` to dynamic-sampling SDK versions endpoint [TET-271]
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
  src/sentry/snuba/events.py
  tests/sentry/api/endpoints/test_organization_dynamic_sampling_sdk_versions.py
  tests/snuba/api/endpoints/test_organization_events.py
Labels: Scope: Backend

#37413 ref(sampling): Remove unused typescript types [TET-277]
  static/app/types/sampling.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/conditions.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/tagValueAutocomplete.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/utils.tsx
  static/app/views/settings/project/server-side-sampling/utils/index.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils.tsx
Labels: Scope: Frontend

#37412 chore(sampling): Update docs url [TET-277]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/samplingBreakdown.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/index.tsx
  tests/js/spec/views/settings/project/server-side-sampling/serverSideSampling.spec.tsx
Labels: Scope: Frontend

#37407 feat(sampling): Allow to activate rule only if sdks are updated [TET-241][TET-277]
  static/app/views/settings/project/server-side-sampling/rule.tsx
  tests/js/spec/views/settings/project/server-side-sampling/serverSideSampling.spec.tsx
Labels: Scope: Frontend

#37336 feat(sampling): Check for source in sdk updates prompt [TET-244]
  static/app/types/sampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.spec.tsx
Labels: Scope: Frontend

#37457 ref(sampling): Add client and server warning/help icons- [TET-298]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
Labels: Scope: Frontend

#37414 ref(rich-http-content): Replace getMeta with _meta object - [TET-144]
  static/app/components/contextData/index.tsx
  static/app/components/contextData/toggle.tsx
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/keyValueList/index.tsx
  static/app/components/events/interfaces/request.tsx
  static/app/components/events/interfaces/request/getTransformedData.tsx
  static/app/components/events/interfaces/request/index.tsx
  static/app/components/events/interfaces/request/richHttpContentClippedBoxBodySection.tsx
  static/app/components/events/interfaces/request/richHttpContentClippedBoxKeyValueList.tsx
  static/app/components/events/interfaces/richHttpContent/getTransformedData.tsx
  static/app/components/events/interfaces/richHttpContent/richHttpContent.tsx
  static/app/components/events/meta/annotatedText/index.tsx
  static/app/components/events/meta/annotatedText/valueElement.tsx
  static/app/types/event.tsx
  tests/js/spec/components/contextData.spec.tsx
  tests/js/spec/components/events/interfaces/request.spec.tsx
  tests/js/spec/components/events/interfaces/richHttpContent.spec.jsx
  tests/js/spec/views/organizationGroupDetails/groupSimilarIssues.spec.tsx
Labels: Scope: Frontend

#37458 feat(sampling): Add feature badge, link to faq [TET-310]
  static/app/views/settings/components/settingsNavItem.tsx
  static/app/views/settings/project/navigationConfiguration.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/types.tsx
  tests/js/spec/views/settings/project/server-side-sampling/serverSideSampling.spec.tsx
Labels: Scope: Frontend

#37443 feat(mep): Metrics compatibility endpoint
  src/sentry/api/bases/organization.py
  src/sentry/api/endpoints/organization_events_meta.py
  src/sentry/api/urls.py
  src/sentry/search/events/datasets/metrics.py
  tests/sentry/api/endpoints/test_organization_transaction_anomaly_detection.py
  tests/snuba/api/endpoints/test_organization_events_meta.py
Labels: Scope: Backend

#37418 feat(tag-mgmt): Add tag to tags endpoint
  src/sentry/api/endpoints/organization_tags.py
Labels: Scope: Backend

#37436 ref: upgrade sentry-arroyo (to get confluent-kafka upgrade)
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/eventstream/kafka/backend.py
Labels: Scope: Backend

#37462 ref(sampling): Add javascript example copy to snippet - [TET-267]
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
Labels: Scope: Frontend

#37393 feat(suspect-functions): Highlight functions linked from suspect func…
  static/app/components/profiling/flamegraphZoomView.tsx
  static/app/components/profiling/functionsTable.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphProfiles.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/index.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/renderers/selectedFrameRenderer.tsx
  tests/js/spec/utils/profiling/renderers/selectedFrameRenderer.spec.tsx
Labels: Scope: Frontend

#37467 ref(ui): remove console.log
  static/app/components/events/eventEntry.tsx
Labels: Scope: Frontend
