Repository getsentry/sentry, pull requests merged in 2022-03, with the labels that each got.

#32321 feat(ci): Increase frontend tests to four groups
  .github/workflows/acceptance.yml
Labels: Component: CI

#32291 fix(github): Unblock Repository Deletions
  src/sentry/db/mixin.py
  src/sentry/deletions/__init__.py
  src/sentry/models/repository.py
  tests/sentry/deletions/test_repository.py
Labels: Type: Bug, Team: Ecosystem

#32383 feat(dev): Do not write CPATH and LDFLAGS in .zshrc
  .envrc
  scripts/lib.sh
Labels: Component: Developer Environment

#32085 ref(serializers): Split up large file
  mypy.ini
  src/sentry/api/serializers/models/organization_member.py
  src/sentry/api/serializers/models/organization_member/__init__.py
  src/sentry/api/serializers/models/organization_member/base.py
  src/sentry/api/serializers/models/organization_member/expand/__init__.py
  src/sentry/api/serializers/models/organization_member/expand/projects.py
  src/sentry/api/serializers/models/organization_member/expand/teams.py
  src/sentry/api/serializers/models/organization_member/response.py
  src/sentry/api/serializers/models/organization_member/scim.py
  src/sentry/api/serializers/models/organization_member/utils.py
  src/sentry/api/serializers/models/team.py
Labels: Team: Ecosystem

#32524 fix(dev): Errors within lib.sh were not being reported to Sentry
  .envrc
  scripts/lib.sh
Labels: Component: Developer Environment

#32544 fix(dev): Fix regression: SENTRY_CLI_NO_EXIT_TRAP: unbound variable
  scripts/lib.sh
Labels: Component: Developer Environment

#32504 feat(dev/ci): Test loading mocks and bootstrap code
  .github/workflows/development-environment.yml
  scripts/lib.sh
  src/sentry/runner/commands/createuser.py
Labels: Component: Developer Environment

#32565 feat(ci): Make dev env check faster by splitting off pyenv testing
  .github/workflows/development-environment.yml
Labels: Component: CI

#32718 ref(endpoints): Pass OrganizationMember through `convert_args()`
  src/sentry/api/bases/organizationmember.py
  src/sentry/api/endpoints/organization_invite_request_details.py
  src/sentry/api/endpoints/organization_member_details.py
  src/sentry/api/endpoints/organization_member_team_details.py
  src/sentry/models/organizationmember.py
  src/sentry/scim/endpoints/members.py
Labels: Team: Ecosystem

#32715 ref(tests): DRY OrganizationMember tests.
  tests/sentry/api/endpoints/test_organization_member_issues_assigned.py
  tests/sentry/api/endpoints/test_organization_member_team_details.py
  tests/sentry/api/endpoints/test_organization_member_unreleased_commits.py
Labels: Team: Ecosystem

#31590 ref(types): Add types to rules
  mypy.ini
  src/sentry/integrations/jira/notify_action.py
  src/sentry/integrations/slack/notify_action.py
  src/sentry/integrations/vsts/notify_action.py
  src/sentry/mail/adapter.py
  src/sentry/rules/__init__.py
  src/sentry/rules/actions/base.py
  src/sentry/rules/actions/notify_event.py
  src/sentry/rules/actions/notify_event_sentry_app.py
  src/sentry/rules/actions/notify_event_service.py
  src/sentry/rules/actions/services.py
  src/sentry/rules/base.py
  src/sentry/rules/conditions/base.py
  src/sentry/rules/conditions/event_frequency.py
  src/sentry/rules/conditions/first_seen_event.py
  src/sentry/rules/conditions/reappeared_event.py
  src/sentry/rules/conditions/regression_event.py
  src/sentry/rules/filters/base.py
  src/sentry/rules/processor.py
  src/sentry/rules/registry.py
  src/sentry/tasks/integrations/__init__.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/rules/test_processor.py
Labels: Status: In Progress

#32745 fix(getsentry): `RuleFuture` circular import
  src/sentry/mail/adapter.py
Labels: Team: Ecosystem

#32755 ref(types): Remove circular dependencies
  src/sentry/integrations/slack/notify_action.py
  src/sentry/mail/adapter.py
  src/sentry/rules/__init__.py
  src/sentry/rules/actions/base.py
  src/sentry/rules/base.py
  src/sentry/rules/processor.py
  src/sentry/types/rules.py
  tests/sentry/integrations/jira/test_notify_action.py
  tests/sentry/integrations/test_ticket_rules.py
  tests/sentry/integrations/vsts/test_notify_action.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/tasks/test_sentry_apps.py
Labels: Team: Ecosystem

#31910 feat(ui): Remove issues from issue stream
  static/app/views/issueList/overview.tsx
  tests/acceptance/page_objects/issue_list.py
  tests/acceptance/test_organization_group_index.py
Labels: Status: In Progress

#32056 fix(trace-view): Do not recreate fuse in trace view
  static/app/views/performance/traceDetails/content.tsx
Labels: Status: In Progress

#32883 fix(dev): New Python virtualenvs to install Python 3.8.13
  .github/workflows/development-environment.yml
  .python-version
  scripts/ensure-venv.sh
  scripts/lib.sh
  scripts/pyenv_setup.sh
Labels: Component: Developer Environment

#32915 fix(ci): Prevent Visual Snapshots when depending jobs fail
  .github/workflows/acceptance.yml
  .github/workflows/visual-diff.yml
Labels: Component: CI

#32911 feat(ci): Prevent cancelling running jobs of a matrix
  .github/workflows/acceptance.yml
  .github/workflows/backend-test.yml
  .github/workflows/snuba-integration-test.yml
Labels: Component: CI

#33005 fix(test): Fix Flaky Test
  tests/sentry/integrations/vsts/test_notify_action.py
Labels: Team: Ecosystem

#33022 fix(tests): Fix flaky tests for GitLab updates
  src/sentry/integrations/gitlab/webhooks.py
  tests/sentry/integrations/gitlab/test_webhook.py
Labels: Component: Integrations, Team: Ecosystem

#33004 ref(tests): Split up large test file
  tests/sentry/incidents/action_handlers/__init__.py
  tests/sentry/incidents/action_handlers/test_email.py
  tests/sentry/incidents/action_handlers/test_msteams.py
  tests/sentry/incidents/action_handlers/test_pagerduty.py
  tests/sentry/incidents/action_handlers/test_sentry_app.py
  tests/sentry/incidents/action_handlers/test_slack.py
  tests/sentry/incidents/test_action_handlers.py
Labels: Team: Ecosystem

#32959 build(ci): Use codecov GH action instead of bash script
  .github/actions/artifacts/action.yml
  .github/workflows/acceptance.yml
  Makefile
Labels: Component: CI

#33087 feat(ci): Use codecov "carryforward" feature
  codecov.yml
Labels: Component: CI

#33123 fix(groupaction): init and teardown store
  static/app/stores/configStore.tsx
  tests/js/spec/views/organizationGroupDetails/actions.spec.tsx
Labels: Type: CI Flakiness

#33127 fix(navigation): init and teardown store
  tests/js/spec/actionCreators/navigation.spec.jsx
Labels: Type: CI Flakiness

#33126 fix(dashboard): init and teardown store
  tests/js/spec/components/breadcrumbs.spec.jsx
  tests/js/spec/views/dashboardsV2/gridLayout/create.spec.tsx
Labels: Type: CI Flakiness

#33122 fix(environmentpagefilters): remove act
  tests/js/spec/components/environmentPageFilter.spec.tsx
Labels: Type: CI Flakiness

#33118 fix(pagefilterstore): init and teardown organizationstore
  tests/js/spec/components/projectPageFilter.spec.tsx
Labels: Type: CI Flakiness

#33018 ref(setTimeout): reference window.setTimeout for correct return type
  docs-ui/components/code.tsx
  static/app/actionCreators/pageFilters.tsx
  static/app/components/asyncComponent.tsx
  static/app/components/autoComplete.tsx
  static/app/components/bases/pluginComponentBase.tsx
  static/app/components/charts/pieChart.tsx
  static/app/components/dashboards/issueWidgetQueriesForm.tsx
  static/app/components/dropdownMenu.tsx
  static/app/components/dropdownMenuControlV2.tsx
  static/app/components/errors/detailedError.tsx
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/utils/performance/contexts/genericQueryBatcher.tsx
  static/app/utils/performanceForSentry.tsx
  static/app/views/alerts/incidentRules/ruleForm/index.tsx
  static/app/views/alerts/issueRuleEditor/index.tsx
  static/app/views/alerts/issueRuleEditor/ruleNodeList.tsx
  static/app/views/dashboardsV2/dashboard.tsx
  static/app/views/onboarding/components/welcomeBackground.tsx
  static/app/views/onboarding/createSampleEventButton.tsx
  static/app/views/onboarding/targetedOnboarding/components/welcomeBackground.tsx
  static/app/views/onboarding/targetedOnboarding/onboarding.tsx
  static/app/views/onboarding/welcome.tsx
  static/app/views/organizationIntegrations/SplitInstallationIdModal.tsx
  static/app/views/settings/account/accountClose.tsx
  static/app/views/settings/project/projectUserFeedback.tsx
  static/app/views/userFeedback/userFeedbackEmpty.tsx
Labels: Type: CI Flakiness

#33129 fix(saferefluxstore): do not return from while loop
  static/app/stores/organizationEnvironmentsStore.tsx
  static/app/utils/makeSafeRefluxStore.ts
  static/app/views/organizationGroupDetails/groupEventDetails/index.tsx
  tests/fixtures/js-stubs/types.tsx
  tests/js/spec/utils/makeSafeRefluxStore.spec.ts
  tests/js/spec/views/dashboardsV2/gridLayout/create.spec.tsx
  tests/js/spec/views/organizationGroupDetails/groupEventDetailsContainer.spec.jsx
  tests/js/spec/views/organizationGroupDetails/groupEventDetailsContainer.spec.tsx
Labels: Type: CI Flakiness

#33119 fix(datepagefilter): init and teardown organizationstore
  tests/js/spec/components/datePageFilter.spec.tsx
Labels: Type: CI Flakiness

#33050 fix(appStoreConnextContext): cleanup promises
  static/app/components/errors/detailedError.tsx
  static/app/components/events/eventCause.tsx
  static/app/components/events/eventCauseEmpty.tsx
  static/app/components/navigationButtonGroup.tsx
  static/app/components/projects/appStoreConnectContext.tsx
  static/app/stores/committerStore.tsx
  static/app/utils/withCommitters.tsx
  static/app/views/organizationGroupDetails/groupEventDetails/groupEventDetails.tsx
  tests/js/spec/views/organizationGroupDetails/groupEventDetails.spec.jsx
  tests/js/spec/views/organizationGroupDetails/groupEventDetails.spec.tsx
Labels: Type: CI Flakiness

#33121 fix(multipleenvironmentsselector): init and teardown store
  tests/js/spec/components/organizations/multipleEnvironmentSelector.spec.tsx
Labels: Type: CI Flakiness

#33061 fix(twilio): Stop sending configuration errors to Sentry
  src/sentry/plugins/bases/notify.py
  src/sentry/shared_integrations/constants.py
Labels: Team: Ecosystem

#33054 fix(integrations): SentryApp error message
  src/sentry/mediators/external_requests/alert_rule_action_requester.py
  src/sentry/mediators/external_requests/util.py
  src/sentry/receivers/sentry_apps.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Type: Bug, Team: Ecosystem

#33150 fix(ops genie): URL Validation
  src/sentry_plugins/opsgenie/plugin.py
Labels: Type: Bug, Team: Ecosystem

#33055 fix(serializer): Project `session_stats`
  src/sentry/api/endpoints/organization_projects.py
  src/sentry/api/serializers/models/project.py
  tests/sentry/api/serializers/test_project.py
Labels: Type: Bug, Team: Ecosystem

#33148 feat(ci): Change charcuterie coverage to be uploaded only on backend changes
  .github/workflows/acceptance.yml
  codecov.yml
Labels: Component: CI

#32864 ref(integrations): Stop swallowing Pipeline Errors
  src/sentry/pipeline/__init__.py
Labels: Team: Ecosystem
