Repository getsentry/sentry, pull requests merged in 2022-01, with the labels that each got.

#30903 feat(doc integrations): Use docIntegrations from the backend with feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  static/app/components/avatar/docIntegrationAvatar.tsx
  static/app/components/search/searchResult.tsx
  static/app/components/search/sources/apiSource.tsx
  static/app/components/search/sources/types.tsx
  static/app/types/integrations.tsx
  static/app/utils/integrationUtil.tsx
  static/app/views/organizationIntegrations/constants.tsx
  static/app/views/organizationIntegrations/docIntegrationDetailedView.tsx
  static/app/views/organizationIntegrations/integrationListDirectory.tsx
  static/app/views/organizationIntegrations/integrationRow.tsx
  tests/acceptance/test_organization_document_integration_detailed_view.py
  tests/fixtures/js-stubs/docIntegration.js
  tests/fixtures/js-stubs/types.tsx
  tests/js/spec/components/modals/commandPaletteModal.spec.jsx
  tests/js/spec/components/search/sources/apiSource.spec.jsx
  tests/js/spec/views/organizationIntegrations/docIntegrationDetailedView.spec.jsx
  tests/js/spec/views/organizationIntegrations/integrationListDirectory.spec.jsx
  tests/js/spec/views/settings/components/settingsSearch/index.spec.jsx
Labels: Component: Integrations, Team: Ecosystem

#30690 Repair changelog
  CHANGES
Labels: Status: Stale

#30944 chore(doc integrations): Remove hard-coded info on DocIntegrations from the codebase
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/static/sentry/images/logos/logo-asayer.svg
  src/sentry/static/sentry/images/logos/logo-datadog.svg
  src/sentry/static/sentry/images/logos/logo-fullstory.svg
  src/sentry/static/sentry/images/logos/logo-github-actions.svg
  src/sentry/static/sentry/images/logos/logo-grafana.svg
  src/sentry/static/sentry/images/logos/logo-insightfinder.svg
  src/sentry/static/sentry/images/logos/logo-netlify.svg
  src/sentry/static/sentry/images/logos/logo-octohook.svg
  src/sentry/static/sentry/images/logos/logo-rocketchat.svg
  static/app/components/search/sources/apiSource.tsx
  static/app/plugins/components/pluginIcon.tsx
  static/app/types/integrations.tsx
  static/app/views/organizationIntegrations/constants.tsx
  static/app/views/organizationIntegrations/docIntegrationDetailedView.tsx
  static/app/views/organizationIntegrations/integrationListDirectory.tsx
  tests/acceptance/test_organization_document_integration_detailed_view.py
  tests/js/spec/components/search/sources/apiSource.spec.jsx
  tests/js/spec/views/organizationIntegrations/docIntegrationDetailedView.spec.jsx
  tests/js/spec/views/organizationIntegrations/integrationListDirectory.spec.jsx
Labels: Component: Integrations, Team: Ecosystem

#30545 feat: Add permission groups via UserRole
  migrations_lockfile.txt
  src/sentry/auth/access.py
  src/sentry/migrations/0265_add_userrole.py
  src/sentry/models/__init__.py
  src/sentry/models/userpermission.py
  src/sentry/models/userrole.py
  tests/sentry/auth/test_access.py
  tests/sentry/models/test_userrole.py
Labels: Status: Stale

#30974 fix(doc integrations): Sort DocIntegrations by popularity as well
  static/app/views/organizationIntegrations/integrationListDirectory.tsx
  tests/js/spec/views/organizationIntegrations/integrationListDirectory.spec.jsx
Labels: Component: Integrations, Team: Ecosystem

#30951 feat(ratelimits): Add headers with rate limit details
  src/sentry/middleware/ratelimit.py
  src/sentry/ratelimits/base.py
  src/sentry/ratelimits/redis.py
  src/sentry/ratelimits/utils.py
  src/sentry/types/ratelimit.py
  tests/sentry/middleware/test_ratelimit_middleware.py
  tests/sentry/ratelimits/test_redis.py
  tests/sentry/ratelimits/utils/test_above_rate_limit_check.py
Labels: Component: API, Team: Ecosystem

#25802 feat(migrations): Add automated checks to migrations, and other safety features.
  requirements-base.txt
  src/sentry/conf/server.py
  src/sentry/db/postgres/base.py
  src/sentry/db/postgres/schema.py
  src/sentry/new_migrations/migrations.py
  src/sentry/new_migrations/monkey/__init__.py
  tests/sentry/db/postgres/schema/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/LICENSE
  tests/sentry/db/postgres/schema/safe_migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_default_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_default_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_default_app/migrations/0002_add_field_default.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_default_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_default_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_app/migrations/0002_add_field_notnull.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_default_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_default_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_default_app/migrations/0002_add_field_notnull_default.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_default_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_add_column_with_notnull_default_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_change_char_type_that_unsafe_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_change_char_type_that_unsafe_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_change_char_type_that_unsafe_app/migrations/0002_change_type_from_char120_to_char100.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_change_char_type_that_unsafe_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_change_char_type_that_unsafe_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_field_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_field_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_field_app/migrations/0002_rename_field.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_field_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_field_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_table_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_table_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_table_app/migrations/0002_rename_table.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_table_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_rename_table_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/decimal_to_float_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/decimal_to_float_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/decimal_to_float_app/migrations/0002_type_conversion.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/decimal_to_float_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/decimal_to_float_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/integration/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/integration/test_migrations.py
Labels: Status: In Progress

#30701 feat(migrations): Add checks for deleting tables/columns in migrations
  src/sentry/db/postgres/schema.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_delete_model_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_delete_model_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_delete_model_app/migrations/0002_delete_model.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_delete_model_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_delete_model_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_remove_field_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_remove_field_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_remove_field_app/migrations/0002_remove_field.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_remove_field_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/bad_flow_remove_field_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/good_flow_delete_model_state_app/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/good_flow_delete_model_state_app/migrations/0001_initial.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/good_flow_delete_model_state_app/migrations/0002_delete_model_state.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/good_flow_delete_model_state_app/migrations/0003_delete_table.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/good_flow_delete_model_state_app/migrations/__init__.py
  tests/sentry/db/postgres/schema/safe_migrations/apps/good_flow_delete_model_state_app/models.py
  tests/sentry/db/postgres/schema/safe_migrations/integration/test_migrations.py
Labels: Status: In Progress

#31030 feat(codeowners): Add endpoint to view code owner associations per organization
  src/sentry/api/endpoints/organization_codeowners_associations.py
  src/sentry/api/urls.py
  src/sentry/models/projectcodeowners.py
  tests/sentry/api/endpoints/test_organization_codeowners_associations.py
Labels: Component: Integrations, Team: Ecosystem

#30526 ref(performance-metrics): Fix tooltip and y-Axis in failure rate widget [INGEST-756]
  static/app/views/performance/charts/chart.tsx
  static/app/views/performance/landing/widgets/widgets/singleFieldAreaWidgetMetrics.tsx
Labels: Status: In Progress

#30681 feat(performance-metrics): Add metrics vital chart (web vital details) - [INGEST-545]
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidgetMetrics.tsx
  static/app/views/performance/vitalDetail/types.tsx
  static/app/views/performance/vitalDetail/utils.tsx
  static/app/views/performance/vitalDetail/vitalChart.tsx
  static/app/views/performance/vitalDetail/vitalChartMetrics.tsx
  static/app/views/performance/vitalDetail/vitalDetailContent.tsx
Labels: Status: In Progress

#30392 feat(ui): Icon Search in Storybook
  .storybook/preview.tsx
  docs-ui/components/code.tsx
  docs-ui/images/icons-link-preview.svg
  docs-ui/stories/assets/fileIcon.stories.js
  docs-ui/stories/assets/iconProps.stories.js
  docs-ui/stories/assets/iconSet.stories.js
  docs-ui/stories/assets/icons/data.tsx
  docs-ui/stories/assets/icons/iconSearch.stories.mdx
  docs-ui/stories/assets/icons/infoBox.tsx
  docs-ui/stories/assets/icons/popper.tsx
  docs-ui/stories/assets/icons/sample.tsx
  docs-ui/stories/assets/icons/searchPanel.tsx
  docs-ui/stories/changelog/changelog.stories.mdx
  docs-ui/stories/gettingStarted/gettingStarted.stories.mdx
Labels: Status: Stale

#30764 feat(gsh): Standalone environment selector
  static/app/components/environmentPageFilter.tsx
  static/app/components/organizations/multipleEnvironmentSelector.tsx
  tests/js/spec/components/environmentPageFilter.spec.tsx
Labels: Status: In Progress, Status: Stale

#30555 ref(analytics): Analytics Refactor + Types
  mypy.ini
  src/sentry/analytics/__init__.py
  src/sentry/analytics/attribute.py
  src/sentry/analytics/base.py
  src/sentry/analytics/event.py
  src/sentry/analytics/event_manager.py
  src/sentry/analytics/events/__init__.py
  src/sentry/analytics/events/inapp_request.py
  src/sentry/analytics/map.py
  src/sentry/analytics/pubsub.py
  src/sentry/analytics/utils.py
  src/sentry/integrations/slack/__init__.py
  src/sentry/integrations/slack/analytics.py
  src/sentry/integrations/vsts/__init__.py
  src/sentry/mail/analytics.py
Labels: Status: In Progress, Team: Ecosystem

#30786 ref(integrations): Split up large file
  src/sentry/shared_integrations/client/__init__.py
  src/sentry/shared_integrations/client/base.py
  src/sentry/shared_integrations/client/internal.py
  src/sentry/shared_integrations/exceptions/__init__.py
  src/sentry/shared_integrations/exceptions/base.py
  src/sentry/shared_integrations/response/__init__.py
  src/sentry/shared_integrations/response/base.py
  src/sentry/shared_integrations/response/mapping.py
  src/sentry/shared_integrations/response/sequence.py
  src/sentry/shared_integrations/response/text.py
  src/sentry/shared_integrations/response/xml.py
  src/sentry/shared_integrations/track_response.py
  tests/sentry/integrations/test_client.py
Labels: Status: In Progress, Component: Integrations, Team: Ecosystem

#30765 ref(notifications): Prepare Slack for sending Nudges.
  src/sentry/integrations/slack/analytics.py
  src/sentry/integrations/slack/endpoints/action.py
  src/sentry/integrations/slack/notifications.py
  src/sentry/integrations/slack/requests/base.py
  src/sentry/integrations/slack/views/link_team.py
  src/sentry/models/identity.py
  src/sentry/notifications/types.py
  tests/sentry/integrations/slack/endpoints/test_action.py
Labels: Component: Notifications, Team: Ecosystem

#30409 feat(notifications): Nudge Notifications
  src/sentry/integrations/slack/endpoints/action.py
  src/sentry/integrations/slack/views/link_identity.py
  src/sentry/notifications/manager.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/integration_nudge.py
  tests/sentry/integrations/slack/endpoints/test_action.py
  tests/sentry/integrations/slack/notifications/test_nudge.py
Labels: Component: Notifications, Team: Ecosystem

#31141 ref(ratelimit): Added a config and changed a default
  src/sentry/api/base.py
  src/sentry/conf/server.py
Labels: Component: API, Team: Ecosystem

#31208 ref(test): Speed up SentryApp API tests
  src/sentry/api/bases/sentryapps.py
  src/sentry/api/serializers/models/alert_rule.py
  src/sentry/api/serializers/models/sentry_app.py
  tests/sentry/api/endpoints/test_sentry_apps.py
Labels: Team: Ecosystem

#30798 ref(types): `src/sentry/shared_integrations`
  mypy.ini
  src/sentry/api/base.py
  src/sentry/integrations/base.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/slack/client.py
  src/sentry/shared_integrations/client/__init__.py
  src/sentry/shared_integrations/client/base.py
  src/sentry/shared_integrations/client/internal.py
  src/sentry/shared_integrations/exceptions/__init__.py
  src/sentry/shared_integrations/exceptions/base.py
  src/sentry/shared_integrations/response/base.py
  src/sentry/shared_integrations/response/mapping.py
  src/sentry/shared_integrations/response/sequence.py
  src/sentry/shared_integrations/response/text.py
  src/sentry/shared_integrations/response/xml.py
  src/sentry/shared_integrations/track_response.py
Labels: Component: Integrations, Status: Stale, Team: Ecosystem

#31236 fix(ratelimit): Don't rate limit system requests
  src/sentry/ratelimits/utils.py
  tests/sentry/ratelimits/utils/test_get_ratelimit_key.py
Labels: Component: API, Team: Ecosystem

#31256 fix(notifications): Truncate version in Regression notification
  src/sentry/notifications/notifications/activity/regression.py
Labels: Component: Notifications, Team: Ecosystem

#31285 chore(codeowners): Restrict the configuration pages to non-members
  static/app/views/settings/organizationIntegrations/configureIntegration.tsx
Labels: Component: Integrations, Team: Ecosystem

#31223 fix(notifications): Fix `get_user_subscriptions_for_groups()`
  src/sentry/notifications/helpers.py
  src/sentry/notifications/notify.py
  src/sentry/shared_integrations/response/base.py
  tests/sentry/notifications/utils/test_get_most_specific.py
  tests/sentry/notifications/utils/test_get_user_subscriptions_for_groups.py
Labels: Component: Notifications, Team: Ecosystem

#31319 ref(codeowners): Allow associations endpoint to be limited by provider
  src/sentry/api/endpoints/organization_codeowners_associations.py
  tests/sentry/api/endpoints/test_organization_codeowners_associations.py
Labels: Component: Integrations, Team: Ecosystem

#31287 feat(codeowners): Use a new UI for user/team mappings
  static/app/components/integrationExternalMappingForm.tsx
  static/app/components/integrationExternalMappings.tsx
  static/app/utils/integrationUtil.tsx
  static/app/views/organizationIntegrations/integrationExternalTeamMappings.tsx
  static/app/views/organizationIntegrations/integrationExternalUserMappings.tsx
  static/app/views/settings/organizationIntegrations/configureIntegration.tsx
Labels: Component: Integrations, Team: Ecosystem

#31359 ref(serializers): Split up large file
  src/sentry/api/serializers/models/alert_rule_trigger_action.py
  src/sentry/incidents/endpoints/organization_alert_rule_available_action_index.py
  src/sentry/incidents/endpoints/organization_alert_rule_details.py
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
  src/sentry/incidents/endpoints/project_alert_rule_details.py
  src/sentry/incidents/endpoints/project_alert_rule_index.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/serializers/__init__.py
  src/sentry/incidents/serializers/alert_rule.py
  src/sentry/incidents/serializers/alert_rule_trigger.py
  src/sentry/incidents/serializers/alert_rule_trigger_action.py
  src/sentry/integrations/slack/tasks.py
  tests/sentry/api/serializers/test_alert_rule_trigger_action.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Team: Ecosystem

#31144 feat(SessionSerializer): read ability for transitional serializer
  src/sentry/conf/server.py
  src/sentry/utils/transitional_serializer.py
  tests/sentry/utils/test_transitional_serializer.py
Labels: Deploy: Risky

#31383 ref(codeowners): Bug fixing on results for SelectAsync settings form
  static/app/components/forms/selectAsyncControl.tsx
  static/app/components/integrationExternalMappingForm.tsx
  static/app/components/integrationExternalMappings.tsx
  static/app/utils/integrationUtil.tsx
  static/app/views/organizationIntegrations/integrationExternalTeamMappings.tsx
  static/app/views/organizationIntegrations/integrationExternalUserMappings.tsx
  static/app/views/settings/components/forms/selectAsyncField.tsx
Labels: Component: Integrations, Team: Ecosystem

#30889 chore(auth): remove deprecated SSO key check
  src/sentry/utils/auth.py
  tests/integration/test_api.py
Labels: Status: Stale

#30058 feat(sso): Add jumpcloud as provider in list
  setup.py
  src/sentry/auth/providers/saml2/jumpcloud/__init__.py
  src/sentry/auth/providers/saml2/jumpcloud/apps.py
  src/sentry/auth/providers/saml2/jumpcloud/provider.py
  src/sentry/auth/providers/saml2/jumpcloud/views.py
  src/sentry/static/sentry/images/logos/logo-jumpcloud.svg
  static/app/plugins/components/pluginIcon.tsx
  static/app/views/settings/components/identityIcon.tsx
  static/app/views/settings/organizationAuth/organizationAuthList.tsx
  static/less/auth.less
Labels: Status: Stale

#31406 feat(codeowners): Display mappings suggestions from codeowners
  static/app/components/integrationExternalMappingForm.tsx
  static/app/components/integrationExternalMappings.tsx
  static/app/types/integrations.tsx
  static/app/utils/integrationUtil.tsx
  static/app/views/organizationIntegrations/integrationExternalTeamMappings.tsx
  static/app/views/organizationIntegrations/integrationExternalUserMappings.tsx
  static/app/views/settings/organizationIntegrations/configureIntegration.tsx
Labels: Component: Integrations, Team: Ecosystem

#30813 feat(insights): Add `(project, date_added)` index to `GroupHistory`
  migrations_lockfile.txt
  src/sentry/migrations/0270_group_history_project_date_added_index.py
  src/sentry/models/grouphistory.py
Labels: Status: In Progress

#31450 fix(ratelimit): Store header info with request
  requirements-dev.txt
  src/sentry/middleware/ratelimit.py
  src/sentry/ratelimits/utils.py
  src/sentry/types/ratelimit.py
  tests/sentry/middleware/test_ratelimit_middleware.py
  tests/sentry/ratelimits/utils/test_above_rate_limit_check.py
Labels: Component: API, Team: Ecosystem
