Repository getsentry/sentry, pull requests merged in 2022-11, with the labels that each got.

#40790 feat(saved-searches): Move pin search button to header [UP-194]
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/header.tsx
  static/app/views/issueList/issueListSetAsDefault.spec.tsx
  static/app/views/issueList/issueListSetAsDefault.tsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#40476 ref(js): Remove issueList searchBuilder
  static/app/components/smartSearchBar/actions.tsx
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/overview.polling.spec.jsx
  static/app/views/issueList/overview.spec.jsx
  static/app/views/issueList/overview.tsx
  static/app/views/issueList/sidebar.tsx
  static/app/views/issueList/tagFilter.spec.tsx
  static/app/views/issueList/tagFilter.tsx
Labels: Scope: Frontend

#40624 faet(dx): Allow make develop to complete w/ hooks disabled
  scripts/lib.sh
Labels: Scope: Backend

#40623 feat(ui): Use main and header for org containers
  static/app/components/sidebar/index.tsx
  static/app/styles/organization.tsx
  static/app/views/performance/content.spec.jsx
Labels: Scope: Frontend

#40631 feat(ui): Mark SettingsBreadcrumb's as nav's with a label
  static/app/views/settings/components/settingsBreadcrumb/index.tsx
Labels: Scope: Frontend

#40794 fix(perf-issue): fix search query logic for !issue.category filters
  src/sentry/search/snuba/executors.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#40823 test(ui): Convert sentry app external issue form to RTL
  static/app/components/group/sentryAppExternalIssueForm.spec.jsx
Labels: Scope: Frontend

#40810 Update actions/cache to v3.0.11
  .github/workflows/acceptance.yml
  .github/workflows/backend.yml
Labels: Scope: Backend

#40804 Update getsentry/action-github-app-token to v2.0.0
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/getsentry-dispatch.yml
  .github/workflows/openapi.yml
  .github/workflows/sentry-pull-request-bot.yml
Labels: Scope: Frontend, Scope: Backend

#40745 feat(profiling): Introduce profile timeseries query builder
  mypy.ini
  src/sentry/api/endpoints/organization_events_stats.py
  src/sentry/search/events/datasets/profiles.py
  src/sentry/snuba/profiles.py
  tests/sentry/snuba/test_profiles.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
Labels: Scope: Backend

#40732 Abdullahkhan/feat/quick context hover
  static/app/components/hovercard.tsx
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/eventsV2/table/cellAction.spec.jsx
  static/app/views/eventsV2/table/cellAction.tsx
  static/app/views/eventsV2/table/quickContext.spec.tsx
  static/app/views/eventsV2/table/quickContext.tsx
  static/app/views/eventsV2/table/tableView.tsx
Labels: Scope: Frontend

#40779 fix(hc) Fix typings of model annotations
  src/sentry/db/models/base.py
Labels: Scope: Backend

#40816 chore(hybrid-cloud): Allow anyone to use customer domains
  src/sentry/middleware/customer_domain.py
  tests/sentry/middleware/test_customer_domain.py
  tests/sentry/web/frontend/test_auth_login.py
Labels: Scope: Backend

#40763 feat(dashboards): hides indexed and processed events alerts/banners/badges
  static/app/views/dashboardsV2/widgetCard/index.tsx
  static/app/views/dashboardsV2/widgetCard/widgetCardContextMenu.tsx
  static/app/views/eventsV2/results.tsx
Labels: Scope: Frontend

#40812 bug(replays): Stop calling getBoundingClientRect when it does not exist
  static/app/utils/replays/highlightNode.tsx
Labels: Scope: Frontend

#40759 feat(team-roles) Modify OrganizationMemberSerializer to validate team-roles
  src/sentry/api/endpoints/organization_member/__init__.py
  src/sentry/api/endpoints/organization_member/index.py
  src/sentry/testutils/factories.py
  tests/sentry/api/endpoints/test_organization_member_index.py
Labels: Scope: Backend

#39869 feat(team-roles): Disable retired org-roles when inviting members to org
  fixtures/js-stubs/roleList.js
  static/app/components/roleSelectControl.tsx
  static/app/types/organization.tsx
  static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
Labels: Scope: Frontend

#40788 fix (perf) Replace clickhouse lambda with has condition when querying for issue ids
  src/sentry/search/events/datasets/discover.py
Labels: Scope: Backend

#40838 feat(profiling): Allow ordering profiles queries by project slug
  src/sentry/search/events/datasets/profiles.py
  tests/sentry/snuba/test_profiles.py
Labels: Scope: Backend

#40834 ui(layout): Use size sm for header action buttons
  static/app/components/profiling/profileHeader.tsx
  static/app/views/eventsV2/eventDetails/content.tsx
Labels: Scope: Frontend

#40587 fix(integrations) Fix disappearing tags after assigning Issue
  src/sentry/integrations/slack/requests/action.py
  src/sentry/integrations/slack/webhooks/action.py
Labels: Scope: Backend, trigger-getsentry-external

#40829 feat(discover-homepage): Change beta badge to new badge
  static/app/views/eventsV2/savedQuery/index.tsx
Labels: Scope: Frontend

#40814 ref: Move shared arroyo metrics wrapper
  mypy.ini
  src/sentry/eventstream/kafka/backend.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/utils/arroyo.py
Labels: Scope: Backend

#40817 ref: Remove empty file
  src/sentry/eventstream/kafka/streaming_consumer.py
Labels: Scope: Backend

#40818 fix: Fix streaming post process forwarder
  src/sentry/eventstream/kafka/consumer_strategy.py
Labels: Scope: Backend

#40793 feat(alerts): spike protection notification setting frontend
  static/app/views/settings/account/accountNotificationFineTuning.tsx
  static/app/views/settings/account/notifications/constants.tsx
  static/app/views/settings/account/notifications/fields.tsx
  static/app/views/settings/account/notifications/fields2.tsx
  static/app/views/settings/account/notifications/notificationSettings.tsx
  static/app/views/settings/account/notifications/utils.tsx
Labels: Scope: Frontend

#40797 feat(session-replay): adds banner for session replay waitlist
  src/sentry/conf/server.py
  src/sentry/templates/sentry/layout.html
  src/sentry/utils/settings.py
  src/sentry/web/frontend/auth_login.py
Labels: Scope: Backend

#40694 feat(js): Add useSyncedLocalStorageState hook
  static/app/utils/useSyncedLocalStorageState.spec.tsx
  static/app/utils/useSyncedLocalStorageState.tsx
Labels: Scope: Frontend

#40783 feat(tracing): remove configure tracing CTA
  static/app/types/hooks.tsx
  static/app/utils/analytics/issueAnalyticsEvents.tsx
  static/app/views/organizationGroupDetails/quickTrace/configureDistributedTracing.tsx
  static/app/views/organizationGroupDetails/quickTrace/index.spec.jsx
  static/app/views/organizationGroupDetails/quickTrace/index.tsx
Labels: Scope: Frontend

#40658 feat(saved-searches): Use SmartSearchBar in save search creation modal
  static/app/components/modals/createSavedSearchModal.spec.jsx
  static/app/components/modals/createSavedSearchModal.tsx
  static/app/views/issueList/searchBar.tsx
Labels: Scope: Frontend

#40845 fix(forms): clean optional value
  src/sentry/rules/conditions/event_frequency.py
Labels: Scope: Backend

#40840 Update github-scripts to v6
  .github/workflows/getsentry-dispatch.yml
  .github/workflows/scripts/getsentry-dispatch.js
  .github/workflows/sentry-pull-request-bot.yml
Labels: Scope: Frontend

#40848 fix(all-events) typo in performance.issue_id which exposes it in the search bar
  static/app/views/organizationGroupDetails/groupEvents.tsx
Labels: Scope: Frontend

#40767 feat(framestack): expand by default for call order tree
  static/app/components/profiling/FrameStack/frameStack.tsx
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/VirtualizedTree.spec.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/VirtualizedTree.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.spec.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
Labels: Scope: Frontend

#40819 ref: Type check postprocessworker.py
  mypy.ini
  src/sentry/eventstream/kafka/postprocessworker.py
Labels: Scope: Backend

#40846 ref(searchbox): quick pass on performance
  static/app/components/events/searchBar.tsx
  static/app/utils/discover/fields.tsx
  static/app/views/dashboardsV2/utils.tsx
Labels: Scope: Frontend

#40850 ref(mep): Add thresholds to allow more null/unparam
  static/app/utils/performance/contexts/metricsCardinality.tsx
  static/app/views/performance/landing/metricsDataSwitcherAlert.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
Labels: Scope: Frontend

#40542 feat(issue-alert): add filter logic to previews
  src/sentry/rules/filters/age_comparison.py
  src/sentry/rules/filters/base.py
  src/sentry/rules/filters/issue_category.py
  src/sentry/rules/filters/issue_occurrences.py
  src/sentry/rules/history/preview.py
  src/sentry/rules/processor.py
  tests/sentry/rules/history/endpoints/test_project_rule_preview.py
  tests/sentry/rules/history/test_preview.py
Labels: Scope: Backend

#40842 fix(settings): Fix platform documentation link
  static/app/views/settings/settingsIndex.tsx
Labels: Scope: Frontend

#40795 ref(typing): add typing to issue search file
  mypy.ini
  src/sentry/api/issue_search.py
Labels: Scope: Backend

#40853 fix(all-events) ensure error state is set correctly
  static/app/views/organizationGroupDetails/allEventsTable.tsx
  static/app/views/organizationGroupDetails/groupEvents.spec.jsx
Labels: Scope: Frontend

#40843 chore(api): Change client attribute to be generic
  src/sentry/integrations/client.py
  src/sentry/integrations/slack/client.py
  src/sentry/plugins/sentry_webhooks/client.py
  src/sentry/shared_integrations/client/base.py
  src/sentry/shared_integrations/client/internal.py
  src/sentry/shared_integrations/track_response.py
  src/sentry/silo/client.py
  src/sentry_plugins/client.py
  src/sentry_plugins/splunk/client.py
Labels: Scope: Backend

#40755 ref(migration): Mark deprecated is_default in savedsearch nullable
  migrations_lockfile.txt
  src/sentry/migrations/0336_mark_deprecated_savedsearch_is_default_nullable.py
  src/sentry/models/savedsearch.py
Labels: Scope: Backend

#40856 fix(alerts): temporarily disable spike protection notif settings
  static/app/views/settings/account/notifications/constants.tsx
  static/app/views/settings/account/notifications/notificationSettings.tsx
Labels: Scope: Frontend

#40826 ref(saved-searches): Remove isOrgCustom from Serializer
  src/sentry/api/serializers/models/savedsearch.py
  src/sentry/models/savedsearch.py
Labels: Scope: Backend

#40825 ref(saved-searches): Remove unnecessary `isOrgCustom`
  fixtures/js-stubs/search.js
  static/app/stores/savedSearchesStore.spec.jsx
  static/app/stores/savedSearchesStore.tsx
  static/app/types/group.tsx
  static/app/views/issueList/filters.spec.tsx
  static/app/views/issueList/overview.spec.jsx
Labels: Scope: Frontend

#40865 feat(weekly-email): increase schedule reports sampling
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#40743 feat(ecosystem): Return connection errors from oauth issues
  src/sentry/identity/oauth2.py
  tests/sentry/identity/test_oauth2.py
Labels: Scope: Backend

#40830 ref(js): Remove deprecated `Form` from window global
  static/app/bootstrap/exportGlobals.tsx
Labels: Scope: Frontend

#40847 fix(backend): session replay banner setting
  src/sentry/conf/server.py
  src/sentry/utils/settings.py
  src/sentry/web/frontend/auth_login.py
Labels: Scope: Backend

#40756 ref(migration): Remove deprecated savedsearch columns (state only)
  migrations_lockfile.txt
  src/sentry/migrations/0337_drop_deprecated_savedsearch_columns.py
  src/sentry/models/savedsearch.py
Labels: Scope: Backend

#40868 feat(onboarding): onboarding sidebar hook
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/types/hooks.tsx
Labels: Scope: Frontend

#40872 ref(deletions): SavedSearch is no longer related to projects
  src/sentry/deletions/defaults/project.py
Labels: Scope: Backend

#40602 ref(processor): Try to fallback to previous frames token function name
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/lang/javascript/processor.py
  tests/sentry/lang/javascript/test_processor.py
Labels: Scope: Backend

#40706 feat(ds): bias healthchecks dropping
  src/sentry/dynamic_sampling/rules_generator.py
  src/sentry/dynamic_sampling/utils.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
  tests/sentry/relay/test_config.py
Labels: Scope: Frontend, Scope: Backend

#40705 ref(sampling): Update links for docs - [TET-501]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/index.tsx
Labels: Scope: Frontend

#40792 feat(tags): Allows tags endpoint to optionally return human readable values
  scripts/extract-android-device-names.js
  src/sentry/api/endpoints/group_tags.py
  src/sentry/api/helpers/android_models.py
  src/sentry/api/helpers/mobile.py
  tests/sentry/api/endpoints/test_group_tags.py
Labels: Scope: Frontend, Scope: Backend

#40832 feat(mobile-exp): Use new design for mobile tags
  static/app/components/group/sidebar.tsx
  static/app/components/group/tagFacets/index.spec.tsx
  static/app/components/group/tagFacets/index.tsx
  static/app/components/group/tagFacets/tagBreakdown.tsx
  static/app/components/tagDistributionMeter.tsx
Labels: Scope: Frontend

#40863 feat(replays): add hasReplays to project serializer
  src/sentry/api/endpoints/organization_projects.py
  src/sentry/api/serializers/models/project.py
  tests/sentry/api/serializers/test_project.py
Labels: Scope: Backend

#40688 feat(replays): calculate activity score in snuba query
  src/sentry/replays/query.py
  src/sentry/replays/testutils.py
  tests/sentry/replays/test_organization_replay_index.py
  tests/sentry/replays/test_project_replay_details.py
Labels: Scope: Backend

#40691 feat(replays): add url as a field alias for urls
  src/sentry/replays/query.py
Labels: Scope: Backend

#40886 ref(tests): Convert tests to rtl and tsx
  static/app/actionCreators/modal.tsx
  static/app/components/modals/reprocessEventModal.spec.tsx
  static/app/components/modals/reprocessEventModal.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
  static/app/views/dashboardsV2/widgetCard/index.spec.tsx
  static/app/views/settings/organizationApiKeys/organizationApiKeysList.spec.jsx
  static/app/views/settings/organizationApiKeys/organizationApiKeysList.spec.tsx
Labels: Scope: Frontend

#40857 ref(tests): Convert `TransactionThresholdModal` to RTL and TSX
  static/app/views/performance/transactionSummary/transactionThresholdModal.spec.jsx
  static/app/views/performance/transactionSummary/transactionThresholdModal.spec.tsx
Labels: Scope: Frontend

#40888 ref(mep): Add analytics for metrics decision
  static/app/utils/analytics/performanceAnalyticsEvents.tsx
  static/app/utils/performance/contexts/metricsCardinality.tsx
  static/app/views/performance/landing/index.tsx
Labels: Scope: Frontend

#40870 ref(deprecatedforms): Remove TrackedDeprecatedForm
  static/app/components/deprecatedforms/form.tsx
Labels: Scope: Frontend

#40869 fix(events-table): remove referrer for events table
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
Labels: Scope: Frontend

#40890 fix(ds): reorder dyn-sampling rules
  src/sentry/dynamic_sampling/rules_generator.py
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#40786 ref(issue-alerts): alert form ui changes
  static/app/views/alerts/create.spec.jsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/issue/previewTable.tsx
  static/app/views/alerts/rules/issue/ruleNode.tsx
Labels: Scope: Frontend

#40893 feat(mobile-exp): Use readable device value when available in Tag Summary
  static/app/components/group/tagFacets/index.spec.tsx
  static/app/components/group/tagFacets/index.tsx
  static/app/types/group.tsx
Labels: Scope: Frontend

#40894 fix(metrics): Fix for bug that ignores interval when validating limit
  src/sentry/snuba/metrics/query.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
Labels: Scope: Backend

#40740 feat(issue-stream): Modify issues page layout to account for saved searches sidebar
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#40636 feat(metrics): Update `apdex` implementation [TET-502]
  src/sentry/search/events/datasets/function_aliases.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/fields/snql.py
  tests/sentry/api/endpoints/test_organization_metrics.py
  tests/sentry/snuba/metrics/fields/test_base.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_snql.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#40798 feat(replays): add count number to Replays tab inside Transaction Summary
  static/app/views/performance/transactionSummary/header.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#40889 fix(discover-quick-context): Added fixes to minor bugs.
  static/app/components/shortId.tsx
  static/app/utils/discover/fieldRenderers.tsx
  static/app/utils/discover/styles.tsx
  static/app/views/eventsV2/table/quickContext.tsx
Labels: Scope: Frontend

#40738 ref(form): Merge FieldErrorReason into ControlState
  static/app/components/forms/field/controlState.tsx
  static/app/components/forms/field/fieldControl.tsx
  static/app/components/forms/field/fieldErrorReason.tsx
  static/app/components/forms/field/index.tsx
  static/app/components/forms/field/types.tsx
  static/app/components/forms/fields/projectMapperField.tsx
  static/app/components/forms/formField/controlState.tsx
  static/app/components/forms/formField/index.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.spec.jsx
Labels: Scope: Frontend

#40621 Limit creation of performance issues
  src/sentry/conf/server.py
  src/sentry/event_manager.py
  tests/sentry/event_manager/test_event_manager.py
Labels: Scope: Backend

#40892 fix(code_mappings): Files that do not match the package name should not match
  src/sentry/integrations/utils/code_mapping.py
  tests/sentry/integrations/utils/test_code_mapping.py
Labels: Scope: Backend

#40821 fix: Fix post process forwarder metric
  src/sentry/eventstream/kafka/postprocessworker.py
Labels: Scope: Backend

#40831 feat(metrics-layer): Histogram can use metrics layer yay
  src/sentry/api/endpoints/organization_events_histogram.py
  src/sentry/search/events/datasets/metrics_layer.py
  src/sentry/snuba/discover.py
  src/sentry/snuba/metrics_enhanced_performance.py
  src/sentry/snuba/metrics_performance.py
  tests/snuba/api/endpoints/test_organization_events_histogram.py
Labels: Scope: Backend

#40460 feat(profiling): profile details page aggregate views
  static/app/components/gridEditable/index.tsx
  static/app/components/gridEditable/styles.tsx
  static/app/components/searchBar.tsx
  static/app/utils/profiling/profile/importProfile.spec.tsx
  static/app/utils/profiling/profile/sentrySampledProfile.spec.tsx
  static/app/utils/profiling/profile/sentrySampledProfile.specutil.ts
  static/app/views/profiling/profileDetails.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.spec.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.tsx
  static/app/views/profiling/profileDetails/hooks/useColumnFilters.ts
  static/app/views/profiling/profileDetails/hooks/useFuseSearch.ts
  static/app/views/profiling/profileDetails/hooks/usePageLinks.ts
  static/app/views/profiling/profileDetails/hooks/useQuerystringState.ts
  static/app/views/profiling/profileDetails/hooks/useSortableColumn.ts
  static/app/views/profiling/profileDetails/index.tsx
  static/app/views/profiling/profileDetails/profileDetails.tsx
  static/app/views/profiling/profileDetails/utils.ts
  tests/js/setup.ts
Labels: Scope: Frontend

#40906 fix(all-events) add conditional on fetching attachments
  static/app/views/organizationGroupDetails/groupEvents.spec.jsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
Labels: Scope: Frontend

#40901 fix(profiling): Transform alias to input format for profile columns
  src/sentry/snuba/profiles.py
  tests/sentry/snuba/test_profiles.py
  tests/snuba/api/endpoints/test_organization_events.py
Labels: Scope: Backend

#40656 fix(MEP): Search by transformed transaction
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/search/events/datasets/metrics_layer.py
  src/sentry/snuba/metrics/mqb_query_transformer.py
  tests/sentry/search/events/test_builder.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#40855 ref(typing): add typing to search utils file
  mypy.ini
  src/sentry/api/issue_search.py
  src/sentry/models/group.py
  src/sentry/search/utils.py
Labels: Scope: Backend

#40871 feat(saved-searches): Add anayltics for creating a saved search
  static/app/components/modals/createSavedSearchModal.tsx
  static/app/components/smartSearchBar/actions.tsx
  static/app/utils/analytics/searchAnalyticsEvents.tsx
Labels: Scope: Frontend

#40921 feat(metric-layer): Allow ordering by rate
  src/sentry/snuba/metrics/fields/base.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#40878 ref(savedsearch): Remove pinned search dedupe logic
  src/sentry/api/endpoints/organization_pinned_searches.py
  src/sentry/api/endpoints/organization_searches.py
  src/sentry/models/savedsearch.py
  tests/sentry/api/endpoints/test_organization_pinned_searches.py
  tests/sentry/api/endpoints/test_organization_searches.py
Labels: Scope: Backend

#40226 feat(hybrid-cloud): Add customer domain to client config
  src/sentry/web/client_config.py
  tests/sentry/web/test_api.py
Labels: Scope: Backend

#40784 feat(replays): Conditionally render Replay touch points by project platform
  static/app/components/eventOrGroupExtraDetails.tsx
  static/app/components/eventsTable/eventsTable.spec.jsx
  static/app/components/eventsTable/eventsTable.tsx
  static/app/data/platformCategories.tsx
  static/app/utils/replays/projectSupportsReplay.tsx
  static/app/views/organizationGroupDetails/header.tsx
  static/app/views/performance/transactionSummary/header.spec.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.spec.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
  static/app/views/performance/transactionSummary/transactionEvents/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#40881 feat(code-mappings): Modify derive-code-mappings task to handle a single event
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#40874 feat(migration): Add `visiblity` to savedsearch model
  migrations_lockfile.txt
  src/sentry/api/endpoints/organization_pinned_searches.py
  src/sentry/api/endpoints/organization_searches.py
  src/sentry/migrations/0338_add_saved_search_visibility.py
  src/sentry/models/savedsearch.py
Labels: Scope: Backend

#40227 feat(hybrid-cloud): Add customerDomain type to config on frontend
  fixtures/js-stubs/config.js
  static/app/stores/configStore.spec.tsx
  static/app/types/system.tsx
Labels: Scope: Frontend

#40782 ref(selectControl): Add divider between sections
  static/app/components/forms/controls/selectControl.tsx
Labels: Scope: Frontend

#40877 feat(hybrid-cloud): Inject customer domain feature whenever a customer domain is used in the request.
  src/sentry/api/serializers/models/organization.py
  src/sentry/utils/http.py
  tests/sentry/api/endpoints/test_organization_details.py
Labels: Scope: Backend

#40875 feat(migration): Correctly mark existing savedsearch visibility
  migrations_lockfile.txt
  src/sentry/migrations/0339_mark_old_pinned_savedsearches.py
Labels: Scope: Backend

#40930 fix(releases): Use Release.is_valid_version on adding releases
  src/sentry/api/endpoints/organization_releases.py
Labels: Scope: Backend

#40922 fix(commit-context): Skip invalidating cache w/o autoassigment
  src/sentry/models/projectownership.py
  tests/sentry/models/test_projectownership.py
Labels: Scope: Backend

#40926 feat(hybrid-cloud): Add superuser cookie domain to client config
  src/sentry/web/client_config.py
  tests/sentry/web/test_api.py
Labels: Scope: Backend

#40862 chore(hybrid-cloud): mypy fixes and organization improvement
  mypy.ini
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/organization.py
  src/sentry/services/hybrid_cloud/project_key.py
  src/sentry/utils/auth.py
  src/sentry/web/client_config.py
  src/sentry/web/frontend/auth_login.py
  src/sentry/web/frontend/base.py
  src/sentry/web/frontend/restore_organization.py
  tests/conftest.py
  tests/sentry/services/test_project_key_service.py
Labels: Scope: Backend

#40879 feat(savedsearch): Serialize visibility for savedsearch
  src/sentry/api/serializers/models/savedsearch.py
  tests/sentry/api/serializers/test_saved_search.py
Labels: Scope: Backend

#40927 feat(hybrid-cloud): Consume superUserCookieDomain from client config
  fixtures/js-stubs/config.js
  static/app/bootstrap/index.tsx
  static/app/components/acl/role.spec.tsx
  static/app/types/system.tsx
  static/app/utils/isActiveSuperuser.tsx
Labels: Scope: Frontend

#40932 ref(monitors): Add logger statements for missed/error checkins
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/models/monitor.py
Labels: Scope: Backend

#40744 feat(saved-searches): Add a saved searches sidebar and header button
  static/app/views/issueList/header.tsx
  static/app/views/issueList/overview.tsx
  static/app/views/issueList/savedIssueSearches.spec.tsx
  static/app/views/issueList/savedIssueSearches.tsx
Labels: Scope: Frontend

#40880 ref(migration): Remove deprecated savedsearch columns (db op)
  migrations_lockfile.txt
  src/sentry/migrations/0340_drop_deprecated_savedsearch_columns_db_op.py
Labels: Scope: Backend

#40934 feat(code-mappings): Add option for code mappings
  src/sentry/options/defaults.py
Labels: Scope: Backend

#40613 feat(monitors): Restrict monitor actions to organization admin properly
  static/app/views/monitors/monitorHeaderActions.tsx
Labels: Scope: Frontend

#40898 feat(saved-searches): Add delete option for saved searches
  static/app/views/issueList/overview.tsx
  static/app/views/issueList/savedIssueSearches.spec.tsx
  static/app/views/issueList/savedIssueSearches.tsx
Labels: Scope: Frontend

#40938 DEVINFRA-85 Log a message to explain email and password request
  scripts/lib.sh
Labels: Scope: Backend

#40935 feat(savedsearch): Use visibility in OrganizationPinnedSearchEndpoint
  src/sentry/api/endpoints/organization_pinned_searches.py
  src/sentry/models/savedsearch.py
  tests/sentry/api/endpoints/test_organization_pinned_searches.py
  tests/sentry/api/endpoints/test_organization_searches.py
Labels: Scope: Backend

#40945 fix(migrations): Mark reconstrain_savedsearch_pinning_fields is_dangerous
  src/sentry/migrations/0341_reconstrain_savedsearch_pinning_fields.py
Labels: Scope: Backend

#40949 chore(sidebar): Fix toPathWithoutReferrer typo
  static/app/components/sidebar/sidebarItem.tsx
Labels: Scope: Frontend

#40897 fix(profiling): remove broken stacks assignment
  src/sentry/profiles/task.py
Labels: Type: Bug, Scope: Backend

#40956 ref(settings): Move disabled description tooltip to field
  static/app/components/forms/field/fieldControl.tsx
  static/app/components/forms/fields/booleanField.tsx
  static/app/components/forms/fields/selectField.tsx
  static/app/components/forms/formField/index.tsx
  static/app/views/settings/project/dynamicSampling/dynamicSampling.spec.tsx
Labels: Scope: Frontend

#40884 doc(project-settings): Provide examples for allowed domains
  static/app/data/forms/projectGeneralSettings.tsx
Labels: Scope: Frontend

#40851 feat(mobile-exp): display multiple screenshots per event
  static/app/components/events/eventTagsAndScreenshot/dataSection.tsx
  static/app/components/events/eventTagsAndScreenshot/index.spec.tsx
  static/app/components/events/eventTagsAndScreenshot/index.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
  static/app/components/events/eventTagsAndScreenshot/tags.tsx
  static/app/components/events/interfaces/performance/spanEvidence.tsx
Labels: Scope: Frontend

#40902 feat(mobile-exp): Highlight mobile tag if matching event
  static/app/components/group/tagFacets/index.spec.tsx
  static/app/components/group/tagFacets/tagBreakdown.tsx
Labels: Scope: Frontend

#40948 feat(hybrid-cloud): Set frontend tags on Sentry events emitted whenever a customer domain is used
  static/app/bootstrap/initializeSdk.tsx
Labels: Scope: Frontend

#40963 fix(perf): Remove suspect spans flag
  src/sentry/conf/server.py
  src/sentry/event_manager.py
  src/sentry/features/__init__.py
  src/sentry/options/defaults.py
  src/sentry/relay/config/__init__.py
  tests/relay_integration/test_integration.py
  tests/sentry/api/serializers/test_event.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config.pysnap
  tests/sentry/relay/test_config.py
  tests/snuba/api/endpoints/test_organization_events_spans_histogram.py
  tests/snuba/api/endpoints/test_organization_events_spans_performance.py
Labels: Scope: Backend

#40931 fix: check the bucketed_time is in the index before accessing
  src/sentry/snuba/metrics/query_builder.py
Labels: Scope: Backend

#40960 chore(dashboards): Remove release widget flags frontend
  static/app/views/dashboardsV2/controls.tsx
  static/app/views/dashboardsV2/dashboard.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/dataSetStep.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilderDataset.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetLibrary/index.tsx
Labels: Scope: Frontend, Scope: Backend

#40923 feat(growth): add abstract onboarding model
  src/sentry/models/organizationonboardingtask.py
Labels: Scope: Backend

#40903 ref(perf): Remove suspect spans feature flag FE
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/views/performance/transactionSummary/header.spec.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.spec.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/opsFilter.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/index.tsx
  static/app/views/performance/transactionSummary/transactionSpans/suspectSpansTable.spec.tsx
Labels: Scope: Frontend

#40689 feat(growth): sandbox walkthrough start guide
  static/app/components/assistant/getGuidesContent.tsx
  static/app/components/demo/demoHeader.tsx
  static/app/components/onboardingWizard/progressHeader.tsx
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/components/onboardingWizard/task.tsx
  static/app/components/onboardingWizard/taskConfig.tsx
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/components/stream/group.tsx
  static/app/stores/demoWalkthroughStore.tsx
  static/app/types/onboarding.tsx
  static/app/utils/demoMode.tsx
Labels: Scope: Frontend

#40907 ref(perf): Remove suspect spans feature flag BE
  src/sentry/api/endpoints/organization_events_span_ops.py
  src/sentry/api/endpoints/organization_events_spans_performance.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/acceptance/test_performance_span_summary.py
  tests/snuba/api/endpoints/test_organization_events_span_ops.py
  tests/snuba/api/endpoints/test_organization_events_spans_performance.py
Labels: Scope: Backend

#40900 fix(mobile-exp): Updates the mobile issue tag selector to always use the first available tag as the default selection
  static/app/components/group/tagFacets/index.tsx
Labels: Scope: Frontend

#40944 feat(monitors): Add landing panel for empty state
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#40854 ref: Change toast message for assigning issue to non-team member
  static/app/components/assigneeSelector.spec.jsx
  static/app/stores/groupStore.tsx
Labels: Scope: Frontend

#40950 fix(hybrid-cloud): Propagate organizations:customer-domains feature if a customer domain is used
  src/sentry/web/client_config.py
  tests/sentry/web/test_api.py
Labels: Scope: Backend

#40939 feat(saved-searches): Add create saved search button to sidebar
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/overview.tsx
  static/app/views/issueList/savedIssueSearches.spec.tsx
  static/app/views/issueList/savedIssueSearches.tsx
Labels: Scope: Frontend

#40605 ref(feature-flag): Remove feature flag BE code for ops breakdown
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
  tests/relay_integration/test_integration.py
  tests/relay_integration/test_metrics_extraction.py
  tests/sentry/api/endpoints/test_relay_projectconfigs.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v2.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config.pysnap
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#40933 chore(migrations): Remove `atomic` from migration template
  src/sentry/new_migrations/migrations.py
  src/sentry/new_migrations/monkey/__init__.py
Labels: Scope: Backend

#40909 feat(saved-searches): Add is_global, visibility, and query to select saved search analytics event
  static/app/types/group.tsx
  static/app/utils/analytics/searchAnalyticsEvents.tsx
  static/app/views/issueList/filters.spec.tsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#40525 fix(jira): Handle perf issue title
  src/sentry/integrations/mixins/issues.py
  src/sentry/rules/actions/integrations/create_ticket/utils.py
  tests/sentry/integrations/jira/test_notify_action.py
Labels: Scope: Backend

#40674 feat(perf-issues): Parametrize DB span SQL queries before hashing
  src/sentry/spans/grouping/strategy/base.py
  src/sentry/spans/grouping/strategy/config.py
  tests/sentry/spans/grouping/test_strategy.py
Labels: Scope: Backend

#40735 ref(performance): Clean up tests related to autogrouping and remove autogroup feature flag
  static/app/components/events/interfaces/spans/spanBar.tsx
  static/app/components/events/interfaces/spans/traceView.spec.tsx
  tests/js/sentry-test/performance/utils.ts
Labels: Scope: Frontend

#40737 ref(discover): Switch params to a dataclass
  mypy.ini
  src/sentry/api/bases/organization_events.py
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/endpoints/organization_events_trends.py
  src/sentry/api/serializers/rest_framework/dashboard.py
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/base.py
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/field_aliases.py
  src/sentry/search/events/datasets/filter_aliases.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/search/events/datasets/profiles.py
  src/sentry/search/events/types.py
  src/sentry/snuba/discover.py
  src/sentry/snuba/metrics_enhanced_performance.py
  src/sentry/snuba/metrics_performance.py
  src/sentry/snuba/profiles.py
  tests/sentry/search/events/test_builder.py
  tests/sentry/search/events/test_filter.py
  tests/sentry/snuba/metrics/test_query.py
  tests/sentry/snuba/metrics/test_query_builder.py
  tests/sentry/snuba/test_discover_query.py
  tests/sentry/snuba/test_entity_subscriptions.py
  tests/sentry/snuba/test_tasks.py
  tests/snuba/api/endpoints/test_organization_events.py
Labels: Scope: Backend

#40760 ref(perf): Remove autogroup flag from BE code
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/acceptance/test_organization_events_v2.py
Labels: Scope: Backend

#39868 feat(team-roles): Better handling of retired roles with feature flag
  src/sentry/api/endpoints/organization_member/details.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/api/serializers/models/organization_member/expand/roles.py
  src/sentry/api/serializers/models/role.py
  src/sentry/conf/server.py
  src/sentry/models/organizationmember.py
  src/sentry/roles/manager.py
  tests/sentry/api/endpoints/test_organization_member_details.py
Labels: Scope: Backend

#40969 security(deps): bump cryptography to 38.0.3
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#40929 ref: Refactor eventWaiter firstIssue field to allow for booleans
  static/app/utils/eventWaiter.tsx
  static/app/views/onboarding/components/firstEventFooter.tsx
  static/app/views/onboarding/components/firstEventIndicator.tsx
Labels: Scope: Frontend

#40973 feat(code-mappings): Add flag check before deriving code mappings
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#40978 ref: Rename onboardingCard.tsx to match the name of the default export
  static/app/components/onboardingWizard/onboardingProjectsCard.tsx
  static/app/components/onboardingWizard/taskConfig.tsx
Labels: Scope: Frontend

#40920 feat(replays): Create a basic onboarding page when people visit the replay index
  docs-ui/stories/views/onboardingPanel.stories.js
  static/app/components/onboardingPanel.tsx
  static/app/types/project.tsx
  static/app/views/replays/list/replayOnboardingPanel.tsx
  static/app/views/replays/replays.tsx
  tests/acceptance/test_replay_list.py
Labels: Scope: Frontend

#40908 fix(Superuser modal): Removed case where we there isn't an API call
  static/app/components/modals/sudoModal.tsx
Labels: Scope: Frontend

#40687 feat(growth): end modal for sandbox walkthrough
  static/app/actionCreators/guides.tsx
  static/app/actionCreators/modal.tsx
  static/app/bootstrap/exportGlobals.tsx
  static/app/components/assistant/guideAnchor.tsx
  static/app/components/modals/demoEndModal.spec.tsx
  static/app/components/modals/demoEndModal.tsx
  static/app/components/onboardingWizard/modalTask.tsx
  static/app/utils/demoMode.tsx
Labels: Scope: Frontend

#40882 feat(code-mappings): Add code mappings task to post process
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#40941 fix(forms): Fix form field alignment
  static/app/components/forms/field/fieldControlState.tsx
  static/app/components/forms/field/fieldWrapper.tsx
Labels: Scope: Frontend

#39558 feat(Replays): Publish replay delete messages synchronously
  src/sentry/replays/tasks.py
Labels: Scope: Backend

#40977 test(js): Convert the rest of IssueListOverview to RTL
  static/app/views/issueList/overview.spec.jsx
Labels: Scope: Frontend

#40982 ref(dropdownMenu): Remove `showDividers` prop & modify default divider rules
  static/app/components/actions/resolve.tsx
  static/app/components/dropdownMenu.tsx
  static/app/components/dropdownMenuItem.tsx
  static/app/components/menuListItem.tsx
Labels: Scope: Frontend
