Repository getsentry/sentry, pull requests merged in 2022-12, with the labels that each got.

#41827 fix(dyn-sampling): Do not send old rules to the Relay [TET-576]
  src/sentry/api/endpoints/project_details.py
  src/sentry/models/release.py
  src/sentry/relay/config/__init__.py
  tests/acceptance/test_project_settings_sampling_deprecated.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/api/endpoints/test_relay_projectconfigs.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v2.py
  tests/sentry/models/test_release.py
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#41829 feat(sampling): Disable LA actions [TET-513]
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/samplingPromo.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.spec.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: Scope: Frontend

#41649 feat(perf-issues): parametrize SAVEPOINTs in db span hashes
  src/sentry/spans/grouping/strategy/base.py
  tests/sentry/spans/grouping/test_strategy.py
Labels: Scope: Backend

#41870 feat(mobile-exp): adds some tracking for project and performance pages
  static/app/views/performance/content.tsx
  static/app/views/projectDetail/index.tsx
Labels: Scope: Frontend

#41920 Fix: `list` object has no attribute `get`
  src/sentry/rules/conditions/event_attribute.py
Labels: Scope: Backend

#41864 ref(perf-issues): Improve Python typing in issue detection
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#41912 feat(perf-issues): N+1 API Calls detector improvements II
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#41914 feat(dashboards): adds retry with backoff to doDiscoverQuery and updates event widgets to use
  static/app/utils/discover/genericDiscoverQuery.spec.tsx
  static/app/utils/discover/genericDiscoverQuery.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
Labels: Scope: Frontend

#41906 feat(profiling): computeConfigView w/ highlightFrames
  static/app/components/profiling/flamegraph.tsx
  static/app/utils/profiling/gl/utils.spec.tsx
  static/app/utils/profiling/gl/utils.ts
Labels: Scope: Frontend

#41929 feat(perf): Instrument the span tree
  static/app/components/events/interfaces/spans/spanTree.tsx
Labels: Scope: Frontend

#41845 ref(tsc): drop ts monitoring
  .github/workflows/frontend.yml
  .github/workflows/scripts/monitor-typescript.ts
Labels: Scope: Frontend

#41905 feat(profiling): optimize gl draws
  static/app/components/profiling/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/differentialFlamegraph.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/renderers/flamegraphRenderer.spec.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer.tsx
  static/app/utils/profiling/renderers/shaders.tsx
Labels: Scope: Frontend

#41930 feat(issue-alert): use cache and add referrer
  src/sentry/rules/history/preview.py
Labels: Scope: Backend

#41928 feat(perf-issues): N+1 API Calls detector improvements III
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#41889 fix(auth) Redirect to customer domain on login more often
  src/sentry/constants.py
  src/sentry/web/frontend/auth_login.py
  src/sentry/web/frontend/base.py
  tests/sentry/web/frontend/test_auth_login.py
Labels: Scope: Backend

#41907 feat(hybrid-cloud): Set active sidebar menu item based on the normalized route
  static/app/components/sidebar/sidebarItem.tsx
Labels: Scope: Frontend

#41880 ref(replays): Refactor Replay Timeline to have fewer DOM nodes as crumbs/duration increases
  static/app/components/replays/breadcrumbs/gridlines.tsx
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx
  static/app/components/replays/breadcrumbs/timeline.tsx
Labels: Scope: Frontend

#41911 fix(metrics): Add organization to sentry.mail_adapter.notify
  src/sentry/notifications/notifications/rules.py
Labels: Scope: Backend

#41909 feat(derived_code_mappings): Support Javascript
  src/sentry/integrations/utils/code_mapping.py
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/integrations/utils/fixtures/sentry_files.json
  tests/sentry/integrations/utils/test_code_mapping.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#41926 fix(discover-quick-context): Removed GroupStore and assigneeSelector usage.
  static/app/components/group/assignedTo.tsx
  static/app/views/eventsV2/table/quickContext.spec.tsx
  static/app/views/eventsV2/table/quickContext.tsx
Labels: Scope: Frontend

#41913 feat(issue-details): Add ability to sort to breadcrumbs
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/index.tsx
  static/app/components/events/interfaces/searchBarAction.tsx
Labels: Scope: Frontend

#41933 feat(derive-code-mappings): For dry run orgs, process Javascript events
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#41900 feat(_admin): Sentry Options readonly endpoint
  src/sentry/api/endpoints/system_options.py
  src/sentry/options/__init__.py
  src/sentry/options/defaults.py
  src/sentry/options/manager.py
  tests/sentry/api/endpoints/test_system_options.py
Labels: Scope: Backend

#41939 ref(profiling): Send message on potential bad symbolication
  src/sentry/profiles/task.py
Labels: Scope: Backend

#41901 feat(perf-issues): Add issue type to latest
  src/sentry/api/serializers/models/event.py
  tests/sentry/api/serializers/test_event.py
Labels: Scope: Backend

#41915 deps(ui): Bump sentry global-search package
  package.json
  yarn.lock
Labels: Scope: Frontend

#41803 feat: Arroyo 2.0.0
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/eventstream/kafka/consumer_strategy.py
  src/sentry/eventstream/kafka/synchronized.py
  src/sentry/ingest/billing_metrics_consumer.py
  src/sentry/replays/consumers/recording/process_recording.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/sentry_metrics/consumers/indexer/common.py
  src/sentry/sentry_metrics/consumers/indexer/multiprocess.py
  src/sentry/sentry_metrics/consumers/indexer/routing_producer.py
  tests/sentry/eventstream/kafka/test_consumer_strategy.py
  tests/sentry/eventstream/kafka/test_synchronized.py
  tests/sentry/ingest/billing_metrics_consumer/test_billing_metrics_consumer_kafka.py
  tests/sentry/region_to_control/test_region_to_control_consumer.py
  tests/sentry/replays/consumers/recording_consumer/test_consumer.py
  tests/sentry/sentry_metrics/consumers/test_routing_producer.py
  tests/sentry/sentry_metrics/consumers/test_slicing_router.py
  tests/sentry/sentry_metrics/test_batch.py
  tests/sentry/sentry_metrics/test_last_seen_updater.py
  tests/sentry/sentry_metrics/test_multiprocess_steps.py
  tests/sentry/sentry_metrics/test_parallel_indexer.py
Labels: Scope: Backend

#41627 feat(workflow): Add issue owners reason to issue alert email
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/notifications/notifications/rules.py
  src/sentry/notifications/utils/participants.py
  src/sentry/templates/sentry/emails/email-styles.html
  src/sentry/templates/sentry/emails/issue_alert_base.html
  src/sentry/web/frontend/debug/mail.py
  tests/sentry/notifications/utils/test_participants.py
Labels: Scope: Backend

#41934 fix(metric_alerts): If session dataset is passed when creating a metric alert, coerce it to metrics
  src/sentry/incidents/serializers/alert_rule.py
Labels: Scope: Backend

#41917 feat(promotions): updated components for promotions checkout UI
  static/app/views/settings/components/settingsPageHeader.tsx
Labels: Scope: Frontend

#41961 feat(sampling): Remove LA docs links
  static/app/views/settings/project/server-side-sampling/samplingPromo.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: Scope: Frontend

#41899 ref(perf-issues): Remove unused duplicate span hash detector
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#41945 fix(perf-issues): Make the issue type consistent
  src/sentry/api/serializers/models/event.py
  tests/sentry/api/serializers/test_event.py
Labels: Scope: Backend

#41856 feat(performance-issue): Remove some n+1 hardcoding
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/performance/spanEvidence.spec.tsx
  static/app/components/events/interfaces/performance/spanEvidence.tsx
  static/app/components/events/interfaces/performance/spanEvidenceKeyValueList.tsx
  static/app/components/events/interfaces/performance/utils.tsx
  static/app/components/groupPreviewTooltip/spanEvidencePreview.tsx
  static/app/types/event.tsx
  static/app/types/group.tsx
  tests/js/sentry-test/performance/utils.ts
Labels: Scope: Frontend

#41956 fix(test): Actually render TransactionHeader component in a test
  static/app/views/performance/transactionSummary/header.spec.tsx
Labels: Scope: Frontend

#41955 fix(superuser): Remove un-used variable current_datetime
  src/sentry/auth/superuser.py
Labels: Scope: Backend

#41954 fix(api): Remove un-used variable team_list
  src/sentry/api/endpoints/organization_projects.py
Labels: Scope: Backend

#41946 feat(discover-quick-context-issues): Design Changes.
  static/app/views/eventsV2/table/quickContext.spec.tsx
  static/app/views/eventsV2/table/quickContext.tsx
Labels: Scope: Frontend

#41922 feat(command-palette): Add open in production option
  static/app/components/search/sources/commandSource.tsx
Labels: Scope: Frontend

#41806 fix(issue-search): properly handle negation logic when searching on Group message
  src/sentry/search/snuba/backend.py
  src/sentry/search/snuba/executors.py
  src/sentry/types/issues.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#41871 feat(alert-preview): support only freq conditions
  src/sentry/rules/history/preview.py
  src/sentry/rules/history/preview_strategy.py
  src/sentry/types/condition_activity.py
  tests/sentry/rules/history/test_preview.py
Labels: Scope: Backend

#41980 fix(global-search): Remove scroll logic on mouse hover and keep open after focus is lost
  static/app/components/search/index.tsx
  static/app/components/search/searchResultWrapper.tsx
Labels: Scope: Frontend

#41960 feat(replays): Replay Details loading placeholders should be 100% height/consistently
  static/app/utils/replays/hooks/useExtractedCrumbHtml.tsx
  static/app/views/replays/detail/console/index.tsx
  static/app/views/replays/detail/domMutations/index.tsx
  static/app/views/replays/detail/focusArea.tsx
  static/app/views/replays/detail/memoryChart.tsx
  static/app/views/replays/detail/network/index.tsx
  static/app/views/replays/detail/network/useNetworkFilters.tsx
  static/app/views/replays/detail/utils.tsx
Labels: Scope: Frontend

#41977 chore(deps): bump storybook to 6.5.14
  package.json
  yarn.lock
Labels: Scope: Frontend

#41882 bug(modals): Fix Modal padding so Backdrop is clickable on the top edge
  static/app/components/globalModal/index.tsx
  static/app/views/performance/transactionSummary/transactionThresholdModal.tsx
Labels: Scope: Frontend

#41983 ref(plugin): split 'to' phone numbers without regex in Twilio plugin
  src/sentry_plugins/twilio/plugin.py
  tests/sentry_plugins/twilio/test_plugin.py
Labels: Scope: Backend

#41995 feat(issue-alert): use prefix sum for calculating bucket sums
  src/sentry/rules/conditions/event_frequency.py
  src/sentry/rules/history/preview.py
  src/sentry/types/condition_activity.py
Labels: Scope: Backend

#41958 fix(issue-alert): Do not sort array of numbers alphabetically
  static/app/views/alerts/rules/issue/index.tsx
Labels: Scope: Frontend

#41982 fix(domains) Fix settings/account link translation
  static/app/utils/withDomainRequired.spec.tsx
  static/app/utils/withDomainRequired.tsx
Labels: Scope: Frontend

#41969 feat(discover-homepage): Default feature flag to True
  src/sentry/conf/server.py
  tests/sentry/api/serializers/test_organization.py
Labels: Scope: Backend

#41862 bug(replays): Fix overflow of breadcrumbs inside Timeline events
  static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx
Labels: Scope: Frontend

#41777 feat(derive-code-mappings): Add caching support for fetching files
  src/sentry/integrations/github/client.py
  tests/sentry/integrations/github/test_client.py
  tests/sentry/integrations/github/test_integration.py
Labels: Scope: Backend

#42002 fix(twilio): split on any whitespace between phone numbers
  src/sentry_plugins/twilio/plugin.py
  tests/sentry_plugins/twilio/test_plugin.py
Labels: Scope: Backend

#41888 fix(replay): Move setBufferTime into useEffect
  static/app/components/replays/replayContext.tsx
Labels: Scope: Frontend

#41802 feat(profiling): minimap resize
  static/app/components/profiling/flamegraphZoomViewMinimap.tsx
Labels: Scope: Frontend

#42003 fix(profiling): fix search matching
  static/app/components/profiling/flamegraphSearch.spec.tsx
  static/app/components/profiling/flamegraphSearch.tsx
  static/app/utils/profiling/validators/regExp.tsx
Labels: Scope: Frontend

#41886 feat(replays): Raise MessageRejected if the queue is full
  src/sentry/replays/consumers/recording/process_recording.py
Labels: Scope: Backend

#41975 feat(span-tree): Instrument toggle interactions on span tree
  static/app/components/events/interfaces/spans/spanBar.tsx
  static/app/components/events/interfaces/spans/spanGroupBar.tsx
  static/app/components/events/interfaces/spans/spanTree.tsx
  static/app/components/events/interfaces/spans/traceView.tsx
Labels: Scope: Frontend

#42007 api: Re-raise APIError's from host exceptions
  src/sentry/shared_integrations/client/base.py
Labels: Scope: Backend

#42010 fix(twilio): allow phone numbers to split with either a comma or any whitespace
  src/sentry_plugins/twilio/plugin.py
  tests/sentry_plugins/twilio/test_plugin.py
Labels: Scope: Backend

#41984 fix(selectControl): Remove extra top padding
  static/app/components/forms/controls/selectControl.tsx
Labels: Scope: Frontend

#41919 ref(breadcrumbs): Remove breadcrumb-linked-event feature flag and unused related code
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/exception.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/http.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/index.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/linkedEvent.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/index.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.tsx
  static/app/components/events/interfaces/breadcrumbs/index.tsx
  static/app/views/eventsV2/eventDetails/content.tsx
  static/app/views/eventsV2/eventDetails/index.tsx
  static/app/views/organizationGroupDetails/groupEventDetails/groupEventDetails.tsx
  static/app/views/performance/transactionDetails/content.tsx
  static/app/views/performance/transactionDetails/index.tsx
  static/app/views/sharedGroupDetails/index.tsx
Labels: Scope: Frontend, Scope: Backend

#42011 fix(profiling): drop default focus border
  static/app/components/profiling/flamegraphZoomView.tsx
Labels: Scope: Frontend

#41824 ref(replays): Refactor ScrubberMouseTracking into a hook
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/player/useScrubberMouseTracking.tsx
  static/app/components/replays/replayController.tsx
  static/app/utils/replays/hooks/useMouseTracking.tsx
  static/app/views/replays/detail/layout/splitPanel.tsx
Labels: Scope: Frontend

#41940 ref(discover): Remove frontend feature flags for events api usage
  static/app/components/charts/simpleTableChart.tsx
  static/app/components/discover/transactionsList.spec.jsx
  static/app/components/discover/transactionsList.tsx
  static/app/components/modals/widgetViewerModal.spec.tsx
  static/app/components/modals/widgetViewerModal.tsx
  static/app/components/modals/widgetViewerModal/widgetViewerTableCell.tsx
  static/app/components/performance/searchBar.spec.tsx
  static/app/components/performance/searchBar.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/detail.spec.jsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilderDataset.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilderSortBy.spec.tsx
  static/app/views/dashboardsV2/widgetCard/chart.tsx
  static/app/views/dashboardsV2/widgetCard/index.spec.tsx
  static/app/views/dashboardsV2/widgetCard/widgetQueries.spec.jsx
  static/app/views/eventsV2/homepage.spec.tsx
  static/app/views/eventsV2/results.spec.tsx
  static/app/views/eventsV2/table/index.tsx
  static/app/views/eventsV2/table/tableView.spec.jsx
  static/app/views/eventsV2/table/tableView.tsx
  static/app/views/performance/content.spec.tsx
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  static/app/views/performance/table.spec.tsx
  static/app/views/performance/table.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.spec.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/durationPercentileChart/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/sidebarCharts.tsx
  static/app/views/performance/transactionSummary/transactionOverview/statusBreakdown.tsx
  static/app/views/performance/transactionSummary/transactionOverview/userStats.tsx
Labels: Scope: Frontend

#42014 logging(weekly-email): adds logging for key errors
  src/sentry/tasks/weekly_reports.py
Labels: Scope: Backend

#41893 perf: Do not clone api response objects so often in the js api client
  static/app/__mocks__/api.tsx
  static/app/api.tsx
Labels: Scope: Frontend

#41820 fix(js): Prevent request errors from creating Sentry issues
  static/app/actionCreators/members.tsx
  static/app/components/smartSearchBar/index.tsx
  static/app/stores/persistedStore.spec.tsx
  static/app/stores/persistedStore.tsx
  static/app/views/settings/organizationTeams/teamSettings/index.tsx
  tests/js/sentry-test/queryClient.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#41974 feat(issue-alerts): better preview/notification tests messages
  static/app/views/alerts/create.spec.jsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/issue/previewTable.tsx
Labels: Scope: Frontend

#41902 ref(ecosystem): Convert stacktrace link component to hooks
  static/app/actionCreators/prompts.tsx
  static/app/components/events/interfaces/frame/context.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.spec.jsx
  static/app/components/events/interfaces/frame/stacktraceLink.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
  static/app/components/events/interfaces/frame/utils.tsx
Labels: Scope: Frontend

#41947 ref(replays): Move mapRRWebAttachments out of useReplayData and into ReplayReader
  fixtures/js-stubs/replayReaderParams.js
  static/app/components/events/eventReplay/replayPreview.spec.tsx
  static/app/utils/replays/flattenListOfObjects.spec.tsx
  static/app/utils/replays/flattenListOfObjects.tsx
  static/app/utils/replays/hooks/useReplayData.spec.jsx
  static/app/utils/replays/hooks/useReplayData.tsx
  static/app/utils/replays/replayDataUtils.spec.tsx
  static/app/utils/replays/replayDataUtils.tsx
  static/app/utils/replays/replayReader.tsx
Labels: Scope: Frontend

#42020 chore(deletions) Add deletion id to log messages
  src/sentry/tasks/deletion.py
Labels: Scope: Backend

#42015 feat(saved-searches): Add analytics event for toggling the saved searches sidebar
  static/app/utils/analytics/searchAnalyticsEvents.tsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#42008 feat(replays): Improve search/empty table consistency in Replay Details page
  docs-ui/stories/views/emptyStateWarning.stories.js
  static/app/components/emptyStateWarning.tsx
  static/app/views/replays/detail/console/index.tsx
  static/app/views/replays/detail/domMutations/index.tsx
  static/app/views/replays/detail/issueList.tsx
  static/app/views/replays/detail/network/index.tsx
Labels: Scope: Frontend

#41988 feat(hybrid-cloud): Redirect to customer domain if customer domain is enabled for an organization
  src/sentry/utils/http.py
  src/sentry/web/frontend/react_page.py
  tests/sentry/web/frontend/test_react_page.py
Labels: Scope: Backend

#42017 ref(profiling): drop node profile
  static/app/types/profiling.d.ts
  static/app/utils/profiling/guards/profile.tsx
  static/app/utils/profiling/profile/importProfile.spec.tsx
  static/app/utils/profiling/profile/importProfile.tsx
Labels: Scope: Frontend

#41873 feat(perf): Add interactive title to widgets
  static/app/views/performance/landing/widgets/components/widgetContainer.tsx
  static/app/views/performance/landing/widgets/components/widgetHeader.tsx
  static/app/views/performance/landing/widgets/types.tsx
  static/app/views/performance/landing/widgets/widgets/histogramWidget.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/singleFieldAreaWidget.tsx
  static/app/views/performance/landing/widgets/widgets/trendsWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  tests/acceptance/test_performance_landing.py
Labels: Scope: Frontend

#42022 fix(project options): Store feedback:branding options correctly
  src/sentry/api/serializers/models/project.py
  tests/sentry/api/endpoints/test_project_details.py
Labels: Scope: Backend

#41720 bug(replays): Fix loading and paging through the Issues>Replays tab
  static/app/components/replays/useReplaysCount.spec.tsx
  static/app/components/replays/useReplaysCount.tsx
  static/app/utils/replays/fetchReplayList.tsx
  static/app/utils/replays/hooks/useReplayList.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.spec.tsx
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.tsx
  static/app/views/organizationGroupDetails/groupReplays/index.tsx
  static/app/views/replays/replays.tsx
Labels: Scope: Frontend

#41948 ref(replays): Download replay attachments optimistically and in parallel
  static/app/utils/replays/hooks/useReplayData.tsx
Labels: Scope: Frontend

#41918 fix(ecosystem): Hide stack link on error unsupported platforms
  static/app/components/events/interfaces/frame/stacktraceLink.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
Labels: Scope: Frontend

#41757 ref(metrics): Change implementation of latest release [TET-555]
  src/sentry/dynamic_sampling/latest_release_booster.py
  src/sentry/dynamic_sampling/latest_release_ttas.py
  src/sentry/dynamic_sampling/rules_generator.py
  src/sentry/event_manager.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#41874 fix(2fa): Wonky failed device icon
  static/less/auth.less
Labels: Scope: Frontend

#42018 feat(kafka): add ingest-occurences to server config
  src/sentry/conf/server.py
Labels: Scope: Backend

#41834 feat(createuser): Support multiple user creation
  src/sentry/runner/commands/createuser.py
Labels: Scope: Backend

#42023 fix(deletions) Fix more issues blocking deletions
  src/sentry/discover/models.py
  src/sentry/rules/filters/latest_release.py
Labels: Scope: Backend

#42069 feat(github): Support to track Github API rate limit
  src/sentry/integrations/github/client.py
  tests/sentry/integrations/github/test_client.py
Labels: Scope: Backend

#42021 feat(perf-issues): N+1 API Calls detector improvements IV
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#42072 chore(discover-quick-context): Directory structure.
  static/app/utils/analytics/discoverAnalyticsEvents.tsx
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/eventsV2/table/quickContext.spec.tsx
  static/app/views/eventsV2/table/quickContext.tsx
  static/app/views/eventsV2/table/quickContext/eventContext.spec.tsx
  static/app/views/eventsV2/table/quickContext/eventContext.tsx
  static/app/views/eventsV2/table/quickContext/issueContext.spec.tsx
  static/app/views/eventsV2/table/quickContext/issueContext.tsx
  static/app/views/eventsV2/table/quickContext/quickContextWrapper.spec.tsx
  static/app/views/eventsV2/table/quickContext/quickContextWrapper.tsx
  static/app/views/eventsV2/table/quickContext/releaseContext.spec.tsx
  static/app/views/eventsV2/table/quickContext/releaseContext.tsx
  static/app/views/eventsV2/table/quickContext/styles.tsx
  static/app/views/eventsV2/table/quickContext/testUtils.tsx
  static/app/views/eventsV2/table/quickContext/utils.tsx
  static/app/views/eventsV2/table/tableView.tsx
Labels: Scope: Frontend

#42080 feat(view-hierarchies): Add feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#42016 fix(profiling): drop tid if we have name
  static/app/components/profiling/threadSelector.tsx
Labels: Scope: Frontend

#42004 feat(alert-preview): user frequency and interval comparison
  src/sentry/rules/conditions/event_frequency.py
  src/sentry/rules/history/preview.py
  src/sentry/types/condition_activity.py
  tests/sentry/rules/history/test_preview.py
Labels: Scope: Backend

#42082 feat(derive_code_mappings): Use lock to get_trees_for_org()
  src/sentry/tasks/derive_code_mappings.py
Labels: Scope: Backend

#42088 ref(analytics): convert analytics for org dashboards
  static/app/views/dashboardsV2/orgDashboards.tsx
Labels: Scope: Frontend

#42089 fix(metrics): Add missing `spans.ui` span op
  src/sentry/search/events/constants.py
Labels: Scope: Backend

#42009 feat(alert-preview): add inbox reason to preview
  src/sentry/api/endpoints/project_rule_preview.py
  tests/sentry/rules/history/endpoints/test_project_rule_preview.py
Labels: Scope: Backend

#42091 chore: Delete unneeded "pass" keyword
  src/sentry/analytics/base.py
  src/sentry/api/endpoints/auth_index.py
  src/sentry/eventstream/snuba.py
Labels: Scope: Backend

#41959 feat(hybrid-cloud): Redirect for non-customer domain url paths
  src/sentry/web/frontend/react_page.py
  src/sentry/web/urls.py
  tests/sentry/web/frontend/test_auth_login.py
  tests/sentry/web/frontend/test_react_page.py
Labels: Scope: Backend

#42099 fix(superuser): Handle request error
  static/app/components/superuserAccessForm.tsx
Labels: Scope: Frontend

#42087 feat(weekly-email): adds another debug logging statement
  src/sentry/tasks/weekly_reports.py
Labels: Scope: Backend

#42104 bug(replays): Fix conditions for showing the Configure Session Replay CTA inside Issue Details
  static/app/components/events/eventReplay/index.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx
  static/app/utils/replays/hooks/useReplayOnboarding.tsx
  static/app/views/replays/replays.tsx
Labels: Scope: Frontend

#33197 feat(quotas): Per-project abuse quotas
  src/sentry/event_manager.py
  src/sentry/options/defaults.py
  src/sentry/quotas/base.py
  src/sentry/quotas/redis.py
  tests/sentry/quotas/test_redis.py
Labels: Scope: Backend

#42106 fix(guideAnchor): Fix arrow position
  static/app/components/assistant/guideAnchor.tsx
Labels: Scope: Frontend

#42030 feat(perf): Add accordion menu to widgets
  static/app/views/performance/landing/widgets/components/accordion.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/trendsWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
Labels: Scope: Frontend

#42060 ref(issue-details-page-analytics): Add has_minified_stack_trace property - [TET-562]
  static/app/components/events/interfaces/exceptionV2.tsx
  static/app/components/events/interfaces/threads/threadSelector/findBestThread.tsx
  static/app/utils/events.tsx
Labels: Scope: Frontend

#42077 feat: Enable DS for the Go SDK
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
Labels: Scope: Backend

#41921 feat(txnames): Write transaction names to redis
  src/sentry/api/endpoints/project_transaction_names.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/ingest/transaction_clusterer/datasource/__init__.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/ingest/transaction_clusterer/datasource/snuba.py
  src/sentry/scripts/utils/sadd_capped.lua
  src/sentry/tasks/post_process.py
  tests/sentry/ingest/test_transaction_clusterer.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#42067 ref(dynamic-sampling): Merge server-side-sampling flag into dynamic-sampling flag - [TET-513]
  static/app/utils/performance/contexts/metricsEnhancedSetting.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilderDataset.spec.tsx
  static/app/views/settings/project/dynamicSampling/dynamicSampling.spec.tsx
  static/app/views/settings/project/dynamicSampling/index.tsx
  static/app/views/settings/project/navigationConfiguration.tsx
Labels: Scope: Frontend

#41927 feat(txnames): Expose redis transaction name store through endpoint
  src/sentry/api/endpoints/project_transaction_names.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/receivers/transactions.py
  tests/sentry/api/endpoints/test_project_transaction_names.py
  tests/sentry/ingest/test_transaction_clusterer.py
Labels: Do Not Merge, Scope: Backend

#41967 feat(nodestore): File-based nodestore backend
  src/sentry/nodestore/filesystem/__init__.py
  src/sentry/nodestore/filesystem/backend.py
Labels: Scope: Backend

#42116 fix(issues): Fix prompt stacktrace link query
  static/app/actionCreators/prompts.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.spec.tsx
  static/app/utils/queryClient.tsx
Labels: Scope: Frontend

#42025 feat(profiling): extract package from path
  static/app/utils/profiling/frame.spec.tsx
  static/app/utils/profiling/frame.tsx
Labels: Scope: Frontend

#42130 fix(derive_code_mappings): Ignore file paths without an extension
  src/sentry/integrations/utils/code_mapping.py
  tests/sentry/integrations/utils/test_code_mapping.py
Labels: Scope: Backend

#42126 feat(replays): Update onboarding links to point to docs.sentry.io
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/views/replays/replays.tsx
Labels: Scope: Frontend

#42111 fix(alerts): Use mep-rollout-flag metrics backend
  src/sentry/incidents/serializers/alert_rule.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Scope: Backend

#42131 feat(perf-issues): N+1 API Calls detector improvements V
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#42135 fix(issues): Update stacktrace link copy
  static/app/components/events/interfaces/frame/stacktraceLink.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
Labels: Scope: Frontend

#42118 feat(scim): add idp flags to OrganizationMemberSerializer
  src/sentry/api/serializers/models/organization_member/base.py
  src/sentry/api/serializers/models/organization_member/response.py
Labels: Scope: Backend

#41996 feat(replays): Add issue replay count endpoint
  mypy.ini
  src/sentry/api/urls.py
  src/sentry/replays/endpoints/organization_issue_replay_count.py
  src/sentry/search/events/datasets/discover.py
  tests/sentry/replays/test_organization_issue_replay_count.py
Labels: Scope: Backend

#42123 fix(queryclient): Disable query cancellation on component unmount
  static/app/utils/queryClient.tsx
Labels: Scope: Frontend

#42140 fix(notification-test): msteams notification fix
  src/sentry/api/endpoints/project_rule_actions.py
Labels: Scope: Backend

#42142 fix(issues): Fix prompt query parameter casing
  static/app/actionCreators/prompts.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.spec.tsx
Labels: Scope: Frontend

#42141 feat(profiling): add all profiles tab to transactions
  static/app/components/profiling/ProfilingOnboarding/util.ts
  static/app/routes.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/pageLayout.tsx
  static/app/views/performance/transactionSummary/tabs.tsx
  static/app/views/performance/transactionSummary/transactionProfiles/index.tsx
  static/app/views/performance/transactionSummary/transactionProfiles/utils.ts
  static/app/views/profiling/profileSummary/content.tsx
Labels: Scope: Frontend

#41674 chore(top-level-filter): Remove frontend feature flag code
  static/app/components/modals/widgetBuilder/addToDashboardModal.spec.tsx
  static/app/components/modals/widgetBuilder/addToDashboardModal.tsx
  static/app/views/dashboardsV2/detail.spec.jsx
  static/app/views/dashboardsV2/detail.tsx
  static/app/views/dashboardsV2/filtersBar.tsx
  static/app/views/dashboardsV2/orgDashboards.spec.tsx
  static/app/views/dashboardsV2/orgDashboards.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/filterResultsStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilderDataset.spec.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilderSortBy.spec.tsx
Labels: Scope: Frontend

#41936 ref(stacktrace-link): stacktrace link tests for Android, Cocoa and Flutter
  src/sentry/api/endpoints/project_stacktrace_link.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
Labels: Scope: Backend

#42132 ref(perf-issues): Remove unused sequential slow spans detector
  src/sentry/models/group.py
  src/sentry/types/issues.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#42113 fix(hybrid-cloud): Do not redirect to customer domain for non-customer domain paths
  src/sentry/web/frontend/react_page.py
  tests/sentry/web/frontend/test_react_page.py
Labels: Scope: Backend

#42098 feat(alert-preview): last triggered
  src/sentry/api/endpoints/project_rule_preview.py
  src/sentry/rules/history/preview.py
  tests/sentry/rules/history/endpoints/test_project_rule_preview.py
  tests/sentry/rules/history/test_preview.py
Labels: Scope: Backend

#42100 feat(alert-preview): show last triggered in preview
  static/app/components/issues/groupListHeader.tsx
  static/app/components/stream/group.tsx
  static/app/components/tooltip.tsx
  static/app/types/group.tsx
  static/app/views/alerts/create.spec.jsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/issue/previewTable.tsx
Labels: Scope: Frontend

#42114 feat(hybrid-cloud): Add customer domain support for org creation flow
  static/app/utils/withDomainRequired.spec.tsx
  static/app/utils/withDomainRequired.tsx
  static/app/views/organizationCreate.spec.tsx
  static/app/views/organizationCreate.tsx
Labels: Scope: Frontend

#42148 fix(profiling): idbadge prop
  static/app/components/idBadge/getBadge.tsx
  static/app/views/profiling/profileSummary/index.tsx
Labels: Scope: Frontend

#42112 fix(alerts): Use only mep-rollout-flag for metrics dataset
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.spec.jsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/utils/getMetricDatasetQueryExtras.tsx
Labels: Scope: Frontend

#42149 fix(useVirtualizedTree): one observer is enough
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
Labels: Scope: Frontend

#42079 feat(profiling): place gc stack frames on top of previous stack
  static/app/utils/profiling/profile/sampledProfile.spec.tsx
  static/app/utils/profiling/profile/sampledProfile.tsx
Labels: Scope: Frontend

#42122 feat(issue-alert): incompatible rules/test notification analytics
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/views/alerts/rules/issue/index.tsx
Labels: Scope: Frontend

#42103 chore(routes): Remove support for deprecated pre-Sentry 10 routes
  static/app/routes.tsx
  static/app/views/projects/redirectDeprecatedProjectRoute.tsx
Labels: Scope: Frontend

#41941 feat(occurrences) Adds a placeholder ingestor for Occurrences (ISP-83)
  src/sentry/issues/occurrence_consumer.py
  src/sentry/runner/commands/devserver.py
  src/sentry/runner/commands/run.py
Labels: Scope: Backend

#42151 fix(weekly-email): fix id for performance issues
  src/sentry/templates/sentry/emails/reports/body.html
Labels: Scope: Backend

#42147 feat(derive_code_mappings): Enable JS code derivation for EA orgs
  src/sentry/tasks/derive_code_mappings.py
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#42158 fix(onboarding): id badge fix #2
  static/app/components/profiling/ProfilingOnboarding/proflingOnboardingSidebar.tsx
Labels: Scope: Frontend

#42068 ref(discover): removes optional args from decodeColumnOrder and getColumns
  static/app/components/charts/simpleTableChart.tsx
  static/app/components/modals/widgetViewerModal.tsx
  static/app/utils/discover/eventView.tsx
  static/app/views/eventsV2/table/tableActions.tsx
  static/app/views/eventsV2/table/tableView.tsx
  static/app/views/eventsV2/utils.tsx
  static/app/views/performance/table.tsx
Labels: Scope: Frontend

#42117 feat(issues): Add stacktrace-link API call for mobile platforms
  static/app/components/events/interfaces/frame/context.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
Labels: Scope: Frontend

#42071 chore(discover): removes unneeded events api feature flags
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/serializers/test_organization.py
Labels: Scope: Backend

#42146 chore(discover): Removes optional useEvent from DiscoverQuery since it should always be set to true now
  static/app/components/discover/performanceCardTable.tsx
  static/app/components/discover/transactionsList.tsx
  static/app/utils/discover/discoverQuery.spec.jsx
  static/app/utils/discover/discoverQuery.tsx
  static/app/views/alerts/rules/metric/details/relatedTransactions.tsx
  static/app/views/organizationStats/teamInsights/teamMisery.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/singleFieldAreaWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  static/app/views/performance/table.tsx
  static/app/views/performance/traceDetails/traceNotFound.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
  static/app/views/performance/transactionSummary/transactionEvents/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/statusBreakdown.tsx
  static/app/views/performance/transactionSummary/transactionSpans/content.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/content.tsx
Labels: Scope: Frontend

#42162 chore(perf): Add new param to the widget analytics
  static/app/utils/analytics/performanceAnalyticsEvents.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.tsx
Labels: Scope: Frontend

#42161 fix(derived_code_mappings): Use default refresh period
  src/sentry/tasks/derive_code_mappings.py
Labels: Scope: Backend

#42115 feat(perf-issues): Account for multiple file-io spans
  fixtures/events/performance_problems/file-io-on-main-thread-with-complicated-structure.json
  fixtures/events/performance_problems/file-io-on-main-thread-with-parallel-spans.json
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_file_io_on_main_thread_detector.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#42165 ref(profiling): Update invalid profile reason names
  src/sentry/profiles/task.py
Labels: Scope: Backend

#42097 feat: SENTRY_SINGLE_TENANT env switch for an ST patch
  src/sentry/tagstore/snuba/backend.py
Labels: Scope: Backend

#41968 feat(perf-issues): Detect MN+1 DB Queries
  fixtures/events/performance_problems/m-n-plus-one-db/m-n-plus-one-graphql-truncated.json
  fixtures/events/performance_problems/m-n-plus-one-db/m-n-plus-one-graphql.json
  src/sentry/types/issues.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_m_n_plus_one_db_detector.py
Labels: Scope: Backend
