Repository getsentry/sentry, pull requests merged in 2022-04, with the labels that each got.

#33029 ref(timeouts): make sure we clear timeouts
  static/app/actionCreators/navigation.tsx
  static/app/components/autoComplete.tsx
  static/app/components/bases/pluginComponentBase.tsx
  static/app/components/charts/pieChart.tsx
  static/app/components/contextPickerModal.tsx
  static/app/components/dashboards/issueWidgetQueriesForm.tsx
  static/app/components/dashboards/widgetQueriesForm.tsx
  static/app/components/dropdownMenu.tsx
  static/app/components/hovercard.tsx
  static/app/components/inputInline.tsx
  static/app/components/modals/createOwnershipRuleModal.tsx
  static/app/components/modals/redirectToProject.tsx
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/components/sidebar/broadcasts.tsx
  static/app/components/smartSearchBar/index.tsx
  static/app/components/stacktracePreview.tsx
  static/app/components/timeSince.tsx
  static/app/utils/cursorPoller.tsx
  static/app/utils/eventWaiter.tsx
  static/app/utils/performance/contexts/genericQueryBatcher.tsx
  static/app/views/alerts/incidentRules/ruleForm/index.tsx
  static/app/views/alerts/issueRuleEditor/index.tsx
  static/app/views/alerts/issueRuleEditor/ruleNodeList.tsx
  static/app/views/dashboardsV2/dashboard.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/filterResultsStep/index.tsx
  static/app/views/onboarding/components/welcomeBackground.tsx
  static/app/views/onboarding/createSampleEventButton.tsx
  static/app/views/onboarding/targetedOnboarding/components/welcomeBackground.tsx
  static/app/views/onboarding/targetedOnboarding/onboarding.tsx
  static/app/views/onboarding/welcome.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
  static/app/views/organizationIntegrations/SplitInstallationIdModal.tsx
  static/app/views/organizationIntegrations/sentryAppDetailedView.tsx
  static/app/views/settings/account/accountClose.tsx
  static/app/views/settings/components/settingsBreadcrumb/breadcrumbDropdown.tsx
  static/app/views/settings/project/projectUserFeedback.tsx
  static/app/views/setupWizard/index.tsx
Labels: Type: CI Flakiness

#33189 fix(tests): Flakey Monitor Check-in API Tests
  src/sentry/api/bases/monitor.py
  src/sentry/api/endpoints/monitor_checkin_details.py
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_monitor_checkin_details.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
Labels: Team: Ecosystem

#33214 fix(jira): Error message copy
  src/sentry/integrations/base.py
  src/sentry/integrations/jira/integration.py
Labels: Type: Bug, Team: Ecosystem

#33223 fix(tests): UserRole Flakey Test
  src/sentry/api/endpoints/user_role_details.py
  tests/sentry/api/endpoints/test_user_role_details.py
Labels: Team: Ecosystem

#33158 fix(jira): `sync_status_inbound` task
  src/sentry/models/group.py
Labels: Type: Bug, Team: Ecosystem

#33194 fix(vsts): Don't redirect when there is a pipeline error
  src/sentry/integrations/vsts_extension/integration.py
Labels: Type: Bug, Team: Ecosystem

#33228 fix(tests): Slack Notification Flakey Test
  tests/sentry/integrations/slack/notifications/test_deploy.py
Labels: Team: Ecosystem

#33230 fix(tests): Join Organization Request Flakey Test
  tests/sentry/api/endpoints/test_organization_join_request.py
Labels: Team: Ecosystem

#33184 fix(slack): `AlertRuleTriggerActionSerializer` weirdness
  src/sentry/incidents/serializers/alert_rule_trigger_action.py
  tests/js/spec/views/alerts/issueRuleEditor/ruleNode.spec.jsx
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
Labels: Type: Bug, Team: Ecosystem

#33131 ref(endpoints): Integration Directory submodule
  .github/CODEOWNERS
  src/sentry/api/endpoints/integrations/__init__.py
  src/sentry/api/endpoints/integrations/doc_integrations/__init__.py
  src/sentry/api/endpoints/integrations/doc_integrations/details.py
  src/sentry/api/endpoints/integrations/doc_integrations/index.py
  src/sentry/api/endpoints/integrations/index.py
  src/sentry/api/endpoints/integrations/install_request.py
  src/sentry/api/endpoints/integrations/organization_integrations/__init__.py
  src/sentry/api/endpoints/integrations/organization_integrations/details.py
  src/sentry/api/endpoints/integrations/organization_integrations/index.py
  src/sentry/api/endpoints/integrations/plugins/__init__.py
  src/sentry/api/endpoints/integrations/plugins/configs_index.py
  src/sentry/api/endpoints/integrations/plugins/index.py
  src/sentry/api/endpoints/integrations/sentry_apps/__init__.py
  src/sentry/api/endpoints/integrations/sentry_apps/authorizations.py
  src/sentry/api/endpoints/integrations/sentry_apps/components.py
  src/sentry/api/endpoints/integrations/sentry_apps/details.py
  src/sentry/api/endpoints/integrations/sentry_apps/features.py
  src/sentry/api/endpoints/integrations/sentry_apps/index.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/__init__.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/details.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/external_issue/__init__.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/external_issue/actions.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/external_issue/details.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/external_issue/index.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/external_requests.py
  src/sentry/api/endpoints/integrations/sentry_apps/installation/index.py
  src/sentry/api/endpoints/integrations/sentry_apps/interaction.py
  src/sentry/api/endpoints/integrations/sentry_apps/internal_app_token/__init__.py
  src/sentry/api/endpoints/integrations/sentry_apps/internal_app_token/details.py
  src/sentry/api/endpoints/integrations/sentry_apps/internal_app_token/index.py
  src/sentry/api/endpoints/integrations/sentry_apps/organization_sentry_apps.py
  src/sentry/api/endpoints/integrations/sentry_apps/publish_request.py
  src/sentry/api/endpoints/integrations/sentry_apps/requests.py
  src/sentry/api/endpoints/integrations/sentry_apps/stats/__init__.py
  src/sentry/api/endpoints/integrations/sentry_apps/stats/details.py
  src/sentry/api/endpoints/integrations/sentry_apps/stats/index.py
  src/sentry/api/urls.py
  src/sentry/apidocs/public_exclusion_list.py
Labels: Team: Ecosystem

#32473 ref(models): `create_or_save()` -> `update_or_create()`
  src/sentry/integrations/github/webhook.py
  src/sentry/integrations/gitlab/webhooks.py
  src/sentry/models/pullrequest.py
  src/sentry_plugins/github/webhooks/events/pull_request.py
Labels: Team: Ecosystem

#33190 fix(tests): Ticket Rules Futures Flakey Test
  src/sentry/integrations/jira/notify_action.py
  src/sentry/integrations/vsts/notify_action.py
  src/sentry/rules/actions/base.py
Labels: Team: Ecosystem

#32862 ref(py): Split up large file
  src/sentry/pipeline/__init__.py
  src/sentry/pipeline/base.py
  src/sentry/pipeline/constants.py
  src/sentry/pipeline/provider.py
  src/sentry/pipeline/store.py
  src/sentry/pipeline/types.py
  src/sentry/pipeline/views/__init__.py
  src/sentry/pipeline/views/base.py
  src/sentry/pipeline/views/nested.py
Labels: Team: Ecosystem

#33143 ref(endpoints): Integration Directory
  src/sentry/api/endpoints/integrations/organization_integrations/index.py
  tests/sentry/api/endpoints/test_organization_integrations.py
Labels: Team: Ecosystem

#33079 security(deps): Bump django version to 2.2.27
  requirements-base.txt
  src/sentry/web/debug_urls.py
  src/sentry/web/urls.py
Labels: dependencies, python

#33313 feat(replay): Show a single <Breadcrumb> widget with data from all events
  static/app/views/replays/details.tsx
  static/app/views/replays/utils/mergeBreadcrumbsEntries.tsx
Labels: Status: In Progress, Team: Emerging Technology, Component: Replay Details

#33344 chore(ratelimit): Reduce default to 420
  src/sentry/ratelimits/config.py
Labels: Component: API

#32206 fix(sdk): Do not error if a project is using an unknown version
  requirements-base.txt
  src/sentry/api/endpoints/organization_sdk_updates.py
  tests/sentry/api/endpoints/test_organization_sdk_updates.py
Labels: Status: In Progress

#33348 ref(pipeline): Abstract Properties
  src/sentry/auth/provider.py
  src/sentry/auth/providers/oauth2.py
  src/sentry/auth/providers/saml2/provider.py
  src/sentry/identity/base.py
  src/sentry/identity/providers/dummy.py
  src/sentry/integrations/base.py
  src/sentry/pipeline/provider.py
  tests/sentry/auth/providers/google/test_provider.py
  tests/sentry/auth/providers/test_oauth2.py
  tests/sentry/auth/providers/test_saml2.py
  tests/sentry/auth/test_helper.py
  tests/sentry/identity/test_oauth2.py
  tests/sentry/models/test_identity.py
  tests/sentry/pipeline/test_pipeline.py
  tests/sentry/web/frontend/test_auth_oauth2.py
  tests/sentry/web/frontend/test_auth_saml2.py
Labels: Team: Ecosystem

#33378 ref(sentryapps): Change signature header and formalize request body
  src/sentry/mediators/external_requests/alert_rule_action_requester.py
  src/sentry/mediators/external_requests/issue_link_requester.py
  src/sentry/mediators/external_requests/select_requester.py
  tests/sentry/mediators/external_requests/test_alert_rule_action_requester.py
  tests/sentry/mediators/external_requests/test_issue_link_requester.py
  tests/sentry/mediators/external_requests/test_select_requester.py
Labels: Team: Ecosystem

#32232 feat(perf): Link child transaction span to transaction summary page
  static/app/components/events/interfaces/spans/spanDetail.tsx
Labels: Status: In Progress

#33381 ref(notifications): Document Notification Platform
  src/sentry/mail/notifications.py
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/codeowners_auto_sync.py
  src/sentry/notifications/notifications/digest.py
  src/sentry/notifications/notifications/integration_nudge.py
  src/sentry/notifications/notifications/organization_request/base.py
  src/sentry/notifications/notifications/rules.py
  src/sentry/notifications/notifications/user_report.py
  src/sentry/utils/email/message_builder.py
  src/sentry/web/frontend/debug/mail.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/utils/email/test_message_builder.py
Labels: Component: Notifications, Team: Ecosystem

#32863 ref(types): Add types to the pipeline module
  .github/CODEOWNERS
  mypy.ini
  src/sentry/api/serializers/models/user_identity_config.py
  src/sentry/integrations/base.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/vsts/integration.py
  src/sentry/pipeline/__init__.py
  src/sentry/pipeline/base.py
  src/sentry/pipeline/provider.py
  src/sentry/pipeline/store.py
  src/sentry/pipeline/views/base.py
  src/sentry/pipeline/views/nested.py
  src/sentry/web/frontend/debug/debug_sso_link_email.py
Labels: Team: Ecosystem

#33455 feat(ci): Join FE & BE workflows
  .github/file-filters.yml
  .github/workflows/acceptance.yml
  .github/workflows/api-docs-test.yml
  .github/workflows/backend-lint.yml
  .github/workflows/backend-test.yml
  .github/workflows/backend-typing.yml
  .github/workflows/backend.yml
  .github/workflows/check-if-migration-is-required.yml
  .github/workflows/command-line-test.yml
  .github/workflows/frontend.yml
  .github/workflows/migrations.yml
  .github/workflows/plugins-test.yml
  .github/workflows/relay-integration-test.yml
  .github/workflows/snuba-integration-test.yml
  .github/workflows/symbolicator-integration-test.yml
Labels: Component: CI

#33547 chore(ratelimit): Drop rate limit to 370
  src/sentry/ratelimits/config.py
Labels: Component: API

#32797 feat(dam): Clear metrics widget error message
  static/app/views/dashboardsV2/widgetCard/metricsWidgetQueries.tsx
Labels: Status: Stale

#33591 fix(ci): Add migrations.yml back
  .github/workflows/backend.yml
  .github/workflows/migrations.yml
Labels: Component: CI

#33579 feat(replays): session column addition
  static/app/views/replays/replays.tsx
  static/app/views/replays/types.tsx
Labels: Team: Emerging Technology

#28396 JSON syntax and OpenAPI spec fixes, to silence (some) swagger/openapi codegen errors.
  api-docs/components/schemas/event.json
  api-docs/components/schemas/key.json
  api-docs/components/schemas/plugin.json
  api-docs/components/schemas/sessions.json
  api-docs/paths/integration-platform/sentry-app-external-issues.json
  api-docs/paths/organizations/event-id-lookup.json
  api-docs/paths/organizations/shortid.json
  api-docs/paths/scim/team_details.json
  api-docs/paths/teams/index.json
Labels: Status: Backlog

#33650 feat(replays): replaced the global header with the new filter components on the replays index.
  static/app/views/replays/filters.tsx
  static/app/views/replays/replays.tsx
Labels: Team: Emerging Technology

#33541 feat(ci): Support skipping of jobs
  .github/workflows/acceptance.yml
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: Component: CI

#33674 fix(dev): Do not use bash-hook for sentry-cli version 2
  scripts/lib.sh
Labels: Component: Developer Environment

#33592 feat(ci): Remove pg14 workflows
  .github/workflows/acceptance-pg14.yml
  .github/workflows/acceptance.yml
  .github/workflows/backend-test-pg14.yml
  .github/workflows/backend.yml
  .github/workflows/command-line-test-pg14.yml
  .github/workflows/migrations-pg14.yml
  .github/workflows/migrations.yml
Labels: Component: CI

#33690 Revert "feat(ci): Support skipping of jobs (#33541)"
  .github/workflows/acceptance.yml
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: Component: CI

#33658 [feat/33275] - Add sorting timestamp
  static/app/views/replays/replays.tsx
Labels: Team: Emerging Technology

#33701 feat(replays): search bar added to the replays index page
  static/app/views/replays/filters.tsx
  static/app/views/replays/replays.tsx
Labels: Team: Emerging Technology, Component: Replay Index

#33691 feat(replays): Show pathname instead of url
  static/app/utils/getUrlPathname.tsx
  static/app/views/replays/replays.tsx
Labels: Team: Emerging Technology

#33793 fix(ci): Export frontend_components_modified_lintable in files-changed
  .github/workflows/frontend.yml
Labels: Component: CI

#33794 fix(ci): Remove unintended conditional
  .github/file-filters.yml
  .github/workflows/frontend.yml
  package.json
  yarn.lock
Labels: Component: CI

#33802 fix(dev): Do not export SENTRY_DSN in .envrc
  .envrc
  config/hooks/pre-commit
  scripts/lib.sh
Labels: Component: Developer Environment

#33784 feat(ci): Collector jobs should fail on dependent job failure
  .github/workflows/acceptance.yml
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
Labels: Component: CI

#33824 fix(ci): only lint changed files in stylelint
  .github/workflows/frontend.yml
  jest.config.ts
  tests/js/setup.ts
Labels: Component: CI

#33833 ref(github): Avoid KeyError on external_id generation
  src/sentry/integrations/github/webhook.py
Labels: Component: Integrations, Team: Ecosystem

#33850 ref(notifications): Test titles
  tests/sentry/integrations/slack/notifications/test_deploy.py
  tests/sentry/integrations/slack/notifications/test_issue_alert.py
  tests/sentry/integrations/slack/notifications/test_new_processing_issues.py
  tests/sentry/integrations/slack/notifications/test_note.py
  tests/sentry/integrations/slack/notifications/test_regression.py
  tests/sentry/integrations/slack/notifications/test_resolved.py
  tests/sentry/integrations/slack/notifications/test_resolved_in_release.py
Labels: Type: Bug, Component: Notifications, Team: Ecosystem

#33869 fix(jira): Prevent KeyError on signed_params
  src/sentry/integrations/jira/views/extension_configuration.py
Labels: Component: Integrations, Team: Ecosystem

#33875 feat(replays): Prevent Replays on Sentry.io from capturing the replay…
  static/app/components/replays/replayPlayer.tsx
Labels: Team: Emerging Technology

#33825 feat(dev): warn on insufficient Docker.app memory
  .envrc
  setup.cfg
  tests/tools/docker_memory_check_test.py
  tools/docker_memory_check.py
Labels: Component: Developer Environment

#33842 feat(jira): Allow multiple Sentry Issues to be rendered on Jira Issue View
  src/sentry/integrations/jira/views/issue_hook.py
  src/sentry/templates/sentry/integrations/jira-issue.html
  tests/sentry/integrations/jira/test_issue_hook.py
Labels: Component: Integrations, Team: Ecosystem

#33930 chore(logs): Forgot to fix logs before merging
  src/sentry/integrations/jira/views/issue_hook.py
Labels: Component: Integrations, Team: Ecosystem

#33871 ref(integrations): Exit task if the external issue doesn't exist
  src/sentry/tasks/integrations/update_comment.py
Labels: Component: Integrations, Team: Ecosystem

#33801 style(replays): added media query to the replay index so the table looks more sensible on smaller screens and corrected dark theme background
  static/app/views/replays/replays.tsx
Labels: Team: Emerging Technology

#33849 ref(notifications): Split up message builders
  src/sentry/integrations/slack/message_builder/notifications.py
  src/sentry/integrations/slack/message_builder/notifications/__init__.py
  src/sentry/integrations/slack/message_builder/notifications/base.py
  src/sentry/integrations/slack/message_builder/notifications/digest.py
  src/sentry/integrations/slack/message_builder/notifications/issues.py
Labels: Component: Notifications, Team: Ecosystem

#33571 fix(rules): Surface errors from Sentry Apps + reformat slack errors
  src/sentry/api/endpoints/project_rules.py
  src/sentry/api/endpoints/project_rules_configuration.py
  src/sentry/api/serializers/rest_framework/rule.py
  src/sentry/constants.py
  src/sentry/integrations/slack/notify_action.py
  src/sentry/mediators/alert_rule_actions/creator.py
  src/sentry/mediators/external_requests/alert_rule_action_requester.py
  tests/sentry/incidents/endpoints/test_serializers.py
  tests/sentry/integrations/slack/test_notify_action.py
  tests/sentry/mediators/external_requests/test_alert_rule_action_requester.py
Labels: Component: Integrations, Team: Ecosystem

#33929 fix(ci): Do not skip step for visual diffs on PRs or master
  .github/workflows/acceptance.yml
  .github/workflows/visual-diff.yml
Labels: Do Not Merge, Component: CI

#33876 style(replays): Make Scrubber hitbox bigger
  static/app/components/replays/replayController.tsx
Labels: Team: Emerging Technology

#33977 fix: improve apple m1 detection for newer OS versions
  src/sentry/conf/server.py
Labels: Component: Developer Environment

#33967 fix(ci): Do not skip step for visual diffs on PRs
  .github/workflows/acceptance.yml
  .github/workflows/visual-diff.yml
Labels: Component: CI

#34002 feat(ci): visual-diff should be skipped with pushes to `master`
  .github/workflows/acceptance.yml
  .github/workflows/visual-diff.yml
Labels: Component: CI

#33948 ref(metric-alerts): Prevent AlertRuleActionRequester from firing on serialization.
  src/sentry/incidents/endpoints/project_alert_rule_details.py
  src/sentry/incidents/endpoints/project_alert_rule_index.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/serializers/alert_rule_trigger_action.py
  src/sentry/incidents/utils/__init__.py
  src/sentry/incidents/utils/sentry_apps.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Component: Integrations, Team: Ecosystem

#34027 ref(issue-alerts): Move AlertRuleAction logic away from endpoint
  src/sentry/api/endpoints/project_rule_details.py
  src/sentry/api/endpoints/project_rules.py
  src/sentry/rules/actions/base.py
  src/sentry/rules/actions/notify_event_sentry_app.py
  tests/sentry/api/endpoints/test_project_rule_details.py
  tests/sentry/api/endpoints/test_project_rules.py
Labels: Component: Integrations, Team: Ecosystem

#34061 ref(notifications): Remove `get_activity_name()`
  src/sentry/notifications/notifications/activity/assigned.py
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/notifications/activity/new_processing_issues.py
  src/sentry/notifications/notifications/activity/note.py
  src/sentry/notifications/notifications/activity/regression.py
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/notifications/activity/resolved.py
  src/sentry/notifications/notifications/activity/resolved_in_release.py
  src/sentry/notifications/notifications/activity/unassigned.py
  src/sentry/templates/sentry/emails/activity/generic.html
  src/sentry/templates/sentry/emails/activity/generic.txt
Labels: Component: Notifications, Team: Ecosystem

#34074 fix(tests): Removing debugging code after confirming fix
  tests/sentry/integrations/vsts/test_notify_action.py
Labels: Component: Integrations, Team: Ecosystem

#33963 feat(replays): Render replay duration and errors count
  static/app/views/replays/replayTable.tsx
  static/app/views/replays/replays.tsx
Labels: Team: Emerging Technology
