Repository getsentry/sentry, pull requests merged in 2022-07, with the labels that each got.

#36246 feat(sampling): Add rules panel new design - [TET-164]
  static/app/components/switchButton.tsx
  static/app/types/sampling.tsx
  static/app/views/settings/project/sampling/rules/draggableList/index.tsx
  static/app/views/settings/project/sampling/rules/index.tsx
  static/app/views/settings/project/sampling/rules/rule/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/promo.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
Labels: frontend

#36301 fix: Disable broken tests
  tests/sentry/integrations/msteams/test_webhook.py
Labels: backend

#36296 ref(sampling): Add activation modal groundwork - [TET-164]
  static/app/components/alert.tsx
  static/app/views/settings/project/server-side-sampling/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/activateModal.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  tests/js/spec/views/settings/project/server-side-sampling/activateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
Labels: frontend

#36188 feat(metrics): Kill switch for transaction metric transaction [INGEST-333]
  src/sentry/killswitches.py
  src/sentry/relay/config/__init__.py
  src/sentry/runner/commands/killswitches.py
  tests/sentry/relay/test_config.py
  tests/sentry/runner/commands/test_killswitches.py
Labels: Do Not Merge, backend

#36307 ref(projectconfigs): Improve metrics reporting
  src/sentry/api/endpoints/relay/project_configs.py
Labels: backend

#36306 fix(dynamic-sampling): Add query optimization for fetching random root transactions [TET-184]
  src/sentry/api/endpoints/project_dynamic_sampling.py
  src/sentry/search/events/datasets/discover.py
  tests/sentry/api/endpoints/test_project_dynamic_sampling.py
Labels: backend

#36113 feat(dynamic-sampling): Adds endpoint that returns onboarding flow trace info [TET-176]
  src/sentry/api/endpoints/project_dynamic_sampling.py
  src/sentry/api/urls.py
  src/sentry/search/events/datasets/discover.py
  src/sentry/snuba/events.py
  tests/sentry/api/endpoints/test_project_dynamic_sampling.py
Labels: backend

#36311 fix(dynamic-sampling): Relax permissions on dyn sampling endpoint
  src/sentry/api/endpoints/project_dynamic_sampling.py
Labels: backend

#36314 feat(metrics): Option for percentage-wise org rollout [INGEST-1423]
  src/sentry/options/defaults.py
Labels: backend

#36240 feat(replays): Create a location qs manager and use it for some state across the replay details page
  static/app/utils/replays/hooks/useActiveReplayTab.tsx
  static/app/utils/replays/hooks/useActiveTabFromLocation.tsx
  static/app/utils/replays/hooks/useUrlParams.tsx
  static/app/views/replays/detail/asideTabs.tsx
  static/app/views/replays/detail/focusArea.tsx
  static/app/views/replays/detail/focusTabs.tsx
  static/app/views/replays/details_v2.tsx
  static/app/views/replays/types.tsx
Labels: frontend

#36309 feat(models): This begins the removal of the encrypted fields
  src/sentry/conf/server.py
  src/sentry/db/models/fields/__init__.py
  src/sentry/db/models/fields/encrypted.py
  src/sentry/db/models/fields/picklefield.py
  src/sentry/models/apiapplication.py
  src/sentry/models/authenticator.py
  src/sentry/models/authidentity.py
  src/sentry/models/authprovider.py
  src/sentry/models/identity.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/integrations/organization_integration.py
  src/sentry/models/integrations/project_integration.py
  src/sentry/models/integrations/sentry_app.py
  src/sentry/models/integrations/sentry_app_component.py
  src/sentry/models/monitor.py
  src/sentry/models/monitorcheckin.py
  src/sentry/models/options/option.py
  src/sentry/models/options/organization_option.py
  src/sentry/models/options/project_option.py
  src/sentry/models/options/user_option.py
  src/sentry/models/servicehook.py
  src/sentry/utils/encryption.py
  src/sentry/utils/pytest/sentry.py
  tests/sentry/utils/test_encryption.py
Labels: backend

#36313 feat(metrics): Enable transaction metric extraction for a percentage of orgs [INGEST-1423]
  mypy.ini
  src/sentry/relay/config/__init__.py
  src/sentry/utils/options.py
  tests/sentry/relay/test_config.py
  tests/sentry/utils/test_options.py
Labels: backend

#36312 ref(sampling): Add add, edit, delete, sort handlers
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/conditions.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/tagValueAutocomplete.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/truncatedLabel.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/utils.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils.tsx
  tests/js/spec/views/settings/project/server-side-sampling/activateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/specificConditionsModal.spec.tsx
Labels: frontend

#36320 chore(dashboards): Add top level query filter flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: backend

#36316 feat(sampling): Add rate suggestion UI [TET-164]
  fixtures/js-stubs/outcomes.js
  fixtures/js-stubs/types.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/styles.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateChart.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/index.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToSampleRates.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToSeries.tsx
  static/app/views/settings/project/server-side-sampling/utils/useProjectStats.tsx
  tests/js/spec/views/settings/project/server-side-sampling/activateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/specificConditionsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToSampleRates.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToSeries.spec.tsx
Labels: frontend

#36303 fix(ci): broken msteams tests
  tests/sentry/integrations/msteams/test_webhook.py
Labels: backend

#36281 feat(overlays): Add generic Overlay component
  static/app/components/hovercard.tsx
  static/app/components/overlay.tsx
  static/app/components/tooltip.tsx
Labels: frontend

#36210 ref(orgStats); Use CompactSelect for data category dropdown
  static/app/utils/theme.tsx
  static/app/views/organizationStats/index.tsx
  tests/js/spec/views/organizationStats/index.spec.jsx
Labels: frontend

#36213 ref(discover): Use CompactSelect for landing page sort dropdown
  static/app/views/eventsV2/landing.tsx
  tests/js/spec/views/eventsV2/index.spec.jsx
Labels: frontend

#36216 ref(dashboards): Use CompactSelect for landing page sort dropdown
  static/app/views/dashboardsV2/manage/index.tsx
  tests/js/spec/views/dashboardsV2/manage/index.spec.jsx
Labels: frontend

#36085 feat(discover): allows a function to be passed as rate limit and updates events endpoint to use rate limit
  src/sentry/api/endpoints/organization_events.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/middleware/ratelimit.py
  src/sentry/ratelimits/utils.py
  tests/sentry/middleware/test_ratelimit_middleware.py
  tests/snuba/api/endpoints/test_organization_events_v2.py
Labels: backend

#36043 feat(alert): Metric alert presets
  static/app/data/experimentConfig.tsx
  static/app/utils/analytics/growthAnalyticsEvents.tsx
  static/app/views/alerts/create.tsx
  static/app/views/alerts/edit.tsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/metric/duplicate.tsx
  static/app/views/alerts/rules/metric/metricField.tsx
  static/app/views/alerts/rules/metric/presetSidebar.tsx
  static/app/views/alerts/rules/metric/presets.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/wizard/index.tsx
  tests/js/spec/views/alerts/metricRules/metricField.spec.jsx
  tests/js/spec/views/alerts/metricRules/presets.spec.jsx
Labels: frontend

#36152 feat(onboarding): add alpha onboarding page
  static/app/utils/analytics/profilingAnalyticsEvents.tsx
  static/app/views/profiling/index.tsx
  static/app/views/profiling/profilingOnboarding.tsx
Labels: frontend

#36290 ref(perf): Refactor vital details and breadcrumbs class components into function components
  static/app/views/performance/breadcrumb.tsx
  static/app/views/performance/vitalDetail/vitalDetailContent.tsx
Labels: frontend

#36288 feat(multi-region): Attach SubdomainMiddleware
  src/sentry/conf/server.py
Labels: backend

#36329 fix(alert): Fix issue alert create layout
  static/app/views/alerts/rules/issue/index.tsx
Labels: frontend

#36275 feat(perf-issues): Add support for focused spans in span tree
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/spans/index.tsx
  static/app/components/events/interfaces/spans/spanTreeModel.tsx
  static/app/components/events/interfaces/spans/types.tsx
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/components/events/interfaces/spans/waterfallModel.tsx
  static/app/types/event.tsx
  tests/js/spec/components/events/interfaces/spans/spanTreeModel.spec.tsx
Labels: frontend

#36233 feat(vitals): creates api for organization vitals
  .github/CODEOWNERS
  src/sentry/api/endpoints/organization_vitals_overview.py
  src/sentry/api/urls.py
  src/sentry/utils/prompts.py
  static/app/data/experimentConfig.tsx
  tests/sentry/api/endpoints/test_organization_vitals_overview.py
Labels: frontend, backend

#36331 fix(summary): remove extra search padding
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
Labels: frontend

#36333 ref(profiling): Use a connection pool to connect to the profiling service
  src/sentry/api/endpoints/organization_profiling_profiles.py
  src/sentry/utils/profiling.py
Labels: backend

#36323 ref(profiling): Remove the IAM authentication for profiling service calls
  src/sentry/utils/profiling.py
Labels: backend

#36226 fix(sudo modal): Stopped superuser prefill on sudo modal
  src/sentry/api/endpoints/auth_index.py
  tests/sentry/api/endpoints/test_auth_index.py
Labels: backend

#35558 fix(ui): Optimize alert bars for mobile
  static/app/components/alert.tsx
  static/app/views/settings/project/sampling/rules/index.tsx
Labels: frontend

#36337 fix(release-notification): Add custom email referrer
  src/sentry/notifications/notifications/rules.py
  src/sentry/notifications/utils/__init__.py
Labels: backend

#36191 ref(dashboards): Move y-axis into config
  static/app/utils/discover/fields.tsx
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/datasetConfig/issues.tsx
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/yAxisStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/yAxisStep/releaseYAxisSelector.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/yAxisStep/yAxisSelector/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
Labels: frontend

#36278 feat(active-release): add commit data to slack release notifications
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/integrations/slack/message_builder/notifications/issues.py
  src/sentry/notifications/notifications/rules.py
  tests/sentry/integrations/slack/test_message_builder.py
Labels: backend

#36325 feat(sampling): Disallow base rule deletion [TET-164]
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/utils/index.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
Labels: frontend

#36328 ref(locks): Make the post_process locks backend configurable
  src/sentry/conf/server.py
  src/sentry/tasks/post_process.py
  src/sentry/utils/locking/backends/redis.py
  tests/sentry/utils/locking/backends/test_redis.py
Labels: backend

#36330 feat(locking): Add locks backend for migration
  src/sentry/utils/locking/backends/migration.py
  tests/sentry/utils/locking/backends/test_migration.py
Labels: backend

#36332 feat(sampling): Add recommended steps modal - [TET-164]
  static/app/components/sidebar/broadcastSdkUpdates.tsx
  static/app/types/sampling.tsx
  static/app/views/settings/organizationRepositories/organizationRepositories.tsx
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/promo.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useSamplingDistribution.tsx
  static/app/views/settings/project/server-side-sampling/utils/useSdkVersions.tsx
  tests/js/spec/views/settings/project/server-side-sampling/activateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/recommendedStepsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/specificConditionsModal.spec.tsx
Labels: frontend

#36335 fix(widget-builder): Ensure defaultTableColumns is string[]
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
Labels: frontend

#36355 feat(sampling): Add active rule without updated sdk alert [TET-164]
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useSdkVersions.tsx
  tests/js/spec/views/settings/project/server-side-sampling/recommendedStepsModal.spec.tsx
Labels: frontend

#36352 feat(sampling): Add onboarding guides [TET-164]
  src/sentry/assistant/guides.py
  static/app/components/assistant/getGuidesContent.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: frontend, backend

#36336 chore: Update sentry-relay version to get new categories
  requirements-base.txt
  tests/sentry/event_manager/interfaces/snapshots/test_frame/test_context_with_nan/neginf.pysnap
Labels: backend

#36354 feat(sampling): Add recommended steps tests and tests clean up - [TET-164]
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/activateModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/recommendedStepsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/specificConditionsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/recommendedStepsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils.tsx
Labels: frontend

#36168 fix(compactSelect): Fix menu offset issue
  static/app/components/forms/compactSelect.tsx
  static/app/utils/theme.tsx
  static/app/views/dashboardsV2/manage/index.tsx
  static/app/views/eventsV2/landing.tsx
  static/app/views/organizationStats/index.tsx
  tests/js/spec/views/dashboardsV2/manage/index.spec.jsx
  tests/js/spec/views/eventsV2/index.spec.jsx
  tests/js/spec/views/organizationStats/index.spec.jsx
Labels: frontend

#36363 ref(sampling): Fix infinite loop in the useSdkVersions hook
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useSdkVersions.tsx
Labels: frontend

#36305 feat(icon): added option
  docs-ui/stories/assets/icons/data.tsx
  static/app/icons/iconOption.tsx
  static/app/icons/index.tsx
Labels: frontend

#36339 fix(multi-region): Update org slug regex for new organizations
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/organization_index.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/models/organization.py
  tests/sentry/api/endpoints/test_organization_index.py
Labels: backend

#36362 feat(perf): Use link icon over anchor icon for span id and event id in span tree
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/views/performance/traceDetails/transactionDetail.tsx
Labels: frontend

#35975 feat(dashboards): display an alert when a custom measurement widget has incompatible settings
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
  static/app/views/dashboardsV2/widgetCard/index.tsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
Labels: frontend

#36374 ref(package.json): Use explicit react-aria submodules
  package.json
  yarn.lock
Labels: frontend

#36373 ref(button): Add xs/sm/md size options to button props
  docs-ui/stories/components/button.stories.js
  static/app/components/button.tsx
  static/app/components/organizations/pageFilterBar.tsx
  static/app/utils/theme.tsx
Labels: frontend

#36377 chore(deletion) Pause organization deletions
  src/sentry/tasks/deletion.py
  tests/sentry/deletions/test_organization.py
Labels: backend

#36365 fix(perf) currentEvent counter inaccurate if < totalEventCount
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
Labels: frontend

#36023 feat(dashboards): updates widget builder to use custom measurements
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
  static/app/views/eventsV2/table/queryField.tsx
  static/app/views/eventsV2/table/types.tsx
  static/app/views/eventsV2/utils.tsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.spec.tsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
  tests/js/spec/views/eventsV2/utils.spec.jsx
Labels: frontend

#36383 chore(deletion) Pause organization deletions part 2
  src/sentry/tasks/deletion.py
  tests/sentry/deletions/test_organization.py
Labels: backend

#36327 fix(perf) Fix percentile selection in all events tab
  static/app/views/performance/transactionSummary/transactionEvents/index.tsx
  tests/js/spec/views/performance/transactionSummary/transactionEvents/eventsTable.spec.tsx
  tests/js/spec/views/performance/transactionSummary/transactionEvents/index.spec.tsx
Labels: frontend

#36292 feat(mep): Write default value for `AlertRule.type`.
  src/sentry/incidents/logic.py
  src/sentry/incidents/models.py
  tests/sentry/incidents/test_logic.py
Labels: backend

#36384 fix(multi-region): Update org slug regex for new orgs
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/organization_index.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/models/organization.py
  tests/sentry/api/endpoints/test_organization_index.py
Labels: backend

#36381 ref(js): Use options for projectPerformance settings
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: frontend

#36338 ref(performance): Use CompactSelect for transaction list filter
  static/app/components/discover/transactionsList.tsx
  tests/js/spec/components/discover/transactionsList.spec.jsx
  tests/js/spec/views/performance/transactionSummary.spec.tsx
Labels: frontend

#36294 feat(mep): Backfill `AlertRule.type` column.
  migrations_lockfile.txt
  src/sentry/migrations/0295_backfill_alertrule_type.py
  tests/sentry/migrations/test_0295_backfill_alertrule_type.py
Labels: backend

#36264 fix(settings): Sort platforms list by ID to make Node.js easier to select
  static/app/data/platforms.tsx
Labels: frontend

#36295 feat(mep): Make `AlertRule.type` not null
  migrations_lockfile.txt
  src/sentry/incidents/models.py
  src/sentry/migrations/0296_alertrule_type_not_null.py
  tests/sentry/migrations/test_0295_backfill_alertrule_type.py
Labels: backend

#36391 ref(js): Use options in storybook icons
  docs-ui/stories/assets/icons/data.tsx
  docs-ui/stories/assets/icons/popper.tsx
  docs-ui/stories/assets/icons/searchPanel.tsx
Labels: frontend

#36388 style(js): Small code style cleanup in stacktracePreview
  static/app/components/stacktracePreview.tsx
Labels: frontend

#36399 chore(js): Bump storybook
  docs-ui/storybook/main.ts
  docs-ui/storybook/preview.tsx
  package.json
  yarn.lock
Labels: frontend

#36405 fix(alert): Metric alert preset log experiment & bug fixes
  static/app/views/alerts/create.tsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/wizard/index.tsx
Labels: frontend

#36367 ref(sampling): Remove activate modal - [TET-164]
  static/app/views/settings/project/server-side-sampling/modals/activateModal.tsx
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/activateModal.spec.tsx
Labels: frontend

#36364 feat(replays): Rewrite navtabs so click targets are bigger
  static/app/components/replays/navTabs.tsx
  static/app/views/replays/detail/focusTabs.tsx
Labels: frontend

#36360 feat(sampling): Consolidate sampling alerts [TET-164]
  static/app/types/sampling.tsx
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/samplingSDKAlert.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: frontend

#36412 fix(dynamic-sampling): Change query time boundaries for cache
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
  tests/sentry/api/endpoints/test_organization_dynamic_sampling_sdk_versions.py
Labels: backend

#36415 ref(redis): Disconnect from redis after service validation and version check
  src/sentry/ratelimits/concurrent.py
  src/sentry/ratelimits/redis.py
  src/sentry/ratelimits/sliding_windows.py
  src/sentry/utils/redis.py
Labels: backend

#36408 ref(sampling): Open uniform rate modal when editing a uniform rule - [TET-164]
  static/app/types/project.tsx
  static/app/types/sampling.tsx
  static/app/views/settings/project/sampling/modal/index.tsx
  static/app/views/settings/project/sampling/sampling.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/promo.tsx
  static/app/views/settings/project/server-side-sampling/samplingSDKAlert.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
Labels: frontend

#36414 ref(sampling): Add sample rate from previous modal - [TET-164]
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/samplingSDKAlert.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/recommendedStepsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/specificConditionsModal.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils.tsx
Labels: frontend

#36395 chore(discover): Dedupe rate_limits code
  src/sentry/api/endpoints/organization_events.py
Labels: backend

#36398 ref(overlay): Update PositionWrapperProps
  static/app/components/overlay.tsx
Labels: frontend

#36371 ref(perf): Use CompactSelect for span operations filter
  static/app/components/events/interfaces/spans/filter.tsx
  static/app/components/events/interfaces/spans/index.tsx
  tests/acceptance/test_organization_events_v2.py
Labels: frontend, backend

#36366 ref(perf): Use popper hook & new overlay component in TagsHeatMap
  static/app/views/performance/transactionSummary/transactionTags/tagsHeatMap.tsx
Labels: frontend

#36379 test(ui): Convert timeRangeSelector to RTL
  tests/js/spec/components/organizations/timeRangeSelector/index.spec.jsx
Labels: frontend

#36428 fix(issues): Show missing suggested assignees
  static/app/components/group/suggestedOwners/suggestedOwners.tsx
  tests/js/spec/components/group/suggestedOwners.spec.jsx
Labels: frontend

#36433 chore: Re-export hasProjectBeenRenamed for api.tsx in tests
  static/app/__mocks__/api.tsx
Labels: frontend

#36434 fix(profiling): properly detect typescript profiles
  static/app/utils/profiling/profile/chromeTraceProfile.tsx
  static/app/utils/profiling/profile/importProfile.tsx
  tests/js/spec/utils/profiling/profile/chromeTraceProfile.spec.tsx
  tests/js/spec/utils/profiling/profile/importProfile.spec.tsx
Labels: frontend

#36345 feat(2fa): support for upcoming 2fa backend change
  fixtures/js-stubs/authenticators.js
  static/app/types/auth.tsx
  static/app/views/settings/account/accountSecurity/index.tsx
  tests/js/spec/views/accountSecurity.spec.jsx
Labels: frontend

#36344 feat(2fa): option for disallowing new enrollments on 2FA interface
  src/sentry/api/endpoints/user_authenticator_enroll.py
  src/sentry/api/serializers/models/authenticator.py
  src/sentry/auth/authenticators/base.py
  src/sentry/options/defaults.py
  tests/sentry/api/endpoints/test_user_authenticator_enroll.py
Labels: backend

#36238 fix(alert): Backfill nonexistent alert owners related to project transfer
  migrations_lockfile.txt
  src/sentry/migrations/0297_backfill_alert_owners.py
  tests/sentry/migrations/test_0297_backfill_alert_owners.py
Labels: backend

#36424 feat(sampling): Wire up the save/edit uniform rule flow [TET-164]
  static/app/types/sampling.tsx
  static/app/views/settings/project/server-side-sampling/modals/recommendedStepsModal.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/samplingSDKAlert.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/index.tsx
  static/app/views/settings/project/server-side-sampling/utils/useProjectStats.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/recommendedStepsModal.spec.tsx
Labels: frontend

#36423 feat(profiling): add layout component
  static/app/components/profiling/flamegraph.tsx
  static/app/components/profiling/profilingFlamechartLayout.tsx
Labels: frontend

#36470 feat(sampling): Fix sampling prediction chart logic [TET-164]
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.tsx
Labels: frontend

#36469 feat(sampling): Add ability to activate the rule [TET-164]
  static/app/views/settings/project/server-side-sampling/rule.tsx
  static/app/views/settings/project/server-side-sampling/samplingSDKAlert.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: frontend

#36468 doc(killswitches): Update description for metrics extraction killswitch [INGEST-333]
  src/sentry/killswitches.py
Labels: backend

#36369 feat(profiling): add internal debug mode sample ticks
  static/app/components/profiling/flamegraphZoomView.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/hooks/useInternalFlamegraphDebugMode.ts
  static/app/utils/profiling/renderers/sampleTickRenderer.tsx
Labels: frontend

#36229 ref(dashboards): Add an optional check before accessing length
  static/app/views/dashboardsV2/widgetCard/chart.tsx
Labels: frontend

#36302 feat(replays): aside tabs for sidebar layout
  static/app/components/replays/replayContext.tsx
  static/app/components/replays/replayView.tsx
  static/app/views/replays/detail/breadcrumbs/index.tsx
  static/app/views/replays/detail/layout/asideTabs_v2.tsx
  static/app/views/replays/detail/layout/index.tsx
  static/app/views/replays/detail/layout/pageSections.tsx
  static/app/views/replays/detail/layout/resizePanel.tsx
  static/app/views/replays/detail/tagPanel.tsx
Labels: frontend

#36476 fix(dashboards): Fix flakey debounce test
  tests/js/spec/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.spec.tsx
Labels: frontend

#36394 fix(dashboards): Fixes widgetQuery not updating isMetricData correctly
  static/app/views/dashboardsV2/widgetCard/widgetQueries.tsx
  tests/js/spec/views/dashboardsV2/widgetCard.spec.tsx
Labels: frontend

#36454 fix(copy): tidied up the copy of release quick start
  static/app/views/releases/list/releasesPromo.tsx
  tests/js/spec/views/releases/list/index.spec.jsx
Labels: frontend

#36478 feat(profiling): create a virtual root for the flamegraph
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/renderers/flamegraphRenderer.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer2D.tsx
  static/app/utils/profiling/renderers/textRenderer.tsx
Labels: frontend

#36472 ref: replace some map() calls with f-strings
  src/sentry/api/event_search.py
  src/sentry/tsdb/redis.py
Labels: backend, trigger-getsentry-external

#36455 feat: Update replaceRouterParams to support number parameters
  static/app/utils/replaceRouterParams.tsx
  tests/js/spec/utils/replaceRouterParams.spec.tsx
Labels: frontend

#36450 fix(model): use textfield instead of varchar for filenames
  migrations_lockfile.txt
  src/sentry/migrations/0299_update_commitfilechange_filename_type.py
  src/sentry/models/commitfilechange.py
Labels: backend

#36437 feat(multi-region): Update the Sentry JS SDK config to support customer domains on local dev
  static/app/bootstrap/initializeSdk.tsx
Labels: frontend

#36393 ref(auditlog): Update auditlog to functional component
  static/app/views/settings/organizationAuditLog/auditLogList.tsx
  static/app/views/settings/organizationAuditLog/index.tsx
  tests/js/spec/views/settings/auditLogView.spec.jsx
  tests/js/spec/views/settings/organizationAuditLog.spec.jsx
Labels: frontend

#36453 chore(multi-region): Rename system.customer-base-hostname to system.organization-base-hostname
  src/sentry/options/defaults.py
  src/sentry/utils/pytest/sentry.py
Labels: backend

#36411 feat(dashboards): Add Releases top level filter
  static/app/utils/releases/releasesProvider.tsx
  static/app/views/dashboardsV2/detail.tsx
  static/app/views/dashboardsV2/releasesSelectControl.tsx
  static/app/views/dashboardsV2/widgetCard/releaseWidgetQueries.tsx
  tests/js/spec/utils/releases/useReleases.spec.tsx
  tests/js/spec/views/dashboardsV2/gridLayout/detail.spec.jsx
  tests/js/spec/views/dashboardsV2/releaseWidgetQueries.spec.tsx
  tests/js/spec/views/dashboardsV2/releasesSelectControl.spec.tsx
Labels: frontend

#36467 ref(sampling): Fix sampling modal race condition - [TET-164]
  static/app/actionCreators/serverSideSampling.tsx
  static/app/stores/serverSideSamplingStore.tsx
  static/app/views/settings/project/sampling/rules/rule/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/utils/useRecommendedSdkUpgrades.tsx
  static/app/views/settings/project/server-side-sampling/utils/useSamplingDistribution.tsx
  static/app/views/settings/project/server-side-sampling/utils/useSdkVersions.tsx
  tests/js/spec/stores/serverSideSamplingStore.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils.tsx
Labels: frontend

#36496 ref(dashboard): Remove unused metrics meta store
  static/app/stores/metricsMetaStore.tsx
  tests/js/spec/stores/metricsMetaStore.spec.tsx
Labels: frontend

#36484 chore(deps): Upgrade @sentry/* JS SDK to 7.6.0
  package.json
  yarn.lock
Labels: frontend

#36334 feat(dashboards): Updates metric badge to Sampled and adds tooltip to Open in Discover buttons for CM widgets
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboardsV2/widgetCard/widgetCardContextMenu.tsx
  tests/js/spec/views/dashboardsV2/widgetCard.spec.tsx
Labels: frontend

#36475 fix(dashboards): extend handling no order by options to all datasets
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
Labels: frontend

#36502 chore(deps): Bump sentry-sdk to 1.7.0 to enable baggage propagation
  requirements-base.txt
Labels: backend

#36508 ref(mep): Rename the dataset to generic_metrics
  src/sentry/search/events/builder.py
  tests/sentry/search/events/test_builder.py
Labels: backend

#36447 fix(dashboards): fixes custom metrics not showing up in yaxis in widget builder
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/yAxisStep/yAxisSelector/index.tsx
Labels: frontend

#36449 feat(dashboards): adds a custom measurement type and store supported functions
  static/app/utils/customMeasurements/customMeasurements.tsx
  static/app/utils/customMeasurements/customMeasurementsContext.tsx
  static/app/utils/customMeasurements/customMeasurementsProvider.tsx
  static/app/utils/measurements/measurements.tsx
Labels: frontend

#36509 feat(sampling): Adjust the chart prediction logic [TET-211]
  static/app/views/organizationStats/types.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToPredictedSeries.spec.tsx
Labels: frontend

#36511 fix(mep): Apdex and misery were calculated wrong
  src/sentry/search/events/constants.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/testutils/cases.py
  tests/snuba/api/endpoints/test_organization_events_v2.py
Labels: backend

#36510 feat(sampling): Add ability to activate rule without SDKs updated [TET-211]
  static/app/views/settings/project/server-side-sampling/rule.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
Labels: frontend

#36435 Fix(release_notifications): Change `slack_release` referrer to `alert_slack_release`
  src/sentry/integrations/slack/message_builder/issues.py
  tests/sentry/integrations/slack/test_message_builder.py
Labels: backend

#36519 ref(apm): Add apm for process_incr tasks
  src/sentry/utils/sdk.py
Labels: backend

#36529 feat(icon): added rotational panel icon
  docs-ui/stories/assets/icons/data.tsx
  static/app/icons/iconPanel.tsx
  static/app/icons/index.tsx
Labels: frontend

#36259 feat(profiling): add zoomIntoFrame strategy
  static/app/components/profiling/FrameStack/frameStackContextMenu.tsx
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/components/profiling/flamegraph.tsx
  static/app/components/profiling/flamegraphSearch.tsx
  static/app/components/profiling/flamegraphZoomView.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  static/app/utils/profiling/gl/utils.ts
  tests/js/spec/utils/profiling/canvasScheduler.spec.tsx
  tests/js/spec/utils/profiling/gl/utils.spec.tsx
Labels: frontend

#36533 feat(vitals): add vitals alert cta component
  static/app/components/alerts/notificationBar.tsx
  static/app/components/performance/vitalsAlert/constants.tsx
  static/app/components/performance/vitalsAlert/types.tsx
  static/app/components/performance/vitalsAlert/utils.tsx
  static/app/components/performance/vitalsAlert/vitalsAlertCTA.tsx
  static/app/utils/analytics/growthAnalyticsEvents.tsx
Labels: frontend

#36370 feat(profiling): split hovered and selected states
  static/app/components/profiling/FrameStack/frameStack.tsx
  static/app/components/profiling/flamegraphSearch.tsx
  static/app/components/profiling/flamegraphZoomView.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphProfiles.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/index.tsx
  static/app/utils/profiling/gl/utils.ts
  tests/js/spec/utils/profiling/canvasScheduler.spec.tsx
Labels: frontend

#35448 feat(perf): Add performance onboarding checklist
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/components/onboardingWizard/task.tsx
  static/app/components/onboardingWizard/taskConfig.tsx
  static/app/components/performanceOnboarding/sidebar.tsx
  static/app/components/performanceOnboarding/step.tsx
  static/app/components/performanceOnboarding/usePerformanceOnboardingDocs.tsx
  static/app/components/performanceOnboarding/utils.tsx
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/types.tsx
  static/app/data/platformCategories.tsx
  static/app/types/onboarding.tsx
  static/app/views/performance/onboarding.tsx
  static/app/views/projectDetail/missingFeatureButtons/missingPerformanceButtons.tsx
  tests/js/spec/components/sidebar/index.spec.jsx
  tests/js/spec/components/sidebar/performanceOnboarding.spec.tsx
  tests/js/spec/components/sidebar/usePerformanceOnboardingDocs.spec.tsx
  tests/js/spec/views/performance/content.spec.jsx
Labels: Status: In Progress, frontend

#36539 Revert "chore(deps): Bump sentry-sdk to 1.7.0 to enable baggage propagation"
  requirements-base.txt
Labels: backend

#36540 Revert "feat(active-release): Send 1 hour deploy summary notif"
  src/sentry/conf/server.py
  src/sentry/notifications/notifications/activity/release_summary.py
  src/sentry/notifications/utils/participants.py
  src/sentry/tasks/release_summary.py
  src/sentry/templates/sentry/emails/activity/release_summary.html
  src/sentry/templates/sentry/emails/activity/release_summary.txt
  src/sentry/web/debug_urls.py
  src/sentry/web/frontend/debug/debug_release_summary_email.py
  tests/sentry/mail/activity/test_release_summary.py
  tests/sentry/tasks/test_release_summary.py
Labels: backend

#36293 feat(ui): Add DataCategory for processed transactions
  static/app/constants/index.tsx
  static/app/types/core.tsx
Labels: frontend

#36457 feat(auditlog): Add version 2 to audit log endpoint
  src/sentry/api/endpoints/organization_auditlogs.py
  tests/sentry/api/endpoints/test_organization_auditlogs.py
Labels: backend

#36542 chore(ui): Bump enzyme-adapter-react-17
  .github/dependabot.yml
  package.json
  yarn.lock
Labels: frontend

#36431 feat(customer-domains): Add sentryUrl and organizationUrl to config on the frontend
  fixtures/js-stubs/config.js
  static/app/types/system.tsx
  tests/js/spec/stores/configStore.spec.tsx
Labels: frontend

#36499 perf(workflow): add index to Deploy.date_finished
  migrations_lockfile.txt
  src/sentry/migrations/0300_deploy_date_finished_index.py
  src/sentry/models/deploy.py
Labels: backend

#36441 feat: Add organizationUrl to OrganizationSummary
  src/sentry/api/serializers/models/organization.py
  tests/sentry/api/endpoints/test_organization_details.py
Labels: backend

#36442 feat: Add organizationUrl to OrganizationSummary (frontend)
  fixtures/js-stubs/organization.js
  static/app/types/organization.tsx
Labels: frontend

#36535 fix(smartSearch): Fix autocomplete race conditions
  static/app/components/smartSearchBar/index.tsx
  tests/js/spec/components/smartSearchBar/index.spec.jsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
Labels: frontend

#36530 fix(api): increase CommitPatchSetSerializer.path max_length limit
  src/sentry/api/serializers/rest_framework/commit.py
  tests/sentry/api/endpoints/test_organization_release_details.py
Labels: backend

#36507 fix(widget): Disable sort by when sort and direction aren't allowed
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/sortByStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/sortByStep/sortBySelectors.tsx
Labels: frontend

#36521 feat(sampling): Round sampling rates to the common ones [TET-211]
  static/app/utils/findClosestNumber.tsx
  static/app/views/settings/project/server-side-sampling/utils/projectStatsToSampleRates.tsx
  tests/js/spec/utils/findClosestNumber.spec.tsx
  tests/js/spec/views/settings/project/server-side-sampling/utils/projectStatsToSampleRates.spec.tsx
Labels: frontend

#36561 ref(sampling): Do not fetch distribution and sdk-versions endpoint if no permission- [T211]
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  tests/js/spec/views/settings/project/server-side-sampling/index.spec.tsx
Labels: frontend

#36543 fix(dyn-sampling): Discards irrelevant sdk names and versions
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
  tests/sentry/api/endpoints/test_organization_dynamic_sampling_sdk_versions.py
Labels: backend

#36432 ref(profiling): rename event names
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/components/profiling/flamegraph.tsx
  static/app/components/profiling/flamegraphOptionsMenu.tsx
  static/app/components/profiling/flamegraphSearch.tsx
  static/app/components/profiling/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  tests/js/spec/utils/profiling/canvasScheduler.spec.tsx
Labels: frontend

#36560 fix(mep): partition cache keyspace
  src/sentry/sentry_metrics/indexer/cache.py
  src/sentry/sentry_metrics/indexer/postgres_v2.py
  tests/sentry/sentry_metrics/test_indexer_cache.py
  tests/sentry/sentry_metrics/test_postgres_indexer.py
Labels: backend

#36562 ref(sampling): Remove empty Add option in conditions modal - [T211]
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/tagValueAutocomplete.tsx
  tests/js/spec/views/settings/project/server-side-sampling/modals/specificConditionsModal.spec.tsx
Labels: frontend

#36566 feat(discover): lowers rate limit for events endpoint
  src/sentry/api/endpoints/organization_events.py
  tests/snuba/api/endpoints/test_organization_events_v2.py
Labels: backend

#36158 feat(custom-measurements): Support custom measurements in mqb
  src/sentry/api/endpoints/organization_metrics.py
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/utils.py
  tests/sentry/snuba/metrics/test_datasource.py
  tests/snuba/api/endpoints/test_organization_events_v2.py
Labels: backend

#36564 fix(projectconfig): Bring back metric with request version
  src/sentry/api/endpoints/relay/project_configs.py
Labels: backend

#36456 fix(ui): lost password link text
  static/app/views/auth/loginForm.tsx
Labels: frontend

#36550 fix(settings): Manually call blur in booleanField, save usage setting
  static/app/components/forms/controls/radioBoolean.tsx
  tests/js/spec/components/deprecatedforms/radioBooleanField.spec.jsx
Labels: frontend

#36494 feat(auditlog): Update Audit Log UI to use endpoint version 2
  fixtures/js-stubs/auditLogsApiEventNames.js
  static/app/views/settings/organizationAuditLog/auditLogList.tsx
  static/app/views/settings/organizationAuditLog/index.tsx
  tests/js/spec/views/settings/auditLogView.spec.jsx
  tests/js/spec/views/settings/organizationAuditLog.spec.jsx
Labels: frontend

#34879 feat: frozen dependencies
  .dockerignore
  .github/actions/setup-sentry/action.yml
  .github/file-filters.yml
  .github/workflows/backend.yml
  .pre-commit-config.yaml
  Makefile
  bin/__init__.py
  config/hooks/post-merge
  docker/Dockerfile
  docker/builder.sh
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-dev-only-frozen.txt
  requirements-dev.txt
  requirements-frozen.txt
  scripts/lib.sh
  setup.py
  tools/check_frozen_requirements.py
  tools/freeze_requirements.py
  tools/lint_requirements.py
Labels: backend
