Repository getsentry/sentry, pull requests merged in 2022-06, with the labels that each got.

#35095 feat(replays): add 'Share' button in header to deeplink timestamp
  static/app/utils/replays/createUrlToShare.tsx
  static/app/views/replays/detail/detailLayout.tsx
Labels: Team: Emerging Technology

#35440 fix(dev): Do not export SENTRY_DSN in .envrc
  .envrc
  config/hooks/pre-commit
  scripts/lib.sh
Labels: Component: Developer Environment

#35141 feat(replays): show lists of replays on Issues details page
  static/app/routes.tsx
  static/app/utils/replays/getQueryParamAsString.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.tsx
  static/app/views/organizationGroupDetails/groupReplays/index.tsx
  static/app/views/organizationGroupDetails/header.tsx
  static/app/views/organizationGroupDetails/types.tsx
  static/app/views/replays/replayTable.tsx
  static/app/views/replays/replays.tsx
  tests/js/spec/views/organizationGroupDetails/groupDetails.spec.jsx
Labels: Team: Emerging Technology

#35466 fix(ci): Prevent meeting acceptance required checks by mistake
  .github/workflows/acceptance.yml
Labels: Component: CI

#35474 fix(ci): Skip running visual snapshots if there are no BE or FE changes
  .github/workflows/acceptance.yml
Labels: Component: CI

#35472 feat(ci): Adjust mapping of workflow changes to executing them
  .github/file-filters.yml
Labels: Component: CI

#35449 fix(replays): show right time on breadcrumbs
  static/app/components/replays/utils.tsx
Labels: Team: Emerging Technology

#35463 fix(replays): fix single line console messages alignment
  static/app/views/replays/detail/console/consoleMessage.tsx
Labels: Team: Emerging Technology

#35420 feat(ci): Label PRs backend / frontend
  .github/workflows/label-pullrequest.yml
Labels: frontend, backend

#35514 fix(replays): show right time on breadcrumbs
  static/app/components/replays/utils.tsx
Labels: Team: Emerging Technology

#35515 ref: move sudo testutils to fixtures
  fixtures/sudo_testutils.py
  tests/sentry/sudo/models.py
  tests/sentry/sudo/test_forms.py
  tests/sentry/sudo/test_middleware.py
  tests/sentry/sudo/test_signals.py
  tests/sentry/sudo/test_utils.py
  tests/sentry/sudo/test_views.py
Labels: backend

#35517 ref: enforce test naming so tests actually run
  .pre-commit-config.yaml
  tests/sentry/apidocs/test_extensions.py
  tests/sentry/buffer/test_base.py
  tests/sentry/buffer/test_redis.py
  tests/sentry/data/test_samples.py
  tests/sentry/db/models/fields/test_bounded.py
  tests/sentry/models/test_lostpasswordhash.py
  tests/sentry/models/test_projectkey.py
  tests/sentry/nodestore/bigtable/test_backend.py
  tests/sentry/nodestore/django/test_backend.py
  tests/sentry/nodestore/test_common.py
  tests/sentry/plugins/base/test_project_api_urls.py
  tests/sentry/plugins/base/test_response.py
  tests/sentry/plugins/base/test_v2.py
  tests/sentry/plugins/bases/test_issue.py
  tests/sentry/plugins/bases/test_notify.py
  tests/sentry/plugins/sentry_useragents/test_models.py
  tests/sentry/plugins/test_helpers.py
  tests/sentry/quotas/test_redis.py
  tests/sentry/services/test_smtp.py
  tests/sentry/tasks/test_post_process.py
  tests/sentry/tasks/test_process_buffer.py
  tests/sentry/utils/email/test_signer.py
  tests/sentry/utils/test_audit.py
  tests/sentry/utils/test_auth.py
  tests/sentry/utils/test_hashlib.py
  tests/sentry/utils/test_http.py
  tests/sentry/utils/test_json.py
  tests/sentry/utils/test_query.py
  tests/sentry/utils/test_settings.py
  tests/sentry/web/test_api.py
  tests/sentry/web/test_urls.py
  tests/tools/test_docker_memory_check.py
  tests/tools/test_flake8_plugin.py
  tests/tools/test_patch_selenium.py
Labels: backend

#35531 ref: fix test pollution in test_mediator.py
  tests/sentry/mediators/test_mediator.py
Labels: backend

#35461 feat(profiling): Add support for Rust profiles ingestion
  src/sentry/profiles/task.py
Labels: backend

#34938 feat(analytics): Add reference implementation links
  static/app/components/modals/createNewIntegrationModal.tsx
  static/app/utils/analytics/integrations/index.ts
  static/app/utils/analytics/integrations/platformAnalyticsEvents.ts
  static/app/utils/analytics/makeAnalyticsFunction.tsx
  static/app/views/organizationIntegrations/createIntegrationButton.tsx
  static/app/views/organizationIntegrations/exampleIntegrationButton.tsx
  static/app/views/organizationIntegrations/integrationListDirectory.tsx
  static/app/views/settings/organizationDeveloperSettings/index.tsx
Labels: Component: Analytics, Team: Ecosystem, frontend

#35540 ref: actually test async/sync consumer
  tests/sentry/ingest/ingest_consumer/test_ingest_consumer_kafka.py
Labels: backend

#35532 fix(customResolutionModal): Use new select UI
  static/app/components/customResolutionModal.tsx
Labels: frontend

#35538 feat(dashboards): Add transformSeries to dataset config
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/widgetCard/index.tsx
  static/app/views/dashboardsV2/widgetCard/releaseWidgetQueries.tsx
  static/app/views/dashboardsV2/widgetCard/transformSessionsResponseToSeries.tsx
  static/app/views/dashboardsV2/widgetCard/widgetQueries.tsx
  tests/js/spec/components/modals/addToDashboardModal.spec.tsx
Labels: frontend

#35156 feat(search): Add quick actions with keyboard hotkeys to the search bar
  static/app/components/searchSyntax/renderer.tsx
  static/app/components/smartSearchBar/index.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
  static/app/components/smartSearchBar/searchHotkeysListener.tsx
  static/app/components/smartSearchBar/types.tsx
  static/app/components/smartSearchBar/utils.tsx
  static/app/utils/theme.tsx
  tests/js/spec/components/smartSearchBar/index.spec.jsx
Labels: frontend

#33487 feat(metrics) Add a metric to measure how long it takes to the indexer to build a batch
  src/sentry/sentry_metrics/multiprocess.py
Labels: Status: Stale, backend

#35524 feat(search): Search quick actions support browser undo/redo
  static/app/components/smartSearchBar/index.tsx
Labels: frontend

#35530 feat: shuffle tests when SENTRY_SHUFFLE_TESTS is set
  src/sentry/utils/pytest/sentry.py
Labels: backend

#35550 ref(icons): add existing icons to storybook
  docs-ui/stories/assets/icons/data.tsx
Labels: frontend

#35266 feat(deprecation): Moved brownout cron spec to option manager
  requirements-base.txt
  src/sentry/api/helpers/deprecation.py
  src/sentry/options/defaults.py
  tests/sentry/helpers/test_deprecation.py
Labels: backend

#35569 ref(grouping): Add read docs button
  static/app/views/organizationGroupDetails/grouping/grouping.tsx
  static/app/views/settings/components/dataScrubbing/index.tsx
  tests/js/spec/views/settings/components/dataScrubbing/dataScrubbing.spec.tsx
Labels: frontend

#35543 ref: delete some dead code in sentry.utils
  src/sentry/utils/cache.py
  src/sentry/utils/dates.py
  src/sentry/utils/distutils/commands/base.py
  src/sentry/utils/fernet_encrypt.py
  src/sentry/utils/http.py
  src/sentry/utils/math.py
  src/sentry/utils/redis.py
  src/sentry/utils/safe.py
  src/sentry/utils/samples.py
  src/sentry/utils/snuba.py
  src/sentry/utils/strings.py
  src/sentry/utils/threadpool.py
  src/sentry/utils/validators.py
  tests/sentry/utils/test_http.py
  tests/sentry/utils/test_safe.py
  tests/sentry/utils/test_strings.py
Labels: backend

#35542 fix(eventstore): Silently handled events beyond retention
  src/sentry/eventstore/snuba/backend.py
  tests/sentry/eventstore/snuba/test_backend.py
  tests/snuba/api/endpoints/test_organization_event_details.py
Labels: backend

#35573 ref(sampling): Add 'all' desc for single rules without conditions - [TET-125]
  static/app/views/settings/project/sampling/rules/rule/index.tsx
  tests/js/spec/views/settings/projectSampling/index.spec.tsx
Labels: frontend

#35305 fix(metrics): Restrict public name regex [TET-111]
  src/sentry/snuba/metrics/naming_layer/mri.py
  src/sentry/snuba/metrics/naming_layer/public.py
  src/sentry/snuba/metrics/query_builder.py
  src/sentry/snuba/metrics/utils.py
  tests/sentry/snuba/metrics/test_naming_layer.py
Labels: backend

#35566 ref(test): Convert to TS and RTL
  static/app/components/events/interfaces/frame/frameRegisters/index.tsx
  static/app/components/events/interfaces/frame/frameRegisters/utils.tsx
  static/app/components/events/interfaces/frame/frameRegisters/value.tsx
  tests/js/spec/components/events/interfaces/frame/frameRegisters.spec.jsx
  tests/js/spec/components/events/interfaces/frame/frameRegisters.spec.tsx
Labels: frontend

#35568 ref(translations): Add translation funcs to strings
  static/app/views/replays/detail/detailLayout.tsx
Labels: frontend

#35441 feat(perf): Transaction name search experiment
  static/app/components/performance/searchBar.tsx
  static/app/views/performance/content.tsx
  static/app/views/performance/data.tsx
  static/app/views/performance/landing/index.tsx
  static/app/views/performance/landing/views/types.tsx
  static/app/views/performance/landing/widgets/components/widgetChartRow.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.tsx
  static/app/views/performance/landing/widgets/types.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/trendsWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  static/app/views/performance/table.tsx
  tests/js/spec/views/performance/landing/index.spec.tsx
  tests/js/spec/views/performance/landing/widgets/widgetContainer.spec.tsx
  tests/js/spec/views/performance/table.spec.tsx
Labels: frontend

#35528 fix(superuser): fixed superuser session on dev env for non sso flow
  src/sentry/api/endpoints/auth_index.py
  src/sentry/auth/superuser.py
Labels: backend

#35577 ref: fix exception AttributeError in social_auth.exceptions
  src/social_auth/exceptions.py
Labels: backend

#35574 ref: delete unused test templates
  tests/sentry/templates/404.html
  tests/sentry/templates/__init__.py
  tests/sentry/templates/sentry-tests/__init__.py
  tests/sentry/templates/sentry-tests/error.html
Labels: backend

#35584 ref: delete dead sentry.relay.query module
  src/sentry/relay/query.py
Labels: backend

#35578 ref: use the correct Any type in type annotations
  src/sentry/db/models/fields/foreignkey.py
  src/sentry/db/models/fields/onetoone.py
  src/sentry/db/models/manager/base_query_set.py
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/models/actor.py
  src/sentry/notifications/utils/actions.py
  src/sentry/shared_integrations/response/xml.py
  src/sentry/utils/types.py
Labels: backend

#35536 fix(ui): Add module to issue owners examples
  static/app/views/settings/project/projectOwnership/editRulesModal.tsx
  static/app/views/settings/project/projectOwnership/index.tsx
  static/app/views/settings/project/projectOwnership/ownerInput.tsx
  static/app/views/settings/project/projectOwnership/ruleBuilder.tsx
Labels: frontend

#35313 ref(calltree): fix scroll performance
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/components/profiling/FrameStack/frameStackTableRow.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
  tests/js/spec/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.spec.tsx
Labels: frontend

#35537 feat(mep): Add `build_snql_query` method to replace `build_snuba_filter`
  src/sentry/search/events/builder.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/snuba/tasks.py
  tests/sentry/snuba/test_entity_subscriptions.py
  tests/sentry/snuba/test_tasks.py
Labels: backend

#35519 fix(replays): highlight final console message if we scrub on or past it
  static/app/views/replays/detail/console/index.tsx
Labels: frontend

#35545 feat(perf): Add analytics events for Perf Landing Page and Trends
  static/app/components/pagination.tsx
  static/app/components/performance/teamKeyTransaction.tsx
  static/app/utils/analytics/performanceAnalyticsEvents.tsx
  static/app/views/performance/table.tsx
  static/app/views/performance/trends/changedTransactions.tsx
Labels: frontend

#35560 feat(mep): Implement `build_snql_query` for sessions
  src/sentry/search/events/builder.py
  src/sentry/search/events/datasets/sessions.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/utils/snuba.py
  tests/sentry/snuba/test_entity_subscriptions.py
  tests/sentry/snuba/test_tasks.py
Labels: backend

#35563 fix(integration): add asana icon
  static/app/utils/integrationUtil.tsx
Labels: frontend

#35589 feat(dashboard): Introduce supported display types to config
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/datasetConfig/issues.tsx
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
Labels: frontend

#35580 fix(profiling): Ensure table header is single line
  static/app/components/profiling/functionsTable.tsx
  static/app/components/profiling/profileTransactionsTable.tsx
  static/app/components/profiling/profilesTable.tsx
  static/app/types/profiling/core.tsx
  static/app/utils/profiling/tableRenderer.tsx
  static/app/views/profiling/utils.tsx
Labels: frontend

#35591 ref(icon-update): remove unused fill and update categories
  docs-ui/stories/assets/icons/data.tsx
  static/app/icons/iconLightning.tsx
  static/app/icons/iconLocation.tsx
Labels: frontend

#35583 ref: fix python2 import of SocketServer
  src/sentry/management/commands/serve_normalize.py
Labels: backend

#35586 ref: unroll ternary to work around mypy crash
  src/sentry/tsdb/redis.py
Labels: backend

#34596 feat(analytics): support organization as string
  static/app/types/hooks.tsx
  static/app/utils/analytics/makeAnalyticsFunction.tsx
Labels: Status: Stale, frontend

#35520 chore(django-3.2): Update django-rest-framework to 3.12.4
  requirements-base.txt
Labels: backend

#35529 feat(search): Move quick actions into a footer
  static/app/components/events/searchBar.tsx
  static/app/components/hotkeysLabel.tsx
  static/app/components/smartSearchBar/index.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
  static/app/components/smartSearchBar/types.tsx
  static/app/components/smartSearchBar/utils.tsx
  tests/js/spec/components/smartSearchBar/index.spec.jsx
Labels: frontend

#35269 ref(utils): use more robust approach to handling paths
  src/sentry/api/endpoints/project_create_sample.py
  src/sentry/api/endpoints/project_create_sample_transaction.py
  src/sentry/utils/integrationdocs.py
  src/sentry/utils/samples.py
  tests/sentry/api/endpoints/test_project_create_sample.py
  tests/sentry/api/endpoints/test_project_create_sample_transaction.py
  tests/sentry/utils/test_integrationdocs.py
  tests/sentry/utils/test_samples.py
Labels: backend

#34944 feat(sentry apps): Capture failed requests data and add sorting
  src/sentry/api/endpoints/integrations/sentry_apps/requests.py
  src/sentry/api/serializers/rest_framework/sentry_app_request.py
  src/sentry/mediators/external_requests/util.py
  src/sentry/utils/sentry_apps/request_buffer.py
  src/sentry/utils/sentry_apps/webhooks.py
  tests/sentry/api/endpoints/test_sentry_app_requests.py
  tests/sentry/tasks/test_sentry_apps.py
Labels: backend

#35238 ref(proj-config): Introduce new tasks [INGEST-1362 INGEST-1324]
  src/sentry/api/endpoints/relay/project_configs.py
  src/sentry/models/options/organization_option.py
  src/sentry/models/options/project_option.py
  src/sentry/models/projectkey.py
  src/sentry/relay/projectconfig_cache/redis.py
  src/sentry/relay/projectconfig_debounce_cache/__init__.py
  src/sentry/relay/projectconfig_debounce_cache/base.py
  src/sentry/relay/projectconfig_debounce_cache/redis.py
  src/sentry/tasks/relay.py
  src/sentry/utils/pytest/fixtures.py
  src/sentry/utils/sdk.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v3.py
  tests/sentry/relay/test_projectconfig_debounce_cache.py
  tests/sentry/tasks/test_relay.py
Labels: backend

#35270 ref(metrics_indexer): Use rapidjson, dont use deepcopy
  src/sentry/sentry_metrics/multiprocess.py
  tests/sentry/sentry_metrics/test_multiprocess_steps.py
Labels: backend

#35479 feat(profiling): add ghost row for hover/selected state
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/components/profiling/FrameStack/frameStackTableRow.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
  tests/js/spec/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.spec.tsx
Labels: frontend

#35619 ref(projectconfig): Add missing metric tag
  src/sentry/tasks/relay.py
Labels: backend

#35581 feat(perf): Add analytics to transaction summary and subpages
  static/app/utils/analytics/performanceAnalyticsEvents.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/charts.tsx
  static/app/views/performance/transactionSummary/transactionOverview/statusBreakdown.tsx
  static/app/views/performance/transactionSummary/transactionTags/content.tsx
  static/app/views/performance/transactionSummary/transactionTags/tagValueTable.tsx
Labels: frontend

#35592 feat: add replays org flag to EXPOSABLE_FEATURES
  src/sentry/relay/config/__init__.py
Labels: backend

#35556 ref(dashboards): Use select's `trailingItems` prop in QueryField
  static/app/views/eventsV2/table/queryField.tsx
  tests/js/spec/views/alerts/metricRules/metricField.spec.jsx
Labels: frontend

#35605 fix(breadcrumb): Fix overflowEllipsis interpolation
  static/app/components/breadcrumbs.tsx
Labels: frontend

#35547 ref(addDashboardWidgetModal): Use SelectControl's tooltip prop
  static/app/components/modals/addDashboardWidgetModal.tsx
  static/app/components/modals/widgetBuilder/addToDashboardModal.tsx
  tests/js/spec/components/modals/addDashboardWidgetModal.spec.jsx
Labels: frontend

#35227 ref(debugMeta): Use searchActionBarV2
  static/app/components/events/interfaces/debugMeta-v2/index.tsx
Labels: frontend

#35228 ref(debugImageDetails): Use searchBarActionV2
  static/app/components/events/interfaces/debugMeta-v2/debugImageDetails/candidates.tsx
Labels: frontend

#35627 fix(ui): Fix overflowEllipsis interpolation
  static/app/components/eventOrGroupTitle.tsx
  static/app/components/idBadge/badgeDisplayName.tsx
Labels: frontend

#35629 feat(perf): Remove implicit filters for the transaction search experiment
  static/app/views/performance/data.tsx
Labels: frontend

#35587 feat(profiling): add ability to filter call tree
  static/app/components/profiling/FrameStack/frameStack.tsx
  static/app/utils/profiling/filterFlamegraphTree.tsx
  tests/js/spec/utils/profiling/filterFlamegraphTree.spec.tsx
Labels: frontend

#35612 feat(profiling): pin columns
  static/app/components/profiling/FrameStack/frameStack.tsx
  static/app/components/profiling/FrameStack/frameStackTable.tsx
  static/app/components/profiling/FrameStack/frameStackTableRow.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
Labels: frontend

#35641 ref: use html.escape directly
  src/sentry/admin.py
  src/sentry/interfaces/base.py
  src/sentry/mediators/external_issues/creator.py
  src/sentry/notifications/notifications/activity/regression.py
  src/sentry/notifications/notifications/activity/resolved_in_release.py
  src/sentry/utils/html.py
  tools/flake8_plugin.py
Labels: backend

#35606 Feat/additional options for org analytics
  static/app/types/hooks.tsx
  static/app/utils/analytics/makeAnalyticsFunction.tsx
Labels: frontend

#35645 ref: simplify and type flake8 plugin
  mypy.ini
  tests/tools/test_flake8_plugin.py
  tools/flake8_plugin.py
Labels: backend

#35630 ref(searchBarAction): Remove V1
  static/app/components/events/interfaces/breadcrumbs/index.tsx
  static/app/components/events/interfaces/debugMeta-v2/debugImageDetails/candidates.tsx
  static/app/components/events/interfaces/debugMeta-v2/index.tsx
  static/app/components/events/interfaces/searchBarAction.tsx
  static/app/components/events/interfaces/searchBarAction/dropDownButton.tsx
  static/app/components/events/interfaces/searchBarAction/index.tsx
  static/app/components/events/interfaces/searchBarAction/searchBarActionFilter.tsx
  tests/js/spec/components/events/interfaces/breadcrumbs/filter.spec.tsx
Labels: frontend

#35631 feat(stacktrace-linking): optionally pass in stackframe data to endpoint
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
Labels: frontend

#35636 ref(ui): Remove `boundaryGap:true` from charts
  static/app/chartcuterie/discover.tsx
  static/app/components/charts/percentageAreaChart.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/app/views/projectsDashboard/chart.tsx
Labels: frontend

#35093 chore(deps): prepare for celery upgrade
  src/sentry/celery.py
  src/sentry/data_export/tasks.py
  src/sentry/tasks/base.py
  src/sentry/tasks/sentry_apps.py
  src/sentry/utils/pytest/sentry.py
Labels: backend

#35651 Revert "ref: simplify and type flake8 plugin (#35645)"
  mypy.ini
  tests/tools/test_flake8_plugin.py
  tools/flake8_plugin.py
Labels: backend

#35644 fix(page-filters): Date selector not respecting current start/end times
  static/app/components/organizations/timeRangeSelector/index.tsx
  tests/js/spec/components/organizations/timeRangeSelector/index.spec.jsx
Labels: frontend

#35414 fix(workflow): Added conditional check to cover issue regression
  src/sentry/event_manager.py
  tests/sentry/event_manager/test_event_manager.py
Labels: backend

#35617 ref(stack-trace): Add new design changes - [TET-128]
  static/app/components/events/interfaces/exceptionV2.tsx
  static/app/components/events/interfaces/frame/lineV2/nativeV2.tsx
  static/app/components/events/interfaces/nativeFrame.tsx
  static/app/components/events/interfaces/stackTraceV2.tsx
  static/app/components/events/interfaces/threadsV2.tsx
  static/app/components/events/traceEventDataSection.tsx
  static/app/components/events/traceEventDataSection/displayOptions.tsx
  static/app/components/events/traceEventDataSection/index.tsx
  static/app/components/events/traceEventDataSection/sortOptions.tsx
  tests/js/spec/components/events/interfaces/threadsV2.spec.tsx
Labels: frontend

#35668 fix(projectconfig): Invalidation task deals with deleted project
  src/sentry/api/endpoints/relay/project_configs.py
  src/sentry/tasks/relay.py
  tests/sentry/tasks/test_relay.py
Labels: backend

#35622 feat(dashboard): Add field options for table cols to config
  static/app/utils/measurements/measurements.tsx
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/datasetConfig/issues.tsx
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/releaseColumnFields.tsx
  static/app/views/dashboardsV2/widgetBuilder/utils.tsx
  static/app/views/eventsV2/utils.tsx
Labels: frontend

#35523 fix(relay): Defer cache invalidation up until after DB transaction [INGEST-1348]
  requirements-dev.txt
  src/sentry/models/options/organization_option.py
  src/sentry/models/options/project_option.py
  src/sentry/models/projectkey.py
  src/sentry/testutils/cases.py
  src/sentry/testutils/helpers/task_runner.py
  tests/sentry/tasks/test_relay.py
Labels: backend

#35670 ref(stack-trace): Update header style
  static/app/components/events/traceEventDataSection.tsx
Labels: frontend

#34524 ref: upgrade boto* packages to fix conflicts
  requirements-base.txt
Labels: Team: Ecosystem

#35620 feat: Thread names
  fixtures/native/threadnames.dmp
  src/sentry/lang/native/processing.py
  tests/symbolicator/test_minidump_full.py
Labels: backend

#35647 fix(replays): fix error/durations on Replays for page >1
  static/app/utils/replays/hooks/useDiscoveryQuery.tsx
  static/app/utils/replays/hooks/useReplayErrors.tsx
  static/app/views/replays/replayTable.tsx
Labels: Team: Emerging Technology

#35676 ref: allow explicit relative imports `from .json`
  tests/tools/test_flake8_plugin.py
  tools/flake8_plugin.py
Labels: backend

#35576 feat(discover): Support sum function while querying metrics in discover
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
  tests/snuba/api/endpoints/test_organization_events_v2.py
Labels: backend

#35677 ref: replace `import_submodules` with explicit `*` imports
  src/sentry/analytics/events/__init__.py
  src/sentry/api/fields/__init__.py
  src/sentry/api/serializers/models/__init__.py
  src/sentry/api/serializers/rest_framework/__init__.py
  src/sentry/api/validators/__init__.py
  src/sentry/deletions/defaults/__init__.py
  src/sentry/identity/bitbucket/__init__.py
  src/sentry/identity/github/__init__.py
  src/sentry/identity/github_enterprise/__init__.py
  src/sentry/identity/gitlab/__init__.py
  src/sentry/identity/google/__init__.py
  src/sentry/identity/providers/__init__.py
  src/sentry/identity/slack/__init__.py
  src/sentry/identity/vercel/__init__.py
  src/sentry/identity/vsts/__init__.py
  src/sentry/identity/vsts_extension/__init__.py
  src/sentry/integrations/aws_lambda/__init__.py
  src/sentry/integrations/bitbucket/__init__.py
  src/sentry/integrations/bitbucket_server/__init__.py
  src/sentry/integrations/custom_scm/__init__.py
  src/sentry/integrations/example/__init__.py
  src/sentry/integrations/github/__init__.py
  src/sentry/integrations/github_enterprise/__init__.py
  src/sentry/integrations/gitlab/__init__.py
  src/sentry/integrations/jira_server/__init__.py
  src/sentry/integrations/msteams/__init__.py
  src/sentry/integrations/slack/__init__.py
  src/sentry/integrations/vercel/__init__.py
  src/sentry/integrations/vsts/__init__.py
  src/sentry/integrations/vsts_extension/__init__.py
  src/sentry/plugins/providers/dummy/__init__.py
  src/sentry/receivers/__init__.py
  src/sentry/utils/imports.py
Labels: backend

#35272 fix(discover): Handle unicode values in parameters
  src/sentry/search/events/fields.py
  tests/sentry/snuba/test_discover_query.py
  tests/snuba/api/endpoints/test_organization_events_v2.py
Labels: backend

#35610 feat(mep): Implement get_snql_query
  src/sentry/search/events/builder.py
  tests/sentry/search/events/test_builder.py
Labels: backend

#35649 feat(perf): Add analytics events for vital detail and trace view
  static/app/utils/analytics/performanceAnalyticsEvents.tsx
  static/app/views/performance/traceDetails/content.tsx
  static/app/views/performance/traceDetails/transactionDetail.tsx
  static/app/views/performance/vitalDetail/vitalDetailContent.tsx
Labels: frontend

#35628 feat(perf): Add analytics for Event Details interactions
  static/app/components/events/interfaces/spans/filter.tsx
  static/app/components/events/interfaces/spans/index.tsx
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/utils/analytics/performanceAnalyticsEvents.tsx
  static/app/views/eventsV2/eventDetails/content.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/content.tsx
Labels: frontend

#35635 feat(dashboard): Split column and yaxis change handlers
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/releaseColumnFields.tsx
  static/app/views/dashboardsV2/widgetBuilder/widgetBuilder.tsx
Labels: frontend

#35597 feat(workflow): Add alert badge indicator to email triggers
  src/sentry/static/sentry/images/email/alert-badge-critical.png
  src/sentry/static/sentry/images/email/alert-badge-resolved.png
  src/sentry/static/sentry/images/email/alert-badge-warning.png
  src/sentry/templates/sentry/emails/email-styles.html
  src/sentry/templates/sentry/emails/incidents/trigger.html
Labels: backend

#35679 feat(replays): Fix dark mode for URL + crumbs header
  static/app/components/replays/replayCurrentUrl.tsx
  static/app/views/replays/detail/userActionsNavigator.tsx
Labels: frontend

#35690 fix(mep): Choose primary dataset when theres no having/orderby
  src/sentry/search/events/builder.py
  tests/sentry/search/events/test_builder.py
Labels: backend

#35688 fix: Fix permission_denied() got an unexpected keyword argument 'code'
  src/sentry/api/endpoints/project_processingissues.py
Labels: backend

#35699 ref(dx): Update dev-tooling channel name
  .github/workflows/label-pullrequest.yml
  scripts/lib.sh
  scripts/pyenv_setup.sh
Labels: backend

#35626 feat(team-roles): Add roleLists to DetailedOrganization (BE)
  src/sentry/api/serializers/models/organization.py
  tests/sentry/api/serializers/test_organization.py
Labels: backend

#35646 ref(replays): Change `useDiscoverQuery` to accept a generic
  static/app/utils/replays/hooks/useDiscoveryQuery.tsx
Labels: frontend

#34695 feat(api): Remove `dsn_requests` from initial client config
  src/sentry/web/client_config.py
  static/app/types/system.tsx
Labels: Status: In Progress, Status: Backlog

#35611 feat(mep): Use snql to create metric alerts
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/snuba/tasks.py
  tests/sentry/api/serializers/test_organization.py
  tests/sentry/snuba/test_tasks.py
Labels: backend

#35693 feat(search): Replace hotkeys labels with icons in search quick actions menu on mobile
  static/app/components/smartSearchBar/searchDropdown.tsx
  static/app/components/smartSearchBar/types.tsx
  static/app/components/smartSearchBar/utils.tsx
Labels: frontend

#35714 test(acceptance): Fix flake in issue comment acceptance test
  fixtures/page_objects/issue_details.py
  tests/acceptance/test_issue_details_workflow.py
Labels: backend

#35391 feat(team-roles) Changes to OrgMembers API response (BE)
  src/sentry/api/serializers/models/organization.py
  src/sentry/api/serializers/models/organization_member/base.py
  src/sentry/api/serializers/models/organization_member/expand/roles.py
  src/sentry/api/serializers/models/organization_member/response.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_organization_invite_request_details.py
  tests/sentry/api/endpoints/test_organization_member_details.py
Labels: backend

#35663 feat(mep): Use snql to validate query in metric alerts api
  src/sentry/incidents/serializers/alert_rule.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/snuba/tasks.py
  tests/sentry/incidents/endpoints/test_serializers.py
  tests/sentry/snuba/test_entity_subscriptions.py
  tests/sentry/snuba/test_tasks.py
Labels: backend

#35650 feat(team-roles) Changes to OrgMembers API response (FE)
  static/app/components/modals/inviteMembersModal/index.tsx
  static/app/components/modals/inviteMembersModal/inviteRowControl.tsx
  static/app/constants/index.tsx
  static/app/types/organization.tsx
  static/app/views/settings/organizationMembers/components/membersFilter.tsx
  static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
  static/app/views/settings/organizationMembers/inviteRequestRow.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.tsx
Labels: frontend

#35593 feat(api): Create endpoint to retrieve a list of commits for a project
  src/sentry/api/endpoints/project_commits.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_project_commits.py
Labels: backend

#35720 test(ui): Convert IdBadge to RTL
  static/app/components/idBadge/teamBadge/badge.tsx
  tests/js/spec/components/idBadge/index.spec.jsx
Labels: frontend

#35715 ref(ts): Update documentation in useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35716 ref(js): Remove unnecessary `renderBody` from useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35717 ref(js): Use `some` over `find` in useApiRequests where appropriate
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35662 feat(search): Better invalid field state
  static/app/components/smartSearchBar/index.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
  tests/js/spec/components/smartSearchBar/index.spec.jsx
  tests/js/spec/views/dashboardsV2/widgetBuilder/widgetBuilder.spec.tsx
Labels: frontend

#35718 fix(search): Fix moving to previous token not working without trailing space
  static/app/components/smartSearchBar/index.tsx
Labels: frontend

#35719 ref(js): Extract `renderLoading` in useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35721 ref(search): Rename quick actions to shortcuts
  static/app/components/smartSearchBar/index.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
  static/app/components/smartSearchBar/searchHotkeysListener.tsx
  static/app/components/smartSearchBar/types.tsx
  static/app/components/smartSearchBar/utils.tsx
  tests/js/spec/components/smartSearchBar/index.spec.jsx
Labels: frontend

#35724 ref(js): Memoize initialState in useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35726 ref(js): Inline `shouldRenderLoading` in useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35738 fix(profiling): memo options object
  static/app/components/profiling/flamegraphOptionsMenu.tsx
Labels: frontend

#35737 fix(framestack): handling of ghost row
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
Labels: frontend

#35734 ref(js): Avoid redefining renderComponent every render
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35733 ref(js): Convert TimeSince to a FC
  static/app/components/timeSince.tsx
  tests/js/spec/components/timeSince.spec.tsx
Labels: frontend

#35725 test(ui): Convert ProjectBadge to RTL
  tests/js/spec/components/idBadge/projectBadge.spec.jsx
Labels: frontend

#35732 chore: pin exam
  requirements-dev-only-frozen.txt
  requirements-dev.txt
Labels: backend

#35730 test(ui): Convert Numberfield to RTL
  tests/js/spec/components/deprecatedforms/numberField.spec.jsx
Labels: frontend

#35731 test(ui): Convert baseChart to RTL
  tests/js/spec/components/charts/baseChart.spec.tsx
Labels: frontend

#35700 fix(performance): Hide MEP dropdown when transaction search is enabled
  static/app/views/performance/landing/index.tsx
Labels: frontend

#35703 fix(ui): Autofocus input in select with clear button
  static/app/components/forms/compactSelect.tsx
Labels: frontend

#35722 test(ui): Convert BaseBadge, UserBadge to RTL
  tests/js/spec/components/idBadge/baseBadge.spec.jsx
  tests/js/spec/components/idBadge/organizationBadge.spec.jsx
  tests/js/spec/components/idBadge/userBadge.spec.jsx
Labels: frontend

#35712 fix(ui): issues search changed negate to exclude
  static/app/components/smartSearchBar/utils.tsx
Labels: frontend

#35696 feat(profiling): add analytics event keys
  static/app/utils/analytics/profilingAnalyticsEvents.tsx
  static/app/utils/analytics/trackAdvancedAnalyticsEvent.tsx
Labels: frontend

#35729 test(ui): Convert FormField to RTL
  tests/js/spec/components/deprecatedforms/formField.spec.jsx
Labels: frontend

#35642 feat(workflow): Shrink yAxis for metric alert chartcuterie
  static/app/chartcuterie/metricAlert.tsx
Labels: frontend

#35687 ref: improve error messages for testutils base classes
  src/sentry/testutils/cases.py
  tests/sentry/api/bases/test_integration.py
  tests/sentry/api/endpoints/test_organization_code_mapping_details.py
  tests/sentry/api/endpoints/test_sentry_app_avatar.py
  tests/sentry/integrations/github/test_repository.py
  tests/sentry/ratelimits/utils/test_enforce_rate_limit.py
  tests/sentry_plugins/bitbucket/test_repository_provider.py
  tests/sentry_plugins/github/test_provider.py
Labels: backend

#35705 perf(api): Load events without stacktrace for the group events endpoint
  src/sentry/api/endpoints/group_events.py
Labels: backend

#35526 feat(discover): adds docs on eventsv2 to events api change
  src/sentry/api/endpoints/organization_events.py
Labels: backend

#35665 feat(alerts): Consolidate metric alert discover queries
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/details/relatedIssues.tsx
  static/app/views/alerts/rules/metric/details/relatedTransactions.tsx
  static/app/views/alerts/rules/metric/metricRulePresets.tsx
  static/app/views/alerts/utils/getMetricRuleDiscoverUrl.tsx
  tests/js/spec/views/alerts/utils/getMetricRuleDiscoverUrl.spec.tsx
Labels: frontend

#35753 fix: only set SENTRY_USE_RELAY to True for devserver iff --ingest is passed
  src/sentry/runner/commands/devserver.py
Labels: backend

#35752 fix(perf): Remove all references to user modified query
  static/app/actionCreators/events.tsx
  static/app/components/charts/eventsChart.tsx
  static/app/components/charts/eventsRequest.tsx
  static/app/utils/discover/genericDiscoverQuery.tsx
  static/app/views/eventsV2/index.tsx
  static/app/views/eventsV2/results.tsx
  static/app/views/eventsV2/table/index.tsx
  static/app/views/performance/content.tsx
  static/app/views/performance/index.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/singleFieldAreaWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/durationChart/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/trendChart/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/vitalsChart/index.tsx
  static/app/views/performance/transactionSummary/transactionSpans/content.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/spanDetailsControls.tsx
  static/app/views/performance/vitalDetail/vitalChart.tsx
  static/app/views/performance/vitalDetail/vitalDetailContent.tsx
  tests/js/spec/views/eventsV2/results.spec.jsx
  tests/js/spec/views/performance/transactionSummary.spec.tsx
  tests/js/spec/views/performance/vitalDetail/index.spec.tsx
Labels: frontend

#35624 ref(dashboards): Add getTableRequest in config
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboardsV2/datasetConfig/base.tsx
  static/app/views/dashboardsV2/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboardsV2/datasetConfig/issues.tsx
  static/app/views/dashboardsV2/datasetConfig/releases.tsx
  static/app/views/dashboardsV2/utils.tsx
  static/app/views/dashboardsV2/widgetCard/issueWidgetQueries.tsx
  static/app/views/dashboardsV2/widgetCard/releaseWidgetQueries.tsx
  static/app/views/dashboardsV2/widgetCard/widgetQueries.tsx
  tests/js/spec/components/modals/widgetViewerModal.spec.tsx
  tests/js/spec/views/dashboardsV2/releaseWidgetQueries.spec.tsx
  tests/js/spec/views/dashboardsV2/widgetQueries.spec.jsx
Labels: frontend

#35686 fix(performance): fixed performance landing page sort not working for some columns
  static/app/views/performance/table.tsx
Labels: frontend

#35697 feat(discover): Allow custom measurements in events metrics dataset queries
  src/sentry/search/events/constants.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/search/events/fields.py
  tests/sentry/search/events/test_builder.py
Labels: backend

#35698 feat(perf): Remove the no-entry icon on the trace & event details page
  static/app/components/events/interfaces/spans/index.tsx
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/views/performance/traceDetails/transactionDetail.tsx
Labels: frontend

#35748 ref(js): useCallback for handleError in useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35763 style(js): Correctly mark `role` usage as deprecated
  static/app/types/organization.tsx
Labels: frontend

#35764 fix(js): Correctly set `isReloading` in useApiRequests
  static/app/utils/useApiRequests.tsx
Labels: frontend

#35695 ref(span-tree): Remove feature flag logic for autoscrolling
  static/app/components/events/interfaces/spans/spanBar.tsx
Labels: frontend

#35758 ref(selectOption): Remove selectComponents.Option wrapper
  static/app/components/forms/selectOption.tsx
  tests/js/spec/views/eventsV2/results.spec.jsx
  tests/js/spec/views/issueList/actions.spec.jsx
  tests/js/spec/views/issueList/overview.spec.jsx
Labels: frontend
