Repository getsentry/sentry, pull requests merged in 2022-10, with the labels that each got.

#39506 fix(gpu-context): Properly insert known data types for gpu context
  static/app/components/events/contexts/gpu/index.tsx
Labels: Scope: Frontend

#39412 feat(metrics): Add `team_key_transaction` to metrics layer [TET-325 TET-426]
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/fields/snql.py
  src/sentry/snuba/metrics/naming_layer/mapping.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/metrics/query_builder.py
  src/sentry/snuba/metrics/utils.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_query.py
  tests/sentry/snuba/metrics/test_query_builder.py
Labels: Scope: Backend

#39535 feat(metrics): Allow `team_key_transaction` to be used as a condition [TET-427 TET-325]
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/metrics/query_builder.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_query_builder.py
Labels: Scope: Backend

#39542 feat(profiling): switch give feedback for join discord btn
  static/app/views/profiling/content.tsx
Labels: Scope: Frontend

#39537 fix: Remove unncessary truthy check for AsyncComponent
  static/app/components/asyncComponent.tsx
Labels: Scope: Frontend

#39503 Add Java SDK to supported SDKs for DS
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
  tests/sentry/api/endpoints/test_organization_dynamic_sampling_sdk_versions.py
Labels: Scope: Backend

#39549 fix(discover): Pagination on discover table
  static/app/views/eventsV2/results.tsx
  static/app/views/eventsV2/table/index.tsx
Labels: Scope: Frontend

#39511 feat(replays): move new event replay to breadcrumbs section
  fixtures/js-stubs/replayReaderParams.js
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventEntry.tsx
  static/app/components/events/eventReplay/replayContent.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/index.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#39488 feat(replays): Fetch error title when querying for issues related to a replay
  src/sentry/replays/endpoints/organization_replay_events_meta.py
  tests/replays/endpoints/test_organization_replay_events_meta.py
Labels: Scope: Backend

#39555 fix(ui): Remove overflow scroll on diff modal (it already has it)
  static/app/components/modals/diffModal.tsx
Labels: Scope: Frontend

#39220 ref(js): Remove UNSAFE_componentWillReceiveProps from tagFilter
  static/app/views/issueList/tagFilter.tsx
Labels: Scope: Frontend

#39560 Add `replays.delete_replay` queue
  src/sentry/conf/server.py
Labels: Scope: Backend

#39515 fix(project-selector): Fix 'Select All Projects' behavior [UP-173]
  static/app/components/organizations/projectSelector/index.tsx
  static/app/components/organizations/projectSelector/projectSelector.spec.jsx
Labels: Scope: Frontend

#39483 ref(ui): Make stack trace tooltip generic for more issue types
  static/app/components/eventOrGroupHeader.spec.tsx
  static/app/components/eventOrGroupTitle.tsx
  static/app/components/groupPreviewTooltip/index.tsx
  static/app/components/groupPreviewTooltip/stackTracePreview.spec.tsx
  static/app/components/groupPreviewTooltip/stackTracePreview.tsx
  static/app/views/projectDetail/projectIssues.spec.jsx
Labels: Scope: Frontend

#39565 ref(ui): Don't export SettingsIconLink from HeaderItem
  static/app/components/organizations/headerItem.tsx
  static/app/views/organizationStats/usageTable/index.tsx
Labels: Scope: Frontend

#39564 feat(Replays): Make replays kafka publisher a global
  src/sentry/replays/tasks.py
Labels: Scope: Backend

#39563 ref(perf): Add full-projects function to EventView
  static/app/utils/discover/eventView.tsx
Labels: Scope: Frontend

#39489 fix(replay): Use the issue title when rendering Error breadcrumbs inside Replay Details
  static/app/utils/replays/replayDataUtils.tsx
  static/app/views/replays/types.tsx
Labels: Scope: Frontend

#39520 chore(replays): put replay deletions on their own celery queue
  src/sentry/replays/tasks.py
Labels: Scope: Backend

#39574 fix(issues): Remove padding from checkmark icon
  static/app/components/group/suggestedOwners/suggestedAssignees.tsx
Labels: Scope: Frontend

#39525 chore(replays): add replay deletion to sampled tasks
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#39139 feat(indexer): Allow mechanism to skip indexing tag values
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/sentry_metrics/consumers/indexer/processing.py
  tests/sentry/sentry_metrics/test_batch.py
  tests/sentry/sentry_metrics/test_parallel_indexer.py
Labels: Scope: Backend

#39582 ref(js): Pass organization into PageFilterPinButton
  static/app/components/organizations/environmentSelector.tsx
  static/app/components/organizations/pageFilters/pageFilterPinButton.tsx
  static/app/components/organizations/projectSelector/index.tsx
  static/app/components/organizations/timeRangeSelector/index.tsx
Labels: Scope: Frontend

#39578 ref(js): Remove old GSH code from EnvironmentSelector
  static/app/components/environmentPageFilter.tsx
  static/app/components/organizations/environmentSelector.spec.tsx
  static/app/components/organizations/environmentSelector.tsx
Labels: Scope: Frontend

#39588 ref(web): Remove bases/react indirection
  src/sentry/templates/sentry/bases/react.html
  src/sentry/web/frontend/react_page.py
  tests/sentry/web/frontend/test_react_page.py
Labels: Scope: Backend

#39469 feat(perf-issues): Add red hatch pattern to affected spans in embedded span tree
  static/app/components/events/interfaces/spans/spanBar.tsx
  static/app/components/events/interfaces/spans/spanDescendantGroupBar.tsx
  static/app/components/events/interfaces/spans/spanRectangle.tsx
  static/app/components/events/interfaces/spans/spanRectangleOverlay.tsx
  static/app/components/events/interfaces/spans/spanTree.tsx
  static/app/components/performance/waterfall/constants.tsx
  static/app/components/performance/waterfall/rowBar.tsx
  static/app/components/performance/waterfall/utils.tsx
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/performance/traceDetails/transactionBar.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/spanDetailsTable.tsx
Labels: Scope: Frontend

#39592 fix(issues): Increase header size on resolution modals
  static/app/components/customCommitsResolutionModal.tsx
  static/app/components/customResolutionModal.tsx
Labels: Scope: Frontend

#39577 ref(js): Remove old GSH code from ProjectSelector
  static/app/components/organizations/projectSelector/index.tsx
  static/app/components/organizations/projectSelector/projectSelector.spec.jsx
  static/app/components/projectPageFilter.tsx
Labels: Scope: Frontend

#39534 ref(test): Convert Event ID field to rtl + ts
  static/app/components/forms/field/controlState.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/eventIdField.spec.tsx
Labels: Scope: Frontend

#39548 fix(profiling): remove unsymbolicated frames before rust runtime
  src/sentry/profiles/task.py
Labels: Scope: Backend

#39567 chore(auth): Update login redirect to support customer domains
  src/sentry/utils/auth.py
  src/sentry/utils/http.py
  tests/sentry/utils/test_auth.py
  tests/sentry/utils/test_http.py
  tests/sentry/web/frontend/test_auth_login.py
Labels: Scope: Backend

#39508 ref(sampling): Open uniform rule modal via url - [TET-430]
  static/app/actionCreators/serverSideSampling.tsx
  static/app/routes.tsx
  static/app/utils/useNavigate.spec.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.spec.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/testUtils.tsx
Labels: Scope: Frontend

#39546 feat(metrics): Add ability to specify result meta type [TET-325 TET-439]
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/query_builder.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_query_builder.py
Labels: Scope: Backend

#39510 ref(performance): Add sampling alert Call to action MVP - [TET-430]
  fixtures/js-stubs/outcomes.js
  fixtures/js-stubs/types.tsx
  static/app/main.tsx
  static/app/utils/analytics/samplingAnalyticsEvents.tsx
  static/app/utils/discover/eventView.tsx
  static/app/utils/useOrganizationStats.tsx
  static/app/views/performance/content.spec.jsx
  static/app/views/performance/landing/dynamicSamplingMetricsAccuracyAlert.spec.tsx
  static/app/views/performance/landing/dynamicSamplingMetricsAccuracyAlert.tsx
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/landing/index.tsx
  static/app/views/performance/landing/metricsDataSwitcher.spec.tsx
  static/app/views/settings/project/server-side-sampling/samplingSDKClientRateChangeAlert.spec.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: Scope: Frontend

#39236 feat(metrics): Add metrics consumer for billing [INGEST-1609]
  mypy.ini
  src/sentry/ingest/billing_metrics_consumer.py
  src/sentry/runner/commands/devserver.py
  src/sentry/runner/commands/run.py
  src/sentry/testutils/skips.py
  tests/sentry/ingest/billing_metrics_consumer/test_billing_metrics_consumer_kafka.py
Labels: Scope: Backend

#39454 feat(dynamic-sampling): Add dynamic sampling feature plans and upsell hooks - [TET-390]
  static/app/types/hooks.tsx
  static/app/views/settings/project/navigationConfiguration.tsx
  static/app/views/settings/project/server-side-sampling/index.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
  static/app/views/settings/project/server-side-sampling/testUtils.tsx
  tests/acceptance/test_project_settings_sampling.py
Labels: Scope: Frontend

#39601 ref(sampling): Default suggested sampling option to reduce friction - [TET-430]
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
Labels: Scope: Frontend

#39603 feat(profiling): Bump sentry-sdk for profiling
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/conf/server.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#39607 fix(sampling): Fix performance cta
  static/app/views/performance/landing/dynamicSamplingMetricsAccuracyAlert.tsx
  static/app/views/settings/project/server-side-sampling/index.tsx
Labels: Scope: Frontend

#39583 fix(hybrid): Correct get_local_region type hint
  src/sentry/types/region.py
Labels: Scope: Backend

#39545 feat(discover): Add new route for homepage
  static/app/routes.tsx
  static/app/utils/discover/eventView.tsx
  static/app/utils/discover/urls.spec.jsx
  static/app/utils/discover/urls.tsx
  static/app/views/eventsV2/breadcrumb.tsx
  static/app/views/eventsV2/eventDetails.spec.jsx
  static/app/views/eventsV2/eventDetails/content.tsx
  static/app/views/eventsV2/eventDetails/index.tsx
  static/app/views/eventsV2/eventInputName.tsx
  static/app/views/eventsV2/homepage.spec.tsx
  static/app/views/eventsV2/homepage.tsx
  static/app/views/eventsV2/results.spec.jsx
  static/app/views/eventsV2/results.tsx
  static/app/views/eventsV2/resultsHeader.tsx
  static/app/views/eventsV2/table/index.tsx
  static/app/views/eventsV2/table/tableView.tsx
Labels: Scope: Frontend

#39611 ref(sampling): Remove dynamic sampling advanced check
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
Labels: Scope: Frontend

#39579 feat(issues): Tracks tab changes in issue group details page
  static/app/utils/analytics/issueAnalyticsEvents.tsx
  static/app/views/organizationGroupDetails/header.tsx
Labels: Scope: Frontend

#39521 feat(perf-issue): rerevert and fix post process forwarder handling multiple groups
  src/sentry/event_manager.py
  src/sentry/eventstream/base.py
  src/sentry/eventstream/kafka/backend.py
  src/sentry/eventstream/kafka/postprocessworker.py
  src/sentry/eventstream/kafka/protocol.py
  src/sentry/eventstream/snuba.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/eventstream/kafka/test_consumer.py
  tests/sentry/eventstream/kafka/test_postprocessworker.py
  tests/sentry/eventstream/kafka/test_protocol.py
  tests/sentry/eventstream/test_eventstream.py
Labels: Scope: Backend

#39575 feat(spike protection): add options to ProjectSerializer
  src/sentry/api/endpoints/organization_projects.py
  src/sentry/api/serializers/models/project.py
  src/sentry/models/options/project_option.py
  tests/sentry/api/endpoints/test_organization_projects.py
Labels: Scope: Backend

#39516 feat(replays): Remove query params from UrlWalker urls and give them more space
  static/app/components/replays/walker/splitCrumbs.tsx
Labels: Scope: Frontend

#39604 fix(discover-homepage): Project IDs not saving on update
  src/sentry/discover/endpoints/discover_homepage_query.py
  tests/snuba/api/endpoints/test_discover_homepage_query.py
Labels: Scope: Backend

#39530 feat(replays): Render the Replays Details page header as soon as data is available
  static/app/utils/replays/hooks/useReplayData.tsx
  static/app/views/replays/details.tsx
Labels: Scope: Frontend

#39527 ref(replay): Make `NetworkSpan` be a sub-type of `ReplaySpan`
  static/app/utils/replays/getReplayEvent.tsx
  static/app/utils/replays/replayDataUtils.spec.tsx
  static/app/utils/replays/replayDataUtils.tsx
  static/app/views/replays/detail/network/index.tsx
  static/app/views/replays/detail/network/useNetworkFilters.spec.tsx
  static/app/views/replays/detail/network/useNetworkFilters.tsx
  static/app/views/replays/detail/network/utils.spec.tsx
  static/app/views/replays/detail/network/utils.tsx
  static/app/views/replays/types.tsx
Labels: Scope: Frontend

#39547 feat(profiles): store transactionId on profileGroup
  static/app/utils/profiling/profile/chromeTraceProfile.tsx
  static/app/utils/profiling/profile/importProfile.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#39335 feat(empty-stacktraces): Tag events with stack traces from JS console errors
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/lang/javascript/processor.py
  tests/sentry/lang/javascript/test_processor.py
Labels: Scope: Backend

#39596 fix(issues) fix sorting on the all events tab
  static/app/utils/discover/eventView.tsx
  static/app/views/organizationGroupDetails/allEventsTable.tsx
Labels: Scope: Frontend

#39585 ref(perf-issues): Add metric for extra spans
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#39616 feat(search) refactor smart search to use excludeTags
  static/app/components/events/searchBar.tsx
  static/app/components/smartSearchBar/index.spec.jsx
  static/app/components/smartSearchBar/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/filterResultsStep/issuesSearchBar.tsx
  static/app/views/issueList/filters.tsx
  static/app/views/organizationGroupDetails/groupEvents.tsx
Labels: Scope: Frontend

#39493 ref(monitors): Convert MonitorCheckIns To FC
  static/app/views/monitors/monitorCheckIns.tsx
Labels: Scope: Frontend

#39631 fix(issue-stream): Ensure that custom ingore modal works when full page is selected
  static/app/components/actions/ignore.tsx
Labels: Scope: Frontend

#39589 fix(perf-issues) Add error state and fix filtering on all events tab
  static/app/components/events/searchBar.tsx
  static/app/components/smartSearchBar/index.spec.jsx
  static/app/components/smartSearchBar/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/filterResultsStep/issuesSearchBar.tsx
  static/app/views/issueList/filters.tsx
  static/app/views/organizationGroupDetails/allEventsTable.tsx
  static/app/views/organizationGroupDetails/groupEvents.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
Labels: Scope: Frontend

#39586 fix(js): Set useApiRequests initial isLoading state to true
  static/app/utils/useApiRequests.tsx
Labels: Scope: Frontend

#39637 Revert "feat(empty-stacktraces): Tag events with stack traces from JS console errors"
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/lang/javascript/processor.py
  tests/sentry/lang/javascript/test_processor.py
Labels: Scope: Backend

#39636 Add span grouping metrics
  src/sentry/event_manager.py
  src/sentry/spans/grouping/strategy/config.py
Labels: Scope: Backend

#39551 feat(workflow): Remove active release notification dry run
  src/sentry/analytics/events/__init__.py
  src/sentry/analytics/events/active_release_notification_dry_run.py
  src/sentry/mail/actions.py
  src/sentry/notifications/utils/participants.py
  src/sentry/rules/processor.py
  tests/sentry/rules/test_processor.py
Labels: Scope: Backend

#39094 ref(js): Remove (almost) all of ProjectActions
  static/app/actionCreators/organization.spec.jsx
  static/app/actionCreators/organization.tsx
  static/app/actionCreators/projects.tsx
  static/app/actions/projectActions.tsx
  static/app/components/contextPickerModal.spec.jsx
  static/app/stores/latestContextStore.tsx
  static/app/stores/projectsStatsStore.tsx
  static/app/stores/projectsStore.spec.jsx
  static/app/stores/projectsStore.tsx
  static/app/utils/projects.spec.jsx
  static/app/utils/projects.tsx
  static/app/utils/useProjects.tsx
  static/app/utils/withTeamsForUser.spec.jsx
  static/app/views/organizationContextContainer.spec.jsx
  static/app/views/settings/organizationTeams/teamProjects.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
  static/app/views/settings/projectDebugFiles/index.tsx
  static/app/views/settings/projectDebugFiles/sources/builtInRepositories.tsx
  static/app/views/settings/projectDebugFiles/sources/customRepositories/index.tsx
  static/app/views/settings/projectGeneralSettings.spec.jsx
  static/app/views/settings/projectGeneralSettings.tsx
  static/app/views/settings/projectIssueGrouping/index.tsx
  static/app/views/settings/projectIssueGrouping/upgradeGrouping.tsx
  static/app/views/settings/projectSecurityAndPrivacy/index.tsx
Labels: Scope: Frontend

#39639 fix(issues): Consistent owned-by sizing
  static/app/components/group/assignedTo.tsx
  static/app/components/group/ownedBy.tsx
Labels: Scope: Frontend

#39647 ref(js): Remove classic Context from Note story
  docs-ui/stories/views/note.stories.js
Labels: Scope: Frontend

#39052 chore(auth): Update sentry.identity.oauth2 to support customer domains
  src/sentry/identity/oauth2.py
  src/sentry/integrations/pipeline.py
  src/sentry/utils/http.py
  src/sentry/web/frontend/pipeline_advancer.py
  tests/sentry/identity/test_oauth2.py
  tests/sentry/integrations/slack/test_integration.py
Labels: Scope: Backend

#39648 fix(releases): Increase size of release adoption tooltip
  static/app/views/releases/list/releasesAdoptionChart.tsx
Labels: Scope: Frontend

#39650 ref(js): Improve naming of ProjectsStatsStore listener
  static/app/views/projectsDashboard/projectCard.tsx
Labels: Scope: Frontend

#39612 ref(sampling): Make 'give feedback' button primary - [TET-435]
  static/app/components/featureFeedback/index.tsx
  static/app/views/settings/project/server-side-sampling/samplingFeedback.tsx
Labels: Scope: Frontend

#39662 fix(billing-consumer): Get correct format for prod servers
  src/sentry/ingest/billing_metrics_consumer.py
Labels: Scope: Backend

#39453 feat: Enable DS for PHP SDKs
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
Labels: Scope: Backend

#39665 chore(deps): Upgrade @sentry/* JS SDKs from 7.13.0 to 7.14.1
  package.json
  yarn.lock
Labels: Scope: Frontend

#39666 feat(feature-flag): Add flag for advanced ds cta in performance - [TET-410]
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#39459 feat(profiling): Send compressed payloads to the profiling service
  src/sentry/profiles/utils.py
Labels: Scope: Backend

#39658 fix(profiling): Fix connection leak in vroom connection pool
  src/sentry/api/endpoints/organization_profiling_profiles.py
  src/sentry/api/endpoints/project_profiling_profile.py
  src/sentry/profiles/utils.py
Labels: Scope: Backend

#39671 feat(discover-homepage): PUT responds with serialized query
  src/sentry/discover/endpoints/discover_homepage_query.py
  tests/snuba/api/endpoints/test_discover_homepage_query.py
Labels: Scope: Backend

#39672 fix(profiling): Tune compression params to lower CPU
  src/sentry/profiles/utils.py
Labels: Scope: Backend

#39673 fix(sampling): Removing redundant keys in sampling endpoint
  src/sentry/api/endpoints/project_dynamic_sampling.py
  tests/sentry/api/endpoints/test_project_dynamic_sampling.py
Labels: Scope: Backend

#39669 fix(sampling): remove redundant keys from sampling endpoint
  static/app/types/sampling.tsx
  static/app/views/settings/project/server-side-sampling/testUtils.tsx
Labels: Scope: Frontend

#39613 fix(discover): Added default label for event title and breadcrums in …
  static/app/views/eventsV2/breadcrumb.tsx
  static/app/views/eventsV2/eventDetails.spec.jsx
  static/app/views/eventsV2/eventInputName.tsx
  static/app/views/eventsV2/resultsHeader.tsx
Labels: Scope: Frontend

#39568 feat(analytics): adds event data to stacktrace events
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
  static/app/utils/analytics/integrations/stacktraceLinkAnalyticsEvents.ts
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/utils/events.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
Labels: Scope: Frontend

#39680 feat(issues): Add issue actions v2 feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#39652 ref: switch to declarative metadata
  MANIFEST.in
  scripts/bump-version.sh
  setup.cfg
  setup.py
Labels: Scope: Backend

#39682 ref(tabs): Add `hideBorder` prop
  static/app/components/tabs/tabList.tsx
  static/app/views/organizationGroupDetails/header.tsx
Labels: Scope: Frontend

#39646 feat(suspect-spans): Improve span grouping for Rails and Laravel
  src/sentry/spans/grouping/strategy/base.py
  src/sentry/spans/grouping/strategy/config.py
  tests/sentry/spans/grouping/test_strategy.py
Labels: Scope: Backend

#39681 ref: add stubs for brotli to enforce type checking
  .github/CODEOWNERS
  .github/file-filters.yml
  fixtures/mypy-stubs/brotli.pyi
  mypy.ini
  src/sentry/profiles/utils.py
Labels: Scope: Backend

#39640 chore(ci): Run hybrid cloud silo mode tests as non required tests in CI
  .github/workflows/backend.yml
Labels: Scope: Backend

#39641 feat(replays): Add missing tags to replay record object
  static/app/utils/replays/replayDataUtils.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#39600 feat(replays): Delete replay button
  static/app/components/replays/deleteButton.tsx
  static/app/views/replays/detail/page.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#39656 fix(issues) fix all events issue id linking to performance
  static/app/views/organizationGroupDetails/allEventsTable.tsx
  static/app/views/organizationGroupDetails/groupEvents.spec.jsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.spec.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
Labels: Scope: Frontend

#39691 fix(ui): Fix context content blowout
  static/app/components/events/contextSummary/item.tsx
Labels: Scope: Frontend

#39693 ref(perf-issues): Add metrics for detected/truncated problems
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#39594 ref(perf-issues): Modularize post_process_group (ISP-11)
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#39581 feat(replays): Show seconds in the tooltip when hovering Replay Details header
  docs-ui/stories/components/timeSince.stories.js
  static/app/components/timeSince.tsx
Labels: Scope: Frontend

#39697 perf(replays): add sampling arg to process_recordings tx
  src/sentry/replays/consumers/recording/process_recording.py
Labels: Scope: Backend

#39504 chore(csrf): Restrict emitting Sentry events for only staff or superusers
  src/sentry/web/frontend/csrf_failure.py
Labels: Scope: Backend

#39701 fix(perf-issues): Fix metric name collision
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#39695 ref: use dict instead of OrderedDict since sentry is >python3.6
  fixtures/bitbucket.py
  fixtures/bitbucket_server.py
  src/sentry/api/endpoints/monitor_stats.py
  src/sentry/api/endpoints/project_servicehook_stats.py
  src/sentry/api/validators/monitor.py
  src/sentry/apidocs/spectacular_ports.py
  src/sentry/constants.py
  src/sentry/digests/utils.py
  src/sentry/eventstore/models.py
  src/sentry/integrations/vsts/issues.py
  src/sentry/interfaces/base.py
  src/sentry/models/eventuser.py
  src/sentry/plugins/config.py
  src/sentry/roles/manager.py
  src/sentry/rules/conditions/level.py
  src/sentry/rules/match.py
  src/sentry/runner/commands/tsdb.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/stacktraces/processing.py
  src/sentry/tagstore/snuba/backend.py
  src/sentry/tasks/reports.py
  src/sentry/tasks/unmerge.py
  src/sentry/tsdb/base.py
  src/sentry/utils/snuba.py
  tests/conftest.py
  tests/sentry/test_canonical.py
  tests/sentry/utils/test_safe.py
  tests/snuba/tasks/test_unmerge.py
Labels: Scope: Backend

#39522 feat(perf issues): Frequency based alerts
  src/sentry/rules/conditions/event_frequency.py
  src/sentry/testutils/perfomance_issues/store_transaction.py
  tests/snuba/api/serializers/test_group.py
  tests/snuba/rules/conditions/test_event_frequency.py
  tests/snuba/tagstore/test_tagstore_backend.py
  tests/snuba/tsdb/test_tsdb_backend.py
Labels: Scope: Backend

#39712 ref(ui): Use @emotion/react for `css` in storybook
  docs-ui/stories/components/progressRing.stories.js
Labels: Scope: Frontend

#39649 ref(js): Remove ProjectActions completely
  static/app/actionCreators/navigation.spec.jsx
  static/app/actions/projectActions.tsx
  static/app/components/assigneeSelector.spec.jsx
  static/app/components/environmentPageFilter.spec.tsx
  static/app/components/group/assignedTo.spec.tsx
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingModal.spec.tsx
  static/app/stores/projectsStore.spec.jsx
  static/app/stores/projectsStore.tsx
  static/app/views/alerts/list/header.spec.tsx
  static/app/views/alerts/rules/issue/details/ruleDetails.spec.jsx
  static/app/views/alerts/rules/issue/issueRuleEditor.spec.jsx
  static/app/views/dashboardsV2/create.spec.tsx
  static/app/views/onboarding/components/createProjectsFooter.tsx
  static/app/views/organizationContextContainer.tsx
  static/app/views/organizationGroupDetails/groupActivity.spec.jsx
  static/app/views/projectInstall/createProject.tsx
Labels: Scope: Frontend

#39595 feat(api-gateway): Proxy GET requests
  src/sentry/api/exceptions.py
  src/sentry/api_gateway/__init__.py
  src/sentry/api_gateway/proxy.py
  src/sentry/conf/server.py
  src/sentry/testutils/helpers/api_gateway.py
  tests/sentry/api_gateway/__init__.py
  tests/sentry/api_gateway/test_api_gateway_helpers.py
  tests/sentry/api_gateway/test_proxy.py
Labels: Scope: Backend

#39719 chore(js): Fix ProjectStore -> ProjectsStore
  static/app/actionCreators/project.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/exception.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/http.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/content.spec.tsx
  static/app/components/events/interfaces/frame/frameVariables.spec.tsx
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingModal.spec.tsx
  static/app/utils/useProjects.tsx
  static/app/views/settings/project/server-side-sampling/modals/specificConditionsModal/index.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.tsx
Labels: Scope: Frontend

#39661 ref(sampling): Update affect other projects transactions alert logic - [TET-436]
  static/app/views/settings/project/server-side-sampling/modals/affectOtherProjectsTransactionsAlert.spec.tsx
  static/app/views/settings/project/server-side-sampling/modals/affectOtherProjectsTransactionsAlert.tsx
  static/app/views/settings/project/server-side-sampling/modals/uniformRateModal.tsx
Labels: Scope: Frontend

#39678 fix(sampling): Rename the keys received from dyn sampling response
  static/app/actionCreators/serverSideSampling.tsx
  static/app/types/sampling.tsx
  static/app/views/settings/project/server-side-sampling/samplingBreakdown.spec.tsx
  static/app/views/settings/project/server-side-sampling/samplingBreakdown.tsx
  static/app/views/settings/project/server-side-sampling/serverSideSampling.spec.tsx
  static/app/views/settings/project/server-side-sampling/testUtils.tsx
Labels: Scope: Frontend

#39660 feat(metrics): Standardize tests and fix overall flakiness [TET-437]
  src/sentry/snuba/metrics/naming_layer/mri.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_release_health.py
Labels: Scope: Backend

#39741 fix(sampling): Fix tooltip content overflowing in breakdown chart - [TET-425]
  static/app/views/settings/project/server-side-sampling/samplingBreakdown.tsx
Labels: Scope: Frontend

#39744 feat(sampling): Feature flag for demo purpose - [TET-442]
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#39696 ref(profiling): Set sentry context on process profile task
  src/sentry/profiles/task.py
Labels: Scope: Backend

#39686 feat(discover-homepage): Homepage query without changes shows reset
  static/app/actionCreators/discoverHomepageQueries.tsx
  static/app/views/eventsV2/homepage.spec.tsx
  static/app/views/eventsV2/results.spec.jsx
  static/app/views/eventsV2/resultsHeader.tsx
  static/app/views/eventsV2/savedQuery/index.spec.tsx
  static/app/views/eventsV2/savedQuery/index.tsx
Labels: Scope: Frontend

#39751 fix(profiling): Should set thread id even if it is zero
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
Labels: Scope: Frontend

#39703 feat(mobile-screenshots): Adds an is:screenshot filter
  src/sentry/api/endpoints/event_attachments.py
  tests/sentry/api/endpoints/test_event_attachments.py
Labels: Scope: Backend

#39754 fix(discover): Requesting equations on metrics dataset returns 500
  static/app/views/eventsV2/metricsBaselineContainer.tsx
Labels: Scope: Frontend

#39755 feat(mobile-exp): Add feature flag for mobile screenshot gallery
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#39633 fix(profiling): hide layout overflow
  static/app/components/profiling/profilingFlamechartLayout.tsx
Labels: Scope: Frontend

#39724 fix(profiling): Retry post profile to vroom
  src/sentry/profiles/task.py
  src/sentry/profiles/utils.py
  tests/sentry/profiling/__init__.py
  tests/sentry/profiling/test_utils.py
  tests/sentry/spans/grouping/__init__.py
Labels: Scope: Backend

#39759 feat(profiling): Show file and lineno for all platforms when possible
  static/app/components/profiling/FlamegraphTooltip/defaultTooltip.tsx
  static/app/components/profiling/FlamegraphTooltip/flamegraphTooltip.tsx
  static/app/components/profiling/FlamegraphTooltip/pythonTooltip.tsx
Labels: Scope: Frontend

#39729 perf(replays): fix start_transaction in replays consumer
  src/sentry/replays/consumers/recording/process_recording.py
Labels: Scope: Backend

#39698 fix(discover-homepage): Absolute date resets to 14d
  static/app/views/eventsV2/homepage.spec.tsx
  static/app/views/eventsV2/homepage.tsx
Labels: Scope: Frontend

#39757 feat(rabbitmq): add new post_process queues
  src/sentry/conf/server.py
Labels: Scope: Backend

#39531 test(useTimeout): Add tests for useTimeout and move to app/utils/*
  static/app/utils/useTimeout.spec.tsx
  static/app/utils/useTimeout.tsx
  static/app/views/replays/detail/layout/splitPanel.tsx
Labels: Scope: Frontend

#39764 fix(discover): Handle undefined case for column text
  static/app/utils/discover/fields.tsx
Labels: Scope: Frontend

#39714 ref(Snowflake): Moved use snowflake flag from sentry
  src/sentry/conf/server.py
Labels: Scope: Backend

#39593 test(replays): TransactionReplays tests
  static/app/views/performance/transactionSummary/transactionReplays/index.spec.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#39685 ref(tabs): Infer `onChange` type from `value`/`defaultValue`
  static/app/components/tabs/index.tsx
  static/app/views/organizationGroupDetails/groupDetails.tsx
Labels: Scope: Frontend

#39732 feat(suspect-spans): Add more metrics to span hashing
  src/sentry/event_manager.py
Labels: Scope: Backend

#39517 feat(replays): Show the error message reported by the backend if listpage searches fail
  static/app/utils/replays/fetchReplayList.tsx
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.spec.tsx
  static/app/views/replays/replayTable.tsx
Labels: Scope: Frontend

#39717 feat(perf_issues): Update `_capture_stats` usage to work with different issue types in post_process
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#39690 ref(performance): Use <Tabs /> in landing page
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/landing/index.tsx
Labels: Scope: Frontend

#39614 chore(arroyo): Upgrade to version 1.0.5
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#39762 fix(discover-home-page): Saved name field as an empty string during p…
  src/sentry/discover/endpoints/discover_homepage_query.py
  tests/snuba/api/endpoints/test_discover_homepage_query.py
Labels: Scope: Backend

#39761 feat(perf-issue): update post_process_group to use GroupStates
  src/sentry/eventstream/base.py
  src/sentry/eventstream/kafka/postprocessworker.py
  src/sentry/tasks/post_process.py
  tests/sentry/eventstream/kafka/test_postprocessworker.py
Labels: Scope: Backend

#39765 feat(perf_issues): Make `post_process_group` able to run different steps based on category
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#39723 feat(issues) add ability to filter attachments by event_ids
  src/sentry/api/endpoints/group_attachments.py
  tests/sentry/api/endpoints/test_group_attachments.py
Labels: Scope: Backend

#39758 test(replays): Add test for Tag Panel component
  static/app/views/replays/detail/tagPanel/index.tsx
  static/app/views/replays/detail/tagPanel/tagPanel.spec.tsx
Labels: Scope: Frontend, trigger-getsentry-external

#39726 ref(js): Remove store listener in SelectedGroupStore
  static/app/stores/groupStore.tsx
  static/app/stores/selectedGroupStore.tsx
Labels: Scope: Frontend

#39777 feat(perf-issue): add feature flag for processing transactions in post_process_group
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/options/defaults.py
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#39651 feat(monitors): Add duration to stats endpoint
  src/sentry/api/endpoints/monitor_stats.py
Labels: Scope: Backend

#39783 Add .NET to supported SDKs for DS
  src/sentry/api/endpoints/organization_dynamic_sampling_sdk_versions.py
Labels: Scope: Backend

#39664 docs(kafka-conf): Add warning on reading configs
  src/sentry/conf/server.py
Labels: Scope: Backend

#39742 fix(metrics): Fix flaky test [TET-387]
  tests/sentry/release_health/test_metrics_sessions_v2.py
Labels: Scope: Backend

#39775 feat(mobile-screenshots): Add filter to group attachments
  src/sentry/api/endpoints/group_attachments.py
  tests/sentry/api/endpoints/test_group_attachments.py
Labels: Scope: Backend

#39778 fix(email): Remove Amixr logo
  src/sentry/templates/sentry/emails/error.html
Labels: Scope: Backend

#39772 fix(charts): Handle a case when chart data is undefined
  static/app/components/charts/eventsRequest.tsx
Labels: Scope: Frontend

#39700 feat(perf-issues): Use post-process-errors queue instead of triggers-0
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#39769 feat(suspect-spans): Switch to new span grouping strategy
  src/sentry/event_manager.py
  src/sentry/spans/grouping/strategy/config.py
  tests/sentry/event_manager/test_event_manager.py
Labels: Scope: Backend

#39657 feat(empty-stacktraces): Tag events with stack traces from JS console errors
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/lang/javascript/processor.py
  tests/sentry/lang/javascript/test_processor.py
Labels: Scope: Backend

#39731 fix(feature-flags): Return False instead of errors when checking feature flags
  src/sentry/features/manager.py
  tests/sentry/web/frontend/test_vercel_extension_configuration.py
Labels: Scope: Backend

#39796 feat(perf-issue): differentiate snuba referrer on group_type
  src/sentry/api/endpoints/group_events.py
  src/sentry/snuba/referrer.py
Labels: Scope: Backend

#39767 ref(perf-issues): Merge extended detector code
  src/sentry/testutils/performance_issues/events/n-plus-one-in-django-new-view-truncated-duplicates.json
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#39770 test(quickTrace): Convert QuickTrace tests to use RTL
  static/app/components/quickTrace/index.tsx
  static/app/components/quickTrace/quickTrace.spec.tsx
  static/app/components/quickTrace/styles.tsx
Labels: Scope: Frontend
