Repository getsentry/sentry, pull requests merged in 2023-03, with the labels that each got.

#45220 fix(hybrid-cloud): Fix redirect on org removal for customer domains
  static/app/actionCreators/organizations.tsx
Labels: Scope: Frontend

#45122 ref(profiling): drop feature flags
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/profilingTransactionHovercard.tsx
  static/app/views/profiling/content.tsx
Labels: Scope: Frontend

#45212 fix(profiling): Pagination for suspect functions
  static/app/components/profiling/suspectFunctions/suspectFunctionsTable.tsx
Labels: Scope: Frontend

#45201 fix(profiling): Fall back to default platform on profiling panel
  static/app/views/profiling/landing/profilingSlowestTransactionsPanel.tsx
Labels: Scope: Frontend

#44761 feat(grouping): New SDK specific enhancer rules
  src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt
  tests/sentry/grouping/grouping_inputs/go-pkg-mod.json
  tests/sentry/grouping/grouping_inputs/javascript-polyfills.json
  tests/sentry/grouping/grouping_inputs/javascript-unpkg.json
  tests/sentry/grouping/grouping_inputs/node-low-level-async.json
  tests/sentry/grouping/similarity/snapshots/test_features/test_similarity_extract_grouping_input/go_pkg_mod.pysnap
  tests/sentry/grouping/similarity/snapshots/test_features/test_similarity_extract_grouping_input/javascript_polyfills.pysnap
  tests/sentry/grouping/similarity/snapshots/test_features/test_similarity_extract_grouping_input/javascript_unpkg.pysnap
  tests/sentry/grouping/similarity/snapshots/test_features/test_similarity_extract_grouping_input/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/android_anr.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/connection_error.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/custom_fingerprint.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_sun_java_generated_constructors.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_sun_java_generated_constructors_2.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_sun_java_generated_methods.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/java_chained.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/java_minimal.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_exception_no_in_app.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_xbrowser_sentryui_firefox.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_xbrowser_sentryui_safari.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/laravel.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/laravel_anonymous.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/node_exception_weird.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/node_low_level_async.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/python_grouping_enhancer_away_from_crash.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/python_grouping_enhancer_towards_crash.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/python_http_error.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/react_native.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/similarity@2020_07_23/go_pkg_mod.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/similarity@2020_07_23/javascript_polyfills.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/similarity@2020_07_23/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/similarity@2020_07_23/node_low_level_async.pysnap
Labels: Scope: Backend

#45189 feat(perf): Swap most improved with most regressed as a default widget
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/landing/views/allTransactionsView.tsx
Labels: Scope: Frontend

#45238 ref(sdk): Move idleTimeout back to default
  static/app/bootstrap/initializeSdk.tsx
Labels: Scope: Frontend

#45219 feat(targeting-context): Add parsed ownership rules to API
  src/sentry/api/endpoints/project_ownership.py
  src/sentry/api/serializers/models/projectownership.py
  src/sentry/ownership/grammar.py
  tests/sentry/api/endpoints/test_project_ownership.py
Labels: Scope: Backend

#45240 feat(view-hierarchy): Change feature badge to new
  static/app/components/events/eventViewHierarchy.tsx
Labels: Scope: Frontend

#45223 Zc/break fks migration part 3
  migrations_lockfile.txt
  src/sentry/data_export/models.py
  src/sentry/discover/models.py
  src/sentry/incidents/models.py
  src/sentry/migrations/0365_breaking_more_fks.py
  src/sentry/models/transaction_threshold.py
  src/sentry/tasks/integrations/slack/find_channel_id_for_rule.py
  tests/sentry/db/test_silo_models.py
Labels: Scope: Backend

#45204 chore(typing) Improve types for env()
  src/sentry/conf/server.py
  src/sentry/utils/types.py
Labels: Scope: Backend

#45130 feat(profiling): Add tags on profile summary page
  static/app/views/profiling/profileSummary/index.tsx
Labels: Scope: Frontend

#45167 fix(replay): Fix console formatter handling of literal "%"
  package.json
  static/app/views/replays/detail/console/messageFormatter.spec.tsx
  static/app/views/replays/detail/console/messageFormatter.tsx
  webpack.config.ts
  yarn.lock
Labels: Scope: Frontend

#45075 feat(codecov-v2): Add task to auto enable codecov integration
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/tasks/auto_enable_codecov.py
  tests/sentry/tasks/test_auto_enable_codecov.py
Labels: Scope: Backend

#45221 fix(replays): Make sure props to useReplaysCount() are all memoized
  static/app/components/replays/replayIdCountProvider.tsx
  static/app/views/issueDetails/header.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/replays/detail/issueList.tsx
Labels: Scope: Frontend

#45231 ref: Use @kafka_options decorator for ingest-consumer cli
  src/sentry/runner/commands/run.py
Labels: Scope: Backend

#45230 fix(query-subscriptions-consumer): Revert CLI changes to query subscriptions consumer
  src/sentry/runner/commands/run.py
Labels: Scope: Backend

#45171 ref(billing-metrics-consumer): Refactor CLI
  src/sentry/ingest/billing_metrics_consumer.py
  src/sentry/runner/commands/run.py
Labels: Scope: Backend

#45228 fix(replays): Fix race condition when loading replay errors & attachments
  fixtures/js-stubs/replayReaderParams.js
  static/app/utils/replays/hooks/useReplayData.spec.tsx
  static/app/utils/replays/hooks/useReplayData.tsx
  static/app/utils/replays/replayDataUtils.tsx
  static/app/views/replays/details.tsx
Labels: Scope: Frontend

#45218 feat(issue-platform): Whitelist several profiling issue types
  src/sentry/data/samples/generic-event-profiling.json
  src/sentry/issues/grouptype.py
  src/sentry/issues/occurrence_consumer.py
  src/sentry/tasks/post_process.py
  src/sentry/testutils/helpers/notifications.py
  tests/sentry/api/endpoints/test_issue_occurrence.py
  tests/sentry/api/serializers/test_group_stream.py
  tests/sentry/integrations/slack/test_message_builder.py
  tests/sentry/issues/test_occurrence_consumer.py
  tests/sentry/issues/test_utils.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/models/test_group.py
  tests/sentry/rules/history/test_preview.py
  tests/snuba/api/endpoints/test_group_events.py
  tests/snuba/api/endpoints/test_organization_events.py
  tests/snuba/api/endpoints/test_organization_events_meta.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
  tests/snuba/api/endpoints/test_organization_group_index_stats.py
  tests/snuba/api/serializers/test_group.py
  tests/snuba/search/test_backend.py
  tests/snuba/tagstore/test_tagstore_backend.py
  tests/snuba/tsdb/test_tsdb_backend.py
Labels: Scope: Backend

#45251 feat(query-client): Make refetchOnWindowFocus false by default
  static/app/utils/queryClient.tsx
Labels: Scope: Frontend

#45096 fix(perf): Only show event "Status" meta on backend projects
  static/app/views/discover/table/quickContext/eventContext.tsx
  static/app/views/performance/transactionDetails/eventMetas.tsx
  static/app/views/performance/transactionDetails/styles.tsx
Labels: Scope: Frontend

#45227 feat(crons): Add new `slug` column
  migrations_lockfile.txt
  src/sentry/migrations/0366_add_slug_to_monitors.py
  src/sentry/models/monitor.py
Labels: Scope: Backend

#45205 fix(assignment): Don't autoassign if already manually assigned
  src/sentry/models/projectownership.py
  tests/sentry/models/test_projectownership.py
Labels: Scope: Backend

#45258 feat(monitors): Write new monitor GUIDs to monitor slug
  src/sentry/models/monitor.py
  tests/sentry/models/test_monitor.py
Labels: Scope: Backend

#45214 feat(replays): Show replayId in table columns instead of the PlayIcon button
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/discover/table/tableView.tsx
  static/app/views/issueDetails/groupTagValues.tsx
Labels: Scope: Frontend

#45211 fix(replays): Only show the inline onboarding cta if the org has replays enabled
  static/app/components/events/eventReplay/index.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/index.tsx
  static/app/utils/replays/projectSupportsReplay.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
Labels: Scope: Frontend

#45264 ref: bump migration tests timeout
  .github/workflows/backend.yml
Labels: Scope: Backend

#44697 ref(codeowners): Move handle_owner_assignment to new task
  src/sentry/conf/server.py
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#45176 ref(ingest-profiles): Remove unused consumer args
  src/sentry/profiles/consumers/__init__.py
  src/sentry/runner/commands/run.py
Labels: Scope: Backend

#45270 feat(crons): Migrate guid to slug
  migrations_lockfile.txt
  src/sentry/migrations/0367_migrate_monitor_guid_to_slug.py
Labels: Scope: Backend

#45243 feat(states): new archive icon
  static/app/icons/iconArchive.tsx
  static/app/icons/index.tsx
Labels: Scope: Frontend

#45268 ref(ui): Improve visual callout for invite request modal
  static/app/components/modals/inviteMembersModal/index.spec.jsx
  static/app/components/modals/inviteMembersModal/index.tsx
Labels: Scope: Frontend

#45278 ref(project selector): Select a project if superuser
  static/app/components/organizations/pageFilters/container.spec.jsx
  static/app/components/organizations/pageFilters/container.tsx
Labels: Scope: Frontend

#45257 feat(codecov-v2): Remove request param for new endpoint
  src/sentry/integrations/utils/codecov.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
  tests/sentry/integrations/utils/test_codecov.py
Labels: Scope: Backend

#45280 fix(search): Use consistent border radii
  static/app/components/globalModal/index.tsx
  static/app/components/modals/commandPalette.tsx
  static/app/components/search/list.tsx
  static/app/utils/theme.tsx
Labels: Scope: Frontend

#45276 feat(crons): Remove slug null=True
  migrations_lockfile.txt
  src/sentry/migrations/0368_monitor_remove_slug_nullable.py
  src/sentry/models/monitor.py
  tests/sentry/models/test_monitor.py
Labels: Scope: Backend

#45229 chore(hybrid-cloud): Break UserOption.organization fk
  migrations_lockfile.txt
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/api/endpoints/user_notification_fine_tuning.py
  src/sentry/api/serializers/models/user.py
  src/sentry/api/serializers/models/user_notifications.py
  src/sentry/migrations/0369_break_useroption_org_fk.py
  src/sentry/models/options/user_option.py
  src/sentry/models/organization.py
  src/sentry/models/outbox.py
  src/sentry/models/project.py
  src/sentry/notifications/utils/legacy_mappings.py
  src/sentry/plugins/bases/notify.py
  src/sentry/plugins/helpers.py
  src/sentry/receivers/outbox/region.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_organization_member_details.py
  tests/sentry/api/endpoints/test_project_index.py
  tests/sentry/api/endpoints/test_user_emails.py
  tests/sentry/api/endpoints/test_user_notification_fine_tuning.py
  tests/sentry/db/test_silo_models.py
  tests/sentry/incidents/action_handlers/test_email.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/models/test_organization.py
  tests/sentry/models/test_project.py
  tests/sentry/receivers/test_core.py
  tests/sentry/tasks/test_weekly_reports.py
  tests/sentry/utils/email/test_message_builder.py
  tests/snuba/api/endpoints/test_organization_group_index.py
  tests/snuba/api/endpoints/test_project_group_index.py
Labels: Scope: Backend

#45288 fix(dx): Throw error on failing to drop db in reset-db
  scripts/lib.sh
Labels: Scope: Backend

#45192 feat(crons): Creates/Updates MonitorEnvironment object during check in
  migrations_lockfile.txt
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/api/validators/monitor.py
  src/sentry/deletions/defaults/project.py
  src/sentry/migrations/0370_integrate_monitor_environment.py
  src/sentry/models/monitorcheckin.py
  src/sentry/models/monitorenvironment.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
Labels: Scope: Backend

#45292 feat(crons): Enforce slug unique constraint
  migrations_lockfile.txt
  src/sentry/migrations/0371_monitor_make_org_slug_unique.py
  src/sentry/models/monitor.py
Labels: Scope: Backend

#45269 ref(mypy): Add missing Organization type to organization_monitors
  src/sentry/api/endpoints/organization_monitors.py
Labels: Scope: Backend

#45249 fix(code mappings): Fix enablement checks
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#45079 feat(monitors): Add basic ingestion via Kafka
  src/sentry/conf/server.py
  src/sentry/models/monitorcheckin.py
  src/sentry/monitors/consumers/__init__.py
  src/sentry/monitors/consumers/check_in.py
  src/sentry/runner/commands/devserver.py
  src/sentry/runner/commands/run.py
Labels: Scope: Backend

#45299 hotfix (dyn-sampling): Prevent to generate model negative sample_rates
  src/sentry/dynamic_sampling/models/adjustment_models.py
  tests/sentry/dynamic_sampling/test_adjusments_models.py
Labels: Scope: Backend

#45301 chore(relay): Bump relay version
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#45198 ref(crons): Check-in endpoint now respects date filter
  src/sentry/api/endpoints/monitor_checkins.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
Labels: Scope: Backend

#45293 fix(profiling): wrong UI frames warning
  static/app/components/profiling/flamegraph/flamegraphUIFrames.tsx
Labels: Scope: Frontend

#45311 fix(monitors): Store duration as milliseconds
  src/sentry/monitors/consumers/check_in.py
Labels: Scope: Backend

#45265 fix(profiling): Update transactions profile id provider to use transa…
  static/app/components/profiling/transactionProfileIdProvider.tsx
Labels: Scope: Frontend

#45254 chore(profiling): Give user misery column a suggested width
  static/app/components/profiling/profileEventsTable.tsx
Labels: Scope: Frontend

#45282 fix(profiling): Show full duration of transaction on profile
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/hooks/useSentryEvent.tsx
Labels: Scope: Frontend

#45303 fix(devserver): Remove kafka batching settings from devserver start command
  src/sentry/runner/commands/devserver.py
Labels: Scope: Backend

#45250 chore(profiling): Remove unneeded profiler tag
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#44939 ref(codeowners): Add handle_owner_assignment datadog metrics
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#45296 ref(code mapping): Remove feature flags
  src/sentry/api/endpoints/organization_derive_code_mappings.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/tasks/derive_code_mappings.py
  src/sentry/tasks/post_process.py
  tests/sentry/api/endpoints/test_organization_derive_code_mappings.py
  tests/sentry/tasks/test_derive_code_mappings.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#45291 fix(codecov-v2): Fix issues with new endpoint
  src/sentry/api/endpoints/project_stacktrace_link.py
  src/sentry/integrations/utils/codecov.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
  tests/sentry/integrations/utils/test_codecov.py
Labels: Scope: Backend

#45274 feat(CapMan): More `tenant_ids` for TSDB Queries
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/endpoints/group_stats.py
  src/sentry/api/endpoints/integrations/sentry_apps/interaction.py
  src/sentry/api/endpoints/organization_stats.py
  src/sentry/api/endpoints/project_group_stats.py
  src/sentry/api/endpoints/project_servicehook_stats.py
  src/sentry/api/endpoints/project_stats.py
  src/sentry/api/endpoints/team_stats.py
  src/sentry/api/serializers/models/group_stream.py
  src/sentry/digests/notifications.py
  src/sentry/models/groupsnooze.py
  src/sentry/rules/conditions/event_frequency.py
  src/sentry/tsdb/base.py
  src/sentry/tsdb/dummy.py
  src/sentry/tsdb/inmemory.py
  src/sentry/tsdb/redis.py
  src/sentry/utils/suspect_resolutions/metric_correlation.py
Labels: Scope: Backend

#45271 bug(replays): Use the new `/replays-count/?returnIds=true` query to list replays related to issues
  static/app/views/issueDetails/groupReplays/groupReplays.spec.tsx
  static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx
Labels: Scope: Frontend

#44133 add duration impact to consecutive db alert
  src/sentry/notifications/utils/__init__.py
  src/sentry/templates/sentry/emails/transactions.html
Labels: Scope: Backend

#45281 ref(hc): Remove future annotations in HC service declarations
  src/sentry/services/hybrid_cloud/app/__init__.py
  src/sentry/services/hybrid_cloud/auth/__init__.py
  src/sentry/services/hybrid_cloud/identity/__init__.py
  src/sentry/services/hybrid_cloud/integration/__init__.py
  src/sentry/services/hybrid_cloud/log/__init__.py
  src/sentry/services/hybrid_cloud/lost_password_hash/__init__.py
  src/sentry/services/hybrid_cloud/notifications/__init__.py
  src/sentry/services/hybrid_cloud/organization/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/__init__.py
  src/sentry/services/hybrid_cloud/project_key/__init__.py
  src/sentry/services/hybrid_cloud/tombstone/__init__.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/services/hybrid_cloud/user_option/__init__.py
Labels: Scope: Backend

#45279 feat(crons): Allow lookup via organization level monitor slug
  src/sentry/api/bases/monitor.py
  src/sentry/api/endpoints/organization_monitor_details.py
  src/sentry/api/endpoints/organization_monitor_stats.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
  tests/sentry/api/endpoints/test_organization_monitor_details.py
Labels: Scope: Backend

#45112 feat(profile-issues): Add function evidence section to discover pages
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventEvidence.spec.tsx
  static/app/components/events/eventEvidence.tsx
  static/app/types/event.tsx
  static/app/utils/issueTypeConfig/index.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.spec.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#45003 ref(compactSelect): Add optional grid structure
  package.json
  static/app/components/compactSelect/composite.spec.tsx
  static/app/components/compactSelect/composite.tsx
  static/app/components/compactSelect/control.tsx
  static/app/components/compactSelect/gridList/index.tsx
  static/app/components/compactSelect/gridList/option.tsx
  static/app/components/compactSelect/gridList/section.tsx
  static/app/components/compactSelect/index.spec.tsx
  static/app/components/compactSelect/index.tsx
  static/app/components/compactSelect/list.tsx
  static/app/components/compactSelect/listBox/index.tsx
  static/app/components/compactSelect/listBox/option.tsx
  static/app/components/compactSelect/listBox/section.tsx
  static/app/components/compactSelect/styles.tsx
  yarn.lock
Labels: Scope: Frontend

#45327 feat(segmentedControl): Add optional `icon` prop
  static/app/components/segmentedControl.tsx
Labels: Scope: Frontend

#45307 ref(profiling): align grid background with defaults
  static/app/components/profiling/flamegraph/collapsibleTimeline.tsx
  static/app/components/profiling/flamegraph/flamegraphLayout.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
Labels: Scope: Frontend

#45316 feat(profiling): make keyboard navigation smooth
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/interactions/useViewKeyboardNavigation.tsx
Labels: Scope: Frontend

#45287 ref(profiling): drop details tab
  static/app/components/profiling/profileHeader.tsx
  static/app/components/profiling/profilingBreadcrumbs.spec.tsx
  static/app/components/profiling/profilingBreadcrumbs.tsx
  static/app/routes.tsx
  static/app/utils/profiling/routes.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.spec.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.tsx
  static/app/views/profiling/profileDetails/hooks/useColumnFilters.ts
  static/app/views/profiling/profileDetails/hooks/useFuseSearch.ts
  static/app/views/profiling/profileDetails/hooks/usePageLinks.ts
  static/app/views/profiling/profileDetails/hooks/useQuerystringState.ts
  static/app/views/profiling/profileDetails/hooks/useSortableColumn.ts
  static/app/views/profiling/profileDetails/index.tsx
  static/app/views/profiling/profileDetails/profileDetails.tsx
  static/app/views/profiling/profileDetails/utils.ts
Labels: Scope: Frontend

#45304 ref(profiling): change ds based off sort
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphOptionsMenu.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphViewSelectMenu.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContext.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphQueryParamSync.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/reducers/flamegraphPreferences.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#45123 ref(profiling): drop feature flags from backend
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Frontend, Scope: Backend

#45290 feat(profiling): add txn link
  static/app/components/profiling/flamegraph/flamegraphDrawer/flamegraphDrawer.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/profileDetails.tsx
  static/app/components/profiling/profileHeader.tsx
  static/app/views/profiling/profilesProvider.tsx
Labels: Scope: Frontend

#45331 fix(issue-platform): use time when API was called as detection_time
  src/sentry/api/endpoints/issue_occurrence.py
Labels: Scope: Backend

#45248 ref(compactSelect): Memoize props to improve performance
  static/app/components/compactSelect/gridList/option.tsx
  static/app/components/compactSelect/listBox/option.tsx
  static/app/components/menuListItem.tsx
Labels: Scope: Frontend

#45319 feat(codecov-v2): Use newly added commit_file_url
  src/sentry/integrations/utils/codecov.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
  tests/sentry/integrations/utils/test_codecov.py
Labels: Scope: Backend

#45310 ref: Update to arroyo 2.7.0
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/eventstream/kafka/synchronized.py
  src/sentry/replays/consumers/recording.py
  src/sentry/sentry_metrics/consumers/last_seen_updater.py
Labels: Scope: Backend

#45326 ref(crons): Adjust order of create / feedback buttons
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#45345 ref(replays): Update ReplayPreview component to match filename
  static/app/components/events/eventReplay/replayPreview.tsx
Labels: Scope: Frontend

#45289 feat(analytics): Replace integrations.stacktrace_link_viewed event with route analytics
  static/app/components/events/interfaces/frame/stacktraceLink.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
  static/app/utils/analytics/integrations/stacktraceLinkAnalyticsEvents.ts
  static/app/views/issueDetails/groupDetails.tsx
Labels: Scope: Frontend

#45346 feat(replays): Sort "Session Replays" under Transaction in /stats category dropdown
  static/app/views/organizationStats/usageChart/index.tsx
Labels: Scope: Frontend

#45216 feat(replays): Iterate on copy to prompt users to inspect replays with their browser
  static/app/components/replays/playerDOMAlert.tsx
Labels: Scope: Frontend

#45188 feat(inbound-filters): Add react-hydration-errors filter
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/serializers/models/project.py
  src/sentry/models/options/project_option.py
  src/sentry/projectoptions/defaults.py
  src/sentry/relay/config/__init__.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/MONOLITH.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/REGION.pysnap
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#45300 feat(inbound-filters): Add react hydration errors filter to frontend
  static/app/data/forms/inboundFilters.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
Labels: Scope: Frontend

#45308 feat(onboarding): Add a new wizard footer - [TET-726]
  static/app/utils/analytics/heartbeatAnalyticsEvents.tsx
  static/app/utils/analytics/onboardingAnalyticsEvents.tsx
  static/app/utils/analytics/trackAdvancedAnalyticsEvent.tsx
  static/app/views/onboarding/components/changeRouteModal.tsx
  static/app/views/onboarding/components/footer.tsx
  static/app/views/onboarding/components/heartbeatFooter/index.tsx
  static/app/views/onboarding/components/heartbeatFooter/useHeartbeat.tsx
  static/app/views/onboarding/index.tsx
  static/app/views/onboarding/setupDocs.tsx
  static/app/views/projectInstall/platform.tsx
Labels: Scope: Frontend

#45360 feat(onboarding): Add new footer tests - [TET-726]
  static/app/views/onboarding/components/footer.spec.tsx
  static/app/views/onboarding/components/footer.tsx
Labels: Scope: Frontend

#45364 fix(inbound-filter): Fix react hydration errors message condition
  src/sentry/relay/config/__init__.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/MONOLITH.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/REGION.pysnap
Labels: Scope: Backend

#45368 fix(webhooks): Reset some tags and context for JIRA & GHE
  mypy.ini
  src/sentry/integrations/github/webhook.py
  src/sentry/integrations/github_enterprise/webhook.py
  src/sentry/integrations/jira_server/webhooks.py
  src/sentry/integrations/utils/cleanup.py
Labels: Scope: Backend

#45347 fix(ecosystem): Prevent code mapping suggestion overflow
  static/app/components/events/interfaces/frame/stacktraceLinkModal.tsx
Labels: Scope: Frontend

#45357 feat(issue-platform): include actor when searching issues for evaluating features
  src/sentry/api/endpoints/organization_events_meta.py
  src/sentry/api/endpoints/organization_group_index.py
  src/sentry/api/endpoints/organization_issues_count.py
  src/sentry/api/helpers/group_index/index.py
  src/sentry/issues/search.py
  src/sentry/search/base.py
  src/sentry/search/snuba/backend.py
  src/sentry/search/snuba/executors.py
Labels: Scope: Backend

#45315 ref(perf-issues): lower thresholds for consecutive http
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_consecutive_http_detector.py
Labels: Scope: Backend

#45372 feat(replays): Track analytics for how many people view the 'Set Up Replays' sidebar
  static/app/utils/analytics/replayAnalyticsEvents.tsx
  static/app/utils/replays/hooks/useReplayOnboarding.tsx
Labels: Scope: Frontend

#45253 chore(codecov-v2): Move codecov logic out of stacktrace-link
  src/sentry/api/endpoints/project_stacktrace_link.py
  src/sentry/integrations/utils/codecov.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
Labels: Scope: Backend

#45374 feat(custom_instrumentation): Set tag and span in bind_organization_context
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#45312 feat(view-hierarchy): Add analytics
  static/app/components/events/viewHierarchy/index.tsx
  static/app/components/events/viewHierarchy/renderingSystem.tsx
  static/app/utils/analytics/issueAnalyticsEvents.tsx
Labels: Scope: Frontend

#45354 fix(dx): Update mkcert to generate for *.dev.getsentry.net
  package.json
Labels: Scope: Frontend

#45379 feat(view-hierarchy): Move transaction start
  src/sentry/lang/java/utils.py
Labels: Scope: Backend

#45382 fix(issue-platform): pass through actor to search/query func
  src/sentry/search/snuba/backend.py
  src/sentry/search/snuba/executors.py
Labels: Scope: Backend

#45383 bug(perf-issues): remove unused N+1 Query issue rate UI
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#45380 bug(perf-issues): hook up N+1 Query detection rate again
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_m_n_plus_one_db_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_db_span_detector.py
Labels: Scope: Frontend, Scope: Backend

#45294 feat(crons): Add monitor slug to APIs
  src/sentry/api/endpoints/organization_monitor_details.py
  src/sentry/api/endpoints/organization_monitors.py
  src/sentry/api/serializers/models/monitor.py
  src/sentry/api/validators/monitor.py
  src/sentry/models/monitor.py
  tests/sentry/api/endpoints/test_organization_monitor_details.py
  tests/sentry/api/endpoints/test_organization_monitors.py
Labels: Scope: Backend

#45387 chore(monitors): Add components folder
  static/app/views/monitors/components/checkInIcon.tsx
  static/app/views/monitors/components/cronsFeedbackButton.tsx
  static/app/views/monitors/components/monitorBadge.tsx
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/components/monitorForm.tsx
  static/app/views/monitors/components/monitorHeader.tsx
  static/app/views/monitors/components/monitorHeaderActions.tsx
  static/app/views/monitors/components/monitorIcon.tsx
  static/app/views/monitors/components/monitorIssues.tsx
  static/app/views/monitors/components/monitorStats.tsx
  static/app/views/monitors/components/onboarding.tsx
  static/app/views/monitors/create.tsx
  static/app/views/monitors/details.tsx
  static/app/views/monitors/edit.tsx
  static/app/views/monitors/monitors.tsx
  static/app/views/monitors/row.tsx
Labels: Scope: Frontend

#45352 fix(profiling): remove tooltip
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphViewSelectMenu.tsx
Labels: Scope: Frontend

#45324 feat(perf-issues: ignore non-http between http spans consecutive http
  src/sentry/utils/performance_issues/detectors/consecutive_http_detector.py
  tests/sentry/utils/performance_issues/test_consecutive_http_detector.py
Labels: Scope: Backend

#45388 fix: Remove process_owner_assignments task
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#45392 fix(monitors): Reverts MonitorEnvironment
  src/sentry/api/endpoints/monitor_checkins.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
  tests/sentry/models/test_monitorenvironment.py
Labels: Scope: Backend

#45375 feat(profile-issues): Add new profile issue types to frontend
  static/app/components/events/profileEventEvidence.spec.tsx
  static/app/stores/tagStore.tsx
  static/app/types/group.tsx
  static/app/utils/issueTypeConfig/profileConfig.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.spec.tsx
Labels: Scope: Frontend

#45385 ref(crons): Remove unnecessary auth check
  src/sentry/api/bases/monitor.py
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/api/endpoints/organization_monitor_details.py
Labels: Scope: Backend

#45399 feat(ui): Allow event timestamp tooltip to be hovered
  static/app/views/issueDetails/eventToolbar.tsx
Labels: Scope: Frontend

#45391 ref(js): Convert CreateMonitor to a FC
  static/app/views/monitors/create.tsx
Labels: Scope: Frontend

#45330 ref: Update MockApiClient to have an asyncDelay flag, so test run with timers
  static/app/__mocks__/api.tsx
  static/app/stores/groupingStore.spec.jsx
  static/app/utils/replays/hooks/useReplayData.spec.tsx
Labels: Scope: Frontend

#45403 feat(replays): Show a page title on the Replay List page
  static/app/components/sentryDocumentTitle.tsx
  static/app/views/replays/detail/page.tsx
  static/app/views/replays/details.tsx
  static/app/views/replays/list/container.tsx
Labels: Scope: Frontend

#45349 feat(codecov-v2): Add AuditLogEntry when auto enabling Codecov
  src/sentry/tasks/auto_enable_codecov.py
  tests/sentry/tasks/test_auto_enable_codecov.py
Labels: Scope: Backend

#45414 ref(onboarding): Add 'are you sure?' dialog to skip onboarding - [TET-734]
  static/app/views/onboarding/components/changeRouteModal.tsx
  static/app/views/onboarding/components/footer.spec.tsx
  static/app/views/onboarding/components/footer.tsx
Labels: Scope: Frontend

#45215 feat(anr): Store thread state on event json
  src/sentry/interfaces/threads.py
  tests/sentry/event_manager/interfaces/snapshots/test_threads/test_basics.pysnap
Labels: Scope: Backend

#45124 ref(relay): Stop sending unnecessary fields in project config
  src/sentry/datascrubbing.py
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/rules/biases/boost_environments_bias.py
  src/sentry/dynamic_sampling/rules/biases/boost_key_transactions_bias.py
  src/sentry/dynamic_sampling/rules/biases/boost_latest_releases_bias.py
  src/sentry/dynamic_sampling/rules/biases/ignore_health_checks_bias.py
  src/sentry/dynamic_sampling/rules/biases/uniform_bias.py
  src/sentry/dynamic_sampling/rules/utils.py
  src/sentry/relay/config/__init__.py
  tests/sentry/api/endpoints/test_relay_projectconfigs.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v2.py
  tests/sentry/dynamic_sampling/rules/biases/test_boost_environments_bias.py
  tests/sentry/dynamic_sampling/rules/biases/test_boost_key_transactions_bias.py
  tests/sentry/dynamic_sampling/rules/biases/test_boost_latest_releases_bias.py
  tests/sentry/dynamic_sampling/rules/biases/test_ignore_health_checks_bias.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
  tests/sentry/dynamic_sampling/test_logging.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/MONOLITH.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/REGION.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/slim_config/MONOLITH.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/slim_config/REGION.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/MONOLITH/False/False.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/MONOLITH/False/True.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/MONOLITH/True/False.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/MONOLITH/True/True.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/REGION/False/False.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/REGION/False/True.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/REGION/True/False.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_satisfaction_thresholds/REGION/True/True.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_with_breakdown/MONOLITH/with_metrics.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_with_breakdown/REGION/with_metrics.pysnap
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#45415 ref(onboarding): Update silent project deletion logic - [TET-739]
  static/app/views/onboarding/components/footer.spec.tsx
  static/app/views/onboarding/components/footer.tsx
  static/app/views/onboarding/index.tsx
Labels: Scope: Frontend

#45318 chore(profiling): Bump sentry-sdk to 1.16.0
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#45325 chore(profiling): Remove x axis preference from flamegraph
  static/app/components/events/interfaces/spans/gapSpanDetails.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphContextMenu.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphOptionsMenu.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContext.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphQueryParamSync.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/reducers/flamegraphPreferences.tsx
Labels: Scope: Frontend

#45329 fix(domains) Improve devserver workflow with customer-domains
  src/sentry/options/defaults.py
  src/sentry/runner/commands/devserver.py
Labels: Scope: Backend

#45398 ref(profiling): Add optional request header for profiling
  src/sentry/web/frontend/react_page.py
Labels: Scope: Backend

#45371 feat(anr): Display thread state in thread selector
  fixtures/js-stubs/entries.js
  static/app/components/events/interfaces/threads/index.spec.tsx
  static/app/components/events/interfaces/threads/threadSelector/filterThreadInfo.tsx
  static/app/components/events/interfaces/threads/threadSelector/header.tsx
  static/app/components/events/interfaces/threads/threadSelector/index.tsx
  static/app/components/events/interfaces/threads/threadSelector/option.tsx
  static/app/components/events/interfaces/threads/threadSelector/selectedOption.tsx
  static/app/components/events/interfaces/threads/threadSelector/styles.tsx
  static/app/types/event.tsx
Labels: Scope: Frontend, Scope: Backend

#45366 feat(profiling): add browser profiling to dev-ui
  package.json
  static/app/bootstrap/commonInitialization.tsx
  static/app/bootstrap/initializeSdk.tsx
  static/app/constants/index.tsx
  static/app/types/system.tsx
  webpack.config.ts
  yarn.lock
Labels: Scope: Frontend

#45418 fix(dynamic-sampling): Handle 0.0 sample rate for dynamic factor function
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/rules/utils.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
  tests/sentry/dynamic_sampling/test_utils.py
Labels: Scope: Backend

#45233 feat(crons): Allow recent check-ins to be paginated
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#45422 ref: make sentry.testutils.silo more typing-compatible
  src/sentry/testutils/silo.py
Labels: Scope: Backend

#45423 feat(grouping): Add more js cdn rules
  src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt
  tests/sentry/grouping/grouping_inputs/javascript-unpkg.json
  tests/sentry/grouping/similarity/snapshots/test_features/test_similarity_extract_grouping_input/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_unpkg.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/similarity@2020_07_23/javascript_unpkg.pysnap
Labels: Scope: Backend

#45421 feat(profiling): enable browser profiling for dev-ui
  package.json
  static/app/bootstrap/commonInitialization.tsx
  static/app/bootstrap/initializeSdk.tsx
  static/app/constants/index.tsx
  static/app/types/system.tsx
  webpack.config.ts
  yarn.lock
Labels: Scope: Frontend

#45424 ref: gettext things return a str Promise
  src/sentry/auth/helper.py
Labels: Scope: Backend

#45400 ref(replays): Remove the session-replay-ui flag in FE code
  static/app/components/eventOrGroupExtraDetails.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumbs.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/index.tsx
  static/app/components/replays/issuesReplayCountProvider.tsx
  static/app/components/sidebar/index.tsx
  static/app/views/discover/results.tsx
  static/app/views/issueDetails/allEventsTable.tsx
  static/app/views/issueDetails/eventToolbar.tsx
  static/app/views/issueDetails/groupReplays/groupReplays.spec.tsx
  static/app/views/issueDetails/groupReplays/index.tsx
  static/app/views/issueDetails/header.tsx
  static/app/views/organizationStats/index.tsx
  static/app/views/performance/transactionDetails/eventMetas.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
  static/app/views/performance/transactionSummary/transactionReplays/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionReplays/index.tsx
  static/app/views/replays/index.tsx
Labels: Scope: Frontend

#45407 feat(codecov-v2): Add flag to restrict by plan
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#45425 ref: retrieve session value using getitem instead of get
  src/sentry/auth/helper.py
Labels: Scope: Backend

#45420 fix(profiling): always render the separator
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/utils/profiling/renderers/gridRenderer.tsx
Labels: Scope: Frontend

#45426 chore(profiling): Add feature flag for profiling span previews
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#45389 feat(trace): Add measurements to the trace view
  static/app/components/events/interfaces/spans/header.tsx
  static/app/components/events/interfaces/spans/measurementsPanel.tsx
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/views/performance/traceDetails/traceView.tsx
  static/app/views/performance/traceDetails/transactionBar.tsx
  static/app/views/performance/traceDetails/transactionGroup.tsx
Labels: Scope: Frontend

#45402 ref(crons): Prefer usage of monitor.slug in the frontend
  static/app/actionCreators/monitors.tsx
  static/app/routes.tsx
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/components/monitorForm.tsx
  static/app/views/monitors/components/monitorHeader.tsx
  static/app/views/monitors/components/monitorHeaderActions.tsx
  static/app/views/monitors/components/monitorStats.tsx
  static/app/views/monitors/create.tsx
  static/app/views/monitors/details.tsx
  static/app/views/monitors/edit.tsx
  static/app/views/monitors/monitors.tsx
  static/app/views/monitors/row.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#45437 fix(growth): Add angular-ivy to known javascript sdks
  static/app/components/events/interfaces/crashContent/exception/utils.tsx
  static/app/components/events/interfaces/spans/utils.tsx
Labels: Scope: Frontend

#45381 feat(ui) Make loading messages dynamic
  src/sentry/templates/sentry/base-react.html
  src/sentry/templatetags/sentry_helpers.py
Labels: Scope: Backend

#45404 feat(ecosystem): Add new suggestions to owners rule editor
  static/app/components/modals/editOwnershipRulesModal.tsx
  static/app/views/settings/project/projectOwnership/editRulesModal.spec.tsx
  static/app/views/settings/project/projectOwnership/editRulesModal.tsx
Labels: Scope: Frontend

#45428 ref(referrers): Fix usage of tagstore enum
  src/sentry/tagstore/snuba/backend.py
Labels: Scope: Backend

#45401 ref(replays): Remove the session-replay-ui flag in BE code
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/acceptance/test_replay_detail.py
  tests/acceptance/test_replay_list.py
Labels: Scope: Backend

#45438 feat(ui): Switch from copy-text-to-clipboard to navigator
  jest.config.ts
  package.json
  static/app/components/clipboard.tsx
  static/app/components/codeSnippet.tsx
  static/app/views/issueDetails/actions/shareModal.tsx
  static/app/views/settings/organizationRelay/modals/form.tsx
  yarn.lock
Labels: Scope: Frontend

#45131 feat(codecov-v2): Schedule the task to auto enable codecov integration
  src/sentry/conf/server.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#45433 ref(post-process-forwarder): Remove dead code
  src/sentry/eventstream/kafka/state.py
  tests/sentry/eventstream/kafka/test_state.py
Labels: Scope: Backend

#45443 fix(auth): Updated CSRF error msg with extra "/" warning
  src/sentry/templates/sentry/403-csrf-failure.html
Labels: Scope: Backend

#45451 fix(monitors): Adds unique_together for MonitorEnvironment
  migrations_lockfile.txt
  src/sentry/migrations/0372_add_uniquetogether_monitorenvironment.py
  src/sentry/models/monitorenvironment.py
Labels: Scope: Backend

#45453 fix(monitors): Re-enables MonitorEnvironment Creation
  src/sentry/api/endpoints/monitor_checkins.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
  tests/sentry/models/test_monitorenvironment.py
Labels: Scope: Backend

#45463 ref(onboarding): Update copy of 'are you sure' modal - [TET-760]
  static/app/views/onboarding/components/changeRouteModal.tsx
Labels: Scope: Frontend

#45465 fix(sourcemaps): Add project_ids default value
  src/sentry/tasks/assemble.py
Labels: Scope: Backend

#45467 chore: Include all fixtures in eslintignore and move fixtures around
  .eslintignore
  .pre-commit-config.yaml
  src/sentry/lint/engine.py
  tests/relay_integration/lang/javascript/example-project/.gitignore
  tests/relay_integration/lang/javascript/example-project/Makefile
  tests/relay_integration/lang/javascript/example-project/index.html
  tests/relay_integration/lang/javascript/example-project/launch.js
  tests/relay_integration/lang/javascript/example-project/minifiedError.json
  tests/relay_integration/lang/javascript/example-project/package.json
  tests/relay_integration/lang/javascript/fixtures/example/test.js
  tests/relay_integration/lang/javascript/fixtures/example/test.min.js
  tests/relay_integration/lang/javascript/fixtures/example/test.min.js.map
  tests/relay_integration/lang/javascript/test_example.py
Labels: Scope: Frontend, Scope: Backend

#45462 feat(locks): Add redis-cluster compatible locking backend
  src/sentry/utils/locking/backends/redis.py
  tests/sentry/utils/locking/backends/test_redis.py
Labels: Scope: Backend

#45464 ref(sourcemaps): Change distribution field in the ReleaseArtifactBundle table
  migrations_lockfile.txt
  src/sentry/migrations/0373_dist_id_to_name.py
  src/sentry/models/artifactbundle.py
  src/sentry/tasks/assemble.py
Labels: Scope: Backend
