Repository getsentry/sentry, pull requests merged in 2023-05, with the labels that each got.

#48088 fix(hybridcloud) Fix n+1 queries in RPC user serialization
  src/sentry/services/hybrid_cloud/user/impl.py
  tests/sentry/hybrid_cloud/test_user.py
Labels: Scope: Backend

#48114 fix(hybridcloud) Try a smaller tombstone batch size
  src/sentry/tasks/deletion/hybrid_cloud.py
  tests/sentry/tasks/deletion/test_hybrid_cloud.py
Labels: Scope: Backend

#48214 feat(starfish): Add more details to the failure rate panel
  static/app/views/starfish/views/webServiceView/failureDetailPanel/focusedFailureRateChart.tsx
  static/app/views/starfish/views/webServiceView/failureDetailPanel/index.tsx
  static/app/views/starfish/views/webServiceView/failureDetailPanel/issueTable.tsx
  static/app/views/starfish/views/webServiceView/starfishView.tsx
Labels: Scope: Frontend

#48108 feat(starfish): Introduce a way to filter on new and old
  static/app/views/starfish/modules/databaseModule/index.tsx
  static/app/views/starfish/modules/databaseModule/queries.js
Labels: Scope: Frontend

#48205 feat(starfish): Add more sidebar details and highlight sql
  static/app/views/starfish/modules/databaseModule/panel.tsx
  static/app/views/starfish/modules/databaseModule/queries.js
Labels: Scope: Frontend

#48167 feat(exception-group): Move related exceptions out of the stack trace and sort properly
  static/app/components/events/interfaces/crashContent/exception/content.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/content.tsx
  static/app/components/events/interfaces/crashContent/exception/mechanism.tsx
  static/app/components/events/interfaces/crashContent/exception/relatedExceptions.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/relatedExceptions.tsx
  static/app/components/events/interfaces/crashContent/exception/stackTrace.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/stackTrace.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/content.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/hierarchicalGroupingContent.tsx
  static/app/components/events/interfaces/frame/context.tsx
  static/app/components/events/interfaces/frame/deprecatedLine.tsx
  static/app/components/events/interfaces/frame/line/index.tsx
  static/app/components/events/interfaces/frame/utils.tsx
Labels: Scope: Frontend

#48166 feat(format-sql): Format other perf db spans
  src/sentry/api/serializers/models/event.py
Labels: Scope: Backend

#48209 feat(starfish): Adds a details component for external apis in api module
  static/app/views/starfish/modules/APIModule/APIModuleView.tsx
  static/app/views/starfish/modules/APIModule/hostDetails.tsx
  static/app/views/starfish/modules/APIModule/hostTable.tsx
  static/app/views/starfish/modules/APIModule/queries.js
Labels: Scope: Frontend

#48248 fix(hybridcloud) Further optimize avatar queries
  src/sentry/services/hybrid_cloud/user/impl.py
Labels: Scope: Backend

#48183 feat(roles): Team-roles for Alerts Settings page
  static/app/views/alerts/rules/issue/index.spec.jsx
  static/app/views/settings/projectAlerts/index.tsx
  static/app/views/settings/projectAlerts/settings.tsx
Labels: Scope: Frontend

#48184 feat(roles): Team-roles for Project Tags page
  static/app/views/settings/projectTags/index.tsx
Labels: Scope: Frontend

#48185 feat(roles): Team-roles for Manage Environments page
  static/app/views/settings/project/projectEnvironments.tsx
Labels: Scope: Frontend

#48187 feat(roles): Team-roles for Data Forwarding page
  static/app/views/settings/projectDataForwarding/index.tsx
Labels: Scope: Frontend

#48188 feat(roles): Team-roles for Inbound Data Filter page
  static/app/views/settings/project/projectFilters/groupTombstones.tsx
  static/app/views/settings/project/projectFilters/index.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
Labels: Scope: Frontend

#48260 chore(login): update the login banners
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#48199 feat(roles): Team-roles for Team Notifications page
  static/app/views/settings/organizationTeams/teamNotifications.tsx
Labels: Scope: Frontend

#48196 feat(roles): Team-roles for Legacy Integrations page
  static/app/views/settings/projectPlugins/index.tsx
  static/app/views/settings/projectPlugins/projectPluginRow.tsx
  static/app/views/settings/projectPlugins/projectPlugins.tsx
Labels: Scope: Frontend

#48216 fix(query-subscription-consumer): Fix initializing metrics
  src/sentry/snuba/query_subscriptions/run.py
Labels: Scope: Backend

#46960 Breaking more keys
  migrations_lockfile.txt
  src/sentry/admin.py
  src/sentry/api/endpoints/organization_code_mapping_codeowners.py
  src/sentry/api/endpoints/organization_code_mapping_details.py
  src/sentry/api/endpoints/organization_code_mappings.py
  src/sentry/api/endpoints/organization_codeowners_associations.py
  src/sentry/api/endpoints/project_stacktrace_link.py
  src/sentry/api/serializers/models/projectcodeowners.py
  src/sentry/api/serializers/models/repository_project_path_config.py
  src/sentry/api/serializers/rest_framework/notification_action.py
  src/sentry/deletions/defaults/organizationintegration.py
  src/sentry/event_manager.py
  src/sentry/incidents/endpoints/organization_alert_rule_available_action_index.py
  src/sentry/incidents/logic.py
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/pagerduty/actions/form.py
  src/sentry/integrations/pagerduty/actions/notification.py
  src/sentry/integrations/pagerduty/integration.py
  src/sentry/integrations/utils/commit_context.py
  src/sentry/migrations/0431_breaking_orgintegration_pieces_and_default_auth_team_fks.py
  src/sentry/models/authprovider.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/integrations/organization_integration.py
  src/sentry/models/integrations/pagerduty_service.py
  src/sentry/models/integrations/repository_project_path_config.py
  src/sentry/models/outbox.py
  src/sentry/models/team.py
  src/sentry/receivers/outbox/control.py
  src/sentry/services/hybrid_cloud/auth/impl.py
  src/sentry/services/hybrid_cloud/integration/__init__.py
  src/sentry/services/hybrid_cloud/integration/impl.py
  src/sentry/tasks/codeowners/code_owners_auto_sync.py
  src/sentry/tasks/codeowners/update_code_owners_schema.py
  tests/sentry/api/endpoints/notifications/test_notification_actions_details.py
  tests/sentry/api/endpoints/notifications/test_notification_actions_index.py
  tests/sentry/api/endpoints/test_organization_integration_repos.py
  tests/sentry/auth/test_helper.py
  tests/sentry/db/test_silo_models.py
  tests/sentry/deletions/test_repository.py
  tests/sentry/incidents/action_handlers/test_pagerduty.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_available_action_index.py
  tests/sentry/incidents/test_logic.py
  tests/sentry/integrations/github/test_integration.py
  tests/sentry/integrations/pagerduty/test_client.py
  tests/sentry/integrations/pagerduty/test_integration.py
  tests/sentry/integrations/pagerduty/test_notify_action.py
  tests/sentry/migrations/test_0286_backfill_alertrule_organization.py
  tests/sentry/migrations/test_0287_backfill_snubaquery_environment.py
  tests/sentry/migrations/test_0295_backfill_alertrule_type.py
  tests/sentry/migrations/test_0297_backfill_alert_owners.py
  tests/sentry/migrations/test_0301_mep_backfill_and_not_null_snuba_query_type.py
  tests/sentry/migrations/test_0394_set_none_date_uploaded_to_date_added.py
  tests/sentry/migrations/test_0403_backfill_actors.py
  tests/sentry/migrations/test_0404_backfill_user_avatars.py
  tests/sentry/migrations/test_0407_recreate_perf_alert_subscriptions.py
  tests/sentry/migrations/test_0413_backfill_organization_integration_denormalization.py
  tests/sentry/migrations/test_0417_backfill_groupedmessage_substatus.py
  tests/sentry/migrations/test_0420_backfill_groupedmessage_ignored_substatus.py
  tests/sentry/models/test_integration.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#48261 fix(starfish): missing reference to startTime and endTime in functions
  static/app/views/starfish/modules/databaseModule/queries.js
Labels: Scope: Frontend

#47874 feat(hybrid-cloud): OrganizationMemberMapping deletes
  src/sentry/receivers/outbox/region.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/__init__.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/impl.py
  src/sentry/testutils/factories.py
  tests/sentry/api/endpoints/test_accept_organization_invite.py
  tests/sentry/auth/test_helper.py
  tests/sentry/deletions/test_organization.py
  tests/sentry/hybrid_cloud/test_organizationmembermapping.py
Labels: Scope: Backend

#48106 feat(escalating-issues): Add is escalating analytic
  src/sentry/issues/analytics.py
  src/sentry/issues/escalating.py
  tests/sentry/issues/test_escalating.py
Labels: Scope: Backend

#48262 ref(starfish): convert queries.js to .ts for db module
  static/app/views/starfish/modules/databaseModule/index.tsx
  static/app/views/starfish/modules/databaseModule/queries.ts
Labels: Scope: Frontend

#48160 feat(starfish): add db module sorting
  static/app/views/starfish/modules/databaseModule/databaseTableView.tsx
  static/app/views/starfish/modules/databaseModule/index.tsx
  static/app/views/starfish/modules/databaseModule/panel.tsx
  static/app/views/starfish/modules/databaseModule/queries.ts
Labels: Scope: Frontend

#48226 chore(crons): Remove bandaid for backlogged checkins [INC-350]
  src/sentry/conf/server.py
  src/sentry/monitors/tasks.py
  tests/sentry/monitors/test_tasks.py
Labels: Scope: Backend

#48025 chore(hybrid-cloud): Backfill organizationmember_id column in OrganizationMemberMapping
  migrations_lockfile.txt
  src/sentry/migrations/0432_backfill_org_member_id_organizationmembermapping.py
Labels: Scope: Backend

#48198 fix(search): skip timestamp search term when querying for issues and issues-stats
  src/sentry/api/serializers/models/group.py
  src/sentry/search/snuba/executors.py
  tests/snuba/api/endpoints/test_organization_group_index_stats.py
  tests/snuba/api/serializers/test_group.py
  tests/snuba/api/serializers/test_group_stream.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#48048 fix(slack): escape Slack messages to prevent malicious actors from doing things
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/integrations/message_builder.py
  src/sentry/integrations/slack/message_builder/base/base.py
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/integrations/slack/utils/escape.py
  tests/sentry/integrations/slack/test_message_builder.py
Labels: Scope: Backend

#48211 feat(starfish): add tpm graph for top 5 tpm queries in db query details
  static/app/views/starfish/modules/databaseModule/panel.tsx
  static/app/views/starfish/modules/databaseModule/queries.ts
Labels: Scope: Frontend

#47909 feat(issue-states): Replace `unignored` with `ongoing`
  src/sentry/models/grouphistory.py
  src/sentry/models/groupinbox.py
  src/sentry/tasks/clear_expired_snoozes.py
  src/sentry/tasks/post_process.py
  tests/snuba/api/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#48277 ref(crons): Remove unnecessary status update logic
  src/sentry/monitors/endpoints/organization_monitor_details.py
  tests/sentry/monitors/endpoints/test_organization_monitor_details.py
Labels: Scope: Backend

#48098 ref(hc): Use IntegrationProxyClient for slack requests
  src/sentry/api/endpoints/internal/integration_proxy.py
  src/sentry/integrations/slack/actions/notification.py
  src/sentry/integrations/slack/client.py
  src/sentry/integrations/slack/integration.py
  src/sentry/integrations/slack/notifications.py
  src/sentry/integrations/slack/utils/channel.py
  src/sentry/integrations/slack/utils/notifications.py
  src/sentry/integrations/slack/utils/users.py
  src/sentry/integrations/slack/webhooks/action.py
  src/sentry/integrations/slack/webhooks/event.py
  src/sentry/shared_integrations/client/proxy.py
  src/sentry/tasks/integrations/slack/post_message.py
  src/sentry/testutils/silo.py
  tests/sentry/api/endpoints/internal/test_integration_proxy.py
  tests/sentry/incidents/action_handlers/test_slack.py
  tests/sentry/integrations/slack/test_client.py
  tests/sentry/integrations/slack/test_tasks.py
  tests/sentry/integrations/slack/webhooks/actions/test_status.py
  tests/sentry/integrations/slack/webhooks/events/test_link_shared.py
  tests/sentry/shared_integrations/client/test_proxy.py
Labels: Scope: Backend

#48230 chore(migration): Set monitor status to ObjectStatus only
  migrations_lockfile.txt
  src/sentry/migrations/0433_set_monitor_status_to_object_status_only.py
Labels: Scope: Backend

#48286 feat(issue-platform): Respect custom dataset query parameter
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/endpoints/organization_events_stats.py
  src/sentry/search/events/datasets/discover.py
Labels: Scope: Backend

#48163 replay(feat): Adjust default Replay>Network Panel height & min/max sizes
  static/app/views/replays/detail/network/index.tsx
  static/app/views/replays/detail/network/networkTableCell.tsx
Labels: Scope: Frontend

#48265 test(replay): Create TestStubs for ReplaySpan objects
  fixtures/js-stubs/replaySegments.ts
  fixtures/js-stubs/types.tsx
  static/app/utils/replays/replayDataUtils.spec.tsx
  tests/js/sentry-test/loadFixtures.ts
Labels: Scope: Frontend

#48281 fix(integrations) Fix json encode errors in pagerduty integrations
  src/sentry/api/serializers/rest_framework/notification_action.py
  src/sentry/incidents/endpoints/organization_alert_rule_available_action_index.py
  src/sentry/incidents/logic.py
  src/sentry/integrations/pagerduty/actions/notification.py
  tests/sentry/integrations/pagerduty/test_notify_action.py
Labels: Scope: Backend

#48042 feat(issue-states): add task to transition 14+ day old regressed issues to ONGOING
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/issues/ongoing.py
  src/sentry/tasks/auto_ongoing_issues.py
  tests/sentry/issues/test_ongoing.py
  tests/sentry/tasks/test_auto_ongoing_issues.py
Labels: Scope: Backend

#48312 ref(crons): Do not use MonitorStatus for monitor.status queries
  src/sentry/monitors/consumers/check_in.py
  src/sentry/monitors/endpoints/organization_monitor_details.py
Labels: Scope: Backend

#47981 ref(onboarding): Replace client-state with onboardingContext
  static/app/components/onboarding/changeRouteModal.tsx
  static/app/components/onboarding/footer.spec.tsx
  static/app/components/onboarding/footer.tsx
  static/app/components/onboarding/footerWithViewSampleErrorButton.tsx
  static/app/components/onboarding/frameworkSuggestionModal.tsx
  static/app/components/onboarding/onboardingContext.tsx
  static/app/components/onboardingWizard/onboardingProjectsCard.tsx
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/components/onboardingWizard/taskConfig.tsx
  static/app/components/performanceOnboarding/sidebar.spec.tsx
  static/app/components/sidebar/index.spec.jsx
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/main.tsx
  static/app/stores/persistedStore.spec.tsx
  static/app/stores/persistedStore.tsx
  static/app/types/onboarding.tsx
  static/app/views/onboarding/components/createProjectsFooter.tsx
  static/app/views/onboarding/components/firstEventFooter.tsx
  static/app/views/onboarding/createSampleEventButton.tsx
  static/app/views/onboarding/index.tsx
  static/app/views/onboarding/onboarding.spec.tsx
  static/app/views/onboarding/onboarding.tsx
  static/app/views/onboarding/platformSelection.tsx
  static/app/views/onboarding/setupDocs.spec.tsx
  static/app/views/onboarding/setupDocs.tsx
  static/app/views/onboarding/types.ts
  static/app/views/onboarding/utils.tsx
  static/app/views/onboarding/welcome.tsx
  tests/acceptance/test_onboarding.py
Labels: Scope: Frontend

#47316 ref(loader): Streamline var usage
  src/sentry/templates/sentry/js-sdk-loader.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.min.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.ts
Labels: Scope: Frontend, Scope: Backend

#48134 feat(dynamic-sampling): Add feature flag for sliding window
  src/sentry/conf/server.py
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/rules/combinators/base.py
  src/sentry/dynamic_sampling/rules/combine.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#48153 fix(sourcemaps): Fix NoneType error
  src/sentry/lang/javascript/processor.py
Labels: Scope: Backend

#48150 feat(js): Map new Symbolicator 'scraping disabled' error
  src/sentry/lang/javascript/processing.py
Labels: Scope: Backend

#48324 fix(command-source): Fix undefined organization throwing
  static/app/components/acl/access.tsx
Labels: Scope: Frontend

#48128 ref(loader): Add analytics when loader is rendered
  src/sentry/web/frontend/__init__.py
  src/sentry/web/frontend/analytics.py
  src/sentry/web/frontend/js_sdk_loader.py
Labels: Scope: Backend

#48022 ref: Remove cardinality limiter, use copy from sentry_redis_tools
  mypy.ini
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/ratelimits/cardinality.py
  src/sentry/utils/redis_metrics.py
  tests/sentry/ratelimits/test_cardinality.py
Labels: Scope: Backend

#48326 chore(deps): Bump sentry-sdk to 1.21.1 to include profiler memory fix
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#48321 ref(spans): Apply to projects the feature flag to extract metrics
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#48340 ref(suggested-solution): Fix image over button
  static/app/components/events/aiSuggestedSolution/banner.tsx
Labels: Scope: Frontend

#48275 feat(starfish): add outlier detection to all columns and use iqr method
  static/app/views/starfish/modules/databaseModule/panel.tsx
Labels: Scope: Frontend

#48278 feat(starfish): Introduce similarity badge
  static/app/views/starfish/modules/databaseModule/databaseTableView.tsx
Labels: Scope: Frontend

#48342 feat(dynamic-sampling): Disable replay_id bias
  src/sentry/dynamic_sampling/rules/combine.py
  tests/sentry/dynamic_sampling/rules/biases/test_boost_replay_id_bias.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#48293 ref(utils): Update docs re: not importing models
  src/sentry/utils/__init__.py
Labels: Scope: Backend

#48296 feat(replays): check queryReferrer to allow multi-project queries
  src/sentry/replays/blueprints/api.md
  src/sentry/replays/endpoints/organization_replay_index.py
  tests/sentry/replays/test_organization_replay_index.py
Labels: Scope: Backend

#48295 feat(issue-platform): Make `GroupEventsEndpoint` able to read from the issue platform for perf issues
  src/sentry/api/helpers/events.py
  tests/snuba/api/endpoints/test_group_events.py
Labels: Scope: Backend

#48152 ref: store audit log state as a list instead of set
  src/sentry/api/endpoints/project_filter_details.py
  src/sentry/audit_log/events.py
Labels: Scope: Backend

#48348 fix(starfish): onclose gets ran when already closed
  static/app/views/starfish/components/detailPanel.tsx
Labels: Scope: Frontend

#48338 feat(starfish): Span comparison view and api view slight improvements
  static/app/views/starfish/components/sparkline.tsx
  static/app/views/starfish/modules/APIModule/constants.tsx
  static/app/views/starfish/modules/APIModule/hostDetails.tsx
  static/app/views/starfish/modules/APIModule/hostTable.tsx
  static/app/views/starfish/views/spanSummary/eventComparisonView.tsx
  static/app/views/starfish/views/spanSummary/index.tsx
Labels: Scope: Frontend

#48092 fix(crons): Sets a hard limit on monitors per org and envs per monitor
  src/sentry/conf/server.py
  src/sentry/monitors/consumers/check_in.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_index.py
  src/sentry/monitors/endpoints/organization_monitors.py
  src/sentry/monitors/models.py
  tests/sentry/monitors/endpoints/test_monitor_ingest_checkin_index.py
  tests/sentry/monitors/endpoints/test_organization_monitors.py
  tests/sentry/monitors/test_models.py
  tests/sentry/monitors/test_monitor_consumer.py
Labels: Scope: Backend

#48284 fix(monitors): Fixes deletions for monitors and monitor environments w/lots of check-ins
  src/sentry/deletions/__init__.py
  src/sentry/deletions/defaults/__init__.py
  src/sentry/deletions/defaults/monitor.py
  src/sentry/deletions/defaults/monitor_environment.py
  tests/sentry/deletions/test_monitor.py
  tests/sentry/deletions/test_monitor_environment.py
  tests/sentry/deletions/test_project.py
Labels: Scope: Backend

#47877 ref(replays): remove unused chunking code
  src/sentry/replays/consumers/recording.py
  src/sentry/replays/usecases/ingest/__init__.py
  tests/sentry/replays/consumers/test_recording.py
Labels: Scope: Backend

#48186 feat(roles): Team-roles for Issue Owner page
  static/app/views/settings/project/projectOwnership/index.tsx
Labels: Scope: Frontend

#48190 feat(roles): Team-roles for Issue Grouping page
  static/app/views/settings/projectIssueGrouping/index.tsx
Labels: Scope: Frontend

#48194 feat(roles): Team-roles for Release Tracking page
  static/app/components/inactivePlugins.tsx
  static/app/components/pluginConfig.tsx
  static/app/components/pluginList.tsx
  static/app/views/settings/project/projectReleaseTracking.tsx
Labels: Scope: Frontend

#48319 fix(ui): Error on Team Details page
  static/app/views/settings/organizationTeams/teamDetails.tsx
Labels: Scope: Frontend

#48191 feat(roles): Team-roles for Performance page
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#48195 feat(roles): Team-roles for User Feedback page
  static/app/views/settings/project/projectUserFeedback.tsx
Labels: Scope: Frontend

#48345 chore: Disable django signal spans
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#48189 feat(roles): Team-roles for Security and Privacy
  static/app/views/settings/projectSecurityAndPrivacy/index.tsx
Labels: Scope: Frontend

#48082 perf(issue-details): updates group details to use new endpoint
  static/app/views/issueDetails/groupDetails.tsx
  static/app/views/issueDetails/utils.tsx
Labels: Scope: Frontend

#48192 feat(roles): Team-roles for Client Keys page
  static/app/views/settings/project/projectKeys/list/index.tsx
  static/app/views/settings/project/projectKeys/list/keyRow.tsx
Labels: Scope: Frontend

#48222 fix(escalating): Adjust resolve and archive tooltip copy
  static/app/components/actions/archive.tsx
  static/app/components/actions/resolve.tsx
Labels: Scope: Frontend

#48291 ref(slack): Remove `integration_id` default for slack `post_message` task
  src/sentry/tasks/integrations/slack/post_message.py
Labels: Scope: Backend

#48349 fix(hybridcloud) Fix N queries and integrity error from actors
  src/sentry/api/serializers/models/project.py
  src/sentry/models/actor.py
  src/sentry/notifications/helpers.py
Labels: Scope: Backend

#48358 chore(team-roles): Refactor Access component
  static/app/components/acl/access.tsx
Labels: Scope: Frontend

#48354 feat(starfish): Remove refs to fromUnixTimestamp
  static/app/views/starfish/modules/databaseModule/databaseChartView.tsx
  static/app/views/starfish/modules/databaseModule/index.tsx
  static/app/views/starfish/modules/databaseModule/panel.tsx
  static/app/views/starfish/modules/databaseModule/queries.ts
  static/app/views/starfish/views/webServiceView/endpointDetails/index.tsx
Labels: Scope: Frontend

#47025 ref(perf): Add VCD to dashboard list view
  static/app/utils/performanceForSentry.tsx
  static/app/views/dashboards/widgetCard/index.tsx
Labels: Status: Stale, Scope: Frontend

#48173 feat(escalating): Add archived until escalating issue activity
  static/app/types/group.tsx
  static/app/views/issueDetails/groupActivity.spec.jsx
  static/app/views/issueDetails/groupActivity.tsx
  static/app/views/issueDetails/groupActivityItem.tsx
Labels: Scope: Frontend

#48161 feat(perf-issues): Update FE tests to use http.method in spans
  static/app/components/events/interfaces/spans/spanTreeModel.spec.tsx
  static/app/components/events/interfaces/spans/waterfallModel.spec.tsx
Labels: Scope: Frontend

#48346 feat(starfish): Add a module breakdown to endpoint detail
  static/app/views/starfish/components/breakdownBar.tsx
  static/app/views/starfish/views/webServiceView/endpointDetails/index.tsx
  static/app/views/starfish/views/webServiceView/queries.js
  static/app/views/starfish/views/webServiceView/starfishView.tsx
Labels: Scope: Frontend

#48347 chore(various): Fix typos, add/clarify comments, apply auto-formatting
  config/hooks/pre-commit
  pyproject.toml
  src/sentry/api/base.py
  src/sentry/features/__init__.py
  src/sentry/features/manager.py
  src/sentry/integrations/jira/endpoints/descriptor.py
  src/sentry/integrations/mixins/repositories.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/rule.py
  src/sentry/options/defaults.py
  src/sentry/shared_integrations/exceptions/base.py
  src/sentry/testutils/cases.py
  src/sentry/utils/sdk.py
  tests/sentry/models/test_release.py
  tests/sentry/utils/test_sdk.py
Labels: Scope: Backend

#48369 ref(escalating_issues): Test changes
  src/sentry/issues/escalating.py
  tests/sentry/issues/test_escalating.py
Labels: Scope: Backend

#48364 feat(starfish): Add Throughput sparklines for API endpoint table
  static/app/views/starfish/components/sparkline.tsx
  static/app/views/starfish/modules/APIModule/endpointTable.tsx
  static/app/views/starfish/modules/APIModule/queries.js
  static/app/views/starfish/views/endpointDetails/index.tsx
  static/app/views/starfish/views/webServiceView/endpointDetails/index.tsx
Labels: Scope: Frontend

#48159 feat(alerts): Allow delete on alert without incidents feature
  src/sentry/incidents/endpoints/bases.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_details.py
Labels: Scope: Backend

#48379 feat(ui): Sanitize org replays endpoint on error
  static/app/utils/requestError/sanitizePath.spec.tsx
  static/app/utils/requestError/sanitizePath.tsx
Labels: Scope: Frontend

#48382 fix(crons): Correct react key error in monitors list
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#48389 ref(starfish): cleanup db module a bit
  static/app/views/starfish/modules/databaseModule/databaseChartView.tsx
  static/app/views/starfish/modules/databaseModule/index.tsx
  static/app/views/starfish/modules/databaseModule/panel.tsx
  static/app/views/starfish/modules/databaseModule/queries.ts
  static/app/views/starfish/views/webServiceView/endpointDetails/index.tsx
Labels: Scope: Frontend

#48283 feat(crons): Include SDK name in consumer metrics
  src/sentry/monitors/consumers/check_in.py
Labels: Scope: Backend

#48400 ref(crons): Show human readable cron tab text in sidebar
  static/app/views/monitors/components/detailsSidebar.tsx
  static/app/views/monitors/components/row.tsx
  static/app/views/monitors/utils.tsx
Labels: Scope: Frontend

#48311 ref(crons): Limit Monitor.status to ONLY object status
  src/sentry/monitors/models.py
Labels: Scope: Backend

#48378 feat(generic-metrics): Complete switchover from old to new cache keys
  src/sentry/sentry_metrics/indexer/cache.py
  tests/sentry/sentry_metrics/test_all_indexers.py
  tests/sentry/sentry_metrics/test_indexer_cache.py
Labels: Scope: Backend

#48318 ref(onboarding): Reactivate project deletion in the the onboarding of new organizations
  static/app/utils/eventWaiter.tsx
  static/app/views/onboarding/components/createProjectsFooter.tsx
  static/app/views/onboarding/onboarding.spec.tsx
  static/app/views/onboarding/onboarding.tsx
Labels: Scope: Frontend

#48353 Revert "fix(quota): Max limit of 2**32 - 1"
  src/sentry/quotas/base.py
  tests/sentry/quotas/test_base.py
Labels: Scope: Backend

#47980 Initial code parts for CSP implementation for sentry and self-hosted
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/conf/server.py
  src/sentry/integrations/jira/views/base.py
Labels: Scope: Backend

#48418 ref(onboarding): Add amplitude code to track project removal
  static/app/components/confirm.tsx
  static/app/utils/analytics/onboardingAnalyticsEvents.tsx
  static/app/views/onboarding/onboarding.tsx
Labels: Scope: Frontend

#48419 ref(project-details-endpoint): Add deletion origin to audit log
  src/sentry/api/endpoints/project_details.py
  src/sentry/audit_log/register.py
Labels: Scope: Backend

#48333 ref: Remove sliding_windows ratelimiter, use copy from sentry_redis_tools
  src/sentry/ratelimits/sliding_windows.py
  tests/sentry/ratelimits/test_sliding_windows.py
Labels: Scope: Backend

#48420 ref(project-deletion): Update code to send the deletion origin in request
  static/app/actionCreators/projects.tsx
  static/app/views/onboarding/onboarding.tsx
  static/app/views/settings/projectGeneralSettings/index.tsx
Labels: Scope: Frontend

#48422 feat(dynamic-sampling): Return whether an org has dynamic sampling
  src/sentry/api/serializers/models/organization.py
  tests/sentry/api/endpoints/test_organization_details.py
Labels: Scope: Backend

#48376 feat(starfish): adds a span tree comparison to span summary
  static/app/views/starfish/views/spanSummary/compare/spanBar.tsx
  static/app/views/starfish/views/spanSummary/compare/spanGroup.tsx
  static/app/views/starfish/views/spanSummary/compare/spanTree.tsx
  static/app/views/starfish/views/spanSummary/compare/styles.tsx
  static/app/views/starfish/views/spanSummary/compare/utils.tsx
  static/app/views/starfish/views/spanSummary/eventComparisonView.tsx
Labels: Scope: Frontend

#48425 ref(onboarding): Update copy confirmation button in the deletion modal
  static/app/views/onboarding/onboarding.tsx
Labels: Scope: Frontend

#48155 feat(perf-issues): Accept http.method as key for span data
  fixtures/events/performance_problems/consecutive-http/consecutive-http-basic.json
  fixtures/events/performance_problems/n-plus-one-api-calls/n-plus-one-api-calls-in-issue-stream.json
  fixtures/events/performance_problems/n-plus-one-api-calls/n-plus-one-api-calls-in-weather-app.json
  fixtures/events/performance_problems/n-plus-one-api-calls/not-n-plus-one-api-calls.json
  fixtures/events/performance_problems/n-plus-one-in-rails-index-view.json
  src/sentry/utils/performance_issues/detectors/consecutive_db_detector.py
  src/sentry/utils/performance_issues/detectors/large_payload_detector.py
  src/sentry/utils/performance_issues/detectors/render_blocking_asset_span_detector.py
  src/sentry/utils/performance_issues/detectors/uncompressed_asset_detector.py
Labels: Scope: Backend

#48269 feat(consecutive-http): Update threshold checks
  fixtures/events/performance_problems/consecutive-http/consecutive-http-basic.json
  src/sentry/options/defaults.py
  src/sentry/utils/performance_issues/detectors/consecutive_http_detector.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_consecutive_http_detector.py
Labels: Scope: Backend

#48368 feat(consecutive-http): Add lcp threshold option to frontend
  static/app/views/admin/adminSettings.tsx
  static/app/views/admin/options.tsx
Labels: Scope: Frontend

#47418 fix(hybrid-cloud): Add OutboxCategory.ORGANIZATION_MEMBER_CREATE
  src/sentry/models/organizationmember.py
  src/sentry/models/outbox.py
  src/sentry/receivers/outbox/region.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  tests/sentry/hybrid_cloud/test_organizationmembermapping.py
Labels: Scope: Backend

#48377 fix(meps): filter histogram outliers when using metrics dataset
  src/sentry/api/endpoints/organization_events_histogram.py
  src/sentry/snuba/metrics/utils.py
  tests/snuba/api/endpoints/test_organization_events_histogram.py
Labels: Scope: Backend

#48432 ref(js): Get module and in_app from symbolicator
  src/sentry/lang/javascript/processing.py
  src/sentry/lang/javascript/processor.py
Labels: Scope: Backend

#48433 feat(starfish): Span view scaffold
  static/app/routes.tsx
  static/app/views/starfish/views/spans/index.tsx
  static/app/views/starfish/views/spans/queries.tsx
  static/app/views/starfish/views/spans/spansTable.tsx
  static/app/views/starfish/views/spans/spansView.tsx
Labels: Scope: Frontend

#48430 feat(consecutive-http): Add tag to separate frontend events
  src/sentry/utils/event.py
  src/sentry/utils/performance_issues/detectors/consecutive_http_detector.py
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#48408 Update resources text for Profiling Issues
  static/app/utils/issueTypeConfig/profileConfig.tsx
Labels: Scope: Frontend

#48406 fix(replays): Fix padding around the TimestampButton in Replay>Network table
  static/app/views/replays/detail/network/networkTableCell.tsx
Labels: Scope: Frontend

#48438 fix(profiling): early return from hook
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingSidebar.tsx
Labels: Scope: Frontend

#48434 fix(routes): Fix starfish route
  static/app/routes.tsx
Labels: Scope: Frontend

#48200 feat(roles): Team-roles for Team Projects page
  fixtures/js-stubs/project.js
  fixtures/js-stubs/team.js
  static/app/views/settings/organizationTeams/teamProjects.spec.jsx
  static/app/views/settings/organizationTeams/teamProjects.tsx
Labels: Scope: Frontend

#48197 feat(roles): Team-roles for Team Settings page
  static/app/data/forms/teamSettingsFields.tsx
  static/app/views/settings/organizationTeams/teamSettings/index.spec.jsx
  static/app/views/settings/organizationTeams/teamSettings/index.tsx
Labels: Scope: Frontend

#48413 fix(perf): remove slug from check_object_permissions_on_organization …
  src/sentry/api/bases/organization.py
Labels: Scope: Backend

#48446 fix(event-waiter): Remove update project logic
  static/app/utils/eventWaiter.tsx
Labels: Scope: Frontend

#48445 fix(hybrid-cloud): Fix Slack webhook response parser bug
  src/sentry/middleware/integrations/parsers/slack.py
Labels: Scope: Backend

#48257 feat(escalating_issues): Support profiling and performance issues
  src/sentry/issues/escalating.py
  tests/sentry/issues/test_escalating.py
Labels: Scope: Backend

#48339 feat(replays): query for all errors for a given replayId
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/components/replays/breadcrumbs/utils.tsx
  static/app/utils/replays/hooks/useReplayData.spec.tsx
  static/app/utils/replays/hooks/useReplayData.tsx
Labels: Scope: Frontend

#48458 ref(vercel): Fix typo
  src/sentry/integrations/vercel/integration.py
Labels: Scope: Backend

#48394 feat(issues): converts GroupEventDetails to functional component
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.tsx
Labels: Scope: Frontend

#48461 chore(frontend): Delete un-used DATA_CATEGORY_NAMES constant
  static/app/constants/index.tsx
Labels: Scope: Frontend

#48448 fix(frontend): Clean up useless expressions
  static/app/components/sidebar/index.tsx
  static/app/components/timeRangeSelector.spec.tsx
Labels: Scope: Frontend

#48455 chore(hybrid-cloud): Simplify usage of RpcOrganizationMemberMappingUpdate
  src/sentry/receivers/outbox/region.py
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/__init__.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/impl.py
Labels: Scope: Backend

#48352 ref(indexer): writes limiter takes UseCaseKeyCollection
  src/sentry/sentry_metrics/indexer/limiters/writes.py
  src/sentry/sentry_metrics/indexer/postgres/postgres_v2.py
  tests/sentry/sentry_metrics/limiters/test_writes_limiter.py
Labels: Scope: Backend

#48193 feat(roles): Team-roles for Key Details page
  static/app/views/settings/project/projectKeys/details/index.spec.jsx
  static/app/views/settings/project/projectKeys/details/index.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.spec.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.tsx
  static/app/views/settings/project/projectKeys/details/loaderSettings.spec.tsx
  static/app/views/settings/project/projectKeys/details/loaderSettings.tsx
Labels: Scope: Frontend

#48397 feat(starfish): small styling improvements db module
  static/app/views/starfish/modules/databaseModule/databaseChartView.tsx
  static/app/views/starfish/modules/databaseModule/index.tsx
  static/app/views/starfish/modules/databaseModule/panel.tsx
Labels: Scope: Frontend

#48391 fix(starfish): sort direction not resetting in db module
  static/app/views/starfish/modules/databaseModule/databaseTableView.tsx
  static/app/views/starfish/modules/databaseModule/panel.tsx
Labels: Scope: Frontend

#48007 ref(integrations): Stop creating new transaction in integrations client during server requests
  src/sentry/integrations/slack/client.py
  src/sentry/shared_integrations/client/base.py
  src/sentry/shared_integrations/track_response.py
  tests/sentry/integrations/test_client.py
Labels: Scope: Backend

#48409 ref(replays): Cleanup the old session-replay-slim-table feature flag (FE)
  static/app/utils/replays/fetchReplayList.tsx
  static/app/views/replays/replayTable/index.tsx
  static/app/views/replays/replayTable/tableCell.tsx
  static/app/views/replays/types.tsx
Labels: Scope: Frontend

#48468 ref(py): Avoid inheriting ObjectStatus
  src/sentry/monitors/models.py
Labels: Scope: Backend

#48473 feat(consecutive-http): Add other options to UI
  static/app/views/admin/adminSettings.tsx
  static/app/views/admin/options.tsx
Labels: Scope: Frontend

#48472 feat(consecutive-http): Convert remaining parameters into options
  src/sentry/options/defaults.py
  src/sentry/utils/performance_issues/performance_detection.py
Labels: Scope: Backend

#48440 fix(starfish): wrong label in span page
  static/app/views/starfish/views/spanSummary/sidebar.tsx
Labels: Scope: Frontend

#48374 feat(replays): display error count by project
  static/app/components/replays/header/errorCount.tsx
  static/app/utils/replays/hooks/useReplayData.spec.tsx
  static/app/utils/replays/hooks/useReplayData.tsx
  static/app/views/replays/detail/page.tsx
  static/app/views/replays/detail/replayMetaData.tsx
  static/app/views/replays/details.tsx
Labels: Scope: Frontend

#48289 feat(issue-states): Add ability to search for substatus
  src/sentry/api/issue_search.py
  src/sentry/api/serializers/models/group.py
  src/sentry/models/group.py
  src/sentry/search/utils.py
  src/sentry/types/group.py
  tests/sentry/api/test_issue_search.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#48309 feat(generic-metrics): Implement use case awareness for RawSimpleIndexer
  src/sentry/sentry_metrics/indexer/base.py
  src/sentry/sentry_metrics/indexer/mock.py
  tests/sentry/sentry_metrics/test_multiprocess_steps.py
Labels: Scope: Backend

#48410 ref(replays): Cleanup the old session-replay-slim-table feature flag (BE)
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#48279 feat(api): Allow setting team-admin when creating a new team
  src/sentry/api/endpoints/organization_teams.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/endpoints/test_organization_teams.py
Labels: Scope: Backend

#48447 fix(replays): Simplify condition for the text colour on the network details panel
  static/app/views/replays/detail/network/networkTableCell.tsx
Labels: Scope: Frontend

#48470 ref(py): Prefer ObjectStatus.ACTIVE over the alias ObjectStatus.VISIBLE
  src/sentry/api/endpoints/integrations/organization_integrations/details.py
  src/sentry/api/endpoints/integrations/organization_integrations/index.py
  src/sentry/api/endpoints/integrations/plugins/configs_index.py
  src/sentry/api/endpoints/organization_codeowners_associations.py
  src/sentry/api/endpoints/organization_repositories.py
  src/sentry/api/endpoints/organization_repository_details.py
  src/sentry/api/endpoints/user_organizationintegrations.py
  src/sentry/integrations/custom_scm/integration.py
  src/sentry/integrations/mixins/repositories.py
  src/sentry/integrations/pipeline.py
  src/sentry/integrations/slack/utils/notifications.py
  src/sentry/integrations/vercel/integration.py
  src/sentry/integrations/vsts/integration.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/integrations/organization_integration.py
  src/sentry/models/project.py
  src/sentry/models/repository.py
  src/sentry/plugins/providers/integration_repository.py
  src/sentry/relay/config/__init__.py
  src/sentry/rules/actions/integrations/create_ticket/utils.py
  src/sentry/runner/commands/cleanup.py
  src/sentry/tasks/integrations/migrate_repo.py
  src/sentry/tasks/integrations/vsts/kickoff_subscription_check.py
  src/sentry/tasks/weekly_escalating_forecast.py
  tests/sentry/api/endpoints/test_organization_repository_details.py
  tests/sentry/integrations/github/test_integration.py
  tests/sentry/integrations/jira/test_installed.py
  tests/sentry/integrations/jira/test_uninstalled.py
  tests/sentry/integrations/slack/test_uninstall.py
  tests/sentry/integrations/vercel/test_uninstall.py
Labels: Scope: Backend

#47691 feat(issue-states): manual transitions from and to ONGOING
  src/sentry/api/helpers/group_index/update.py
  tests/sentry/api/helpers/test_group_index.py
  tests/sentry/issues/test_status_change.py
Labels: Scope: Backend

#48474 feat(alerts): Introduce RuleSource for the Rule model
  migrations_lockfile.txt
  src/sentry/migrations/0435_add_alert_rule_source.py
  src/sentry/models/rule.py
Labels: Scope: Backend

#47950 feat(issue-platform): Make sure perf issues read from issue platform in notifications
  src/sentry/integrations/github/issues.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/message_builder.py
  src/sentry/integrations/slack/message_builder/base/base.py
  src/sentry/notifications/utils/__init__.py
Labels: Scope: Backend

#48501 chore(ui): Upgrade eslint
  package.json
  yarn.lock
Labels: Scope: Frontend

#48360 ref(crons): Refactor stats endpoint to make adding new statuses simpler
  src/sentry/monitors/endpoints/organization_monitor_stats.py
Labels: Scope: Backend

#48505 ref(dynamic-sampling): Add optional project
  src/sentry/quotas/base.py
Labels: Scope: Backend

#48320 feat(dynamic-sampling): Implement sliding window
  src/sentry/conf/server.py
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/rules/helpers/sliding_window.py
  src/sentry/dynamic_sampling/sliding_window.py
  src/sentry/dynamic_sampling/tasks.py
  src/sentry/options/defaults.py
  src/sentry/quotas/base.py
  tests/sentry/dynamic_sampling/rules/helpers/test_sliding_window.py
  tests/sentry/dynamic_sampling/test_sliding_window.py
  tests/sentry/dynamic_sampling/test_tasks.py
Labels: Scope: Backend
