Repository getsentry/sentry, pull requests merged in 2023-07, with the labels that each got.

#52004 featIgithub-comments): url referrer query param
  src/sentry/tasks/integrations/github/pr_comment.py
  src/sentry/types/referrer_ids.py
  tests/sentry/tasks/integrations/github/test_pr_comment.py
Labels: Scope: Backend

#51973 fix(org-tokens): Ensure correct actor is shown in security email
  src/sentry/templates/sentry/emails/org-auth-token-created.html
  src/sentry/templates/sentry/emails/org-auth-token-created.txt
Labels: Scope: Backend

#51783 fix(org-tokens): Ensure tokens are correctly reloaded
  static/app/views/settings/organizationAuthTokens/authTokenDetails.tsx
Labels: Scope: Frontend

#51980 ref(ts): Convert organizationRoot.spec to tsx
  static/app/views/organizationRoot.spec.tsx
Labels: Scope: Frontend

#51879 feat(org-token): Ensure you can upload source maps & create releases with org token
  src/sentry/api/bases/organization.py
  src/sentry/api/bases/project.py
  src/sentry/api/endpoints/organization_release_details.py
  src/sentry/api/endpoints/organization_releases.py
  src/sentry/services/hybrid_cloud/auth/model.py
  tests/sentry/api/endpoints/test_organization_artifactbundle_assemble.py
  tests/sentry/api/endpoints/test_organization_release_details.py
  tests/sentry/api/endpoints/test_organization_releases.py
  tests/sentry/api/endpoints/test_project_release_details.py
  tests/sentry/api/endpoints/test_project_releases.py
Labels: Scope: Backend

#52076 ref(ts): Convert apiNewToken.spec to tsx
  static/app/views/settings/account/apiNewToken.spec.tsx
Labels: Scope: Frontend

#52079 ref(inbound-filters): Rename chart
  static/app/views/settings/project/projectFilters/projectFiltersChart.tsx
Labels: Scope: Frontend

#52082 feat(sdk-crash-detection): Keep system lib frames
  fixtures/sdk_crash_detection/crash_event.py
  src/sentry/utils/sdk_crashes/event_stripper.py
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
Labels: Scope: Backend

#51975 Add Indexing of Artifact Bundles
  src/sentry/debug_files/__init__.py
  src/sentry/debug_files/artifact_bundles.py
Labels: Scope: Backend

#51638 ref(crons): Move timeline component into overviewTimeline/
  static/app/views/monitors/components/overviewTimeline/checkInTimeline.tsx
  static/app/views/monitors/components/overviewTimeline/index.tsx
Labels: Scope: Frontend

#51999 ref: Remove default processing store, use redis backend everywhere
  src/sentry/conf/server.py
  src/sentry/eventstore/processing/default.py
  src/sentry/eventstore/processing/redis.py
  src/sentry/integrations/slack/utils/rule_status.py
  src/sentry/ratelimits/concurrent.py
  src/sentry/ratelimits/redis.py
  src/sentry/testutils/helpers/eventprocessing.py
  src/sentry/utils/kvstore/redis.py
  src/sentry/utils/redis.py
  tests/sentry/ratelimits/test_redis_concurrent.py
  tests/sentry/tasks/test_post_process.py
  tests/sentry/tasks/test_reprocessing2.py
  tests/sentry/utils/test_redis.py
Labels: Scope: Backend

#52083 feat(sdk-crash-detection): Set in app for SDK frames
  src/sentry/utils/sdk_crashes/event_stripper.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
Labels: Scope: Backend

#52091 fix: Make docker host overridable
  src/sentry/runner/commands/devservices.py
Labels: Scope: Backend

#52100 feat(sdk-crash-detection): Project and event ID
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#52098 feat(sdk-crash-detection): Remove SDK frame path
  fixtures/sdk_crash_detection/crash_event.py
  src/sentry/utils/sdk_crashes/event_stripper.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
Labels: Scope: Backend

#51791 feat(indexer): Add bulk_reverse_resolve to avoid N+1 db queries.
  src/sentry/sentry_metrics/indexer/__init__.py
  src/sentry/sentry_metrics/indexer/base.py
  src/sentry/sentry_metrics/indexer/cache.py
  src/sentry/sentry_metrics/indexer/mock.py
  src/sentry/sentry_metrics/indexer/postgres/postgres_v2.py
  src/sentry/sentry_metrics/indexer/strings.py
  tests/sentry/sentry_metrics/test_all_indexers.py
Labels: Scope: Backend

#52109 fix(sdk-crash-detection): Ignore test crash
  fixtures/sdk_crash_detection/crash_event.py
  src/sentry/utils/sdk_crashes/cocoa_sdk_crash_detector.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
Labels: Scope: Backend

#52108 ref(sdk-crash-detection): Remove context detected
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#52114 ref(source-maps): Enable new UI and remove legacy code
  static/app/routes.tsx
  static/app/views/settings/projectSourceMaps/detail/index.spec.jsx
  static/app/views/settings/projectSourceMaps/detail/index.tsx
  static/app/views/settings/projectSourceMaps/detail/sourceMapsArtifactRow.tsx
  static/app/views/settings/projectSourceMaps/index.spec.jsx
  static/app/views/settings/projectSourceMaps/index.tsx
  static/app/views/settings/projectSourceMaps/list/index.tsx
  static/app/views/settings/projectSourceMaps/list/sourceMapsArchiveRow.tsx
Labels: Scope: Frontend

#52093 ref(setup-wizard): Reduce number of queries and remove query limits
  src/sentry/web/frontend/setup_wizard.py
  tests/sentry/web/frontend/test_setup_wizard.py
Labels: Scope: Backend

#52116 fix(dynamic-sampling): Fix false positive in organization details
  src/sentry/api/serializers/models/organization.py
  tests/sentry/api/endpoints/test_organization_details.py
Labels: Scope: Backend

#52103 feat(sdk-crash-detection): Sample Rate
  src/sentry/conf/server.py
  src/sentry/tasks/post_process.py
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  tests/sentry/tasks/test_post_process.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#52115 feat(metrics): Use bulk_reverse_reslove in metrics
  src/sentry/api/endpoints/organization_measurements_meta.py
  src/sentry/release_health/release_monitor/metrics.py
  src/sentry/sentry_metrics/utils.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/utils/pytest/metrics.py
  tests/sentry/api/endpoints/test_organization_metric_tags.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
Labels: Scope: Backend

#51920 feat(functions): Add examples to function trends endpoint
  src/sentry/api/endpoints/organization_profiling_functions.py
Labels: Scope: Backend

#51789 Recap Servers Polling support
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/serializers/models/project.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/models/options/project_option.py
  src/sentry/tasks/recap_servers.py
  static/app/data/forms/projectGeneralSettings.tsx
  static/app/views/settings/projectGeneralSettings/index.tsx
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/tasks/test_recap_servers.py
Labels: Scope: Frontend, Scope: Backend

#52043 ref(projectperf): convert test to tsx
  static/app/views/settings/projectPerformance/projectPerformance.spec.tsx
Labels: Scope: Frontend

#52102 feat(sourcemaps): Remove feature flag for artifact bundles UI
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/serializers/test_organization.py
Labels: Do Not Merge, Scope: Backend

#52041 ref(projectplugins): convert test to tsx
  static/app/views/settings/projectSourceMaps/detail/index.spec.tsx
Labels: Scope: Frontend

#52039 ref(sourcemap): convert test to tsx
  static/app/views/settings/projectSourceMaps/index.spec.tsx
Labels: Scope: Frontend

#52038 ref(userfeedback): convert test to tsx
  static/app/views/asyncView.tsx
  static/app/views/userFeedback/index.spec.tsx
  static/app/views/userFeedback/index.tsx
Labels: Scope: Frontend

#52119 fix(sdk-crashes): Improve Cocoa crash detection
  src/sentry/utils/sdk_crashes/cocoa_sdk_crash_detector.py
  src/sentry/utils/sdk_crashes/event_stripper.py
  src/sentry/utils/sdk_crashes/sdk_crash_detector.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#51252 feat(hybridcloud) Trigger separate silo DB tests with labels
  .github/workflows/backend.yml
Labels: Scope: Backend

#52224 fix(sourceMaps): remove deleted tests
  static/app/views/settings/projectSourceMaps/detail/index.spec.tsx
  static/app/views/settings/projectSourceMaps/index.spec.tsx
Labels: Scope: Frontend

#51896 ref(starfish): Remove unused code in WSV chart
  static/app/views/starfish/views/webServiceView/spanGroupBreakdown.tsx
Labels: Scope: Frontend

#51894 feat(starfish): update query param when over 7 days
  static/app/views/starfish/components/pageFilterContainer.tsx
Labels: Scope: Frontend

#52226 fix(trends): Fix trend type
  static/app/views/performance/landing/views/allTransactionsView.tsx
  static/app/views/performance/landing/views/backendView.tsx
  static/app/views/performance/landing/views/mobileView.tsx
  static/app/views/performance/landing/widgets/widgets/trendsWidget.tsx
Labels: Scope: Frontend

#52187 feat(starfish): Adds analytics for breakdown chart
  static/app/utils/analytics/starfishAnalyticsEvents.tsx
  static/app/views/starfish/components/chart.tsx
  static/app/views/starfish/components/datePicker.tsx
  static/app/views/starfish/views/webServiceView/spanGroupBreakdown.tsx
Labels: Scope: Frontend

#51739 feat(starfish): Trims off the last datapoint in starfish chart series because its incomplete
  static/app/views/starfish/components/chart.tsx
Labels: Scope: Frontend

#52229 chore(starfish): Remove unused failure detail code
  static/app/routes.tsx
  static/app/views/starfish/views/webServiceView/endpointFailureEvents/eventList.tsx
  static/app/views/starfish/views/webServiceView/endpointFailureEvents/index.tsx
Labels: Scope: Frontend

#52064 feat(auth): Add model for OIDC tokens
  src/sentry/web/frontend/openidtoken.py
  tests/sentry/web/frontend/test_openidtoken.py
Labels: Scope: Backend

#51678 ref(hybrid-cloud): make notification_settings.actor_id nullable
  migrations_lockfile.txt
  pyproject.toml
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/endpoints/team_notification_settings_details.py
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/api/endpoints/user_notification_fine_tuning.py
  src/sentry/api/endpoints/user_notification_settings_details.py
  src/sentry/api/serializers/models/notification_setting.py
  src/sentry/integrations/slack/views/link_team.py
  src/sentry/integrations/slack/webhooks/action.py
  src/sentry/migrations/0503_alter_notification_actor_nullable.py
  src/sentry/models/notificationsetting.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/manager.py
  src/sentry/services/hybrid_cloud/notifications/impl.py
  src/sentry/services/hybrid_cloud/notifications/model.py
  src/sentry/services/hybrid_cloud/notifications/serial.py
  src/sentry/services/hybrid_cloud/notifications/service.py
  src/sentry/testutils/cases.py
  src/sentry/web/frontend/accounts.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/api/endpoints/test_rpc.py
  tests/sentry/api/endpoints/test_team_notification_settings.py
  tests/sentry/api/endpoints/test_user_notification_details.py
  tests/sentry/api/endpoints/test_user_notification_fine_tuning.py
  tests/sentry/api/endpoints/test_user_notification_settings.py
  tests/sentry/api/serializers/test_group.py
  tests/sentry/digests/test_notifications.py
  tests/sentry/incidents/action_handlers/test_email.py
  tests/sentry/integrations/slack/notifications/test_issue_alert.py
  tests/sentry/integrations/slack/test_uninstall.py
  tests/sentry/integrations/slack/webhooks/actions/test_enable_notifications.py
  tests/sentry/mail/activity/test_note.py
  tests/sentry/mail/activity/test_release.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/models/test_groupsubscription.py
  tests/sentry/models/test_notificationsetting.py
  tests/sentry/models/test_project.py
  tests/sentry/models/test_team.py
  tests/sentry/notifications/notifications/test_assigned.py
  tests/sentry/notifications/notifications/test_organization_request.py
  tests/sentry/notifications/test_notifications.py
  tests/sentry/notifications/test_utils.py
  tests/sentry/notifications/utils/test_get_scope.py
  tests/sentry/notifications/utils/test_participants.py
  tests/snuba/api/serializers/test_group.py
Labels: Scope: Backend

#52240 feat(sdk-crash): Add simulator device context
  fixtures/sdk_crash_detection/crash_event.py
  src/sentry/utils/sdk_crashes/event_stripper.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
Labels: Scope: Backend

#52099 ref(inbound-filters) Remove unused inbound filter health-check feature
  src/sentry/api/endpoints/project_filter_details.py
  src/sentry/api/endpoints/project_filters.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/ingest/inbound_filters.py
  src/sentry/relay/config/__init__.py
  tests/sentry/api/endpoints/snapshots/ProjectFiltersTest/test_get.pysnap
  tests/sentry/api/endpoints/test_project_filter_details.py
  tests/sentry/api/endpoints/test_project_filters.py
  tests/sentry/api/endpoints/test_relay_projectconfigs.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/MONOLITH.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/full_config/REGION.pysnap
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#52242 fix(sdk-crash): Keep SDK frames based on filename
  src/sentry/utils/sdk_crashes/event_stripper.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#52225 fix(metrics): Use bulk_reverse_resolve take 2
  src/sentry/api/endpoints/organization_measurements_meta.py
  src/sentry/release_health/release_monitor/metrics.py
  src/sentry/sentry_metrics/indexer/base.py
  src/sentry/sentry_metrics/utils.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/utils/pytest/metrics.py
  tests/sentry/api/endpoints/test_organization_metric_tags.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
Labels: Scope: Backend

#52247 feat(sdk-crash): Require sentry-cocoa 8.2.0
  fixtures/sdk_crash_detection/crash_event.py
  src/sentry/utils/sdk_crashes/cocoa_sdk_crash_detector.py
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  src/sentry/utils/sdk_crashes/sdk_crash_detector.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#52112 fix(org-token): Ensure last used info is correctly displayed
  static/app/views/settings/organizationAuthTokens/authTokenRow.tsx
  static/app/views/settings/organizationAuthTokens/index.spec.tsx
  static/app/views/settings/organizationAuthTokens/index.tsx
Labels: Scope: Frontend

#52246 fix(dynamic-sampling): Add logging for debugging problem
  src/sentry/dynamic_sampling/tasks/logging.py
  src/sentry/dynamic_sampling/tasks/recalibrate_orgs.py
Labels: Scope: Backend

#52253 feat(framework-suggestion-modal): Add Java and its frameworks to the modal
  static/app/components/onboarding/frameworkSuggestionModal.tsx
  static/images/spot/onboarding-framework-selection-java.svg
Labels: Scope: Frontend

#51997 feat(sourcemaps): Add tables for supporting indexes
  migrations_lockfile.txt
  src/sentry/migrations/0504_add_artifact_bundle_index.py
  src/sentry/models/artifactbundle.py
  tests/sentry/migrations/test_500_set_none_date_last_modified_to_date_uploaded.py
Labels: Scope: Backend

#52256 feat(framework-suggestion-modal): Add Dotnet and its frameworks to the modal
  static/app/components/onboarding/frameworkSuggestionModal.tsx
  static/images/spot/onboarding-framework-selection-dotnet.svg
Labels: Scope: Frontend

#52255 feat(sourcemaps): Delete project association on project deletion
  src/sentry/deletions/defaults/project.py
Labels: Scope: Backend

#52044 ref(projectgeneralsettings): convert test to tsx
  static/app/views/settings/projectGeneralSettings/index.spec.tsx
Labels: Scope: Frontend

#52258 fix(dynamic-sampling): Improve logging for debugging problem
  src/sentry/dynamic_sampling/tasks/logging.py
  src/sentry/dynamic_sampling/tasks/recalibrate_orgs.py
Labels: Scope: Backend

#52230 fix(pr-comment): Guard against API errors other than rate limits
  src/sentry/tasks/integrations/github/pr_comment.py
Labels: Scope: Backend

#52263 feat(crons): Add monitor check-ins org killswitch
  src/sentry/killswitches.py
  src/sentry/monitors/consumers/monitor_consumer.py
  src/sentry/options/defaults.py
  tests/sentry/monitors/test_monitor_consumer.py
Labels: Scope: Backend

#52265 fix(dashboard-widget-descriptions): Descriptions can be blank.
  src/sentry/api/serializers/rest_framework/dashboard.py
  tests/sentry/api/endpoints/test_organization_dashboard_widget_details.py
Labels: Scope: Backend

#52000 feat(alerts): Add support for on-demand metrics in subscriptions
  src/sentry/incidents/logic.py
  src/sentry/incidents/models.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/search/events/builder/metrics.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/metric_extraction.py
  src/sentry/snuba/metrics/naming_layer/mapping.py
  src/sentry/snuba/metrics/naming_layer/mri.py
  src/sentry/snuba/metrics/naming_layer/public.py
  src/sentry/snuba/metrics/utils.py
  tests/sentry/incidents/test_logic.py
  tests/sentry/incidents/test_models.py
  tests/sentry/relay/config/test_metric_extraction.py
  tests/sentry/relay/test_config.py
  tests/sentry/search/events/builder/test_metrics.py
Labels: Scope: Backend

#52259 fix(org-token): Fix view when no token has last used project
  static/app/views/settings/organizationAuthTokens/index.spec.tsx
  static/app/views/settings/organizationAuthTokens/index.tsx
Labels: Scope: Frontend

#52234 feat(dashboard-automation): Add feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#52235 feat(starfish): consolidates and reduces the amount of unnecessary calls in span summary
  static/app/views/starfish/queries/useSpanMetrics.tsx
  static/app/views/starfish/queries/useSpanTransactionMetrics.tsx
  static/app/views/starfish/queries/useTransactions.tsx
  static/app/views/starfish/utils/useSpansQuery.tsx
  static/app/views/starfish/views/spanSummaryPage/index.tsx
  static/app/views/starfish/views/spanSummaryPage/sampleList/durationChart/index.tsx
  static/app/views/starfish/views/spanSummaryPage/spanTransactionsTable.tsx
Labels: Scope: Frontend

#52264 ref(projectalerts): convert settings to tsx
  static/app/views/settings/projectAlerts/settings.spec.tsx
Labels: Scope: Frontend

#52166 feat(profiling): support nodestore as a possible backend for span-scoped flamegraph
  src/sentry/api/endpoints/organization_profiling_profiles.py
  src/sentry/profiles/flamegraph.py
Labels: Scope: Backend

#52049 feat(issue-details): Add analytics for event has_profile
  static/app/types/event.tsx
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/utils/events.tsx
Labels: Scope: Frontend

#52236 feat(starfish): Allow clicking into WSV breakdown to jump to modular view
  static/app/views/starfish/components/chart.tsx
  static/app/views/starfish/views/webServiceView/spanGroupBreakdown.tsx
Labels: Scope: Frontend

#52271 ref: un-silence warnings about django 3.x removals
  pyproject.toml
  src/sentry/runner/settings.py
  src/sentry/utils/pytest/sentry.py
Labels: Scope: Backend

#52273 feat(starfish): Retry on 429s and increase exponential backoff
  static/app/views/starfish/queries/useTransactions.tsx
  static/app/views/starfish/utils/retryHandlers.tsx
  static/app/views/starfish/utils/useEventsStatsQuery.tsx
  static/app/views/starfish/utils/useSpansQuery.tsx
Labels: Scope: Frontend

#52276 Fix GHSA-4xqm-4p72-87h6
  src/sentry/api/base.py
  tests/sentry/api/test_base.py
Labels: Scope: Backend

#52272 ref(tests): use MockApiClient instead of Client
  static/app/__mocks__/api.tsx
  static/app/actionCreators/events.spec.tsx
  static/app/actionCreators/group.spec.tsx
  static/app/actionCreators/projects.spec.tsx
  static/app/api.spec.tsx
  static/app/components/assigneeSelector.spec.jsx
  static/app/components/discover/transactionsList.spec.jsx
  static/app/components/events/interfaces/spans/spanTreeModel.spec.tsx
  static/app/components/group/sentryAppExternalIssueForm.spec.jsx
  static/app/components/modals/dashboardWidgetQuerySelectorModal.spec.tsx
  static/app/components/modals/sudoModal.spec.jsx
  static/app/components/repositoryRow.spec.tsx
  static/app/utils/discover/discoverQuery.spec.jsx
  static/app/utils/performance/quickTrace/quickTraceQuery.spec.jsx
  static/app/utils/performance/quickTrace/traceFullQuery.spec.jsx
  static/app/utils/useApi.spec.tsx
  static/app/utils/withApi.spec.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.spec.tsx
  static/app/views/dashboards/widgetCard/index.spec.tsx
  static/app/views/dashboards/widgetCard/issueWidgetCard.spec.tsx
  static/app/views/dashboards/widgetCard/releaseWidgetQueries.spec.tsx
  static/app/views/dashboards/widgetCard/widgetQueries.spec.jsx
  static/app/views/discover/tags.spec.jsx
  static/app/views/performance/transactionSummary/transactionOverview/tagExplorer.spec.jsx
  static/app/views/settings/account/accountAuthorizations.spec.jsx
  static/app/views/settings/account/accountEmails.spec.jsx
  static/app/views/settings/account/accountIdentities.spec.jsx
  static/app/views/settings/account/accountSecurity/accountSecurityEnroll.spec.jsx
  static/app/views/settings/account/accountSecurity/index.spec.jsx
  static/app/views/settings/organizationDeveloperSettings/index.spec.jsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.spec.jsx
  static/app/views/settings/organizationIntegrations/integrationListDirectory.spec.jsx
  static/app/views/settings/organizationMembers/organizationMembersList.spec.jsx
  static/app/views/settings/organizationProjects/index.spec.jsx
  static/app/views/settings/organizationRepositories/index.spec.jsx
  static/app/views/settings/organizationTeams/teamDetails.spec.jsx
  static/app/views/settings/organizationTeams/teamMembers.spec.jsx
  static/app/views/settings/organizationTeams/teamProjects.spec.jsx
Labels: Scope: Frontend

#51559 ref(replay): Convert Errors Tab to use `*Frame` types
  fixtures/js-stubs/replay/error.ts
  fixtures/js-stubs/replayError.ts
  static/app/components/replays/virtualizedGrid/headerCell.tsx
  static/app/utils/replays/hydrateErrors.spec.tsx
  static/app/utils/replays/hydrateErrors.tsx
  static/app/utils/replays/types.tsx
  static/app/views/replays/detail/errorList/errorFilters.tsx
  static/app/views/replays/detail/errorList/errorTableCell.tsx
  static/app/views/replays/detail/errorList/index.tsx
  static/app/views/replays/detail/errorList/useErrorFilters.spec.tsx
  static/app/views/replays/detail/errorList/useErrorFilters.tsx
  static/app/views/replays/detail/errorList/useSortErrors.spec.tsx
  static/app/views/replays/detail/errorList/useSortErrors.tsx
  static/app/views/replays/detail/layout/focusArea.tsx
Labels: Scope: Frontend

#51560 ref(replay): Refactor Replay Breadcrumbs current & hoverTime highlighting
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx
  static/app/components/replays/walker/splitCrumbs.tsx
  static/app/views/replays/detail/breadcrumbs/breadcrumbRow.tsx
  static/app/views/replays/detail/breadcrumbs/index.tsx
  static/app/views/replays/detail/breadcrumbs/useScrollToCurrentItem.tsx
Labels: Scope: Frontend

#51928 ref(replay): Refactor ReplayReader.isNetworkDetailsSetup to use getSDKOptions internally
  static/app/utils/replays/replayDataUtils.spec.tsx
  static/app/utils/replays/replayDataUtils.tsx
  static/app/utils/replays/replayReader.spec.tsx
  static/app/utils/replays/replayReader.tsx
  static/app/views/replays/types.tsx
Labels: Scope: Frontend

#52281 fix(plugins): adds close modal call
  static/app/components/group/pluginActions.tsx
Labels: Scope: Frontend

#52040 ref(sourcemapdetail): convert test to tsx
  static/app/views/settings/projectSourceMaps/detail/index.spec.tsx
Labels: Scope: Frontend

#52283 fix(issue-details): Fix deleting screenshot from tags section
  static/app/components/events/eventTagsAndScreenshot/index.spec.tsx
  static/app/components/events/eventTagsAndScreenshot/index.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
Labels: Scope: Frontend

#52279 fix: correctly reflect open membership behavior
  static/app/data/forms/organizationGeneralSettings.tsx
Labels: Scope: Frontend

#52048 fix(escalating): Remove new tab from issues stream
  static/app/views/issueList/utils.spec.tsx
  static/app/views/issueList/utils.tsx
Labels: Scope: Frontend

#52287 ref: add deletion protection to sentry_activity pickle migration
  src/sentry/migrations/0493_pickle_to_json_sentry_activity.py
Labels: Scope: Backend

#52056 ref: Import deprecatedforms components directly, remove barrel file
  static/app/components/deprecatedforms/index.tsx
  static/app/components/deprecatedforms/numberField.spec.tsx
Labels: Scope: Frontend

#52284 fix(github-comments): github integration check
  static/app/views/settings/organizationGeneralSettings/index.spec.tsx
  static/app/views/settings/organizationGeneralSettings/organizationSettingsForm.spec.jsx
  static/app/views/settings/organizationGeneralSettings/organizationSettingsForm.tsx
Labels: Scope: Frontend

#51574 feat(discord): Implement Discord integration installation
  src/sentry/integrations/discord/client.py
  src/sentry/integrations/discord/integration.py
  src/sentry/integrations/discord/utils/__init__.py
  src/sentry/shared_integrations/client/integration_proxy_client.md
  tests/sentry/integrations/discord/__init__.py
  tests/sentry/integrations/discord/test_client.py
  tests/sentry/integrations/discord/test_integration.py
Labels: Scope: Backend

#52291 ref(github-comments): remove temp have qs text
  src/sentry/tasks/integrations/github/pr_comment.py
  tests/sentry/tasks/integrations/github/test_pr_comment.py
Labels: Scope: Backend

#52047 feat(helpful-event): Pass contextual issue stream query into helpful event endpoint
  static/app/components/eventOrGroupHeader.tsx
  static/app/components/eventOrGroupTitle.tsx
  static/app/components/groupPreviewTooltip/evidencePreview.tsx
  static/app/components/groupPreviewTooltip/index.tsx
  static/app/components/groupPreviewTooltip/spanEvidencePreview.tsx
  static/app/components/groupPreviewTooltip/stackTracePreview.tsx
  static/app/components/groupPreviewTooltip/utils.tsx
  static/app/views/issueDetails/groupDetails.tsx
  static/app/views/issueDetails/utils.tsx
Labels: Scope: Frontend

#52294 fix(crons): Simplify update call on task
  src/sentry/monitors/tasks.py
Labels: Scope: Backend

#51824 feat(starfish): Create service selector component
  static/app/views/starfish/components/starfishProjectSelector.tsx
  static/app/views/starfish/modules/DBModule.tsx
  static/app/views/starfish/modules/HTTPModule.tsx
  static/app/views/starfish/views/spans/spansView.tsx
  static/app/views/starfish/views/webServiceView/starfishLanding.tsx
Labels: Scope: Frontend

#52227 feat(functions): Add links to examples in function trends widgets
  static/app/utils/profiling/hooks/types.tsx
  static/app/views/profiling/landing/functionTrendsWidget.tsx
Labels: Scope: Frontend

#51919 fix(functions): Handle function fingerprint search correctly
  src/sentry/search/events/datasets/profile_functions.py
  tests/sentry/search/events/builder/test_profile_functions.py
Labels: Scope: Backend

#52295 ref: fix some `request` types
  src/sentry/web/frontend/auth_logout.py
  src/sentry/web/frontend/base.py
  src/sentry/web/frontend/debug/debug_assigned_email.py
  src/sentry/web/frontend/debug/debug_auth_views.py
  src/sentry/web/frontend/debug/debug_chart_renderer.py
  src/sentry/web/frontend/debug/debug_codeowners_auto_sync_failure_email.py
  src/sentry/web/frontend/debug/debug_error_embed.py
  src/sentry/web/frontend/debug/debug_incident_activity_email.py
  src/sentry/web/frontend/debug/debug_invalid_identity_email.py
  src/sentry/web/frontend/debug/debug_mfa_added_email.py
  src/sentry/web/frontend/debug/debug_mfa_removed_email.py
  src/sentry/web/frontend/debug/debug_new_processing_issues_email.py
  src/sentry/web/frontend/debug/debug_new_release_email.py
  src/sentry/web/frontend/debug/debug_new_user_feedback_email.py
  src/sentry/web/frontend/debug/debug_note_email.py
  src/sentry/web/frontend/debug/debug_oauth_authorize.py
  src/sentry/web/frontend/debug/debug_onboarding_continuation_email.py
  src/sentry/web/frontend/debug/debug_organization_integration_request.py
  src/sentry/web/frontend/debug/debug_organization_invite_request.py
  src/sentry/web/frontend/debug/debug_organization_join_request.py
  src/sentry/web/frontend/debug/debug_password_changed_email.py
  src/sentry/web/frontend/debug/debug_recovery_codes_regenerated_email.py
  src/sentry/web/frontend/debug/debug_regression_email.py
  src/sentry/web/frontend/debug/debug_resolved_email.py
  src/sentry/web/frontend/debug/debug_resolved_in_release_email.py
  src/sentry/web/frontend/debug/debug_setup_2fa_email.py
  src/sentry/web/frontend/debug/debug_sso_link_email.py
  src/sentry/web/frontend/debug/debug_trigger_error.py
  src/sentry/web/frontend/debug/debug_unable_to_delete_repository.py
  src/sentry/web/frontend/debug/debug_unable_to_fetch_commits_email.py
  src/sentry/web/frontend/debug/debug_unassigned_email.py
  src/sentry/web/frontend/debug/mail.py
  src/sentry/web/frontend/error_404.py
  src/sentry/web/frontend/error_500.py
  src/sentry/web/frontend/error_page_embed.py
  src/sentry/web/frontend/group_event_json.py
  src/sentry/web/frontend/home.py
  src/sentry/web/frontend/integration_extension_configuration.py
  src/sentry/web/frontend/mailgun_inbound_webhook.py
  src/sentry/web/frontend/oauth_authorize.py
  src/sentry/web/frontend/oauth_token.py
  src/sentry/web/frontend/release_webhook.py
  src/sentry/web/frontend/restore_organization.py
  src/sentry/web/frontend/setup_wizard.py
Labels: Scope: Backend

#52285 ref: django 3.x: convert csrf failure view to function view
  pyproject.toml
  src/sentry/conf/urls.py
  src/sentry/web/frontend/csrf_failure.py
Labels: Scope: Backend

#52249 Deny update of ownership settings by team contributors
  src/sentry/api/endpoints/project_ownership.py
  tests/sentry/api/endpoints/test_project_ownership.py
Labels: Scope: Backend

#52286 fix(starfish): Updates span table description link to propagate page filters
  static/app/views/starfish/views/spans/spansTable.tsx
Labels: Scope: Frontend

#52303 Revert "feat(starfish): Create service selector component"
  static/app/views/starfish/components/starfishProjectSelector.tsx
  static/app/views/starfish/modules/DBModule.tsx
  static/app/views/starfish/modules/HTTPModule.tsx
  static/app/views/starfish/views/spans/spansView.tsx
  static/app/views/starfish/views/webServiceView/starfishLanding.tsx
Labels: Scope: Frontend

#51926 feat(profiling): Mark partially deobfuscated android frames
  src/sentry/profiles/task.py
Labels: Scope: Backend

#52300 fix(starfish): Always use resolve_division to avoid infinite
  src/sentry/search/events/builder/discover.py
  src/sentry/search/events/datasets/spans_metrics.py
  tests/snuba/api/endpoints/test_organization_events_span_metrics.py
Labels: Scope: Backend

#52298 ref: fix __eq__ on Release model
  src/sentry/models/release.py
Labels: Scope: Backend

#52233 feat(starfish): add vcd measurements
  static/app/views/starfish/views/spanSummaryPage/sampleList/sampleTable/sampleTable.tsx
  static/app/views/starfish/views/spanSummaryPage/spanTransactionsTable.tsx
  static/app/views/starfish/views/spans/spansTable.tsx
  static/app/views/starfish/views/webServiceView/spanGroupBreakdown.tsx
Labels: Scope: Frontend

#51843 ref(eventstream): Remove unnecessary try/except
  src/sentry/eventstream/snuba.py
Labels: Scope: Backend

#52302 ref: replace deprecated django.conf.urls.url with django.urls.re_path
  src/sentry/admin.py
  src/sentry/api/urls.py
  src/sentry/api/utils.py
  src/sentry/conf/urls.py
  src/sentry/django_admin.py
  src/sentry/integrations/bitbucket/urls.py
  src/sentry/integrations/bitbucket_server/urls.py
  src/sentry/integrations/github/urls.py
  src/sentry/integrations/github_enterprise/urls.py
  src/sentry/integrations/gitlab/urls.py
  src/sentry/integrations/jira/urls.py
  src/sentry/integrations/jira_server/urls.py
  src/sentry/integrations/msteams/urls.py
  src/sentry/integrations/slack/urls.py
  src/sentry/integrations/vercel/urls.py
  src/sentry/integrations/vsts/urls.py
  src/sentry/plugins/base/group_api_urls.py
  src/sentry/plugins/base/project_api_urls.py
  src/sentry/plugins/base/urls.py
  src/sentry/plugins/bases/issue2.py
  src/sentry/testutils/helpers/api_gateway.py
  src/sentry/web/debug_urls.py
  src/sentry/web/urls.py
  src/sentry_plugins/asana/plugin.py
  src/sentry_plugins/bitbucket/plugin.py
  src/sentry_plugins/bitbucket/urls.py
  src/sentry_plugins/github/plugin.py
  src/sentry_plugins/github/urls.py
  src/sentry_plugins/jira/plugin.py
  src/sentry_plugins/phabricator/plugin.py
  src/sentry_plugins/pivotal/plugin.py
  src/sentry_plugins/trello/plugin.py
  src/social_auth/urls.py
  tests/sentry/api/test_handlers.py
  tests/sentry/middleware/test_access_log_middleware.py
  tests/sentry/middleware/test_customer_domain.py
  tests/sentry/middleware/test_ratelimit_middleware.py
  tests/sentry/middleware/test_subdomain.py
  tests/sentry/plugins/base/test_project_api_urls.py
  tests/sentry/ratelimits/utils/test_enforce_rate_limit.py
Labels: Scope: Backend

#52006 docs(replays): Update blueprint to include dead and rage click counts
  src/sentry/replays/blueprints/api.md
Labels: Scope: Backend

#51967 ref(Hybrid-Cloud): Patches transaction atomic to choose and assert correct silo for a given silo mode
  src/sentry/runner/initializer.py
  src/sentry/silo/patches/silo_aware_transaction_patch.py
  tests/sentry/deletions/test_sentry_app_installations.py
  tests/sentry/silo/test_silo_aware_transaction_patch.py
Labels: Scope: Backend

#51852 feat(escalating): Set substatus to ongoing when marking reviewed
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/issues/ongoing.py
  src/sentry/issues/update_inbox.py
  src/sentry/models/groupinbox.py
  tests/sentry/issues/test_ongoing.py
  tests/sentry/issues/test_update_inbox.py
  tests/sentry/models/test_groupinbox.py
  tests/sentry/tasks/test_auto_ongoing_issues.py
Labels: Scope: Backend

#52320 chore(ui): Update eslint + rules
  package.json
  static/app/views/performance/traceDetails/content.spec.tsx
  yarn.lock
Labels: Scope: Frontend

#52051 fix(escalating): Add more docs links to archive button
  static/app/components/actions/archive.tsx
  static/app/components/dropdownMenu/index.tsx
  static/app/components/dropdownMenu/list.tsx
Labels: Scope: Frontend

#51892 chore(hybrid-cloud): Add client proxy for vsts integration
  fixtures/vsts.py
  pyproject.toml
  src/sentry/integrations/client.py
  src/sentry/integrations/utils/sync.py
  src/sentry/integrations/vsts/client.py
  src/sentry/integrations/vsts/integration.py
  src/sentry/integrations/vsts/repository.py
  src/sentry/integrations/vsts/webhooks.py
  src/sentry/shared_integrations/client/proxy.py
  src/sentry/tasks/integrations/sync_status_inbound.py
  tests/sentry/integrations/vsts/test_client.py
  tests/sentry/integrations/vsts/test_integration.py
  tests/sentry/integrations/vsts/test_webhooks.py
Labels: Scope: Backend

#51765 feat(escalating): Bring back mark reviewed button
  static/app/views/issueDetails/actions/index.tsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/issueList/actions/index.spec.jsx
  static/app/views/issueList/actions/reviewAction.tsx
Labels: Scope: Frontend

#51996 feat(sourcemaps): Implement indexing with threshold
  fixtures/artifact_bundle/manifest.json
  src/sentry/conf/server.py
  src/sentry/debug_files/__init__.py
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/features/__init__.py
  src/sentry/models/artifactbundle.py
  src/sentry/tasks/assemble.py
  tests/sentry/debug_files/__init__.py
  tests/sentry/debug_files/test_artifact_bundles.py
  tests/sentry/tasks/test_assemble.py
Labels: Scope: Backend

#52008 feat(doc): Update health-check inbound filter API documentation
  src/sentry/apidocs/parameters.py
Labels: Scope: Backend

#52268 fix(dynamic-sampling): Add query timeout logging for more functions
  src/sentry/dynamic_sampling/tasks/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_transactions.py
  src/sentry/dynamic_sampling/tasks/common.py
  src/sentry/dynamic_sampling/tasks/logging.py
  src/sentry/dynamic_sampling/tasks/recalibrate_orgs.py
  src/sentry/dynamic_sampling/tasks/sliding_window.py
Labels: Scope: Backend

#52092 fix(crons): Fix Monitor list paging
  static/app/views/monitors/utils.tsx
Labels: Scope: Frontend

#52057 ref: Import forms components directly, and remove barrel file
  static/app/components/featureFeedback/feedbackModal.spec.tsx
  static/app/components/forms/index.tsx
  static/app/components/modals/savedSearchModal/createSavedSearchModal.tsx
  static/app/components/modals/savedSearchModal/editSavedSearchModal.tsx
  static/app/components/modals/savedSearchModal/savedSearchModalContent.tsx
  static/app/components/repositoryEditForm.tsx
  static/app/views/admin/adminSettings.tsx
  static/app/views/admin/installWizard/index.tsx
  static/app/views/admin/options.tsx
  static/app/views/dashboards/widgetBuilder/widgetBuilder.tsx
  static/app/views/newsletterConsent/index.tsx
  static/app/views/organizationCreate/index.tsx
  static/app/views/settings/organizationAuthTokens/authTokenDetails.tsx
  static/app/views/settings/organizationAuthTokens/newAuthToken.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryFunctionsEnvironmentVariables.tsx
  static/app/views/settings/organizationIntegrations/integrationExternalMappingForm.tsx
  static/app/views/settings/organizationIntegrations/repositoryProjectPathConfigForm.tsx
Labels: Scope: Frontend

#52251 feat(alerts): generic dataset for on-demand metrics
  static/app/views/alerts/rules/metric/ruleForm.spec.jsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/utils/onDemandMetricAlert.tsx
  static/app/views/alerts/wizard/options.tsx
Labels: Scope: Frontend

#52336 feat(sourcemaps): Improve bundles indexing resilience
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/tasks/assemble.py
Labels: Scope: Backend

#52317 ref: fix incorrect stringly-typed on_deletes
  src/sentry/migrations/0430_break_fks_on_alertruletriggeraction.py
  src/sentry/migrations/0488_add_orgauthtoken.py
  src/sentry/models/orgauthtoken.py
Labels: Scope: Backend

#52314 styles(functions): Ensure profiling widgets do not overflow
  static/app/views/profiling/landing/functionTrendsWidget.tsx
  static/app/views/profiling/landing/slowestFunctionsWidget.tsx
  static/app/views/profiling/landing/styles.tsx
Labels: Scope: Frontend

#52335 ref(metrics): Rename metrics extraction module
  src/sentry/incidents/logic.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/search/events/builder/metrics.py
  src/sentry/snuba/metrics/extraction.py
  tests/sentry/search/events/builder/test_metrics.py
Labels: Scope: Backend

#52290 fix(starfish): Remove hard-coded project IDs in queries
  static/app/types/organization.tsx
  static/app/utils/discover/eventView.tsx
  static/app/views/starfish/components/samplesTable/transactionSamplesTable.tsx
  static/app/views/starfish/queries/useSpanList.tsx
  static/app/views/starfish/queries/useSpanMeta.tsx
  static/app/views/starfish/queries/useSpanMetrics.tsx
  static/app/views/starfish/queries/useSpanMetricsSeries.tsx
  static/app/views/starfish/queries/useSpanTransactionMetrics.tsx
  static/app/views/starfish/queries/useTransactions.tsx
  static/app/views/starfish/utils/generatePerformanceEventView.tsx
  static/app/views/starfish/views/spans/queries.tsx
  static/app/views/starfish/views/spans/selectors/actionSelector.tsx
  static/app/views/starfish/views/spans/selectors/domainSelector.tsx
  static/app/views/starfish/views/spans/selectors/spanOperationSelector.tsx
  static/app/views/starfish/views/spans/spanTimeCharts.tsx
  static/app/views/starfish/views/webServiceView/endpointList.tsx
  static/app/views/starfish/views/webServiceView/endpointOverview/index.tsx
  static/app/views/starfish/views/webServiceView/endpointOverview/issuesTable.tsx
  static/app/views/starfish/views/webServiceView/index.tsx
  static/app/views/starfish/views/webServiceView/serviceDurationChartContainer.tsx
  static/app/views/starfish/views/webServiceView/serviceTimeSpentBreakdown.tsx
  static/app/views/starfish/views/webServiceView/spanGroupBreakdownContainer.tsx
  static/app/views/starfish/views/webServiceView/starfishLanding.tsx
  static/app/views/starfish/views/webServiceView/starfishView.tsx
Labels: Scope: Frontend

#52338 ref(sourcemaps): Remove option for enabling artifact bundles upload
  src/sentry/api/endpoints/chunk.py
  src/sentry/options/defaults.py
  tests/sentry/api/endpoints/test_chunk_upload.py
Labels: Scope: Backend

#52333 fix(profiling): fix broken workflow to fetch spans data.
  src/sentry/profiles/flamegraph.py
Labels: Scope: Backend

#52288 ref(discover): Convert `EventView` specs to TypeScript
  static/app/utils/discover/eventView.spec.tsx
  static/app/utils/discover/eventView.tsx
Labels: Scope: Frontend

#52299 feat(starish): update sample list to use "near baseline"
  static/app/views/starfish/components/samplesTable/common.tsx
  static/app/views/starfish/views/spanSummaryPage/sampleList/durationChart/index.tsx
Labels: Scope: Frontend

#52351 deps(ui): Upgrade typescript 5.1.6
  package.json
  yarn.lock
Labels: Scope: Frontend

#52315 fix(starfish): Dont show percentages in WSV chart if duration selected
  static/app/views/starfish/views/webServiceView/spanGroupBreakdown.tsx
Labels: Scope: Frontend

#52305 ref(tests): use tsx
  static/app/components/assigneeSelector.spec.tsx
  static/app/components/discover/transactionsList.spec.tsx
  static/app/components/group/sentryAppExternalIssueActions.spec.tsx
  static/app/components/group/sentryAppExternalIssueForm.spec.tsx
  static/app/components/modals/sudoModal.spec.tsx
  static/app/stores/teamStore.tsx
  static/app/utils/discover/discoverQuery.spec.tsx
  static/app/utils/performance/quickTrace/quickTraceQuery.spec.tsx
  static/app/utils/performance/quickTrace/traceFullQuery.spec.tsx
  static/app/views/dashboards/widgetCard/widgetQueries.spec.tsx
  static/app/views/discover/tags.spec.tsx
  static/app/views/performance/transactionDetails/quickTraceMeta.spec.tsx
  static/app/views/performance/transactionDetails/quickTraceMeta.tsx
  static/app/views/performance/transactionSummary/transactionOverview/tagExplorer.spec.tsx
  static/app/views/settings/account/accountAuthorizations.spec.tsx
  static/app/views/settings/account/accountEmails.spec.tsx
  static/app/views/settings/account/accountIdentities.spec.tsx
  static/app/views/settings/account/accountSecurity/accountSecurityEnroll.spec.tsx
  static/app/views/settings/account/accountSecurity/index.spec.tsx
  static/app/views/settings/organizationDeveloperSettings/index.spec.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.spec.tsx
  static/app/views/settings/organizationIntegrations/integrationListDirectory.spec.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.spec.tsx
  static/app/views/settings/organizationProjects/index.spec.tsx
  static/app/views/settings/organizationProjects/index.tsx
  static/app/views/settings/organizationRepositories/index.spec.tsx
  static/app/views/settings/organizationTeams/teamDetails.spec.tsx
  static/app/views/settings/organizationTeams/teamMembers.spec.tsx
  static/app/views/settings/organizationTeams/teamMembers.tsx
  static/app/views/settings/organizationTeams/teamProjects.spec.tsx
Labels: Scope: Frontend

#52239 feat(perf-detector-threshold-configuration) Added backend changes for more threshold configurations
  src/sentry/api/endpoints/project_performance_issue_settings.py
  src/sentry/options/defaults.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/api/endpoints/test_project_performance_issue_settings.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#52343 ref: fix typing in test_link_team
  pyproject.toml
  tests/sentry/integrations/slack/test_link_team.py
Labels: Scope: Backend

#52341 ref: django 3.x does not pass None groups to views any more
  src/sentry/web/frontend/js_sdk_loader.py
Labels: Scope: Backend

#52301 nit: Update fly build config
  src/sentry/auth/providers/fly/provider.py
  tests/sentry/auth/providers/fly/test_provider.py
Labels: Scope: Backend

#52354 fix(github-comments): update option toggle copy
  static/app/views/settings/organizationGeneralSettings/organizationSettingsForm.tsx
Labels: Scope: Frontend

#52362 fix(mute-metric-alerts): Add query params to incident redirect
  static/app/views/alerts/incidentRedirect.tsx
Labels: Scope: Frontend

#52347 feat(starfish): API module consistency and continuity updaes
  static/app/views/starfish/components/chart.tsx
  static/app/views/starfish/components/tableCells/countCell.tsx
  static/app/views/starfish/components/tableCells/renderHeadCell.tsx
  static/app/views/starfish/queries/useSpanMetrics.tsx
  static/app/views/starfish/views/spanSummaryPage/index.tsx
  static/app/views/starfish/views/spans/spanTimeCharts.tsx
  static/app/views/starfish/views/spans/spansTable.tsx
Labels: Scope: Frontend

#52363 fix(mute-metric-alerts): Use incident link in metric alert emails for muting
  src/sentry/incidents/action_handlers.py
  src/sentry/templates/sentry/emails/incidents/trigger.html
  src/sentry/templates/sentry/emails/incidents/trigger.txt
  tests/sentry/incidents/action_handlers/test_email.py
Labels: Scope: Backend

#52361 fix(ui): Export named constants from forms
  static/app/components/forms/types.tsx
  static/app/data/forms/organizationSecurityAndPrivacyGroups.tsx
  static/app/data/forms/projectSecurityAndPrivacyGroups.tsx
Labels: Scope: Frontend

#52002 feat(github-comments): use internal feature flag
  src/sentry/features/__init__.py
  src/sentry/tasks/integrations/github/pr_comment.py
Labels: Scope: Backend

#52036 ref(crons): Remove references to crons-issue-platform flag
  src/sentry/monitors/models.py
  tests/sentry/monitors/test_models.py
Labels: Scope: Backend

#52326 fix(hc): Prevent exception from siloed_atomic
  src/sentry/db/router.py
  src/sentry/silo/patches/silo_aware_transaction_patch.py
Labels: Scope: Backend

#52262 feat(perf-detector-threshold-configuration) Added frontend changes for more threshold configurations.
  static/app/components/forms/formPanel.tsx
  static/app/components/forms/jsonForm.tsx
  static/app/views/settings/projectPerformance/projectPerformance.spec.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#52037 feat(crons): Change crons groupcategory name
  src/sentry/issues/grouptype.py
Labels: Scope: Backend

#52034 feat(slack): slack channel lookup via schedule message
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/integrations/slack/utils/channel.py
  tests/sentry/integrations/slack/test_utils.py
Labels: Scope: Backend

#52368 ref(tests): convert test to tsx
  static/app/components/charts/baseChart.tsx
  static/app/components/charts/components/xAxis.spec.tsx
  static/app/components/charts/components/xAxis.tsx
  static/app/components/charts/eventsAreaChart.spec.tsx
  static/app/components/charts/eventsRequest.spec.tsx
  static/app/components/charts/eventsRequest.tsx
  static/app/components/charts/releaseSeries.spec.tsx
  static/app/components/charts/releaseSeries.tsx
  static/app/components/customCommitsResolutionModal.spec.tsx
  static/app/components/customResolutionModal.spec.tsx
Labels: Scope: Frontend

#52374 fix(starfish): Time spent local was always querying light time spent
  src/sentry/search/events/builder/discover.py
  src/sentry/search/events/datasets/spans_metrics.py
Labels: Scope: Backend

#52346 feat(functions): Tune function trends default threshold
  src/sentry/api/endpoints/organization_profiling_functions.py
Labels: Scope: Backend

#52357 ref(autocomplete): convert test to tsx
  static/app/components/autoComplete.spec.tsx
  static/app/components/autoComplete.tsx
Labels: Scope: Frontend

#51837 chore(gh-comments): Drop pr window to 7 days for rollout
  src/sentry/tasks/commit_context.py
  tests/sentry/tasks/test_commit_context.py
Labels: Scope: Backend

#52381 fix(ui): Set lazy calendar component type
  static/app/components/calendar/index.tsx
Labels: Scope: Frontend

#52385 feat(issue-details): Add analytics for event has_next_event and has_previous_event
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/utils/events.tsx
Labels: Scope: Frontend

#52377 ref(HC): Patches Django Transaction to have silo aware get_connection and on_commit methods
  src/sentry/silo/patches/silo_aware_transaction_patch.py
Labels: Scope: Backend

#51807 feat(api): Update Project PUT+GET+DELETE
  api-docs/openapi.json
  api-docs/paths/projects/details.json
  src/sentry/api/endpoints/organization_teams.py
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/endpoints/team_projects.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/api/serializers/models/project.py
  src/sentry/api/serializers/types.py
  src/sentry/apidocs/examples/project_examples.py
  src/sentry/apidocs/parameters.py
  tests/apidocs/endpoints/projects/test_details.py
Labels: Scope: Backend

#52386 ref(hc): Add assume_test_silo_mode test helper.
  src/sentry/testutils/silo.py
Labels: Scope: Backend

#52390 ref(sdk): Use http timing experiment
  static/app/bootstrap/initializeSdk.tsx
  static/app/utils/performanceForSentry/integrations.tsx
Labels: Scope: Frontend

#52029 feat(crons): Add crons to issue filters
  static/app/components/stream/group.tsx
  static/app/stores/tagStore.tsx
  static/app/types/group.tsx
  static/app/utils/issueTypeConfig/index.tsx
  static/app/views/issueList/filters.spec.tsx
  static/app/views/issueList/issueCategoryFilter.tsx
Labels: Scope: Frontend
