Repository getsentry/sentry, pull requests merged in 2023-09, with the labels that each got.

#55431 feat(backup): Adjust which models are backed up
  fixtures/backup/model_dependencies/detailed.json
  src/sentry/backup/comparators.py
  src/sentry/backup/mixins.py
  src/sentry/models/apigrant.py
  src/sentry/models/authenticator.py
  src/sentry/models/authidentity.py
  src/sentry/models/authprovider.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/integrations/organization_integration.py
  src/sentry/models/integrations/project_integration.py
  src/sentry/models/repository.py
  src/sentry/monitors/models.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/backup/test_imports.py
  tests/sentry/backup/test_invariants.py
  tests/sentry/backup/test_models.py
Labels: Scope: Backend

#55432 feat(backup): Use model save
  src/sentry/backup/comparators.py
  src/sentry/backup/imports.py
  src/sentry/backup/mixins.py
  src/sentry/db/models/base.py
  src/sentry/models/options/project_option.py
  src/sentry/models/projectkey.py
  src/sentry/models/team.py
  src/sentry/models/useremail.py
  src/sentry/testutils/fixtures.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/backup/test_imports.py
  tests/sentry/backup/test_roundtrip.py
Labels: Scope: Backend

#55433 fix(backup): UserEmail handling
  fixtures/backup/user-with-maximum-privileges.json
  src/sentry/models/user.py
  src/sentry/models/useremail.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#55452 feat(metrics): Implement metrics backend for minisentry
  src/sentry/metrics/composite_experimental.py
  src/sentry/metrics/minimetrics.py
  src/sentry/options/defaults.py
  tests/sentry/metrics/test_minimetrics.py
Labels: Scope: Backend

#55604 feat(onboarding): Add profiling to platform android & apple-ios
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/android/android.spec.tsx
  static/app/gettingStartedDocs/android/android.tsx
  static/app/gettingStartedDocs/apple/apple-ios.spec.tsx
  static/app/gettingStartedDocs/apple/apple-ios.tsx
Labels: Scope: Frontend

#55531 fix IN, NOT IN support in extrapolation endpoint
  src/sentry/api/event_search.py
  tests/sentry/api/test_event_search.py
Labels: Scope: Backend

#55538 feat(onboarding): Add profiling to serverless node platforms
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/node/awslambda.spec.tsx
  static/app/gettingStartedDocs/node/awslambda.tsx
  static/app/gettingStartedDocs/node/gcpfunctions.spec.tsx
  static/app/gettingStartedDocs/node/gcpfunctions.tsx
  static/app/utils/gettingStartedDocs/node.ts
Labels: Scope: Frontend

#55610 fix(onboarding): Fix malformed url regex
  static/app/gettingStartedDocs/javascript/angular.tsx
  static/app/gettingStartedDocs/javascript/gatsby.tsx
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/react.tsx
  static/app/gettingStartedDocs/javascript/remix.tsx
  static/app/gettingStartedDocs/javascript/svelte.tsx
  static/app/gettingStartedDocs/javascript/vue.tsx
Labels: Scope: Frontend

#55613 Do not store empty Bundles
  src/sentry/tasks/assemble.py
  tests/sentry/tasks/test_assemble.py
Labels: Scope: Backend

#55616 fix(platform-categories): Add missing python profiling platforms
  static/app/data/platformCategories.tsx
Labels: Scope: Frontend

#55630 feat(check): Consider on demand alerts in the compatibility check
  src/sentry/tasks/check_am2_compatibility.py
Labels: Scope: Backend

#55615 ref(stacktrace): Allow for multiple tags inside stack trace
  static/app/components/events/interfaces/frame/deprecatedLine.tsx
Labels: Scope: Frontend

#55632 ref(on-demand): Remove prefilling throttling feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/incidents/logic.py
  src/sentry/relay/config/metric_extraction.py
  tests/sentry/incidents/test_logic.py
  tests/sentry/relay/config/test_metric_extraction.py
Labels: Scope: Backend

#55617 Fix metrics name for FlatFileIndex size
  src/sentry/models/artifactbundle.py
Labels: Scope: Backend

#55633 feat(onboarding): Display slugs in onboarding doc snippets
  static/app/components/onboarding/gettingStartedDoc/sdkDocumentation.tsx
  static/app/gettingStartedDocs/java/java.spec.tsx
  static/app/gettingStartedDocs/java/java.tsx
  static/app/gettingStartedDocs/java/log4j2.spec.tsx
  static/app/gettingStartedDocs/java/log4j2.tsx
  static/app/gettingStartedDocs/java/logback.spec.tsx
  static/app/gettingStartedDocs/java/logback.tsx
  static/app/gettingStartedDocs/java/spring-boot.spec.tsx
  static/app/gettingStartedDocs/java/spring-boot.tsx
  static/app/gettingStartedDocs/java/spring.spec.tsx
  static/app/gettingStartedDocs/java/spring.tsx
Labels: Scope: Frontend

#55643 fix(alerts): run field validation for on demand alerts
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
Labels: Scope: Frontend

#55642 feat(onboarding): Remove node-serverlesscloud from project creation
  static/app/components/platformPicker.tsx
  static/app/data/platformCategories.tsx
Labels: Scope: Frontend

#55634 fix(sessions): Check wildcard search before making query
  src/sentry/snuba/sessions_v2.py
  tests/snuba/api/endpoints/test_organization_sessions.py
Labels: Scope: Backend

#55619 add link to inbound filter settings from Filtered stats tooltip
  static/app/components/scoreCard.tsx
  static/app/views/organizationStats/index.tsx
  static/app/views/organizationStats/usageStatsOrg.tsx
Labels: Scope: Frontend

#55666 fix(alerts): query on demand metrics for apdex
  static/app/views/alerts/rules/metric/ruleForm.tsx
Labels: Scope: Frontend

#55540 feat(onboarding): Add more Electron verification detail
  static/app/gettingStartedDocs/electron/electron.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#55671 fix(metrics): Fix wrong dictionary call
  src/sentry/metrics/minimetrics.py
Labels: Scope: Backend

#55676 fix(stacktrace): Right-align repeated frames icon
  static/app/components/events/interfaces/frame/deprecatedLine.tsx
Labels: Scope: Frontend

#55547 deps(profiling): bump to 1.2.0
  package.json
  yarn.lock
Labels: Scope: Frontend

#55490 fix(profiling): bump label size
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
Labels: Scope: Frontend

#55686 fix(profiling): dont render anything when < 3 points
  static/app/components/profiling/flamegraph/flamegraphChart.tsx
  static/app/utils/profiling/flamegraphChart.tsx
Labels: Scope: Frontend

#55673 feat(metrics): Add early flushing and more metrics to minimetrics
  src/sentry/metrics/minimetrics.py
  tests/sentry/metrics/test_minimetrics.py
Labels: Scope: Backend

#55575 fix(hybridcloud) Add email queue to control silo queue list
  src/sentry/conf/server.py
Labels: Scope: Backend

#54190 Feat(opsgenie): deprecate Opsgenie plugin
  src/sentry/integrations/opsgenie/integration.py
  src/sentry/plugins/__init__.py
  src/sentry/rules/actions/notify_event_service.py
Labels: Scope: Backend

#55479 feat(alerts): Emit `alert.sent` analytic on incidents
  src/sentry/analytics/events/__init__.py
  src/sentry/analytics/events/alert_sent.py
  src/sentry/incidents/action_handlers.py
  src/sentry/integrations/msteams/utils.py
  src/sentry/integrations/opsgenie/utils.py
  src/sentry/integrations/pagerduty/utils.py
  src/sentry/integrations/slack/utils/notifications.py
  src/sentry/rules/actions/notify_event_service.py
  src/sentry/services/hybrid_cloud/integration/impl.py
  src/sentry/services/hybrid_cloud/integration/service.py
  tests/sentry/incidents/action_handlers/test_email.py
  tests/sentry/incidents/action_handlers/test_msteams.py
  tests/sentry/incidents/action_handlers/test_opsgenie.py
  tests/sentry/incidents/action_handlers/test_pagerduty.py
  tests/sentry/incidents/action_handlers/test_sentry_app.py
  tests/sentry/incidents/action_handlers/test_slack.py
Labels: Scope: Backend

#54870 feat(statistical-detectors): Store states in redis
  src/sentry/statistical_detectors/algorithm.py
  src/sentry/statistical_detectors/detector.py
  src/sentry/statistical_detectors/redis.py
  src/sentry/tasks/statistical_detectors.py
  src/sentry/utils/math.py
  tests/sentry/statistical_detectors/test_algorithm.py
  tests/sentry/statistical_detectors/test_detector.py
  tests/sentry/tasks/test_statistical_detectors.py
  tests/sentry/utils/test_math.py
Labels: Scope: Backend

#55668 Remove dead fixture files
  fixtures/js-stubs/debugSymbols.js
  fixtures/js-stubs/exceptionWithRawStackTrace.js
  fixtures/js-stubs/metricsMeta.js
  fixtures/js-stubs/phabricator.js
  fixtures/js-stubs/vsts-old.js
Labels: Scope: Frontend

#55669 ref: Refactor DataScrubbingRelayPiiConfig fixture to be TS
  fixtures/js-stubs/dataScrubbingRelayPiiConfig.js
  fixtures/js-stubs/dataScrubbingRelayPiiConfig.ts
  static/app/views/settings/components/dataScrubbing/convertRelayPiiConfig.tsx
  static/app/views/settings/components/dataScrubbing/modals/add.spec.tsx
Labels: Scope: Frontend

#55572 ref(js): Convert PageOverlay to a FC
  static/app/components/pageOverlay.tsx
Labels: Scope: Frontend

#53836 fix(integrations): Make ApiClient respect REQUESTS_CA_BUNDLE env variable
  src/sentry/shared_integrations/client/base.py
  tests/sentry/integrations/test_client.py
Labels: Scope: Backend, Trigger: getsentry tests

#55590 fix(crons): Correct assumption that lastCheckIn is never null
  static/app/views/monitors/details.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#55568 feat(performance-starfish-db-widget): Minor iterations on feedback.
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/landing/queryBatcher.spec.tsx
  static/app/views/performance/landing/views/allTransactionsView.tsx
  static/app/views/performance/landing/views/backendView.tsx
  static/app/views/performance/landing/widgets/components/performanceWidget.tsx
  static/app/views/performance/landing/widgets/components/widgetChartRow.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
  static/app/views/performance/landing/widgets/components/widgetHeader.tsx
  static/app/views/performance/landing/widgets/transforms/transformTrendsDiscover.tsx
  static/app/views/performance/landing/widgets/utils.tsx
  static/app/views/performance/landing/widgets/widgets/histogramWidget.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/singleFieldAreaWidget.tsx
  static/app/views/performance/landing/widgets/widgets/stackedAreaChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/trendsWidget.tsx
  static/app/views/performance/landing/widgets/widgets/vitalWidget.tsx
Labels: Scope: Frontend

#55481 fix(profiling): format battery usage values from nanojoules to watts
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/utils/profiling/flamegraphChart.tsx
  static/app/utils/profiling/units/unit.spec.ts
  static/app/utils/profiling/units/units.ts
Labels: Scope: Frontend

#55425 ref(replays): refactor rendering of DOM events
  static/app/utils/replays/extractDomNodes.tsx
  static/app/utils/replays/replayReader.tsx
Labels: Scope: Frontend

#55695 feat(starfish): init interactions module
  static/app/views/performance/browser/interactionTable.tsx
  static/app/views/performance/browser/interactionsLandingPage.tsx
  static/app/views/performance/browser/useBrowserFilters.tsx
Labels: Scope: Frontend

#55073 feat(replays): Add jump to current timestamp in network tab
  static/app/views/replays/detail/network/index.tsx
Labels: Scope: Frontend

#55702 test(units): add nj to watt test
  static/app/utils/profiling/units/unit.spec.ts
Labels: Scope: Frontend

#55705 fix(alerts): Debug incident with uuid, remove unused date created
  src/sentry/templates/sentry/emails/incidents/trigger.html
  src/sentry/web/frontend/debug/debug_incident_trigger_email.py
Labels: Scope: Backend

#55707 fix(rules): Allow removing all conditions
  src/sentry/mediators/project_rules/updater.py
  tests/sentry/api/endpoints/test_project_rule_details.py
Labels: Scope: Backend

#55522 feat(notifications): Set up helpers to read from new notification tables
  fixtures/backup/model_dependencies/sorted.json
  pyproject.toml
  src/sentry/api/endpoints/notification_defaults.py
  src/sentry/integrations/slack/views/link_identity.py
  src/sentry/notifications/helpers.py
  tests/sentry/notifications/test_helpers.py
  tests/sentry/notifications/test_utils.py
Labels: Scope: Backend

#55414 feat(issue-details): Enable Replays for Performance Issues Backend
  src/sentry/models/group.py
  src/sentry/replays/endpoints/organization_replay_count.py
  src/sentry/replays/usecases/replay_counts.py
  tests/sentry/replays/test_organization_replay_count.py
Labels: Scope: Backend

#55711 fix(statistical-detectors): Should be float not int
  src/sentry/statistical_detectors/algorithm.py
  tests/sentry/statistical_detectors/test_algorithm.py
Labels: Scope: Backend

#55712 Update replay button to point to correct section
  static/app/views/performance/transactionDetails/eventMetas.tsx
Labels: Scope: Frontend

#55701 chore(spans): Remove unused options
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#55715 fix: Slice on unevaluated QuerySet for Organization.has_single_owner
  src/sentry/models/organization.py
Labels: Scope: Backend

#55713 feat(team-workflow): Add feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#55720 bug(replays): Remove explitic SplitDivider height so it flows to fill all space
  static/app/views/replays/detail/layout/splitDivider.tsx
  static/app/views/replays/detail/network/details/index.tsx
Labels: Scope: Frontend

#55723 feat(crons): Add feature flag for new onboarding
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#55567 feat(opsgenie): Frontend for spike protection notifications
  fixtures/js-stubs/availableNotificationActions.tsx
  static/app/components/notificationActions/forms/onCallServiceForm.tsx
  static/app/components/notificationActions/notificationActionItem.tsx
  static/app/components/notificationActions/notificationActionManager.spec.tsx
  static/app/components/notificationActions/notificationActionManager.tsx
Labels: Scope: Frontend

#55600 ref(alerts): Add snooze status to combined rules for metric alerts
  src/sentry/api/serializers/models/alert_rule.py
  tests/sentry/api/serializers/test_alert_rule.py
Labels: Scope: Backend

#55424 ref(hc): Replicating AuthIdentity and AuthProvider models
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  migrations_lockfile.txt
  src/sentry/api/endpoints/avatar/user.py
  src/sentry/api/endpoints/user_identity_details.py
  src/sentry/conf/server.py
  src/sentry/db/models/base.py
  src/sentry/db/models/outboxes.py
  src/sentry/migrations/0541_add_replicated_auth_models.py
  src/sentry/models/__init__.py
  src/sentry/models/authidentity.py
  src/sentry/models/authidentityreplica.py
  src/sentry/models/authprovider.py
  src/sentry/models/authproviderreplica.py
  src/sentry/models/outbox.py
  src/sentry/models/user.py
  src/sentry/receivers/outbox/control.py
  src/sentry/receivers/outbox/region.py
  src/sentry/services/hybrid_cloud/auth/model.py
  src/sentry/services/hybrid_cloud/auth/serial.py
  src/sentry/services/hybrid_cloud/identity/impl.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/services/hybrid_cloud/organization/service.py
  src/sentry/services/hybrid_cloud/user/impl.py
  src/sentry/tasks/backfill_outboxes.py
  src/sentry/tasks/check_auth.py
  src/sentry/testutils/silo.py
  src/sentry/types/region.py
  tests/sentry/hybrid_cloud/test_auth.py
  tests/sentry/hybrid_cloud/test_organization.py
  tests/sentry/tasks/test_backfill_outboxes.py
Labels: Scope: Frontend, Scope: Backend

#55417 chore(conf): rename testorg-az -> demo: step 1
  static/app/views/starfish/allowedProjects.ts
Labels: Scope: Frontend

#55737 ref: Refactor ProjectFilters to be a ts file
  fixtures/js-stubs/projectFilters.ts
Labels: Scope: Frontend

#55599 feat(notifications): Rewrite notification setting reads to use new tables
  src/sentry/notifications/helpers.py
  src/sentry/notifications/notifications/activity/new_processing_issues.py
  src/sentry/notifications/utils/participants.py
  src/sentry/plugins/bases/notify.py
  tests/sentry/notifications/test_helpers.py
Labels: Scope: Backend

#55748 fix(onboarding): Wrong profiling import
  static/app/utils/gettingStartedDocs/node.ts
Labels: Scope: Frontend

#55733 feat(issue-details): Enable Replays for Performance Issues Frontend
  static/app/components/replays/useReplaysCount.spec.tsx
  static/app/components/replays/useReplaysCount.tsx
  static/app/utils/issueTypeConfig/performanceConfig.tsx
  static/app/views/issueDetails/groupReplays/groupReplays.spec.tsx
  static/app/views/issueDetails/groupReplays/useReplaysFromIssue.spec.tsx
  static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx
  static/app/views/issueDetails/header.spec.tsx
  static/app/views/issueDetails/header.tsx
Labels: Scope: Frontend

#55675 fix(alerts): Disallow wildcard in session dataset queries
  static/app/components/smartSearchBar/index.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
Labels: Scope: Frontend

#55690 fix(metrics) Add support for apdex on metrics estimation endpoint
  src/sentry/api/endpoints/organization_metrics_estimation_stats.py
  tests/sentry/api/endpoints/test_organization_metrics_estimation_stats.py
Labels: Scope: Backend

#55753 fix(onboarding): js loader script configuration
  static/app/views/onboarding/setupDocsLoader.tsx
Labels: Scope: Frontend

#55755 Do not index DebugIds for Bundles containing none
  src/sentry/debug_files/artifact_bundle_indexing.py
  src/sentry/tasks/assemble.py
  tests/sentry/debug_files/test_artifact_bundle_indexing.py
Labels: Scope: Backend

#55659 feat(source-maps-debugger): Add source maps explain frontend on steroids
  static/app/components/events/interfaces/sourceMapsDebuggerModal.tsx
Labels: Scope: Frontend

#55736 fix(statistical-detectors): Trends link and stats period
  static/app/components/events/eventStatisticalDetector/breakpointChart.tsx
  static/app/components/events/eventStatisticalDetector/regressionMessage.tsx
Labels: Scope: Frontend

#55770 Use periodic task to bump in-use ArtifactBundles
  src/sentry/conf/server.py
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/debug_files/tasks.py
  tests/relay_integration/lang/javascript/test_plugin.py
Labels: Scope: Backend

#55762 fix: Make sure `file` exists when deleting assemble status
  src/sentry/models/artifactbundle.py
Labels: Scope: Backend

#55697 fix(hybridcloud) Fix 500s from serializing users
  src/sentry/api/serializers/models/organization_member/expand/roles.py
  src/sentry/api/serializers/models/user.py
  tests/sentry/api/endpoints/test_organization_member_details.py
Labels: Scope: Backend

#55598 fix(opsgenie): fix alert rule migration behavior
  src/sentry/tasks/integrations/migrate_opsgenie_plugin.py
  tests/sentry/integrations/opsgenie/test_integration.py
Labels: Scope: Backend

#55775 fix(performance-trace-view): Fixed row divider bug and hid duration bar in ONLY error case.
  static/app/views/performance/traceDetails/traceView.tsx
  static/app/views/performance/traceDetails/transactionBar.tsx
  static/app/views/performance/traceDetails/transactionGroup.tsx
Labels: Scope: Frontend

#55670 ref: Refactor MetricRule to be TS
  fixtures/js-stubs/metricRule.ts
  static/app/views/alerts/types.tsx
Labels: Scope: Frontend

#55401 ref(hybridcloud) Resolve cross silo queries in tasks/auth.py
  src/sentry/api/endpoints/organization_auth_provider_send_reminders.py
  src/sentry/auth/helper.py
  src/sentry/models/organizationmember.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/services/hybrid_cloud/organization/service.py
  src/sentry/tasks/auth.py
  src/sentry/templates/sentry/emails/auth-link-identity.html
  src/sentry/templates/sentry/emails/auth-link-identity.txt
  src/sentry/templates/sentry/emails/auth-sso-disabled.html
  src/sentry/templates/sentry/emails/auth-sso-disabled.txt
  src/sentry/web/frontend/debug/debug_sso_link_email.py
  src/sentry/web/frontend/organization_auth_settings.py
  tests/sentry/models/test_organizationmember.py
  tests/sentry/tasks/test_auth.py
Labels: Scope: Backend

#55699 feat(apple-crash-report): Add crashed thread state section
  src/sentry/lang/native/applecrashreport.py
  src/sentry/lang/native/registers.py
  tests/sentry/lang/native/test_applecrashreport.py
Labels: Scope: Backend

#55360 feat(issue-details): Adds in actionable items widget
  static/app/components/events/interfaces/crashContent/exception/actionableItems.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/actionableItems.tsx
  static/app/components/events/interfaces/crashContent/exception/actionableItemsUtils.tsx
  static/app/components/events/interfaces/crashContent/exception/sourcemapsWizard.tsx
  static/app/components/events/interfaces/crashContent/exception/useActionableItems.tsx
  static/app/constants/eventErrors.tsx
  static/app/utils/analytics/issueAnalyticsEvents.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#55754 feat(2 icons): Replay Breadcrumbs
  static/app/icons/iconCursorArrow.tsx
  static/app/icons/iconKeyDown.tsx
  static/app/icons/index.tsx
Labels: Scope: Frontend

#55740 cleanup: rm unused fixture file
  fixtures/js-stubs/organizationEvent.js
Labels: Scope: Frontend

#55779 feat(opsgenie): remove feature flags
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/integrations/opsgenie/integration.py
Labels: Scope: Backend

#55773 feat(starfish): fetch list of pages
  static/app/views/performance/browser/interactionsLandingPage.tsx
  static/app/views/performance/browser/useBrowserFilters.ts
  static/app/views/performance/browser/usePageQuery.ts
Labels: Scope: Frontend

#55732 chore(github-growth): add column for file language in CommitFileChange
  migrations_lockfile.txt
  src/sentry/migrations/0542_add_commitfilechange_language_col.py
  src/sentry/models/commitfilechange.py
Labels: Scope: Backend

#55783 ref(hc): Migration adding last_verified to AuthIdentityReplica
  migrations_lockfile.txt
  src/sentry/migrations/0543_add_last_verified_auth_ident_replica.py
  src/sentry/models/authidentityreplica.py
Labels: Scope: Backend

#55785 ref: prevent test pollution from not-always-registered signal in #55091
  src/sentry/tasks/integrations/slack/find_channel_id_for_rule.py
  tests/sentry/integrations/slack/test_tasks.py
Labels: Scope: Backend

#55741 ref: Replace ProjectDetails fixture with Project fixture
  fixtures/js-stubs/projectDetails.js
  static/app/components/issueDiff/index.spec.tsx
  static/app/components/modals/diffModal.spec.tsx
  static/app/utils/eventWaiter.spec.tsx
  static/app/views/issueDetails/actions/index.spec.tsx
  static/app/views/issueList/overview.spec.tsx
  static/app/views/settings/project/projectOwnership/addCodeOwnerModal.spec.tsx
  static/app/views/settings/project/projectOwnership/modal.spec.tsx
  static/app/views/settings/projectGeneralSettings/index.spec.tsx
  static/app/views/settings/projectPerformance/projectPerformance.spec.tsx
  static/app/views/settings/projectSecurityAndPrivacy/index.spec.tsx
Labels: Scope: Frontend

#55784 feat(replays): Add non-aggregate filtering optimization
  src/sentry/replays/usecases/query/__init__.py
  src/sentry/replays/usecases/query/configs/aggregate_sort.py
  src/sentry/replays/usecases/query/configs/scalar.py
  src/sentry/replays/usecases/query/configs/scalar_sort.py
Labels: Scope: Backend

#55729 fix(jira server): Only fetch issue types of projects that are available
  src/sentry/integrations/jira_server/integration.py
  tests/sentry/integrations/jira_server/test_integration.py
Labels: Scope: Backend

#55780 chore(metrics): Add a new referrer for metric validations
  src/sentry/snuba/referrer.py
Labels: Scope: Backend

#55790 fix(replays api): change limit to be per_page
  src/sentry/replays/blueprints/api.md
Labels: Scope: Backend

#55797 feat(browser-starfish): hookup prod interaction transactions
  static/app/views/performance/browser/interactionTable.tsx
  static/app/views/performance/browser/useInteractionsQuery.ts
Labels: Scope: Frontend

#55798 fix(weekly_report): Correctly add referrer to replay upsell
  src/sentry/templates/sentry/emails/reports/body.html
Labels: Scope: Backend

#55806 fix(perf): Add backslash support to SQL parser
  static/app/views/starfish/utils/sqlish/SQLishFormatter.tsx
  static/app/views/starfish/utils/sqlish/SQLishParser.spec.tsx
  static/app/views/starfish/utils/sqlish/sqlish.pegjs
Labels: Scope: Frontend

#55042 ref(metric layer): Create span versions of http_error_count and http_error_rate
  src/sentry/search/events/constants.py
  src/sentry/search/events/datasets/spans_metrics.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/fields/snql.py
  src/sentry/snuba/metrics/naming_layer/mapping.py
  src/sentry/snuba/metrics/naming_layer/mri.py
  src/sentry/snuba/metrics/naming_layer/public.py
  tests/sentry/snuba/metrics/fields/test_base.py
  tests/snuba/api/endpoints/test_organization_events_span_metrics.py
  tests/snuba/api/endpoints/test_organization_measurements_meta.py
Labels: Scope: Backend

#55789 ref(replays): update icons for replay details
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/utils/replays/getFrameDetails.tsx
  static/app/views/replays/detail/domMutations/domMutationRow.tsx
  static/app/views/replays/detail/perfTable/perfRow.tsx
Labels: Scope: Frontend

#55812 fix(replay): Update blueprint docs to use `per_page` instead of `limit` for replay list api
  src/sentry/replays/blueprints/api.md
Labels: Scope: Backend

#55813 feat(feedback): Create feature flags for user-feedback UI and ingest
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#55560 feat(backup): Add UserIP and UserOption sanitization
  src/sentry/backup/comparators.py
  src/sentry/backup/imports.py
  src/sentry/db/models/base.py
  src/sentry/models/email.py
  src/sentry/models/options/user_option.py
  src/sentry/models/userip.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#55744 feat(notifications): Read from multiple recipients for notification settings
  fixtures/backup/model_dependencies/sorted.json
  src/sentry/notifications/helpers.py
  tests/sentry/notifications/test_helpers.py
Labels: Scope: Backend

#55384 fix(hybrid-cloud): Adds an optional DB param to relay project cache on-commit logic
  src/sentry/tasks/relay.py
Labels: Scope: Backend

#55815 fix(hc): Move Authenticator query out of atomic txn
  src/sentry/api/endpoints/user_authenticator_details.py
Labels: Scope: Backend

#55561 feat(backup): Support username collision resolution
  src/sentry/api/endpoints/user_details.py
  src/sentry/db/models/base.py
  src/sentry/db/models/utils.py
  src/sentry/models/user.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#55596 feat(backup): Support org slug remapping
  fixtures/backup/duplicate-username-and-organization-slug.json
  src/sentry/api/endpoints/user_details.py
  src/sentry/backup/comparators.py
  src/sentry/backup/findings.py
  src/sentry/models/userip.py
  tests/sentry/backup/test_comparators.py
  tests/sentry/backup/test_imports.py
  tests/sentry/backup/test_roundtrip.py
Labels: Scope: Backend

#55820 chore(hybrid-cloud): Update doc string for enforce_constraints
  src/sentry/db/postgres/transactions.py
Labels: Scope: Backend

#54928 Use gradle plugin auto install in onboarding docs
  static/app/gettingStartedDocs/java/java.tsx
  static/app/gettingStartedDocs/java/log4j2.tsx
  static/app/gettingStartedDocs/java/logback.tsx
  static/app/gettingStartedDocs/java/spring-boot.tsx
  static/app/gettingStartedDocs/java/spring.tsx
  static/app/views/onboarding/setupDocs.spec.tsx
Labels: Scope: Frontend

#55764 FlatFileIndex Tables Cleanup
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  migrations_lockfile.txt
  src/sentry/migrations/0542_rm_flatfile_file.py
  src/sentry/models/artifactbundle.py
Labels: Scope: Backend

#55834 fix(metrics): handle unparseable mri
  src/sentry/snuba/metrics/datasource.py
Labels: Scope: Backend

#55829 fix(hybrid-cloud): Fix notification helpers for split db and split silo world
  fixtures/backup/model_dependencies/sorted.json
  src/sentry/notifications/helpers.py
Labels: Scope: Backend

#55841 fix(metrics): Fix key error in cardinality limiter
  src/sentry/sentry_metrics/indexer/limiters/cardinality.py
Labels: Scope: Backend

#55771 feat(product-selector): Enable product selector for self-hosted
  static/app/components/acl/featureDisabledModal.spec.tsx
  static/app/components/acl/featureDisabledModal.tsx
  static/app/components/onboarding/gettingStartedDoc/layout.tsx
  static/app/components/onboarding/productSelection.spec.tsx
  static/app/components/onboarding/productSelection.tsx
  static/app/types/hooks.tsx
  static/app/views/onboarding/setupDocs.tsx
  static/app/views/onboarding/setupDocsLoader.tsx
Labels: Scope: Frontend

#55810 fix(hybridcloud) Fix typed dict usage in organization details
  src/sentry/api/endpoints/organization_details.py
Labels: Scope: Backend

#55843 feat(onboarding): Add profiling to php platforms
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/php/laravel.spec.tsx
  static/app/gettingStartedDocs/php/laravel.tsx
  static/app/gettingStartedDocs/php/php.spec.tsx
  static/app/gettingStartedDocs/php/php.tsx
  static/app/gettingStartedDocs/php/symfony.spec.tsx
  static/app/gettingStartedDocs/php/symfony.tsx
Labels: Scope: Frontend

#55824 fix(hybrid-cloud): Update create_default_project for split silo
  src/sentry/receivers/core.py
  src/sentry/services/hybrid_cloud/user/impl.py
  src/sentry/services/hybrid_cloud/user/service.py
Labels: Scope: Backend

#55667 ref(projconfig): Bump transaction metric extraction and remove measurements config
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v3.py
  tests/sentry/relay/snapshots/test_config/test_project_config_with_breakdown/MONOLITH/with_metrics.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_with_breakdown/REGION/with_metrics.pysnap
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#55851 chore(hybrid-cloud): Enforce split database for all sentry python tests
  .github/workflows/backend.yml
Labels: Scope: Backend

#55805 feat(team-workflow): Add team to GroupSubscription
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  migrations_lockfile.txt
  src/sentry/migrations/0543_add_team_id_to_groupsubscription.py
  src/sentry/models/groupsubscription.py
Labels: Scope: Backend

#55858 chore(github-growth): add column for file language in CommitFileChange
  migrations_lockfile.txt
  src/sentry/migrations/0544_add_commitfilechange_language_col.py
  src/sentry/models/commitfilechange.py
Labels: Scope: Backend

#55716 test(hc): Partial silo mode fixes for test_organization_member_details
  src/sentry/api/bases/user.py
  tests/sentry/api/endpoints/test_organization_member_details.py
Labels: Scope: Backend

#55859 ref(hc): Disable backfill job
  src/sentry/tasks/backfill_outboxes.py
  tests/sentry/tasks/test_backfill_outboxes.py
Labels: Scope: Backend

#53584 Move project repo path parsing logic into integration
  src/sentry/api/endpoints/project_repo_path_parsing.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/integrations/mixins/repositories.py
  tests/sentry/integrations/github/test_integration.py
  tests/sentry/integrations/gitlab/test_integration.py
Labels: Scope: Backend, Trigger: getsentry tests

#55728 feat(feedback): create django model
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  migrations_lockfile.txt
  src/sentry/conf/server.py
  src/sentry/feedback/__init__.py
  src/sentry/feedback/migrations/0001_feedback.py
  src/sentry/feedback/migrations/__init__.py
  src/sentry/feedback/models.py
Labels: Scope: Backend

#55828 ref(alerts): Add rule id to dupe alert error msg
  src/sentry/api/endpoints/project_rule_details.py
  src/sentry/api/endpoints/project_rules.py
Labels: Scope: Backend

#55822 feat(hybrid-cloud): Add various methods to services
  src/sentry/services/hybrid_cloud/app/impl.py
  src/sentry/services/hybrid_cloud/app/model.py
  src/sentry/services/hybrid_cloud/app/serial.py
  src/sentry/services/hybrid_cloud/app/service.py
  src/sentry/services/hybrid_cloud/auth/impl.py
  src/sentry/services/hybrid_cloud/auth/service.py
  src/sentry/services/hybrid_cloud/user/impl.py
  src/sentry/services/hybrid_cloud/user/service.py
  src/sentry/signals.py
Labels: Scope: Backend

#55816 feat(releases): Add POST endpoint for thresholds
  fixtures/backup/model_dependencies/sorted.json
  src/sentry/api/endpoints/release_threshold.py
  src/sentry/api/serializers/models/__init__.py
  src/sentry/api/serializers/models/release_threshold.py
  src/sentry/api/urls.py
  src/sentry/models/__init__.py
  src/sentry/models/release_threshold/__init__.py
  src/sentry/models/release_threshold/constants.py
  src/sentry/models/release_threshold/releasethreshold.py
  src/sentry/models/releasethreshold.py
  tests/sentry/api/endpoints/test_release_threshold.py
Labels: Scope: Backend

#55861 test(hc): Stabilize Update and DeleteOrganizationMemberTest
  src/sentry/api/endpoints/organization_member/details.py
  tests/sentry/api/endpoints/test_organization_member_details.py
Labels: Scope: Backend

#55574 feat(crons): Implement monitor threshold issues
  src/sentry/monitors/logic/mark_failed.py
  src/sentry/monitors/models.py
  tests/sentry/monitors/logic/test_mark_failed.py
  tests/sentry/monitors/test_models.py
Labels: Scope: Backend

#55800 Add timeout to list_topics
  src/sentry/utils/batching_kafka_consumer.py
Labels: Scope: Backend

#55870 fix(migrations) Conditionally remove groupsubscription columns
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  migrations_lockfile.txt
  src/sentry/migrations/0545_remove_groupsubscription_columns.py
  src/sentry/models/groupsubscription.py
  tests/sentry/migrations/test_0502_savedsearch_update_me_myteams.py
Labels: Scope: Backend

#55877 feat(severity): adds more logging for severity
  src/sentry/event_manager.py
Labels: Scope: Backend

#55868 ref(alerts): Add snooze status to combined rules for metric alerts
  src/sentry/api/serializers/models/alert_rule.py
  tests/sentry/api/serializers/test_alert_rule.py
Labels: Scope: Backend

#55519 ref(crons): Extract mark_ok into monitors.logic
  src/sentry/monitors/consumers/monitor_consumer.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_details.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_index.py
  src/sentry/monitors/logic/mark_ok.py
  src/sentry/monitors/models.py
  tests/sentry/monitors/logic/test_mark_ok.py
  tests/sentry/monitors/test_models.py
Labels: Scope: Backend

#54996 fix(crons): Cast uuid to string for occurrence event
  src/sentry/monitors/logic/mark_failed.py
Labels: Scope: Backend

#55807 fix(hc): Add missing region-mode snapshot
  tests/sentry/api/endpoints/snapshots/ProjectFiltersTest__InRegionMode/test_get.pysnap
  tests/sentry/api/endpoints/test_project_filters.py
Labels: Scope: Backend

#55884 fix(crons): Increase check_missing timeout
  src/sentry/monitors/tasks.py
Labels: Scope: Backend

#55862 ref(hybrid-cloud): Removes kludge for less strict pydantic validation, updates org mapping RPC type
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/model.py
  tests/sentry/hybrid_cloud/test_rpc.py
Labels: Scope: Backend

#55885 feat(crons): Set 1.0 sampling on monitor task metrics
  src/sentry/monitors/tasks.py
Labels: Scope: Backend

#55595 fix(alerts): Display muted for metric alerts
  static/app/views/alerts/list/rules/index.spec.tsx
  static/app/views/alerts/list/rules/row.tsx
Labels: Scope: Frontend

#55869 feat(hc): Capture service and method name in RpcExceptions
  src/sentry/services/hybrid_cloud/organization/service.py
  src/sentry/services/hybrid_cloud/region.py
  src/sentry/services/hybrid_cloud/rpc.py
  tests/sentry/api/test_authentication.py
  tests/sentry/hybrid_cloud/test_region.py
  tests/sentry/hybrid_cloud/test_rpc.py
Labels: Scope: Backend

#55887 nit - unnecessary splat of .map
  static/app/views/issueList/header.tsx
Labels: Scope: Frontend

#55890 chore(alerts): Fix severity typo
  src/sentry/rules/filters/issue_severity.py
Labels: Scope: Backend

#55832 feat(alerts): Display a noisy alert banner for no conditions
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/views/alerts/create.spec.tsx
  static/app/views/alerts/rules/issue/index.tsx
Labels: Scope: Frontend

#55895 fix(migrations) Conditionally remove groupsubscription columns
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  migrations_lockfile.txt
  src/sentry/migrations/0544_remove_groupsubscription_columns.py
  src/sentry/models/groupsubscription.py
  tests/sentry/migrations/test_0502_savedsearch_update_me_myteams.py
Labels: Scope: Backend

#55897 fix: reorder server.py
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  src/sentry/conf/server.py
Labels: Scope: Backend

#55768 ref(metrics): Refactor minimetrics
  src/minimetrics/__init__.py
  src/minimetrics/core.py
  src/sentry/metrics/minimetrics.py
  tests/minimetrics/__init__.py
  tests/minimetrics/test_core.py
  tests/sentry/metrics/test_minimetrics.py
Labels: Scope: Backend

#55838 feat(alerts): on demand alerts UI
  src/sentry/assistant/guides.py
  static/app/components/alerts/onDemandMetricAlert.tsx
  static/app/components/assistant/getGuidesContent.tsx
  static/app/components/charts/utils.tsx
  static/app/utils/onDemandMetrics/index.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/details/sidebar.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/thresholdsChart.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/index.tsx
Labels: Scope: Frontend, Scope: Backend

#55708 fix(issues): Prevent adding a code mapping if the user does not have project access
  src/sentry/api/endpoints/organization_code_mappings.py
  tests/sentry/api/endpoints/test_organization_code_mappings.py
Labels: Scope: Backend

#55756 ref(globalconfig): Support global config in projectconfig v3
  src/sentry/api/endpoints/relay/project_configs.py
  tests/sentry/api/endpoints/test_relay_globalconfig_v4.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v3.py
Labels: Scope: Backend

#55905 fix(alerts): on-demand warning icon
  static/app/views/alerts/rules/metric/details/sidebar.tsx
Labels: Scope: Frontend

#55908 fix(metrics) Metrics estimation endpoint - remove result scaling from everything except throughput
  src/sentry/api/endpoints/organization_metrics_estimation_stats.py
  tests/sentry/api/endpoints/test_organization_metrics_estimation_stats.py
Labels: Scope: Backend

#55844 Wizard only onboarding
  static/app/gettingStartedDocs/javascript/nextjs.spec.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.spec.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.tsx
Labels: Scope: Frontend

#55904 fix(platform-categories): Add missing platforms
  src/sentry/utils/platform_categories.py
Labels: Scope: Backend

#55915 fix(onboarding): Remove product selector for sveltekit & nextjs
  static/app/components/onboarding/productSelection.tsx
Labels: Scope: Frontend
