Repository getsentry/sentry, pull requests merged in 2023-12, with the labels that each got.

#60930 feat(projects): Cleanup project creation experiment - Sentry backend
  src/sentry/api/endpoints/organization_projects_experiment.py
  src/sentry/apidocs/examples/project_examples.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/endpoints/test_organization_projects_experiment.py
Labels: Scope: Backend

#60951 fix(alerts): Add dataset=errors to request for total events
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
Labels: Scope: Frontend

#60953 fix(feedbacks): populate environment correctly for crash report feedbacks
  src/sentry/feedback/usecases/create_feedback.py
  tests/sentry/api/endpoints/test_project_user_reports.py
Labels: Scope: Backend

#60944 fix(metric-alerts): Render chartcuterie charts correctly when using `is:unresolved`
  src/sentry/incidents/charts.py
  tests/sentry/incidents/action_handlers/test_email.py
Labels: Scope: Backend

#60788 feat(ddm): Add FE query validation
  static/app/components/searchSyntax/parser.spec.tsx
  static/app/components/searchSyntax/parser.tsx
  static/app/components/searchSyntax/renderer.tsx
  static/app/components/smartSearchBar/index.tsx
  static/app/components/smartSearchBar/searchDropdown.tsx
  static/app/components/smartSearchBar/utils.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/ddm/queryBuilder.tsx
Labels: Scope: Frontend

#60865 fix(ddm-alerts): Trim metric names in select control
  static/app/utils/middleEllipsis.spec.tsx
  static/app/utils/middleEllipsis.tsx
  static/app/utils/trimSlug.tsx
  static/app/views/alerts/rules/metric/mriField.tsx
Labels: Scope: Frontend

#60895 feat(ddm-alerts): Set chart granularity and period via url
  static/app/types/metrics.tsx
  static/app/utils/metrics/index.spec.tsx
  static/app/utils/metrics/index.tsx
  static/app/utils/metrics/useMetricsData.tsx
  static/app/views/alerts/rules/metric/constants.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
  static/app/views/ddm/createAlertModal.tsx
Labels: Scope: Frontend

#60960 ref(ddm): Use SmartSearchBar directly
  static/app/views/ddm/queryBuilder.tsx
Labels: Scope: Frontend

#60883 feat(ddm): code location source context
  src/sentry/api/serializers/models/code_locations.py
  src/sentry/sentry_metrics/querying/metadata.py
  tests/sentry/api/endpoints/test_organizations_ddm_meta.py
Labels: Scope: Backend

#60962 feat(profiling): upgrade symbolic dependency to 12.8.0 and re-enable android deobfuscation v2
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/profiles/task.py
Labels: Scope: Backend

#60963 feat(ddm): Move ddm-alerts to ddm-ui feature flag
  static/app/views/alerts/filterBar.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/wizardField.tsx
  static/app/views/alerts/wizard/options.tsx
  static/app/views/ddm/contextMenu.tsx
Labels: Scope: Frontend

#60758 feat(ddm): Add MQL grammar query generation to metrics API
  src/sentry/sentry_metrics/querying/api.py
  src/sentry/sentry_metrics/querying/utils.py
  tests/sentry/sentry_metrics/querying/test_api.py
Labels: Scope: Backend

#60925 fix(issues): optimize query to run only for new queries
  static/app/views/issueList/groupStatsProvider.tsx
  static/app/views/issueList/overview.spec.tsx
Labels: Scope: Frontend

#60939 ref: add tools.fast_editable as a faster pip install -e
  .github/actions/setup-sentry/action.yml
  .github/workflows/backend.yml
  scripts/lib.sh
  tools/fast_editable.py
Labels: Scope: Backend

#60931 chore(hybridcloud) Add logging for early return cases in jira
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/jira/utils/api.py
Labels: Scope: Backend

#60932 fix(hybridcloud) Don't double run celerybeat and run more webs
  src/sentry/runner/commands/devserver.py
Labels: Scope: Backend

#60837 feat(stats-detectors): Disable unsupported resolve and archive actions
  static/app/components/actions/archive.spec.tsx
  static/app/components/actions/archive.tsx
  static/app/components/actions/resolve.spec.tsx
  static/app/components/actions/resolve.tsx
  static/app/utils/issueTypeConfig/cronConfig.tsx
  static/app/utils/issueTypeConfig/errorConfig.tsx
  static/app/utils/issueTypeConfig/index.tsx
  static/app/utils/issueTypeConfig/performanceConfig.tsx
  static/app/utils/issueTypeConfig/types.tsx
  static/app/views/issueDetails/actions/index.tsx
Labels: Scope: Frontend

#60899 feat(webvitals): Adds opportunity_score function to discover and metrics dataset
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#60898 chore(hybridcloud) Remove unused setting
  src/sentry/conf/server.py
Labels: Scope: Backend

#60934 fix(profiling): render selected frame border in after render pass
  static/app/components/profiling/flamegraph/interactions/useDrawSelectedBorderEffect.tsx
Labels: Scope: Frontend

#60935 fix(profiling): dont collapse text on very long frames
  static/app/components/profiling/flamegraph/callTreeTable.tsx
Labels: Scope: Frontend

#60876 feat(sdks): Upgrade SDKs to `7.84.0` and Feedback SDK to `0.0.1-alpha.17`
  package.json
  static/app/utils/replays/replay.tsx
  yarn.lock
Labels: Scope: Frontend

#60854 ref(hc): Add check_organization_by_slug support in control
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/services/hybrid_cloud/organization/service.py
  tests/sentry/services/hybrid_cloud/organization/test_service.py
Labels: Scope: Backend

#60942 feat(replay): Add a debug view to look at mutations near replay.hydrate breadcrumbs
  static/app/utils/replays/getFrameDetails.tsx
  static/app/utils/replays/getReplayEvent.spec.tsx
  static/app/utils/replays/hydrateBreadcrumbs.spec.tsx
  static/app/utils/replays/hydrateBreadcrumbs.tsx
  static/app/utils/replays/replayReader.tsx
  static/app/views/replays/detail/console/messageFormatter.spec.tsx
  static/app/views/replays/detail/console/useConsoleFilters.spec.tsx
  static/app/views/replays/detail/perfTable/usePerfFilters.spec.tsx
Labels: Scope: Frontend

#60905 fix(perf): Correctly parse successful time ranges
  static/app/components/charts/utils.spec.tsx
  static/app/components/organizations/pageFilters/parse.tsx
Labels: Scope: Frontend

#60919 perf(perf): Memoize SQL query formatting
  static/app/views/starfish/components/spanDescription.tsx
  static/app/views/starfish/components/tableCells/spanDescriptionCell.tsx
Labels: Scope: Frontend

#60805 turn release card into a functional component
  static/app/views/releases/list/releaseCard/index.tsx
Labels: Scope: Frontend

#60973 ref(stats-detectors): Unify breakpoint detection
  src/sentry/statistical_detectors/detector.py
  src/sentry/tasks/statistical_detectors.py
  tests/sentry/tasks/test_statistical_detectors.py
Labels: Scope: Backend

#60946 chore(hybrid-cloud): Add debugging captures for MS Teams request parser
  src/sentry/integrations/msteams/webhook.py
  src/sentry/middleware/integrations/classifications.py
  src/sentry/middleware/integrations/parsers/msteams.py
Labels: Scope: Backend

#60848 feat(relocation): Add throttling
  src/sentry/api/endpoints/relocations/index.py
  src/sentry/options/defaults.py
  tests/sentry/api/endpoints/relocations/test_index.py
Labels: Scope: Backend

#60825 Remove env from threshold status response keys
  src/sentry/api/endpoints/release_thresholds/release_threshold_status_index.py
  tests/sentry/api/endpoints/release_thresholds/test_release_threshold_status.py
Labels: Scope: Backend

#60887 feat(stats-detectors): Add regression group model
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/migrations/0611_add_regression_group_model.py
  src/sentry/models/__init__.py
  src/sentry/models/statistical_detectors.py
  src/sentry/statistical_detectors/__init__.py
Labels: Scope: Backend

#60976 fix(hybridcloud) Fix silo isolation in local development and prod.
  src/sentry/conf/server.py
  src/sentry/runner/commands/devserver.py
  src/sentry/tasks/deliver_from_outbox.py
Labels: Scope: Backend

#60814 feat(webvitals): adds weighted_performance_score function to discover
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#60856 fix(issues): revert groupstore stats changes
  static/app/components/eventOrGroupExtraDetails.tsx
  static/app/components/stream/group.tsx
  static/app/components/stream/groupChart.tsx
  static/app/stores/groupStore.spec.tsx
  static/app/stores/groupStore.tsx
  static/app/utils/parseApiError.tsx
  static/app/views/issueList/groupStatsProvider.tsx
  static/app/views/issueList/overview.spec.tsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#60485 feat(feedback): display tracked issues on list
  static/app/components/feedback/list/feedbackListItem.tsx
  static/app/components/feedback/list/issueTrackingSignals.tsx
  static/app/components/feedback/useFeedbackListQueryKey.tsx
Labels: Scope: Frontend

#60565 feat(ai): Update individual consent option for sentry employees
  static/app/components/events/aiSuggestedSolution/suggestion.tsx
Labels: Scope: Frontend

#60990 chore(hybrid-cloud): Updates docs for ngrok silo running, adds port info
  src/sentry/silo/README.md
Labels: Scope: Backend

#60999 fix(alerts): Revert disabled alert list filter
  static/app/views/alerts/filterBar.tsx
Labels: Scope: Frontend

#60691 feat(grouping): Exclude sentry-java sdk frames from group and inapp
  src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt
  tests/sentry/grouping/grouping_inputs/stacktrace-collapse-recursion.json
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/stacktrace_collapse_recursion.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/stacktrace_collapse_recursion.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/stacktrace_collapse_recursion.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/stacktrace_collapse_recursion.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/stacktrace_collapse_recursion.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/stacktrace_collapse_recursion.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/java_chained.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/java_minimal.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/stacktrace_collapse_recursion.pysnap
Labels: Scope: Backend

#60938 fix(hybrid-cloud): Mark DiscordInteractionsEndpoint as an all silo endpoint
  src/sentry/integrations/discord/webhooks/base.py
  src/sentry/integrations/discord/webhooks/message_component.py
  static/app/data/controlsiloUrlPatterns.ts
  tests/sentry/integrations/discord/webhooks/test_message_component.py
  tests/sentry/middleware/integrations/parsers/test_discord.py
Labels: Scope: Frontend, Scope: Backend

#60886 feat(feedback): Move contact-email and message fields outside the contexts object
  src/sentry/feedback/usecases/create_feedback.py
  tests/sentry/feedback/usecases/test_create_feedback.py
Labels: Scope: Backend

#60954 doc(snuba): document datasets in Sentry
  src/sentry/snuba/dataset.py
Labels: Scope: Backend

#60904 feat(backup): Add confirmation dialog for global imports
  src/sentry/backup/exports.py
  src/sentry/backup/helpers.py
  src/sentry/backup/imports.py
  src/sentry/runner/commands/backup.py
  src/sentry/tasks/relocation.py
  src/sentry/testutils/helpers/backups.py
  src/sentry/utils/relocation.py
  tests/sentry/backup/test_imports.py
  tests/sentry/backup/test_releases.py
  tests/sentry/runner/commands/test_backup.py
  tests/sentry/tasks/test_relocation.py
Labels: Scope: Backend

#60964 feat(ddm): Rework quantiles support in the metrics API
  src/sentry/api/endpoints/organization_metrics.py
  src/sentry/sentry_metrics/querying/api.py
  src/sentry/snuba/metrics_layer/query.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/sentry_metrics/querying/test_api.py
Labels: Scope: Backend

#61026 fix(ddm): Rework logic for aggregate translation in alerts
  src/sentry/api/serializers/models/alert_rule.py
  src/sentry/incidents/charts.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/serializers/alert_rule.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
Labels: Scope: Backend

#61030 fix(ddm-alerts): Fix timestamp formatting in chart and alerts edit form resetting MRI
  static/app/views/alerts/rules/metric/mriField.tsx
  static/app/views/ddm/createAlertModal.tsx
Labels: Scope: Frontend

#61028 chore(metrics): Add feature for Relay cardinality limiter
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#59567 ref: upgrade celery to 5.x
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#60989 fix(devserver) Add additional workers for devserver
  src/sentry/runner/commands/devserver.py
Labels: Scope: Backend

#60998 chore(hybridcloud) Add more logging to jira early returns
  src/sentry/conf/server.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/jira/utils/api.py
  src/sentry/integrations/jira/webhooks/issue_updated.py
  src/sentry/integrations/utils/sync.py
  src/sentry/models/project.py
Labels: Scope: Backend

#60995 ref: upgrade datadog to 0.39
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/metrics/datadog.py
  src/sentry/metrics/dogstatsd.py
Labels: Scope: Backend

#61009 feat(replay): Create a hook for more Replay Onboarding CTA buttons
  static/app/types/hooks.tsx
  static/app/views/replays/list/replayOnboardingPanel.tsx
Labels: Scope: Frontend

#60909 removes the v2 suffix from notification methods and does more cleanup
  src/sentry/api/validators/integrations.py
  src/sentry/api/validators/notifications.py
  src/sentry/incidents/action_handlers.py
  src/sentry/mail/adapter.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/notifications/activity/new_processing_issues.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/types.py
  src/sentry/notifications/utils/participants.py
  src/sentry/notifications/validators.py
  tests/sentry/models/test_project.py
Labels: Scope: Backend

#61035 chore(ddm): Change comment of DDM feature flag
  src/sentry/conf/server.py
Labels: Scope: Backend

#60977 feat(icons): zoom in and out
  static/app/icons/iconZoom.tsx
  static/app/icons/index.tsx
Labels: Scope: Frontend

#61002 test(prism): Mock Prism in test env to prevent act warnings
  static/app/__mocks__/prismjs.tsx
  static/app/components/events/interfaces/request/index.spec.tsx
  static/app/components/onboarding/gettingStartedDoc/onboardingCodeSnippet.tsx
  static/app/utils/prism.tsx
  static/app/utils/usePrismTokens.spec.tsx
  static/app/utils/usePrismTokens.tsx
  static/app/views/onboarding/setupDocs.spec.tsx
Labels: Scope: Frontend

#61042 ref(feedback): Call `getIntegration` directly on hub
  static/app/components/feedback/widget/feedbackWidget.tsx
  static/app/components/profiling/profilingFeedbackButton.tsx
  static/app/views/monitors/components/cronsFeedbackButton.tsx
Labels: Scope: Frontend

#61021 chore(ppf): Remove old method of instantiating post process forwarder
  src/sentry/post_process_forwarder/__init__.py
  src/sentry/post_process_forwarder/post_process_forwarder.py
  tests/sentry/post_process_forwarder/test_post_process_forwarder.py
Labels: Scope: Backend

#61056 ref: remove PlanOut
  requirements-dev-frozen.txt
  requirements-frozen.txt
  requirements-getsentry.txt
Labels: Scope: Backend

#61050 ref: we only need a specific version of pip to do installs
  scripts/lib.sh
Labels: Scope: Backend

#61058 ref: use importlib.metadata instead of pkg_resources for internal packages api
  src/sentry/api/endpoints/internal/packages.py
Labels: Scope: Backend

#61016 ref: Remove TestStubs.Organization in favor of importing sentry-fixture/organization
  fixtures/js-stubs/types.tsx
  static/app/components/forms/fields/sentryMemberTeamSelectorField.spec.tsx
  static/app/utils/withDomainRedirect.spec.tsx
Labels: Scope: Frontend

#61004 fix(hybrid-cloud): Fix MS Teams Integration inference
  src/sentry/integrations/msteams/webhook.py
  src/sentry/middleware/integrations/parsers/msteams.py
  tests/sentry/middleware/integrations/parsers/test_msteams.py
Labels: Scope: Backend

#61063 ref(feedback): fix capitalization and mapping of integration names
  static/app/components/feedback/list/issueTrackingSignals.tsx
Labels: Scope: Frontend

#61065 nit(github): Remove search repo logger
  src/sentry/integrations/github/integration.py
Labels: Scope: Backend

#61003 feat(alerts): Skip snuba query on frequency filters for new issues
  src/sentry/rules/conditions/event_frequency.py
  tests/snuba/rules/conditions/test_event_frequency.py
Labels: Scope: Backend

#60983 feat(replays): Accept timestamp parameter when calculating accessibility issues
  src/sentry/replays/blueprints/api.md
  src/sentry/replays/constants.py
  src/sentry/replays/endpoints/project_replay_accessibility_issues.py
  src/sentry/replays/usecases/reader.py
  src/sentry/replays/usecases/segment.py
  tests/sentry/replays/test_project_replay_accessibility_issues.py
Labels: Scope: Backend

#60641 fix(discord): Update commands is hitting a rate limit error consistently
  src/sentry/integrations/discord/__init__.py
  src/sentry/integrations/discord/client.py
  src/sentry/integrations/discord/commands.py
  src/sentry/integrations/discord/integration.py
  tests/sentry/integrations/discord/test_integration.py
Labels: Scope: Backend

#61075 fix(alerts): Hide migration banner when creating/editing
  static/app/views/alerts/rules/metric/ruleForm.tsx
Labels: Scope: Frontend

#61072 ref(notifications): start removing notification_setting_type from code
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/codeowners_auto_sync.py
  src/sentry/notifications/notifications/missing_members_nudge.py
  src/sentry/notifications/notifications/organization_request/base.py
  src/sentry/notifications/notifications/rules.py
Labels: Scope: Backend

#61044 fix(webvitals): Web Vitals module minor fixes
  static/app/views/performance/browser/webVitals/components/pageOverviewSidebar.tsx
  static/app/views/performance/browser/webVitals/pageOverviewWebVitalsDetailPanel.tsx
  static/app/views/performance/browser/webVitals/pagePerformanceTable.tsx
  static/app/views/performance/browser/webVitals/webVitalsDetailPanel.tsx
Labels: Scope: Frontend

#61061 feat(stats-detectors): Add feature flag for stats detectors lifecycles
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/statistical_detectors/detector.py
Labels: Scope: Backend

#61077 feat(replay): Mark the Accessibility tab as Alpha for release to EA orgs
  static/app/views/replays/detail/layout/focusTabs.tsx
Labels: Scope: Frontend

#61076 feat(sdks): Upgrade to 7.85.0
  package.json
  static/app/components/feedback/widget/feedbackWidget.tsx
  static/app/components/profiling/profilingFeedbackButton.tsx
  static/app/utils/replays/replay.tsx
  static/app/views/monitors/components/cronsFeedbackButton.tsx
  yarn.lock
Labels: Scope: Frontend

#60947 chore(weekly-reports): log cleanup + explicitly set query limit for all orgs
  src/sentry/tasks/weekly_reports.py
Labels: Scope: Backend

#60915 chore(issues): Cleanup code for javascript console errors
  src/sentry/api/endpoints/organization_tags.py
  src/sentry/api/issue_search.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/test_issue_search.py
  tests/snuba/api/endpoints/test_organization_tags.py
Labels: Scope: Backend

#61080 ref(feedback): update feedback setup URL to link to docs
  static/app/components/feedback/feedbackSetupPanel.tsx
Labels: Scope: Frontend

#61067 chore(weekly-reports): flag cleanup
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#61012 feat(replay): Let the a11y analysis run at any point inside the replay
  static/app/utils/replays/hooks/useA11yData.tsx
  static/app/views/replays/detail/accessibility/accessibilityHeaderCell.tsx
  static/app/views/replays/detail/accessibility/accessibilityRefetchBanner.tsx
  static/app/views/replays/detail/accessibility/accessibilityTableCell.tsx
  static/app/views/replays/detail/accessibility/index.tsx
Labels: Scope: Frontend

#60738 feat(first-severity-escalation): Calculate and store escalation threshold
  src/sentry/conf/server.py
  src/sentry/issues/issue_velocity.py
  tests/sentry/issues/test_issue_velocity.py
Labels: Scope: Backend

#61091 nit(superuser): Remove unused function argument
  src/sentry/auth/superuser.py
Labels: Scope: Backend

#61090 [chore] Update casing inside of accessibilityRefetchBanner.tsx
  static/app/views/replays/detail/accessibility/accessibilityRefetchBanner.tsx
Labels: Scope: Frontend

#61010 ref(crons): Remove unneeded exc_info
  src/sentry/monitors/consumers/monitor_consumer.py
  tests/sentry/monitors/test_monitor_consumer.py
Labels: Scope: Backend

#61008 ref(crons): Track relay -> kafka delay
  src/sentry/monitors/consumers/monitor_consumer.py
Labels: Scope: Backend

#60988 feat(crons): Show date for check-ins in table
  static/app/views/monitors/components/monitorCheckIns.tsx
Labels: Scope: Frontend

#61024 feat(relay): Introduce options to global config
  src/sentry/api/endpoints/relay/project_configs.py
  src/sentry/relay/globalconfig.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v3.py
Labels: Scope: Backend

#61110 feat: Bump sentry sdk to 67c963d9c8d5e7e9de6347aee0edcf0c58d9fb24
  requirements-getsentry-overrides.txt
Labels: Scope: Backend

#61045 Improve ArtifactBundle (DB) Indexing
  fixtures/artifact_bundle_duplicated_debug_ids/manifest.json
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/debug_files/tasks.py
  src/sentry/models/artifactbundle.py
  src/sentry/tasks/assemble.py
  tests/sentry/debug_files/test_artifact_bundles.py
  tests/sentry/tasks/test_assemble.py
Labels: Scope: Backend

#61113 fix(ddm): Allow derived metrics in alerts with the metrics layer enabled
  src/sentry/search/events/builder/metrics.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
Labels: Scope: Backend

#61095 fix(replays): Parse timestamp as float
  src/sentry/replays/endpoints/project_replay_accessibility_issues.py
  src/sentry/replays/usecases/segment.py
  tests/sentry/replays/test_project_replay_accessibility_issues.py
Labels: Scope: Backend

#61123 ref: upgrade datadog client
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#61127 ref: fix typing for sentry.utils.query
  pyproject.toml
  src/sentry/utils/query.py
Labels: Scope: Backend

#61126 ref: fix typing for sentry.api.endpoints.organization_integration_repos
  pyproject.toml
  src/sentry/api/endpoints/organization_integration_repos.py
  src/sentry/integrations/mixins/repositories.py
Labels: Scope: Backend

#61088 feat(profiling): render initial differential flamegraph
  static/app/components/events/eventStatisticalDetector/eventDifferentialFlamegraph.tsx
  static/app/components/events/interfaces/spans/gapSpanDetails.tsx
  static/app/components/profiling/aggregateFlamegraphPanel.tsx
  static/app/components/profiling/flamegraph/aggregateFlamegraph.tsx
  static/app/components/profiling/flamegraph/deprecatedAggregateFlamegraph.tsx
  static/app/components/profiling/flamegraph/differentialFlamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphPreview.spec.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/utils/profiling/differentialFlamegraph.spec.tsx
  static/app/utils/profiling/differentialFlamegraph.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/hooks/useAggregateFlamegraphQuery.ts
  static/app/utils/profiling/hooks/useDifferentialFlamegraphQuery.ts
  static/app/utils/profiling/renderers/flamegraphTextRenderer.spec.tsx
  static/app/views/profiling/flamegraphProvider.tsx
  static/app/views/profiling/profileGroupProvider.tsx
  tests/js/sentry-test/profiling/utils.tsx
Labels: Scope: Frontend

#61051 fix(perf): Re-enable React profiler
  static/app/utils/performanceForSentry/index.tsx
Labels: Scope: Frontend

#61120 feat(profiling): use pre-generated colors in differential flamegraph
  static/app/components/events/eventStatisticalDetector/eventDifferentialFlamegraph.tsx
  static/app/components/profiling/flamegraph/aggregateFlamegraphTreeTable.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/differentialFlamegraph.spec.tsx
  static/app/utils/profiling/differentialFlamegraph.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/hooks/useAggregateFlamegraphQuery.ts
  static/app/utils/profiling/renderers/flamegraphRenderer.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer2D.tsx
  static/app/utils/profiling/renderers/flamegraphRendererDOM.tsx
  static/app/utils/profiling/renderers/flamegraphRendererWebGL.spec.tsx
  static/app/utils/profiling/renderers/shaders.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
Labels: Scope: Frontend

#61116 feat(ddm): Fix yAxis formatting
  static/app/utils.tsx
  static/app/utils/formatters.spec.tsx
  static/app/utils/formatters.tsx
  static/app/utils/metrics/index.spec.tsx
  static/app/utils/metrics/index.tsx
Labels: Scope: Frontend

#61084 ref(notifications): Remove NOTIFICATION_SETTINGS_ALL_SOMETIMES_V2
  src/sentry/notifications/defaults.py
  src/sentry/notifications/helpers.py
Labels: Scope: Backend

#61136 ref: clamp lower bound of deletion watermark to (min(id) - 1)
  src/sentry/tasks/deletion/hybrid_cloud.py
Labels: Scope: Backend

#61124 ref: fix typing for sentry.auth.access
  pyproject.toml
  src/sentry/auth/access.py
Labels: Scope: Backend

#61106 feat(relocation): Expand relocation model
  migrations_lockfile.txt
  src/sentry/migrations/0612_expand_relocation_model.py
  src/sentry/models/relocation.py
  src/sentry/tasks/relocation.py
  src/sentry/utils/relocation.py
Labels: Scope: Backend

#61097 ref: Refactor routerFixtures so they are in their own files for import
  fixtures/js-stubs/locationFixture.tsx
  fixtures/js-stubs/routeComponentPropsFixture.tsx
  fixtures/js-stubs/routerContextFixture.tsx
  fixtures/js-stubs/routerFixture.tsx
  fixtures/js-stubs/routerPropsFixture.tsx
  tests/js/setup.ts
Labels: Scope: Frontend

#61059 ref: upgrade pytest-django
  requirements-dev-frozen.txt
  requirements-dev.txt
  src/sentry/testutils/metrics_backend.py
  tests/sentry/sentry_metrics/test_kafka.py
Labels: Scope: Backend

#61134 fix(replays): Gracefully handle empty segment response
  src/sentry/replays/endpoints/project_replay_accessibility_issues.py
  src/sentry/replays/usecases/segment.py
  tests/sentry/replays/test_project_replay_accessibility_issues.py
Labels: Scope: Backend

#61086 feat(ai): add openai sdk integration to sentry sdk internally
  src/sentry/utils/openai_sdk_integration.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#61093 nit(superuser): Fix superuser mypy typing
  pyproject.toml
  src/sentry/auth/superuser.py
Labels: Scope: Backend

#61096 fix(webvitals): remove pagefilters isready check to remove potential stuck loading loop
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useProjectRawWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useTransactionRawWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useProjectWebVitalsScoresQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useTransactionWebVitalsScoresQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/useProjectWebVitalsTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/useProjectWebVitalsValuesTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/useTransactionSamplesWebVitalsQuery.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
Labels: Scope: Frontend

#61145 chore(app-start): Expose App Start in sidebar
  static/app/components/sidebar/index.tsx
  static/app/routes.tsx
  static/app/views/starfish/modules/mobile/appStartup.tsx
  static/app/views/starfish/modules/mobile/initialization.tsx
  static/app/views/starfish/utils/routeNames.tsx
Labels: Scope: Frontend

#59962 Fix(Redirection on deleting monitor): fixed redirection on deleting monitor
  static/app/views/monitors/components/cronsLandingPanel.tsx
  static/app/views/monitors/components/monitorCreateForm.tsx
  static/app/views/monitors/components/monitorHeader.tsx
  static/app/views/monitors/components/monitorHeaderActions.tsx
  static/app/views/monitors/create.tsx
  static/app/views/monitors/edit.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#61087 chore(team-selector): use "None" as placeholder text
  static/app/components/modals/inviteMembersModal/inviteRowControl.tsx
  static/app/components/modals/inviteMissingMembersModal/index.tsx
  static/app/views/settings/organizationMembers/inviteRequestRow.tsx
Labels: Scope: Frontend

#61155 fix(ui): align headings on invite members modal
  static/app/components/modals/inviteMembersModal/index.tsx
Labels: Scope: Frontend

#61153 fix(feedback): fix small bug in post-process logic
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#61057 Threshold status releases index
  static/app/views/releases/list/index.tsx
  static/app/views/releases/list/releaseCard/index.tsx
  static/app/views/releases/list/releaseCard/releaseCardProjectRow.tsx
  static/app/views/releases/utils/fetchThresholdStatus.tsx
  static/app/views/releases/utils/types.tsx
Labels: Scope: Frontend

#61152 fix(ai): switch to 16k token gpt 3.5 model
  src/sentry/api/endpoints/event_ai_suggested_fix.py
Labels: Scope: Backend

#61130 feat(profiling): add error and loading state
  static/app/components/events/eventStatisticalDetector/eventDifferentialFlamegraph.tsx
Labels: Scope: Frontend

#61102 fix(crons): Correct math on relay_kafka_delay metric
  src/sentry/monitors/consumers/monitor_consumer.py
Labels: Scope: Backend

#61160 docs(alerts): Clarify docs to restrict metric alerts to single project
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
Labels: Scope: Backend

#61163 ref: crons compatibility with stdlib timezone.utc
  src/sentry/monitors/tasks.py
Labels: Scope: Backend

#61066 ref(stats-detectors): Use top_events_timeseries function for stats
  src/sentry/tasks/statistical_detectors.py
  tests/sentry/tasks/test_statistical_detectors.py
Labels: Scope: Backend

#61156 feat(replays): Canvas feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#61166 docs(stories): Add an icon for files inside the storybook tree
  static/app/views/stories/storyTree.tsx
Labels: Scope: Frontend

#60843 Replace owners-ingest with team ingest
  .github/CODEOWNERS
  src/sentry/api/api_owners.py
Labels: Scope: Backend

#61133 feat(perf): Add release information to transaction event serializer
  src/sentry/api/endpoints/organization_event_details.py
  src/sentry/api/serializers/models/event.py
  tests/sentry/api/serializers/test_event.py
Labels: Scope: Backend

#61177 fix(replays): don't save sort query when going to selector table
  static/app/views/replays/tabs.tsx
Labels: Scope: Frontend

#61178 ref: upgrade to the latest django-stubs
  pyproject.toml
  requirements-dev-frozen.txt
  requirements-dev.txt
  src/sentry/services/hybrid_cloud/organization/impl.py
Labels: Scope: Backend

#61085 chore(hybrid-cloud): Relax logging for MS Teams request parser
  src/sentry/middleware/integrations/parsers/msteams.py
Labels: Scope: Backend

#61173 ref(database): Fetch full span info using `OrganizationEventDetailsEndpoint` instead of `EventJsonEndpoint`
  static/app/views/starfish/queries/useEventDetails.tsx
  static/app/views/starfish/queries/useFullSpanFromTrace.tsx
Labels: Scope: Frontend

#61107 feat(relocation): Enable pausing
  src/sentry/tasks/relocation.py
  src/sentry/utils/relocation.py
  tests/sentry/tasks/test_relocation.py
  tests/sentry/utils/test_relocation.py
Labels: Scope: Backend

#61168 feat(alerts): Allow alerts on span breakdown fields
  static/app/views/alerts/rules/metric/constants.tsx
  static/app/views/alerts/rules/metric/metricField.tsx
Labels: Scope: Frontend

#61129 ref: fix typing for AggregateFilter.key
  pyproject.toml
  src/sentry/api/event_search.py
Labels: Scope: Backend

#61100 ref(crons): Remove new onboarding panel feature flag
  static/app/views/monitors/components/cronsLandingPanel.tsx
Labels: Scope: Frontend

#60073 feat(accounting): Add bigtable accounting
  src/sentry/conf/server.py
  src/sentry/event_manager.py
  src/sentry/usage_accountant/accountant.py
  tests/sentry/event_manager/test_event_manager.py
Labels: Scope: Backend

#61131 ref: fix typing for sentry.rules.history.endpoints
  pyproject.toml
  src/sentry/rules/history/endpoints/project_rule_group_history.py
  src/sentry/rules/history/endpoints/project_rule_stats.py
Labels: Scope: Backend

#61180 fix(api) Don't use deprecated get_raw_uri
  src/sentry/middleware/subdomain.py
Labels: Scope: Backend

#61172 fix(hybridcloud) Omit control outbox delivery from cron monitoring
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#61174 feat(profiling): use different tooltip per chart type
  static/app/components/profiling/flamegraph/flamegraphPreview.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
Labels: Scope: Frontend

#61150 feat(profiling): add txn pagination to toolbar
  static/app/components/events/eventStatisticalDetector/eventDifferentialFlamegraph.tsx
Labels: Scope: Frontend

#61146 feat(profiling) add transaction and % change text above toolbar
  static/app/components/events/eventStatisticalDetector/eventDifferentialFlamegraph.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#61184 ref: upgrade to latest drf-stubs
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#60342 feat(crons): Add QuotaConfig for check-in rate-limits
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/monitors/models.py
  src/sentry/monitors/rate_limit.py
  src/sentry/quotas/base.py
  src/sentry/quotas/redis.py
  tests/sentry/monitors/test_rate_limit.py
  tests/sentry/quotas/test_redis.py
Labels: Scope: Backend

#61182 ref(replays): migrate javascript and react onboarding docs
  static/app/components/onboarding/gettingStartedDoc/layout.tsx
  static/app/components/onboarding/gettingStartedDoc/sdkDocumentation.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/gettingStartedDocs/replay-onboarding/javascript/javascript.tsx
  static/app/gettingStartedDocs/replay-onboarding/javascript/react.tsx
Labels: Scope: Frontend

#61175 bug(feedback): Pass the number of `hits` into the Infinite Loader so that we load all pages of data
  static/app/components/feedback/list/feedbackList.tsx
  static/app/components/feedback/useFeedbackListQueryKey.tsx
  static/app/components/feedback/useFetchFeedbackInfiniteListData.tsx
  static/app/utils/queryClient.tsx
Labels: Scope: Frontend

#61187 ref: fix regex simplification in drf path generation for django 4.x
  src/sentry/apidocs/api_publish_status_allowlist_dont_modify.py
  src/sentry/apidocs/hooks.py
  src/sentry/conf/server.py
Labels: Scope: Backend

#61108 feat(relocation): Track emails sent on relocation
  src/sentry/tasks/relocation.py
  src/sentry/utils/relocation.py
  tests/sentry/tasks/test_relocation.py
  tests/sentry/utils/test_relocation.py
Labels: Scope: Backend

#61140 feat(profiling): add differential flamegraph toolbar
  static/app/components/events/eventStatisticalDetector/eventDifferentialFlamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/differentialFlamegraphNegationSwitch.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/differentialFlamegraphToolbar.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphOptionsMenu.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#61083 ref(notifications): use new types for notification validators
  src/sentry/api/validators/notifications.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/types.py
  src/sentry/notifications/validators.py
  tests/sentry/notifications/test_helpers.py
Labels: Scope: Backend

#61082 feat(severity): Pass has_escalated to RuleProcessor
  src/sentry/rules/base.py
  src/sentry/rules/processor.py
  src/sentry/tasks/post_process.py
  src/sentry/testutils/cases.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#61196 ref: ignore django 5.x warnings until we are on 4.x
  pyproject.toml
Labels: Scope: Backend

#61185 ref(grouping): add missing SDK tag in ingest
  src/sentry/event_manager.py
  src/sentry/issues/ingest.py
  src/sentry/utils/tag_normalization.py
  tests/sentry/issues/test_ingest.py
  tests/sentry/utils/test_tag_normalization.py
Labels: Scope: Backend
