Repository getsentry/sentry, pull requests merged in 2023-01, with the labels that each got.

#42579 feat: Arroyo 2.3.1
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#42667 feat(profiling): add some depth offset to spans
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
Labels: Scope: Frontend

#42666 feat(profiling): wire up span interactions and tooltip
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#42662 ref(profiling): optimize rerendering
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphLayout.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphThreadSelector.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphViewSelectMenu.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/components/profiling/profileHeader.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphQueryParamSync.tsx
  static/app/utils/useUndoableReducer.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.spec.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.tsx
  static/app/views/profiling/profileFlamechart.tsx
  static/app/views/profiling/profileGroupProvider.tsx
  static/app/views/profiling/utils.tsx
Labels: Scope: Frontend

#42633 feat(profiling): generate stable color palette for spans
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/canvasView.spec.tsx
  static/app/utils/profiling/canvasView.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/flamegraphDomRenderer.spec.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer.spec.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanChart.spec.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#42628 feat(profiling): break ties on parent_span_id edge
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/canvasView.spec.tsx
  static/app/utils/profiling/canvasView.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/flamegraphDomRenderer.spec.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer.spec.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanChart.spec.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.spec.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#42598 feat(profiling): initialize span space
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/canvasView.spec.tsx
  static/app/utils/profiling/canvasView.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/flamegraphDomRenderer.spec.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer.spec.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanChart.spec.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.spec.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#42595 feat(profiling): listen for span canvas size changes
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/utils/profiling/canvasView.spec.tsx
  static/app/utils/profiling/canvasView.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/flamegraphDomRenderer.spec.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer.spec.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanChart.spec.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.spec.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#42614 ref(perf-issues): Remove unused `PerformanceSpanProblem` class
  src/sentry/utils/performance_issues/performance_detection.py
  src/sentry/utils/performance_issues/performance_span_issue.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
  tests/sentry/utils/performance_issues/test_slow_span_detector.py
Labels: Scope: Backend

#42706 fix(all-events): error state cannot be removed
  static/app/views/organizationGroupDetails/allEventsTable.tsx
Labels: Scope: Frontend

#42690 fix(crons): Match permissions on the checkin details endpoint
  src/sentry/api/endpoints/monitor_checkin_details.py
Labels: Scope: Backend

#42720 feat(profiling): add rust onboarding support
  static/app/components/profiling/ProfilingOnboarding/util.ts
Labels: Scope: Frontend

#42256 fix(profiling): Fix frames disappearing from profile
  src/sentry/profiles/task.py
  tests/sentry/profiles/test_task.py
Labels: Scope: Backend

#42575 feat(perf): Close the transaction searchbar when clicked outside of
  static/app/components/performance/searchBar.spec.tsx
  static/app/components/performance/searchBar.tsx
Labels: Scope: Frontend

#42574 ref(digests): Add generic issues to debug view and tests
  fixtures/emails/digest.txt
  src/sentry/web/frontend/debug/debug_generic_issue.py
  src/sentry/web/frontend/debug/mail.py
  tests/sentry/notifications/notifications/test_digests.py
Labels: Scope: Backend

#42689 ref(crons): Add MonitorCheckIn to cleanup.py
  src/sentry/runner/commands/cleanup.py
Labels: Scope: Backend

#42588 fix(jira): Fix assignee outbound sync
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/jira_server/integration.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/integrations/jira/test_integration.py
  tests/sentry/integrations/jira_server/test_integration.py
Labels: Scope: Backend

#42509 bug(replays): Fetch errors on Replay Details in chunks
  static/app/utils/replays/hooks/useReplayData.tsx
Labels: Scope: Frontend

#42403 ref(hybrid-cloud): add organization_slug to GroupParticipants
  src/sentry/api/endpoints/group_participants.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_group_participants.py
Labels: Scope: Backend

#42677 feat(hybrid-cloud): Move Identity to Control and implement IdentityService
  src/sentry/integrations/notifications.py
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/integrations/slack/requests/base.py
  src/sentry/integrations/slack/webhooks/action.py
  src/sentry/integrations/slack/webhooks/command.py
  src/sentry/models/groupassignee.py
  src/sentry/models/identity.py
  src/sentry/models/organization.py
  src/sentry/models/organizationmember.py
  src/sentry/services/hybrid_cloud/identity/__init__.py
  src/sentry/services/hybrid_cloud/identity/impl.py
  tests/sentry/db/test_silo_models.py
  tests/sentry/models/test_identity.py
Labels: Scope: Backend

#42674 fix(workflow): Remove metrics-performance flags
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#42024 feat(indexer): Consumer builder using routing strategy
  src/sentry/conf/server.py
  src/sentry/runner/commands/run.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/sentry_metrics/consumers/indexer/common.py
  src/sentry/sentry_metrics/consumers/indexer/parallel.py
  src/sentry/sentry_metrics/consumers/indexer/processing.py
  src/sentry/sentry_metrics/consumers/indexer/routing_producer.py
  src/sentry/sentry_metrics/consumers/indexer/slicing_router.py
  tests/sentry/sentry_metrics/consumers/test_routing_producer.py
  tests/sentry/sentry_metrics/consumers/test_slicing_router.py
  tests/sentry/sentry_metrics/test_batch.py
  tests/sentry/sentry_metrics/test_parallel_indexer.py
Labels: Scope: Backend

#42732 Revert "fix(profiling): Fix frames disappearing from profile"
  src/sentry/profiles/task.py
  tests/sentry/profiles/test_task.py
Labels: Scope: Backend

#42731 fix(profiling): Selected frame renderer incorrect width
  static/app/utils/profiling/renderers/selectedFrameRenderer.spec.tsx
  static/app/utils/profiling/renderers/selectedFrameRenderer.tsx
Labels: Scope: Frontend

#42734 Revert "bug(replays): Trust the Replay api response `duration` field …
  static/app/utils/replays/replayDataUtils.tsx
  static/app/utils/replays/replayReader.tsx
Labels: Scope: Frontend

#42735 fix(profiling): messaging for undefined platform
  static/app/components/profiling/ProfilingOnboarding/proflingOnboardingSidebar.tsx
Labels: Scope: Frontend

#42558 feat(replays): Implement isHovered states for DOM and Network tabs
  static/app/utils/replays/hooks/useCrumbHandlers.tsx
  static/app/views/replays/detail/domMutations/index.tsx
  static/app/views/replays/detail/focusArea.tsx
  static/app/views/replays/detail/network/index.tsx
Labels: Scope: Frontend

#42728 ref(hybrid-cloud): use monitor urls with org slug frontend
  static/app/views/monitors/details.tsx
  static/app/views/monitors/monitorCheckIns.tsx
  static/app/views/monitors/monitorStats.tsx
Labels: Scope: Frontend

#42722 ref(js): Minor cleanup to Button
  static/app/components/button.tsx
Labels: Scope: Frontend

#42738 bug(replays): Do not suppress MessageRejected error
  src/sentry/replays/lib/consumer.py
Labels: Scope: Backend

#42741 ref(js): Simplify form source require regex
  static/app/actionCreators/formSearch.tsx
Labels: Scope: Frontend

#42742 style(js): Fix comment wording on form field types
  static/app/components/forms/field/types.tsx
Labels: Scope: Frontend

#42726 fix(checkbox): Remove hover/active states when disabled
  static/app/components/checkbox.tsx
Labels: Scope: Frontend

#42745 fix(ui): Django templating leaking into HTML
  src/sentry/templates/sentry/integrations/slack/expired-link.html
Labels: Scope: Backend

#42736 feat(workflow): Remove release activity endpoint
  mypy.ini
  src/sentry/api/endpoints/project_release_activity.py
  src/sentry/api/serializers/models/__init__.py
  src/sentry/api/serializers/models/releaseactivity.py
  src/sentry/api/urls.py
  src/sentry/models/deploy.py
  src/sentry/receivers/releases.py
  tests/sentry/api/endpoints/test_project_release_activity.py
  tests/sentry/receivers/test_releases.py
Labels: Scope: Backend

#42748 ref(js): Some fixup to avatarCropper
  static/app/components/avatarCropper.tsx
Labels: Scope: Frontend

#42746 fix(js): Default `type="button"` for buttons
  static/app/components/actions/resolve.tsx
  static/app/components/activity/note/input.tsx
  static/app/components/avatarChooser.tsx
  static/app/components/button.tsx
  static/app/components/compactSelect.tsx
  static/app/components/customCommitsResolutionModal.tsx
  static/app/components/customIgnoreCountModal.tsx
  static/app/components/customIgnoreDurationModal.tsx
  static/app/components/customResolutionModal.tsx
  static/app/components/deprecatedforms/form.tsx
  static/app/components/dropdownButton.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
  static/app/components/events/interfaces/frame/stacktraceLinkModal.tsx
  static/app/components/events/traceEventDataSection.tsx
  static/app/components/forms/fields/projectMapperField.tsx
  static/app/components/forms/form.tsx
  static/app/components/forms/formField/index.tsx
  static/app/components/group/ownedBy.tsx
  static/app/components/loadingError.tsx
  static/app/components/modals/widgetViewerModal.tsx
  static/app/components/pagination.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphSearch.tsx
  static/app/components/projects/missingProjectMembership.tsx
  static/app/components/searchBar.tsx
  static/app/components/teamSelector.tsx
  static/app/components/textCopyInput.tsx
  static/app/views/admin/adminUserEdit.tsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/issue/ruleNode.tsx
  static/app/views/alerts/rules/metric/details/relatedIssuesNotAvailable.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/triggers/actionsPanel/deleteActionButton.tsx
  static/app/views/alerts/rules/metric/triggers/actionsPanel/index.tsx
  static/app/views/organizationGroupDetails/actions/index.tsx
  static/app/views/organizationGroupDetails/actions/shareIssue.tsx
  static/app/views/organizationGroupDetails/actions/shareModal.tsx
  static/app/views/organizationGroupDetails/groupTagValues.tsx
  static/app/views/organizationIntegrations/sentryAppDetailedView.tsx
  static/app/views/projectInstall/createProject.tsx
  static/app/views/settings/account/accountSecurity/components/u2fEnrolledDetails.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryFunctionsEnvironmentVariables.tsx
  static/app/views/settings/project/projectFilters/groupTombstones.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
  static/app/views/settings/project/projectOwnership/addCodeOwnerModal.tsx
  static/app/views/settings/project/projectReleaseTracking.tsx
  static/app/views/settings/projectGeneralSettings.tsx
  static/app/views/settings/projectIssueGrouping/upgradeGrouping.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#42749 feat(issue-details): Hide suggested assignees when already assigned
  static/app/components/group/suggestedOwners/suggestedOwners.spec.jsx
  static/app/components/group/suggestedOwners/suggestedOwners.tsx
Labels: Scope: Frontend

#42751 fix(ui): Re-enable performance issue query fields
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#42753 fix(issue-details): Fix right padding in suggested assignee button
  static/app/components/group/suggestedOwners/suggestedAssignees.tsx
Labels: Scope: Frontend

#42713 ref(metrics): Improve and standardize metrics test suite
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/release_health/test_metrics_sessions_v2.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_release_health.py
Labels: Scope: Backend

#42733 ref(span-tree): Use `useEffect` instead of `useLayoutEffect`
  static/app/components/events/interfaces/spans/spanTree.tsx
Labels: Scope: Frontend

#42740 ref(profiling): add content spacing and adjust markup in profilingOnboardingSidebar
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingSidebar.tsx
  static/app/components/sidebar/index.tsx
Labels: Scope: Frontend

#42743 fix(profiling): KeyError in symbolicated profiles
  src/sentry/profiles/task.py
  tests/sentry/profiles/test_task.py
Labels: Scope: Backend

#42398 ref(analytics): convert savedquery utils analytics
  static/app/utils/analytics/discoverAnalyticsEvents.tsx
  static/app/views/eventsV2/savedQuery/utils.tsx
Labels: Scope: Frontend

#42756 fix(workflow): Alert not triggered yet copy
  static/app/views/alerts/list/rules/row.tsx
Labels: Scope: Frontend

#42747 ref(crons): Remove feature flag check from endpoints and tests
  src/sentry/api/bases/monitor.py
  src/sentry/api/endpoints/monitor_checkin_details.py
  src/sentry/api/endpoints/organization_monitors.py
  tests/sentry/api/endpoints/test_monitor_checkin_details.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
  tests/sentry/api/endpoints/test_monitor_details.py
  tests/sentry/api/endpoints/test_organization_monitors.py
Labels: Scope: Backend

#42765 feat(profiling): add span messaging
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42757 ref(profiling): dry up more interactions
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasZoomOrScroll.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.spec.ts
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.ts
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42721 ref(profiling): dry up interaction handlers
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasZoomOrScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useDrawHoveredBorderEffect.tsx
  static/app/components/profiling/flamegraph/interactions/useDrawSelectedBorderEffect.tsx
  static/app/components/profiling/flamegraph/interactions/useInteractionViewCheckPoint.tsx
  static/app/components/profiling/flamegraph/interactions/useWheelCenterZoom.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.spec.ts
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.ts
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42717 feat(profiling): wire up span interactions
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/flamegraphTreeTable.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasZoomOrScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useDrawHoveredBorderEffect.tsx
  static/app/components/profiling/flamegraph/interactions/useDrawSelectedBorderEffect.tsx
  static/app/components/profiling/flamegraph/interactions/useInteractionViewCheckPoint.tsx
  static/app/components/profiling/flamegraph/interactions/useWheelCenterZoom.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.spec.ts
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
  static/app/utils/profiling/units/units.ts
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42754 ref(resolveButton): Use a lighter divider
  static/app/components/actions/resolve.tsx
Labels: Scope: Frontend

#42750 fix(alerts): Fix message for percent of sessions issue alert
  static/app/views/alerts/rules/issue/details/textRule.spec.tsx
  static/app/views/alerts/rules/issue/details/textRule.tsx
Labels: Scope: Frontend

#42696 fix(test): Fix flaky performance issue email test
  src/sentry/web/frontend/debug/mail.py
  tests/acceptance/test_emails.py
Labels: Scope: Backend

#42768 feat(perf-issues): Add feature flag for slow db span issue
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#42718 ref(perf-issues): Simplify performance problem iteration
  src/sentry/utils/performance_issues/performance_detection.py
  src/sentry/utils/performance_issues/performance_problem.py
Labels: Scope: Backend

#42590 ref(hybrid-cloud): Additional api endpoint tests
  src/django_picklefield/fields.py
  src/sentry/api/endpoints/auth_index.py
  src/sentry/api/endpoints/group_integration_details.py
  src/sentry/api/endpoints/group_notes.py
  src/sentry/api/endpoints/group_notes_details.py
  src/sentry/api/endpoints/grouping_level_new_issues.py
  src/sentry/api/endpoints/grouping_levels.py
  src/sentry/api/endpoints/index.py
  src/sentry/api/endpoints/integration_features.py
  src/sentry/api/endpoints/internal/beacon.py
  src/sentry/api/endpoints/issue_occurrence.py
  src/sentry/api/serializers/models/grouptombstone.py
  src/sentry/api/serializers/rest_framework/mentions.py
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/mixins/issues.py
  src/sentry/middleware/locale.py
  src/sentry/models/options/user_option.py
  src/sentry/models/user.py
  src/sentry/notifications/utils/participants.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/services/hybrid_cloud/user/impl.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/modelmanifest.py
  tests/sentry/api/endpoints/test_group_integration_details.py
  tests/sentry/api/endpoints/test_group_notes.py
  tests/sentry/api/endpoints/test_group_notes_details.py
  tests/sentry/api/endpoints/test_group_stats.py
  tests/sentry/api/endpoints/test_group_suspect_releases.py
  tests/sentry/api/endpoints/test_group_tagkey_details.py
  tests/sentry/api/endpoints/test_group_tagkey_values.py
  tests/sentry/api/endpoints/test_group_tags.py
  tests/sentry/api/endpoints/test_group_tombstone.py
  tests/sentry/api/endpoints/test_group_tombstone_details.py
  tests/sentry/api/endpoints/test_group_user_reports.py
  tests/sentry/api/endpoints/test_grouping_levels.py
  tests/sentry/api/endpoints/test_index.py
  tests/sentry/api/endpoints/test_integration_features.py
  tests/sentry/api/endpoints/test_internal_beacon.py
  tests/sentry/api/serializers/test_group_tombstone.py
  tests/sentry/mail/activity/test_note.py
Labels: Scope: Backend, trigger-getsentry-external

#42730 Use a copy of events to prevent shuffle errors
  src/sentry/testutils/performance_issues/event_generators.py
  tests/sentry/api/serializers/test_event.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/utils/performance_issues/test_consecutive_db_detector.py
  tests/sentry/utils/performance_issues/test_file_io_on_main_thread_detector.py
  tests/sentry/utils/performance_issues/test_m_n_plus_one_db_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_db_span_detector.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
  tests/sentry/utils/performance_issues/test_slow_span_detector.py
  tests/sentry/web/frontend/test_newest_performance_issue.py
Labels: Scope: Backend

#42772 feat(alerts): Add GA default for Active Members fallback option
  src/sentry/notifications/utils/participants.py
  tests/sentry/notifications/utils/test_participants.py
Labels: Scope: Backend

#42769 feat(perf): Add ability to scroll horizontally on transaction trace view
  static/app/views/performance/traceDetails/transactionBar.tsx
  static/app/views/performance/traceDetails/transactionGroup.tsx
Labels: Scope: Frontend

#42776 fix(all-events): Ensure pagination caption is always correct
  static/app/views/organizationGroupDetails/allEventsTable.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.spec.tsx
  static/app/views/performance/transactionSummary/transactionEvents/content.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.spec.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
  static/app/views/performance/transactionSummary/transactionEvents/index.tsx
Labels: Scope: Frontend

#42782 fix(ui): Make sudo modal COPS/CSM Button a submit button
  static/app/components/modals/sudoModal.tsx
  static/app/components/superuserAccessForm.tsx
Labels: Scope: Frontend

#42786 fix(issue-occurrence): Auto create occurrence ingest topic
  src/sentry/issues/occurrence_consumer.py
Labels: Scope: Backend

#42790 Revert "ref(hybrid-cloud): use organization_slug in org invite link url"
  fixtures/emails/invitation.txt
  src/sentry/api/endpoints/accept_organization_invite.py
  src/sentry/models/organizationmember.py
  src/sentry/web/frontend/debug/mail.py
Labels: Scope: Backend

#42791 fix(crons): Match permissions on the checkin details endpoint v2
  src/sentry/api/endpoints/monitor_checkin_details.py
Labels: Scope: Backend

#42775 ref(audit): Clean up utils/audit.py
  mypy.ini
  src/sentry/utils/audit.py
Labels: Scope: Backend

#42688 ref(profiling): allow rendering on any axis
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/flamegraphTreeTable.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomView.tsx
  static/app/components/profiling/flamegraph/flamegraphZoomViewMinimap.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasZoomOrScroll.tsx
  static/app/components/profiling/flamegraph/interactions/useDrawHoveredBorderEffect.tsx
  static/app/components/profiling/flamegraph/interactions/useDrawSelectedBorderEffect.tsx
  static/app/components/profiling/flamegraph/interactions/useInteractionViewCheckPoint.tsx
  static/app/components/profiling/flamegraph/interactions/useWheelCenterZoom.tsx
  static/app/utils/profiling/canvasScheduler.tsx
  static/app/utils/profiling/canvasView.spec.tsx
  static/app/utils/profiling/canvasView.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph.ts
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.spec.ts
  static/app/utils/profiling/flamegraph/flamegraphKeyboardNavigation.ts
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/flamegraphRenderer.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/renderers/textRenderer.tsx
  static/app/utils/profiling/spanChart.tsx
  static/app/utils/profiling/spanTree.tsx
  static/app/utils/profiling/units/units.ts
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42783 fix(ui): Alignment on Remove button in Sentry App Tokens panel
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.tsx
Labels: Scope: Frontend

#42802 ref(hybrid-cloud): User Options and several tests marked for hybrid cloud
  src/django_picklefield/fields.py
  src/sentry/api/endpoints/auth_index.py
  src/sentry/api/endpoints/group_integration_details.py
  src/sentry/api/endpoints/group_notes.py
  src/sentry/api/endpoints/group_notes_details.py
  src/sentry/api/endpoints/grouping_level_new_issues.py
  src/sentry/api/endpoints/grouping_levels.py
  src/sentry/api/endpoints/index.py
  src/sentry/api/endpoints/integration_features.py
  src/sentry/api/endpoints/internal/beacon.py
  src/sentry/api/endpoints/issue_occurrence.py
  src/sentry/api/serializers/models/grouptombstone.py
  src/sentry/api/serializers/rest_framework/mentions.py
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/mixins/issues.py
  src/sentry/middleware/locale.py
  src/sentry/models/options/user_option.py
  src/sentry/notifications/utils/participants.py
  src/sentry/receivers/releases.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/services/hybrid_cloud/user/impl.py
  src/sentry/services/hybrid_cloud/user_option/__init__.py
  src/sentry/services/hybrid_cloud/user_option/impl.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/modelmanifest.py
  src/sentry/utils/email/manager.py
  tests/sentry/api/endpoints/test_group_integration_details.py
  tests/sentry/api/endpoints/test_group_notes.py
  tests/sentry/api/endpoints/test_group_notes_details.py
  tests/sentry/api/endpoints/test_group_stats.py
  tests/sentry/api/endpoints/test_group_suspect_releases.py
  tests/sentry/api/endpoints/test_group_tagkey_details.py
  tests/sentry/api/endpoints/test_group_tagkey_values.py
  tests/sentry/api/endpoints/test_group_tags.py
  tests/sentry/api/endpoints/test_group_tombstone.py
  tests/sentry/api/endpoints/test_group_tombstone_details.py
  tests/sentry/api/endpoints/test_group_user_reports.py
  tests/sentry/api/endpoints/test_grouping_levels.py
  tests/sentry/api/endpoints/test_index.py
  tests/sentry/api/endpoints/test_integration_features.py
  tests/sentry/api/endpoints/test_internal_beacon.py
  tests/sentry/api/serializers/test_group_tombstone.py
  tests/sentry/hybrid_cloud/test_user_option.py
  tests/sentry/integrations/bitbucket/test_issues.py
  tests/sentry/mail/activity/test_note.py
Labels: Scope: Backend

#42779 fix(domains) Don't use params.orgId in settings views
  static/app/views/settings/organizationApiKeys/index.tsx
  static/app/views/settings/organizationApiKeys/organizationApiKeyDetails.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.spec.jsx
  static/app/views/settings/organizationMembers/organizationMembersList.tsx
  static/app/views/settings/organizationTeams/teamMembers.tsx
  static/app/views/settings/project/projectEnvironments.spec.jsx
  static/app/views/settings/project/projectEnvironments.tsx
  static/app/views/settings/project/projectFilters/index.spec.jsx
  static/app/views/settings/project/projectFilters/index.tsx
  static/app/views/settings/project/projectFilters/projectFiltersChart.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
  static/app/views/settings/project/projectKeys/details/index.spec.jsx
  static/app/views/settings/project/projectKeys/details/index.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.tsx
  static/app/views/settings/project/projectKeys/list/index.spec.jsx
  static/app/views/settings/project/projectKeys/list/index.tsx
  static/app/views/settings/project/projectServiceHookDetails.tsx
  static/app/views/settings/project/projectSettingsLayout.tsx
  static/app/views/settings/project/projectTeams.spec.jsx
  static/app/views/settings/project/projectTeams.tsx
  static/app/views/settings/projectAlerts/settings.tsx
  static/app/views/settings/projectDataForwarding.tsx
  static/app/views/settings/projectIssueGrouping/index.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
  static/app/views/settings/projectPlugins/details.tsx
  static/app/views/settings/projectPlugins/projectPlugins.spec.tsx
  static/app/views/settings/projectPlugins/projectPlugins.tsx
  static/app/views/settings/projectSourceMaps/list/index.tsx
Labels: Scope: Frontend

#42798 ref(replays): Refactor Transaction counts to use new /replay-count/ endpoint
  static/app/components/replays/useReplaysCount.spec.tsx
  static/app/components/replays/useReplaysCount.tsx
  static/app/views/performance/transactionSummary/transactionReplays/index.spec.tsx
Labels: Scope: Frontend

#42815 fix(flamechart): prevent browser nav
  static/app/components/profiling/flamegraph/interactions/useCanvasZoomOrScroll.tsx
Labels: Scope: Frontend

#41876 feat(workflow): Hide issue alert fallthrough setting w/ flag
  static/app/views/settings/project/projectOwnership/index.spec.jsx
  static/app/views/settings/project/projectOwnership/index.tsx
Labels: Status: Stale, Scope: Frontend

#42217 (perf-issues) add time saving function to consecutive db detector
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_consecutive_db_detector.py
Labels: Scope: Backend

#42812 ref(perf): Delete unified span view flag
  static/app/components/events/interfaces/spans/spanBar.tsx
  static/app/components/events/interfaces/spans/traceView.spec.tsx
Labels: Scope: Frontend

#42813 ref(perf): Delete unified span view flag backend
  src/sentry/features/__init__.py
Labels: Scope: Backend

#42682 ref(tests): Refactor Slack activity tests
  src/sentry/testutils/cases.py
  tests/sentry/integrations/slack/notifications/test_assigned.py
  tests/sentry/integrations/slack/notifications/test_issue_alert.py
  tests/sentry/integrations/slack/notifications/test_note.py
  tests/sentry/integrations/slack/notifications/test_regression.py
  tests/sentry/integrations/slack/notifications/test_resolved.py
  tests/sentry/integrations/slack/notifications/test_resolved_in_release.py
  tests/sentry/integrations/slack/notifications/test_unassigned.py
Labels: Scope: Backend

#42820 Revert "ref(hybrid-cloud): use monitor urls with org slug frontend"
  static/app/views/monitors/details.tsx
  static/app/views/monitors/monitorCheckIns.tsx
  static/app/views/monitors/monitorStats.tsx
Labels: Scope: Frontend

#29135 ref(js): useLegacyStore for GlobalModal
  static/app/components/events/interfaces/debugMeta/debugImageDetails/index.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLinkModal.spec.tsx
  static/app/components/featureFeedback/feedbackModal.spec.tsx
  static/app/components/globalModal/index.spec.jsx
  static/app/components/globalModal/index.tsx
  static/app/components/group/sentryAppExternalIssueActions.spec.jsx
  static/app/components/modals/demoEndModal.spec.tsx
  static/app/components/modals/redirectToProject.spec.tsx
  static/app/components/modals/suggestProjectModal.spec.tsx
  static/app/views/organizationGroupDetails/actions/shareModal.spec.tsx
  static/app/views/organizationIntegrations/integrationCodeMappings.spec.jsx
  static/app/views/settings/account/accountClose.spec.jsx
  static/app/views/settings/organizationDeveloperSettings/index.spec.jsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Status: In Progress, Scope: Frontend

#42822 feat(perf-issues): Add N+1 API Calls detector system options to management UI
  static/app/views/admin/adminSettings.tsx
  static/app/views/admin/options.tsx
Labels: Scope: Frontend

#42808 fix(perf-issues): fix off-by-one issue in MN+1 detection
  fixtures/events/performance_problems/m-n-plus-one-db/m-n-plus-one-off-by-one.json
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_m_n_plus_one_db_detector.py
Labels: Scope: Backend

#42801 fix(checkbox): Remove border when checked to improve aliasing
  static/app/components/checkbox.tsx
Labels: Scope: Frontend

#42827 fix(profiling): fix grid span row size
  static/app/components/profiling/flamegraph/flamegraphLayout.tsx
Labels: Scope: Frontend

#42819 feat: Support latest identifier on checkins
  src/sentry/api/base.py
  src/sentry/api/bases/organization_events.py
  src/sentry/api/endpoints/monitor_checkin_details.py
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/testutils/cases.py
  tests/sentry/api/bases/test_endpoint.py
  tests/sentry/api/endpoints/test_monitor_checkin_details.py
  tests/sentry/api/endpoints/test_monitor_checkins.py
  tests/sentry/api/test_base.py
Labels: Scope: Backend

#42834 ref(ts): Fix re-exporting types `InputProps`, `TextAreaProp`
  static/app/components/inputGroup.tsx
Labels: Scope: Frontend

#42830 ref(theme): Avoid exporting Theme (use @emotion/react)
  static/app/utils/theme.tsx
Labels: Scope: Frontend

#42839 ref(js): Remove unused `get` in modalStore
  static/app/stores/modalStore.tsx
Labels: Scope: Frontend

#42841 chore(js): Rename Field to FieldGroup
  docs-ui/stories/components/panels.stories.js
  static/app/components/confirmDelete.tsx
  static/app/components/featureFeedback/feedbackModal.tsx
  static/app/components/forms/field/index.tsx
  static/app/components/forms/fields/blankField.tsx
  static/app/components/forms/formField/index.tsx
  static/app/components/modals/debugFileCustomRepository/appStoreConnect/stepOne.tsx
  static/app/components/modals/debugFileCustomRepository/http.tsx
  static/app/components/radioGroupRating.tsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/metric/triggers/form.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/columnFields.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/filterResultsStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/groupByStep/groupBySelector.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/sortByStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/yAxisStep/yAxisSelector/index.tsx
  static/app/views/integrationOrganizationLink.tsx
  static/app/views/monitors/monitorForm.tsx
  static/app/views/performance/transactionSummary/transactionThresholdModal.tsx
  static/app/views/sentryAppExternalInstallation.tsx
  static/app/views/settings/account/accountSecurity/accountSecurityEnroll.tsx
  static/app/views/settings/account/accountSecurity/index.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/eventIdField.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/index.tsx
  static/app/views/settings/organizationGeneralSettings/index.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/organizationRateLimits/organizationRateLimits.tsx
  static/app/views/settings/organizationRelay/modals/form.tsx
  static/app/views/settings/organizationTeams/teamSettings/index.tsx
  static/app/views/settings/project/dynamicSampling/samplingFeedback.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.tsx
  static/app/views/settings/project/projectKeys/projectKeyCredentials.tsx
  static/app/views/settings/project/projectReleaseTracking.tsx
  static/app/views/settings/project/projectServiceHookDetails.tsx
  static/app/views/settings/project/projectServiceHooks.tsx
  static/app/views/settings/projectGeneralSettings.tsx
  static/app/views/settings/projectIssueGrouping/upgradeGrouping.tsx
  static/app/views/settings/projectSecurityHeaders/reportUri.tsx
Labels: Scope: Frontend

#42842 bug(replays): Quote transaction names when doing a query for replay counts
  static/app/components/replays/useReplaysCount.spec.tsx
  static/app/components/replays/useReplaysCount.tsx
Labels: Scope: Frontend

#42847 feat(crons): Cron monitor detail page view analytics
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#42853 fix(workflow): Stacktrace value could be an object and error
  static/app/components/events/interfaces/keyValueList/index.tsx
Labels: Scope: Frontend

#42855 ref(js): Remove `form` Button priority
  static/app/components/button.tsx
  static/app/components/demo/demoHeader.tsx
  static/app/components/dropdownButton.tsx
  static/app/utils/theme.tsx
Labels: Scope: Frontend

#42824 ref(useOverlay): Update popper position on state change
  static/app/utils/useOverlay.tsx
Labels: Scope: Frontend

#42835 ref(crons): Add page view empty_state analytic parameter
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#42854 feat(workflow): Add streamline targeting context flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#42851 ref(api): put idp:provisioned under flags attr in TeamSerializer
  src/sentry/api/serializers/models/team.py
  tests/sentry/api/serializers/test_team.py
Labels: Scope: Backend

#42856 feat(workflow): Remove issue-details-owners flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#42858 feat(issue-platform): Ensure new issue categories don't break when checking capabilities
  static/app/utils/groupCapabilities.tsx
Labels: Scope: Frontend

#42852 ref(js): mv components/form/{field,fieldGroup}
  docs-ui/stories/components/panels.stories.js
  static/app/components/confirmDelete.tsx
  static/app/components/featureFeedback/feedbackModal.tsx
  static/app/components/forms/fieldFromConfig.tsx
  static/app/components/forms/fieldGroup/controlState.tsx
  static/app/components/forms/fieldGroup/fieldControl.tsx
  static/app/components/forms/fieldGroup/fieldControlState.tsx
  static/app/components/forms/fieldGroup/fieldDescription.tsx
  static/app/components/forms/fieldGroup/fieldHelp.tsx
  static/app/components/forms/fieldGroup/fieldLabel.tsx
  static/app/components/forms/fieldGroup/fieldQuestion.tsx
  static/app/components/forms/fieldGroup/fieldRequiredBadge.tsx
  static/app/components/forms/fieldGroup/fieldWrapper.tsx
  static/app/components/forms/fieldGroup/index.tsx
  static/app/components/forms/fieldGroup/types.tsx
  static/app/components/forms/fields/blankField.tsx
  static/app/components/forms/fields/checkboxField.tsx
  static/app/components/forms/formField/controlState.tsx
  static/app/components/forms/formField/index.tsx
  static/app/components/modals/debugFileCustomRepository/appStoreConnect/stepOne.tsx
  static/app/components/modals/debugFileCustomRepository/http.tsx
  static/app/components/radioGroupRating.tsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/metric/triggers/form.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/columnsStep/columnFields.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/filterResultsStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/groupByStep/groupBySelector.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/sortByStep/index.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/visualizationStep.tsx
  static/app/views/dashboardsV2/widgetBuilder/buildSteps/yAxisStep/yAxisSelector/index.tsx
  static/app/views/integrationOrganizationLink.tsx
  static/app/views/monitors/monitorForm.tsx
  static/app/views/newsletterConsent.tsx
  static/app/views/performance/transactionSummary/transactionThresholdModal.tsx
  static/app/views/sentryAppExternalInstallation.tsx
  static/app/views/settings/account/accountSecurity/accountSecurityEnroll.tsx
  static/app/views/settings/account/accountSecurity/index.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/eventIdField.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/eventIdFieldStatusIcon.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/index.tsx
  static/app/views/settings/organizationGeneralSettings/index.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/organizationRateLimits/organizationRateLimits.tsx
  static/app/views/settings/organizationRelay/modals/form.tsx
  static/app/views/settings/organizationTeams/teamSettings/index.tsx
  static/app/views/settings/project/dynamicSampling/samplingFeedback.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.tsx
  static/app/views/settings/project/projectKeys/projectKeyCredentials.tsx
  static/app/views/settings/project/projectReleaseTracking.tsx
  static/app/views/settings/project/projectServiceHookDetails.tsx
  static/app/views/settings/project/projectServiceHooks.tsx
  static/app/views/settings/projectGeneralSettings.tsx
  static/app/views/settings/projectIssueGrouping/upgradeGrouping.tsx
  static/app/views/settings/projectSecurityHeaders/reportUri.tsx
Labels: Scope: Frontend

#42687 ref(hybrid-cloud): Region/Control Outboxes and Tombstones
  migrations_lockfile.txt
  src/sentry/api/serializers/models/__init__.py
  src/sentry/api/serializers/models/apiorganizationmapping.py
  src/sentry/conf/server.py
  src/sentry/migrations/0348_add_outbox_and_tombstone_tables.py
  src/sentry/models/__init__.py
  src/sentry/models/organization.py
  src/sentry/models/organizationmember.py
  src/sentry/models/outbox.py
  src/sentry/models/tombstone.py
  src/sentry/models/user.py
  src/sentry/options/defaults.py
  src/sentry/receivers/__init__.py
  src/sentry/receivers/outbox.py
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/impl.py
  src/sentry/services/hybrid_cloud/tombstone/__init__.py
  src/sentry/services/hybrid_cloud/tombstone/impl.py
  src/sentry/tasks/deliver_from_outbox.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  src/sentry/testutils/silo.py
  tests/sentry/db/test_silo_models.py
  tests/sentry/hybrid_cloud/test_organizationmapping.py
  tests/sentry/models/test_outbox.py
Labels: Scope: Backend

#42807 feat(profiling): make timelines collapsible
  static/app/components/profiling/flamegraph/collapsibleTimeline.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphLayout.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContext.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphQueryParamSync.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/reducers/flamegraphPreferences.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42761 ref(profiling): fix setting identity on identity matrix
  static/app/utils/profiling/gl/utils.ts
  static/app/utils/profiling/renderers/positionIndicatorRenderer.spec.tsx
  static/app/utils/profiling/renderers/selectedFrameRenderer.spec.tsx
  static/app/utils/profiling/renderers/textRenderer.spec.tsx
Labels: Scope: Frontend

#42823 feat(profiling): improve color scheme
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/utils/profiling/colors/utils.spec.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer.spec.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42846 ref(issues): Add stacktrace link tag for Windows
  src/sentry/api/endpoints/project_stacktrace_link.py
Labels: Scope: Backend

#42437 fix(discover): Support tags that look like functions
  src/sentry/search/events/builder/discover.py
  src/sentry/snuba/discover.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
Labels: Scope: Backend

#42668 feat: Add Ruby support for auto code mappings
  src/sentry/integrations/utils/code_mapping.py
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#42877 fix(flag): drop flag override
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#42868 fix(ui): Detach thread selector
  static/app/components/events/interfaces/threads/threadSelector/index.tsx
Labels: Scope: Frontend

#42787 feat(perf-issues): Add feature flag for consecutive db issue
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/options/defaults.py
Labels: Scope: Backend

#42850 feat: Add OpenAPI docs for monitor endpoints
  src/sentry/api/endpoints/monitor_checkin_details.py
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/api/endpoints/monitor_details.py
  src/sentry/api/serializers/models/monitor.py
  src/sentry/api/serializers/models/monitorcheckin.py
  src/sentry/api/serializers/rest_framework/project.py
  src/sentry/api/validators/monitor.py
  src/sentry/apidocs/build.py
  src/sentry/apidocs/constants.py
  src/sentry/apidocs/hooks.py
  src/sentry/apidocs/parameters.py
  src/sentry/apidocs/public_exclusion_list.py
Labels: Scope: Backend

#42785 feat(anr-rate): Display ANR rate chart in project details
  static/app/types/project.tsx
  static/app/views/projectDetail/charts/projectBaseSessionsChart.tsx
  static/app/views/projectDetail/charts/projectSessionsAnrRequest.tsx
  static/app/views/projectDetail/charts/projectSessionsChartRequest.tsx
  static/app/views/projectDetail/projectCharts.spec.tsx
  static/app/views/projectDetail/projectCharts.tsx
  static/app/views/projectDetail/projectDetail.tsx
  static/app/views/releases/utils/sessionTerm.tsx
Labels: Scope: Frontend

#42882 fix(domains) Fix URL generation in issues
  static/app/views/issueList/overview.spec.jsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#42878 fix(domains) Fix URL generation for security headers
  static/app/views/settings/projectSecurityHeaders/index.tsx
Labels: Scope: Frontend

#42867 ref(js): Remove old components/form/field
  static/app/components/forms/field/controlState.tsx
  static/app/components/forms/field/fieldControl.tsx
  static/app/components/forms/field/fieldControlState.tsx
  static/app/components/forms/field/fieldDescription.tsx
  static/app/components/forms/field/fieldHelp.tsx
  static/app/components/forms/field/fieldLabel.tsx
  static/app/components/forms/field/fieldQuestion.tsx
  static/app/components/forms/field/fieldRequiredBadge.tsx
  static/app/components/forms/field/fieldWrapper.tsx
  static/app/components/forms/field/index.tsx
  static/app/components/forms/field/types.tsx
Labels: Scope: Frontend

#42866 ref(ui): Prefer Link for `to={} priority="link"` buttons
  static/app/views/replays/detail/console/viewIssueLink.tsx
Labels: Scope: Frontend

#42880 fix(domains) Fix URL generation for remaining org settings
  static/app/views/organizationIntegrations/integrationListDirectory.tsx
  static/app/views/settings/organizationAuth/index.tsx
  static/app/views/settings/organizationIntegrations/configureIntegration.tsx
Labels: Scope: Frontend

#42885 fix(ecosystem): Remove unused codeowners api call
  static/app/components/group/suggestedOwners/suggestedOwners.spec.jsx
  static/app/components/group/suggestedOwners/suggestedOwners.tsx
Labels: Scope: Frontend

#42795 feat(replays): Save Replay>Network sort field/dir into the url
  static/app/views/replays/detail/domMutations/domMutationRow.tsx
  static/app/views/replays/detail/network/index.tsx
  static/app/views/replays/detail/network/networkHeaderCell.tsx
  static/app/views/replays/detail/network/networkTableCell.tsx
  static/app/views/replays/detail/network/useSortNetwork.spec.tsx
  static/app/views/replays/detail/network/useSortNetwork.tsx
  static/app/views/replays/detail/useVirtualizedGrid.tsx
Labels: Scope: Frontend

#41937 fix(deletions) Remove events when groups/projects are deleted
  src/sentry/deletions/defaults/group.py
  src/sentry/deletions/defaults/project.py
  src/sentry/utils/query.py
  tests/sentry/deletions/test_group.py
  tests/sentry/deletions/test_project.py
  tests/sentry/utils/test_query.py
Labels: Scope: Backend

#42883 fix(domains) Fix URL generation in alerts
  static/app/views/alerts/create.tsx
  static/app/views/alerts/edit.tsx
  static/app/views/alerts/incidentRedirect.spec.jsx
  static/app/views/alerts/incidentRedirect.tsx
  static/app/views/alerts/list/incidents/index.spec.jsx
  static/app/views/alerts/list/incidents/index.tsx
  static/app/views/alerts/list/rules/index.spec.jsx
  static/app/views/alerts/list/rules/index.tsx
  static/app/views/alerts/rules/issue/details/alertChart.tsx
  static/app/views/alerts/rules/issue/details/index.tsx
  static/app/views/alerts/rules/issue/details/ruleDetails.tsx
  static/app/views/alerts/rules/issue/index.spec.jsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/alerts/rules/metric/create.spec.jsx
  static/app/views/alerts/rules/metric/create.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
  static/app/views/alerts/rules/metric/details/header.tsx
  static/app/views/alerts/rules/metric/details/index.spec.tsx
  static/app/views/alerts/rules/metric/details/index.tsx
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/duplicate.spec.tsx
  static/app/views/alerts/rules/metric/duplicate.tsx
  static/app/views/alerts/rules/metric/edit.spec.jsx
  static/app/views/alerts/rules/metric/edit.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/wizard/index.spec.tsx
  static/app/views/alerts/wizard/index.tsx
Labels: Scope: Frontend

#42794 feat(alerts): Switch default alert action to email
  static/app/views/projectInstall/issueAlertOptions.spec.jsx
  static/app/views/projectInstall/issueAlertOptions.tsx
Labels: Scope: Frontend

#42887 fix(ui): Fix up visuals of Modal CloseButton
  static/app/components/globalModal/components.tsx
Labels: Scope: Frontend

#42889 fix(ui): button over priority="link" for manage upgrade button
  static/app/views/admin/adminEnvironment.tsx
Labels: Scope: Frontend

#42810 feat(stacktrace-link): Refactor tagging process and add few more tags
  src/sentry/api/endpoints/project_stacktrace_link.py
  src/sentry/api/serializers/models/repository_project_path_config.py
  tests/sentry/api/endpoints/test_organization_code_mappings.py
  tests/sentry/api/endpoints/test_organization_derive_code_mappings.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
Labels: Scope: Backend

#42890 ref(theme): Update drop shadow keys & values
  static/app/components/banner.tsx
  static/app/components/button.tsx
  static/app/components/checkbox.tsx
  static/app/components/dropdownBubble.tsx
  static/app/components/events/eventReplay/replayPreview.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/type/index.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/contentV3.tsx
  static/app/components/events/interfaces/frame/openInContextLine.tsx
  static/app/components/forms/controls/selectControl.tsx
  static/app/components/forms/controls/selectOption.tsx
  static/app/components/forms/fields/datePickerField.tsx
  static/app/components/input.tsx
  static/app/components/modals/dashboardWidgetQuerySelectorModal.tsx
  static/app/components/panels/panel.tsx
  static/app/components/performance/waterfall/treeConnector.tsx
  static/app/components/pill.tsx
  static/app/components/radio.tsx
  static/app/components/replays/breadcrumbs/replayTimelineEvents.tsx
  static/app/components/replays/replayView.tsx
  static/app/components/smartSearchBar/index.tsx
  static/app/components/switchButton.tsx
  static/app/styles/deprecatedInput.tsx
  static/app/utils/theme.tsx
  static/app/views/organizationStats/teamInsights/controls.tsx
  static/app/views/replays/detail/breadcrumbs/breadcrumbItem.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/index.tsx
  static/app/views/settings/components/settingsSearch/index.tsx
  static/app/views/settings/organizationMembers/components/membersFilter.tsx
Labels: Scope: Frontend

#42892 fix(integrations): User is not always a model instance, use identifier.
  src/sentry/plugins/providers/base.py
Labels: Scope: Backend

#42876 feat(spans): optimize render
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
Labels: Scope: Frontend

#42872 feat(spans): missing instrumentation
  static/app/utils/profiling/spanChart.spec.tsx
  static/app/utils/profiling/spanTree.spec.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#42899 test(js): Disable flaky searchBar test
  static/app/views/issueList/searchBar.spec.tsx
Labels: Scope: Frontend

#42895 ref(ui): Remove title on upgrade button in manage/env
  static/app/views/admin/adminEnvironment.tsx
Labels: Scope: Frontend

#42893 ref(ui): Improve screenshot component w/ DropdownMenuControl
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
Labels: Scope: Frontend

#42862 fix(ui): Use ExternalLink for SetupSourceMapsAlert
  static/app/components/events/interfaces/crashContent/exception/setupSourceMapsAlert.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/setupSourceMapsAlert.tsx
Labels: Scope: Frontend

#42906 fix(ui): Alignment of SavedIssueSearches buttons
  static/app/views/issueList/savedIssueSearches.tsx
Labels: Scope: Frontend

#42886 fix: Correct API usage for Crons
  src/sentry/api/endpoints/monitor_checkin_details.py
  src/sentry/api/endpoints/monitor_checkins.py
  src/sentry/api/endpoints/monitor_details.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_monitor_checkin_details.py
Labels: Scope: Backend

#42800 feat(page-filters): Use Checkbox instead of CheckboxFancy for env and project selectors
  static/app/components/checkbox.tsx
  static/app/components/environmentPageFilter.spec.tsx
  static/app/components/organizations/environmentSelector.tsx
  static/app/components/organizations/pageFilterRow.tsx
  static/app/components/organizations/projectSelector/selectorItem.tsx
  static/app/components/projectPageFilter.spec.tsx
  tests/acceptance/test_organization_global_selection_header.py
Labels: Scope: Frontend

#42905 ref(js): Remove export on ButtonPropsWith{,out}AriaLabel
  static/app/components/button.tsx
  static/app/components/demoSandboxButton.tsx
  static/app/components/profiling/exportProfileButton.tsx
  static/app/views/organizationIntegrations/addIntegrationButton.tsx
Labels: Scope: Frontend

#42869 ref(ui): Remove little-used Button align prop
  docs-ui/stories/components/button.stories.js
  static/app/components/button.tsx
  static/app/components/events/interfaces/threads/threadSelector/index.tsx
  static/app/views/auth/loginForm.tsx
  static/app/views/issueList/savedIssueSearches.tsx
Labels: Scope: Frontend

#42859 ref(hybrid-cloud): use correct monitor urls with org slug frontend
  static/app/views/monitors/details.tsx
  static/app/views/monitors/edit.tsx
  static/app/views/monitors/monitorCheckIns.tsx
  static/app/views/monitors/monitorHeaderActions.tsx
  static/app/views/monitors/monitorStats.tsx
Labels: Scope: Frontend

#42857 ref(replays): Refactor the ReplayTable to make it more reusable
  static/app/views/organizationGroupDetails/groupReplays/groupReplays.tsx
  static/app/views/performance/transactionSummary/transactionReplays/content.tsx
  static/app/views/replays/replayTable.tsx
  static/app/views/replays/replayTable/headerCell.tsx
  static/app/views/replays/replayTable/index.tsx
  static/app/views/replays/replayTable/sortableHeader.tsx
  static/app/views/replays/replayTable/tableCell.tsx
  static/app/views/replays/replayTable/types.tsx
  static/app/views/replays/replays.tsx
Labels: Scope: Frontend

#42910 ref(ui): Enforce IconSize enum usage
  static/app/components/assigneeSelectorDropdown.tsx
  static/app/components/avatar/sentryAppAvatar.tsx
  static/app/components/checkbox.tsx
  static/app/components/checkboxFancy/checkboxFancy.tsx
  static/app/components/contextData/toggle.tsx
  static/app/components/emptyStateWarning.tsx
  static/app/components/events/groupingInfo/groupingComponentFrames.tsx
  static/app/components/events/interfaces/frame/line.tsx
  static/app/components/events/interfaces/frame/lineV2/expander.tsx
  static/app/components/events/interfaces/nativeFrame.tsx
  static/app/components/forms/controls/selectControl.tsx
  static/app/components/globalModal/components.tsx
  static/app/components/group/times.tsx
  static/app/components/modals/debugFileCustomRepository/http.tsx
  static/app/components/modals/inviteMembersModal/renderEmailValue.tsx
  static/app/components/modals/sentryAppDetailsModal.tsx
  static/app/components/numberDragControl.tsx
  static/app/components/tag.tsx
  static/app/icons/svgIcon.tsx
  static/app/views/dashboardsV2/manage/templateCard.tsx
  static/app/views/organizationGroupDetails/grouping/newIssue.tsx
  static/app/views/organizationJoinRequest.tsx
  static/app/views/organizationStats/usageTable/index.tsx
  static/app/views/releases/list/releasesPromo.tsx
  static/app/views/settings/components/settingsBreadcrumb/divider.tsx
  static/app/views/settings/components/settingsSearch/index.tsx
Labels: Scope: Frontend

#42792 ref(hybrid-cloud): use organization_slug in SharedGroupDetails
  src/sentry/api/endpoints/shared_group_details.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_shared_group_details.py
Labels: Scope: Backend

#42915 fix(ui): Use consistent Buttons in group OwnedBy
  static/app/components/group/ownedBy.tsx
Labels: Scope: Frontend

#42922 fix(checkbox): Set ref on input so indeterminate state is set correctly
  static/app/components/checkbox.tsx
Labels: Scope: Frontend

#42860 feat(alerts): Add a default fallback option for issue alerts
  src/sentry/mail/actions.py
  src/sentry/notifications/utils/participants.py
  tests/sentry/mail/test_actions.py
  tests/sentry/notifications/utils/test_participants.py
Labels: Scope: Backend

#42925 ref(ui): Actually enforce size as IconSize
  static/app/icons/svgIcon.tsx
Labels: Scope: Frontend

#42914 fix(ui): Icon sizes in stack trace drop downs
  static/app/components/events/traceEventDataSection.tsx
Labels: Scope: Frontend

#42916 fix(ui): Use button for IssueSyncListElement add/remove
  static/app/components/issueSyncListElement.tsx
Labels: Scope: Frontend

#42873 feat(spans): update span and frame color fallbacks
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/flamegraph/flamegraphTheme.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
Labels: Scope: Frontend

#42918 ref(ui): Consistent close button on dismissable alerts
  static/app/components/globalSdkUpdateAlert.spec.tsx
  static/app/components/globalSdkUpdateAlert.tsx
  static/app/views/organizationGroupDetails/quickTrace/issueQuickTrace.tsx
Labels: Scope: Frontend

#42928 chore(ui): Upgrade to TypeScript 4.9
  package.json
  static/app/components/lazyLoad.tsx
  yarn.lock
Labels: Scope: Frontend
