Repository getsentry/sentry, pull requests merged in 2023-04, with the labels that each got.

#46587 feat(sourcemaps): Improve search of artifact bundle files
  src/sentry/models/artifactbundle.py
  tests/sentry/api/endpoints/test_project_artifact_bundle_files.py
Labels: Scope: Backend

#46657 fix(sourcemaps): Add error when fetching is disabled
  src/sentry/lang/javascript/processor.py
  src/sentry/models/eventerror.py
  tests/relay_integration/lang/javascript/test_plugin.py
Labels: Scope: Backend

#46585 feat(sourcemaps): Add count of weakly associated artifacts
  src/sentry/api/endpoints/organization_release_meta.py
  src/sentry/models/release.py
  tests/sentry/api/endpoints/test_organization_release_meta.py
Labels: Scope: Backend

#46777 fix(dynamic-sampling) Remove unused prioritise by transaction/project features
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/dynamic_sampling/test_tasks.py
Labels: Scope: Backend

#46781 feat(sourcemaps): Rename debug id bundles to artifact bundles
  static/app/routes.tsx
  static/app/views/releases/detail/overview/sidebar/projectReleaseDetails.tsx
  static/app/views/settings/projectSourceMaps/projectSourceMaps.spec.tsx
  static/app/views/settings/projectSourceMaps/projectSourceMaps.tsx
  static/app/views/settings/projectSourceMaps/projectSourceMapsArtifacts.spec.tsx
  static/app/views/settings/projectSourceMaps/projectSourceMapsArtifacts.tsx
Labels: Scope: Frontend

#46578 Avoid infinite processing loop
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#46773 chore(flag): Add new feature flag (organizations:ds-apply-actual-sample-rate-to-biases)
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#46784 ref(ui): Improve empty release bundles UI
  static/app/views/settings/projectSourceMaps/projectSourceMaps.tsx
Labels: Scope: Frontend

#46785 Filter hierarchical GroupHash updates that already have a Group
  src/sentry/event_manager.py
Labels: Scope: Backend

#46788 fix(sourcemaps): Remove artifact count when no bundle is associated
  static/app/views/settings/projectSourceMaps/projectSourceMaps.tsx
Labels: Scope: Frontend

#46700 feat(mobile): Makes device.class searchable in issues stream frontend
  static/app/stores/tagStore.tsx
  static/app/utils/fields/index.ts
  static/app/views/issueList/searchBar.tsx
Labels: Scope: Frontend

#46708 chore: Update eslint config to latest release
  package.json
  yarn.lock
Labels: Scope: Frontend

#46787 fix(clusterer): Remove transaction rules if minimum threshold not met
  src/sentry/ingest/transaction_clusterer/tasks.py
  tests/sentry/ingest/test_transaction_clusterer.py
Labels: Scope: Backend

#45528 chore(hybrid-cloud): More keys broken
  migrations_lockfile.txt
  src/sentry/migrations/0397_break_some_more_fks.py
  src/sentry/models/apikey.py
  src/sentry/models/authprovider.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/integrations/organization_integration.py
  src/sentry/models/integrations/sentry_app.py
  src/sentry/models/integrations/sentry_app_installation.py
  src/sentry/models/integrations/sentry_app_installation_for_provider.py
  src/sentry/models/organizationaccessrequest.py
  src/sentry/models/organizationonboardingtask.py
  src/sentry/models/projectbookmark.py
  src/sentry/models/promptsactivity.py
  src/sentry/models/rule.py
  tests/sentry/db/test_silo_models.py
Labels: Scope: Frontend, Scope: Backend

#46795 fix(crons): Properly allows updates where the slug doesn't change
  src/sentry/monitors/endpoints/organization_monitor_details.py
  src/sentry/monitors/validators.py
  tests/sentry/monitors/endpoints/test_organization_monitor_details.py
Labels: Scope: Backend

#46705 fix(workflow): Replace ignored with archived for esclating
  static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx
Labels: Scope: Frontend

#46633 feat(workflow): Dedupe issue stream assignees
  static/app/components/assigneeSelectorDropdown.tsx
Labels: Scope: Frontend

#46793 fix(dynamic-sampling):Explicitly handle project does not exist
  src/sentry/dynamic_sampling/tasks.py
Labels: Scope: Backend

#46063 feat(roles): display role names in members list
  fixtures/js-stubs/member.js
  fixtures/js-stubs/members.js
  static/app/views/settings/organizationMembers/organizationMemberRow.spec.jsx
  static/app/views/settings/organizationMembers/organizationMemberRow.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.spec.jsx
Labels: Scope: Frontend

#46797 fix(hc): Remove remainig ApiKey.organization references
  src/sentry/api/endpoints/organization_index.py
  src/sentry/api/endpoints/project_index.py
Labels: Scope: Backend

#46800 chore(ui): Update yarn.lock file
  yarn.lock
Labels: Scope: Frontend

#46791 feat(replays): updated dropdown with projects partitioned and sorted
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/components/replaysOnboarding/useCurrentProjectState.tsx
  static/app/components/replaysOnboarding/utils.tsx
Labels: Scope: Frontend

#46713 fix(features): Fix feature test helper to properly use default values when combined with batch_has
  src/sentry/testutils/helpers/features.py
  tests/sentry/testutils/helpers/test_features.py
Labels: Scope: Backend

#46801 fix(workflow): Convert `owners.send_to` metric tag to a string
  src/sentry/notifications/utils/participants.py
Labels: Scope: Backend

#46528 feat(replay): Show all `user` attributes in Replay tags, add `replayType`
  static/app/utils/replays/replayDataUtils.tsx
  static/app/views/replays/detail/tagPanel/index.tsx
Labels: Scope: Frontend

#46642 ref(compactSelect): Small improvements
  static/app/components/charts/optionSelector.tsx
  static/app/components/compactSelect/control.tsx
  static/app/components/compactSelect/gridList/option.tsx
  static/app/components/compactSelect/listBox/option.tsx
  static/app/components/compactSelect/styles.tsx
  static/app/components/compactSelect/types.tsx
  static/app/components/menuListItem.tsx
Labels: Scope: Frontend

#46609 feat(compactSelect): Add ability to limit the number of displayed options
  static/app/components/compactSelect/composite.tsx
  static/app/components/compactSelect/control.tsx
  static/app/components/compactSelect/gridList/index.tsx
  static/app/components/compactSelect/gridList/section.tsx
  static/app/components/compactSelect/index.spec.tsx
  static/app/components/compactSelect/index.tsx
  static/app/components/compactSelect/list.tsx
  static/app/components/compactSelect/listBox/index.tsx
  static/app/components/compactSelect/listBox/section.tsx
  static/app/components/compactSelect/styles.tsx
  static/app/components/compactSelect/utils.tsx
Labels: Scope: Frontend

#46809 fix(compactSelect): Fix sizeLimit tests
  static/app/components/compactSelect/index.spec.tsx
Labels: Scope: Frontend

#46808 feat(profiling): add flags for ga and beta grace period
  src/sentry/conf/server.py
Labels: Scope: Backend

#46621 ref: use hashed frontend assets configmap for urls
  requirements-dev-frozen.txt
  requirements-dev.txt
  src/sentry/utils/assets.py
  src/sentry/web/client_config.py
  tests/sentry/utils/test_assets.py
  tests/sentry/web/frontend/generic/test_static_media.py
Labels: Scope: Backend

#46806 ref(emails): Use normal font weight
  src/sentry/templates/sentry/emails/email-styles.html
Labels: Scope: Frontend

#46475 feat(trace): Add perf issues to trace view
  static/app/utils/performance/quickTrace/types.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.spec.tsx
  static/app/views/performance/traceDetails/transactionBar.tsx
  static/app/views/performance/traceDetails/transactionDetail.tsx
Labels: Scope: Frontend

#46810 fix(hybrid-cloud): Fix integration.organizations references
  src/sentry/integrations/bitbucket/uninstalled.py
  src/sentry/integrations/github/webhook.py
Labels: Scope: Backend

#46697 fix(features) Add feature implementation for organizations:create
  src/sentry/features/__init__.py
  src/sentry/features/base.py
Labels: Scope: Backend

#46647 chore(subscriptions): Add Typing to Incident Tasks
  mypy.ini
  src/sentry/incidents/subscription_processor.py
  src/sentry/incidents/tasks.py
  src/sentry/incidents/utils/types.py
  src/sentry/snuba/query_subscription_consumer.py
  tests/sentry/snuba/test_query_subscription_consumer.py
Labels: Scope: Backend

#46807 feat(replay): Move DOM search UI flag to flagr
  src/sentry/features/__init__.py
Labels: Scope: Backend

#46652 feat(notification-actions): UI forms
  static/app/components/notificationActions/forms/pagerdutyForm.tsx
  static/app/components/notificationActions/forms/slackForm.tsx
  static/app/types/notificationActions.tsx
Labels: Scope: Frontend

#46716 feat(crons): Add environment selector to crons list page
  static/app/views/monitors/components/row.tsx
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#46821 ref(issue-details): Remove unused network request
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.tsx
Labels: Scope: Frontend

#46816 fix(hybrid-cloud): Fix Integration.objects.get call
  src/sentry/integrations/vsts/search.py
Labels: Scope: Backend

#45717 feat(sandbox): custom model org onboarding fe
  static/app/actionCreators/guides.tsx
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/stores/guideStore.tsx
  static/app/utils/demoWalkthrough.tsx
  tests/acceptance/test_sidebar.py
Labels: Scope: Frontend

#46171 ref(hybrid-cloud): Invert actor foreign keys 1/4
  migrations_lockfile.txt
  src/sentry/api/bases/external_actor.py
  src/sentry/api/endpoints/user_notification_details.py
  src/sentry/db/models/fields/hybrid_cloud_foreign_key.py
  src/sentry/deletions/defaults/team.py
  src/sentry/incidents/models.py
  src/sentry/migrations/0398_actor_fk_inversion.py
  src/sentry/models/actor.py
  src/sentry/models/identity.py
  src/sentry/models/team.py
  src/sentry/models/user.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/manager.py
  src/sentry/runner/commands/backup.py
  src/sentry/services/hybrid_cloud/actor.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/tasks/deletion/scheduled.py
  src/sentry/testutils/factories.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_project_rule_details.py
  tests/sentry/api/endpoints/test_project_rules.py
  tests/sentry/api/serializers/test_external_actor.py
  tests/sentry/digests/test_utilities.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_serializers.py
  tests/sentry/incidents/test_logic.py
  tests/sentry/integrations/slack/webhooks/actions/test_enable_notifications.py
  tests/sentry/mediators/project_rules/test_creator.py
  tests/sentry/mediators/project_rules/test_updater.py
  tests/sentry/migrations/test_0381_fix_org_slug_casing.py
  tests/sentry/migrations/test_0386_backfill_monitor_env_checkins.py
  tests/sentry/models/test_actor.py
  tests/sentry/models/test_notificationsetting.py
  tests/sentry/models/test_project.py
  tests/sentry/notifications/test_notifications.py
  tests/sentry/notifications/utils/test_get_fallback_settings.py
  tests/sentry/notifications/utils/test_get_most_specific.py
  tests/sentry/notifications/utils/test_get_scope.py
  tests/sentry/notifications/utils/test_get_setting_mapping_from_mapping.py
  tests/sentry/notifications/utils/test_get_user_subscriptions_for_groups.py
  tests/sentry/notifications/utils/test_should_be_notified.py
  tests/sentry/notifications/utils/test_should_be_participating.py
  tests/sentry/notifications/utils/test_transforms.py
  tests/sentry/sentry_apps/test_sentry_app_creator.py
  tests/sentry/sentry_apps/test_sentry_app_installation_creator.py
  tests/sentry/utils/test_query.py
Labels: Scope: Frontend, Scope: Backend

#46822 chore(js): Prefer Array.includes for feature checks
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/projects/missingProjectMembership.tsx
  static/app/views/issueDetails/actions/index.tsx
  static/app/views/settings/organizationIntegrations/integrationRepos.tsx
  static/app/views/settings/organizationProjects/index.tsx
  static/app/views/settings/organizationSecurityAndPrivacy/index.tsx
  static/app/views/settings/organizationTeams/teamNotifications.tsx
  static/app/views/settings/organizationTeams/teamProjects.tsx
  static/app/views/settings/project/projectKeys/list/index.tsx
  static/app/views/settings/project/projectServiceHooks.tsx
  static/app/views/settings/project/projectTeams.tsx
  static/app/views/settings/projectGeneralSettings/index.tsx
  static/app/views/settings/projectSecurityAndPrivacy/index.tsx
Labels: Scope: Frontend

#46850 fix(hc): Duplicate actors resulting from lack of index, fixed.
  src/sentry/models/actor.py
  tests/sentry/api/serializers/test_external_actor.py
Labels: Scope: Backend

#46847 ref(hc): Enable indexes for new actor columns
  migrations_lockfile.txt
  src/sentry/migrations/0399_enable_indexes_for_actor_fks.py
  src/sentry/models/actor.py
Labels: Scope: Backend

#46866 ref(stack-traces): Remove native stack trace v2 feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#46867 ref(stack-trace): Rename stack trace components and clean ups
  static/app/components/events/eventEntry.tsx
  static/app/components/events/interfaces/crashContent/exception/stackTrace.tsx
  static/app/components/events/interfaces/crashContent/index.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/content.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/hierarchicalGroupingContent.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/index.tsx
  static/app/components/events/interfaces/exception.tsx
  static/app/components/events/interfaces/frame/deprecatedLine.spec.tsx
  static/app/components/events/interfaces/frame/deprecatedLine.tsx
  static/app/components/events/interfaces/frame/line/default.tsx
  static/app/components/events/interfaces/frame/line/expander.tsx
  static/app/components/events/interfaces/frame/line/index.tsx
  static/app/components/events/interfaces/frame/line/leadHint.tsx
  static/app/components/events/interfaces/frame/line/native.tsx
  static/app/components/events/interfaces/frame/line/wrapper.tsx
  static/app/components/events/interfaces/frame/symbol.tsx
  static/app/components/events/interfaces/spans/spanProfileDetails.tsx
  static/app/components/events/interfaces/stackTrace.tsx
  static/app/components/events/interfaces/template.tsx
  static/app/components/events/interfaces/threads.spec.tsx
  static/app/components/events/interfaces/threads.tsx
  static/app/components/groupPreviewTooltip/stackTracePreview.tsx
Labels: Scope: Frontend

#46855 feat(onboarding): Add hook for the onboarding existing orgs
  static/app/types/hooks.tsx
  static/app/views/onboarding/setupDocs.tsx
  static/app/views/projectInstall/platform.spec.jsx
  static/app/views/projectInstall/platform.spec.tsx
  static/app/views/projectInstall/platform.tsx
  tests/acceptance/test_create_project.py
Labels: Scope: Frontend

#46817 chore(profiling): Remove path from suspect functions
  static/app/components/profiling/suspectFunctions/functionsTable.tsx
  static/app/types/profiling/core.tsx
Labels: Scope: Frontend

#46676 feat(transactions): Add CPU chart to transaction detail
  static/app/components/events/interfaces/spans/constants.tsx
  static/app/components/events/interfaces/spans/header.tsx
  static/app/components/events/interfaces/spans/profilingMeasurements.spec.tsx
  static/app/components/events/interfaces/spans/profilingMeasurements.tsx
  static/app/components/events/opsBreakdown.tsx
  static/app/types/profiling.d.ts
Labels: Scope: Frontend

#46874 fix(hybridcloud) Fix most of the pydantic warnings for RPC data classes
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/app/__init__.py
  src/sentry/services/hybrid_cloud/auth/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/__init__.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/services/hybrid_cloud/user_option/__init__.py
Labels: Scope: Backend

#46805 feat(replay): Add search field for DOM click selector syntax
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#46869 feat(profiling): add billing banner to prep for GA
  static/app/components/profiling/billing/alerts.tsx
  static/app/types/hooks.tsx
  static/app/views/profiling/content.tsx
Labels: Scope: Frontend, Scope: Backend

#46628 feat(generic-metrics): Add unique constraint to indexer
  migrations_lockfile.txt
  src/sentry/migrations/0400_add_unique_constraint_indexer.py
  src/sentry/sentry_metrics/indexer/postgres/models.py
Labels: Scope: Backend

#46845 feat(escalating-issues): Add new `ARCHIVED_UNTIL_ESCALATING` status
  src/sentry/models/group.py
  src/sentry/models/grouphistory.py
Labels: Scope: Backend

#46826 feat(crons): Include `hasMonitors` in project serializer
  src/sentry/api/endpoints/organization_projects.py
  src/sentry/api/serializers/models/project.py
  tests/sentry/api/serializers/test_project.py
Labels: Scope: Backend

#46644 fix(hc): Make RPC pagination args into RpcModels
  src/sentry/api/endpoints/group_integrations.py
  src/sentry/api/endpoints/integrations/organization_integrations/index.py
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/integration/__init__.py
  src/sentry/services/hybrid_cloud/integration/impl.py
  src/sentry/services/hybrid_cloud/pagination.py
Labels: Scope: Backend

#46517 feat(escalating_issues): Fetch historical hourly count for list of groups
  src/sentry/issues/escalating.py
  src/sentry/snuba/referrer.py
  src/sentry/utils/snuba.py
  tests/sentry/issues/test_escalating.py
Labels: Scope: Backend

#46638 feat(hc): Set up region resolution on RPC services
  src/sentry/models/commitauthor.py
  src/sentry/models/team.py
  src/sentry/services/hybrid_cloud/organization/__init__.py
  src/sentry/services/hybrid_cloud/project_key/__init__.py
  src/sentry/services/hybrid_cloud/region.py
  src/sentry/services/hybrid_cloud/rpc.py
  tests/sentry/hybrid_cloud/test_rpc.py
Labels: Scope: Backend

#46836 feat(issue-details): Event selector revisions
  static/app/components/tag.tsx
  static/app/views/issueDetails/groupEventCarousel.spec.tsx
  static/app/views/issueDetails/groupEventCarousel.tsx
  static/app/views/issueDetails/groupEventHeader.tsx
  static/app/views/issueDetails/quickTrace/index.tsx
  static/app/views/issueDetails/quickTrace/issueQuickTrace.tsx
  static/app/views/issueDetails/quickTrace/traceLink.tsx
Labels: Scope: Frontend

#46878 fix(hc): Suppress RPC parameter model validation in non-monolith modes
  src/sentry/services/hybrid_cloud/rpc.py
Labels: Scope: Backend

#46794 fix(issues): More adjustments for the page filter bar styling
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/issueCategoryFilter.tsx
Labels: Scope: Frontend

#46885 chore(referrer): add referrer for backfill
  src/sentry/snuba/referrer.py
Labels: Scope: Backend

#46430 feat(notification-actions): UI
  fixtures/js-stubs/availableNotificationActions.js
  fixtures/js-stubs/types.tsx
  static/app/components/notificationActions/notificationActionItem.tsx
  static/app/components/notificationActions/notificationActionManager.spec.jsx
  static/app/components/notificationActions/notificationActionManager.tsx
Labels: Scope: Frontend

#46877 feat(perf-issues): Write occurrences for consecutive http detector
  src/sentry/utils/performance_issues/detectors/consecutive_http_detector.py
  tests/sentry/utils/performance_issues/test_consecutive_http_detector.py
Labels: Scope: Backend

#46701 feat(replays): Add support for filtering click events with a CSS selector
  requirements-base.txt
  src/sentry/replays/blueprints/api.md
  src/sentry/replays/lib/query.py
  src/sentry/replays/lib/selector/__init__.py
  src/sentry/replays/lib/selector/parse.py
  src/sentry/replays/lib/selector/query.py
  src/sentry/replays/post_process.py
  src/sentry/replays/query.py
  tests/sentry/replays/test_organization_replay_index.py
Labels: Scope: Backend

#46814 feat(transactions): Sync cursor hover between minimap and CPU chart
  static/app/components/events/interfaces/spans/header.tsx
  static/app/components/events/interfaces/spans/profilingMeasurements.tsx
Labels: Scope: Frontend

#46887 ref(prism): Auto-download language dependencies
  static/app/utils/loadPrismLanguage.ts
Labels: Scope: Frontend

#46846 feat(rulesnooze): Create RuleSnooze table
  migrations_lockfile.txt
  src/sentry/migrations/0401_create_rulesnooze_table.py
  src/sentry/models/__init__.py
  src/sentry/models/rulesnooze.py
  tests/sentry/deletions/test_project.py
Labels: Scope: Backend

#46879 (feat): Migrate all perf detectors
  src/sentry/event_manager.py
  src/sentry/issues/utils.py
  src/sentry/utils/performance_issues/detectors/consecutive_db_detector.py
  src/sentry/utils/performance_issues/detectors/io_main_thread_detector.py
  src/sentry/utils/performance_issues/detectors/mn_plus_one_db_span_detector.py
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
  src/sentry/utils/performance_issues/detectors/n_plus_one_db_span_detector.py
  src/sentry/utils/performance_issues/detectors/render_blocking_asset_span_detector.py
  src/sentry/utils/performance_issues/detectors/slow_db_query_detector.py
  src/sentry/utils/performance_issues/detectors/uncompressed_asset_detector.py
  tests/sentry/api/serializers/test_event.py
  tests/sentry/utils/performance_issues/test_consecutive_db_detector.py
  tests/sentry/utils/performance_issues/test_db_main_thread_detector.py
  tests/sentry/utils/performance_issues/test_file_io_on_main_thread_detector.py
  tests/sentry/utils/performance_issues/test_m_n_plus_one_db_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_db_span_detector.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
  tests/sentry/utils/performance_issues/test_render_blocking_asset_detector.py
  tests/sentry/utils/performance_issues/test_slow_db_span_detector.py
  tests/sentry/utils/performance_issues/test_uncompressed_assets_detector.py
Labels: Scope: Backend

#46888 feat(crons): Include empty env checkins for prod environment
  src/sentry/monitors/endpoints/organization_monitor_checkin_index.py
  tests/sentry/monitors/endpoints/test_organization_monitor_checkin_index.py
Labels: Scope: Backend

#45867 feat(hybrid-cloud): Introduce OrganizationMemberMapping model and service
  migrations_lockfile.txt
  src/sentry/migrations/0402_add_organizationmembermapping_table.py
  src/sentry/models/__init__.py
  src/sentry/models/organizationmembermapping.py
  src/sentry/receivers/outbox/region.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/__init__.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/impl.py
  tests/sentry/hybrid_cloud/test_organizationmembermapping.py
Labels: Scope: Backend

#46905 fix(hybrid-cloud): Fix org to region resolution logic
  src/sentry/services/hybrid_cloud/region.py
Labels: Scope: Backend

#46902 ref(hybrid-cloud): Removing the User from organization_mapping_service
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/organization_index.py
  src/sentry/services/hybrid_cloud/organization_mapping/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/impl.py
  tests/sentry/hybrid_cloud/test_organizationmapping.py
Labels: Scope: Backend

#46890 feat(starfish): Stack all the operations
  static/app/views/starfish/charts/chart.tsx
  static/app/views/starfish/landing/widgets/widgetDefinitions.tsx
  static/app/views/starfish/landing/widgets/widgets/stackedAreaWidget.tsx
Labels: Scope: Frontend

#46909 fix(workflow): Add features array to share issue org
  static/app/views/sharedGroupDetails/index.tsx
Labels: Scope: Frontend

#46857 fix(alerts): Fix wrong UseCaseKey
  src/sentry/snuba/entity_subscription.py
Labels: Scope: Backend

#46531 feat(monitors): Create missed checkins for monitor envs
  src/sentry/analytics/events/monitor_mark_failed.py
  src/sentry/monitors/models.py
  src/sentry/monitors/tasks.py
  src/sentry/receivers/features.py
  src/sentry/signals.py
  tests/sentry/monitors/test_models.py
  tests/sentry/monitors/test_tasks.py
Labels: Scope: Backend

#45868 feat(hybrid-cloud): Update invite request endpoint to consume `organizationmember_mapping_service`
  src/sentry/api/endpoints/organization_member/requests/invite/index.py
  src/sentry/services/hybrid_cloud/auth/impl.py
  src/sentry/services/hybrid_cloud/organization/__init__.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/testutils/hybrid_cloud.py
  tests/sentry/api/endpoints/test_organization_invite_request_index.py
  tests/sentry/hybrid_cloud/test_rpc.py
Labels: Scope: Backend

#46851 ref(hybrid-cloud): Invert actor foreign keys 2/4
  migrations_lockfile.txt
  src/sentry/migrations/0403_backfill_actors.py
  src/sentry/models/actor.py
  tests/sentry/api/serializers/test_external_actor.py
  tests/sentry/migrations/test_0403_backfill_actors.py
Labels: Scope: Backend

#46917 feat(compactSelect): Add `onInteractOutside` callback
  static/app/components/compactSelect/control.tsx
  static/app/components/dropdownMenu/index.tsx
  static/app/utils/useOverlay.tsx
Labels: Scope: Frontend

#46920 style(update_groups): Change variable to snake case
  src/sentry/api/helpers/group_index/update.py
Labels: Scope: Backend

#46230 chore(hybrid-cloud): Update auth helper tests to assert org member mappings
  tests/sentry/auth/test_helper.py
Labels: Scope: Backend

#46589 feat(onboarding): Show JS Loader in onboarding
  static/app/components/onboarding/documentationWrapper.tsx
  static/app/components/onboarding/productSelection.spec.tsx
  static/app/components/onboarding/productSelection.tsx
  static/app/views/onboarding/setupDocs.spec.tsx
  static/app/views/onboarding/setupDocs.tsx
  static/app/views/onboarding/setupDocsLoader.tsx
Labels: Scope: Frontend

#46932 ref(policies): Restrict superusers to accept policies
  static/app/views/issueDetails/actions/index.tsx
  static/app/views/issueDetails/openAIFixSuggestion/openAIFixSuggestionButton.tsx
  static/app/views/issueDetails/openAIFixSuggestion/openAIFixSuggestionPanel.tsx
Labels: Scope: Frontend

#46792 ref(ui): Vertically align empty release bundles warning
  static/app/views/settings/projectSourceMaps/projectSourceMaps.tsx
Labels: Scope: Frontend

#46929 ref(sourcemaps): Use all events traffic as the base for sample rate
  src/sentry/lang/javascript/utils.py
Labels: Scope: Backend

#46604 feat(settings): Ensure JS Loader validates SDK version & products
  static/app/views/settings/project/projectKeys/details/keySettings.spec.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.tsx
Labels: Scope: Frontend

#46935 ref(product-selection): Update product selection tooltips
  static/app/components/onboarding/productSelection.spec.tsx
  static/app/components/onboarding/productSelection.tsx
  static/app/views/projectInstall/platform.tsx
Labels: Scope: Frontend

#46933 fix(threads): Hide thread tags if none exist
  static/app/components/events/interfaces/threads.spec.tsx
  static/app/components/events/interfaces/threads.tsx
Labels: Scope: Frontend

#46936 Create new symbolication queues for JS/LPQ processing
  src/sentry/conf/server.py
Labels: Scope: Backend

#46893 feat(transactions): Add time window selection to CPU chart
  static/app/components/events/interfaces/spans/header.tsx
  static/app/components/events/interfaces/spans/profilingMeasurements.tsx
Labels: Scope: Frontend

#46662 feat(dyn-sampling): Apply actual sample_rate to not oversample/undersample
  src/sentry/dynamic_sampling/prioritise_projects.py
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/rules/biases/factor_bias.py
  src/sentry/dynamic_sampling/rules/combine.py
  src/sentry/dynamic_sampling/rules/helpers/prioritise_project.py
  src/sentry/dynamic_sampling/rules/utils.py
  src/sentry/dynamic_sampling/tasks.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
  tests/sentry/dynamic_sampling/test_prioritise_projects.py
  tests/sentry/dynamic_sampling/test_tasks.py
  tests/sentry/dynamic_sampling/test_utils.py
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#46875 feat(spurl-param): Add a string glob replacer
  src/sentry/spans/grouping/strategy/glob_replace.py
  tests/sentry/spans/grouping/test_glob_replace.py
Labels: Scope: Backend

#46941 fix(perf): Allow User Misery widget on Mobile landing
  static/app/views/performance/landing/views/mobileView.tsx
Labels: Scope: Frontend

#46948 fix(onboarding): Replace api fetch for loadDocs with useApiQuery
  static/app/views/onboarding/setupDocs.tsx
Labels: Scope: Frontend

#46947 fix(profiling): enable wizard for nextjs
  static/app/components/profiling/ProfilingOnboarding/util.ts
  static/app/data/platformCategories.tsx
  static/app/utils/profiling/platforms.tsx
Labels: Scope: Frontend

#46706 feat(issue-details): Add analytics events for issue tracking
  static/app/components/group/externalIssueActions.tsx
  static/app/components/group/externalIssueForm.tsx
  static/app/components/group/externalIssuesList.tsx
  static/app/components/group/pluginActions.tsx
  static/app/components/group/sentryAppExternalIssueActions.tsx
  static/app/plugins/components/issueActions.tsx
  static/app/utils/analytics/issueAnalyticsEvents.tsx
Labels: Scope: Frontend

#46923 chore(hybrid-cloud): Simplify auth_service.handle_new_membership
  src/sentry/api/invite_helper.py
  src/sentry/services/hybrid_cloud/auth/impl.py
  tests/sentry/auth/test_helper.py
Labels: Scope: Backend

#46812 feat(replays): hide onboarding alert for AM1
  static/app/types/hooks.tsx
  static/app/views/replays/list/replayOnboardingPanel.tsx
Labels: Scope: Frontend

#46952 fix(debug-view): use actor_id when initializing User
  src/sentry/web/frontend/debug/debug_codeowners_auto_sync_failure_email.py
  src/sentry/web/frontend/debug/debug_incident_activity_email.py
  src/sentry/web/frontend/debug/debug_onboarding_continuation_email.py
  src/sentry/web/frontend/debug/debug_organization_integration_request.py
  src/sentry/web/frontend/debug/debug_organization_invite_request.py
  src/sentry/web/frontend/debug/debug_organization_join_request.py
Labels: Scope: Backend

#46882 feat(crons): Add environment selector to crons list page
  static/app/views/monitors/components/row.tsx
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#46819 feat(crons): Filter monitor details to specified environment
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/components/monitorHeader.tsx
  static/app/views/monitors/components/monitorIssues.tsx
  static/app/views/monitors/components/monitorStats.tsx
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#46790 feat(spurl-param): Register a new span grouping strategy
  src/sentry/spans/grouping/strategy/base.py
  src/sentry/spans/grouping/strategy/config.py
Labels: Scope: Backend

#45816 ref(hybrid-cloud): Denormalize user avatars 2/3
  migrations_lockfile.txt
  src/sentry/migrations/0404_backfill_user_avatars.py
  tests/sentry/migrations/test_0404_backfill_user_avatars.py
Labels: Scope: Backend

#46916 feat(breadcrumbs): Format SQL queries in breadcrumbs
  src/sentry/api/serializers/models/event.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/serializers/test_event.py
Labels: Scope: Backend

#46956 ref(perf): Add VCD to discover homepage
  static/app/views/discover/table/index.tsx
Labels: Scope: Frontend

#46953 feat(integrations): Add `host` and `path` to `ApiError`
  src/sentry/shared_integrations/exceptions/base.py
Labels: Scope: Backend

#46959 fix(integration): Add guard for nullable error text
  src/sentry/integrations/github/client.py
Labels: Scope: Backend

#46921 feat(hc): Allow non-abstract methods in RPC interface
  src/sentry/services/hybrid_cloud/integration/__init__.py
  src/sentry/services/hybrid_cloud/rpc.py
  src/sentry/services/hybrid_cloud/user/__init__.py
Labels: Scope: Backend

#46894 fix(deletions) Reorder project relations to fix stuck deletions
  src/sentry/deletions/defaults/project.py
  tests/sentry/deletions/test_project.py
Labels: Scope: Backend

#46965 fix(api-tokens): Implicit userId to be the superuser's user id
  src/sentry/api/endpoints/api_tokens.py
  tests/sentry/api/endpoints/test_api_tokens.py
Labels: Scope: Backend

#46966 fix(issue-platform): fix project settings
  src/sentry/api/endpoints/project_details.py
Labels: Scope: Backend

#46968 fix(crons): Fix undefined monitor leading to broken url
  static/app/views/monitors/components/row.tsx
Labels: Scope: Frontend

#46958 feat(analytics): adds issue type and category to issue resolve analytics
  src/sentry/analytics/events/issue_resolved.py
  src/sentry/api/serializers/models/group.py
  src/sentry/receivers/features.py
  src/sentry/tasks/integrations/sync_status_inbound.py
  tests/snuba/api/serializers/test_group.py
Labels: Scope: Backend

#46884 feat(performance): adds special case for transaction tags
  static/app/components/events/eventTags/eventTagsPill.tsx
  static/app/components/events/eventTags/index.spec.tsx
  static/app/components/events/eventTags/index.tsx
  static/app/views/performance/traceDetails/styles.tsx
Labels: Scope: Frontend

#46961 feat(perf-issues): don't use span hash for fingerprinting consecutive http
  src/sentry/utils/performance_issues/base.py
  src/sentry/utils/performance_issues/detectors/consecutive_http_detector.py
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_consecutive_http_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_performance_detection.py
Labels: Scope: Backend

#46969 fix(migration) Fix migration encountering pickle errors
  src/sentry/migrations/0404_backfill_user_avatars.py
Labels: Scope: Backend

#46974 fix(issues-platform): serialize the option
  src/sentry/api/endpoints/project_details.py
Labels: Scope: Backend

#46924 fix(replays): correct archive query
  src/sentry/replays/query.py
  src/sentry/replays/testutils.py
Labels: Scope: Backend

#46889 feat(crons): Warn users they are deleting additional monitor environments
  static/app/views/monitors/components/row.tsx
Labels: Scope: Frontend

#46973 ref(crons): Remove deprecated monitor fields from frontend
  static/app/views/monitors/components/monitorBadge.tsx
  static/app/views/monitors/components/monitorForm.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#46970 ref(crons): Use `monitor_slug` over `monitor_id`
  src/sentry/api/urls.py
  src/sentry/apidocs/parameters.py
  src/sentry/conf/server.py
  src/sentry/monitors/endpoints/base.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_details.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_index.py
  src/sentry/monitors/endpoints/organization_monitor_checkin_index.py
  src/sentry/monitors/endpoints/organization_monitor_details.py
  src/sentry/monitors/validators.py
  src/sentry/testutils/cases.py
  src/sentry/utils/monitors.py
  tests/sentry/monitors/endpoints/test_monitor_ingest_checkin_details.py
Labels: Scope: Backend

#46907 ref(rulesnooze): Model changes
  migrations_lockfile.txt
  src/sentry/migrations/0405_rulesnooze_user_null.py
  src/sentry/models/rulesnooze.py
  tests/sentry/models/test_rulesnooze.py
Labels: Scope: Backend

#46986 Revert "ref: use hashed frontend assets configmap for urls"
  requirements-dev-frozen.txt
  requirements-dev.txt
  src/sentry/utils/assets.py
  src/sentry/web/client_config.py
  tests/sentry/utils/test_assets.py
  tests/sentry/web/frontend/generic/test_static_media.py
Labels: Scope: Backend

#46985 fix(crons): Allow page filter bar to widen
  static/app/views/monitors/monitors.tsx
Labels: Scope: Frontend

#46979 feat(ecosystem): Add project ownership analytics
  static/app/components/modals/issueOwnershipRuleModal.tsx
  static/app/utils/analytics/integrations/index.ts
  static/app/views/settings/organizationIntegrations/abstractIntegrationDetailedView.tsx
  static/app/views/settings/project/projectOwnership/editRulesModal.tsx
  static/app/views/settings/project/projectOwnership/modal.tsx
  static/app/views/settings/project/projectOwnership/ownerInput.tsx
Labels: Scope: Frontend

#46980 feat(perf-issues): set a default project option
  src/sentry/issues/utils.py
  src/sentry/projectoptions/defaults.py
Labels: Scope: Backend

#46641 fix(commit-context): Fix commit message field
  src/sentry/tasks/commit_context.py
Labels: Scope: Backend

#46928 ref(sourcemaps): Improve queries in artifact bundles endpoints
  src/sentry/api/endpoints/project_artifact_bundle_file_details.py
  src/sentry/api/endpoints/project_artifact_bundle_files.py
Labels: Scope: Backend

#46780 build: Add script to build & minify loader
  .eslintignore
  .eslintrc.js
  package.json
  scripts/build-js-loader.ts
  src/sentry/templates/sentry/js-sdk-loader.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.min.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.ts
  tsconfig.json
  yarn.lock
Labels: Scope: Frontend, Scope: Backend

#46934 ref(sourcemaps): Add serializers to UI endpoints of artifact bundles
  src/sentry/api/endpoints/artifact_bundles.py
  src/sentry/api/endpoints/project_artifact_bundle_files.py
  src/sentry/api/serializers/models/artifactbundle.py
Labels: Scope: Backend

#46994 feat(loader): Add default debug/tracing/replay config for loader
  src/sentry/web/frontend/js_sdk_loader.py
  tests/sentry/web/frontend/test_js_sdk_loader.py
Labels: Scope: Backend

#46995 feat(loader): Ensure default integrations are added & work for performance
  src/sentry/templates/sentry/js-sdk-loader.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.min.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.ts
Labels: Scope: Frontend, Scope: Backend

#46852 feat(tx-clusterer): Bump clustering rule lifetimes
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/ingest/transaction_clusterer/rules.py
  src/sentry/ingest/transaction_clusterer/tasks.py
  tests/sentry/ingest/test_transaction_clusterer.py
Labels: Scope: Backend

#47007 ref(tx-clusterer): Log discarded transactions as a measurement
  src/sentry/ingest/transaction_clusterer/rules.py
Labels: Scope: Backend

#46971 feat(profiling): Update designs for profile previews
  static/app/components/events/interfaces/spans/gapSpanDetails.tsx
  static/app/components/events/interfaces/spans/spanTreeModel.tsx
  static/app/components/events/interfaces/spans/waterfallModel.spec.tsx
  static/app/components/profiling/flamegraph/flamegraphPreview.tsx
  static/app/components/profiling/flamegraph/flamegraphSpanTooltip.tsx
  static/app/utils/profiling/colors/utils.tsx
  static/app/utils/profiling/profile/sampledProfile.tsx
  static/app/utils/profiling/renderers/flamegraphRenderer2D.tsx
  static/app/utils/profiling/renderers/spansRenderer.tsx
  static/app/utils/profiling/spanTree.spec.tsx
  static/app/utils/profiling/spanTree.tsx
Labels: Scope: Frontend

#46323 feat(hybrid-cloud) Add silo limiter for celery tasks
  src/sentry/tasks/base.py
  tests/sentry/tasks/test_base.py
Labels: Scope: Backend

#46996 feat(loader): Add analytics for loader-based onboarding
  static/app/utils/analytics/onboardingAnalyticsEvents.tsx
  static/app/views/onboarding/setupDocs.tsx
  static/app/views/onboarding/setupDocsLoader.tsx
Labels: Scope: Frontend

#47022 chore(mobile): Adds a comment to device.class field
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#46922 fix(replays): delete blobs regardless of storage mechanism
  src/sentry/replays/tasks.py
Labels: Scope: Backend

#47027 fix(perf-issue): Revert "Revert "feat(perf-issues): set a default project option (#469…
  src/sentry/issues/utils.py
  src/sentry/projectoptions/defaults.py
Labels: Scope: Backend

#47024 fix(issues-platform): Read initial state of the project options
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#46899 migration(crons): Clean up orphaned monitors
  migrations_lockfile.txt
  src/sentry/migrations/0406_monitor_cleanup.py
  tests/sentry/migrations/test_0406_monitor_cleanup.py
Labels: Scope: Backend

#46983 feat(crons): Allow searching by slug on monitors list page
  src/sentry/monitors/endpoints/organization_monitors.py
  tests/sentry/monitors/endpoints/test_organization_monitors.py
Labels: Scope: Backend

#47038 feat(issue-platform): add more metrics to debug performance issues
  src/sentry/issues/occurrence_consumer.py
Labels: Scope: Backend

#47034 fix(replays): computing styles on every tick instead inline style.width
  static/app/components/replays/player/scrubber.tsx
  static/app/components/replays/progress.tsx
Labels: Scope: Frontend

#47033 fix(replays): network sort by size
  static/app/views/replays/detail/network/useSortNetwork.tsx
Labels: Scope: Frontend

#47032 feat(replays): align dom events ts btn to console
  static/app/views/replays/detail/timestampButton.tsx
Labels: Scope: Frontend

#46975 ref(crons): Upgrade croniter for bugfixes
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend
