Repository getsentry/sentry, pull requests merged in 2023-11, with the labels that each got.

#59141 fix(browser-starfish): ignore browser-extensions in resource module
  static/app/views/performance/browser/resources/utils/useResourceDomansQuery.ts
  static/app/views/performance/browser/resources/utils/useResourcePagesQuery.ts
  static/app/views/performance/browser/resources/utils/useResourcesQuery.ts
Labels: Scope: Frontend

#58973 feat(bug reports): Optimistically update the feedback items mutation is finished
  static/app/components/feedback/decodeFeedbackId.tsx
  static/app/components/feedback/feedbackDataContext.tsx
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/feedbackItemLoader.tsx
  static/app/components/feedback/getFeedbackItemQueryKey.tsx
  static/app/components/feedback/list/feedbackList.tsx
  static/app/components/feedback/list/feedbackListHeader.tsx
  static/app/components/feedback/list/feedbackListItem.tsx
  static/app/components/feedback/useBulkMutateFeedback.tsx
  static/app/components/feedback/useCurrentFeedbackId.tsx
  static/app/components/feedback/useFeedbackCache.tsx
  static/app/components/feedback/useFeedbackItemQueryKey.tsx
  static/app/components/feedback/useFeedbackListQueryKey.tsx
  static/app/components/feedback/useFeedbackQueryKeys.tsx
  static/app/components/feedback/useFetchFeedbackData.tsx
  static/app/components/feedback/useFetchFeedbackInfiniteListData.tsx
  static/app/components/feedback/useMutateFeedback.tsx
  static/app/utils/dates.spec.tsx
  static/app/utils/dates.tsx
  static/app/utils/queryClient.tsx
  static/app/views/feedback/feedbackListPage.tsx
Labels: Scope: Frontend

#59147 ref(feedback): when bulk resolve/unresolve, header checkbox unchecks
  static/app/components/feedback/list/feedbackList.tsx
  static/app/components/feedback/list/feedbackListHeader.tsx
  static/app/components/feedback/list/useListItemCheckboxState.tsx
Labels: Scope: Frontend

#59169 fix(issues): Fix infinite react rerenders in issue list
  static/app/components/replays/useReplaysCount.tsx
Labels: Scope: Frontend

#59145 feat(browser-starfish): make things more consistent in resource module
  static/app/views/performance/browser/resources/jsCssView/resourceTable.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/resourceInfo.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/resourceSummaryCharts.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/resourceSummaryTable.tsx
  static/app/views/starfish/views/spans/types.tsx
Labels: Scope: Frontend

#59131 chore(avatars) Use avatarUrl in UI components
  fixtures/js-stubs/organization.tsx
  static/app/components/avatar/baseAvatar.tsx
  static/app/components/avatar/docIntegrationAvatar.tsx
  static/app/components/avatar/index.spec.tsx
  static/app/components/avatar/organizationAvatar.tsx
  static/app/components/avatar/sentryAppAvatar.tsx
  static/app/components/avatar/teamAvatar.tsx
  static/app/components/avatar/userAvatar.tsx
  static/app/types/core.tsx
Labels: Scope: Frontend

#59168 feat(starfish): Add profile_id to indexed spans query builder
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#59170 feat(starfish): Span samples return profile ids
  src/sentry/api/endpoints/organization_events_meta.py
Labels: Scope: Backend

#59043 fix(ui) Fix domains used in preloading
  src/sentry/templates/sentry/layout.html
  src/sentry/templates/sentry/partial/preload-data.html
  static/app/bootstrap/index.tsx
  static/app/index.tsx
  static/app/types/system.tsx
  static/index.ejs
Labels: Scope: Frontend, Scope: Backend

#59149 feat(starfish-web-vitals): Small UI iterations/ bug fixes.
  static/app/views/performance/browser/webVitals/components/pageOverviewSidebar.tsx
  static/app/views/performance/browser/webVitals/components/recommendations.tsx
  static/app/views/performance/browser/webVitals/components/webVitalDescription.tsx
  static/app/views/performance/browser/webVitals/pageOverWebVitalsTagDetailPanel.tsx
  static/app/views/performance/browser/webVitals/pageOverview.tsx
  static/app/views/performance/browser/webVitals/pageOverviewWebVitalsDetailPanel.tsx
Labels: Scope: Frontend

#58974 feat(metrics-extraction): Add widget columns to extraction
  src/sentry/incidents/logic.py
  src/sentry/options/defaults.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/snuba/metrics/extraction.py
  src/sentry/snuba/referrer.py
  src/sentry/tasks/check_am2_compatibility.py
  tests/sentry/relay/config/test_metric_extraction.py
Labels: Scope: Backend

#59118 ref(metrics): Automatically infer the Dataset
  src/sentry/snuba/metrics_layer/query.py
  tests/snuba/test_metrics_layer.py
Labels: Scope: Backend

#59166 feat(replays): New hybrid timeline design
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/player/useScrubberMouseTracking.tsx
  static/app/components/replays/replayContext.tsx
Labels: Scope: Frontend

#58736 ref(backup): Use local impl of lost_password_hash service
  src/sentry/models/user.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#59178 feat(bug reports): Allow "check all" to really check all items
  static/app/components/feedback/list/feedbackList.tsx
  static/app/components/feedback/list/feedbackListHeader.tsx
  static/app/components/feedback/list/feedbackListItem.tsx
  static/app/components/feedback/list/useListItemCheckboxState.tsx
  static/app/components/feedback/useFeedbackCache.tsx
  static/app/components/feedback/useFetchFeedbackInfiniteListData.tsx
  static/app/components/feedback/useMutateFeedback.tsx
Labels: Scope: Frontend

#59124 feat(provisioning): add partnership:restricted flag to OrganizationMember model
  migrations_lockfile.txt
  src/sentry/migrations/0585_add_orgmember_partnership_restricted_flag.py
  src/sentry/models/organizationmember.py
Labels: Scope: Backend

#58940 feat(notifications): Add workflow notifications for teams
  src/sentry/models/groupsubscription.py
  src/sentry/notifications/notificationcontroller.py
  src/sentry/notifications/notifications/activity/assigned.py
  tests/sentry/models/test_groupsubscription.py
  tests/sentry/notifications/notifications/test_assigned.py
  tests/sentry/notifications/test_notificationcontroller.py
  tests/sentry/notifications/utils/test_participants.py
Labels: Scope: Backend

#59181 feat(starfish): Separate samples for release 1 and release 2
  static/app/views/starfish/components/samplesTable/spanSamplesTable.tsx
  static/app/views/starfish/queries/useSpanMetrics.tsx
  static/app/views/starfish/queries/useSpanMetricsSeries.tsx
  static/app/views/starfish/queries/useSpanSamples.tsx
  static/app/views/starfish/types.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/index.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/samples/index.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/samples/samplesContainer.tsx
  static/app/views/starfish/views/spanSummaryPage/sampleList/durationChart/index.tsx
  static/app/views/starfish/views/spanSummaryPage/sampleList/sampleInfo/index.tsx
  static/app/views/starfish/views/spanSummaryPage/sampleList/sampleTable/sampleTable.tsx
Labels: Scope: Frontend

#59163 Release status health api fixes
  src/sentry/api/endpoints/release_thresholds/release_threshold_status_index.py
  tests/sentry/api/endpoints/release_thresholds/test_release_threshold_status.py
Labels: Scope: Backend

#59190 fix(browser-starfish): filtering resources modules inconsistent
  static/app/views/performance/browser/resources/jsCssView/index.tsx
  static/app/views/performance/browser/resources/jsCssView/resourceTable.tsx
  static/app/views/performance/browser/resources/shared/domainSelector.tsx
  static/app/views/performance/browser/resources/shared/selectControlWithProps.tsx
  static/app/views/performance/browser/resources/utils/useResourceDomansQuery.ts
  static/app/views/performance/browser/resources/utils/useResourcePagesQuery.ts
  static/app/views/performance/browser/resources/utils/useResourcesQuery.ts
Labels: Scope: Frontend

#59146 feat(sdk): Upgrade `@sentry` SDKs to v7.77.0
  package.json
  yarn.lock
Labels: Scope: Frontend

#59150 fix(hybrid-cloud): Adds audit log IP Address fallback
  src/sentry/models/auditlogentry.py
Labels: Scope: Backend

#59040 feat(metrics): Update send_metrics.py
  bin/send_metrics.py
Labels: Scope: Backend

#58941 fix(issue-platform): Add default value for payload type
  src/sentry/issues/occurrence_consumer.py
  src/sentry/issues/producer.py
  tests/sentry/issues/test_occurrence_consumer.py
Labels: Scope: Backend

#59188 feat(starfish): Add pages list pagination
  static/app/views/performance/browser/webVitals/pagePerformanceTable.tsx
  static/app/views/performance/browser/webVitals/utils/useProjectWebVitalsQuery.tsx
Labels: Scope: Frontend

#59196 ref(ui): if user title is [Filtered], display ? in letter avatar
  static/app/components/avatar/baseAvatar.tsx
Labels: Scope: Frontend

#58942 ref(team-workflow): Update team validation
  src/sentry/notifications/helpers.py
  tests/sentry/notifications/test_helpers.py
  tests/sentry/notifications/test_notificationcontroller.py
Labels: Scope: Backend

#58865 fix(jira-server): adds project if missing in issue schema
  src/sentry/integrations/jira_server/integration.py
  tests/sentry/integrations/jira_server/test_integration.py
Labels: Scope: Backend

#59204 chore(starfish): Use the Version component and link out to release
  static/app/views/starfish/views/screens/screenLoadSpans/samples/samplesContainer.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/sidebar.tsx
Labels: Scope: Frontend

#59192 feat(starfish): Updates Webvitals page overview design and layout
  static/app/views/performance/browser/webVitals/components/pageOverviewSidebar.tsx
  static/app/views/performance/browser/webVitals/components/webVitalMeters.tsx
  static/app/views/performance/browser/webVitals/pageOverview.tsx
  static/app/views/performance/browser/webVitals/pageOverviewWebVitalsDetailPanel.tsx
  static/app/views/performance/browser/webVitals/pageSamplePerformanceTable.tsx
Labels: Scope: Frontend

#59197 fix(jira-server): Fetch project priorities using safe API
  src/sentry/integrations/jira_server/client.py
  src/sentry/integrations/jira_server/integration.py
  tests/sentry/integrations/jira_server/test_integration.py
Labels: Scope: Backend

#59172 feat: Add API endpoints for workflow unsubscribe and digest unsubscribe
  src/sentry/api/authentication.py
  src/sentry/api/endpoints/organization_unsubscribe.py
  src/sentry/api/urls.py
  src/sentry/web/urls.py
  tests/sentry/api/endpoints/test_organization_unsubscribe.py
Labels: Scope: Backend

#59208 feat(stats-detectors): Overlay throughput on chart for regression issues
  static/app/components/events/eventStatisticalDetector/breakpointChart.tsx
  static/app/components/events/eventStatisticalDetector/functionBreakpointChart.tsx
  static/app/components/events/eventStatisticalDetector/lineChart.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#59212 fix(starfish): Use project param from row in profile URL
  static/app/views/starfish/components/samplesTable/spanSamplesTable.tsx
Labels: Scope: Frontend

#59202 ref(analytics): Add actor type to Slack notification analytics
  src/sentry/integrations/slack/analytics.py
  tests/sentry/notifications/test_notifications.py
Labels: Scope: Backend

#59214 feat(feedback): migration for has feedbacks flag
  migrations_lockfile.txt
  src/sentry/migrations/0586_add_has_feedbacks_flag.py
  src/sentry/models/project.py
Labels: Scope: Backend

#59213 fix(stat-detectors): Quote transaction name in RCA
  src/sentry/api/endpoints/organization_events_root_cause_analysis.py
Labels: Scope: Backend

#59205 fix(pageFilters): Fix reset issue when clicking on sidebar link
  static/app/components/organizations/pageFilters/container.tsx
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/sidebarItem.tsx
  static/app/components/sidebar/utils.tsx
Labels: Scope: Frontend

#59189 feat(replays): Replay layout center line and zoom labels
  static/app/components/replays/player/scrubber.tsx
  static/app/components/replays/replayContext.tsx
  static/app/components/replays/replayController.tsx
Labels: Scope: Frontend

#59171 fix(issue-platform): insert occurrence into event stream after _get_or_create_group_environment is ran
  src/sentry/issues/ingest.py
  tests/sentry/issues/test_ingest.py
Labels: Scope: Backend

#59194 feat(suspect-commits): Add more logging to GitHub blame fetching
  src/sentry/integrations/github/blame.py
  src/sentry/integrations/github/client.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/mixins/commit_context.py
  src/sentry/integrations/utils/commit_context.py
  tests/sentry/integrations/github/test_client.py
  tests/sentry/tasks/test_commit_context.py
Labels: Scope: Backend

#59062 feat(feedback): add assignment component for single feedbacks
  static/app/components/assigneeSelectorDropdown.tsx
  static/app/components/feedback/feedbackItem/feedbackAssignedTo.tsx
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/feedbackViewers.tsx
  static/app/components/feedback/useMutateFeedback.tsx
  static/app/components/group/assignedTo.tsx
  static/app/views/discover/table/quickContext/issueContext.tsx
Labels: Scope: Frontend

#59025 feat(provisioning): Default team RPC
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/services/hybrid_cloud/organization/service.py
  tests/sentry/hybrid_cloud/test_team.py
Labels: Scope: Backend

#59165 ref(hc): Add prefixes to RPC metrics tags
  src/sentry/services/hybrid_cloud/rpc.py
Labels: Scope: Backend

#59066 fix(notifications): HC bug serializing external provider
  src/sentry/incidents/action_handlers.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/utils/participants.py
  src/sentry/services/hybrid_cloud/notifications/impl.py
  src/sentry/services/hybrid_cloud/notifications/service.py
  tests/sentry/api/endpoints/test_organization_invite_request_index.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/notifications/utils/test_participants.py
Labels: Scope: Backend

#59032 feat(feedback): process feedbacks in ingestion
  src/sentry/event_manager.py
  src/sentry/ingest/consumer/processors.py
  src/sentry/tasks/store.py
  tests/sentry/ingest/ingest_consumer/test_ingest_consumer_processing.py
Labels: Scope: Backend

#59152 feat(provisioning): partnership user api restrictions
  src/sentry/api/endpoints/organization_member/details.py
  src/sentry/scim/endpoints/members.py
  tests/sentry/api/endpoints/test_organization_member_details.py
  tests/sentry/api/endpoints/test_scim_user_details.py
Labels: Scope: Backend

#59068 feat(crons): Show environment name in checkin table
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#58309 feat(issue-platform): Add support for unresolved statuses in issue platform API
  src/sentry/issues/occurrence_status_change.py
  src/sentry/issues/status_change_consumer.py
  tests/sentry/issues/test_producer.py
  tests/sentry/issues/test_status_change_consumer.py
Labels: Scope: Backend

#58666 feat(metrics): Add option to disable schema validation
  src/sentry/options/defaults.py
  src/sentry/sentry_metrics/consumers/indexer/processing.py
  src/sentry/sentry_metrics/consumers/indexer/schema_validator.py
  tests/sentry/sentry_metrics/consumers/test_schema_validator.py
Labels: Scope: Backend

#59234 ref(replays): move viewers section to next to description
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/feedbackItemSection.tsx
  static/app/components/feedback/feedbackItem/feedbackViewers.tsx
Labels: Scope: Frontend

#59155 feat(feedback): introduce banner with link to set up docs
  static/app/components/feedback/feedbackSetupBanner.tsx
  static/app/views/feedback/feedbackListPage.tsx
Labels: Scope: Frontend

#59134 feat(feedback): render assigned user in list item
  static/app/components/feedback/list/feedbackListItem.tsx
Labels: Scope: Frontend

#59229 fix(issues-platform): get stack traces for when we fail to validate with the new schema
  src/sentry/issues/occurrence_consumer.py
  tests/sentry/issues/test_occurrence_consumer.py
Labels: Scope: Backend

#59237 ref(feedback): fix purple-on-purple color scheme
  static/app/components/checkbox.tsx
  static/app/components/feedback/list/feedbackListItem.tsx
Labels: Scope: Frontend

#58712 feat(crons): Add new monitor manual creation flow
  static/app/views/monitors/components/cronsLandingPanel.tsx
  static/app/views/monitors/components/monitorCreateForm.tsx
  static/app/views/monitors/components/monitorForm.tsx
  static/app/views/monitors/utils.tsx
Labels: Scope: Frontend

#59246 perf(issues): Move annotated text useProjects into subcomponent
  static/app/components/events/meta/annotatedText/annotatedTextValue.tsx
  static/app/components/events/meta/annotatedText/index.tsx
Labels: Scope: Frontend

#58905 feat(crons): Add endpoint to mock schedule
  src/sentry/api/api_owners.py
  src/sentry/api/urls.py
  src/sentry/monitors/endpoints/organization_monitor_schedule_sample_data.py
  tests/sentry/monitors/endpoints/test_organization_monitor_schedule_sample_data.py
Labels: Scope: Backend

#59252 chore(bug reports): Mark new User Feedback as beta!
  static/app/components/sidebar/index.tsx
Labels: Scope: Frontend

#59091 Always upload Release as Artifact Bundles
  src/sentry/api/endpoints/organization_release_assemble.py
  tests/sentry/api/endpoints/test_organization_release_assemble.py
Labels: Scope: Backend

#59081 feat(alerts): on demand field support
  static/app/utils/onDemandMetrics/constants.tsx
Labels: Scope: Frontend

#58996 Automatically finish stuck reprocessing
  src/sentry/api/serializers/models/group.py
  src/sentry/reprocessing2.py
Labels: Scope: Backend

#59256 ref(sdk-crashes): Add path replacement names
  src/sentry/utils/sdk_crashes/cocoa_sdk_crash_detector.py
  src/sentry/utils/sdk_crashes/event_stripper.py
  src/sentry/utils/sdk_crashes/sdk_crash_detection.py
  src/sentry/utils/sdk_crashes/sdk_crash_detector.py
  tests/sentry/utils/sdk_crashes/test_event_stripper.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection.py
Labels: Scope: Backend

#59090 Remove obsolete JS Processor
  pyproject.toml
  src/sentry/lang/java/plugin.py
  src/sentry/lang/javascript/plugin.py
  src/sentry/lang/javascript/processor.py
  src/sentry/lang/javascript/utils.py
  tests/relay_integration/lang/java/test_plugin.py
  tests/sentry/lang/javascript/test_errormapping.py
  tests/sentry/lang/javascript/test_processor.py
  tests/sentry/lang/javascript/test_utils.py
Labels: Scope: Backend

#56464 feat(api): Add symbol sources endpoint
  src/sentry/api/endpoints/project_symbol_sources.py
  src/sentry/api/urls.py
  src/sentry/apidocs/examples/project_examples.py
  src/sentry/apidocs/parameters.py
  src/sentry/lang/native/sources.py
  tests/sentry/api/endpoints/test_project_symbol_sources.py
Labels: Scope: Backend

#59217 feat(perf): Register feature flag for Query view percentiles
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#59159 fix(onboarding): Render the list of Go frameworks in create project UI and framework modal
  static/app/data/platformPickerCategories.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#59254 chore(starfish): Screen load module UI clean up
  static/app/views/starfish/components/releaseSelector.tsx
  static/app/views/starfish/utils/centerTruncate.ts
  static/app/views/starfish/views/screens/index.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/table.tsx
Labels: Scope: Frontend

#59257 ref(sdk-crashes): Extract building configs
  src/sentry/tasks/post_process.py
  src/sentry/utils/sdk_crashes/build_sdk_crash_detection_configs.py
Labels: Scope: Backend

#59193 tests(hybrid-cloud): Stabilize access log middleware tests
  src/sentry/api/bases/organization.py
  tests/sentry/middleware/test_access_log_middleware.py
Labels: Scope: Backend

#59269 feat(ddm): sampled trace table
  static/app/components/sidebar/index.tsx
  static/app/views/ddm/ddm.tsx
  static/app/views/ddm/traceTable.tsx
Labels: Scope: Frontend

#59187 fix(ui) Send preload requests to region urls v2
  src/sentry/templates/sentry/layout.html
  src/sentry/templates/sentry/partial/preload-data.html
  static/app/bootstrap/index.tsx
  static/app/index.tsx
  static/app/types/system.tsx
  static/index.ejs
Labels: Scope: Frontend, Scope: Backend

#59271 fix(starfish): fixes transaction link in web vitals page overview
  static/app/views/performance/browser/webVitals/pageSamplePerformanceTable.tsx
Labels: Scope: Frontend

#59273 chore(starfish): Show fewer characters in release selector
  static/app/views/starfish/components/releaseSelector.tsx
Labels: Scope: Frontend

#59221 fix(hybrid-cloud): Prevent cross silo accesses on serializing jira configs
  src/sentry/api/endpoints/integrations/organization_integrations/index.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/jira_server/integration.py
  static/app/data/controlsiloUrlPatterns.ts
  tests/sentry/api/endpoints/test_organization_integrations.py
Labels: Scope: Frontend, Scope: Backend

#59275 feat(ddm): Use new metrics layer
  static/app/utils/metrics.tsx
Labels: Scope: Frontend

#58175 feat(github): Create GH/GH Enterprise ticket action
  src/sentry/api/endpoints/project_rules.py
  src/sentry/constants.py
  src/sentry/integrations/github/__init__.py
  src/sentry/integrations/github/actions/create_ticket.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/github/issues.py
  src/sentry/integrations/mixins/issues.py
  src/sentry/rules/actions/integrations/create_ticket/base.py
  tests/sentry/api/endpoints/test_project_rules_configuration.py
  tests/sentry/integrations/github/test_ticket_action.py
Labels: Scope: Backend

#59247 feat(metrics_extraction): Decouple alert and widget extraction
  src/sentry/relay/config/metric_extraction.py
  tests/sentry/relay/config/test_metric_extraction.py
Labels: Scope: Backend

#58702 remove unused features ( front-end)
  static/app/components/events/aiSuggestedSolution/index.tsx
  static/app/data/forms/organizationGeneralSettings.tsx
  static/app/views/issueDetails/resourcesAndMaybeSolutions.tsx
Labels: Scope: Frontend

#59277 chore(on_demand): spec generation metrics
  src/sentry/relay/config/metric_extraction.py
Labels: Scope: Backend

#59274 feat(perf): Add basic percentile selector to Query Details duration chart
  static/app/views/performance/database/databaseSpanSummaryPage.tsx
  static/app/views/performance/database/durationAggregateSelector.tsx
  static/app/views/performance/database/settings.ts
  static/app/views/starfish/components/chartPanel.tsx
  static/app/views/starfish/queries/useSpanMetricsSeries.tsx
Labels: Scope: Frontend

#57448 feat(metrics): Integrate new metrics layer into the metrics API
  src/sentry/api/endpoints/organization_metrics.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/sentry_metrics/querying/__init__.py
  src/sentry/sentry_metrics/querying/api.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/api/endpoints/test_organization_metrics.py
  tests/sentry/sentry_metrics/querying/test_api.py
Labels: Scope: Backend

#59251 perf(discover): Disable resize observer on cell dropdown
  static/app/components/compactSelect/control.tsx
  static/app/components/dropdownMenu/index.tsx
  static/app/views/discover/table/cellAction.tsx
Labels: Scope: Frontend

#58821 feat(relocation): Add relocation password reset page
  src/sentry/models/lostpasswordhash.py
  src/sentry/templates/sentry/account/relocate/confirm.html
  src/sentry/templates/sentry/account/relocate/failure.html
  src/sentry/templates/sentry/debug/mail/preview.html
  src/sentry/templates/sentry/emails/relocate_account.html
  src/sentry/templates/sentry/emails/relocate_account.txt
  src/sentry/web/debug_urls.py
  src/sentry/web/forms/accounts.py
  src/sentry/web/frontend/accounts.py
  src/sentry/web/frontend/debug/mail.py
  src/sentry/web/urls.py
  tests/sentry/models/test_lostpasswordhash.py
  tests/sentry/web/forms/test_accounts.py
  tests/sentry/web/frontend/test_accounts.py
Labels: Scope: Backend

#59186 chore(login): update the login banners
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#59127 feat(issue-stream): Find search from backend
  src/sentry/api/endpoints/organization_group_index.py
  src/sentry/api/helpers/group_index/index.py
  tests/snuba/api/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#59278 ref(on-demand): Emit gauges in minimetrics
  src/sentry/metrics/minimetrics.py
  src/sentry/options/defaults.py
  tests/sentry/metrics/test_minimetrics.py
Labels: Do Not Merge, Scope: Backend

#58969 feat(stats-detectors): Add per project ratelimit for ema detection
  src/sentry/options/defaults.py
  src/sentry/statistical_detectors/algorithm.py
  src/sentry/statistical_detectors/detector.py
  src/sentry/tasks/statistical_detectors.py
  tests/sentry/statistical_detectors/test_algorithm.py
  tests/sentry/tasks/test_statistical_detectors.py
Labels: Scope: Backend

#59222 feat(provisioning): return partnership flag in API
  src/sentry/api/serializers/models/organization_member/base.py
  src/sentry/api/serializers/models/organization_member/response.py
  src/sentry/apidocs/examples/organization_examples.py
Labels: Scope: Backend

#59253 meta(crons): Update ownership + publishing for crons
  src/sentry/monitors/endpoints/monitor_ingest_checkin_attachment.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_index.py
  src/sentry/monitors/endpoints/organization_monitor_checkin_attachment.py
  src/sentry/monitors/endpoints/organization_monitor_checkin_index.py
  src/sentry/monitors/endpoints/organization_monitor_details.py
  src/sentry/monitors/endpoints/organization_monitor_index.py
  src/sentry/monitors/endpoints/organization_monitor_index_stats.py
  src/sentry/monitors/endpoints/organization_monitor_stats.py
Labels: Scope: Backend

#59216 feat(feedback): feedback analytic event and modification on first rec…
  src/sentry/analytics/events/__init__.py
  src/sentry/analytics/events/first_feedback_sent.py
  src/sentry/feedback/usecases/create_feedback.py
  src/sentry/receivers/onboarding.py
  src/sentry/signals.py
  tests/sentry/feedback/test_feedback_ingest.py
Labels: Scope: Backend

#59291 ref: fix more model managers not using ClassVar
  pyproject.toml
  src/sentry/db/models/paranoia.py
  src/sentry/incidents/models.py
  src/sentry/models/integrations/external_issue.py
  src/sentry/models/integrations/sentry_app.py
  src/sentry/models/integrations/sentry_app_installation.py
  src/sentry/models/notificationsetting.py
  src/sentry/models/organizationmember.py
Labels: Scope: Backend

#59276 perf(assigneeselector): lazy compute assignees
  static/app/components/assigneeSelectorDropdown.tsx
  static/app/components/dropdownAutoComplete/index.tsx
  static/app/components/dropdownAutoComplete/menu.tsx
  static/app/components/forms/fields/choiceMapperField.tsx
Labels: Scope: Frontend

#59228 feat(provisioning): partnership user UI restrictions
  fixtures/js-stubs/member.tsx
  fixtures/js-stubs/members.tsx
  static/app/types/organization.tsx
  static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/organizationMembers/organizationMemberRow.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.tsx
Labels: Scope: Frontend

#59293 ref: add minimal stubs for uwsgi / uwsgidecorators
  fixtures/stubs-for-mypy/uwsgi.pyi
  fixtures/stubs-for-mypy/uwsgidecorators.pyi
  pyproject.toml
Labels: Scope: Backend

#59129 feat(provisioning): project rpc
  src/sentry/services/hybrid_cloud/project/impl.py
  src/sentry/services/hybrid_cloud/project/service.py
  tests/sentry/hybrid_cloud/test_project.py
Labels: Scope: Backend

#59294 ref: add backward compatibility for swapping django-stubs to a fork
  scripts/lib.sh
Labels: Scope: Backend

#59218 feat(feedback): add hasFeedback flag to project serializer
  src/sentry/api/serializers/models/project.py
  tests/sentry/api/serializers/test_project.py
Labels: Scope: Backend

#59297 chore(starfish): Remove aggregate span waterfall in Screen Load
  static/app/views/starfish/views/screens/screenLoadSpans/sidebar.tsx
Labels: Scope: Frontend

#59287 Release threshold status nits
  src/sentry/api/endpoints/release_thresholds/release_threshold_status_index.py
  tests/sentry/api/endpoints/release_thresholds/test_release_threshold_status.py
Labels: Scope: Backend

#59300 fix(starfish): Screenload charts are always 2 columns with full width
  static/app/views/starfish/views/screens/screenLoadSpans/charts.tsx
Labels: Scope: Frontend

#58570 feat(generic-metrics): Add support for gauges
  src/sentry/sentry_metrics/consumers/indexer/batch.py
Labels: Scope: Backend

#59301 fix(starfish): page overview profile link use proper project
  static/app/views/performance/browser/webVitals/pageSamplePerformanceTable.tsx
Labels: Scope: Frontend

#59302 feat(starfish): hides webvitals recommendations for now
  static/app/views/performance/browser/webVitals/pageOverviewWebVitalsDetailPanel.tsx
Labels: Scope: Frontend

#59153 fix(hybrid-cloud): Make wizard interface silo-safe
  src/sentry/api/endpoints/setup_wizard.py
  src/sentry/services/hybrid_cloud/project/impl.py
  src/sentry/services/hybrid_cloud/project/service.py
  src/sentry/services/hybrid_cloud/project_key/impl.py
  src/sentry/services/hybrid_cloud/project_key/model.py
  src/sentry/services/hybrid_cloud/project_key/serial.py
  src/sentry/services/hybrid_cloud/project_key/service.py
  src/sentry/web/frontend/setup_wizard.py
  static/app/data/controlsiloUrlPatterns.ts
  tests/sentry/api/endpoints/test_setup_wizard.py
  tests/sentry/web/frontend/test_setup_wizard.py
Labels: Scope: Frontend, Scope: Backend

#59305 fix(starfish): Replace Pageload header with Screens
  static/app/components/sidebar/index.tsx
  static/app/views/starfish/utils/routeNames.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/index.tsx
Labels: Scope: Frontend

#59108 ref(metrics): Add support for gauges to new metrics layer
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/snuba/dataset.py
  src/sentry/snuba/metrics_layer/query.py
  src/sentry/testutils/cases.py
  tests/snuba/test_metrics_layer.py
Labels: Scope: Backend

#59156 feat(plugins): Add Babel plugin to annotate frontend with React component names
  babel.config.ts
  package.json
  yarn.lock
Labels: Scope: Frontend

#59248 feat(issue-platform): Add toggle to enable/disable escalation detection
  src/sentry/issues/grouptype.py
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#59310 fix(starfish): Clicking span description shouldn't reload page
  static/app/views/starfish/views/screens/screenLoadSpans/table.tsx
Labels: Scope: Frontend

#59241 chore(typing): fix tsdb method calls
  pyproject.toml
  src/sentry/api/endpoints/group_stats.py
  src/sentry/api/endpoints/integrations/sentry_apps/interaction.py
  src/sentry/api/endpoints/internal/stats.py
  src/sentry/api/endpoints/project_group_stats.py
  src/sentry/api/endpoints/project_stats.py
  src/sentry/api/endpoints/project_user_stats.py
  src/sentry/api/endpoints/team_stats.py
  src/sentry/tasks/beacon.py
  src/sentry/tasks/servicehooks.py
  src/sentry/templatetags/sentry_admin_helpers.py
  src/sentry/utils/metrics.py
  src/sentry/utils/mockdata/core.py
  src/sentry/utils/suspect_resolutions/metric_correlation.py
  tests/sentry/api/endpoints/test_group_details.py
  tests/sentry/utils/suspect_resolutions/test_metric_correlation.py
  tests/snuba/api/endpoints/test_group_details.py
Labels: Scope: Backend

#59311 ref: upgrade django-stubs to our fork
  pyproject.toml
  requirements-dev-frozen.txt
  requirements-dev.txt
  scripts/lib.sh
  src/sentry/api/helpers/span_analysis.py
  src/sentry/db/models/base.py
  src/sentry/migrations/0001_squashed_0200_release_indices.py
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/services/http.py
  src/sentry/utils/strings.py
  tests/sentry/auth/test_superuser.py
Labels: Scope: Backend

#59307 feat(starfish-webvitals-opportunity-widget): Adding widget functionality
  static/app/components/compactSelect/control.tsx
  static/app/views/performance/browser/webVitals/components/performanceScoreBreakdownChart.tsx
  static/app/views/performance/browser/webVitals/utils/useProjectWebVitalsTimeseriesQuery.tsx
  static/app/views/performance/landing/views/frontendOtherView.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
  static/app/views/performance/landing/widgets/components/widgetHeader.tsx
  static/app/views/performance/landing/widgets/widgetDefinitions.tsx
  static/app/views/performance/landing/widgets/widgets/stackedAreaChartListWidget.tsx
Labels: Scope: Frontend

#59308 feat(feedback): shim user report embed form to new feedbacks
  src/sentry/feedback/usecases/create_feedback.py
  src/sentry/ingest/userreport.py
  src/sentry/web/frontend/error_page_embed.py
  tests/sentry/web/frontend/test_error_page_embed.py
Labels: Scope: Backend

#59298 fix(github-growth): improve performance of missing members api
  src/sentry/api/endpoints/organization_missing_org_members.py
  src/sentry/tasks/invite_missing_org_members.py
  tests/sentry/api/endpoints/test_organization_missing_org_members.py
Labels: Scope: Backend

#59313 fix(issue-platform): allowing extra fields in StackTrace/Frames
  src/sentry/issues/event.schema.json
  tests/sentry/issues/test_occurrence_consumer.py
Labels: Scope: Backend

#59318 ref(replays): add wrapping to feedback item header actions
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/feedbackItemUsername.tsx
Labels: Scope: Frontend

#59326 fix(feedback): allow feedback in project config
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#59322 ref(feedback): add confirm modal for bulk mutation actions
  static/app/components/feedback/list/feedbackListHeader.tsx
Labels: Scope: Frontend

#59264 perf(issues): optimize chart references and rendering
  static/app/components/charts/miniBarChart.tsx
  static/app/components/stream/group.tsx
  static/app/components/stream/groupChart.tsx
Labels: Scope: Frontend

#58960 feat(replays): try history.replace instead of push for url query state
  static/app/components/replays/useQueryBasedColumnResize.tsx
  static/app/utils/replays/hooks/useFiltersInLocationQuery.tsx
  static/app/views/replays/detail/console/useConsoleFilters.spec.tsx
  static/app/views/replays/detail/errorList/useErrorFilters.spec.tsx
  static/app/views/replays/detail/network/useNetworkFilters.spec.tsx
  static/app/views/replays/detail/perfTable/usePerfFilters.spec.tsx
Labels: Scope: Frontend

#59282 fix(ddm): Add support for distribution in utils
  src/sentry/utils/metrics.py
Labels: Scope: Backend

#59268 feat(ddm): Add gauges support in old metrics layer
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/query.py
  src/sentry/snuba/metrics/query_builder.py
  src/sentry/snuba/metrics/utils.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_organization_metric_data.py
  tests/sentry/snuba/metrics/test_metrics_layer/test_metrics_enhanced_performance.py
  tests/sentry/snuba/metrics/test_query_builder.py
Labels: Scope: Backend

#59279 Move `EventAttachment.mimetype` property into Serializer
  src/sentry/api/serializers/models/eventattachment.py
  src/sentry/models/eventattachment.py
  tests/sentry/api/endpoints/test_event_attachment_details.py
  tests/sentry/api/endpoints/test_event_attachments.py
Labels: Scope: Backend

#58703 ref: Remove unused features ( back-end)
  src/sentry/api/endpoints/event_ai_suggested_fix.py
  src/sentry/apidocs/examples/project_examples.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  tests/sentry/api/endpoints/test_event_ai_suggested_fix.py
Labels: Scope: Backend

#59339 chore(on_demand): spec generation metrics
  src/sentry/relay/config/metric_extraction.py
Labels: Scope: Backend

#59106 feat(metrics): metrics meta support for gauges
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/fields/base.py
Labels: Scope: Backend

#59342 fix(on_demand): device model mapping
  src/sentry/snuba/metrics/extraction.py
  tests/sentry/snuba/test_extraction.py
Labels: Scope: Backend

#59344 fix(ddm): mri selector performance
  static/app/views/ddm/queryBuilder.tsx
Labels: Scope: Frontend

#59296 ref(tsc): Convert `JsonViewer` to FC
  static/app/components/events/attachmentViewers/jsonViewer.spec.tsx
  static/app/components/events/attachmentViewers/jsonViewer.tsx
Labels: Scope: Frontend

#59332 fix(hybrid-cloud): Fix cross-silo access on Jira (again)
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/jira_server/integration.py
Labels: Scope: Backend

#59345 chore(ddm): rename sidebar item
  static/app/components/sidebar/index.tsx
  static/app/views/ddm/ddm.tsx
  static/app/views/ddm/traceTable.tsx
Labels: Scope: Frontend

#59223 feat: Add views for react rendered unsubscribe views
  src/sentry/api/endpoints/organization_unsubscribe.py
  src/sentry/web/urls.py
  static/app/routes.tsx
  static/app/views/unsubscribe/issue.spec.tsx
  static/app/views/unsubscribe/issue.tsx
  static/app/views/unsubscribe/project.spec.tsx
  static/app/views/unsubscribe/project.tsx
Labels: Scope: Frontend, Scope: Backend

#59333 styles(stats-detectors): Update regression details from feedback
  static/app/components/events/eventStatisticalDetector/aggregateSpanDiff.tsx
  static/app/components/events/eventStatisticalDetector/breakpointChart.tsx
  static/app/components/events/eventStatisticalDetector/eventAffectedTransactions.tsx
  static/app/components/events/eventStatisticalDetector/eventComparison/index.tsx
  static/app/components/events/eventStatisticalDetector/lineChart.tsx
  static/app/components/events/eventStatisticalDetector/regressionMessage.spec.tsx
  static/app/components/events/eventStatisticalDetector/regressionMessage.tsx
  static/app/utils/performance/regression/table.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#59329 ref(overlay): Add min width modifier
  static/app/components/compactSelect/control.tsx
  static/app/components/dropdownMenu/index.tsx
  static/app/components/dropdownMenu/list.tsx
  static/app/components/pageTimeRangeSelector.tsx
  static/app/utils/useOverlay.tsx
  static/app/views/discover/table/cellAction.tsx
Labels: Scope: Frontend

#59316 feat(starfish): Add Web Vital score chart to page summary slideout panel
  static/app/views/performance/browser/webVitals/components/webVitalStatusLineChart.tsx
  static/app/views/performance/browser/webVitals/pageOverviewWebVitalsDetailPanel.tsx
  static/app/views/performance/browser/webVitals/webVitalsDetailPanel.tsx
Labels: Scope: Frontend

#59349 feat(starfish): Page Overview Table Columns
  static/app/components/gridEditable/index.tsx
  static/app/views/performance/browser/webVitals/pageOverview.tsx
  static/app/views/performance/browser/webVitals/pageSamplePerformanceTable.tsx
Labels: Scope: Frontend

#59325 feat(starfish): Page overview samples table pagination and sorting
  static/app/components/gridEditable/index.tsx
  static/app/components/pagination.tsx
  static/app/views/performance/browser/webVitals/pageOverview.tsx
  static/app/views/performance/browser/webVitals/pageSamplePerformanceTable.tsx
  static/app/views/performance/browser/webVitals/utils/types.tsx
  static/app/views/performance/browser/webVitals/utils/useTransactionSamplesWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/useWebVitalsSort.tsx
Labels: Scope: Frontend

#59233 ref(alerts): Use feature flag instead of options for metric alert rate limiting
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/incidents/subscription_processor.py
  src/sentry/options/defaults.py
  tests/sentry/incidents/test_subscription_processor.py
Labels: Scope: Backend

#59346 feat(starfish): Update release selector to use txn counts
  static/app/views/starfish/components/releaseSelector.tsx
  static/app/views/starfish/queries/useReleases.tsx
Labels: Scope: Frontend

#58972 feat(notifications): Remove team notifications off by default
  src/sentry/integrations/slack/views/link_team.py
  src/sentry/notifications/notificationcontroller.py
  tests/sentry/integrations/slack/test_link_team.py
  tests/sentry/models/test_groupsubscription.py
  tests/sentry/notifications/test_notificationcontroller.py
Labels: Scope: Backend

#58862 feat(stats-detectors): Read project settings before running detection
  src/sentry/api/endpoints/project_performance_issue_settings.py
  src/sentry/projectoptions/defaults.py
  src/sentry/tasks/statistical_detectors.py
  tests/sentry/tasks/test_statistical_detectors.py
Labels: Scope: Backend

#59236 feat(stats-detectors): Prepare to emit final regression issue type
  src/sentry/api/endpoints/organization_events_trends_v2.py
  src/sentry/issues/grouptype.py
  src/sentry/statistical_detectors/issue_platform_adapter.py
  src/sentry/tasks/statistical_detectors.py
  tests/sentry/api/endpoints/test_organization_events_trends_v2.py
  tests/sentry/statistical_detectors/test_issue_platform_adapter.py
  tests/sentry/tasks/test_statistical_detectors.py
Labels: Scope: Backend

#59331 feat(suspect-commits): Add suspect commit calculation type to frontend analytics
  static/app/components/events/eventCause.tsx
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/views/issueDetails/groupDetails.tsx
Labels: Scope: Frontend

#58886 feat(stats-detectors): Add project settings UI for stats detector
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#59319 chore(code): Document jira server API limitations
  src/sentry/integrations/jira_server/client.py
Labels: Scope: Backend

#59337 fix(feedback): fix shim in error embed page
  src/sentry/feedback/usecases/create_feedback.py
  src/sentry/web/frontend/error_page_embed.py
  tests/sentry/web/frontend/test_error_page_embed.py
Labels: Scope: Backend

#59328 feat(issues): Remove project fetch from issue details
  static/app/actionCreators/project.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/default.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/exception.spec.tsx
  static/app/components/events/interfaces/breadcrumbs/breadcrumb/data/http.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/content.spec.tsx
  static/app/components/events/interfaces/frame/frameVariables.spec.tsx
  static/app/components/events/meta/annotatedText/annotatedTextValue.tsx
  static/app/components/events/meta/annotatedText/filteredAnnotatedTextValue.tsx
  static/app/routes.tsx
  static/app/views/issueDetails/groupDetails.spec.tsx
  static/app/views/issueDetails/groupDetails.tsx
  static/app/views/issueDetails/index.tsx
Labels: Scope: Frontend

#59355 fix(stat-detectors): Align change markers in table
  static/app/utils/performance/regression/table.tsx
Labels: Scope: Frontend

#59226 feat(issue-stream): Update issue request to not rely on saved search
  static/app/utils/withSavedSearches.tsx
  static/app/views/issueList/overview.spec.tsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend
