Repository getsentry/sentry, pull requests merged in 2023-02, with the labels that each got.

#42533 feat: Implement instruction_addr_adjustment
  src/sentry/lang/native/processing.py
  src/sentry/profiles/task.py
  tests/sentry/lang/native/test_processing.py
  tests/sentry/profiles/consumers/test_process.py
Labels: Status: In Progress, Scope: Backend

#43880 feat(loader): Sync loader with JS monorepo
  src/sentry/templates/sentry/js-sdk-loader.js.tmpl
  src/sentry/templates/sentry/js-sdk-loader.min.js.tmpl
Labels: Scope: Backend

#43883 feat(release-health): implement timestamp based release_health API with Metrics Layer [TET 671]
  src/sentry/release_health/metrics.py
  src/sentry/snuba/metrics/query.py
Labels: Scope: Backend

#43944 fix: Prevent html pages with sourcemap pragma to be processed
  src/sentry/lang/javascript/processor.py
Labels: Scope: Backend

#43946 feat: Add Ubuntu as builtin symbol server
  src/sentry/conf/server.py
Labels: Scope: Backend

#43907 ref(profiling): Remove code producing to Kafka as it's handled by vroom
  src/sentry/profiles/task.py
Labels: Scope: Backend

#43881 feat(perf-issues): Add N+1 API Call alert email template support
  src/sentry/data/samples/transaction-n-plus-one-api-call.json
  src/sentry/templates/sentry/debug/mail/preview.html
  src/sentry/web/debug_urls.py
  src/sentry/web/frontend/debug/debug_performance_issue.py
  src/sentry/web/frontend/debug/mail.py
  tests/acceptance/test_emails.py
Labels: Scope: Backend

#43949 fix(heartbeat): Fix domains which trigger the exit warning
  static/app/routes.tsx
  static/app/views/onboarding/components/heartbeatFooter/index.tsx
Labels: Scope: Frontend

#43557 feat(file-io): Update issue details with the docs link
  static/app/components/events/interfaces/performance/utils.tsx
Labels: Scope: Frontend

#43950 feat(perf-issues): Add min size to render-blocking asset detector
  src/sentry/options/defaults.py
  src/sentry/projectoptions/defaults.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_render_blocking_asset_detector.py
Labels: Scope: Backend

#43947 fix(profiling): run search on page load
  static/app/views/profiling/profileDetails/components/profileDetailsTable.tsx
Labels: Scope: Frontend

#43958 feat(profiling): allow user handling of scroll
  static/app/components/events/viewHierarchy/index.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/flamegraphTreeTable.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/useVirtualizedTree.tsx
  static/app/utils/profiling/hooks/useVirtualizedTree/virtualizedTreeUtils.tsx
Labels: Scope: Frontend

#43569 feat(profiling): add p95 support to profiling hovercard
  static/app/components/profiling/functionsMiniGrid.tsx
  static/app/components/profiling/functionsTable.tsx
  static/app/types/profiling/core.tsx
  static/app/utils/profiling/hooks/useProfilingTransactionQuickSummary.tsx
Labels: Scope: Frontend

#43943 feat: Add NuGet as builtin symbol server
  src/sentry/conf/server.py
Labels: Scope: Backend

#43681 feat(codecov): Add coverage details to issue details
  static/app/components/events/interfaces/frame/context.spec.tsx
  static/app/components/events/interfaces/frame/context.tsx
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
Labels: Scope: Frontend

#43927 fix(tsdb) Pass through consistent flag correctly with SnQL
  src/sentry/utils/snuba.py
  tests/snuba/tsdb/test_tsdb_backend.py
Labels: Scope: Backend

#43749 feat(issue platform): Create GroupType dataclass
  src/sentry/grouptype/grouptype.py
  tests/grouptype/test_grouptype.py
Labels: Scope: Backend

#43857 ref(snuba-referrer): dynamically define Referrer snuba enum for TSDBModels
  src/sentry/snuba/referrer.py
  tests/snuba/test_referrer.py
Labels: Scope: Backend

#43817 fix(heroku): Use app webhooks
  src/sentry_plugins/heroku/plugin.py
  tests/sentry_plugins/heroku/test_plugin.py
Labels: Scope: Backend

#43850 feat(codecov): Add latest commit sha from git blame list
  src/sentry/api/endpoints/project_stacktrace_link.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/integrations/utils/codecov.py
  tests/sentry/api/endpoints/test_project_stacktrace_link.py
Labels: Scope: Backend

#43972 fixes get_release_sessions_time_bounds condition
  src/sentry/release_health/metrics.py
Labels: Scope: Backend

#43926 feat(view-hierarchy): Scale and center wireframe contents
  static/app/components/events/viewHierarchy/index.tsx
  static/app/components/events/viewHierarchy/useMousePan.tsx
  static/app/components/events/viewHierarchy/wireframe.spec.tsx
  static/app/components/events/viewHierarchy/wireframe.tsx
Labels: Scope: Frontend

#43896 feat(profiling): Render profile context
  static/app/components/events/contexts/app/index.tsx
  static/app/components/events/contexts/browser/index.tsx
  static/app/components/events/contexts/device/index.tsx
  static/app/components/events/contexts/gpu/index.tsx
  static/app/components/events/contexts/memoryInfo/index.tsx
  static/app/components/events/contexts/operatingSystem/index.tsx
  static/app/components/events/contexts/profile/index.spec.tsx
  static/app/components/events/contexts/profile/index.tsx
  static/app/components/events/contexts/runtime/index.tsx
  static/app/components/events/contexts/threadPoolInfo/index.tsx
  static/app/components/events/contexts/trace/index.tsx
  static/app/components/events/contexts/unity/index.tsx
  static/app/components/events/contexts/user/index.tsx
  static/app/components/events/contexts/utils.spec.tsx
  static/app/components/events/contexts/utils.tsx
  static/app/components/events/eventExtraData/index.tsx
  static/app/types/event.tsx
Labels: Scope: Frontend

#43939 feat(codecov): Use counter-reset instead of list marker
  static/app/components/events/interfaces/frame/context.tsx
  static/less/group-detail.less
Labels: Scope: Frontend

#43886 feat(roles): update team put api to set org_role
  src/sentry/api/endpoints/team_details.py
  src/sentry/auth/access.py
  src/sentry/models/organizationmember.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  tests/sentry/api/endpoints/test_team_details.py
  tests/sentry/auth/test_access.py
Labels: Scope: Backend

#43954 fix(domains) Fix more links in notifications
  src/sentry/integrations/metric_alerts.py
  src/sentry/integrations/slack/webhooks/action.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/digest.py
  src/sentry/notifications/notifications/user_report.py
Labels: Scope: Backend

#43980 fix(snuba): fix logging in utils/snuba.py
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#43979 fix(profiling): Stop converting profile received to datetime string
  src/sentry/profiles/task.py
Labels: Scope: Backend

#43890 feat(perf-issues): remove hardcoded demo org
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_consecutive_db_detector.py
Labels: Scope: Backend

#43986 fix(perf-issues): cleanup from hardcoded consecutive db org
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_consecutive_db_detector.py
Labels: Scope: Backend

#43988 fix(codecov): Add margin right of codecov status
  static/app/components/events/interfaces/frame/context.tsx
Labels: Scope: Frontend

#43932 feat(issues): Don't debug sourcemaps on anonymous frames
  static/app/components/events/interfaces/crashContent/exception/content.tsx
  static/app/components/events/interfaces/crashContent/exception/setupSourceMapsAlert.tsx
  static/app/components/events/interfaces/crashContent/exception/useSourceMapDebug.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/useSourceMapDebug.tsx
  static/app/components/events/interfaces/crashContent/exception/utils.tsx
Labels: Scope: Frontend

#43960 feat(perf-issues): Update N+1 API Call alert email evidence section
  src/sentry/notifications/utils/__init__.py
  src/sentry/templates/sentry/emails/email-styles.html
  src/sentry/templates/sentry/emails/transactions.html
  src/sentry/utils/performance_issues/base.py
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
  src/sentry/web/debug_urls.py
  tests/sentry/notifications/test_utils.py
Labels: Scope: Backend

#43935 fix(source-maps): fix url matching for source maps debug endpoint
  src/sentry/api/endpoints/source_map_debug.py
  src/sentry/models/sourcemapprocessingissue.py
  tests/sentry/api/endpoints/test_source_map_debug.py
Labels: Scope: Backend

#43976 fix(docs): update scim orgmember post docs
  src/sentry/scim/endpoints/members.py
  src/sentry/scim/endpoints/teams.py
Labels: Scope: Backend

#43934 fix(issues): Add additional sourcemap debug messages
  static/app/components/events/interfaces/crashContent/exception/sourceMapDebug.tsx
  static/app/components/events/interfaces/crashContent/exception/sourceaMapDebug.spec.tsx
  static/app/components/events/interfaces/crashContent/exception/useSourceMapDebug.tsx
Labels: Scope: Frontend

#43992 fix(ui): Bad spacing in invalid search text
  static/app/components/smartSearchBar/searchDropdown.tsx
Labels: Scope: Frontend

#43993 ref(js): Remove unnecessary tct in searchDropdown
  static/app/components/smartSearchBar/searchDropdown.tsx
Labels: Scope: Frontend

#43991 fix(hybrid-cloud): Fix is_auth_required for customer domains
  src/sentry/web/frontend/base.py
  tests/sentry/web/frontend/test_react_page.py
Labels: Scope: Backend

#43994 fix(crons): Rename monitors/ to crons/ for Django web route
  src/sentry/web/urls.py
Labels: Scope: Backend

#43984 feat(api-tokens): Allow super-users to access the tokens endpoint on behalf of users
  src/sentry/api/endpoints/api_tokens.py
  tests/sentry/api/endpoints/test_api_tokens.py
Labels: Scope: Backend

#43995 bug(quicktrace): Update QuickTrace placeholder css so it does not overflow
  static/app/views/issueDetails/quickTrace/index.tsx
Labels: Scope: Frontend

#43905 bug(replays): Fix the replay event node display in dark mode
  static/app/views/issueDetails/quickTrace/replayNode.tsx
Labels: Scope: Frontend

#40768 feat(replays): Replay Index searchbox implements onGetTagValues
  static/app/views/replays/replaySearchBar.tsx
Labels: Status: In Progress, Component: Replay Index, Scope: Frontend

#43998 bug(replays): Fix default search on the replays list
  static/app/views/replays/filters.tsx
Labels: Scope: Frontend

#43936 feat(expermient): Add useExperiment hook
  static/app/utils/useExperiment.spec.tsx
  static/app/utils/useExperiment.tsx
  static/app/utils/withExperiment.spec.jsx
  static/app/utils/withExperiment.tsx
Labels: Scope: Frontend

#44001 chore(login): update the login banners
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#43868 ref(event-details): Use react-query for fetching and deleting attachments
  static/app/actionCreators/events.tsx
  static/app/components/events/eventAttachments.spec.tsx
  static/app/components/events/eventAttachments.tsx
  static/app/components/events/eventAttachmentsCrashReportsNotice.tsx
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventTagsAndScreenshot/index.spec.tsx
  static/app/components/events/eventTagsAndScreenshot/index.tsx
  static/app/components/events/eventViewHierarchy.spec.tsx
  static/app/components/events/eventViewHierarchy.tsx
Labels: Scope: Frontend

#43999 feat(migration): Add missing unique indexes to UUID fields
  migrations_lockfile.txt
  src/sentry/migrations/0353_add_missing_uuid_unique_indexes.py
Labels: Scope: Backend

#44011 ref(ui): Remove unnecessary styled component
  static/app/views/releases/detail/overview/sidebar/deploys.tsx
Labels: Scope: Frontend

#44014 ref(onboarding-new-org): Update button copy
  static/app/views/onboarding/components/createProjectsFooter.tsx
Labels: Scope: Frontend

#44016 feat(api): Allow for querying release files/archives with checksums
  src/sentry/api/endpoints/organization_release_files.py
  src/sentry/api/endpoints/project_release_files.py
  tests/sentry/api/endpoints/test_organization_release_files.py
  tests/sentry/api/endpoints/test_project_release_files.py
Labels: Scope: Backend

#43961 fix(perf-issues): ignore graphql from consecutive db detector
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_consecutive_db_detector.py
Labels: Scope: Backend

#43933 ref(profiling): Use `SegmentedControl` in `FlamegraphViewSelectMenu`
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphViewSelectMenu.tsx
Labels: Scope: Frontend

#43920 feat(replays): Add handling for null ip-address aggregations
  src/sentry/replays/post_process.py
  src/sentry/replays/query.py
  tests/sentry/replays/test_organization_replay_index.py
Labels: Scope: Backend

#44022 fix(profiling): use priority
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphViewSelectMenu.tsx
Labels: Scope: Frontend

#43985 feat(n1-api-calls): Revert Add metrics for a suspicious parameter format
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#43919 (perf-issues) increase grouphash ignore rate for consecutive db
  src/sentry/event_manager.py
Labels: Scope: Backend

#44030 fix(codecov): Override marker content
  static/app/components/events/interfaces/frame/context.tsx
Labels: Scope: Frontend

#44033 feat(n1-api-calls): Add parameterization metrics
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#43990 feat(roles): refactor OrganizationMember model and API
  src/sentry/api/endpoints/organization_member/details.py
  src/sentry/models/organization.py
  src/sentry/models/organizationmember.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  tests/sentry/api/endpoints/test_organization_member_details.py
  tests/sentry/integrations/slack/webhooks/actions/test_status.py
  tests/sentry/models/test_organizationmember.py
Labels: Scope: Backend

#44037 fix(release-health) fixes get_crash_free_breakdown returning empty results when no environment is specified
  src/sentry/release_health/metrics.py
  tests/snuba/sessions/test_sessions.py
Labels: Scope: Backend

#43925 feat(spike-protection): Enable project stats for spike protection organizations
  src/sentry/api/serializers/models/organization.py
  src/sentry/constants.py
  tests/sentry/api/serializers/test_organization.py
Labels: Scope: Backend

#43882 ref(perf-issues): Move unc. asset to its own file
  src/sentry/utils/performance_issues/base.py
  src/sentry/utils/performance_issues/detectors/__init__.py
  src/sentry/utils/performance_issues/detectors/uncompressed_asset_detector.py
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_uncompressed_assets_detector.py
Labels: Scope: Backend

#44035 fix(codecov): Simplify analytics for line coverage
  static/app/components/events/interfaces/frame/context.spec.tsx
  static/app/components/events/interfaces/frame/context.tsx
Labels: Scope: Frontend

#44008 style(js): Use docblock comments in date utils
  static/app/utils/dates.tsx
Labels: Scope: Frontend

#43921 ref(crons): Make monitors check task limits clear
  src/sentry/tasks/check_monitors.py
Labels: Scope: Backend

#44009 feat(ui): Add timezone to chart tooltips
  static/app/components/charts/components/tooltip.tsx
Labels: Scope: Frontend

#43989 feat(perf-issues): Improve render blocking asset issue hashing
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_render_blocking_asset_detector.py
Labels: Scope: Backend

#44012 ref(ui): Remove unnecessary icon from deployBadge
  static/app/components/deployBadge.spec.tsx
  static/app/components/deployBadge.tsx
Labels: Scope: Frontend

#44040 chore(discover): Removes usage of quick context feature flag from frontend
  static/app/components/profiling/profileEventsTable.tsx
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/discover/table/tableView.tsx
Labels: Scope: Frontend

#44026 feat(view-hierarchy): Do not show wireframe for Unity
  static/app/components/events/eventEntries.tsx
  static/app/components/events/eventViewHierarchy.spec.tsx
  static/app/components/events/eventViewHierarchy.tsx
  static/app/components/events/viewHierarchy/index.spec.tsx
  static/app/components/events/viewHierarchy/index.tsx
  static/app/components/events/viewHierarchy/wireframe.tsx
Labels: Scope: Frontend

#44052 ref(perf): Allow private operations from URL
  static/app/views/discover/table/columnEditCollection.tsx
Labels: Scope: Frontend

#43909 feat(profiling): Add profile.id column to discover
  static/app/utils/discover/fieldRenderers.tsx
  static/app/utils/discover/fields.tsx
  static/app/utils/fields/index.ts
  static/app/views/discover/table/tableView.tsx
  static/app/views/discover/utils.tsx
Labels: Scope: Frontend

#44036 feat(profiling): Skip steps already done on retries
  src/sentry/profiles/task.py
Labels: Scope: Backend

#44045 style(prettier): Upgrade prettier to 2.8.3
  package.json
  static/app/components/avatar/baseAvatar.tsx
  static/app/components/charts/chartZoom.tsx
  static/app/components/deprecatedforms/genericField.tsx
  static/app/components/deprecatedforms/passwordField.tsx
  static/app/components/forms/formField/index.tsx
  static/app/components/forms/types.tsx
  static/app/components/letterAvatar.tsx
  static/app/components/multiPlatformPicker.tsx
  static/app/components/platformPicker.tsx
  static/app/components/profiling/ProfilingOnboarding/util.ts
  static/app/components/profiling/profileEventsTable.spec.tsx
  static/app/components/profiling/profileEventsTable.tsx
  static/app/components/replays/replayController.tsx
  static/app/data/platformCategories.tsx
  static/app/plugins/components/issueActions.tsx
  static/app/styles/space.tsx
  static/app/types/core.tsx
  static/app/types/experiments.tsx
  static/app/utils/docs.tsx
  static/app/utils/formatters.tsx
  static/app/utils/profiling/hooks/useProfileEvents.spec.tsx
  static/app/utils/useOverlay.tsx
  static/app/views/admin/adminQueue.tsx
  static/app/views/app/alertMessage.tsx
  static/app/views/issueDetails/groupDetails.tsx
  static/app/views/performance/types.tsx
  static/app/views/profiling/content.tsx
  static/app/views/profiling/landing/profilingSlowestTransactionsPanel.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.tsx
  static/app/views/profiling/profileSummary/content.tsx
  static/app/views/projects/projectContext.tsx
  static/app/views/projectsDashboard/projectCard.tsx
  static/app/views/settings/account/notifications/constants.tsx
  static/app/views/settings/organizationApiKeys/types.tsx
  static/app/views/settings/organizationDeveloperSettings/resourceSubscriptions.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryFunctionSubscriptions.tsx
  static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
  tests/js/instrumentedEnv/userEventIntegration.ts
  yarn.lock
Labels: Scope: Frontend

#44048 fix(transaction-details): Missing instrumentation details compatibili…
  static/app/components/events/interfaces/spans/inlineDocs.tsx
  static/app/components/events/interfaces/spans/spanBar.tsx
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/events/interfaces/spans/spanTree.tsx
Labels: Scope: Frontend

#44044 fix(audit-log): propagate ip_address through to audit_log_entry when creating alert rules
  src/sentry/incidents/endpoints/organization_alert_rule_details.py
  src/sentry/incidents/endpoints/project_alert_rule_details.py
  src/sentry/incidents/endpoints/project_alert_rule_index.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/serializers/alert_rule.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_index.py
Labels: Scope: Backend

#44006 feat(crons): Support configuring timezone
  src/sentry/api/validators/monitor.py
  tests/sentry/api/endpoints/test_monitor_details.py
  tests/sentry/models/test_monitor.py
Labels: Scope: Backend

#44042 feat(metrics): Register release health limiter rollout option
  src/sentry/options/defaults.py
Labels: Scope: Backend

#44005 fix(crons): Only show edit warning if the nextCheckIn is known
  static/app/views/monitors/monitorForm.tsx
Labels: Scope: Frontend

#43769 fix(crons): Constrain clipboard zone for monitor header
  static/app/views/monitors/monitorHeader.tsx
Labels: Scope: Frontend

#44061 feat(profiling): add flamegraph feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#44059 chore(sdk): Upgrade Sentry SDK to 7.36.0
  package.json
  yarn.lock
Labels: Scope: Frontend

#44007 feat(crons): Add timezone configuration to the form
  static/app/views/monitors/monitorForm.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#44010 feat(monitors): Do not force UTC on the checkin chart
  static/app/views/monitors/monitorStats.tsx
Labels: Scope: Frontend

#43997 feat(roles): update team and project serializers with all org roles
  src/sentry/api/serializers/models/project.py
  src/sentry/api/serializers/models/team.py
  src/sentry/models/organizationmember.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/serializers/test_project.py
  tests/sentry/api/serializers/test_team.py
Labels: Scope: Backend

#43974 ref(segmentedControl): Update styles
  static/app/components/segmentedControl.tsx
Labels: Scope: Frontend

#43924 feat(ingest): Add exception metrics to event_manager and post_process_group
  src/sentry/tasks/post_process.py
  src/sentry/tasks/store.py
Labels: Scope: Backend

#44065 fix(workflow): Remove owners.send_to org tag
  src/sentry/notifications/utils/participants.py
Labels: Scope: Backend

#44066 chore(js): Deprecated default Tooltip export
  static/app/components/events/interfaces/frame/line.tsx
  static/app/components/events/interfaces/frame/lineV2/default.tsx
  static/app/components/group/sidebar.tsx
  static/app/components/tooltip.tsx
  static/app/utils/discover/viewReplayLink.tsx
Labels: Scope: Frontend

#44062 fix(ecosystem): Fix text wrapping in sourcemap modal
  static/app/components/events/interfaces/frame/stacktraceLinkModal.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLinkModal.tsx
Labels: Scope: Frontend

#43930 feat(expermients): Add saved issue searches location experiment to config
  static/app/data/experimentConfig.tsx
Labels: Scope: Frontend

#44069 fix(ui): Remove unused styled exports
  static/app/components/alerts/notificationBar.tsx
  static/app/components/textCopyInput.tsx
  static/app/views/discover/table/quickContext/styles.tsx
Labels: Scope: Frontend

#44046 ref(segmentedControl): Add optional tooltips
  static/app/components/segmentedControl.tsx
Labels: Scope: Frontend

#43969 bug(replays): Properly quote transaction name when loading Txn → Replays tab
  static/app/views/performance/transactionSummary/transactionReplays/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionReplays/transactionReplays.tsx
Labels: Scope: Frontend

#44032 Revert "feat(replays): Add link to View Replay next to the Trace Navigator on Issue Details (#43608)
  static/app/components/quickTrace/styles.tsx
  static/app/views/issueDetails/eventToolbar.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.tsx
  static/app/views/issueDetails/linkContainer.tsx
  static/app/views/issueDetails/quickTrace/replayLink.tsx
  static/app/views/issueDetails/quickTrace/replayNode.tsx
  static/app/views/issueDetails/quickTrace/traceLink.tsx
Labels: Scope: Frontend

#44064 ref(ui): Remove old alert style from projectContext 404
  static/app/views/projects/projectContext.tsx
Labels: Scope: Frontend

#44075 fix(segmentedControl): Vertically align label text
  static/app/components/segmentedControl.tsx
Labels: Scope: Frontend

#44073 ref(userFeedback): Use `SegmentedControl` for issue status filter
  static/app/views/userFeedback/index.spec.jsx
  static/app/views/userFeedback/index.tsx
Labels: Scope: Frontend

#43784 ref(onboarding): Update onboarding minified stack trace analytics code
  src/sentry/event_manager.py
  src/sentry/receivers/onboarding.py
  tests/sentry/receivers/test_onboarding.py
Labels: Scope: Backend

#44093 feat(replays): Control recording scrubbing through a feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#44034 ref(derived_code_mappings): Easier to maintain and prep work
  src/sentry/integrations/github/client.py
  src/sentry/integrations/github/integration.py
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/integrations/github/test_integration.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#44051 feat(view-hierarchy): Wireframe performance improvements
  static/app/components/events/viewHierarchy/useMousePan.tsx
  static/app/components/events/viewHierarchy/wireframe.spec.tsx
  static/app/components/events/viewHierarchy/wireframe.tsx
Labels: Scope: Frontend

#44039 chore(discover): removes quick context feature flag from backend
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#44078 feat(sourcemaps): add more data about filepaths to sourcemaps debug endpoint
  src/sentry/api/endpoints/source_map_debug.py
  tests/sentry/api/endpoints/test_source_map_debug.py
Labels: Scope: Backend

#44107 Dominik b2014/consecutive db alert transaction name
  src/sentry/notifications/utils/__init__.py
Labels: Scope: Backend

#44063 feat(features): Enable project stats view without checking global-views
  static/app/views/organizationStats/index.spec.tsx
  static/app/views/organizationStats/index.tsx
Labels: Scope: Frontend

#44113 fix(tags): removes the arrow marker from details and summary element
  static/app/components/group/tagFacets/tagFacetsDistributionMeter.tsx
Labels: Scope: Frontend

#44100 feat(n1-api-calls): Revert "Add parameterization metrics"
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#44109 feat(analytics): Add group_id to more events on the issue details page
  static/app/components/events/eventCause.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
  static/app/components/group/sidebar.tsx
  static/app/components/group/suggestedOwners/suggestedAssignees.tsx
  static/app/utils/analytics/workflowAnalyticsEvents.tsx
  static/app/utils/events.tsx
  static/app/views/issueDetails/actions/index.tsx
  static/app/views/issueDetails/groupDetails.tsx
Labels: Scope: Frontend

#43712 feat(issue-platform): Support issue platform events in post process group
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#43760 ref(types): Use DataCategory in favour of DataCategoryExact
  static/app/constants/index.tsx
  static/app/types/core.tsx
  static/app/utils/theme.tsx
  static/app/views/organizationStats/index.spec.tsx
  static/app/views/organizationStats/index.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/app/views/organizationStats/usageChart/utils.tsx
  static/app/views/organizationStats/usageStatsOrg.tsx
  static/app/views/organizationStats/usageStatsPerMin.tsx
  static/app/views/organizationStats/usageStatsProjects.tsx
  static/app/views/organizationStats/usageTable/index.tsx
  static/app/views/organizationStats/utils.tsx
Labels: Scope: Frontend

#44076 fix(js): Prefer copy-to-clipboard over navigator.clipboard
  static/app/components/codeSnippet.tsx
  static/app/views/issueDetails/actions/shareModal.tsx
  static/app/views/releases/list/releasesPromo.tsx
  static/app/views/settings/organizationRelay/modals/form.tsx
Labels: Scope: Frontend

#44114 feat(tags): adds a tooltip to tag values on hover
  static/app/components/group/tagFacets/tagFacetsDistributionMeter.tsx
Labels: Scope: Frontend

#44038 feat(roles): refactor slack integration to include all org roles
  src/sentry/integrations/slack/utils/auth.py
  tests/sentry/integrations/slack/test_link_team.py
  tests/sentry/integrations/slack/webhooks/commands/test_link_team.py
Labels: Scope: Backend

#44112 feat(roles): allow unsetting team org role
  src/sentry/api/endpoints/team_details.py
  tests/sentry/api/endpoints/test_team_details.py
Labels: Scope: Backend

#44067 feat(roles): refactor OrganizationMemberTeam model and API
  src/sentry/api/endpoints/organization_member/team_details.py
  src/sentry/models/organizationmember.py
  src/sentry/models/organizationmemberteam.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_organization_member_team_details.py
  tests/sentry/models/test_organizationmemberteam.py
Labels: Scope: Backend

#44120 feat(profiling): add analytic events to profiling links
  static/app/components/events/contexts/profile/index.tsx
  static/app/components/profiling/arrayLinks.tsx
  static/app/components/profiling/functionsTable.tsx
  static/app/utils/analytics/profilingAnalyticsEvents.tsx
  static/app/views/discover/table/tableView.tsx
Labels: Scope: Frontend

#44050 fix(perf-issues): ignore huge assets in render blocking assets detector
  src/sentry/utils/performance_issues/performance_detection.py
  tests/sentry/utils/performance_issues/test_render_blocking_asset_detector.py
Labels: Scope: Backend

#44106 feat(analytics): Add analytics for different types of issue resolution
  src/sentry/analytics/events/issue_resolved.py
  src/sentry/api/serializers/models/group.py
  src/sentry/receivers/features.py
  src/sentry/tasks/integrations/sync_status_inbound.py
  tests/snuba/api/serializers/test_group.py
Labels: Scope: Backend

#44111 chore(issues) Add more context to missing project error
  static/app/views/issueDetails/groupDetails.tsx
Labels: Scope: Frontend

#44103 fix(n1-api-calls): Exclude Next.js stack traces from detection
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#44115 feat(perf): Add linear regression in discover
  src/sentry/search/events/builder/discover.py
  src/sentry/search/events/datasets/discover.py
  tests/snuba/api/endpoints/test_organization_events.py
Labels: Scope: Backend

#44079 feat(perf): Use metrics in transaction summary
  static/app/views/performance/transactionSummary/transactionOverview/charts.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/durationChart/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/durationPercentileChart/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/durationPercentileChart/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/durationPercentileChart/utils.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/latencyChart/content.tsx
  static/app/views/performance/transactionSummary/transactionOverview/latencyChart/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/sidebarCharts.tsx
  static/app/views/performance/transactionSummary/transactionOverview/userStats.tsx
  static/app/views/performance/transactionSummary/transactionOverview/utils.tsx
  static/app/views/performance/transactionSummary/transactionOverview/vitalsChart/index.tsx
  static/app/views/performance/transactionSummary/utils.tsx
  static/app/views/performance/trends/changedTransactions.tsx
  static/app/views/performance/vitalDetail/table.tsx
  static/app/views/performance/vitalDetail/vitalInfo.tsx
  static/app/views/releases/detail/overview/index.tsx
Labels: Scope: Frontend

#44124 feat(issue-search): temporarily feature flag searching for performance issues
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/search/snuba/executors.py
  tests/sentry/api/serializers/test_organization.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#44083 chore(ui): Upgrade jest
  package.json
  static/app/components/lazyLoad.spec.tsx
  static/app/stores/groupStore.spec.tsx
  static/app/stores/groupingStore.spec.jsx
  static/app/stores/groupingStore.tsx
  static/app/views/integrationPipeline/pipelineView.spec.jsx
  static/app/views/organizationContextContainer.spec.jsx
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/landing/metricsDataSwitcher.spec.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionVitals/index.spec.jsx
  static/app/views/settings/projectGeneralSettings.spec.jsx
  yarn.lock
Labels: Scope: Frontend

#44105 ref(profiling): keep the sorting logic closer to profile imports
  static/app/types/profiling.d.ts
  static/app/utils/profiling/profile/importProfile.spec.tsx
  static/app/utils/profiling/profile/importProfile.tsx
  static/app/utils/profiling/profile/jsSelfProfile.tsx
  static/app/utils/profiling/profile/sampledProfile.tsx
  static/app/utils/profiling/profile/sentrySampledProfile.tsx
  static/app/views/profiling/profileGroupProvider.tsx
Labels: Scope: Frontend

#44098 feat(profiling): prevent initializing with incompatible state
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphOptionsMenu.tsx
  static/app/types/profiling.d.ts
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
  static/app/utils/profiling/profile/importProfile.spec.tsx
  static/app/utils/profiling/profile/importProfile.tsx
  static/app/utils/profiling/profile/jsSelfProfile.tsx
  static/app/utils/profiling/profile/sampledProfile.tsx
  static/app/utils/profiling/profile/sentrySampledProfile.tsx
  static/app/views/profiling/profileGroupProvider.tsx
Labels: Scope: Frontend

#44097 feat(profiling): sort samples and import as flamegraph
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphOverlays/profileDragDropImport.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphOptionsMenu.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphViewSelectMenu.tsx
  static/app/components/profiling/profileHeader.tsx
  static/app/types/jsSelfProfiling.d.ts
  static/app/types/profiling.d.ts
  static/app/utils/profiling/differentialFlamegraph.spec.tsx
  static/app/utils/profiling/flamegraph.spec.tsx
  static/app/utils/profiling/flamegraph/flamegraphStateProvider/flamegraphContextProvider.tsx
  static/app/utils/profiling/guards/profile.tsx
  static/app/utils/profiling/jsSelfProfiling.spec.tsx
  static/app/utils/profiling/profile/eventedProfile.spec.tsx
  static/app/utils/profiling/profile/eventedProfile.tsx
  static/app/utils/profiling/profile/importProfile.spec.tsx
  static/app/utils/profiling/profile/importProfile.tsx
  static/app/utils/profiling/profile/jsSelfProfile.spec.tsx
  static/app/utils/profiling/profile/jsSelfProfile.tsx
  static/app/utils/profiling/profile/profile.tsx
  static/app/utils/profiling/profile/sampledProfile.spec.tsx
  static/app/utils/profiling/profile/sampledProfile.tsx
  static/app/utils/profiling/profile/sentrySampledProfile.spec.tsx
  static/app/utils/profiling/profile/sentrySampledProfile.tsx
  static/app/utils/profiling/profile/utils.tsx
  static/app/utils/profiling/renderers/flamegraphTextRenderer.spec.tsx
  static/app/views/profiling/profileDetails/components/profileDetailsTable.spec.tsx
  static/app/views/profiling/profileDetails/profileDetails.tsx
  static/app/views/profiling/profileFlamechart.tsx
  static/app/views/profiling/profileGroupProvider.tsx
  static/app/views/profiling/profilesProvider.tsx
  tests/js/sentry-test/profiling/utils.tsx
Labels: Scope: Frontend

#44118 ref(issues): Use `SegmentedControl`
  static/app/components/events/groupingInfo/groupingVariant.tsx
  static/app/components/issueDiff/index.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachments.spec.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachmentsFilter.tsx
  static/app/views/issueDetails/groupSimilarIssues/similarStackTrace/index.tsx
Labels: Scope: Frontend

#44128 fix(source-maps): fixes which artifacts are used in sourcemap debug endpoint
  src/sentry/api/endpoints/source_map_debug.py
Labels: Scope: Backend

#44123 ref(releaseDetails): Use `SegmentedControl` for issue type filter
  static/app/views/releases/detail/overview/releaseIssues.spec.jsx
  static/app/views/releases/detail/overview/releaseIssues.tsx
Labels: Scope: Frontend

#44130 feat(projects): Allow filtering on dsn
  src/sentry/api/endpoints/project_index.py
  tests/sentry/api/endpoints/test_project_index.py
Labels: Scope: Backend

#44127 feat(n1-api-calls): Omit unparameterized spans from detection
  fixtures/events/performance_problems/n-plus-one-api-calls/n-plus-one-api-calls-in-weather-app.json
  src/sentry/utils/performance_issues/detectors/n_plus_one_api_calls_detector.py
  tests/sentry/utils/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#44131 fix(segmentedControl): Fix text ellipsization
  static/app/components/segmentedControl.tsx
Labels: Scope: Frontend

#43938 feat(issue-platform): Send occurrence id to `post_process_group` via `post_process_forwarder`
  src/sentry/eventstream/kafka/consumer_strategy.py
  src/sentry/eventstream/kafka/postprocessworker.py
  src/sentry/eventstream/kafka/protocol.py
  src/sentry/tasks/post_process.py
  tests/sentry/eventstream/kafka/test_consumer.py
  tests/sentry/eventstream/kafka/test_consumer_strategy.py
  tests/sentry/eventstream/kafka/test_postprocessworker.py
  tests/sentry/eventstream/kafka/test_protocol.py
Labels: Scope: Backend

#44144 fix(serializers): Properly log errors when serialization fails
  src/sentry/api/serializers/base.py
Labels: Scope: Backend

#44057 ref(hybrid-cloud): RPC strong types spike
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/endpoints/group_participants.py
  src/sentry/api/endpoints/organization_user_details.py
  src/sentry/api/serializers/models/activity.py
  src/sentry/api/serializers/models/dashboard.py
  src/sentry/api/serializers/models/group.py
  src/sentry/api/serializers/models/grouptombstone.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/api/serializers/models/organization_member/base.py
  src/sentry/api/serializers/models/release.py
  src/sentry/api/serializers/rest_framework/mentions.py
  src/sentry/models/actor.py
  src/sentry/models/organization.py
  src/sentry/notifications/notifications/strategies/role_based_recipient_strategy.py
  src/sentry/notifications/utils/participants.py
  src/sentry/receivers/sentry_apps.py
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/auth/impl.py
  src/sentry/services/hybrid_cloud/filter_query.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/services/hybrid_cloud/user/impl.py
  src/sentry/utils/committers.py
  src/sentry/utils/email/manager.py
  src/sentry/web/client_config.py
  tests/sentry/api/serializers/test_group_tombstone.py
  tests/sentry/integrations/jira/test_integration.py
  tests/sentry/integrations/jira_server/test_integration.py
  tests/sentry/middleware/test_auth.py
Labels: Scope: Backend

#44096 fix(txnames): Run clusterer at fixed time every hour
  src/sentry/conf/server.py
Labels: Scope: Backend

#44099 fix: Make Automatic LPQ actually work (it *never* did)
  src/sentry/processing/realtime_metrics/base.py
  tests/sentry/tasks/test_low_priority_symbolication.py
Labels: Scope: Backend

#43720 ref: Make `Symbolicator` agnostic of request kind
  src/sentry/api/endpoints/project_app_store_connect_credentials.py
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/serializers/models/project.py
  src/sentry/lang/native/appconnect.py
  src/sentry/lang/native/sources.py
  src/sentry/lang/native/symbolicator.py
  tests/sentry/lang/native/test_ignoredsourcesfiltering.py
  tests/sentry/lang/native/test_symbolicator.py
Labels: Scope: Backend

#44024 Remove `symbolicator.status_code` tagging with `project_id`
  src/sentry/lang/native/symbolicator.py
Labels: Scope: Backend

#44135 fix(perf): Fix icon rendering in the transaction summary search
  static/app/components/smartSearchBar/index.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
Labels: Scope: Frontend

#43940 feat: Give the new `newstyle:2023-01-11` grouping its own enhancers
  src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt
  src/sentry/grouping/strategies/configurations.py
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/actix.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/android_anr.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/callee_guaranteed.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/exception_cocoa_nserror.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/fallback_prefix_level_1.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_dartlang_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_125_event_126.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_200_event_200.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_275_event_275.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_289_event_312.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_294_event_294.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_294_event_329.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_307_event_307.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_307_event_657.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_313_event_313.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_313_event_333.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_319_event_321.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_389_event_389.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_432_event_432.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_432_event_453.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/group_445_event_445.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/in_app_in_ui.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/java_minimal.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/macos_amd_driver.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/macos_intel_driver.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/malloc_sentinel.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_complex_function_names.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_driver_crash1.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_driver_crash2.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_driver_crash3.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_limit_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_malloc_chain.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_no_filenames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_unlimited_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/native_windows_anon_namespace.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/stacktrace_enforce_min_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/stacktrace_negated_match.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/stacktrace_rust.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/stacktrace_rust2.pysnap
Labels: Scope: Backend

#44102 feat(profiling): Add feature flag for profiling previews
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#44160 ref(perf-issues): Increase limit threshold for unc detection
  src/sentry/event_manager.py
  src/sentry/grouptype/grouptype.py
Labels: Scope: Backend

#44159 feat(perf): Show stacked area in the span op widget
  static/app/components/charts/eventsRequest.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.tsx
  static/app/views/performance/landing/widgets/transforms/transformEventsToStackedBars.tsx
  static/app/views/performance/landing/widgets/types.tsx
  static/app/views/performance/landing/widgets/widgetDefinitions.tsx
  static/app/views/performance/landing/widgets/widgets/stackedAreaChartListWidget.tsx
Labels: Scope: Frontend

#44104 feat(n1-api-calls): Remove "Beta" badge
  static/app/views/issueDetails/header.tsx
Labels: Scope: Frontend

#44136 chore(ado): Add more logging
  src/sentry/integrations/vsts/integration.py
Labels: Scope: Backend
