Repository getsentry/sentry, pull requests merged in 2024-07, with the labels that each got.

#73501 ref: Replace `push_scope` with `isolation_scope` in `src/sentry/utils`
  src/sentry/utils/appleconnect/appstore_connect.py
  src/sentry/utils/metrics.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#73502 ref: Replace `push_scope` with `isolation_scope` in integrations
  src/sentry/integrations/services/integration/impl.py
  src/sentry/middleware/integrations/parsers/discord.py
  src/sentry/middleware/integrations/parsers/msteams.py
Labels: Scope: Backend

#73503 ref: Replace `push_scope` with `isolation_scope` in relay code
  src/sentry/relay/config/__init__.py
  src/sentry/relay/config/metric_extraction.py
  tests/relay_integration/test_sdk.py
Labels: Scope: Backend

#73490 ref: Replace `push_scope` with `isolation_scope` in API code
  src/sentry/api/base.py
  src/sentry/api/endpoints/artifact_bundles.py
  src/sentry/api/endpoints/custom_rules.py
  src/sentry/api/endpoints/organization_traces.py
Labels: Scope: Backend

#73504 ref: Replace `push_scope` with `isolation_scope` in all remaining places
  src/sentry/auth/helper.py
  src/sentry/consumers/validate_schema.py
  src/sentry/dynamic_sampling/tasks/common.py
  src/sentry/hybridcloud/tasks/deliver_webhooks.py
  src/sentry/search/events/builder/metrics.py
  src/sentry/seer/breakpoints.py
  src/sentry/sentry_apps/apps.py
  src/sentry/sentry_metrics/querying/data/execution.py
  src/sentry/snuba/query_subscriptions/consumer.py
Labels: Scope: Backend

#73434 ref(project-details): Convert class to func component
  static/app/views/projectDetail/projectDetail.spec.tsx
  static/app/views/projectDetail/projectDetail.tsx
Labels: Scope: Frontend

#73559 Clean up inline-attachments options
  src/sentry/models/eventattachment.py
  src/sentry/relay/globalconfig.py
  tests/sentry/api/endpoints/test_event_attachment_details.py
Labels: Scope: Backend

#73566 feat(metrics): add span attribute spec limit
  src/sentry/options/defaults.py
  src/sentry/relay/config/metric_extraction.py
  tests/sentry/relay/config/test_metric_extraction.py
Labels: Scope: Backend

#73567 ref(on-demand-metrics): remove alert spec limit default
  src/sentry/relay/config/metric_extraction.py
Labels: Scope: Backend

#73569 fix(metrics): add Echarts brush end check
  static/app/components/metrics/chart/useFocusArea.tsx
Labels: Scope: Frontend

#73432 fix(trace) add extra analytics properties
  static/app/utils/analytics/tracingEventMap.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
Labels: Scope: Frontend

#73570 Do not allow crash rate value to be greater than 1
  src/sentry/api/endpoints/organization_release_health_data.py
  src/sentry/utils/metrics.py
  tests/sentry/api/endpoints/test_organization_release_health_data.py
Labels: Scope: Backend

#73574 fix: transaction_id check during project transfer
  src/sentry/api/endpoints/accept_project_transfer.py
  src/sentry/api/endpoints/project_transfer.py
  tests/sentry/api/endpoints/test_accept_project_transfer.py
  tests/sentry/api/endpoints/test_project_transfer.py
Labels: Scope: Backend

#73576 fix: add rate limit for project transfer endpoint
  src/sentry/api/endpoints/project_transfer.py
  tests/sentry/api/endpoints/test_project_transfer.py
Labels: Scope: Backend

#73476 feat(query-builder): Organize and sort issue/event filters better
  static/app/stores/tagStore.spec.tsx
  static/app/stores/tagStore.tsx
  static/app/utils/fields/index.ts
  static/app/views/issueList/searchBar.tsx
Labels: Scope: Frontend

#73549 Remove Sentry warnings and GCP logs for throttled queries
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#73546 chore(slack): track timeout errors from sdk WebClient
  src/sentry/integrations/slack/sdk_client.py
  tests/sentry/integrations/slack/test_sdk_client.py
Labels: Scope: Backend

#73580 ref: fix more typing issues in HC modules
  src/sentry/audit_log/services/log/impl.py
  src/sentry/audit_log/services/log/service.py
Labels: Scope: Backend

#73345 perf(similarity): in backfill lower time bounds
  src/sentry/tasks/embeddings_grouping/utils.py
Labels: Scope: Backend

#73583 ref(ui): Add types for typescript 5.5
  static/app/components/feedback/feedbackOnboarding/sidebar.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
Labels: Scope: Frontend

#73579 fix(search): Stop sending invalid start/end dates to tag values endpoint
  static/app/views/issueList/searchBar.tsx
Labels: Scope: Frontend

#73581 ref: fix more types in tasks
  src/sentry/tasks/collect_project_platforms.py
  src/sentry/tasks/summaries/utils.py
Labels: Scope: Backend

#73517 feat(query-builder): Hide section headers when searching
  static/app/components/compactSelect/listBox/index.tsx
  static/app/components/compactSelect/listBox/section.tsx
  static/app/components/searchQueryBuilder/combobox.tsx
Labels: Scope: Frontend

#73530 deps(ui): Upgrade to typescript 5.5
  package.json
  yarn.lock
Labels: Scope: Frontend

#73586 fix(query-builder): Exclude environment tag from results
  static/app/views/issueList/searchBar.tsx
Labels: Scope: Frontend

#73582 chore(slack): Add Ignore Transaction Boundary in SDK Client for Tests
  src/sentry/integrations/slack/sdk_client.py
Labels: Scope: Backend

#73588 fix(sidebar): Avoid error from null user
  static/app/components/sidebar/sidebarDropdown/index.tsx
Labels: Scope: Frontend

#72918 feat(uptime): Add uptime issue frontend type and config
  static/app/components/stream/group.tsx
  static/app/types/group.tsx
  static/app/utils/issueTypeConfig/index.tsx
  static/app/utils/issueTypeConfig/uptimeConfig.tsx
Labels: Scope: Frontend

#73589 ref: add row type to our custom QuerySet
  src/sentry/db/models/manager/base_query_set.py
  src/sentry/db/models/manager/types.py
Labels: Scope: Backend

#72892 ref: fix various types for sentry.monitors
  src/sentry/monitors/clock_tasks/check_missed.py
  src/sentry/monitors/endpoints/base_monitor_details.py
  src/sentry/monitors/endpoints/organization_monitor_index_stats.py
  src/sentry/monitors/serializers.py
Labels: Scope: Backend

#73590 fix(slack): set delete_original to False when responding to webhooks
  src/sentry/integrations/slack/webhooks/action.py
Labels: Scope: Backend

#71889 chore(deps): Bump moment-timezone from 0.5.43 to 0.5.44
  package.json
  yarn.lock
Labels: Scope: Frontend, Trigger: getsentry tests, Stale

#73447 Revert "ref(metrics): Add metrics for script run times (#72223)"
  requirements-dev-frozen.txt
  requirements-dev.txt
  scripts/do.sh
  scripts/lib.sh
Labels: Scope: Backend

#73595 ref: annotate query type for ReleaseQuerySet
  src/sentry/models/release.py
  src/sentry/models/releases/util.py
Labels: Scope: Backend

#73596 ref: fix types for create_or_update to match the requirements of BaseManager
  src/sentry/db/models/query.py
Labels: Scope: Backend

#73597 dev(similarity): log sentry error when seer fails
  src/sentry/tasks/embeddings_grouping/backfill_seer_grouping_records_for_project.py
Labels: Scope: Backend

#71443 chore(issues): Enable trace timeline for cron issues
  static/app/utils/issueTypeConfig/cronConfig.tsx
Labels: WIP, Scope: Frontend, Stale

#68658 feat(replays): Add materialized view query entrypoints
  src/sentry/replays/endpoints/organization_replay_index.py
  src/sentry/replays/lib/new_query/fields.py
  src/sentry/replays/query.py
  src/sentry/replays/scripts/delete_replays.py
  src/sentry/replays/usecases/query/__init__.py
  src/sentry/replays/usecases/query/conditions/activity.py
  src/sentry/replays/usecases/query/configs/materialized_view.py
  tests/sentry/replays/test_organization_replay_index.py
Labels: WIP, Scope: Backend

#73531 fix(stacktrace-link): Fix gitlab integration url being incorrectly generated
  src/sentry/integrations/utils/code_mapping.py
  tests/sentry/integrations/utils/test_code_mapping.py
  tests/sentry/tasks/test_commit_context.py
Labels: Scope: Backend

#73519 chore(slack): remove handle dialog submission in webhook
  src/sentry/integrations/slack/webhooks/action.py
Labels: Scope: Backend

#73251 chore(empty-states): Use existing docs for empty state
  static/app/components/onboarding/gettingStartedDoc/step.tsx
  static/app/components/updatedEmptyState.spec.tsx
  static/app/components/updatedEmptyState.tsx
Labels: Scope: Frontend

#73605 docs: Fix typo in comment
  static/app/components/replays/replayPlayer.tsx
Labels: Scope: Frontend

#73486 nit(rollup): Use reverse instead of sorting
  src/sentry/tsdb/base.py
Labels: Scope: Backend

#73608 ref(replay): Insert the init breadcrumb to the front of the list
  static/app/utils/replays/replayReader.tsx
Labels: Scope: Frontend

#73602 ref: improve annotations for Outbox Managers
  src/sentry/models/apitoken.py
  src/sentry/models/integrations/organization_integration.py
  src/sentry/models/organizationmemberteam.py
Labels: Scope: Backend

#73603 ref: Future is generic in our version of python
  src/sentry/sentry_metrics/consumers/indexer/routing_producer.py
  src/sentry/utils/arroyo_producer.py
  src/sentry/utils/concurrent.py
Labels: Scope: Backend

#73572 ref(metrics): Onboarding updates for span-based metrics
  static/app/views/metrics/layout.spec.tsx
  static/app/views/metrics/layout.tsx
  static/app/views/metrics/metricQueryContextMenu.tsx
  static/app/views/metrics/metricsIngestionStopAlert.tsx
  static/app/views/metrics/optInModal.tsx
  static/app/views/metrics/pageHeaderActions.spec.tsx
  static/app/views/metrics/pageHeaderActions.tsx
Labels: Scope: Frontend

#73421 feat(metrics): persist span attribute extraction rules in django
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/api/endpoints/project_metrics_extraction_rules.py
  src/sentry/api/serializers/models/metrics_extraction_rules.py
  src/sentry/backup/comparators.py
  src/sentry/conf/server.py
  src/sentry/migrations/0732_add_span_attribute_extraction_rules.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/extraction_rules.py
  src/sentry/sentry_metrics/models/__init__.py
  src/sentry/sentry_metrics/models/metricsextractionrules.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/snuba/metrics/span_attribute_extraction.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/api/endpoints/test_project_metrics_extraction_rules.py
  tests/sentry/backup/snapshots/ReleaseTests/test_at_head.pysnap
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/models/test_user.py
  tests/sentry/relay/config/test_metric_extraction.py
  tests/sentry/sentry_metrics/test_extraction_rules.py
  tests/sentry/snuba/metrics/test_span_attribute_extraction.py
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Frontend, Scope: Backend

#73560 Remove a bunch of now-enabled options
  src/sentry/options/defaults.py
Labels: Scope: Backend

#73624 feat(metrics): persist span attribute extraction rules in django (v2)
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/api/endpoints/project_metrics_extraction_rules.py
  src/sentry/api/serializers/models/metrics_extraction_rules.py
  src/sentry/backup/comparators.py
  src/sentry/conf/server.py
  src/sentry/migrations/0732_add_span_attribute_extraction_rules.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/extraction_rules.py
  src/sentry/sentry_metrics/models/__init__.py
  src/sentry/sentry_metrics/models/metricsextractionrules.py
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/snuba/metrics/span_attribute_extraction.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/api/endpoints/test_project_metrics_extraction_rules.py
  tests/sentry/backup/snapshots/ReleaseTests/test_at_head.pysnap
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/models/test_user.py
  tests/sentry/relay/config/test_metric_extraction.py
  tests/sentry/sentry_metrics/test_extraction_rules.py
  tests/sentry/snuba/metrics/test_span_attribute_extraction.py
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Frontend, Scope: Backend

#73494 ref(metrics): rename name param to mri
  src/sentry/sentry_metrics/client/snuba.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_organization_metrics_details.py
  tests/sentry/api/endpoints/test_organization_metrics_metadata.py
  tests/sentry/api/endpoints/test_organization_metrics_tag_details_v2.py
  tests/sentry/api/endpoints/test_organization_metrics_tags.py
  tests/sentry/api/endpoints/test_organization_release_health_data.py
  tests/sentry/issues/test_escalating.py
  tests/sentry/sentry_metrics/querying/data/test_api.py
  tests/sentry/snuba/metrics/test_datasource.py
  tests/sentry/tasks/test_statistical_detectors.py
  tests/snuba/sessions/test_sessions.py
  tests/snuba/test_metrics_layer.py
Labels: Scope: Backend

#73626 feat(metrics-extraction): Introduce virtual metrics
  static/app/components/metrics/queryBuilder.tsx
  static/app/types/metrics.tsx
  static/app/utils/metrics/formatters.tsx
  static/app/utils/metrics/index.spec.tsx
  static/app/utils/metrics/index.tsx
  static/app/utils/metrics/useMetricsMeta.tsx
  static/app/utils/metrics/virtualMetricsContext.tsx
  static/app/views/alerts/rules/metric/mriField.tsx
  static/app/views/settings/projectMetrics/customMetricsTable.tsx
Labels: Scope: Frontend

#73045 feat(metrics-extraction): Selectable aggregates
  static/app/types/metrics.tsx
  static/app/views/settings/projectMetrics/extractMetric.tsx
  static/app/views/settings/projectMetrics/metricsExtractionRuleEditModal.tsx
  static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx
  static/app/views/settings/projectMetrics/metricsExtractionRulesTable.tsx
  static/app/views/settings/projectMetrics/utils/api.tsx
Labels: Do Not Merge, Scope: Frontend

#73573 ref(auth): Replace `configure_scope` with `get_isolation_scope`
  src/sentry/api/authentication.py
Labels: Scope: Backend

#73636 Simplify attachment rate limiting `reason`
  src/sentry/event_manager.py
Labels: Scope: Backend

#73630 ref(api): Migrate `configure_scope` in `src/sentry/api/bases/`
  src/sentry/api/bases/doc_integrations.py
  src/sentry/api/bases/group.py
  src/sentry/api/bases/project.py
  src/sentry/api/bases/sentryapps.py
Labels: Scope: Backend

#73631 ref(api): Migrate `configure_scope` in `OrganizationReleaseDetails` endpoint
  src/sentry/api/endpoints/organization_release_details.py
Labels: Scope: Backend

#73632 ref(api): Migrate `configure_scope` in `OrganizationReleases` endpoint
  src/sentry/api/endpoints/organization_releases.py
Labels: Scope: Backend

#73634 ref(api): Migrate `configure_scope` in `ProjectReleaseDetails` endpoint
  src/sentry/api/endpoints/project_release_details.py
Labels: Scope: Backend

#73635 ref(api): Migrate `configure_scope` in `ProjectReleases` endpoint
  src/sentry/api/endpoints/project_releases.py
Labels: Scope: Backend

#73637 ref(api): Migrate `configure_scope` in Sentry app authorizations endpoint
  src/sentry/api/endpoints/integrations/sentry_apps/authorizations.py
Labels: Scope: Backend

#73639 ref(integrations): Migrate `configure_scope` in GH integration
  src/sentry/integrations/github_enterprise/webhook.py
Labels: Scope: Backend

#73641 ref(integrations): Migrate `configure_scope` in JIRA integration
  src/sentry/integrations/jira/views/sentry_issue_details.py
Labels: Scope: Backend

#73645 feat(metrics-extraction): Disable used attributes
  static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx
Labels: Scope: Frontend

#73643 ref(integrations): Migrate `configure_scope` in remaining integration code
  src/sentry/integrations/base.py
  src/sentry/integrations/mixins/repositories.py
  src/sentry/integrations/utils/scope.py
Labels: Scope: Backend

#73646 ref: Migrate `configure_scope` in `src/sentry/tasks`
  src/sentry/tasks/app_store_connect.py
  src/sentry/tasks/assemble.py
  src/sentry/tasks/base.py
Labels: Scope: Backend

#73524 chore(trace-explorer): Start enforcing project selection behind flag
  src/sentry/api/endpoints/organization_spans_fields.py
  src/sentry/api/endpoints/organization_traces.py
  src/sentry/features/temporary.py
  tests/sentry/api/endpoints/test_organization_spans_fields.py
  tests/sentry/api/endpoints/test_organization_traces.py
Labels: Scope: Backend

#73506 chore(insights): removes no longer needed webvitals weighted score calculation workaround
  src/sentry/features/temporary.py
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#73649 ref: add continuous profiling ui flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#73532 feat(autofix): Add feature flag to disable codebase indexing
  src/sentry/api/endpoints/group_ai_autofix.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#73651 ref(data_export): Migrate `configure_scope` to new API in `src/sentry/data_export`
  src/sentry/data_export/tasks.py
Labels: Scope: Backend

#73652 ref(ingest): Migrate `configure_scope` in `src/sentry/ingest`
  src/sentry/ingest/transaction_clusterer/rules.py
Labels: Scope: Backend

#73653 ref(issues): Migrate `configure_scope` in `src/sentry/issues`
  src/sentry/issues/endpoints/project_stacktrace_link.py
Labels: Scope: Backend

#73539 fix(insights): Link "View Query Summary" button to Insights URL
  static/app/components/events/interfaces/spans/spanDetail.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/utils.tsx
Labels: Scope: Frontend

#73654 ref: Migrate `configure_scope` in `src/sentry/web`
  src/sentry/web/frontend/csrf_failure.py
Labels: Scope: Backend

#73612 ref(replay): Move ReplayPlayerTimestampEmitter into its own file
  static/app/components/replays/replayContext.tsx
  static/app/utils/replays/replayPlayerTimestampEmitter.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
Labels: Scope: Frontend

#73655 ref: Migrate remaining `configure_scope` to new API
  src/sentry/hybridcloud/rpc/service.py
  src/sentry/middleware/integrations/classifications.py
  src/sentry/monitors/endpoints/base.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_attachment.py
  src/sentry/reprocessing2.py
  src/sentry/shared_integrations/client/base.py
Labels: Scope: Backend

#73601 ref(slack): retry link slack user identities task
  src/sentry/integrations/slack/utils/channel.py
  src/sentry/integrations/slack/utils/users.py
  src/sentry/tasks/integrations/slack/link_slack_user_identities.py
  tests/sentry/integrations/slack/test_integration.py
  tests/sentry/integrations/slack/test_utils.py
Labels: Scope: Backend

#73578 feat(profiling) setup continuous profiling routes
  static/app/routes.tsx
  static/app/utils/profiling/routes.tsx
  static/app/views/profiling/continuousProfileFlamechart.tsx
  static/app/views/profiling/continuousProfilesProvider.tsx
Labels: Scope: Frontend

#73606 feat(empty-states): Add python and javascript
  static/app/views/issueList/noGroupsHandler/index.tsx
Labels: Scope: Frontend

#73450 ref(querybuilder): Differentiate between Discover and Base
  src/sentry/api/endpoints/organization_events_facets_performance.py
  src/sentry/api/endpoints/organization_events_root_cause_analysis.py
  src/sentry/api/endpoints/organization_events_span_ops.py
  src/sentry/api/endpoints/organization_events_spans_performance.py
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/api/endpoints/organization_events_trends.py
  src/sentry/api/endpoints/organization_spans_fields.py
  src/sentry/api/endpoints/organization_traces.py
  src/sentry/api/helpers/events.py
  src/sentry/data_export/endpoints/data_export.py
  src/sentry/discover/endpoints/serializers.py
  src/sentry/incidents/logic.py
  src/sentry/issues/related/trace_connected.py
  src/sentry/profiles/flamegraph.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/search/events/builder/__init__.py
  src/sentry/search/events/builder/base.py
  src/sentry/search/events/builder/discover.py
  src/sentry/search/events/builder/errors.py
  src/sentry/search/events/builder/metrics_summaries.py
  src/sentry/search/events/builder/profile_functions.py
  src/sentry/search/events/builder/profiles.py
  src/sentry/search/events/builder/sessions.py
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/search/events/datasets/discover.py
  src/sentry/search/events/datasets/metrics_summaries.py
  src/sentry/search/events/datasets/profile_functions.py
  src/sentry/search/events/datasets/profiles.py
  src/sentry/search/events/datasets/sessions.py
  src/sentry/search/events/datasets/spans_indexed.py
  src/sentry/sentry_metrics/querying/samples_list.py
  src/sentry/snuba/discover.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/snuba/issue_platform.py
  src/sentry/tasks/on_demand_metrics.py
  tests/sentry/api/test_event_search.py
  tests/sentry/search/events/builder/test_discover.py
Labels: Scope: Backend

#71105 fix(slack): Escape assignee dropdown input
  src/sentry/integrations/slack/webhooks/options_load.py
  tests/sentry/integrations/slack/webhooks/options_load/test_dynamic_assignment_dropdown.py
Labels: Scope: Backend, Stale

#73611 perf(seer): add multithreading for making seer requests
  src/sentry/options/defaults.py
  src/sentry/tasks/embeddings_grouping/backfill_seer_grouping_records_for_project.py
  src/sentry/tasks/embeddings_grouping/utils.py
  tests/sentry/tasks/test_backfill_seer_grouping_records.py
Labels: Scope: Backend

#73528 chore(trace-explorer): Restore project selector
  static/app/views/traces/content.tsx
  static/app/views/traces/tracesSearchBar.tsx
Labels: Scope: Frontend

#73660 feat(trace): Add profile id to trace response
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/snuba/events.py
Labels: Scope: Backend

#73453 fix(discover): Update dataset with PUT on homepage query
  src/sentry/discover/endpoints/discover_homepage_query.py
  tests/snuba/api/endpoints/test_discover_homepage_query.py
Labels: Scope: Backend

#73658 fix(performance): Txn Summary's Duration Breakdown avg should be a duration
  static/app/views/performance/transactionSummary/transactionOverview/durationChart/content.tsx
Labels: Scope: Frontend

#72863 chore(slack): remove old slack client from notify recipient
  src/sentry/features/temporary.py
  src/sentry/integrations/slack/metrics.py
  src/sentry/integrations/slack/notifications.py
  src/sentry/notifications/notifications/organization_request/abstract_invite_request.py
  src/sentry/tasks/integrations/slack/post_message.py
  src/sentry/testutils/cases.py
  tests/sentry/api/endpoints/test_organization_invite_request_index.py
  tests/sentry/api/endpoints/test_organization_join_request.py
  tests/sentry/integrations/slack/notifications/test_assigned.py
  tests/sentry/integrations/slack/notifications/test_deploy.py
  tests/sentry/integrations/slack/notifications/test_escalating.py
  tests/sentry/integrations/slack/notifications/test_issue_alert.py
  tests/sentry/integrations/slack/notifications/test_new_processing_issues.py
  tests/sentry/integrations/slack/notifications/test_note.py
  tests/sentry/integrations/slack/notifications/test_nudge.py
  tests/sentry/integrations/slack/notifications/test_regression.py
  tests/sentry/integrations/slack/notifications/test_resolved.py
  tests/sentry/integrations/slack/notifications/test_resolved_in_release.py
  tests/sentry/integrations/slack/notifications/test_unassigned.py
  tests/sentry/integrations/slack/test_notifications.py
  tests/sentry/integrations/slack/test_tasks.py
  tests/sentry/notifications/notifications/test_assigned.py
  tests/sentry/notifications/notifications/test_digests.py
  tests/sentry/notifications/test_notifications.py
  tests/sentry/tasks/test_daily_summary.py
Labels: Scope: Backend

#73664 fix(queues): remove option for timing queued tasks
  src/sentry/options/defaults.py
  src/sentry/tasks/base.py
Labels: Scope: Backend

#73461 fix(trace) disable scroll when trace list is scrolling
  static/app/views/performance/newTraceDetails/traceRenderers/virtualizedViewManager.tsx
Labels: Scope: Frontend

#73455 fix(trace): copy fetch status
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
Labels: Scope: Frontend

#73659 chore(slack): Use Slack SDK Client in `validate_channel_id`
  src/sentry/integrations/slack/utils/channel.py
  src/sentry/options/defaults.py
  tests/sentry/api/endpoints/test_project_rule_details.py
  tests/sentry/api/endpoints/test_project_rules.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_serializers.py
  tests/sentry/integrations/slack/test_notify_action.py
Labels: Scope: Backend

#73668 feat(option): Add option to control MEP flag in STs
  src/sentry/api/serializers/models/organization.py
  src/sentry/options/defaults.py
Labels: Scope: Backend

#73670 feat(trace): Add span extraction date option
  src/sentry/api/serializers/models/organization.py
  src/sentry/options/defaults.py
Labels: Scope: Backend

#73607 ref(replay): Refactor text extraction inside replay diff toolset
  static/app/components/replays/replayDiff.tsx
  static/app/utils/replays/extractPageHtml.tsx
  static/app/utils/replays/hooks/useExtractedPageHtml.tsx
Labels: Scope: Frontend

#73676 fix(insights): Tidy up module title declarations
  static/app/components/sidebar/index.tsx
  static/app/views/insights/browser/resources/settings.ts
  static/app/views/insights/browser/resources/views/resourcesLandingPage.tsx
  static/app/views/insights/common/components/modulePageProviders.tsx
  static/app/views/insights/common/utils/moduleTitles.tsx
  static/app/views/insights/common/utils/useModuleBreadcrumbs.tsx
  static/app/views/insights/database/settings.ts
  static/app/views/insights/http/settings.ts
  static/app/views/insights/settings.ts
  static/app/views/performance/landing/widgets/widgetDefinitions.tsx
Labels: Scope: Frontend

#73672 fix(rules): Use the right comparison interval mapping
  src/sentry/rules/processing/delayed_processing.py
  tests/sentry/rules/processing/test_delayed_processing.py
Labels: Scope: Backend

#73681 fix(insights): use sentry_tags.category for module type
  src/sentry/constants.py
Labels: Scope: Backend

#73533 chore(autofix): Use repo_external_id in autofix change
  static/app/components/events/autofix/autofixChanges.tsx
  static/app/components/events/autofix/index.spec.tsx
  static/app/components/events/autofix/types.ts
  tests/js/fixtures/autofixCodebaseChangeData.ts
Labels: Scope: Frontend

#73685 fix(trace-explorer): Feature check for projects
  static/app/views/traces/content.tsx
Labels: Scope: Frontend

#73673 ref(seer grouping): Only send 20 frames if stacktrace is fully minified
  src/sentry/seer/similarity/utils.py
  tests/sentry/seer/similarity/test_utils.py
Labels: Scope: Backend

#73333 chore(slack): Use Slack SDK for SlackEventEndpoints
  src/sentry/integrations/slack/metrics.py
  src/sentry/integrations/slack/webhooks/event.py
  src/sentry/options/defaults.py
  tests/sentry/integrations/slack/webhooks/events/test_discover_link_shared.py
  tests/sentry/integrations/slack/webhooks/events/test_link_shared.py
  tests/sentry/integrations/slack/webhooks/events/test_message_im.py
Labels: Scope: Backend

#73682 feat(assignee-selector): Make user searchable by email in dropdown
  static/app/components/assigneeSelectorDropdown.spec.tsx
  static/app/components/assigneeSelectorDropdown.tsx
Labels: Scope: Frontend

#73690 fix(stats): Correct release count tooltip data
  static/app/views/organizationStats/teamInsights/teamReleases.tsx
Labels: Scope: Frontend

#73694 fix(app-start): Show infinity symbol when change request returns NaN
  static/app/views/insights/mobile/appStarts/components/tables/spanOperationTable.spec.tsx
  static/app/views/insights/mobile/appStarts/components/tables/spanOperationTable.tsx
Labels: Scope: Frontend

#73475 feat(replay): Gap in replay timeline
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/breadcrumbs/timelineGaps.tsx
  static/app/utils/replays/replayReader.tsx
  static/app/utils/replays/types.tsx
Labels: Scope: Frontend

#73604 dev(similarity): add spans
  src/sentry/tasks/embeddings_grouping/utils.py
Labels: Scope: Backend

#73615 ref(replay): Pull some stuff out of components/replays/utils.tsx
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/player/scrubber.tsx
  static/app/components/replays/player/useScrubberMouseTracking.tsx
  static/app/components/replays/timeAndScrubberGrid.tsx
  static/app/components/replays/utils.spec.tsx
  static/app/components/replays/utils.tsx
  static/app/utils/duration/formatReplayDuration.spec.tsx
  static/app/utils/duration/formatReplayDuration.tsx
  static/app/utils/number/divide.spec.tsx
  static/app/utils/number/divide.tsx
  static/app/views/replays/detail/accessibility/accessibilityRefetchBanner.tsx
  static/app/views/replays/detail/memoryPanel/domNodesChart.tsx
  static/app/views/replays/detail/memoryPanel/memoryChart.tsx
  static/app/views/replays/detail/timestampButton.tsx
  static/app/views/replays/replayTable/tableCell.tsx
Labels: Scope: Frontend

#73701 fix(uptime): Fix actual_check_time(_ms) timestamps
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/testutils/cases.py
  src/sentry/uptime/issue_platform.py
  tests/sentry/uptime/test_issue_platform.py
Labels: Scope: Backend

#73677 ref(seer grouping): Lower frame limit to 30
  src/sentry/seer/similarity/utils.py
  tests/sentry/seer/similarity/test_utils.py
Labels: Scope: Backend

#73529 feat(self-hosted): Disable ai features for self-hosted errors only
  static/app/views/issueDetails/resourcesAndPossibleSolutions.tsx
Labels: Scope: Frontend

#73704 ref(metrics): Add edit route
  static/app/routes.tsx
  static/app/views/metrics/metricQueryContextMenu.tsx
  static/app/views/settings/projectMetrics/metricsExtractionRulesTable.spec.tsx
  static/app/views/settings/projectMetrics/metricsExtractionRulesTable.tsx
Labels: Scope: Frontend

#73625 feat(relay): Expose metric extrapolation config
  src/sentry/relay/config/metric_extraction.py
Labels: Scope: Backend

#73712 fix(metrics): enable new conditions without ids in metrics extraction rules
  src/sentry/api/endpoints/project_metrics_extraction_rules.py
  tests/sentry/api/endpoints/test_project_metrics_extraction_rules.py
Labels: Scope: Backend

#73714 ref(metrics): Update route cond for metrics settings
  static/app/views/metrics/metricQueryContextMenu.tsx
Labels: Scope: Frontend

#73716 fix(metrics): Disable metric settings option
  static/app/views/metrics/metricQueryContextMenu.tsx
Labels: Scope: Frontend

#73627 feat(metrics): limit number of specs during creation
  src/sentry/api/endpoints/project_metrics_extraction_rules.py
  src/sentry/sentry_metrics/models/metricsextractionrules.py
  tests/sentry/api/endpoints/test_project_metrics_extraction_rules.py
Labels: Scope: Backend

#73718 fix(metrics): Use correct key for extrapolation config
  src/sentry/relay/config/metric_extraction.py
Labels: Scope: Backend

#73120 feat(related_issues): Post GA clean up
  static/app/views/issueDetails/groupEventHeader.tsx
  static/app/views/issueDetails/traceTimeline/traceTimeline.spec.tsx
  static/app/views/issueDetails/traceTimeline/traceTimeline.tsx
Labels: Scope: Frontend

#73726 feat(metrics-extraction): Query builder refinement
  static/app/components/metrics/mriSelect/index.tsx
  static/app/components/metrics/mriSelect/metricListItemDetails.tsx
  static/app/components/metrics/queryBuilder.tsx
  static/app/utils/metrics/useMetricsTags.tsx
  static/app/utils/metrics/virtualMetricsContext.tsx
  static/app/views/metrics/metricQueryContextMenu.tsx
Labels: Scope: Frontend

#73702 chore(hybridcloud) Add newly moved services to mypy stronglist
  pyproject.toml
  src/sentry/auth/provider.py
  src/sentry/auth/services/auth/model.py
  src/sentry/organizations/services/organization/model.py
  src/sentry/users/services/usersocialauth/model.py
  src/social_auth/backends/__init__.py
  src/social_auth/utils.py
Labels: Scope: Backend

#73650 ref(sdk): Delete unused mark_scope_as_unsafe function
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#73728 feat(metrics-extraction): Enumerate queries in rule form
  static/app/views/settings/projectMetrics/metricsExtractionRuleForm.tsx
Labels: Scope: Frontend

#73678 chore(hybridcloud) Remove shims from services.hybrid_cloud
  pyproject.toml
  src/sentry/hybridcloud/rpc/service.py
  src/sentry/pipeline/base.py
  src/sentry/scim/endpoints/members.py
  src/sentry/scim/endpoints/utils.py
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/app/__init__.py
  src/sentry/services/hybrid_cloud/app/service.py
  src/sentry/services/hybrid_cloud/auth/__init__.py
  src/sentry/services/hybrid_cloud/auth/impl.py
  src/sentry/services/hybrid_cloud/auth/service.py
  src/sentry/services/hybrid_cloud/integration/__init__.py
  src/sentry/services/hybrid_cloud/integration/model.py
  src/sentry/services/hybrid_cloud/integration/service.py
  src/sentry/services/hybrid_cloud/log/__init__.py
  src/sentry/services/hybrid_cloud/lost_password_hash/__init__.py
  src/sentry/services/hybrid_cloud/organization/__init__.py
  src/sentry/services/hybrid_cloud/organization/model.py
  src/sentry/services/hybrid_cloud/organization/serial.py
  src/sentry/services/hybrid_cloud/organization_actions/__init__.py
  src/sentry/services/hybrid_cloud/organization_actions/impl.py
  src/sentry/services/hybrid_cloud/organization_mapping/__init__.py
  src/sentry/services/hybrid_cloud/organization_mapping/model.py
  src/sentry/services/hybrid_cloud/organization_mapping/serial.py
  src/sentry/services/hybrid_cloud/project/__init__.py
  src/sentry/services/hybrid_cloud/project/service.py
  src/sentry/services/hybrid_cloud/project_key/__init__.py
  src/sentry/services/hybrid_cloud/project_key/service.py
  src/sentry/services/hybrid_cloud/rpc.py
  src/sentry/services/hybrid_cloud/user/__init__.py
  src/sentry/services/hybrid_cloud/user/model.py
  src/sentry/services/hybrid_cloud/user/serial.py
  src/sentry/services/hybrid_cloud/user/service.py
  src/sentry/services/hybrid_cloud/user_option/__init__.py
  src/sentry/testutils/cases.py
  tests/sentry/models/test_user.py
  tests/sentry/ratelimits/utils/test_get_ratelimit_key.py
Labels: Scope: Backend

#73729 feat(metrics): add better error messages to project metrics extraction rules endpoint
  src/sentry/api/endpoints/project_metrics_extraction_rules.py
  tests/sentry/api/endpoints/test_project_metrics_extraction_rules.py
Labels: Scope: Backend

#73463 ref(querybuilder): Move querybuilder imports to absolute
  src/sentry/api/endpoints/organization_event_details.py
  src/sentry/api/endpoints/organization_events_spans_performance.py
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/api/endpoints/organization_profiling_functions.py
  src/sentry/api/endpoints/organization_spans_fields.py
  src/sentry/api/endpoints/organization_spans_trace.py
  src/sentry/api/endpoints/organization_traces.py
  src/sentry/api/event_search.py
  src/sentry/api/serializers/rest_framework/dashboard.py
  src/sentry/search/events/builder/__init__.py
  src/sentry/search/events/builder/errors.py
  src/sentry/search/events/builder/issue_platform.py
  src/sentry/search/events/builder/profile_functions.py
  src/sentry/search/events/builder/profile_functions_metrics.py
  src/sentry/search/events/builder/profiles.py
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/search/events/builder/spans_metrics.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/search/events/datasets/metrics_layer.py
  src/sentry/search/events/datasets/profile_functions_metrics.py
  src/sentry/search/events/datasets/spans_metrics.py
  src/sentry/sentry_metrics/querying/samples_list.py
  src/sentry/snuba/discover.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/snuba/errors.py
  src/sentry/snuba/functions.py
  src/sentry/snuba/issue_platform.py
  src/sentry/snuba/metrics/extraction.py
  src/sentry/snuba/metrics/query_builder.py
  src/sentry/snuba/metrics_performance.py
  src/sentry/snuba/metrics_summaries.py
  src/sentry/snuba/profiles.py
  src/sentry/snuba/sessions_v2.py
  src/sentry/snuba/spans_indexed.py
  src/sentry/snuba/spans_metrics.py
  src/sentry/tasks/check_am2_compatibility.py
  tests/sentry/search/events/builder/test_errors.py
  tests/sentry/search/events/builder/test_metrics.py
  tests/sentry/search/events/builder/test_span_metrics.py
  tests/sentry/search/events/builder/test_spans_indexed.py
  tests/sentry/search/events/test_fields.py
  tests/sentry/search/events/test_filter.py
  tests/sentry/snuba/test_profiles.py
Labels: Scope: Backend

#73721 fix(related_issues): Remove correct trace link
  static/app/views/issueDetails/groupEventCarousel.tsx
  static/app/views/issueDetails/groupEventHeader.tsx
Labels: Scope: Frontend

#73680 feat(autofix): Indexing check true if indexing disabled flag
  src/sentry/api/endpoints/group_autofix_setup_check.py
  tests/sentry/api/endpoints/test_group_autofix_setup_check.py
Labels: Scope: Backend

#73679 feat(autofix): Remove codebase indexing setup step if flag enabled
  static/app/components/events/autofix/autofixSetupModal.spec.tsx
  static/app/components/events/autofix/autofixSetupModal.tsx
  static/app/components/guidedSteps/guidedSteps.tsx
Labels: Scope: Frontend

#73545 feat(breadcrumbs): Add drawer for breadcrumbs
  static/app/components/events/breadcrumbs/breadcrumbsDataSection.spec.tsx
  static/app/components/events/breadcrumbs/breadcrumbsDataSection.tsx
  static/app/components/events/breadcrumbs/breadcrumbsDrawerContent.spec.tsx
  static/app/components/events/breadcrumbs/breadcrumbsDrawerContent.tsx
  static/app/components/events/breadcrumbs/breadcrumbsTimeline.tsx
  static/app/components/events/breadcrumbs/testUtils.tsx
  static/app/components/events/breadcrumbs/utils.tsx
  static/app/components/timeline/index.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend

#73440 feat(new-trace): Incrementally rendering traces in replay details
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTrace.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/trace/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/traceDrawer.tsx
  static/app/views/performance/newTraceDetails/traceMetadataHeader.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/replays/detail/trace/index.tsx
  static/app/views/replays/detail/trace/trace.tsx
  static/app/views/replays/detail/trace/useReplayTraces.spec.tsx
  static/app/views/replays/detail/trace/useReplayTraces.tsx
Labels: Scope: Frontend

#73708 fix(query-builder): Escape tag values with parens
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/utils.tsx
Labels: Scope: Frontend

#73709 Emit Sentry warning and GCP log for sampled throttled queries (generic)
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#73674 feat(new-trace): Route to traceView if traceSlug from query is not null.
  static/app/views/discover/table/tableView.tsx
Labels: Scope: Frontend

#73735 fix(insights): Update "Requests" module page header
  static/app/components/sidebar/index.tsx
  static/app/views/insights/http/settings.ts
  static/app/views/insights/http/views/httpLandingPage.spec.tsx
Labels: Scope: Frontend

#73703 fix(grouping): Fix missing system-only stacktraces in similar issues diff view
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.spec.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.tsx
Labels: Scope: Frontend

#73665 fix(rules): Fix environment fetch
  src/sentry/rules/actions/utils.py
  tests/sentry/api/endpoints/test_project_rule_details.py
Labels: Scope: Backend

#73730 ref(sdk): Remove `configure_scope` re-export from SDK utils
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#73613 ref(replay): Extract useTimelineScale from useReplayContext and tweak ui styles
  static/app/components/replays/breadcrumbs/replayTimeline.tsx
  static/app/components/replays/player/scrubber.tsx
  static/app/components/replays/replayContext.tsx
  static/app/components/replays/timeAndScrubberGrid.tsx
  static/app/utils/replays/hooks/useTimelineScale.tsx
Labels: Scope: Frontend

#73744 ref: use concrete dict in HC payloads
  src/sentry/auth/services/auth/model.py
Labels: Scope: Backend

#73725 chore(related_issues): Remove flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#73752 fix(replay): Include timestamps in the useExtractedPageHtml cache key
  static/app/utils/replays/hooks/useExtractedPageHtml.tsx
Labels: Scope: Frontend

#73736 fix(insights): Add redirects for Insights sub-routes
  static/app/routes.tsx
Labels: Scope: Frontend

#73070 ref(crons): Add test for onDismiss from processing errors
  static/app/views/monitors/components/processingErrors/monitorProcessingErrors.spec.tsx
Labels: Scope: Frontend

#73727 feat(trace_timeline): Remove the need to check flag
  static/app/utils/issueTypeConfig/index.tsx
  static/app/utils/issueTypeConfig/replayConfig.tsx
  static/app/utils/issueTypeConfig/types.tsx
  static/app/utils/issueTypeConfig/uptimeConfig.tsx
  static/app/views/issueDetails/groupEventHeader.tsx
Labels: Scope: Frontend

#73748 fix(feedback): Sometimes events can be missing fields, we should guard against it
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
Labels: Scope: Frontend

#73688 feat(relocation): Add relocatin provenance
  migrations_lockfile.txt
  src/sentry/migrations/0733_relocation_provenance.py
  src/sentry/models/organization.py
  src/sentry/models/relocation.py
Labels: Scope: Backend

#73761 ref: upgrade sentry-forked-django-stubs
  requirements-dev-frozen.txt
  requirements-dev.txt
  src/sentry/audit_log/services/log/impl.py
  src/sentry/auth/services/orgauthtoken/impl.py
  src/sentry/db/models/outboxes.py
  src/sentry/hybridcloud/services/control_organization_provisioning/impl.py
  src/sentry/hybridcloud/services/region_organization_provisioning/impl.py
  src/sentry/hybridcloud/services/replica/impl.py
  src/sentry/migrations/0634_backfill_github_webhook_outbox_shard_ids.py
  src/sentry/models/authidentityreplica.py
  src/sentry/models/authproviderreplica.py
  src/sentry/models/integrations/sentry_app_installation.py
  src/sentry/models/organizationmember.py
  src/sentry/models/outbox.py
  tests/sentry/models/test_outbox.py
Labels: Scope: Backend

#73618 Add ability to get options if project has a template
  src/sentry/models/options/project_option.py
  src/sentry/models/project.py
  src/sentry/projectoptions/manager.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  tests/sentry/models/test_project.py
  tests/sentry/projectoptions/test_basic.py
Labels: Scope: Backend

#73308 feat(uptime): Add downtime information to downtime issues
  static/app/components/events/interfaces/uptime/uptimeDataSection.spec.tsx
  static/app/components/events/interfaces/uptime/uptimeDataSection.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
Labels: Scope: Frontend
