Repository getsentry/sentry, pull requests merged in 2024-09, with the labels that each got.

#76787 ref(alerts): Remove span metrics alerts
  static/app/utils/metrics/extractionRules.tsx
  static/app/utils/metrics/mri.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/spanMetricsField.tsx
  static/app/views/alerts/rules/metric/utils/getFormattedSpanMetric.tsx
  static/app/views/alerts/rules/metric/utils/isSpanMetricAlert.tsx
  static/app/views/alerts/rules/metric/wizardField.tsx
  static/app/views/alerts/wizard/index.tsx
  static/app/views/alerts/wizard/options.tsx
  static/app/views/alerts/wizard/panelContent.tsx
  static/app/views/alerts/wizard/utils.tsx
  static/images/spot/alerts-wizard-span-metrics.svg
Labels: Scope: Frontend

#76796 ref(metrics): Remove extraction rules feature flag usage
  static/app/utils/metrics/features.tsx
  static/app/views/metrics/layout.spec.tsx
  static/app/views/metrics/layout.tsx
  static/app/views/metrics/metricsIngestionStopAlert.tsx
  static/app/views/settings/projectMetrics/customMetricsTable.tsx
Labels: Scope: Frontend

#76797 ref(metrics): Remove virtual metrics provider
  static/app/components/metrics/metricQuerySelect.spec.tsx
  static/app/components/metrics/metricQuerySelect.tsx
  static/app/components/metrics/queryBuilder.tsx
  static/app/utils/metrics/virtualMetricsContext.spec.tsx
  static/app/utils/metrics/virtualMetricsContext.tsx
  static/app/views/metrics/metricScratchpad.spec.tsx
  static/app/views/settings/projectMetrics/utils/useMetricsExtractionRules.tsx
Labels: Scope: Frontend

#76771 chore(metrics): remove span metrics api endpoints
  src/sentry/api/endpoints/organization_metrics_extraction_rules.py
  src/sentry/api/endpoints/project_metrics_extraction_rules.py
  src/sentry/api/endpoints/project_metrics_usage.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_organization_metrics_extraction_rules.py
  tests/sentry/api/endpoints/test_project_metrics_extraction_rules.py
  tests/sentry/api/endpoints/test_project_metrics_usage.py
Labels: Scope: Backend

#76808 fix(ruby-onboarding): Move text below snippet
  static/app/gettingStartedDocs/ruby/rails.tsx
Labels: Scope: Frontend

#76779 chore(metrics): remove span metrics relay config & serializers
  src/sentry/api/serializers/models/metrics_extraction_rules.py
  src/sentry/api/serializers/rest_framework/metrics_usage.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/snuba/metrics/span_attribute_extraction.py
  tests/sentry/relay/config/test_metric_extraction.py
  tests/sentry/snuba/metrics/test_span_attribute_extraction.py
Labels: Scope: Backend

#76785 chore(metrics): remove usages of span metric models
  src/sentry/sentry_metrics/querying/visitors/query_expression.py
  src/sentry/sentry_metrics/span_attribute_extraction_rules.py
  src/sentry/snuba/metrics/naming_layer/mri.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  tests/sentry/sentry_metrics/querying/data/test_api.py
  tests/snuba/metrics/naming_layer/test_mri.py
Labels: Scope: Backend

#76806 fix(onboarding) conditionally show minimum version for profiling notice for all python packages
  static/app/components/onboarding/gettingStartedDoc/types.ts
  static/app/components/profiling/profilingOnboardingSidebar.tsx
  static/app/gettingStartedDocs/python/aiohttp.tsx
  static/app/gettingStartedDocs/python/asgi.tsx
  static/app/gettingStartedDocs/python/awslambda.tsx
  static/app/gettingStartedDocs/python/bottle.tsx
  static/app/gettingStartedDocs/python/celery.tsx
  static/app/gettingStartedDocs/python/chalice.tsx
  static/app/gettingStartedDocs/python/django.tsx
  static/app/gettingStartedDocs/python/falcon.tsx
  static/app/gettingStartedDocs/python/fastapi.tsx
  static/app/gettingStartedDocs/python/flask.tsx
  static/app/gettingStartedDocs/python/gcpfunctions.tsx
  static/app/gettingStartedDocs/python/mongo.tsx
  static/app/gettingStartedDocs/python/python.tsx
  static/app/gettingStartedDocs/python/quart.tsx
  static/app/gettingStartedDocs/python/serverless.tsx
  static/app/gettingStartedDocs/python/starlette.tsx
  static/app/gettingStartedDocs/python/tornado.tsx
  static/app/gettingStartedDocs/python/wsgi.tsx
Labels: Scope: Frontend

#76815 chore(metrics): remove methods of span metric models
  src/sentry/sentry_metrics/models/spanattributeextractionrules.py
Labels: Scope: Backend

#76819 feat(whats-new): Add feature flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#76777 ref(metrics): Remove extrapolation ui
  static/app/types/project.tsx
  static/app/utils/metrics/features.tsx
  static/app/views/settings/projectMetrics/extrapolationField.tsx
  static/app/views/settings/projectMetrics/projectMetrics.tsx
  tests/js/fixtures/project.ts
Labels: Scope: Frontend

#76780 ref(metrics): Remove extrapolation code
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/api/serializers/models/project.py
  src/sentry/apidocs/examples/project_examples.py
  src/sentry/constants.py
  src/sentry/features/temporary.py
  src/sentry/models/options/project_option.py
  src/sentry/options/defaults.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/relay/globalconfig.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/api/endpoints/test_relay_globalconfig_v3.py
Labels: Scope: Backend

#76834 chore(onboarding): instrument "take me to..." buttons
  static/app/utils/analytics/onboardingAnalyticsEvents.tsx
  static/app/views/projectInstall/platform.tsx
Labels: Scope: Frontend

#76813 fix(release-health): add supported sdks
  static/app/data/platformCategories.tsx
Labels: Scope: Frontend

#76836 fix(metrics): Handle null unit
  static/app/views/settings/projectMetrics/customMetricsTable.tsx
Labels: Scope: Frontend

#76837 fix(metrics): fix the unit of eap meta to not break FE
  src/sentry/sentry_metrics/querying/eap/metrics_details.py
Labels: Scope: Backend

#76838 feat(php-onboarding): Add stack trace args warning
  static/app/gettingStartedDocs/php/laravel.tsx
  static/app/gettingStartedDocs/php/php.tsx
  static/app/gettingStartedDocs/php/symfony.tsx
Labels: Scope: Frontend

#76832 ref(profiling): remove deprecated options for processed profiles metrics ingestion
  src/sentry/options/defaults.py
Labels: Scope: Backend

#76847 chore(sdks): bump Sentry SDK to 8.28.0
  package.json
  yarn.lock
Labels: Scope: Frontend

#76693 feat(alerts): Updates Insights Metric Alerts to not use Metrics Layer
  static/app/utils/metrics/features.tsx
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.spec.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.spec.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
Labels: Scope: Frontend

#76849 fix(onboarding): instrument take me to buttons
  static/app/utils/analytics/onboardingAnalyticsEvents.tsx
Labels: Scope: Frontend

#76700 feat(alerts): Updates isOnDemandMetricAlert to always return false on insights metrics
  static/app/views/alerts/rules/metric/utils/onDemandMetricAlert.spec.tsx
  static/app/views/alerts/rules/metric/utils/onDemandMetricAlert.tsx
Labels: Scope: Frontend

#76759 feat(discover): update spm to default interval to 1 when no start or end is provided and skip_time_conditions is set to true
  src/sentry/search/events/datasets/metrics.py
  tests/sentry/snuba/test_tasks.py
Labels: Scope: Backend

#76853 fix(insights): Broken span sample search in HTTP Panel
  static/app/views/insights/http/components/httpSamplesPanel.tsx
Labels: Scope: Frontend

#76762 fix(issues): Avoid animating tags on initial load
  static/app/components/group/tagFacets/tagFacetsDistributionMeter.tsx
  static/app/views/performance/transactionSummary/transactionOverview/index.spec.tsx
Labels: Scope: Frontend

#75791 feat(data-secrecy): Data Secrecy Settings UI
  static/app/types/organization.tsx
  static/app/views/settings/components/dataSecrecy/index.spec.tsx
  static/app/views/settings/components/dataSecrecy/index.tsx
  static/app/views/settings/organizationSecurityAndPrivacy/index.spec.tsx
  static/app/views/settings/organizationSecurityAndPrivacy/index.tsx
  tests/js/fixtures/organization.ts
Labels: Scope: Frontend

#76778 api: Mark ProguardArtifactReleasesEndpoint private
  src/sentry/api/endpoints/debug_files.py
Labels: Scope: Backend

#76824 ref: Remove duration shims after files were renamed
  static/app/utils/formatters.tsx
Labels: Scope: Frontend

#76768 Update tags for more comprehensive CapMan payload
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#76758 chore(grouping): Use optimized grouping logic for 60% of non-transitioning projects
  src/sentry/grouping/ingest/config.py
  tests/sentry/event_manager/grouping/test_assign_to_group.py
Labels: Scope: Backend

#76823 feat: Add ISO8601 format to formatDuration
  static/app/utils/duration/formatDuration.spec.tsx
  static/app/utils/duration/formatDuration.tsx
Labels: Scope: Frontend

#76723 feat(issue-platform): handle edge case where api populates a default value
  static/app/views/alerts/rules/issue/sentryAppRuleModal.spec.tsx
  static/app/views/settings/organizationIntegrations/sentryAppExternalForm.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#76645 style(toolbar): update release panel css
  static/app/components/devtoolbar/components/panelLayout.tsx
  static/app/components/devtoolbar/components/releases/releaseIssues.tsx
  static/app/components/devtoolbar/components/releases/releasesPanel.tsx
  static/app/components/devtoolbar/styles/releasesPanel.ts
Labels: Scope: Frontend

#76859 fix(custom-views): Replace hard coded pathname with useLocation
  static/app/views/issueList/customViewsHeader.tsx
  static/app/views/issueList/groupSearchViewTabs/draggableTabBar.tsx
Labels: Scope: Frontend

#76864 fix(issues): Add upcoming release check
  src/sentry/models/groupresolution.py
Labels: Scope: Backend

#76867 feat(feedback): add a FF for feedback details trace section
  src/sentry/features/temporary.py
Labels: Scope: Backend

#76366 feat(uptime): Add url_domain and url_suffix columns to the uptime subscription model
  migrations_lockfile.txt
  src/sentry/uptime/migrations/0008_uptime_url_suffix.py
  src/sentry/uptime/models.py
  tests/sentry/migrations/test_0007_update_detected_subscription_interval.py
Labels: Scope: Backend

#76572 fix(grouping): Fix project-deletion-triggered `GroupHash` deletion
  src/sentry/deletions/defaults/project.py
Labels: Scope: Backend

#76872 chore(feedback): rm unused, redundant metric
  src/sentry/tasks/update_user_reports.py
Labels: Scope: Backend

#76709 feat(replay): add mobile platforms to onboarding sidebar
  static/app/components/feedback/feedbackOnboarding/sidebar.tsx
  static/app/components/onboarding/gettingStartedDoc/types.ts
  static/app/components/onboarding/gettingStartedDoc/utils/index.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/replayOnboarding.tsx
  static/app/components/replaysOnboarding/replayOnboardingLayout.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/data/platformCategories.tsx
  static/app/gettingStartedDocs/android/android.tsx
  static/app/gettingStartedDocs/apple/ios.tsx
  static/app/gettingStartedDocs/capacitor/capacitor.tsx
  static/app/gettingStartedDocs/electron/electron.tsx
  static/app/gettingStartedDocs/javascript/angular.tsx
  static/app/gettingStartedDocs/javascript/astro.tsx
  static/app/gettingStartedDocs/javascript/ember.tsx
  static/app/gettingStartedDocs/javascript/gatsby.tsx
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/react.tsx
  static/app/gettingStartedDocs/javascript/remix.tsx
  static/app/gettingStartedDocs/javascript/solid.tsx
  static/app/gettingStartedDocs/javascript/solidstart.tsx
  static/app/gettingStartedDocs/javascript/svelte.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.tsx
  static/app/gettingStartedDocs/javascript/vue.tsx
  static/app/gettingStartedDocs/react-native/react-native.tsx
Labels: Scope: Frontend

#76879 feat(explore): Add group by to explore toolbar
  static/app/views/explore/hooks/useGroupBys.spec.tsx
  static/app/views/explore/hooks/useGroupBys.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  static/app/views/explore/toolbar/index.tsx
  static/app/views/explore/toolbar/styles.tsx
  static/app/views/explore/toolbar/toolbarDataset.tsx
  static/app/views/explore/toolbar/toolbarGroupBy.tsx
  static/app/views/explore/toolbar/toolbarLimitTo.tsx
  static/app/views/explore/toolbar/toolbarResults.tsx
  static/app/views/explore/toolbar/toolbarSortBy.tsx
  static/app/views/explore/toolbar/toolbarVisualize.tsx
Labels: Scope: Frontend

#76245 feat(grouping): Store metadata for new grouphashes
  src/sentry/event_manager.py
  src/sentry/features/temporary.py
  src/sentry/grouping/ingest/hashing.py
  src/sentry/options/defaults.py
  tests/sentry/event_manager/test_event_manager_grouping.py
Labels: Scope: Backend

#76866 fix(issues): Add back feature flag checks to the backend for upcoming release
  src/sentry/api/helpers/group_index/validators/status_details.py
  tests/snuba/api/endpoints/test_project_group_index.py
Labels: Scope: Backend

#76881 feat(new-trace): Updating trace banner images.
  static/app/views/performance/newTraceDetails/traceTypeWarnings/errorsOnlyWarnings.tsx
  static/app/views/performance/newTraceDetails/traceTypeWarnings/styles.tsx
  static/images/spot/performance-empty-trace.svg
Labels: Scope: Frontend

#76884 chore(eap): Add snuba.rpc function that reuses connection pool
  src/sentry/sentry_metrics/querying/eap/mql_eap_bridge.py
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#76869 fix(custom-views): Fix unsaved changes not triggering correctly
  static/app/views/issueList/customViewsHeader.tsx
Labels: Scope: Frontend

#76320 feat(replay): Web Vital Breadcrumb Design
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/utils/replays/extractHtml.tsx
  static/app/utils/replays/getFrameDetails.tsx
  static/app/utils/replays/highlightNode.tsx
  static/app/utils/replays/hooks/useCrumbHandlers.tsx
  static/app/utils/replays/hooks/useInitialTimeOffsetMs.spec.tsx
  static/app/utils/replays/hooks/useInitialTimeOffsetMs.tsx
  static/app/utils/replays/replayReader.tsx
  static/app/utils/replays/types.tsx
  static/app/views/replays/detail/breadcrumbs/breadcrumbRow.tsx
  static/app/views/replays/detail/useVirtualizedInspector.tsx
Labels: Scope: Frontend

#76699 chore (anomaly detection): hardcode seasonality in serializer
  src/sentry/incidents/logic.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
Labels: Scope: Backend

#76886 fix(replay/issues): prevent read on undefined data in highlights
  static/app/components/events/highlights/highlightsDataSection.tsx
Labels: Scope: Frontend

#76858 feat(feedback): add trace section to details, with analytics and FF
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/utils/analytics/feedbackAnalyticsEvents.tsx
Labels: Scope: Frontend

#76887 ref(replay): don't show mobile onboarding if org can't ingest video replays
  static/app/components/replaysOnboarding/sidebar.tsx
Labels: Scope: Frontend

#76883 ref: upgrade pytest and pytest-django
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#76765 dev(releases): add telemetry for set_commits
  src/sentry/models/release.py
Labels: Scope: Backend

#76894 fix(custom-views): Fix broken back-navigation when hitting issues
  static/app/views/issueList/customViewsHeader.tsx
Labels: Scope: Frontend

#76904 ref(formatDuration): Fix hh:mm:ss formatting to account for precision
  static/app/utils/duration/formatDuration.spec.tsx
  static/app/utils/duration/formatDuration.tsx
Labels: Scope: Frontend

#76799 fix(scrollbar): Make sidebar scrollbar nicer
  static/app/components/sidebar/index.tsx
  static/app/utils/theme.tsx
Labels: Scope: Frontend

#76721 feat(translations): Allow reusing elements
  static/app/locale.spec.tsx
  static/app/locale.tsx
Labels: Scope: Frontend

#76811 ref(onboarding): Add hook to deal with urls param
  static/app/components/onboarding/productSelection.spec.tsx
  static/app/components/onboarding/productSelection.tsx
  static/app/utils/queryString.spec.tsx
  static/app/utils/queryString.tsx
  static/app/utils/url/normalizeUrl.tsx
  static/app/utils/url/useLocationQuery.tsx
  static/app/views/onboarding/components/useOnboardingQueryParams.tsx
  static/app/views/onboarding/setupDocs.tsx
Labels: Scope: Frontend

#76851 feat(platform): Add javascript-nuxt platform in BE
  src/sentry/models/project.py
  src/sentry/utils/platform_categories.py
Labels: Scope: Backend

#76914 fix(onboarding): Additional info about feedback integration for remix
  static/app/gettingStartedDocs/javascript/remix.tsx
Labels: Scope: Frontend

#76917 chore(onboarding): Clean up nextjs onboarding - translations and wording of the notes
  static/app/gettingStartedDocs/javascript/nextjs.tsx
Labels: Scope: Frontend

#76554 ref: add hard-stop migration for index_together migrations rebase
  src/sentry/runner/commands/upgrade.py
Labels: Scope: Backend

#76891 feat(explore): Support multiple visualizes to explore toolbar
  static/app/views/explore/charts/index.tsx
  static/app/views/explore/hooks/useVisualize.spec.tsx
  static/app/views/explore/hooks/useVisualizes.spec.tsx
  static/app/views/explore/hooks/useVisualizes.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  static/app/views/explore/toolbar/index.tsx
  static/app/views/explore/toolbar/toolbarVisualize.tsx
Labels: Scope: Frontend

#76885 ref: upgrade google-crc32c
  fixtures/stubs-for-mypy/google_crc32c/__init__.pyi
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#76873 Update alerts.html
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#76923 fix(new-trace): Adding analytics for missing spans and fixing distributed tracing link.
  static/app/utils/analytics/tracingEventMap.tsx
  static/app/views/performance/newTraceDetails/traceAnalytics.tsx
  static/app/views/performance/newTraceDetails/traceConfigurations.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/index.tsx
Labels: Scope: Frontend

#76196 feat(insights): add geo selector mobile module
  static/app/views/insights/common/views/spans/selectors/subregionSelector.tsx
  static/app/views/insights/mobile/appStarts/components/samples.tsx
  static/app/views/insights/mobile/appStarts/components/tables/spanOperationTable.tsx
  static/app/views/insights/mobile/common/components/tables/samplesTables.tsx
  static/app/views/insights/mobile/screenload/components/eventSamples.tsx
  static/app/views/insights/mobile/screenload/components/tables/eventSamplesTable.tsx
  static/app/views/insights/mobile/ui/components/tables/spanOperationTable.tsx
Labels: Scope: Frontend

#76876 ref(onboarding): kotlin language changes
  static/app/components/onboarding/gettingStartedDoc/utils/metricsOnboarding.tsx
  static/app/gettingStartedDocs/java/log4j2.tsx
  static/app/gettingStartedDocs/java/logback.tsx
  static/app/gettingStartedDocs/java/spring.tsx
Labels: Scope: Frontend

#76674 fix(spans): Add sampling option for span sample table
  src/sentry/api/endpoints/organization_events_meta.py
  src/sentry/options/defaults.py
  tests/snuba/api/endpoints/test_organization_events_meta.py
Labels: Scope: Backend

#76892 fix(issue-list): Fix resolve in current release when My Projects is selected
  static/app/views/issueList/actions/index.spec.tsx
  static/app/views/issueList/actions/index.tsx
Labels: Scope: Frontend

#76906 fix(alerts): Send epoch timestamp
  src/sentry/incidents/subscription_processor.py
Labels: Scope: Backend

#76749 chore(substatus): Remove logs and substatus changes
  src/sentry/tasks/post_process.py
Labels: Scope: Backend

#76760 ref(alerts): Add support for dynamic crash rate alert
  src/sentry/incidents/logic.py
  src/sentry/seer/anomaly_detection/store_data.py
  tests/sentry/incidents/test_subscription_processor.py
  tests/sentry/seer/anomaly_detection/test_store_data.py
Labels: Scope: Backend

#76511 ref: squash index_together operation for UserReport model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76515 ref: squash index_together operation for Incident model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0575_incident_date_added_index.py
  src/sentry/migrations/0577_drop_latest_incident_index.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76890 chore(grouping): Use optimized grouping logic for 80% of non-transitioning projects
  src/sentry/grouping/ingest/config.py
  tests/sentry/event_manager/grouping/test_assign_to_group.py
Labels: Scope: Backend

#76514 ref: squash index_together operation for EventAttachment model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0600_eventattachment_metadata.py
  src/sentry/migrations/0629_eventattachment_index.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76513 ref: squash index_together operation for GroupEnvironment model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0635_groupenvironment_index.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76512 ref: squash index_together operation for ReleaseFile model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76895 fix(seer grouping): Fix metric for events from backfilled projects
  src/sentry/grouping/ingest/seer.py
Labels: Scope: Backend

#76509 ref: squash EventUser table out of existence
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0572_sentry_remove_unused_eventuser_index.py
  src/sentry/migrations/0613_drop_eventuser_table_part_1.py
  src/sentry/migrations/0614_drop_eventuser_table_part_2.py
Labels: Scope: Backend

#76508 ref: squash index_together operation for PullRequest model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76507 ref: squash index_together operation into replays initial migration
  src/sentry/replays/migrations/0001_init_replays.py
  src/sentry/replays/migrations/0002_rename_to_segment_id.py
  src/sentry/replays/migrations/0004_index_together.py
Labels: Scope: Backend

#76506 ref: squash index_together operation into feedback initial migration
  src/sentry/feedback/migrations/0001_feedback.py
  src/sentry/feedback/migrations/0004_index_together.py
Labels: Scope: Backend

#76510 ref: squash index_together operation for Commit model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0589_add_commit_date_added_indices.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76854 chore(insights): Upgrade requests span samples panel searchbar
  static/app/views/insights/http/components/httpSamplesPanel.tsx
Labels: Scope: Frontend

#76929 chore(insights): Upgrade Queues span sample panel search + `useNavigate`
  static/app/views/insights/queues/components/messageSpanSamplesPanel.tsx
Labels: Scope: Frontend

#76930 chore(insights): Upgrade cache sample panel searchbar + `useNavigate`
  static/app/views/insights/cache/components/samplePanel.tsx
Labels: Scope: Frontend

#76928 chore(insights): Upgrade search bar + `useNavigate` in Vitals module
  static/app/utils/discover/eventView.tsx
  static/app/views/insights/browser/webVitals/components/tables/pageSamplePerformanceTable.tsx
Labels: Scope: Frontend

#76898 fix(crons): Correct cursor behavior upon filtering on monitor overview page
  static/app/views/monitors/overview.spec.tsx
  static/app/views/monitors/overview.tsx
Labels: Scope: Frontend

#76367 feat(uptime): Extract domain and suffix from urls when creating uptime monitors
  src/sentry/uptime/subscriptions/subscriptions.py
  tests/sentry/uptime/subscriptions/test_subscriptions.py
Labels: Scope: Backend

#76937 fix(spans): Add duration to eap spans
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/search/events/datasets/spans_indexed.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#76945 chore(docs): Remove mention of "inUpcomingRelease"
  api-docs/paths/events/issue-details.json
Labels: Scope: Frontend

#76948 feat(spans): Add stats support to spans-eap
  src/sentry/search/events/builder/discover.py
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/snuba/spans_eap.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#76953 ref(replay): don't show rage click banner if all mobile proj
  static/app/views/replays/list/listContent.spec.tsx
  static/app/views/replays/list/listContent.tsx
Labels: Scope: Frontend

#76941 ref: upgrade just pytest-django
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#76963 feat(profiling): Give profile summary back for transaction profiles
  static/app/components/profiling/profilingTransactionHovercard.tsx
Labels: Scope: Frontend

#76968 fix(rr6): Use `query` for feedbackSlug
  static/app/views/alerts/rules/issue/details/issuesList.tsx
Labels: Scope: Frontend

#76966 feat(custom-views): Add feedback button to tab menu button
  static/app/views/issueList/groupSearchViewTabs/draggableTabMenuButton.tsx
Labels: Scope: Frontend

#76965 fix(alerts): Pass time_period as an int
  src/sentry/incidents/subscription_processor.py
  src/sentry/seer/anomaly_detection/types.py
  tests/sentry/incidents/test_subscription_processor.py
Labels: Scope: Backend

#76934 chore (anomaly detection): create proxy API endpoint
  src/sentry/api/urls.py
  src/sentry/apidocs/examples/metric_alert_examples.py
  src/sentry/incidents/endpoints/organization_alert_rule_anomalies.py
  src/sentry/seer/anomaly_detection/get_historical_anomalies.py
  src/sentry/seer/anomaly_detection/store_data.py
  src/sentry/seer/anomaly_detection/types.py
  src/sentry/seer/anomaly_detection/utils.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_anomalies.py
  tests/sentry/seer/anomaly_detection/test_store_data.py
Labels: Scope: Backend

#76954 perf(ratelimits): remove timing metric
  src/sentry/middleware/ratelimit.py
Labels: Scope: Backend

#76959 feat(custom_views): Make tabs animate better when selected
  static/app/components/draggableTabs/draggableTabList.tsx
Labels: Scope: Frontend

#76918 feat(onboarding): sentry wizard url param
  static/app/components/feedback/feedbackOnboarding/feedbackOnboardingLayout.tsx
  static/app/components/onboarding/gettingStartedDoc/onboardingLayout.tsx
  static/app/components/onboarding/gettingStartedDoc/types.ts
  static/app/components/profiling/profilingOnboardingSidebar.tsx
  static/app/components/replaysOnboarding/replayOnboardingLayout.tsx
  static/app/components/updatedEmptyState.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/remix.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.tsx
Labels: Scope: Frontend

#76951 drop(grouping): Remove mobile synthetic exception detection
  src/sentry/grouping/api.py
  src/sentry/grouping/ingest/hashing.py
  src/sentry/grouping/strategies/configurations.py
  src/sentry/grouping/strategies/newstyle.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/bugly.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_125_event_126.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_200_event_200.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_275_event_275.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_289_event_312.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_294_event_294.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_294_event_329.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_307_event_307.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_307_event_657.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_313_event_313.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_313_event_333.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_319_event_321.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_389_event_389.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_432_event_432.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_432_event_453.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/group_445_event_445.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/in_app_in_ui.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/macos_amd_driver.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/macos_intel_driver.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/malloc_sentinel.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_complex_function_names.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_driver_crash1.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_driver_crash2.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_driver_crash3.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_limit_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_malloc_chain.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_no_filenames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_unlimited_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_windows_anon_namespace.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/native_with_function_name.pysnap
  tests/sentry/grouping/test_variants.py
Labels: Scope: Backend

#76989 chore(nestjs): Add note about GraphQL applications to nest onboarding
  static/app/gettingStartedDocs/node/nestjs.tsx
Labels: Scope: Frontend

#76952 ref: upgrade google-cloud-spanner
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#76956 feat(insights): Set label for domain selector in DB module to `Collection` for MongoDB
  static/app/views/insights/common/views/spans/selectors/domainSelector.tsx
  static/app/views/insights/database/components/useSystemSelectorOptions.tsx
  static/app/views/insights/database/utils/constants.tsx
  static/app/views/insights/database/views/databaseLandingPage.spec.tsx
  static/app/views/insights/database/views/databaseLandingPage.tsx
Labels: Scope: Frontend

#76608 fix(deletion) Use a specialized deletion strategy for GroupHistory
  src/sentry/deletions/__init__.py
  src/sentry/deletions/defaults/__init__.py
  src/sentry/deletions/defaults/grouphistory.py
  tests/sentry/deletions/test_group.py
Labels: Scope: Backend

#76931 ref: squash index_together operation for ProjectDebugFile model
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0640_index_together.py
Labels: Scope: Backend

#76675 chore(apitoken): remove options
  src/sentry/api/authentication.py
  src/sentry/middleware/auth.py
  src/sentry/models/apitoken.py
  tests/sentry/api/serializers/test_apitoken.py
  tests/sentry/api/test_authentication.py
  tests/sentry/migrations/test_0726_apitoken_backfill_hashes.py
  tests/sentry/models/test_apitoken.py
Labels: Scope: Backend

#76711 ref(replay): Use formatDuration directly, or through `<Duration>` in replay
  static/app/components/duration/duration.spec.tsx
  static/app/components/duration/duration.stories.tsx
  static/app/components/duration/duration.tsx
  static/app/components/replays/player/scrubber.tsx
  static/app/components/replays/replayContext.tsx
  static/app/components/replays/timeAndScrubberGrid.tsx
  static/app/utils/duration/formatDuration.tsx
  static/app/utils/duration/formatReplayDuration.spec.tsx
  static/app/utils/duration/formatReplayDuration.tsx
  static/app/utils/replays/types.tsx
  static/app/views/replays/detail/accessibility/accessibilityRefetchBanner.tsx
  static/app/views/replays/detail/errorList/errorTableCell.tsx
  static/app/views/replays/detail/memoryPanel/domNodesChart.tsx
  static/app/views/replays/detail/memoryPanel/memoryChart.tsx
  static/app/views/replays/detail/network/details/sections.tsx
  static/app/views/replays/detail/network/networkTableCell.tsx
  static/app/views/replays/detail/timestampButton.tsx
  static/app/views/replays/replayTable/tableCell.tsx
Labels: Scope: Frontend

#76997 chore: Preserve timestamp of empty transactions in SDK setup
  static/app/bootstrap/initializeSdk.tsx
Labels: Scope: Frontend

#76983 fix(feedback): set api_expose=True for user-feedback-trace-section FF registration
  src/sentry/features/temporary.py
Labels: Scope: Backend

#76995 chore(dashboards): Add basic spec for `AutoSizedText`
  static/app/views/dashboards/widgetCard/autoSizedTest.spec.tsx
  static/app/views/dashboards/widgetCard/autoSizedText.tsx
Labels: Scope: Frontend

#76944 feat(dashboards): Add release `SearchQueryBuilder`
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/releaseSearchBar.tsx
Labels: Scope: Frontend

#76955 chore(dashboards): Add manual duration measurement for `AutoSizedText`
  static/app/views/dashboards/widgetCard/autoSizedText.tsx
Labels: Scope: Frontend

#76973 ref(reports): Remove daily report task
  src/sentry/conf/server.py
Labels: Scope: Backend

#76865 feat(issues): Add issues trace view feature flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#76958 feat(dashboards): Events `SearchQueryBuilder`
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/eventsSearchBar.tsx
  static/app/views/discover/results.tsx
  static/app/views/discover/resultsSearchQueryBuilder.tsx
Labels: Scope: Frontend

#76969 fix(profiling): Increase vroom requests timeouts
  src/sentry/profiles/utils.py
Labels: Scope: Backend

#76369 fix(ecosystem): Propagate test alert errors to the UI, behind a flag
  src/sentry/api/endpoints/project_rule_actions.py
  src/sentry/features/temporary.py
  src/sentry/options/defaults.py
  src/sentry/rules/actions/integrations/create_ticket/utils.py
  tests/sentry/api/endpoints/test_project_rule_actions.py
Labels: Scope: Backend

#77008 perf(ratelimits): adjust sample rates of ratelimit middleware timing
  src/sentry/middleware/ratelimit.py
Labels: Scope: Backend

#77010 feat(explore): Link to span
  static/app/views/explore/tables/spansTable.tsx
Labels: Scope: Frontend

#76979 fix(api): Rename to avoid confusion
  .github/workflows/openapi-diff.yml
Labels: Scope: Frontend

#76939 feat(data-secrecy): Render Data Secrecy Enabled Page for Superusers
  src/sentry/templates/sentry/data-secrecy.html
  src/sentry/web/frontend/base.py
  tests/sentry/web/frontend/test_data_secrecy_error.py
Labels: Scope: Backend

#76946 feat(explore): Adding trace samples table.
  static/app/views/explore/hooks/useTraceSpans.spec.tsx
  static/app/views/explore/hooks/useTraceSpans.tsx
  static/app/views/explore/hooks/useTraces.spec.tsx
  static/app/views/explore/hooks/useTraces.tsx
  static/app/views/explore/tables/index.tsx
  static/app/views/explore/tables/tracesTable.tsx
  static/app/views/explore/tables/tracesTable/data.tsx
  static/app/views/explore/tables/tracesTable/fieldRenderers.tsx
  static/app/views/explore/tables/tracesTable/index.tsx
  static/app/views/explore/tables/tracesTable/spansTable.tsx
  static/app/views/explore/tables/tracesTable/styles.tsx
  static/app/views/explore/tables/tracesTable/utils.tsx
Labels: Scope: Frontend

#76766 ops(celery): set hard limit for all celery tasks to 3 hours
  src/sentry/conf/server.py
Labels: Scope: Backend

#76627 ref(scm): search endpoint abstraction
  src/sentry/integrations/bitbucket/search.py
  src/sentry/integrations/github/search.py
  src/sentry/integrations/gitlab/search.py
  src/sentry/integrations/source_code_management/search.py
  src/sentry/integrations/vsts/search.py
Labels: Scope: Backend

#76999 ref: upgrade pytest to 8.1.x
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#76899 fix(auth): add /auth/sso to social auth urls
  src/sentry/web/urls.py
  src/social_auth/backends/visualstudio.py
  src/social_auth/views.py
Labels: Scope: Backend

#76975 chore(api): make index endpoint private
  src/sentry/api/endpoints/index.py
Labels: Scope: Backend

#76967 fix(issue-search): Skip archived releases when using latest alias
  src/sentry/search/utils.py
  src/sentry/testutils/factories.py
  tests/sentry/api/test_issue_search.py
Labels: Scope: Backend

#77004 fix(alerts): Pass cur_window and parse response correctly
  src/sentry/incidents/subscription_processor.py
  src/sentry/seer/anomaly_detection/types.py
  tests/sentry/incidents/test_subscription_processor.py
Labels: Scope: Backend

#77024 fix(explore) Updating banner text.
  static/app/views/performance/newTraceDetails/traceTypeWarnings/errorsOnlyWarnings.tsx
Labels: Scope: Frontend

#77025 Update alerts.html
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#77018 fix(replay): Mobile replay missing pause time
  static/app/components/replays/replayContext.tsx
Labels: Scope: Frontend

#77026 fix(grouping): Fix getting group metadata in `_save_aggregate_new`
  src/sentry/event_manager.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/tasks/test_reprocessing2.py
Labels: Scope: Backend

#77029 chore: Autofix feedback tagging
  static/app/components/events/autofix/autofixCard.tsx
Labels: Scope: Frontend

#76980 chore(api): make SlugsUpdateEndpoint private
  src/sentry/api/endpoints/organization_slugs.py
Labels: Scope: Backend

#77022 fix(uptime): Fix sorting by name for uptime rules
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_organization_combined_rule_index_endpoint.py
Labels: Scope: Backend

#77034 chore(similarity): Turn on AI grouping for all new projects
  src/sentry/api/endpoints/team_projects.py
  tests/sentry/api/endpoints/test_team_projects.py
Labels: Scope: Backend

#76977 chore(anomaly detection): replace placeholder get_historical_data with seer call
  src/sentry/seer/anomaly_detection/get_historical_anomalies.py
  src/sentry/seer/anomaly_detection/store_data.py
  src/sentry/seer/anomaly_detection/utils.py
  src/sentry/snuba/referrer.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_anomalies.py
  tests/sentry/seer/anomaly_detection/test_store_data.py
Labels: Scope: Backend

#77016 fix(alerts): Prevent muting alerts
  src/sentry/api/endpoints/rule_snooze.py
  tests/sentry/api/endpoints/test_rule_snooze.py
Labels: Scope: Backend

#76889 Anomaly Charts
  static/app/views/alerts/rules/metric/details/body.tsx
  static/app/views/alerts/rules/metric/details/index.tsx
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/details/metricChartOption.tsx
  static/app/views/alerts/types.tsx
  static/app/views/alerts/utils/apiCalls.tsx
Labels: Scope: Frontend

#77037 fix(groupIndex): fix useGroupSnubaDataset url param check
  src/sentry/issues/endpoints/organization_group_index.py
Labels: Scope: Backend

#77038 ref(alerts): Increase Seer timeout
  src/sentry/conf/server.py
Labels: Scope: Backend

#77042 feat(workflows): Set up Django app for `workflow_engine` project
  src/sentry/conf/server.py
  src/sentry/workflow_engine/__init__.py
  src/sentry/workflow_engine/apps.py
  src/sentry/workflow_engine/models/__init__.py
Labels: Scope: Backend

#77043 chore(django): Rename `DefaultFieldsModel`
  src/sentry/data_secrecy/models/datasecrecywaiver.py
  src/sentry/db/models/base.py
  src/sentry/integrations/models/integration.py
  src/sentry/integrations/models/repository_project_path_config.py
  src/sentry/models/groupsearchview.py
  src/sentry/models/importchunk.py
  src/sentry/models/integrations/sentry_app_installation_for_provider.py
  src/sentry/models/notificationsettingbase.py
  src/sentry/models/projecttemplate.py
  src/sentry/models/relocation.py
  src/sentry/models/transaction_threshold.py
  src/sentry/sentry_metrics/models/spanattributeextractionrules.py
  src/sentry/uptime/models.py
  tests/sentry/backup/test_sanitize.py
Labels: Scope: Backend

#77050 chore(django): Add new db default fields model
  src/sentry/db/models/base.py
Labels: Scope: Backend
