Repository getsentry/sentry, pull requests merged in 2024-01, with the labels that each got.

#61351 feat(ddm): Extend billing consumer to update flag on project model
  src/sentry/ingest/billing_metrics_consumer.py
  tests/sentry/ingest/billing_metrics_consumer/test_billing_metrics_consumer_kafka.py
Labels: Scope: Backend

#62464 fix(ddm): responsive focus area
  static/app/views/ddm/chart.tsx
  static/app/views/ddm/chartBrush.tsx
Labels: Scope: Frontend

#62117 chore(starfish): Introduce flag for platform selector
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#62467 feat(ddm): Limit to 10000 the results
  src/sentry/sentry_metrics/querying/api.py
Labels: Scope: Backend

#62232 decouple handle_query_errors and move into api utils
  src/sentry/api/utils.py
  tests/sentry/api/test_utils.py
Labels: Scope: Backend

#62476 perf(chartcuterie): optimize min/max domain search
  static/app/views/alerts/rules/metric/details/metricChartOption.tsx
Labels: Scope: Frontend

#62450 ref(js): Named export for RouterPropsFixture
  fixtures/js-stubs/routerPropsFixture.tsx
  tests/js/setup.ts
Labels: Scope: Frontend

#62438 fix(crons): Enforce min of 1 for interval frequency
  static/app/views/monitors/components/monitorForm.tsx
Labels: Scope: Frontend

#62440 test(crons): Add test to MonitorForm
  fixtures/js-stubs/monitor.tsx
  static/app/views/monitors/components/monitorForm.spec.tsx
  static/app/views/monitors/components/monitorForm.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#62425 test(crons): Add utils tests
  static/app/views/monitors/utils.spec.tsx
  static/app/views/monitors/utils.tsx
Labels: Scope: Frontend

#62140 feat(issues): Add Hydration Error resource to issue details
  static/app/utils/issueTypeConfig/errorConfig.tsx
  static/app/utils/issueTypeConfig/types.tsx
Labels: Scope: Frontend

#62015 fix(clippedbox): Adjust max-height to the content height when revealing
  static/app/components/clippedBox.tsx
Labels: Scope: Frontend

#62060 ref(ts): Fix types for updateMonitor
  static/app/actionCreators/monitors.tsx
  static/app/views/monitors/components/monitorHeaderActions.tsx
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#62072 feat(crons): Add monitor-status-toggle hook
  static/app/types/hooks.tsx
  static/app/views/monitors/components/monitorHeaderActions.tsx
  static/app/views/monitors/components/overviewTimeline/timelineTableRow.tsx
  static/app/views/monitors/components/statusToggleButton.tsx
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#62451 ref(js): Better error in useTeams for missing org context
  static/app/utils/useTeams.tsx
Labels: Scope: Frontend

#62282 ref(auth): Create base authindex endpoint class
  src/sentry/api/endpoints/auth_index.py
Labels: Scope: Backend

#61883 feat(apis): add ownership to open-source apis
  src/sentry/api/api_owners.py
  src/sentry/api/endpoints/internal/beacon.py
  src/sentry/api/endpoints/internal/environment.py
  src/sentry/api/endpoints/internal/feature_flags.py
  src/sentry/api/endpoints/internal/mail.py
  src/sentry/api/endpoints/internal/packages.py
  src/sentry/api/endpoints/internal/queue_tasks.py
  src/sentry/api/endpoints/internal/quotas.py
  src/sentry/api/endpoints/internal/stats.py
  src/sentry/api/endpoints/internal/warnings.py
  src/sentry/api/endpoints/relocations/abort.py
  src/sentry/api/endpoints/relocations/cancel.py
  src/sentry/api/endpoints/relocations/details.py
  src/sentry/api/endpoints/relocations/index.py
  src/sentry/api/endpoints/relocations/pause.py
  src/sentry/api/endpoints/relocations/public_key.py
  src/sentry/api/endpoints/relocations/unpause.py
Labels: Scope: Backend

#62471 fix(replays): Remove column shadowing and eagerly exit when counting replays
  src/sentry/replays/query.py
  src/sentry/replays/usecases/replay_counts.py
Labels: Scope: Backend

#61692 ref(crons): Remove deprecated "muted" status translation
  src/sentry/monitors/validators.py
  tests/sentry/monitors/endpoints/test_organization_monitor_details.py
Labels: Scope: Backend

#62284 ref(crons): Refactor out monitor detail query key generation
  static/app/views/monitors/details.tsx
  static/app/views/monitors/edit.tsx
  static/app/views/monitors/utils.tsx
Labels: Scope: Frontend

#62479 ref(ts): Remove unnecessary Date type parameters
  static/app/components/events/interfaces/crons/cronTimelineSection.tsx
  static/app/components/events/interfaces/performance/durationChart.tsx
  static/app/components/events/interfaces/performance/spanCountChart.tsx
  static/app/views/monitors/components/cronDetailsTimeline.tsx
  static/app/views/monitors/components/monitorStats.tsx
  static/app/views/monitors/components/overviewTimeline/index.tsx
Labels: Scope: Frontend

#62480 fix(crons): Remove environment limitation on details page
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#62481 ref(replays): add message about setting up trace propagation in onboarding sidebar
  static/app/components/replaysOnboarding/sidebar.tsx
Labels: Scope: Frontend

#62483 fix(suspect-commits): Allow rate_limit calls to fail for GitHub
  src/sentry/integrations/github/client.py
  tests/sentry/integrations/github/test_client.py
Labels: Scope: Backend

#61407 chore(snuba): update referrer
  src/sentry/snuba/referrer.py
Labels: Scope: Backend, Stale

#62441 fix(beacon): Events in 24h for now calculated properly
  src/sentry/tasks/beacon.py
  tests/sentry/tasks/test_beacon.py
Labels: Scope: Backend

#62405 feat(stacktrace): Fix broken syntax highlighting when there are cut-off block comments
  static/app/components/events/interfaces/frame/context.tsx
  static/app/components/events/interfaces/frame/usePrismTokensSourceContext.spec.tsx
  static/app/components/events/interfaces/frame/usePrismTokensSourceContext.tsx
  static/app/utils/usePrismTokens.tsx
Labels: Scope: Frontend

#62406 feat(revenue): Add monitor seats data category
  static/app/types/core.tsx
Labels: Scope: Frontend

#62180 cleanup(replays): Delete unused cache interfaces
  src/sentry/replays/cache.py
Labels: Scope: Backend

#62492 deps(ui): Update react-aria, react-stately packages
  package.json
  static/app/components/compactSelect/list.tsx
  yarn.lock
Labels: Scope: Frontend

#62341 fix(discord): Log and warn rather than raise error
  src/sentry/integrations/discord/webhooks/command.py
  tests/sentry/integrations/discord/webhooks/test_command.py
Labels: Scope: Backend

#62354 fix(issues): Repeat issues request if project id changes
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#60955 ref(crons): Add parallelism to monitor_consumer
  src/sentry/monitors/consumers/monitor_consumer.py
  src/sentry/monitors/types.py
Labels: Scope: Backend

#62498 feat(replays): add FAQ section to replay onboarding
  static/app/components/accordion/accordion.tsx
  static/app/views/replays/list/replayOnboardingPanel.tsx
Labels: Scope: Frontend

#62104 feat(replays): Add alternative buffered I/O recording consumer implementation
  src/sentry/consumers/__init__.py
  src/sentry/replays/consumers/recording_buffered.py
  src/sentry/replays/usecases/ingest/__init__.py
  src/sentry/replays/usecases/ingest/dom_index.py
  tests/sentry/replays/consumers/test_recording.py
Labels: Scope: Backend

#62500 fix(ui): Prevent projects from being undefined
  static/app/actionCreators/organization.tsx
Labels: Scope: Frontend

#62285 feat(crons): Add delete option to monitor details
  static/app/views/monitors/components/cronDetailsTimeline.tsx
Labels: Scope: Frontend

#62502 disable cursor query from release-threshold api query
  static/app/views/releases/list/index.tsx
Labels: Scope: Frontend

#62277 feat(project-creation): Add bitfield flag for org-wide setting
  migrations_lockfile.txt
  src/sentry/migrations/0626_add_member_project_creation_bitfield.py
  src/sentry/models/organization.py
  tests/sentry/models/test_organization.py
Labels: Scope: Backend

#62287 feat(crons): Add mute env option to details page
  static/app/views/monitors/components/cronDetailsTimeline.tsx
Labels: Scope: Frontend

#62499 feat(feedback): remove feedback ingest endpoint
  src/sentry/api/urls.py
  src/sentry/feedback/endpoints/feedback_ingest.py
  tests/sentry/feedback/test_feedback_ingest.py
Labels: Scope: Backend

#62514 feat(api): Privatize self-hosted-only internal APIs
  src/sentry/api/endpoints/internal/beacon.py
  src/sentry/api/endpoints/internal/environment.py
  src/sentry/api/endpoints/internal/mail.py
  src/sentry/api/endpoints/internal/packages.py
  src/sentry/api/endpoints/internal/queue_tasks.py
  src/sentry/api/endpoints/internal/quotas.py
  src/sentry/api/endpoints/internal/stats.py
  src/sentry/api/endpoints/internal/warnings.py
Labels: Scope: Backend

#62487 fix(replay): Dont emit an EventView from useReplaysFromIssue when no replayIds are in the fetched list
  static/app/views/issueDetails/groupReplays/groupReplays.tsx
  static/app/views/issueDetails/groupReplays/useReplaysFromIssue.spec.tsx
  static/app/views/issueDetails/groupReplays/useReplaysFromIssue.tsx
Labels: Scope: Frontend

#62513 feat(issue details): add replay onboarding CTA for backend projects
  static/app/components/events/eventReplay/eventReplaySection.tsx
  static/app/components/events/eventReplay/index.tsx
  static/app/components/events/eventReplay/replayInlineOnboardingPanelBackend.tsx
  static/app/data/platformCategories.tsx
  static/images/spot/replay-onboarding-backend.svg
Labels: Scope: Frontend

#62522 fix(replays): add additional check in case replayId exists
  static/app/components/events/eventReplay/index.tsx
Labels: Scope: Frontend

#62524 feat(crons): Add options to enable check_accept_monitor_checkin
  src/sentry/options/defaults.py
Labels: Scope: Backend

#62424 fix(ddm): Scratchpad project selection
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/utils/metrics/index.tsx
  static/app/views/ddm/ddm.tsx
  static/app/views/ddm/layout.tsx
  static/app/views/ddm/scratchpadContext.tsx
  static/app/views/ddm/scratchpadSelector.tsx
Labels: Scope: Frontend

#62468 Use zstd compression for `CachedAttachment`s
  src/sentry/attachments/base.py
  src/sentry/options/defaults.py
  tests/sentry/attachments/test_base.py
Labels: Scope: Backend

#62461 chore(alerts): remove migration email templates
  src/sentry/static/sentry/images/email/alert-migration-lgtm.png
  src/sentry/templates/sentry/emails/alert_migration.html
  src/sentry/templates/sentry/emails/alert_migration.txt
Labels: Scope: Backend

#62318 Save `EventAttachment` blobs directly
  src/sentry/api/endpoints/event_attachment_details.py
  src/sentry/event_manager.py
  src/sentry/models/eventattachment.py
  src/sentry/models/files/utils.py
  src/sentry/options/defaults.py
  tests/relay_integration/test_integration.py
  tests/sentry/api/endpoints/test_event_attachment_details.py
Labels: Scope: Backend

#62532 ref(ddm): Use hasCustomMetrics flag
  fixtures/js-stubs/project.tsx
  static/app/types/project.tsx
  static/app/views/ddm/context.tsx
  static/app/views/ddm/layout.tsx
  static/app/views/ddm/scratchpadContext.tsx
  static/app/views/ddm/scratchpadSelector.tsx
Labels: Scope: Frontend

#62534 feat(ddm): Implement dynamic interval calculation for metrics API
  src/sentry/sentry_metrics/querying/api.py
  tests/sentry/sentry_metrics/querying/test_api.py
Labels: Scope: Backend

#62544 fix(ddm): Scratchpad without project param
  static/app/views/ddm/scratchpadContext.tsx
Labels: Scope: Frontend

#62552 Use list instead of set for `options`
  src/sentry/options/defaults.py
Labels: Scope: Backend

#62550 Do not double-store an unprocessed Event in NodeStore
  src/sentry/event_manager.py
  src/sentry/reprocessing2.py
Labels: Scope: Backend

#62551 fix(ddm): Search tag values
  static/app/views/ddm/queryBuilder.tsx
Labels: Scope: Frontend

#62546 ref: fix typing of sentry.identity.vsts.provider
  pyproject.toml
  src/sentry/identity/vsts/provider.py
Labels: Scope: Backend

#62545 ref: fix erroneously passing code=400 to ValidationError
  pyproject.toml
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/helpers/group_index/update.py
  src/sentry/issues/merge.py
Labels: Scope: Backend

#62547 ref: fix typing for sentry.mail.notifications
  pyproject.toml
  src/sentry/mail/notifications.py
Labels: Scope: Backend

#62554 feat(ddm): samples table
  static/app/components/modals/widgetViewerModal.tsx
  static/app/utils/metrics/index.tsx
  static/app/utils/metrics/useMetricsCodeLocations.tsx
  static/app/views/ddm/sampleTable.tsx
  static/app/views/ddm/samplesTable.tsx
  static/app/views/ddm/widgetDetails.tsx
Labels: Scope: Frontend

#62555 ref: add metrics to native and javascript stacktraces processing symbolicator requests
  src/sentry/lang/javascript/processing.py
  src/sentry/lang/native/processing.py
Labels: Scope: Backend

#61679 feat(performance-tracing-details): Adding event details slideout panel.
  static/app/components/events/eventCustomPerformanceMetrics.tsx
  static/app/components/events/eventDataSection.tsx
  static/app/components/events/eventEntries.tsx
  static/app/components/events/interfaces/breadcrumbs/index.tsx
  static/app/types/event.tsx
  static/app/views/performance/traceDetails/newTraceDetailsContent.tsx
  static/app/views/performance/traceDetails/newTraceDetailsTraceView.tsx
  static/app/views/performance/traceDetails/newTraceDetailsTransactionBar.tsx
  static/app/views/performance/traceDetails/styles.tsx
  static/app/views/performance/traceDetails/traceViewDetailPanel.tsx
  static/app/views/performance/traceDetails/transactionGroup.tsx
Labels: Scope: Frontend

#62548 ref: fix typing for sentry.management.commands.makemigrations
  pyproject.toml
  src/sentry/management/commands/makemigrations.py
Labels: Scope: Backend

#62433 chore(ts): Remove JS fixture lazy-loading
  .eslintrc.js
  fixtures/js-stubs/types.tsx
  tests/js/sentry-test/loadFixtures.ts
  tests/js/setup.ts
Labels: Scope: Frontend

#62517 feat(feedback): delete prototype retrieval endpoints
  src/sentry/api/urls.py
  src/sentry/feedback/endpoints/__init__.py
  src/sentry/feedback/endpoints/base.py
  src/sentry/feedback/endpoints/organization_feedback_index.py
  src/sentry/feedback/endpoints/project_feedback_details.py
  src/sentry/feedback/serializers.py
  tests/sentry/feedback/test_organization_feedback_index.py
  tests/sentry/feedback/test_project_feedback_details.py
Labels: Scope: Backend

#62566 fix(mql): Set correct Dataset based on use case ID
  src/sentry/snuba/metrics_layer/query.py
  tests/snuba/test_metrics_layer.py
Labels: Scope: Backend

#62477 feat(app-startup): Add Cold/Warm start widgets on summary page
  static/app/views/starfish/views/appStartup/screenSummary/deviceClassBreakdownBarChart.tsx
  static/app/views/starfish/views/appStartup/screenSummary/widgets.tsx
  static/app/views/starfish/views/screens/screenLoadSpans/charts.tsx
  static/app/views/starfish/views/screens/utils.tsx
Labels: Scope: Frontend

#62491 Utilize decoupled handle query errors
  src/sentry/api/bases/organization_events.py
  src/sentry/api/endpoints/organization_event_details.py
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/endpoints/organization_events_facets.py
  src/sentry/api/endpoints/organization_events_facets_performance.py
  src/sentry/api/endpoints/organization_events_has_measurements.py
  src/sentry/api/endpoints/organization_events_histogram.py
  src/sentry/api/endpoints/organization_events_meta.py
  src/sentry/api/endpoints/organization_events_root_cause_analysis.py
  src/sentry/api/endpoints/organization_events_span_ops.py
  src/sentry/api/endpoints/organization_events_spans_histogram.py
  src/sentry/api/endpoints/organization_events_spans_performance.py
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/api/endpoints/organization_events_trends.py
  src/sentry/api/endpoints/organization_events_trends_v2.py
  src/sentry/api/endpoints/organization_events_vitals.py
  src/sentry/api/endpoints/organization_group_index.py
  src/sentry/api/endpoints/organization_group_index_stats.py
  src/sentry/api/endpoints/organization_issues_count.py
  src/sentry/api/endpoints/organization_measurements_meta.py
  src/sentry/api/endpoints/organization_metrics_estimation_stats.py
  src/sentry/api/endpoints/organization_metrics_meta.py
  src/sentry/api/endpoints/organization_profiling_functions.py
  src/sentry/api/endpoints/organization_sdk_updates.py
  src/sentry/api/endpoints/organization_sessions.py
  src/sentry/api/endpoints/organization_stats_summary.py
  src/sentry/api/endpoints/organization_stats_v2.py
  src/sentry/api/endpoints/organization_tagkey_values.py
  src/sentry/api/endpoints/organization_tags.py
  src/sentry/api/endpoints/organization_transaction_anomaly_detection.py
  src/sentry/api/utils.py
  tests/sentry/api/test_utils.py
Labels: Scope: Backend

#62355 feat(metrics-layer): Support release-health tag resolution
  src/sentry/snuba/metrics_layer/query.py
  tests/sentry/snuba/metrics/test_metrics_query_layer/test_metrics_query_layer.py
  tests/snuba/test_metrics_layer.py
Labels: Scope: Backend

#62574 feat(crons): Increase Rule frequency
  src/sentry/monitors/utils.py
Labels: Scope: Backend

#62575 ref(ts:) Remove test stubs export aliases
  fixtures/js-stubs/availableNotificationActions.tsx
  fixtures/js-stubs/config.tsx
  fixtures/js-stubs/group.ts
  fixtures/js-stubs/member.tsx
  fixtures/js-stubs/organization.tsx
  fixtures/js-stubs/project.tsx
  fixtures/js-stubs/team.tsx
  fixtures/js-stubs/user.tsx
Labels: Scope: Frontend

#62526 fix(backup): Fix mis-migrated AlertRule imports
  src/sentry/incidents/models.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#62577 ref(ts): Remove unused exports for fixtures
  fixtures/js-stubs/locationFixture.tsx
  fixtures/js-stubs/routeComponentPropsFixture.tsx
  fixtures/js-stubs/routerContextFixture.tsx
  fixtures/js-stubs/routerFixture.tsx
  fixtures/js-stubs/routerPropsFixture.tsx
Labels: Scope: Frontend

#62572 ref(replays): update FAQ wording
  static/app/views/replays/list/replayOnboardingPanel.tsx
Labels: Scope: Frontend

#62576 fix(replays): Commit on poll and join in buffered recording consumer
  src/sentry/replays/consumers/recording_buffered.py
  tests/sentry/replays/unit/test_recording_buffer.py
Labels: Scope: Backend

#62580 fix(custom-measurments): Handle measurement names with numbers
  src/sentry/snuba/metrics/naming_layer/mri.py
  tests/sentry/snuba/metrics/test_naming_layer.py
  tests/snuba/api/endpoints/test_organization_measurements_meta.py
Labels: Scope: Backend

#62246 feat(system): Use custom slug field
  migrations_lockfile.txt
  pyproject.toml
  src/sentry/api/endpoints/integrations/sentry_apps/installation/index.py
  src/sentry/api/endpoints/organization_teams.py
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/endpoints/relocations/index.py
  src/sentry/api/endpoints/team_details.py
  src/sentry/api/endpoints/team_projects.py
  src/sentry/api/fields/sentry_slug.py
  src/sentry/api/helpers/slugs.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/db/models/fields/slug.py
  src/sentry/migrations/0627_change_to_sentry_slug.py
  src/sentry/models/dashboard.py
  src/sentry/models/integrations/doc_integration.py
  src/sentry/models/integrations/sentry_app.py
  src/sentry/models/organization.py
  src/sentry/models/project.py
  src/sentry/models/sentryfunction.py
  src/sentry/models/team.py
  src/sentry/monitors/models.py
  src/sentry/monitors/validators.py
  src/sentry/slug/__init__.py
  src/sentry/slug/errors.py
  src/sentry/slug/patterns.py
  src/sentry/slug/validators.py
  tests/sentry/api/endpoints/test_organization_index.py
  tests/sentry/api/endpoints/test_organization_sentry_app_installations.py
  tests/sentry/api/endpoints/test_organization_teams.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/api/endpoints/test_team_details.py
  tests/sentry/api/endpoints/test_team_projects.py
  tests/sentry/db/models/fields/test_slug.py
  tests/sentry/monitors/endpoints/test_monitor_ingest_checkin_index.py
  tests/sentry/monitors/endpoints/test_organization_monitor_details.py
  tests/sentry/monitors/endpoints/test_organization_monitor_index.py
Labels: Scope: Backend

#62516 feat(alerts): Refactor Alert Settings to FC
  fixtures/js-stubs/integrationListDirectory.ts
  static/app/views/settings/projectAlerts/index.tsx
  static/app/views/settings/projectAlerts/settings.spec.tsx
  static/app/views/settings/projectAlerts/settings.tsx
Labels: Scope: Frontend

#62581 chore(crons): Add hasMonitors field to project type def
  fixtures/js-stubs/project.tsx
  static/app/types/project.tsx
Labels: Scope: Frontend

#62523 fix(stacktrace): Extend syntax highlight block comment fix to all languages
  static/app/components/events/interfaces/frame/usePrismTokensSourceContext.spec.tsx
  static/app/components/events/interfaces/frame/usePrismTokensSourceContext.tsx
  static/app/utils/prism.tsx
Labels: Scope: Frontend

#62586 chore(relocation): Add name to relocation url
  src/sentry/web/urls.py
Labels: Scope: Backend

#62587 fix(replay): Always emit if a replay has a hydration breadcrumb
  static/app/utils/replays/hooks/useLogReplayDataLoaded.tsx
Labels: Scope: Frontend

#62460 feat(crons): Feature flag for disabling crons in new projects
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#62582 feat(crons): Disable new monitors in projects without monitors in FE
  static/app/views/monitors/components/monitorForm.tsx
  static/app/views/monitors/overview.tsx
Labels: Scope: Frontend

#62512 feat(crons): Check quotas.check_accept_monitor_checkin in monitor_consumer
  src/sentry/monitors/consumers/monitor_consumer.py
  tests/sentry/monitors/test_monitor_consumer.py
Labels: Scope: Backend

#62597 fix(replay onboarding): fix bug where mask/block toggles not working for JS Loader
  static/app/components/onboarding/gettingStartedDoc/utils/index.tsx
Labels: Scope: Frontend

#62556 fix(smart-search-bar): Debouncing dropdown updates
  static/app/components/smartSearchBar/index.tsx
  static/app/views/issueList/savedIssueSearches.spec.tsx
  static/app/views/performance/transactionSummary/transactionVitals/index.spec.tsx
Labels: Scope: Frontend

#62561 Compress whole Attachment in memory
  src/sentry/models/eventattachment.py
Labels: Scope: Backend

#62606 Switch back to `StreamingHttpResponse` for Attachment Downloads
  src/sentry/api/endpoints/event_attachment_details.py
  tests/sentry/api/endpoints/test_event_attachment_details.py
Labels: Scope: Backend

#62607 feat(ddm-dashboards): Add table columns
  static/app/views/discover/table/columnEditCollection.tsx
Labels: Scope: Frontend

#62578 fix(database): Sync chart and table filters on the landing page
  static/app/views/performance/database/databaseLandingPage.spec.tsx
  static/app/views/performance/database/databaseLandingPage.tsx
Labels: Scope: Frontend

#62612 Add metric for legacy ReleaseFile uploads
  src/sentry/api/endpoints/project_release_files.py
Labels: Scope: Backend

#62588 ref(ts): Remove fixture type aliases
  fixtures/js-stubs/accessRequest.tsx
  fixtures/js-stubs/actor.tsx
  fixtures/js-stubs/apiApplication.tsx
  fixtures/js-stubs/apiToken.tsx
  fixtures/js-stubs/auditLogs.tsx
  fixtures/js-stubs/authProvider.tsx
  fixtures/js-stubs/authProviders.tsx
  fixtures/js-stubs/authenticators.tsx
  fixtures/js-stubs/availableNotificationActions.tsx
  fixtures/js-stubs/broadcast.tsx
  fixtures/js-stubs/builtInSymbolSources.tsx
  fixtures/js-stubs/codeOwner.ts
  fixtures/js-stubs/commit.ts
  fixtures/js-stubs/config.tsx
  fixtures/js-stubs/dashboard.tsx
  fixtures/js-stubs/debugFile.ts
  fixtures/js-stubs/deprecatedApiKey.tsx
  fixtures/js-stubs/docIntegration.ts
  fixtures/js-stubs/entries.ts
  fixtures/js-stubs/event.ts
  fixtures/js-stubs/eventAttachment.ts
  fixtures/js-stubs/eventEntry.ts
  fixtures/js-stubs/events.ts
  fixtures/js-stubs/exceptionValue.tsx
  fixtures/js-stubs/frame.tsx
  fixtures/js-stubs/group.ts
  fixtures/js-stubs/groupStats.ts
  fixtures/js-stubs/image.tsx
  fixtures/js-stubs/incident.ts
  fixtures/js-stubs/incidentStats.ts
  fixtures/js-stubs/member.tsx
  fixtures/js-stubs/members.tsx
  fixtures/js-stubs/organizations.tsx
  fixtures/js-stubs/pageFilters.ts
  fixtures/js-stubs/platformExternalIssue.tsx
  fixtures/js-stubs/plugin.tsx
  fixtures/js-stubs/plugins.tsx
  fixtures/js-stubs/project.tsx
  fixtures/js-stubs/projectSdkUpdates.tsx
  fixtures/js-stubs/pullRequest.tsx
  fixtures/js-stubs/releaseMeta.ts
  fixtures/js-stubs/replayList.ts
  fixtures/js-stubs/repository.ts
  fixtures/js-stubs/repositoryProjectPathConfig.ts
  fixtures/js-stubs/sentryApp.tsx
  fixtures/js-stubs/sentryAppComponent.ts
  fixtures/js-stubs/sentryAppInstallation.tsx
  fixtures/js-stubs/sentryAppWebhookRequest.tsx
  fixtures/js-stubs/team.tsx
  fixtures/js-stubs/traceError.tsx
  fixtures/js-stubs/user.tsx
  fixtures/js-stubs/userFeedback.tsx
  fixtures/js-stubs/widget.tsx
Labels: Scope: Frontend

#62349 ref: upgrade to urllib3 2.x
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-dev.txt
  requirements-frozen.txt
  src/sentry/hybridcloud/apigateway/proxy.py
  src/sentry/mediators/external_requests/alert_rule_action_requester.py
  src/sentry/net/http.py
  src/sentry/shared_integrations/exceptions/__init__.py
Labels: Scope: Backend

#62348 fix(discover): Round query end times up when quantizing
  src/sentry/api/bases/organization_events.py
  src/sentry/utils/snuba.py
  tests/sentry/utils/test_snuba.py
Labels: Scope: Backend

#62616 fix(replays): Cap the number of aggregation targets we'll search for to match the number of aggregations we'll return
  src/sentry/replays/usecases/replay_counts.py
Labels: Scope: Backend

#62614 fix(severity): Use Events dataset for escalation threshold query
  src/sentry/issues/issue_velocity.py
  tests/sentry/issues/test_issue_velocity.py
Labels: Scope: Backend

#62530 fix: empty replays count badge
  static/app/components/replays/replayCountBadge.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#62228 ref: Change alert rule serializers to accept name of 256 chars
  src/sentry/api/endpoints/project_rule_details.py
  src/sentry/api/endpoints/project_rules.py
  src/sentry/api/serializers/rest_framework/rule.py
  src/sentry/incidents/endpoints/organization_alert_rule_details.py
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
  src/sentry/incidents/serializers/alert_rule.py
  tests/sentry/api/endpoints/test_project_rules.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
Labels: Scope: Backend

#62620 ref: new flake8 rule S009 + fix exception reraising
  config/hooks/pre-commit
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/endpoints/project_artifact_bundle_files.py
  src/sentry/api/validators/sentry_apps/schema.py
  src/sentry/backup/imports.py
  src/sentry/db/postgres/creation.py
  src/sentry/grouping/enhancer/__init__.py
  src/sentry/identity/gitlab/provider.py
  src/sentry/incidents/charts.py
  src/sentry/integrations/bitbucket/search.py
  src/sentry/integrations/discord/utils/auth.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/github_enterprise/integration.py
  src/sentry/integrations/gitlab/client.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/integrations/jira/views/sentry_issue_details.py
  src/sentry/integrations/mixins/commit_context.py
  src/sentry/integrations/opsgenie/actions/notification.py
  src/sentry/integrations/opsgenie/utils.py
  src/sentry/integrations/pagerduty/actions/notification.py
  src/sentry/integrations/pagerduty/utils.py
  src/sentry/integrations/slack/utils/channel.py
  src/sentry/integrations/utils/commit_context.py
  src/sentry/integrations/vercel/client.py
  src/sentry/integrations/vercel/integration.py
  src/sentry/integrations/vsts/integration.py
  src/sentry/mediators/mediator.py
  src/sentry/models/groupsubscription.py
  src/sentry/models/identity.py
  src/sentry/models/outbox.py
  src/sentry/plugins/bases/notify.py
  src/sentry/plugins/providers/integration_repository.py
  src/sentry/receivers/outbox/control.py
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/runner/__init__.py
  src/sentry/runner/commands/backup.py
  src/sentry/search/snuba/executors.py
  src/sentry/sentry_metrics/indexer/postgres/postgres_v2.py
  src/sentry/services/hybrid_cloud/organizationmember_mapping/impl.py
  src/sentry/shared_integrations/client/base.py
  src/sentry/silo/client.py
  src/sentry/snuba/metrics_enhanced_performance.py
  src/sentry/snuba/metrics_layer/query.py
  src/sentry/tasks/deletion/hybrid_cloud.py
  src/sentry/tasks/deletion/scheduled.py
  src/sentry/tasks/derive_code_mappings.py
  src/sentry/tasks/integrations/github/open_pr_comment.py
  src/sentry/tasks/integrations/github/pr_comment.py
  src/sentry/tasks/integrations/link_all_repos.py
  src/sentry/utils/relocation.py
  src/sentry_plugins/slack/plugin.py
  src/sentry_plugins/splunk/plugin.py
  tests/sentry/incidents/test_models.py
  tests/sentry/models/test_outbox.py
  tests/tools/test_flake8_plugin.py
  tools/flake8_plugin.py
Labels: Scope: Backend

#62529 ref(ui): Convert account details to FC
  static/app/actionCreators/account.tsx
  static/app/views/settings/account/accountDetails.spec.tsx
  static/app/views/settings/account/accountDetails.tsx
Labels: Scope: Frontend

#62599 feat(integrations): Add integration details to activity created in status sync
  src/sentry/tasks/integrations/sync_status_inbound.py
  tests/sentry/integrations/test_issues.py
Labels: Scope: Backend

#62525 ref(settings): Refactor PluginConfig to functional component
  static/app/components/pluginConfig.spec.tsx
  static/app/components/pluginConfig.tsx
  static/app/components/pluginList.tsx
  static/app/views/settings/projectPlugins/details.tsx
Labels: Scope: Frontend

#62624 bug(replay): Make sure replayId is valid before calling replayExists()
  static/app/utils/discover/viewReplayLink.tsx
Labels: Scope: Frontend

#62622 ref: add lint rule to encourage override_options instead of override_settings(SENTRY_OPTIONS=...)
  setup.cfg
  src/sentry/testutils/helpers/options.py
  tests/sentry/api/endpoints/test_relay_projectids.py
  tests/sentry/api/endpoints/test_relay_register.py
  tests/sentry/api/endpoints/test_system_options.py
  tests/sentry/api/endpoints/test_user_authenticator_details.py
  tests/sentry/api/endpoints/test_user_authenticator_enroll.py
  tests/sentry/api/endpoints/test_user_authenticators_index.py
  tests/sentry/helpers/test_deprecation.py
  tests/sentry/tsdb/test_redis.py
  tests/tools/test_flake8_plugin.py
  tools/flake8_plugin.py
Labels: Scope: Backend

#62585 feat(crons): Disable new monitors in projects without monitors in BE
  src/sentry/monitors/consumers/monitor_consumer.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_index.py
  src/sentry/monitors/endpoints/organization_monitor_index.py
  tests/sentry/monitors/endpoints/test_monitor_ingest_checkin_index.py
  tests/sentry/monitors/endpoints/test_organization_monitor_index.py
  tests/sentry/monitors/test_monitor_consumer.py
Labels: Scope: Backend

#62429 feat(issue-stream): Updated waiting for events
  static/app/components/waitingForEvents.spec.tsx
  static/app/components/waitingForEvents.tsx
  static/app/views/issueList/noGroupsHandler/index.tsx
Labels: Scope: Frontend

#62626 fix(ui): Allow null organization in account details
  static/app/views/settings/account/accountDetails.tsx
Labels: Scope: Frontend

#62473 fix(hybrid-cloud): Avoid attribute error on response_url
  src/sentry/middleware/integrations/parsers/slack.py
Labels: Scope: Backend

#62628 chore(stats-detectors): Update the released issue type
  src/sentry/issues/grouptype.py
Labels: Scope: Backend

#62569 ref(settings): Convert account emails to FC
  static/app/views/settings/account/accountEmails.spec.tsx
  static/app/views/settings/account/accountEmails.tsx
Labels: Scope: Frontend

#62592 test(relocation): Improve tests
  src/sentry/api/endpoints/relocations/index.py
  tests/sentry/api/endpoints/relocations/test_abort.py
  tests/sentry/api/endpoints/relocations/test_cancel.py
  tests/sentry/api/endpoints/relocations/test_details.py
  tests/sentry/api/endpoints/relocations/test_index.py
  tests/sentry/api/endpoints/relocations/test_pause.py
  tests/sentry/api/endpoints/relocations/test_unpause.py
  tests/sentry/api/serializers/test_relocation.py
  tests/sentry/backup/test_models.py
  tests/sentry/tasks/test_relocation.py
Labels: Scope: Backend

#62632 feat(feedback): add tags to user feedback shim
  src/sentry/feedback/usecases/create_feedback.py
  tests/sentry/api/endpoints/test_project_user_reports.py
Labels: Scope: Backend

#62437 feat(issue-stream): Updated empty state for no issues matches
  static/app/views/issueList/noGroupsHandler/index.tsx
  static/app/views/issueList/noGroupsHandler/noIssuesMatched.tsx
Labels: Scope: Frontend

#62631 ref(replays): update issue details cta banner title
  static/app/components/events/eventReplay/replayInlineOnboardingPanelBackend.tsx
Labels: Scope: Frontend

#62633 ref(replays onboarding): add http, negroni, go to allowed backend platforms
  static/app/data/platformCategories.tsx
  static/app/gettingStartedDocs/go/go.tsx
  static/app/gettingStartedDocs/go/http.tsx
  static/app/gettingStartedDocs/go/negroni.tsx
  static/app/utils/replays/projectSupportsReplay.spec.tsx
Labels: Scope: Frontend

#62635 ref(platform): add go-negroni as backend platform
  src/sentry/utils/platform_categories.py
Labels: Scope: Backend

#62501 fix(crons): Only resolve issues for OK check-ins
  src/sentry/monitors/logic/mark_ok.py
  tests/sentry/monitors/logic/test_mark_ok.py
Labels: Scope: Backend

#62637 ref(replays): link to full list of FAQs in tooltip
  static/app/views/replays/list/replayOnboardingPanel.tsx
Labels: Scope: Frontend

#62638 ref(replays): make faq accordion collapsible
  static/app/views/replays/list/replayOnboardingPanel.tsx
  static/app/views/replays/list/replayPanel.tsx
Labels: Scope: Frontend

#62642 ref(crons): Pass Promise return down for timelineTableRow actions
  static/app/views/monitors/components/overviewTimeline/timelineTableRow.tsx
  static/app/views/monitors/components/statusToggleButton.tsx
Labels: Scope: Frontend

#62600 feat(replays): Replace datadog metrics with Sentry performance spans
  src/sentry/replays/consumers/recording_buffered.py
Labels: Scope: Backend

#62648 fix(issue-stream): Fix typo in no issues matched page
  static/app/views/issueList/noGroupsHandler/noIssuesMatched.tsx
Labels: Scope: Frontend

#62593 feat(relocation): Add endpoint to retry failed relocation
  src/sentry/api/endpoints/relocations/index.py
  src/sentry/api/endpoints/relocations/retry.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/relocations/test_retry.py
Labels: Scope: Backend

#62652 feat(indexer): Add option for raising Validation Errors
  src/sentry/options/defaults.py
Labels: Scope: Backend

#62655 feat(issues): Add integration details to resolve/unresolve
  static/app/types/group.tsx
  static/app/views/issueDetails/groupActivity.spec.tsx
  static/app/views/issueDetails/groupActivityItem.tsx
Labels: Scope: Frontend

#62656 fix(relocation): Retry endpoint file filtering
  src/sentry/api/endpoints/relocations/retry.py
  tests/sentry/api/endpoints/relocations/test_retry.py
Labels: Scope: Backend

#62658 ref(crons): Improve error messages for monitor updates
  static/app/actionCreators/monitors.tsx
Labels: Scope: Frontend

#62661 ref(crons): Change disabled cron creation alert/tooltip text
  static/app/views/monitors/overview.tsx
Labels: Scope: Frontend

#62659 ref(crons): Adjust wording of StatusToggleButton in the details alert
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#62663 ref: Rename constant
  src/sentry/auth/staff.py
  tests/sentry/auth/test_staff.py
Labels: Scope: Backend

#62662 chore(relocation): Disable org context for relocation page
  static/app/routes.tsx
Labels: Scope: Frontend

#62665 fix(backup): Stop filtering on inviter_id
  src/sentry/models/organizationmember.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#62671 fix(ddm-onboarding): Python snippet formatted as js
  static/app/components/onboarding/gettingStartedDoc/utils/metricsOnboarding.tsx
Labels: Scope: Frontend

#62677 chore(stats-detector): Tune stats detector escalation
  src/sentry/statistical_detectors/algorithm.py
  src/sentry/tasks/statistical_detectors.py
Labels: Scope: Backend

#62634 fix(alert-rule): Allow word break to show 256 char name with no breaks
  static/app/components/confirm.tsx
Labels: Scope: Frontend

#62293 feat(useroption): Allow new experience toggle state to be stored as a UserOption
  src/sentry/api/endpoints/user_details.py
  src/sentry/api/serializers/models/user.py
  src/sentry/models/options/user_option.py
  tests/sentry/api/endpoints/test_user_details.py
Labels: Scope: Backend

#62682 ref: vendor django's removed memcached backend
  fixtures/stubs-for-mypy/memcache.pyi
  src/sentry/utils/memcached.py
Labels: Scope: Backend

#62646 metrics(replays): Add canvas event size logging
  src/sentry/replays/usecases/ingest/__init__.py
  src/sentry/replays/usecases/ingest/dom_index.py
  tests/sentry/replays/unit/test_ingest_dom_index.py
Labels: Scope: Backend

#62615 feat(replays): Optimize /replay-counts query by passing a narrowed set of project_ids
  src/sentry/replays/usecases/replay_counts.py
  tests/sentry/replays/test_organization_replay_count.py
Labels: Scope: Backend

#62683 ref: remove redundant classes in except clause
  src/sentry/issues/run.py
Labels: Scope: Backend

#62687 chore(stats-detectors): Bump min data points to 18
  src/sentry/tasks/statistical_detectors.py
  tests/sentry/tasks/test_statistical_detectors.py
Labels: Scope: Backend

#62668 feat(replays): Run replays deletion task on shared queue
  src/sentry/replays/tasks.py
Labels: Scope: Backend

#62562 Abdk/perf trace details nav
  static/app/components/events/interfaces/spans/newTraceDetailsSpanBar.tsx
  static/app/components/events/interfaces/spans/newTraceDetailsSpanDetails.tsx
  static/app/components/events/interfaces/spans/newTraceDetailsSpanTree.tsx
  static/app/components/events/interfaces/spans/spanDescendantGroupBar.tsx
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/events/interfaces/spans/spanGroupBar.tsx
  static/app/components/events/interfaces/spans/spanSiblingGroupBar.tsx
  static/app/components/events/interfaces/spans/spanTreeModel.tsx
  static/app/components/events/interfaces/spans/utils.tsx
  static/app/components/events/interfaces/spans/waterfallModel.tsx
  static/app/components/profiling/transactionToProfileButton.tsx
  static/app/views/discover/eventDetails/content.tsx
  static/app/views/performance/traceDetails/TraceDetailsRouting.tsx
  static/app/views/performance/traceDetails/newTraceDetailsContent.tsx
  static/app/views/performance/traceDetails/newTraceDetailsTraceView.tsx
  static/app/views/performance/traceDetails/newTraceDetailsTransactionBar.tsx
  static/app/views/performance/traceDetails/traceViewDetailPanel.tsx
  static/app/views/performance/traceDetails/transactionGroup.tsx
  static/app/views/performance/traceDetails/utils.tsx
  static/app/views/performance/transactionDetails/content.tsx
Labels: Scope: Frontend

#62688 ref(replay onboarding): move trace prop message & remove intro text
  static/app/components/replaysOnboarding/replayOnboardingLayout.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/components/replaysOnboarding/utils.tsx
  static/app/gettingStartedDocs/capacitor/capacitor.tsx
  static/app/gettingStartedDocs/electron/electron.tsx
  static/app/gettingStartedDocs/javascript/angular.tsx
  static/app/gettingStartedDocs/javascript/astro.tsx
  static/app/gettingStartedDocs/javascript/ember.tsx
  static/app/gettingStartedDocs/javascript/gatsby.tsx
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/jsLoader/jsLoader.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/react.tsx
  static/app/gettingStartedDocs/javascript/remix.tsx
  static/app/gettingStartedDocs/javascript/svelte.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.tsx
  static/app/gettingStartedDocs/javascript/vue.tsx
Labels: Scope: Frontend

#62686 ref(severity): Change threshold calculation to use 95th percentile
  src/sentry/issues/issue_velocity.py
  tests/sentry/issues/test_issue_velocity.py
Labels: Scope: Backend

#62649 fix(integrations): Prevent warning for new integrations
  static/app/views/settings/organizationDeveloperSettings/permissionsObserver.spec.tsx
  static/app/views/settings/organizationDeveloperSettings/permissionsObserver.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.tsx
Labels: Scope: Frontend

#62692 introduce crash free sessions to release threhsolds
  static/app/views/releases/thresholdsList/thresholdGroupRows.tsx
  static/app/views/releases/utils/constants.ts
Labels: Scope: Frontend

#62347 fix(csv-export): Handle the need for escape characters
  src/sentry/data_export/tasks.py
  tests/sentry/data_export/test_tasks.py
Labels: Scope: Backend

#62693 fix(severity): Include GT and LT in severity filter match types
  src/sentry/rules/filters/issue_severity.py
  tests/sentry/rules/filters/test_issue_severity.py
Labels: Scope: Backend
