Repository getsentry/sentry, pull requests merged in 2024-12, with the labels that each got.

#81464 feat(nuxt): Use Sentry wizard in nuxt onboarding
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/javascript/nuxt.spec.tsx
  static/app/gettingStartedDocs/javascript/nuxt.tsx
  static/app/locale.tsx
Labels: Scope: Frontend

#81457 feat(symbolication): Pass event & frame platforms
  src/sentry/lang/java/processing.py
  src/sentry/lang/javascript/processing.py
  src/sentry/lang/native/processing.py
  src/sentry/lang/native/symbolicator.py
  src/sentry/profiles/task.py
Labels: Scope: Backend

#80172 ref(quick-start): Prevent 'complete' tasks from being displayed outside of the completed tasks list
  static/app/components/onboardingWizard/newSidebar.tsx
  static/app/components/sidebar/newOnboardingStatus.tsx
Labels: Scope: Frontend

#81423 ref(releases): Create two new functions
  src/sentry/api/helpers/group_index/update.py
Labels: Component: Releases, Scope: Backend, Product Area: Releases

#81475 feat(widget-builder): Add filter to hook
  static/app/views/dashboards/widgetBuilder/components/devBuilder.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useQueryParamState.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.tsx
Labels: Scope: Frontend

#81478 feat(widget-builder): Add helper to convert widget to builder state
  static/app/views/dashboards/dashboard.tsx
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetBuilder/components/devBuilder.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetBuilderSlideout.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.tsx
  static/app/views/dashboards/widgetBuilder/utils/convertWidgetToBuilderStateParams.ts
Labels: Scope: Frontend

#81362 feat(dashboard): add favourite field to dashboard model
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/backup/comparators.py
  src/sentry/migrations/0798_add_favorite_dashboard_col.py
  src/sentry/models/dashboard.py
  src/sentry/organizations/services/organization/impl.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
  tests/sentry/users/models/test_user.py
Labels: Scope: Frontend, Scope: Backend

#81477 chore(api): Add few more referrers to organization-events
  src/sentry/api/endpoints/organization_events.py
  src/sentry/snuba/referrer.py
Labels: Scope: Backend

#81498 ref(tests): Improve a bit the tests for releases
  tests/sentry/issues/endpoints/test_group_details.py
Labels: Component: Releases, Product Area: Releases

#81514 fix(insights): Link "Highest Cache Miss Rate" widget to module correctly
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
Labels: Scope: Frontend

#81497 feat(widget-builder): Add title and description fields
  static/app/views/dashboards/widgetBuilder/components/nameAndDescFields.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetBuilderSlideout.tsx
Labels: Scope: Frontend

#81432 feat(new-trace): Redesigning no instrumentation drawer content.
  static/app/views/performance/newTraceDetails/traceDrawer/details/missingInstrumentation.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/profiling/profilePreview.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
Labels: Scope: Frontend

#81516 fix(rollback): Hide banner when sidebar is horizontal
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/sidebarDropdown/index.tsx
Labels: Scope: Frontend

#81446 fix(taskworker) Fix not_found errors being handled
  src/sentry/runner/commands/run.py
  src/sentry/taskworker/client.py
  tests/sentry/taskworker/test_client.py
Labels: Scope: Backend

#81373 feat(autofix): Add feedback & root cause selection events + tests
  static/app/components/events/autofix/autofixMessageBox.analytics.spec.tsx
  static/app/components/events/autofix/autofixMessageBox.tsx
Labels: Scope: Frontend

#81411 fix(autofix): Fix write setup modal closing the drawer
  static/app/components/events/autofix/autofixSetupWriteAccessModal.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsSection.tsx
Labels: Scope: Frontend

#81366 feat(new-trace): Redesigning span details content.
  static/app/components/events/interfaces/spans/spanProfileDetails.tsx
  static/app/components/events/interfaces/spans/types.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/autogroup/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/autogroup/parentAutogroup.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/autogroup/siblingAutogroup.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/error.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/missingInstrumentation.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/profiling/profilePreview.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/components/spanSummaryLink.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/ancestry.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/description.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/generalInfo.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/sections/highlights.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/traceTreeNodeDetails.tsx
Labels: Scope: Frontend

#81267 chore(sentryapp): add regional RPC service to get request buffers by region
  src/sentry/sentry_apps/models/sentry_app.py
  src/sentry/sentry_apps/services/app_request/__init__.py
  src/sentry/sentry_apps/services/app_request/impl.py
  src/sentry/sentry_apps/services/app_request/model.py
  src/sentry/sentry_apps/services/app_request/serial.py
  src/sentry/sentry_apps/services/app_request/service.py
  src/sentry/types/region.py
  tests/sentry/sentry_apps/models/test_sentryapp.py
  tests/sentry/sentry_apps/services/test_app_request.py
  tests/sentry/types/test_region.py
Labels: Scope: Backend

#81386 chore(alerts): Remove incident activity comments
  src/sentry/incidents/endpoints/organization_incident_details.py
  src/sentry/incidents/events.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/tasks.py
  src/sentry/testutils/fixtures.py
  src/sentry/web/debug_urls.py
  src/sentry/web/frontend/debug/debug_incident_activity_email.py
  tests/sentry/api/serializers/test_incident_activity.py
  tests/sentry/incidents/endpoints/serializers/test_incident.py
  tests/sentry/incidents/endpoints/test_organization_incident_details.py
  tests/sentry/incidents/test_logic.py
  tests/sentry/incidents/test_tasks.py
Labels: Scope: Backend

#81474 fix(flamegraph): Restrict number of profile candidates more strictly
  src/sentry/profiles/flamegraph.py
Labels: Scope: Backend

#81469 fix(explore): Order of options in aggregate mode
  static/app/views/explore/tables/aggregatesTable.tsx
Labels: Scope: Frontend

#81519 feat(widget-builder): Add context for synchronized state
  static/app/views/dashboards/widgetBuilder/components/devBuilder.tsx
  static/app/views/dashboards/widgetBuilder/components/nameAndDescFields.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.tsx
  static/app/views/dashboards/widgetBuilder/contexts/widgetBuilderContext.tsx
Labels: Scope: Frontend

#81372 feat(rpc): Support projects in top events
  src/sentry/api/endpoints/organization_events_stats.py
  src/sentry/search/eap/spans.py
  src/sentry/snuba/spans_rpc.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#81369 chore(insights): Remove insights alerts progress
  static/app/views/alerts/rules/metric/utils/getMetricDatasetQueryExtras.tsx
  static/app/views/alerts/rules/metric/wizardField.tsx
  static/app/views/alerts/wizard/options.tsx
  static/app/views/insights/common/components/chartPanel.spec.tsx
  static/app/views/insights/common/components/chartPanel.tsx
  static/app/views/insights/common/utils/hasInsightsAlerts.tsx
Labels: Scope: Frontend

#81410 fix(oauth): Limit org index response to token's org
  src/sentry/api/endpoints/organization_index.py
  tests/sentry/api/endpoints/test_organization_index.py
Labels: Scope: Backend

#81472 fix(alerts): EAP alerts default to minimum 24h timerange when coming from 1h timerange in explore
  static/app/views/insights/common/utils/getAlertsUrl.tsx
Labels: Scope: Frontend

#81468 fix(alerts): Format EAP alert chart y axis label
  static/app/views/alerts/rules/metric/ruleForm.tsx
Labels: Scope: Frontend

#81442 fix(alerts): Fix EAP alert field select label too verbose
  static/app/views/alerts/rules/metric/eapField.tsx
Labels: Scope: Frontend

#81371 ref(flags): add more python platforms to onboarding
  static/app/data/platformCategories.tsx
  static/app/gettingStartedDocs/python/aiohttp.tsx
  static/app/gettingStartedDocs/python/bottle.tsx
  static/app/gettingStartedDocs/python/django.tsx
  static/app/gettingStartedDocs/python/falcon.tsx
  static/app/gettingStartedDocs/python/fastapi.tsx
  static/app/gettingStartedDocs/python/flask.tsx
  static/app/gettingStartedDocs/python/pyramid.tsx
  static/app/gettingStartedDocs/python/python.tsx
  static/app/gettingStartedDocs/python/quart.tsx
  static/app/gettingStartedDocs/python/sanic.tsx
  static/app/gettingStartedDocs/python/starlette.tsx
  static/app/gettingStartedDocs/python/tornado.tsx
Labels: Scope: Frontend

#81521 fix(eap): Make p100 alias to max
  src/sentry/search/events/datasets/spans_indexed.py
Labels: Scope: Backend

#81274 devenv: upgrade to 1.14.2
  devenv/config.ini
  devenv/sync.py
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#81447 feat(eap): Add columns for some known http attributes
  src/sentry/search/eap/columns.py
  src/sentry/search/events/builder/base.py
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/utils/snuba.py
  tests/sentry/api/endpoints/test_organization_spans_fields.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#81523 chore(flags): add cta flag to temporary.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#81524 chore(alerts): Remove seen_by from expand
  static/app/views/alerts/utils/apiCalls.tsx
Labels: Scope: Frontend

#80645 feat(flags): add inline cta and update js onboarding platforms allowed
  static/app/components/events/featureFlags/eventFeatureFlagList.spec.tsx
  static/app/components/events/featureFlags/eventFeatureFlagList.tsx
  static/app/components/events/featureFlags/featureFlagInlineCTA.spec.tsx
  static/app/components/events/featureFlags/featureFlagInlineCTA.tsx
  static/app/components/events/featureFlags/featureFlagOnboardingSidebar.tsx
  static/app/components/events/featureFlags/testUtils.tsx
  static/app/data/platformCategories.tsx
  static/app/gettingStartedDocs/javascript/angular.tsx
  static/app/gettingStartedDocs/javascript/astro.tsx
  static/app/gettingStartedDocs/javascript/ember.tsx
  static/app/gettingStartedDocs/javascript/gatsby.tsx
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/nuxt.tsx
  static/app/gettingStartedDocs/javascript/react.tsx
  static/app/gettingStartedDocs/javascript/remix.tsx
  static/app/gettingStartedDocs/javascript/solid.tsx
  static/app/gettingStartedDocs/javascript/solidstart.tsx
  static/app/gettingStartedDocs/javascript/svelte.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.tsx
  static/app/gettingStartedDocs/javascript/vue.tsx
  static/app/utils/analytics/featureFlagAnalyticsEvents.tsx
Labels: Scope: Frontend

#81527 feat(widget-builder): Add dataset selector
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetBuilder/components/datasetSelector.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetBuilderSlideout.tsx
Labels: Scope: Frontend

#81528 fix(flags): fix flag series suffix
  static/app/views/issueDetails/streamline/hooks/useFlagSeries.tsx
Labels: Scope: Frontend

#81535 ref(flags): remove frontend feature flag
  static/app/components/events/featureFlags/eventFeatureFlagList.spec.tsx
  static/app/components/events/featureFlags/featureFlagDrawer.spec.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.spec.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.spec.tsx
  static/app/views/issueDetails/streamline/eventGraph.spec.tsx
  static/app/views/issueDetails/streamline/eventGraph.tsx
  static/app/views/issueDetails/streamline/groupDetailsLayout.spec.tsx
  static/app/views/issueDetails/streamline/hooks/useFlagSeries.tsx
  static/app/views/issueDetails/streamline/hooks/useOrganizationFlagLog.tsx
  static/app/views/issueDetails/streamline/hooks/useSuspectFlags.tsx
Labels: Scope: Frontend

#81540 feat(issues): Add ownership button to assignee dropdwn
  static/app/components/assigneeSelectorDropdown.tsx
  static/app/components/group/assigneeSelector.tsx
  static/app/views/issueDetails/streamline/header/assigneeSelector.spec.tsx
  static/app/views/issueDetails/streamline/header/assigneeSelector.tsx
Labels: Scope: Frontend

#81548 fix(rollback): Use default org permissions on endpoint
  src/sentry/api/endpoints/organization_user_rollback.py
Labels: Scope: Backend

#81551 fix(flags): fix python import in onboarding
  static/app/gettingStartedDocs/python/python.tsx
Labels: Scope: Frontend

#81542 fix(autofix): Align AutofixStatus enum
  src/sentry/autofix/utils.py
Labels: Scope: Backend

#81550 fix(autofix): Invalidate autofix query on a rethink and on feedback
  static/app/components/events/autofix/autofixDiff.tsx
  static/app/components/events/autofix/autofixInsightCards.tsx
  static/app/components/events/autofix/autofixMessageBox.tsx
Labels: Scope: Frontend

#81481 ref(profiling): remove unused option for profile outcomes
  src/sentry/options/defaults.py
  src/sentry/profiles/task.py
Labels: Scope: Backend

#81415 Update action requirement
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
Labels: Scope: Backend

#81416 Update action requirement
  src/sentry/incidents/endpoints/organization_alert_rule_details.py
Labels: Scope: Backend

#81491 fix(dynamic-sampling): round dynamic sampling rates
  src/sentry/api/endpoints/organization_sampling_project_rates.py
  tests/sentry/api/endpoints/test_organization_sampling_project_rates.py
Labels: Scope: Backend

#81569 feat(onboarding): adapt AIOHTTP onboarding to install-configure-verify structure
  static/app/gettingStartedDocs/python/aiohttp.tsx
Labels: Scope: Frontend

#81520 feat(grouping): Blacklist a list of platforms instead of whitelisting it
  src/sentry/seer/similarity/utils.py
  tests/sentry/seer/similarity/test_utils.py
Labels: Scope: Backend

#81526 feat(eap): Derive aggregation type from args
  src/sentry/search/eap/columns.py
  src/sentry/search/eap/constants.py
  src/sentry/search/eap/spans.py
  src/sentry/search/events/builder/base.py
  src/sentry/snuba/spans_rpc.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#81428 chore(insights): Remove unused insights alerts logic and components
  static/app/components/metrics/metricSearchBar.spec.tsx
  static/app/components/metrics/metricSearchBar.tsx
  static/app/utils/metrics/features.tsx
  static/app/utils/metrics/mri.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
  static/app/views/alerts/rules/metric/details/metricChart.tsx
  static/app/views/alerts/rules/metric/insightsMetricField.spec.tsx
  static/app/views/alerts/rules/metric/insightsMetricField.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/alerts/rules/metric/ruleForm.spec.tsx
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/thresholdTypeForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.spec.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
  static/app/views/alerts/rules/metric/utils/isInsightsMetricAlert.tsx
  static/app/views/alerts/rules/metric/utils/onDemandMetricAlert.spec.tsx
  static/app/views/alerts/rules/metric/utils/onDemandMetricAlert.tsx
  static/app/views/alerts/rules/metric/wizardField.tsx
  static/app/views/alerts/wizard/options.tsx
  static/app/views/alerts/wizard/panelContent.tsx
  static/app/views/alerts/wizard/utils.spec.tsx
  static/app/views/alerts/wizard/utils.tsx
Labels: Scope: Frontend

#81574 fix(dynamic-sampling): round dynamic sampling rates when switching from org to project mode
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/project_details.py
Labels: Scope: Backend

#81573 chore: Upgrade sentry-kafka-schemas
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#81534 feat(dashboards): add new filters to dashboard list endpoint
  src/sentry/api/endpoints/organization_dashboards.py
  tests/sentry/api/endpoints/test_organization_dashboards.py
Labels: Scope: Backend

#81465 ref(insights): group all module routes under one constant
  static/app/routes.tsx
Labels: Scope: Frontend

#81583 chore(profiling): Remove unused chunks flamegraph endpoint
  src/sentry/api/endpoints/organization_profiling_profiles.py
  src/sentry/api/urls.py
  src/sentry/profiles/flamegraph.py
  tests/sentry/profiling/test_flamegraph.py
Labels: Scope: Backend

#81585 fix(insights): Styling of Web Vitals cards
  static/app/views/insights/browser/webVitals/components/webVitalMeters.tsx
  static/app/views/insights/browser/webVitals/utils/performanceScoreColors.tsx
Labels: Scope: Frontend

#81529 chore(github): webhook metrics
  src/sentry/integrations/github/webhook.py
  src/sentry/integrations/utils/metrics.py
  tests/sentry/integrations/github/test_webhooks.py
  tests/sentry/integrations/utils/test_assert_metrics.py
Labels: Scope: Backend

#81584 fix(issue-details): Add viewer/particpant last seen back
  static/app/views/issueDetails/streamline/sidebar/participantList.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/participantList.tsx
  static/app/views/issueDetails/streamline/sidebar/peopleSection.tsx
Labels: Scope: Frontend

#81590 fix(issue-details): Ensure trace link appears for performance issues
  static/app/components/events/interfaces/performance/eventTraceView.spec.tsx
  static/app/components/events/interfaces/performance/eventTraceView.tsx
Labels: Scope: Frontend

#81577 ref: Improve symbolication platform logic
  src/sentry/lang/java/processing.py
  src/sentry/lang/java/utils.py
  src/sentry/lang/javascript/processing.py
  src/sentry/lang/javascript/utils.py
  src/sentry/tasks/symbolication.py
  tests/relay_integration/lang/java/test_plugin.py
Labels: Scope: Backend

#81549 :wrench: chore(slo): Add slos for "View Submission" for Slack
  src/sentry/integrations/messaging/metrics.py
  src/sentry/integrations/slack/webhooks/action.py
  tests/sentry/integrations/slack/webhooks/actions/test_status.py
Labels: Scope: Backend

#80129 feat(billing): Invite billing members to a developer plan
  src/sentry/api/endpoints/organization_member/index.py
  src/sentry/features/temporary.py
  static/app/components/modals/inviteMembersModal/index.tsx
  static/app/components/modals/inviteMembersModal/inviteMembersModalview.spec.tsx
  static/app/components/modals/inviteMembersModal/inviteMembersModalview.tsx
  static/app/components/modals/inviteMembersModal/inviteRowControl.tsx
  static/app/components/modals/memberInviteModalCustomization.tsx
  static/app/types/hooks.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.tsx
  tests/sentry/api/endpoints/test_organization_member_index.py
Labels: Scope: Frontend, Scope: Backend

#79753 ref: remove non-functional github enterprise identity provider
  pyproject.toml
  src/sentry/identity/github_enterprise/provider.py
  src/sentry/integrations/github_enterprise/integration.py
Labels: Scope: Backend

#81582 ci(coverage) only run coverage on master
  .github/workflows/frontend.yml
  codecov.yml
  package.json
Labels: Scope: Frontend

#81480 chore(sentry apps): Add backwards compatbility for SentryAppCompenent errors
  static/app/components/feedback/list/useHasLinkedIssues.tsx
  static/app/components/group/externalIssuesList/useExternalIssueData.tsx
  static/app/components/sentryAppComponentIcon.spec.tsx
  static/app/components/sentryAppComponentIcon.tsx
  static/app/types/integrations.tsx
Labels: Scope: Frontend

#81593 feat(widget-builder): Add query in state -> widget conversion
  static/app/views/dashboards/widgetBuilder/components/devBuilder.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetPreview.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.tsx
  static/app/views/dashboards/widgetBuilder/utils/convertWidgetToBuilderStateParams.ts
Labels: Scope: Frontend

#81289 fix(transactions): fix for ingesting transactions with attachments
  src/sentry/ingest/consumer/processors.py
Labels: Scope: Backend

#81530 fix(taskworker) Disallow at_most_once + retry
  src/sentry/taskworker/registry.py
  src/sentry/taskworker/task.py
  tests/sentry/taskworker/test_task.py
Labels: Scope: Backend

#81522 chore(alerts): Rm incidentseen and incidentsubscription
  src/sentry/api/serializers/models/__init__.py
  src/sentry/api/serializers/models/incidentseen.py
  src/sentry/incidents/endpoints/serializers/incident.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/models/incident.py
  src/sentry/organizations/services/organization/impl.py
  src/sentry/testutils/factories.py
  tests/sentry/incidents/endpoints/test_organization_incident_details.py
  tests/sentry/users/models/test_user.py
Labels: Scope: Backend

#81539 chore(grouping): Add `unsafe-eval` and `unsafe-inline` grouping test inputs
  tests/sentry/grouping/grouping_inputs/csp-script-src-unsafe-eval.json
  tests/sentry/grouping/grouping_inputs/csp-script-src-unsafe-inline.json
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/csp_script_src_unsafe_inline.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/csp_script_src_unsafe_eval.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/csp_script_src_unsafe_inline.pysnap
Labels: Scope: Backend

#81597 chore(autofix): Pre expand relevant code context
  static/app/components/events/autofix/autofixInsightCards.tsx
  static/app/components/events/autofix/autofixRootCause.spec.tsx
  static/app/components/events/autofix/autofixRootCause.tsx
Labels: Scope: Frontend

#81600 chore(vsts): webhook metrics
  src/sentry/integrations/utils/metrics.py
  src/sentry/integrations/vsts/webhooks.py
  tests/sentry/integrations/utils/test_assert_metrics.py
  tests/sentry/integrations/vsts/test_webhooks.py
Labels: Scope: Backend

#80951 chore(grouping): Add fingerprinting-related types
  src/sentry/grouping/api.py
  src/sentry/grouping/fingerprinting/__init__.py
  src/sentry/grouping/variants.py
  tests/sentry/grouping/test_variants.py
Labels: Scope: Backend

#81601 fix(flags): fix flag context type
  static/app/components/events/featureFlags/eventFeatureFlagList.tsx
  static/app/components/events/featureFlags/testUtils.tsx
  static/app/types/event.tsx
  static/app/utils/featureObserver.ts
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
  static/app/views/issueDetails/streamline/hooks/useFlagSeries.tsx
  static/app/views/issueDetails/streamline/hooks/useSuspectFlags.tsx
Labels: Scope: Frontend

#81466 feat(explore): Do not reload existing charts
  static/app/views/explore/charts/index.tsx
Labels: Scope: Frontend

#81592 chore(statistical-detectors): Do not make vroom request when not nece…
  src/sentry/tasks/statistical_detectors.py
Labels: Scope: Backend

#81546 feat(flags): Add list and delete endpoints to signing-secrets resource
  src/sentry/api/urls.py
  src/sentry/flags/docs/api.md
  src/sentry/flags/endpoints/secrets.py
  tests/sentry/flags/endpoints/test_secrets.py
Labels: Scope: Frontend, Scope: Backend

#81438 feat(dashboards): add new endpoint for favourite dashboards
  src/sentry/api/endpoints/organization_dashboard_details.py
  src/sentry/api/serializers/models/dashboard.py
  src/sentry/api/urls.py
  src/sentry/apidocs/examples/dashboard_examples.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
Labels: Scope: Backend

#81604 feat(widget-builder): Add sort field to hook
  static/app/views/dashboards/widgetBuilder/components/devBuilder.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useQueryParamState.spec.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useQueryParamState.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.spec.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.tsx
  static/app/views/dashboards/widgetBuilder/utils/convertBuilderStateToWidget.spec.tsx
  static/app/views/dashboards/widgetBuilder/utils/convertBuilderStateToWidget.ts
  static/app/views/dashboards/widgetBuilder/utils/convertWidgetToBuilderStateParams.ts
Labels: Scope: Frontend

#80959 fix(grouping): `BaseGroupingCompoent` types cleanup
  src/sentry/grouping/api.py
  src/sentry/grouping/component.py
  src/sentry/grouping/variants.py
  tests/sentry/grouping/test_grouphash_metadata.py
Labels: Scope: Backend

#81554 chore(flagpole): Adds a test flag to validate region checks in flagpole
  src/sentry/features/temporary.py
Labels: Scope: Backend

#81382 feat(oauth): Adding org to ApiAuthorizationSerializer
  src/sentry/api/serializers/models/apiauthorization.py
  tests/sentry/api/endpoints/test_api_authorizations.py
Labels: Scope: Backend

#81390 fix(similarity): Add catch for no module and filename in the ui
  src/sentry/issues/endpoints/group_similar_issues_embeddings.py
  src/sentry/seer/similarity/utils.py
  tests/sentry/issues/endpoints/test_group_similar_issues_embeddings.py
Labels: Scope: Backend

#81614 feat(rpc): Add confidence to the events stats response
  src/sentry/api/serializers/snuba.py
  src/sentry/snuba/spans_rpc.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#81494 fix(dashboards): modify team rendering in edit access selector
  static/app/views/dashboards/editAccessSelector.tsx
Labels: Scope: Frontend

#81605 chore(alerts): Remove incidentseen and incidentsubscription models
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/incidents/models/incident.py
  src/sentry/migrations/0800_rm_incidentseen_incidentsubscription.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Frontend, Scope: Backend

#81223 feat(event tracker) add logging everywhere in transaction ingestion
  src/sentry/event_manager.py
  src/sentry/tasks/post_process.py
  src/sentry/tasks/store.py
  src/sentry/utils/event_tracker.py
Labels: Scope: Backend

#81336 [Opsgenie integration] Hit close api instead acknowledge api when resolved
  src/sentry/integrations/opsgenie/client.py
  tests/sentry/incidents/action_handlers/test_opsgenie.py
Labels: Scope: Backend, Trigger: getsentry tests

#81445 ref(profiling) implement edge detection on profiling tooltip
  static/app/components/profiling/boundTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphChartTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphSpanTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphTooltip.tsx
  static/app/components/profiling/flamegraph/flamegraphUIFramesTooltip.tsx
  static/app/utils/profiling/gl/utils.ts
  static/app/views/performance/transactionSummary/transactionProfiles/content.tsx
  static/app/views/profiling/profileSummary/index.tsx
Labels: Scope: Frontend

#81630 fix(flags): Use org event permission for secrets resource
  src/sentry/flags/endpoints/secrets.py
Labels: Scope: Backend

#81383 feat(oauth): Display org name for org scoped authorizations
  static/app/views/settings/account/accountAuthorizations.tsx
Labels: Scope: Frontend

#81628 feat(autofix): Add line numbers to github links
  static/app/components/events/autofix/autofixRootCause.tsx
  static/app/components/events/autofix/types.ts
Labels: Scope: Frontend

#81643 Reapply Revert "ref: upgrade pytest (#81135)"
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#80960 ref(grouping): Make `BaseGroupingComponent` and `BaseVariant` abstract
  src/sentry/grouping/component.py
  src/sentry/grouping/variants.py
Labels: Scope: Backend

#81326 feat(workflow_engine): Process Workflows
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  src/sentry/workflow_engine/apps.py
  src/sentry/workflow_engine/condition_handlers/__init__.py
  src/sentry/workflow_engine/condition_handlers/group_event.py
  src/sentry/workflow_engine/models/data_condition.py
  src/sentry/workflow_engine/models/workflow.py
  src/sentry/workflow_engine/processors/data_condition_group.py
  src/sentry/workflow_engine/processors/workflow.py
  src/sentry/workflow_engine/registry.py
  src/sentry/workflow_engine/types.py
  tests/sentry/workflow_engine/models/test_data_condition.py
  tests/sentry/workflow_engine/models/test_workflow.py
  tests/sentry/workflow_engine/processors/test_data_condition_group.py
  tests/sentry/workflow_engine/processors/test_workflow.py
  tests/sentry/workflow_engine/test_base.py
Labels: Scope: Backend

#81490 fix(quick-start): Pass user to feature flag check
  src/sentry/api/endpoints/organization_onboarding_tasks.py
  src/sentry/onboarding_tasks/backends/organization_onboarding_task.py
  src/sentry/onboarding_tasks/base.py
  src/sentry/receivers/onboarding.py
Labels: Scope: Backend

#81572 fix(quick-start): Update release receiver logic to include releases from transactions
  src/sentry/receivers/onboarding.py
  tests/sentry/receivers/test_onboarding.py
Labels: Scope: Backend

#81653 fix(quick-start): Do not display waiting event in 'adding second platform' task
  static/app/components/onboardingWizard/taskConfig.tsx
Labels: Scope: Frontend

#81652 fix(quick-start): Pass actor to 'quick-start-updates' feature flag
  src/sentry/receivers/onboarding.py
Labels: Scope: Backend

#80728 chore(releases): Remove feature flag
  src/sentry/api/helpers/group_index/update.py
  src/sentry/features/temporary.py
  tests/sentry/issues/endpoints/test_group_details.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Component: Releases, Scope: Backend

#81656 fix: add os.distribution_X FieldKey values to autofill search
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#81619 fix(widget-builder): Pass along proper fields depending on display
  static/app/views/dashboards/datasetConfig/utils/getSeriesRequestData.spec.tsx
  static/app/views/dashboards/datasetConfig/utils/getSeriesRequestData.tsx
  static/app/views/dashboards/widgetBuilder/utils/convertWidgetToBuilderStateParams.ts
Labels: Scope: Frontend

#81591 feat(insights): add http module to mobile domain view
  static/app/views/insights/common/utils/moduleTitles.tsx
  static/app/views/insights/http/settings.ts
  static/app/views/insights/http/views/httpDomainSummaryPage.tsx
  static/app/views/insights/http/views/httpLandingPage.tsx
  static/app/views/insights/pages/mobile/mobilePageHeader.tsx
Labels: Scope: Frontend

#81629 feat(discover): Deprecate discover dataset in saved queries
  src/sentry/api/endpoints/organization_dashboard_widget_details.py
  src/sentry/api/serializers/rest_framework/dashboard.py
  src/sentry/discover/endpoints/discover_saved_queries.py
  src/sentry/discover/endpoints/discover_saved_query_detail.py
  src/sentry/discover/endpoints/serializers.py
  src/sentry/features/temporary.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
  tests/snuba/api/endpoints/test_discover_homepage_query.py
  tests/snuba/api/endpoints/test_discover_saved_query_detail.py
Labels: Scope: Backend

#81589 feat(widget-builder): Add display type dropdown
  static/app/views/dashboards/widgetBuilder/components/datasetSelector.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/typeSelector.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetBuilderSlideout.tsx
Labels: Scope: Frontend

#81651 fix(insights): Fix text overflows within mobile screen rendering tables
  static/app/views/insights/mobile/ui/components/tables/spanOperationTable.tsx
  static/app/views/insights/mobile/ui/components/tables/uiScreensTable.tsx
Labels: Scope: Frontend

#81662 feat(insights): new badge geo region selector
  static/app/views/insights/common/views/spans/selectors/subregionSelector.tsx
Labels: Scope: Frontend

#81612 fix(dashboards): pre-load dashboardperms and dashboardfavorite objects
  src/sentry/api/serializers/models/dashboard.py
Labels: Scope: Backend

#81624 feat(dashboards): add 'return' to endpoint response
  src/sentry/api/endpoints/organization_dashboard_details.py
Labels: Scope: Backend

#81650 :mag: nit: update msteams provider slug enum key to be all caps
  src/sentry/integrations/base.py
Labels: Scope: Backend

#81613 ref: fix types for sentry.notifications.activity.release
  pyproject.toml
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/utils/__init__.py
Labels: Scope: Backend

#80601 fix(insights): Queries module handle no span system
  static/app/views/insights/database/components/databasePageFilters.tsx
  static/app/views/insights/database/components/databaseSystemSelector.tsx
  static/app/views/insights/database/components/tables/queriesTable.tsx
  static/app/views/insights/database/components/useSystemSelectorOptions.tsx
Labels: Scope: Frontend

#81623 chore(alerts): Drop incidentseen and incidentsubscription
  migrations_lockfile.txt
  src/sentry/migrations/0801_drop_incidentseen_incidentsubscription.py
Labels: Scope: Backend

#81633 chore(grouping): Add test input and clean up existing inputs
  tests/sentry/grouping/grouping_inputs/empty.out
  tests/sentry/grouping/grouping_inputs/exception-comput-hashes.json
  tests/sentry/grouping/grouping_inputs/exception-compute-hashes.json
  tests/sentry/grouping/grouping_inputs/exception-groups-two-exceptions-with-frames.json
  tests/sentry/grouping/grouping_inputs/frame-compute-hashes-ignores-ENHANCED-clojure-classes.json
  tests/sentry/grouping/grouping_inputs/javascript_regression_tree_labels.json
  tests/sentry/grouping/grouping_inputs/template-compute-hashes.json
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/legacy@2019_03_12/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/exception_comput_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/exception_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/exception_groups_two_exceptions_with_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_compute_hashes_ignores_ENHANCED_clojure_classes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/javascript_regression_tree_labels.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/template_compute_hashes.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/similarity@2020_07_23/message_with_key_pair_values.pysnap
Labels: Scope: Backend

#81644 fix(grouping): Return 400 when trying to merge across projects
  src/sentry/api/helpers/group_index/update.py
  tests/sentry/api/helpers/test_group_index.py
Labels: Scope: Backend

#81658 feat(flags): Use sentry-sdk to collect flag evaluations
  src/sentry/conf/server.py
  src/sentry/features/manager.py
  src/sentry/middleware/flag.py
  src/sentry/utils/flag.py
  src/sentry/utils/sdk.py
  tests/sentry/utils/test_flag.py
Labels: Scope: Backend

#81596 chore(gitlab): webhook metrics
  src/sentry/integrations/gitlab/webhooks.py
  tests/sentry/integrations/gitlab/test_webhook.py
Labels: Scope: Backend

#81595 chore(bitbucket): bitbucket + bitbucket server webhook metrics
  src/sentry/integrations/bitbucket/webhook.py
  src/sentry/integrations/bitbucket_server/webhook.py
  tests/sentry/integrations/bitbucket/test_webhook.py
  tests/sentry/integrations/bitbucket_server/test_webhook.py
Labels: Scope: Backend

#81657 ref(grouping): Minor refactor for utils
  src/sentry/seer/similarity/utils.py
Labels: Scope: Backend

#81674 chore(explore): margin tweaks
  static/app/views/explore/toolbar/styles.tsx
  static/app/views/explore/toolbar/toolbarGroupBy.tsx
  static/app/views/explore/toolbar/toolbarVisualize.tsx
Labels: Scope: Frontend

#81626 fix(rpc): Disable zerofill for rpc
  src/sentry/api/endpoints/organization_events_stats.py
  src/sentry/snuba/spans_rpc.py
Labels: Scope: Backend

#81649 chore(grouping): Remove grouping auto update option from remaining projects
  migrations_lockfile.txt
  src/sentry/migrations/0802_remove_grouping_auto_update_option.py
Labels: Scope: Backend

#81669 feat(new-trace): Adding span start end timestamps
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/generalInfo.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/keys.tsx
Labels: Scope: Frontend

#81673 ref: avoid clobbering APIView.handle_exception
  pyproject.toml
  src/sentry/api/base.py
  src/sentry/api/bases/project.py
  src/sentry/integrations/api/bases/integration.py
  src/sentry/integrations/api/endpoints/integration_proxy.py
  src/sentry/integrations/jira/webhooks/base.py
  src/sentry/integrations/jira/webhooks/issue_updated.py
  tests/sentry/api/test_base.py
  tests/sentry/integrations/api/bases/test_integration.py
  tests/sentry/integrations/jira/test_webhooks.py
Labels: Scope: Backend

#81672 fix(relocation): Indentation error
  src/sentry/tasks/relocation.py
Labels: Scope: Backend

#81681 chore(seer-severity): Log seer severity errors to sentry
  src/sentry/event_manager.py
Labels: Scope: Backend

#81682 fix(hydration error): Improve hydration error slider diff when resizing the screen
  static/app/components/replays/diff/replaySliderDiff.tsx
Labels: Scope: Frontend

#81683 fix(auth): typo
  static/app/views/settings/account/accountAuthorizations.tsx
Labels: Scope: Frontend

#81536 chore(flags): rm backend feature flag
  src/sentry/flags/endpoints/logs.py
  tests/sentry/flags/endpoints/test_logs.py
Labels: Scope: Backend

#81631 feat(flags): add settings page for webhook secrets
  static/app/components/events/featureFlags/onboardingIntegrationSection.tsx
  static/app/routes.tsx
  static/app/views/settings/featureFlags/index.spec.tsx
  static/app/views/settings/featureFlags/index.tsx
  static/app/views/settings/featureFlags/newProviderForm.spec.tsx
  static/app/views/settings/featureFlags/newProviderForm.tsx
  static/app/views/settings/featureFlags/newSecretHandler.spec.tsx
  static/app/views/settings/featureFlags/newSecretHandler.tsx
  static/app/views/settings/featureFlags/organizationFeatureFlagsNewSecret.spec.tsx
  static/app/views/settings/featureFlags/organizationFeatureFlagsNewSecret.tsx
  static/app/views/settings/featureFlags/organizationFeatureFlagsProviderRow.spec.tsx
  static/app/views/settings/featureFlags/organizationFeatureFlagsProviderRow.tsx
  static/app/views/settings/featureFlags/useUserFromId.tsx
  static/app/views/settings/organization/navigationConfiguration.tsx
  static/app/views/settings/organizationAuthTokens/index.tsx
  tests/js/fixtures/secret.ts
Labels: Scope: Frontend

#81675 feat(dashboards): `WidgetSyncContext`
  static/app/views/dashboards/contexts/widgetSyncContext.stories.tsx
  static/app/views/dashboards/contexts/widgetSyncContext.tsx
  static/app/views/dashboards/widgets/lineChartWidget/lineChartWidgetVisualization.tsx
Labels: Scope: Frontend

#81688 feat(workflow_engine): add `workflow-engine-ui` feature flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#81270 chore: Bump `sentry-arroyo` to 2.18.2
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/consumers/synchronized.py
  src/sentry/spans/consumers/process/factory.py
Labels: Scope: Backend

#81690 chore(issue-details): Add analytics for non-streamline comments
  static/app/utils/analytics/issueAnalyticsEvents.tsx
  static/app/views/issueDetails/activitySection.tsx
  static/app/views/issueDetails/streamline/sidebar/activitySection.tsx
Labels: Scope: Frontend

#81686 ref(insights): Remove references to `alertConfigs` prop
  static/app/views/insights/browser/resources/alerts.ts
  static/app/views/insights/browser/resources/components/charts/resourceSummaryCharts.tsx
  static/app/views/insights/browser/webVitals/alerts.ts
  static/app/views/insights/browser/webVitals/components/charts/performanceScoreBreakdownChart.tsx
  static/app/views/insights/cache/alerts.ts
  static/app/views/insights/cache/components/charts/hitMissChart.tsx
  static/app/views/insights/cache/components/charts/throughputChart.tsx
  static/app/views/insights/cache/components/charts/transactionDurationChart.tsx
  static/app/views/insights/common/components/chartPanel.tsx
  static/app/views/insights/common/views/spans/spanTimeCharts.tsx
  static/app/views/insights/database/alerts.ts
  static/app/views/insights/database/components/charts/durationChart.tsx
  static/app/views/insights/database/components/charts/throughputChart.tsx
  static/app/views/insights/database/views/databaseLandingPage.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.tsx
  static/app/views/insights/http/alerts.ts
  static/app/views/insights/http/components/charts/durationChart.tsx
  static/app/views/insights/http/components/charts/responseRateChart.tsx
  static/app/views/insights/http/components/charts/throughputChart.tsx
  static/app/views/insights/http/components/httpSamplesPanel.tsx
  static/app/views/insights/http/views/httpDomainSummaryPage.tsx
  static/app/views/insights/http/views/httpLandingPage.tsx
  static/app/views/insights/llmMonitoring/alerts.ts
  static/app/views/insights/llmMonitoring/components/charts/llmMonitoringCharts.tsx
  static/app/views/insights/queues/alerts.ts
  static/app/views/insights/queues/charts/latencyChart.tsx
  static/app/views/insights/queues/charts/throughputChart.tsx
  static/app/views/insights/queues/components/messageSpanSamplesPanel.tsx
Labels: Scope: Frontend

#81693 fix(ui): Filter organization object from sidebar link
  static/app/components/sidebar/sidebarItem.tsx
Labels: Scope: Frontend

#81694 fix(rpc): Table request's timezone
  src/sentry/search/eap/columns.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#81702 fix(issue-stream): Show tooltip when hovering over events column for new layout
  static/app/components/stream/group.tsx
Labels: Scope: Frontend

#81705 fix(crons): fix check-in env styling
  static/app/views/monitors/components/overviewTimeline/overviewRow.tsx
Labels: Scope: Frontend

#81706 fix(replay): Use braces to fix operator precedence
  static/app/views/issueDetails/groupReplays/groupReplays.tsx
Labels: Scope: Frontend

#81698 debug(event tracker): add metrics in save event
  src/sentry/tasks/store.py
Labels: Scope: Backend

#81543 fix(isues): Sort unresolved issue count result
  static/app/views/organizationStats/teamInsights/teamUnresolvedIssues.spec.tsx
  static/app/views/organizationStats/teamInsights/teamUnresolvedIssues.tsx
Labels: Scope: Frontend

#81547 fix(issues): Hide empty project series in team stats
  static/app/views/organizationStats/teamInsights/teamIssuesBreakdown.tsx
Labels: Scope: Frontend

#81710 fix(relocation): Rollback indentation change
  src/sentry/tasks/relocation.py
Labels: Scope: Backend

#81718 feat(explore): Add read the discussion tooltip
  static/app/components/pageHeadingQuestionTooltip.tsx
  static/app/views/explore/content.tsx
Labels: Scope: Frontend

#81712 ref(flags): update settings page to include webhook url
  static/app/views/settings/featureFlags/newProviderForm.spec.tsx
  static/app/views/settings/featureFlags/newProviderForm.tsx
  static/app/views/settings/featureFlags/newSecretHandler.spec.tsx
  static/app/views/settings/featureFlags/newSecretHandler.tsx
  static/app/views/settings/featureFlags/organizationFeatureFlagsNewSecret.tsx
Labels: Scope: Frontend

#81707 ref: use context manager for django cursor
  src/sentry/models/counter.py
Labels: Scope: Backend

#81655 ref(profiling): remove project allowlist option and release stacktraces rules for all the projects
  src/sentry/profiles/task.py
Labels: Scope: Backend

#81725 feat(quick-start): Add new feature flag for GA design changes
  src/sentry/features/temporary.py
Labels: Scope: Backend
