Repository getsentry/sentry, pull requests merged in 2024-04, with the labels that each got.

#67971 ref(crons): Add start + end to TimeWindowConfig
  static/app/components/events/interfaces/crons/cronTimelineSection.tsx
  static/app/views/monitors/components/cronDetailsTimeline.tsx
  static/app/views/monitors/components/mockTimelineVisualization.tsx
  static/app/views/monitors/components/overviewTimeline/checkInTimeline.tsx
  static/app/views/monitors/components/overviewTimeline/gridLines.tsx
  static/app/views/monitors/components/overviewTimeline/index.tsx
  static/app/views/monitors/components/overviewTimeline/jobTickTooltip.spec.tsx
  static/app/views/monitors/components/overviewTimeline/types.tsx
  static/app/views/monitors/components/overviewTimeline/utils.spec.tsx
  static/app/views/monitors/components/overviewTimeline/utils.tsx
  static/app/views/monitors/utils/useMonitorDates.tsx
Labels: Scope: Frontend

#67986 build: remove unused `tocbot` dependency
  package.json
  yarn.lock
Labels: Scope: Frontend

#67970 feat(snuba): Make sure use_group_snuba_dataset is false if using trends
  src/sentry/issues/endpoints/organization_group_index.py
  src/sentry/search/snuba/executors.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#67947 fix(reprocessing): Add indexes on datetime cols for reprocessing models to fix `clear_expired_raw_events`
  migrations_lockfile.txt
  src/sentry/migrations/0683_reprocessing_datetime_indexes.py
  src/sentry/models/processingissue.py
  src/sentry/models/rawevent.py
  src/sentry/models/reprocessingreport.py
  src/sentry/tasks/reprocessing.py
Labels: Scope: Backend

#67978 fix(stories): Scroll the /stories sidebar before the page
  static/app/views/stories/index.tsx
Labels: Scope: Frontend

#67975 feat(replay): Count additions & removals in the Replay Details > Dom chart
  static/app/utils/replays/countDomNodes.tsx
  static/app/views/replays/detail/memoryPanel/domNodesChart.tsx
  static/app/views/replays/detail/memoryPanel/index.tsx
  static/app/views/replays/detail/memoryPanel/memoryChart.tsx
Labels: Scope: Frontend

#67992 build: Rebuild yarn.lock file
  yarn.lock
Labels: Scope: Frontend

#68008 ref: remove unused _format_mods
  tools/mypy_helpers/make_stub_ignores.py
Labels: Scope: Backend

#67909 chore(slack): Cleanup FF as feature is released
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
  src/sentry/integrations/slack/utils/notifications.py
Labels: Scope: Backend

#68007 style(crons): Some comments on GridLines Props
  static/app/views/monitors/components/overviewTimeline/gridLines.tsx
Labels: Scope: Frontend

#67942 fix(crons): Fix monitor form errors
  static/app/views/monitors/components/monitorForm.spec.tsx
  static/app/views/monitors/components/monitorForm.tsx
Labels: Scope: Frontend

#68006 ref: remove some deprecated functions from Interface
  src/sentry/interfaces/base.py
Labels: Scope: Backend

#67980 feat(hybridcloud): Created `get_org_by_id` method
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/services/hybrid_cloud/organization/service.py
  tests/sentry/hybridcloud/test_organization.py
Labels: Scope: Backend

#67955 ref(feedback): update screenshot display in feedback details
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/feedbackScreenshot.tsx
  static/app/components/feedback/feedbackItem/messageSection.tsx
  static/app/components/feedback/feedbackItem/openScreenshotModal.tsx
  static/app/components/feedback/feedbackItem/screenshotSection.tsx
Labels: Scope: Frontend

#67819 ref(crons): Return auto-mute broken monitors to 14 day period
  src/sentry/monitors/tasks/detect_broken_monitor_envs.py
Labels: Scope: Backend

#67925 fix(msteams): Allow new install event to pass
  src/sentry/integrations/msteams/webhook.py
  src/sentry/middleware/integrations/parsers/msteams.py
  tests/sentry/integrations/msteams/webhook/test_ms_teams_webhook_mixin.py
Labels: Scope: Backend

#68024 style(feedback): remove border from screenshot
  static/app/components/feedback/feedbackItem/feedbackScreenshot.tsx
Labels: Scope: Frontend

#68027 ref(crons): Optimize broken detection task schedule
  src/sentry/conf/server.py
Labels: Scope: Backend

#67214 feat(integration): Allow passing of RuleFireHistory
  src/sentry/rules/actions/base.py
  src/sentry/rules/base.py
  src/sentry/rules/history/backends/postgres.py
  src/sentry/rules/history/base.py
  src/sentry/rules/processor.py
  tests/sentry/integrations/slack/actions/__init__.py
  tests/sentry/integrations/slack/actions/notification/__init__.py
  tests/sentry/integrations/slack/actions/notification/test_slack_notify_service_action.py
  tests/sentry/rules/actions/__init__.py
  tests/sentry/rules/actions/base/__init__.py
  tests/sentry/rules/actions/base/test_event_action.py
  tests/sentry/rules/actions/test_base.py
  tests/sentry/rules/history/backends/test_postgres.py
Labels: Scope: Backend

#67974 ref(replay): fix clicks and selectors examples
  src/sentry/apidocs/examples/replay_examples.py
  src/sentry/replays/endpoints/project_replay_clicks_index.py
Labels: Scope: Backend

#68030 style(replays): fix header placeholder size
  static/app/components/replays/header/replayMetaData.tsx
  static/app/views/replays/detail/page.tsx
Labels: Scope: Frontend

#68036 style(replay): fix PanelTable border styles
  static/app/components/panels/panelTable.tsx
  static/app/views/replays/replayTable/index.tsx
Labels: Scope: Frontend

#67913 feat(issue-priority): Add a circuit breaker on consecutive failures
  src/sentry/event_manager.py
  src/sentry/options/defaults.py
  src/sentry/utils/circuit_breaker.py
  tests/sentry/event_manager/test_severity.py
  tests/sentry/utils/test_circuit_breaker.py
Labels: Scope: Backend

#68040 fix(reprocessing): Attempt to fix `clear_expired_raw_events`
  src/sentry/tasks/reprocessing.py
Labels: Scope: Backend

#68041 fix(api): Fix `id_or_slug` Lookup
  src/sentry/db/models/fields/slug.py
  tests/sentry/db/models/fields/test_slug.py
Labels: Scope: Backend

#67933 fix(trace): remove project from query params
  static/app/views/performance/newTraceDetails/useTrace.tsx
Labels: Scope: Frontend

#67983 fix(trace): fix icons and background
  static/app/utils/theme.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#68054 ref(trace): optimize memory usage
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#68055 fix(trace): clear clicked node on outside click
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/traceSearch.tsx
  static/app/views/performance/newTraceDetails/traceTabs.tsx
Labels: Scope: Frontend

#68005 fix(trace): clear last clicked if we are unpinning current one
  static/app/views/performance/newTraceDetails/traceTabs.tsx
Labels: Scope: Frontend

#67935 feat(trace): add web or mobile vitals tab
  static/app/components/events/eventVitals.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/trace.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/traceVitals.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/traceDrawer.tsx
  static/app/views/performance/newTraceDetails/traceTabs.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
Labels: Scope: Frontend

#68004 feat(trace): add manual scrollbar
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#67932 fix(trace): fix autogrouping
  static/app/utils/performance/quickTrace/types.tsx
  static/app/views/performance/newTraceDetails/guards.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#67587 feat(ui): format chart values with abbreviations
  static/app/utils/formatters.spec.tsx
  static/app/utils/formatters.tsx
  static/app/utils/metrics/formatters.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
Labels: Scope: Frontend

#67899 feat(tracing): Allow multiple average columns
  src/sentry/api/endpoints/organization_event_details.py
  src/sentry/snuba/referrer.py
  tests/snuba/api/endpoints/test_organization_event_details.py
Labels: Scope: Backend

#67761 chore(profiles): Send deobfuscation error to Sentry
  src/sentry/profiles/task.py
Labels: Scope: Backend

#67969 feat: hashed user auth tokens
  src/sentry/api/authentication.py
  src/sentry/options/defaults.py
  src/sentry/services/hybrid_cloud/auth/model.py
  src/sentry/services/hybrid_cloud/auth/serial.py
  src/sentry/services/hybrid_cloud/replica/impl.py
  tests/sentry/api/test_authentication.py
Labels: Scope: Backend

#67770 chore(hybridcloud) Add more logging for webhook delivery
  src/sentry/hybridcloud/tasks/deliver_webhooks.py
Labels: Scope: Backend

#67959 fix(trends): Handle asterisks in transaction name for trends
  src/sentry/api/endpoints/organization_events_trends_v2.py
  tests/sentry/api/endpoints/test_organization_events_trends_v2.py
Labels: Scope: Backend

#67706 ref(invites): Disable team selector when non-team role is selected
  fixtures/js-stubs/roleList.tsx
  static/app/components/acl/role.spec.tsx
  static/app/components/modals/inviteMembersModal/index.spec.tsx
  static/app/components/modals/inviteMembersModal/inviteMembersModalview.tsx
  static/app/components/modals/inviteMembersModal/inviteRowControl.tsx
  static/app/components/modals/inviteMissingMembersModal/index.spec.tsx
  static/app/components/modals/inviteMissingMembersModal/index.tsx
  static/app/components/roleSelectControl.tsx
  static/app/constants/index.tsx
  static/app/data/forms/organizationGeneralSettings.tsx
  static/app/types/organization.tsx
  static/app/types/role.tsx
  static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
  static/app/views/settings/organizationMembers/inviteRequestRow.spec.tsx
  static/app/views/settings/organizationMembers/inviteRequestRow.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.spec.tsx
  static/app/views/settings/organizationMembers/organizationMembersList.tsx
Labels: Scope: Frontend

#67984 fix(sidebar): fix bottom nav color
  static/app/components/sidebar/index.tsx
Labels: Scope: Frontend

#67946 fix(trace): attach zoom event handler in invisible space
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#68022 Initialize project joins for alert rules
  src/sentry/incidents/logic.py
  tests/sentry/incidents/test_logic.py
Labels: Scope: Backend

#68052 chore(issues): Remove unused GroupManager.from_kwargs
  src/sentry/models/group.py
  tests/sentry/manager/test_group_manager.py
Labels: Scope: Backend

#67987 feat(trace): partially implement trace searching
  jest.config.ts
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearch.pegjs
  static/app/views/performance/newTraceDetails/traceSearch/traceSearch.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchInput.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchTokenizer.spec.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchTokenizer.tsx
Labels: Scope: Frontend

#68020 fix(crons): Fix monitor env broken notice type
  static/app/views/monitors/components/overviewTimeline/monitorEnvironmentLabel.tsx
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#68031 ref: use redis.client Script directly
  src/sentry/digests/backends/redis.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/quotas/redis.py
  src/sentry/ratelimits/concurrent.py
  src/sentry/similarity/backends/redis.py
  src/sentry/tsdb/redis.py
  src/sentry/utils/locking/backends/redis.py
  src/sentry/utils/redis.py
  tests/sentry/quotas/test_redis.py
Labels: Scope: Backend

#67825 ref(crons): Mark MonitorCheckIn config column as nullable
  migrations_lockfile.txt
  src/sentry/migrations/0684_monitor_check_in_config_nullable.py
  src/sentry/monitors/models.py
Labels: Scope: Backend

#68063 feat/logos/nintendo switch
  src/sentry/static/sentry/images/logos/logo-nintendo-switch.svg
  static/app/components/events/contextSummary/contextIcon.tsx
Labels: Scope: Frontend

#67938 fix(similarity-embedding): Fix analytic null check
  src/sentry/api/endpoints/group_similar_issues_embeddings.py
Labels: Scope: Backend

#67982 ref(code-mappings): Refactor "packaged" platforms for code-mappings (#2)
  src/sentry/integrations/utils/code_mapping.py
  tests/sentry/api/endpoints/test_project_repo_path_parsing.py
  tests/sentry/integrations/utils/test_code_mapping.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#67896 feat(new-trace): Adding transaction duration comparison.
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction.tsx
  static/app/views/performance/newTraceDetails/useTraceAverageTransactionDuration.tsx
Labels: Scope: Frontend

#68077 fix(trace): fix loading indicator
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
Labels: Scope: Frontend

#68026 fix(staff): Remove idle expiration time for staff
  src/sentry/auth/staff.py
  tests/sentry/auth/test_staff.py
Labels: Scope: Backend

#67653 fix(perfscore): Temporary fix for `weighted_performance_score` returning incorrect values.
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#67939 feat(ui): Add a reusable GuidedSteps component
  static/app/components/guidedSteps/guidedSteps.spec.tsx
  static/app/components/guidedSteps/guidedSteps.stories.tsx
  static/app/components/guidedSteps/guidedSteps.tsx
Labels: Scope: Frontend

#68079 fix(replay): change state for selected replay
  static/app/views/replays/replayTable/index.tsx
Labels: Scope: Frontend

#68039 ref(crons): Adjust stats bounds to included start not end
  src/sentry/monitors/endpoints/organization_monitor_index_stats.py
  tests/sentry/monitors/endpoints/test_organization_monitor_index_stats.py
Labels: Scope: Backend

#67758 feat(rca): Add regression score to span metrics
  src/sentry/search/events/datasets/spans_metrics.py
  tests/snuba/api/endpoints/test_organization_events_span_metrics.py
Labels: Scope: Backend

#68033 ref(crons): Improve timeline marker calculations
  static/app/views/monitors/components/mockTimelineVisualization.spec.tsx
  static/app/views/monitors/components/overviewTimeline/gridLines.tsx
  static/app/views/monitors/components/overviewTimeline/jobTickTooltip.spec.tsx
  static/app/views/monitors/components/overviewTimeline/types.tsx
  static/app/views/monitors/components/overviewTimeline/utils.spec.tsx
  static/app/views/monitors/components/overviewTimeline/utils.tsx
  static/app/views/monitors/utils/useMonitorDates.tsx
Labels: Scope: Frontend

#68016 chore(slack): default message builder to block kit
  src/sentry/integrations/slack/message_builder/issues.py
  src/sentry/testutils/cases.py
  tests/sentry/integrations/slack/notifications/test_assigned.py
  tests/sentry/integrations/slack/notifications/test_issue_alert.py
  tests/sentry/integrations/slack/notifications/test_regression.py
  tests/sentry/integrations/slack/notifications/test_resolved.py
  tests/sentry/integrations/slack/notifications/test_resolved_in_release.py
  tests/sentry/integrations/slack/notifications/test_unassigned.py
  tests/sentry/integrations/slack/test_message_builder.py
  tests/sentry/integrations/slack/test_notifications.py
  tests/sentry/integrations/slack/test_notify_action.py
  tests/sentry/integrations/slack/test_unfurl.py
  tests/sentry/integrations/slack/webhooks/actions/test_status.py
  tests/sentry/notifications/notifications/test_assigned.py
  tests/sentry/notifications/notifications/test_digests.py
  tests/sentry/notifications/test_notifications.py
  tests/sentry/rules/test_processor.py
Labels: Scope: Backend

#68088 fix(issues): add metrics to allowlist for issues apis
  src/sentry/conf/server.py
  src/sentry/middleware/stats.py
Labels: Scope: Backend

#68078 feat(sdks): Upgrade to 7.109.0
  package.json
  yarn.lock
Labels: Scope: Frontend

#68037 feat(snuba): use assignee filters for snuba
  src/sentry/search/snuba/executors.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#67604 fix(auth) Fix incorrect silo mode task spawning
  src/sentry/web/frontend/organization_auth_settings.py
  tests/sentry/web/frontend/test_organization_auth_settings.py
Labels: Scope: Backend

#68090 chore(onboarding): Update PHP onboarding with excimer information
  static/app/gettingStartedDocs/php/laravel.tsx
  static/app/gettingStartedDocs/php/php.tsx
  static/app/gettingStartedDocs/php/symfony.tsx
Labels: Scope: Frontend

#67838 fix(hybridcloud) Use celery for unlink delivery
  src/sentry/services/hybrid_cloud/organization/impl.py
  src/sentry/tasks/auth.py
  tests/sentry/tasks/test_auth.py
Labels: Scope: Backend

#68035 ref(alerts): Remove unused project prop
  static/app/components/selectMembers/index.tsx
  static/app/views/alerts/rules/issue/memberTeamFields.tsx
  static/app/views/alerts/rules/metric/triggers/actionsPanel/actionTargetSelector.tsx
Labels: Scope: Frontend

#68070 Activation condition singular rename
  migrations_lockfile.txt
  src/sentry/incidents/models/alert_rule.py
  src/sentry/incidents/models/alert_rule_activations.py
  src/sentry/migrations/0685_alert_rule_conditons_rename_singular.py
Labels: Scope: Backend

#68098 fix(hybridcloud) Add missing int() on jira issue_id
  fixtures/integrations/jira/stubs/edit_issue_assignee_payload.json
  src/sentry/middleware/integrations/parsers/jira_server.py
Labels: Scope: Backend

#68093 ref(autofix): fallback to latest event if no recommended event
  src/sentry/api/endpoints/group_ai_autofix.py
  tests/sentry/api/endpoints/test_group_ai_autofix.py
Labels: Scope: Backend

#68080 chore(relocation): Increase import/export timeouts
  src/sentry/runner/initializer.py
  src/sentry/tasks/relocation.py
  src/sentry/utils/relocation.py
  tests/sentry/runner/test_initializer.py
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Backend

#68096 feat(backup): Add some user facing terminal updates
  src/sentry/runner/commands/backup.py
Labels: Scope: Backend

#68013 feat(autofix): Add setup modal
  static/app/components/events/autofix/autofixBanner.spec.tsx
  static/app/components/events/autofix/autofixBanner.tsx
  static/app/components/events/autofix/index.spec.tsx
  static/app/components/events/autofix/index.tsx
  static/app/components/events/autofix/useAutofixSetup.tsx
  static/app/components/guidedSteps/guidedSteps.spec.tsx
  static/app/components/guidedSteps/guidedSteps.stories.tsx
  static/app/components/guidedSteps/guidedSteps.tsx
  static/app/components/modals/autofixSetupModal.spec.tsx
  static/app/components/modals/autofixSetupModal.tsx
  static/app/types/hooks.tsx
Labels: Scope: Frontend

#68105 ref(crons): Remove MonitorCheckIn config column as state operation
  migrations_lockfile.txt
  src/sentry/migrations/0686_remove_config_from_checkin_state_operation.py
  src/sentry/monitors/models.py
Labels: Scope: Backend

#68029 ref: remove client_class customization for redis single-node
  src/sentry/processing/backpressure/memory.py
  src/sentry/utils/redis.py
  tests/sentry/utils/test_redis.py
Labels: Scope: Backend

#68018 ref: break the generic / inheritance of redis ClusterManager
  src/sentry/digests/backends/redis.py
  src/sentry/tsdb/redis.py
  src/sentry/utils/redis.py
  tests/sentry/processing/realtime_metrics/test_redis.py
  tests/sentry/tsdb/test_redis.py
  tests/sentry/utils/test_redis.py
Labels: Scope: Backend

#68075 feat(new-trace): Adding timestamp to trace url from discover eventId and trace id click
  static/app/utils/dates.tsx
  static/app/views/discover/results.tsx
  static/app/views/discover/table/index.tsx
  static/app/views/discover/table/tableView.tsx
Labels: Scope: Frontend

#68103 feat(rca): Add avg_by_timestamp to span metrics
  src/sentry/search/events/datasets/spans_metrics.py
  tests/snuba/api/endpoints/test_organization_events_span_metrics.py
Labels: Scope: Backend

#68110 style(crons): Spelling in overviewTimeline/utils
  static/app/views/monitors/components/overviewTimeline/utils.tsx
Labels: Scope: Frontend

#68084 fix(hc): Removes option check for region-specific upload URLs
  src/sentry/api/endpoints/chunk.py
  src/sentry/options/defaults.py
  tests/sentry/api/endpoints/test_chunk_upload.py
Labels: Scope: Backend

#68112 ref: --disallow-any-generics for utils.redis
  pyproject.toml
  src/sentry/cache/redis.py
  src/sentry/monitors/clock_dispatch.py
  src/sentry/relay/projectconfig_cache/redis.py
  src/sentry/spans/buffer/redis.py
  src/sentry/utils/locking/backends/redis.py
  src/sentry/utils/redis.py
  tests/sentry/attachments/test_redis.py
  tests/sentry/buffer/test_redis.py
Labels: Scope: Backend

#68074 feat(ai): Display object values in new trace view nicely
  static/app/components/events/interfaces/spans/newTraceDetailsSpanDetails.tsx
  static/app/views/performance/traceDetails/newTraceDetailsValueRenderer.tsx
Labels: Scope: Frontend

#68117 fix(perfscore): shortens feature flag key to organizations:starfish-browser-webvitals-score-computed-total
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
  src/sentry/search/events/datasets/metrics.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
Labels: Scope: Backend

#68115 fix(new-trace): Fixes infinite loading state for empty traces bug.
  static/app/views/performance/newTraceDetails/index.tsx
Labels: Scope: Frontend

#68116 fix(grouping): release support in custom fingerprinting
  src/sentry/grouping/fingerprinting/__init__.py
  tests/sentry/grouping/fingerprint_inputs/fingerprint-release.json
  tests/sentry/grouping/snapshots/test_fingerprinting/test_event_hash_variant/fingerprint_release.pysnap
  tests/sentry/grouping/test_fingerprinting.py
Labels: Scope: Backend

#68050 feat(crons): Add monitor.incident tag to issue events
  src/sentry/monitors/logic/mark_failed.py
  tests/sentry/monitors/logic/test_mark_failed.py
Labels: Scope: Backend

#68120 fix(relocation): Increase cloudbuild import/export timeout
  src/sentry/utils/relocation.py
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Backend

#67563 Alert rule project backfill migration
  migrations_lockfile.txt
  src/sentry/incidents/models/alert_rule.py
  src/sentry/migrations/0687_alert_rule_project_backfill_migration.py
  src/sentry/snuba/models.py
  tests/sentry/migrations/test_0687_alert_rule_project_backfill_migration.py
Labels: Scope: Backend

#68126 style(crons): A couple comment cleanups in monitor types
  static/app/views/monitors/types.tsx
Labels: Scope: Frontend

#68124 ref: enforce stronger types for sentry.runner.commands.backup
  pyproject.toml
  src/sentry/backup/crypto.py
  src/sentry/backup/exports.py
  src/sentry/backup/imports.py
  src/sentry/runner/commands/backup.py
Labels: Scope: Backend

#68095 ref(code-mappings): code-mapping readability & style refactors
  src/sentry/integrations/utils/code_mapping.py
  tests/sentry/integrations/utils/test_code_mapping.py
Labels: Scope: Backend

#67793 ref(code-mappings): Remove feature flag for php auto code mappings (post-GA)
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#68128 ref: ensure stronger typing list is sorted
  .pre-commit-config.yaml
  Makefile
  pyproject.toml
  tests/tools/mypy_helpers/test_sort_stronger_modules.py
  tools/mypy_helpers/sort_stronger_modules.py
Labels: Scope: Backend

#67248 ref(hc): Represent RPC request and response bodies as Pydantic objects
  src/sentry/api/endpoints/internal/rpc.py
  src/sentry/services/hybrid_cloud/__init__.py
  src/sentry/services/hybrid_cloud/rpc.py
  tests/sentry/api/endpoints/test_rpc.py
  tests/sentry/hybridcloud/test_rpc.py
Labels: Scope: Backend

#67668 test+fix(ingest): exclude KeyError from Retriable
  src/sentry/ingest/consumer/processors.py
  tests/sentry/ingest/ingest_consumer/test_dlq.py
Labels: Scope: Backend

#68139 style(replay): fix widget bottom border corners
  static/app/views/replays/deadRageClick/deadRageSelectorCards.tsx
Labels: Scope: Frontend

#67814 Remove Redis references from Sentry
  src/sentry/sentry_metrics/configuration.py
Labels: Scope: Backend

#68125 ref: Reuse makeFetchEventAttachmentsQueryKey in useFetchEventAttachments
  static/app/actionCreators/events.tsx
Labels: Scope: Frontend

#68053 feat(api-idorslug): Finish single `organization_slug` Tests
  src/sentry/api/bases/organization.py
  src/sentry/api/bases/project.py
  src/sentry/api/bases/sentryapps.py
  src/sentry/api/endpoints/codeowners/details.py
  src/sentry/api/endpoints/organization_region.py
  src/sentry/db/models/fields/slug.py
  tests/sentry/api/path_params/resources/test_id_or_slug_path_params_mixin.py
  tests/sentry/api/path_params/resources/test_organization_slug.py
  tests/sentry/api/path_params/resources/test_project_slug.py
  tests/sentry/api/path_params/resources/test_sentry_app_slug.py
  tests/sentry/api/path_params/test_id_or_slug_path_params.py
Labels: Scope: Backend

#68108 feat(new-trace): Changing duration comparison text.
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
Labels: Scope: Frontend

#67784 feat(proguard): A/B test new Symbolicator implementation
  src/sentry/lang/java/plugin.py
  src/sentry/lang/java/processing.py
  src/sentry/lang/java/utils.py
  src/sentry/options/defaults.py
Labels: Scope: Backend

#68158 ref(relay): Make cardinality limits more configurable
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/options/defaults.py
  src/sentry/relay/config/__init__.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v2.py
  tests/sentry/relay/snapshots/test_config/test_project_config_cardinality_limits/False/REGION.pysnap
  tests/sentry/relay/snapshots/test_config/test_project_config_cardinality_limits/True/REGION.pysnap
  tests/sentry/relay/test_config.py
Labels: Scope: Backend

#67865 Simplify Symbolication Task definition
  src/sentry/tasks/symbolication.py
  tests/sentry/tasks/test_store.py
  tests/sentry/tasks/test_symbolication.py
Labels: Scope: Backend

#68168 fix(onboarding): Blank setup docs
  static/app/views/onboarding/onboarding.tsx
Labels: Scope: Frontend

#68132 ref: stronger types for sentry.runner.commands.cleanup
  src/sentry/runner/commands/cleanup.py
Labels: Scope: Backend

#68129 ref: require stronger typing for tools.* modules
  pyproject.toml
Labels: Scope: Backend

#68099 chore(onboarding): Update flutter onboarding to include profiling
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/flutter/flutter.spec.tsx
  static/app/gettingStartedDocs/flutter/flutter.tsx
Labels: Scope: Frontend

#68092 feat(rca): Add feature flag for spans UI
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#68136 feat(feedback): Refactor the feedback screenshot rendering to show N screenshots side by side
  static/app/components/feedback/feedbackItem/feedbackScreenshot.tsx
  static/app/components/feedback/feedbackItem/screenshotSection.tsx
Labels: Scope: Frontend

#68174 chore(sdk): Bump to `sentry-sdk` `1.44.1`
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#67529 feat(profiles): Add support for continuous profiling
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
  src/sentry/profiles/task.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#67890 ref(performance): Remove Apdex and User Misery charts on landing page
  static/app/views/performance/landing/views/allTransactionsView.tsx
  static/app/views/performance/landing/views/backendView.tsx
Labels: Scope: Frontend

#68140 fix(backup): Change UserIP relocation scope to global
  fixtures/backup/model_dependencies/detailed.json
  src/sentry/models/userip.py
  tests/sentry/backup/test_exports.py
  tests/sentry/backup/test_imports.py
Labels: Scope: Backend

#68152 fix(trace): fix bad border style
  static/app/views/performance/newTraceDetails/traceDrawer/traceDrawer.tsx
Labels: Scope: Frontend

#68151 fix(trace): use old path format and fix autogrouping edge case
  static/app/views/performance/newTraceDetails/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.spec.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
  static/app/views/performance/traceDetails/TraceDetailsRouting.tsx
Labels: Scope: Frontend

#68182 ref(ui): Avoid gap in invite member modal
  static/app/components/modals/inviteMembersModal/inviteStatusMessage.tsx
  static/app/components/modals/inviteMissingMembersModal/index.tsx
Labels: Scope: Frontend

#68134 ref(crons): Extract useMonitorStats hook
  static/app/views/monitors/components/cronDetailsTimeline.tsx
  static/app/views/monitors/components/overviewTimeline/index.tsx
  static/app/views/monitors/components/overviewTimeline/jobTickTooltip.spec.tsx
  static/app/views/monitors/components/overviewTimeline/types.tsx
  static/app/views/monitors/components/overviewTimeline/useMonitorDates.tsx
  static/app/views/monitors/components/overviewTimeline/useMonitorStats.tsx
  static/app/views/monitors/components/overviewTimeline/useTimeWindowConfig.tsx
  static/app/views/monitors/components/overviewTimeline/utils.spec.tsx
  static/app/views/monitors/components/overviewTimeline/utils.tsx
  static/app/views/monitors/utils/useMonitorDates.tsx
Labels: Scope: Frontend

#68138 ref(daily summary): Remove 'internal only' text
  src/sentry/notifications/notifications/daily_summary.py
  tests/sentry/tasks/test_daily_summary.py
Labels: Scope: Backend

#68143 ref(rules): Collect metrics on rule create/edit notifications
  src/sentry/api/endpoints/project_rule_details.py
  src/sentry/api/endpoints/project_rules.py
Labels: Scope: Backend

#68086 feat(severity): Add metrics for error cases
  src/sentry/event_manager.py
Labels: Scope: Backend

#67979 fix(issue-priority): Fix determining previous priority for ongoing groups
  src/sentry/issues/priority.py
  src/sentry/models/group.py
  tests/sentry/issues/test_ongoing.py
  tests/sentry/issues/test_priority.py
  tests/sentry/issues/test_status_change_consumer.py
Labels: Scope: Backend

#68130 ref: require stronger types for sentry.runner.commands.*
  pyproject.toml
  src/sentry/runner/commands/config.py
  src/sentry/runner/commands/configoptions.py
  src/sentry/runner/commands/createuser.py
  src/sentry/runner/commands/devservices.py
  src/sentry/runner/commands/django.py
  src/sentry/runner/commands/exec.py
  src/sentry/runner/commands/execfile.py
  src/sentry/runner/commands/files.py
  src/sentry/runner/commands/help.py
  src/sentry/runner/commands/init.py
  src/sentry/runner/commands/killswitches.py
  src/sentry/runner/commands/migrations.py
  src/sentry/runner/commands/openai.py
  src/sentry/runner/commands/performance.py
  src/sentry/runner/commands/permissions.py
  src/sentry/runner/commands/plugins.py
  src/sentry/runner/commands/presenters/presenterdelegator.py
  src/sentry/runner/commands/presenters/webhookpresenter.py
  src/sentry/runner/commands/queues.py
  src/sentry/runner/commands/repair.py
  src/sentry/runner/commands/run.py
  src/sentry/runner/commands/sendmail.py
  src/sentry/runner/commands/spans.py
  src/sentry/runner/commands/start.py
  src/sentry/runner/commands/tsdb.py
  src/sentry/runner/commands/upgrade.py
Labels: Scope: Backend

#67672 feat(grouping): Improve uniq_id token identification in parameterization logic
  src/sentry/grouping/strategies/message.py
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/csp_style_src_elem.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/csp_style_src_elem.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/csp_style_src_elem.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/csp_style_src_elem.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/csp_style_src_elem.pysnap
  tests/sentry/grouping/test_normalize_message.py
Labels: Scope: Backend

#68195 Feature flags in the backend for AI analytics
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#67533 feat(devenv): repo-local bins
  .envrc
  devenv/sync.py
  requirements-dev-frozen.txt
  requirements-dev.txt
  scripts/start-colima.py
  src/sentry/runner/commands/devservices.py
Labels: Scope: Backend

#68121 feat(replays): Add support for Range header
  src/sentry/replays/endpoints/project_replay_video_details.py
  src/sentry/replays/lib/http.py
  tests/sentry/replays/test_project_replay_video_details.py
  tests/sentry/replays/unit/lib/test_http.py
Labels: Scope: Backend

#68127 update alert_rule details endpoint to accept activation condition
  src/sentry/incidents/endpoints/organization_alert_rule_details.py
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
  src/sentry/incidents/serializers/alert_rule.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
Labels: Scope: Backend

#68196 Removed Redis config
  src/sentry/conf/server.py
Labels: Scope: Backend

#68188 fix(severity): Update default rate limits
  src/sentry/event_manager.py
  src/sentry/options/defaults.py
Labels: Scope: Backend

#68113 feat(snuba-search): skip snuba on certain filters
  src/sentry/issues/endpoints/organization_group_index.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#68204 ref(ui): Switch DateTime to named exports
  static/app/components/activity/item/index.tsx
  static/app/components/archivedBox.tsx
  static/app/components/dateTime.spec.tsx
  static/app/components/dateTime.tsx
  static/app/components/events/autofix/autofixSteps.tsx
  static/app/components/events/eventMetadata.tsx
  static/app/components/events/eventStatisticalDetector/eventComparison/eventDisplay.tsx
  static/app/components/events/eventStatisticalDetector/regressionMessage.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/modal.tsx
  static/app/components/events/interfaces/debugMeta/debugImageDetails/candidate/information/index.tsx
  static/app/components/events/interfaces/spans/newTraceDetailsSpanDetails.tsx
  static/app/components/events/interfaces/spans/spanDetail.tsx
  static/app/components/feedback/feedbackItem/feedbackViewers.tsx
  static/app/components/group/seenInfo.tsx
  static/app/components/mutedBox.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/profileDetails.tsx
  static/app/components/profiling/profileEventsTable.tsx
  static/app/utils/discover/styles.tsx
  static/app/views/alerts/rules/issue/details/issuesList.tsx
  static/app/views/alerts/rules/metric/details/index.tsx
  static/app/views/alerts/rules/metric/details/metricHistory.tsx
  static/app/views/alerts/rules/metric/details/sidebar.tsx
  static/app/views/dataExport/dataDownload.tsx
  static/app/views/issueDetails/groupActivityItem.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachmentsTableRow.tsx
  static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx
  static/app/views/issueDetails/groupEventCarousel.tsx
  static/app/views/issueDetails/groupSidebar.tsx
  static/app/views/issueDetails/traceTimeline/traceTimelineEvents.tsx
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/components/overviewTimeline/checkInTimeline.tsx
  static/app/views/monitors/components/overviewTimeline/gridLines.tsx
  static/app/views/monitors/components/overviewTimeline/jobTickTooltip.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction.tsx
  static/app/views/performance/traceDetails/traceViewDetailPanel.tsx
  static/app/views/performance/traceDetails/transactionDetail.tsx
  static/app/views/performance/transactionDetails/eventMetas.tsx
  static/app/views/profiling/profileSummary/index.tsx
  static/app/views/projectDetail/projectLatestReleases.tsx
  static/app/views/releases/detail/overview/index.tsx
  static/app/views/releases/detail/overview/sidebar/projectReleaseDetails.tsx
  static/app/views/replays/detail/timestampButton.tsx
  static/app/views/settings/account/accountIdentities.tsx
  static/app/views/settings/account/accountSecurity/accountSecurityDetails.tsx
  static/app/views/settings/account/accountSecurity/components/u2fEnrolledDetails.tsx
  static/app/views/settings/account/accountSubscriptions.tsx
  static/app/views/settings/account/apiTokenRow.tsx
  static/app/views/settings/organizationAuditLog/auditLogList.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDashboard/index.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDashboard/requestLog.tsx
  static/app/views/settings/organizationMembers/organizationMemberDetail.tsx
  static/app/views/settings/organizationRelay/list/activityList.tsx
  static/app/views/settings/organizationRelay/list/cardHeader.tsx
  static/app/views/settings/project/projectKeys/details/keySettings.tsx
  static/app/views/settings/projectDebugFiles/sources/customRepositories/details.tsx
  static/app/views/settings/projectSourceMaps/debugIdBundleDetails.tsx
  static/app/views/settings/projectSourceMaps/projectSourceMaps.tsx
  static/app/views/starfish/components/samplesTable/transactionSamplesTable.tsx
Labels: Scope: Frontend

#68205 ref(ui): Remove unused default export of ActivityAvatar
  static/app/components/activity/item/avatar.tsx
Labels: Scope: Frontend

#68119 feat(trace): Default to all projects for traces
  src/sentry/api/endpoints/organization_events_trace.py
  tests/snuba/api/endpoints/test_organization_events_trace.py
Labels: Scope: Backend

#68198 feat(issues): add audit log for deletions
  src/sentry/api/helpers/group_index/delete.py
  src/sentry/audit_log/register.py
  tests/sentry/api/endpoints/test_group_details.py
  tests/sentry/audit_log/test_register.py
Labels: Scope: Backend

#68190 feat(replay): Adds click to search on component name
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/utils/replays/types.tsx
Labels: Scope: Frontend

#68207 chore(slack): attachments logger
  src/sentry/integrations/slack/actions/notification.py
Labels: Scope: Backend

#68194 chore(empty-states): Add feature flag
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#68209 chore(dependencies): Bump platformicons
  package.json
  yarn.lock
Labels: Scope: Frontend

#68147 feat(code-mappings): Add support for Go automatic code-mappings (EA)
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
  src/sentry/tasks/derive_code_mappings.py
  tests/sentry/tasks/test_derive_code_mappings.py
Labels: Scope: Backend

#68208 feat(perf): Improve rendering of HTTP Status Code columns
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/performance/http/httpSamplesPanel.tsx
  static/app/views/starfish/components/tableCells/renderHeadCell.tsx
  static/app/views/starfish/components/tableCells/responseStatusCodeCell.tsx
Labels: Scope: Frontend

#67918 fix(replays): show first frame by default for mobile replays
  static/app/components/replays/videoReplayer.tsx
Labels: Scope: Frontend

#68219 fix(severity): Initialize unbounded variable
  src/sentry/event_manager.py
  tests/sentry/event_manager/test_priority.py
Labels: Scope: Backend

#67353 feat(release-health): Sessions should not be default
  src/sentry/conf/server.py
  src/sentry/release_health/metrics.py
  src/sentry/testutils/pytest/metrics.py
  tests/acceptance/test_organization_dashboards.py
  tests/acceptance/test_organization_switch.py
  tests/apidocs/endpoints/releases/test_organization_releases.py
  tests/apidocs/endpoints/releases/test_organization_sessions.py
  tests/sentry/api/endpoints/test_organization_release_details.py
  tests/sentry/api/endpoints/test_organization_releases.py
  tests/sentry/api/endpoints/test_project_release_details.py
  tests/sentry/api/endpoints/test_project_release_stats.py
  tests/sentry/integrations/slack/test_unfurl.py
  tests/sentry/release_health/test_metrics_sessions_v2.py
  tests/sentry/rules/filters/test_latest_release.py
  tests/snuba/api/endpoints/test_organization_sessions.py
  tests/snuba/api/serializers/test_group_stream.py
  tests/snuba/rules/conditions/test_event_frequency.py
  tests/snuba/sessions/test_sessions.py
Labels: Scope: Backend

#68225 chore(login): update the login banners
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#68229 fix(relocation): Right size validation step timeouts
  src/sentry/utils/relocation.py
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Backend

#68220 feat(webvitals): Escapes asterisk in transaction name for page overview
  static/app/views/performance/browser/webVitals/pageOverview.spec.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useProjectRawWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useProjectRawWebVitalsTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useProjectRawWebVitalsValuesTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useTransactionRawSamplesWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useTransactionRawWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useProjectWebVitalsScoresQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useProjectWebVitalsScoresTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useTransactionSamplesWebVitalsScoresQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useTransactionWebVitalsScoresQuery.tsx
Labels: Scope: Frontend

#67577 feat: PowerShell support (backend)
  bin/extension_language_map.py
  fixtures/integration-docs/_platforms.json
  fixtures/integration-docs/powershell.json
  src/sentry/constants.py
  src/sentry/issues/event.schema.json
  src/sentry/models/featureadoption.py
  src/sentry/models/project.py
  src/sentry/utils/platform_categories.py
  src/sentry/utils/tag_normalization.py
Labels: Scope: Backend, Trigger: getsentry tests

#68223 fix(backup): Update password comparator to handle SSO users
  src/sentry/backup/comparators.py
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/backup/test_comparators.py
Labels: Scope: Backend

#68221 feat(testing): allow forcing in_test_environment via env var
  src/sentry/utils/env.py
Labels: Scope: Backend
