Repository getsentry/sentry, pull requests merged in 2024-03, with the labels that each got.

#66112 fix: Filter null user IDs before querying in get_owners
  src/sentry/services/hybrid_cloud/organization/model.py
Labels: Scope: Backend

#66046 feat(ddm): Add limit when fetching code locations from Redis
  src/sentry/sentry_metrics/querying/metadata/metrics_code_locations.py
  tests/sentry/api/endpoints/test_organization_ddm_meta.py
  tests/sentry/api/endpoints/test_organization_metrics_metadata.py
Labels: Scope: Backend

#65613 feat(profiling): Minimal UI for internal DSNs
  static/app/types/project.tsx
  static/app/views/settings/project/projectKeys/projectKeyCredentials.tsx
Labels: Scope: Frontend, Scope: Backend

#65696 feat(ddm): Implement unit normalization in the metrics query endpoint
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/sentry_metrics/querying/data_v2/api.py
  src/sentry/sentry_metrics/querying/data_v2/execution.py
  src/sentry/sentry_metrics/querying/data_v2/parsing.py
  src/sentry/sentry_metrics/querying/data_v2/preparation.py
  src/sentry/sentry_metrics/querying/data_v2/transformation.py
  src/sentry/sentry_metrics/querying/data_v2/units.py
  tests/sentry/api/endpoints/test_organization_metrics_query.py
  tests/sentry/sentry_metrics/querying/data_v2/test_api.py
Labels: Scope: Backend

#66124 fix(ddm): Fix query substitution algorithm with overlapping query names
  src/sentry/sentry_metrics/querying/data_v2/plan.py
  tests/sentry/sentry_metrics/querying/data_v2/test_plan.py
Labels: Scope: Backend

#66125 RIP `ArtifactBundleFlatFileIndex`
  src/sentry/api/endpoints/artifact_lookup.py
  src/sentry/conf/server.py
  src/sentry/debug_files/artifact_bundle_indexing.py
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/debug_files/tasks.py
  src/sentry/lang/native/sources.py
  src/sentry/lang/native/symbolicator.py
  src/sentry/models/artifactbundle.py
  src/sentry/tasks/assemble.py
  tests/relay_integration/lang/javascript/test_plugin.py
  tests/sentry/debug_files/test_artifact_bundle_indexing.py
  tests/sentry/lang/native/test_sources.py
  tests/sentry/models/test_artifactbundle.py
  tests/sentry/tasks/test_assemble.py
Labels: Scope: Backend

#66133 ref(ddm): Pass blocked metric tags to search bar
  static/app/utils/metrics/index.tsx
  static/app/utils/metrics/useMetricsMeta.tsx
  static/app/utils/metrics/useMetricsTags.tsx
  static/app/views/ddm/formulaInput.tsx
  static/app/views/ddm/metricSearchBar.tsx
  static/app/views/ddm/queryBuilder.tsx
  static/app/views/ddm/scratchpad.tsx
  static/app/views/ddm/widget.tsx
Labels: Scope: Frontend

#66070 feat(trace): render web vitals labels
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#65165 chore(processing) Remove multiredis adapter
  src/sentry/eventstore/processing/multiredis.py
  src/sentry/options/defaults.py
  tests/sentry/eventstore/processing/test_multiredis.py
Labels: Scope: Backend

#66035 feat(feedback): add koa node platform to onboarding
  static/app/data/platformCategories.tsx
  static/app/gettingStartedDocs/node/koa.tsx
Labels: Scope: Frontend

#66101 feat(feedback): add crash report banner to dotnet platforms
  static/app/components/onboarding/gettingStartedDoc/feedback/altCrashReportCallout.tsx
  static/app/gettingStartedDocs/dotnet/dotnet.tsx
  static/app/gettingStartedDocs/unity/unity.tsx
Labels: Scope: Frontend

#66063 fix(hybridcloud) Add an index to orgauthtokenreplica
  migrations_lockfile.txt
  src/sentry/hybridcloud/migrations/0013_add_orgauthtokenreplica_token_index.py
  src/sentry/hybridcloud/models/orgauthtokenreplica.py
Labels: Scope: Backend

#66142 ref(wizard) aspnetcore remove outdated setp
  static/app/gettingStartedDocs/dotnet/aspnetcore.tsx
Labels: Scope: Frontend

#66022 test(metrics): Update send_metrics.py to include gauges
  bin/send_metrics.py
Labels: Scope: Backend

#66143 fix(metrics-extraction): Fix discover splitting code
  src/sentry/api/bases/organization_events.py
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/endpoints/organization_events_stats.py
  tests/snuba/api/endpoints/test_organization_events_stats_mep.py
Labels: Scope: Backend

#65861 fix(hybridcloud) Don't use integration proxy for slack
  src/sentry/integrations/slack/client.py
  src/sentry/integrations/slack/integration.py
  tests/sentry/integrations/slack/test_client.py
  tests/sentry/integrations/slack/webhooks/events/test_message_im.py
Labels: Scope: Backend

#66110 feat(github-comments): Don't comment info-level issues on merged PRs
  src/sentry/tasks/commit_context.py
  src/sentry/tasks/integrations/github/pr_comment.py
  tests/sentry/tasks/integrations/github/test_pr_comment.py
  tests/sentry/tasks/test_commit_context.py
Labels: Scope: Backend

#66122 test(ui): Silence act warnings in utils tests
  static/app/utils/discover/discoverQuery.spec.tsx
  static/app/utils/discover/fieldRenderers.spec.tsx
  static/app/utils/projects.spec.tsx
  static/app/utils/url/useLocationQuery.spec.tsx
  static/app/utils/useDismissAlert.spec.tsx
  static/app/utils/useTeams.spec.tsx
  static/app/utils/useTimeout.spec.tsx
  static/app/utils/useUndoableReducer.spec.tsx
  static/app/utils/useUserTeams.spec.tsx
  static/app/utils/withRelease.spec.tsx
  static/app/utils/withRepositories.spec.tsx
  static/app/utils/withSentryAppComponents.spec.tsx
  static/app/views/replays/detail/console/useConsoleFilters.spec.tsx
  static/app/views/replays/detail/errorList/useErrorFilters.spec.tsx
  static/app/views/replays/detail/network/useNetworkFilters.spec.tsx
Labels: Scope: Frontend

#66023 feat(feedback): add project option for enabling AI spam detection
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/serializers/models/project.py
  src/sentry/models/options/project_option.py
  src/sentry/projectoptions/defaults.py
  tests/sentry/api/endpoints/test_project_details.py
Labels: Scope: Backend

#66149 ref(ui): Swap `React.Key` for our own type in Select components
  static/app/components/compactSelect/composite.tsx
  static/app/components/compactSelect/control.tsx
  static/app/components/compactSelect/gridList/index.tsx
  static/app/components/compactSelect/gridList/section.tsx
  static/app/components/compactSelect/index.tsx
  static/app/components/compactSelect/list.tsx
  static/app/components/compactSelect/listBox/index.tsx
  static/app/components/compactSelect/listBox/section.tsx
  static/app/components/compactSelect/types.tsx
  static/app/components/compactSelect/utils.tsx
  static/app/components/organizations/hybridFilter.tsx
  static/app/components/tabs/index.tsx
  static/app/components/tabs/tabList.tsx
Labels: Scope: Frontend

#66033 chore(relocation): Hide relocation link from org create page if feature is not enabled
  static/app/views/organizationCreate/index.spec.tsx
  static/app/views/organizationCreate/index.tsx
Labels: Scope: Frontend

#65369 fix(alert): Fix cascading deletion for alert rule
  src/sentry/deletions/__init__.py
  src/sentry/deletions/defaults/__init__.py
  src/sentry/deletions/defaults/alert_rule_trigger.py
  src/sentry/deletions/defaults/alert_rule_trigger_action.py
  src/sentry/deletions/defaults/alertrule.py
  src/sentry/incidents/logic.py
  src/sentry/incidents/models.py
  src/sentry/models/scheduledeletion.py
  tests/sentry/deletions/test_alert_rule.py
  tests/sentry/deletions/test_alert_rule_trigger.py
  tests/sentry/deletions/test_alert_rule_trigger_action.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_project_alert_rule_details.py
  tests/sentry/incidents/test_logic.py
Labels: Scope: Backend

#66105 fix(feedback): Pass the project list when editing feedbacks
  static/app/components/feedback/feedbackItem/feedbackActions.tsx
  static/app/components/feedback/feedbackItem/feedbackAssignedTo.tsx
  static/app/components/feedback/list/useBulkEditFeedbacks.tsx
  static/app/components/feedback/useFetchFeedbackData.tsx
  static/app/components/feedback/useMutateFeedback.tsx
Labels: Scope: Frontend

#66043 chore(superuser): No longer enable superuser locally upon login
  src/sentry/auth/superuser.py
Labels: Scope: Backend

#66152 feat(trace): Calculate ts more precisely
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/search/events/constants.py
  src/sentry/search/events/datasets/discover.py
  tests/snuba/api/endpoints/test_organization_events_trace.py
Labels: Scope: Backend

#66018 feat(crons): Ensure that org level monitor endpoints will continue working if there are multiple monitors with the same slug
  src/sentry/monitors/endpoints/base.py
Labels: Scope: Backend

#66115 feat(integration): Send slack message to main
  src/sentry/integrations/slack/utils/notifications.py
Labels: Scope: Backend

#66138 ref(spotlight): respect NO_SPOTLIGHT env variable
  static/app/bootstrap/initializeSdk.tsx
Labels: Scope: Frontend

#66136 feat(trace): implement scroll to error and missing instrumentation
  static/app/views/performance/newTraceDetails/guards.tsx
  static/app/views/performance/newTraceDetails/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.spec.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#66094 chore(staff): Let staff access relocation details
  src/sentry/api/endpoints/relocations/details.py
  tests/sentry/api/endpoints/relocations/test_details.py
Labels: Scope: Backend

#66116 chore(staff): Let staff access relocation pause
  src/sentry/api/endpoints/relocations/pause.py
  tests/sentry/api/endpoints/relocations/test_pause.py
Labels: Scope: Backend

#66117 chore(staff): Let staff access relocation unpause
  src/sentry/api/endpoints/relocations/unpause.py
  tests/sentry/api/endpoints/relocations/test_unpause.py
Labels: Scope: Backend

#66106 chore(staff): Let staff access relocation abort
  src/sentry/api/endpoints/relocations/abort.py
  tests/sentry/api/endpoints/relocations/test_abort.py
Labels: Scope: Backend

#65995 chore(staff): Let staff access proj metrics endpoints
  src/sentry/api/bases/organization.py
  src/sentry/api/endpoints/organization_metrics.py
  tests/sentry/api/endpoints/test_organization_metrics_data.py
  tests/sentry/api/endpoints/test_organization_metrics_details.py
  tests/sentry/api/endpoints/test_organization_metrics_tags.py
Labels: Scope: Backend

#66150 fix(crons): Call append rather than subscripting to it
  src/sentry/monitors/utils.py
  src/sentry/testutils/cases.py
  tests/sentry/monitors/endpoints/test_base_monitor_details.py
Labels: Scope: Backend

#66157 ref(ui): Swap React.Key for our own type in Tab components
  static/app/components/tabs/item.tsx
  static/app/components/tabs/tabList.tsx
Labels: Scope: Frontend

#66120 feat(crons): Make sure checkin attachment endpoints will continue working if there are multiple monitors with the same slug
  src/sentry/monitors/endpoints/base.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_attachment.py
Labels: Scope: Backend

#66154 fix(ai-autofix): Fix request payload + add raise for status
  src/sentry/api/endpoints/group_ai_autofix.py
  tests/sentry/api/endpoints/test_group_ai_autofix.py
Labels: Scope: Backend

#66156 fix(app-start): Default the start type to cold
  static/app/views/starfish/modules/mobile/appStartup.tsx
  static/app/views/starfish/views/appStartup/averageComparisonChart.tsx
  static/app/views/starfish/views/appStartup/countChart.tsx
  static/app/views/starfish/views/appStartup/index.tsx
  static/app/views/starfish/views/appStartup/screenSummary/deviceClassBreakdownBarChart.tsx
  static/app/views/starfish/views/appStartup/screenSummary/eventSamples.tsx
  static/app/views/starfish/views/appStartup/screenSummary/spanOperationTable.tsx
  static/app/views/starfish/views/appStartup/screenSummary/startDurationWidget.tsx
  static/app/views/starfish/views/appStartup/screenSummary/startTypeSelector.tsx
  static/app/views/starfish/views/appStartup/screensTable.tsx
Labels: Scope: Frontend

#66119 feat(feedback): add LazyServiceWrapper for spam detection
  src/sentry/conf/server.py
  src/sentry/feedback/spam/__init__.py
  src/sentry/feedback/spam/base.py
  src/sentry/feedback/spam/stub.py
  tests/sentry/feedback/spam/test_stub.py
Labels: Scope: Backend

#65738 Self Cleaning Activated Alerts
  src/sentry/incidents/models.py
  src/sentry/incidents/subscription_processor.py
  tests/sentry/incidents/test_models.py
  tests/sentry/incidents/test_subscription_processor.py
Labels: Scope: Backend

#66167 fix(alerts): Fix icon type for alert badge style
  static/app/views/projectDetail/projectLatestAlerts.tsx
Labels: Scope: Frontend

#62210 test(hc): Run unit tests in region silo mode by default
  src/sentry/testutils/pytest/sentry.py
  tests/relay_integration/test_integration.py
Labels: Scope: Backend

#66141 feat(metrics): Render summary for custom metrics
  static/app/components/ddm/metricSamplesTable.tsx
  static/app/utils/metrics/useMetricsSamples.tsx
  static/app/views/ddm/widgetDetails.tsx
Labels: Scope: Frontend

#66166 feat(metrics): Render samples as scatter plot
  static/app/components/ddm/metricSamplesTable.tsx
  static/app/utils/metrics/useMetricsSamples.tsx
  static/app/views/ddm/chart/useMetricChartSamples.tsx
  static/app/views/ddm/context.tsx
  static/app/views/ddm/scratchpad.tsx
  static/app/views/ddm/widget.tsx
  static/app/views/ddm/widgetDetails.tsx
Labels: Scope: Frontend

#66187 fix(ai-autofix): Handle duped repos from code mappings + None providers
  src/sentry/api/endpoints/group_ai_autofix.py
  tests/sentry/api/endpoints/test_group_ai_autofix.py
Labels: Scope: Backend

#66196 fix(ddm): Remove duplicated syntax error tooltip
  static/app/views/ddm/formulaParser/formatter.tsx
Labels: Scope: Frontend

#66123 ref(dynamic-sampling): Cleanup sliding window org feature flags
  src/sentry/conf/server.py
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/recalibrate_orgs.py
  src/sentry/features/__init__.py
  tests/sentry/dynamic_sampling/tasks/test_tasks.py
Labels: Scope: Backend

#65970 feat(ddm): summary table sticky header
  static/app/views/ddm/summaryTable.tsx
Labels: Scope: Frontend

#66144 fix(ddm): Fix missing series/totals alignment in the query executor
  src/sentry/sentry_metrics/querying/data_v2/execution.py
  tests/sentry/sentry_metrics/querying/data_v2/test_api.py
Labels: Scope: Backend

#65882 feat(dashboards): metric big number widget
  static/app/components/modals/metricWidgetViewerModal/visualization.tsx
  static/app/views/dashboards/metrics/bigNumber.tsx
  static/app/views/dashboards/metrics/widgetCard.tsx
Labels: Scope: Frontend

#66131 feat(ddm): Implement transformer abstractions in the metrics API
  src/sentry/api/endpoints/organization_metrics.py
  src/sentry/sentry_metrics/querying/data_v2/api.py
  src/sentry/sentry_metrics/querying/data_v2/execution.py
  src/sentry/sentry_metrics/querying/data_v2/parsing.py
  src/sentry/sentry_metrics/querying/data_v2/plan.py
  src/sentry/sentry_metrics/querying/data_v2/preparation.py
  src/sentry/sentry_metrics/querying/data_v2/transformation/__init__.py
  src/sentry/sentry_metrics/querying/data_v2/transformation/base.py
  src/sentry/sentry_metrics/querying/data_v2/transformation/metrics_api.py
  src/sentry/sentry_metrics/querying/types.py
  tests/sentry/sentry_metrics/querying/data_v2/test_api.py
Labels: Scope: Backend

#66197 fix(ddm): summary table overflow
  static/app/views/ddm/summaryTable.tsx
Labels: Scope: Frontend

#66198 chore(ddm): Remove formula feature flag in FE
  static/app/views/ddm/queries.tsx
Labels: Scope: Frontend

#66202 feat(profiling): add options for ingestion of function metrics in the generic metric platform
  src/sentry/options/defaults.py
Labels: Scope: Backend

#66205 feat(ddm): Rename formulas to equations
  static/app/views/ddm/formulaInput.tsx
  static/app/views/ddm/queries.tsx
Labels: Scope: Frontend

#66183 feat(metrics): Add basic search bar for samples list searching
  static/app/components/ddm/metricSamplesTable.tsx
  static/app/views/ddm/widgetDetails.tsx
Labels: Scope: Frontend

#66181 feat(metrics): Add feature flag for metrics sample list search
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#66146 fix: handle redis cluster types correctly
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/dynamic_sampling/rules/utils.py
  src/sentry/dynamic_sampling/tasks/helpers/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/helpers/recalibrate_orgs.py
  src/sentry/dynamic_sampling/tasks/helpers/sliding_window.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/ingest/transaction_clusterer/rules.py
  src/sentry/lang/native/sources.py
  src/sentry/models/files/utils.py
  src/sentry/reprocessing2.py
  src/sentry/sentry_metrics/querying/utils.py
  src/sentry/tasks/check_am2_compatibility.py
  src/sentry/utils/redis.py
  tests/sentry/dynamic_sampling/tasks/test_tasks.py
Labels: Scope: Backend

#66215 ref(profiling): refactor metrics options name
  src/sentry/options/defaults.py
Labels: Scope: Backend

#66206 Clean up `ArtifactBundle(FlatFile)Index`
  migrations_lockfile.txt
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/migrations/0659_artifactbundleindex_cleanup.py
  src/sentry/models/artifactbundle.py
  tests/sentry/debug_files/test_artifact_bundles.py
Labels: Scope: Backend

#66216 Giving the correct type to `apply_modifications_to_frame`
  src/sentry/stacktraces/processing.py
  tests/sentry/grouping/test_enhancer.py
Labels: Scope: Backend

#66225 feat(metrics): Pass missing MRI to search bar
  static/app/components/ddm/metricSamplesTable.tsx
Labels: Scope: Frontend

#66226 fix(metrics): Referrer on samples list query
  static/app/components/ddm/metricSamplesTable.tsx
Labels: Scope: Frontend

#66224 ref(sdk): Bump js sdk version to 7.105.0
  package.json
  static/app/bootstrap/initializeSdk.tsx
  tests/js/setup.ts
  yarn.lock
Labels: Scope: Frontend

#66039 perf: enable dogstatsd buffering
  src/sentry/conf/server.py
  src/sentry/metrics/dogstatsd.py
Labels: Scope: Backend

#66228 fix(profiling): remove early return
  static/app/components/profiling/ProfilingOnboarding/profilingOnboardingSidebar.tsx
Labels: Scope: Frontend

#66182 feat(issues): Remove old guides, archive and semver
  static/app/components/assistant/getGuidesContent.tsx
  static/app/views/issueDetails/actions/index.tsx
  static/app/views/issueDetails/groupEventCarousel.tsx
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/projectDetail/projectFilters.tsx
  static/app/views/releases/list/index.tsx
Labels: Scope: Frontend

#66139 feat(new-trace): Added default bottom position on panel load in trace…
  static/app/views/performance/newTraceDetails/newTraceDetailPanel.tsx
  static/app/views/starfish/components/detailPanel.tsx
Labels: Scope: Frontend

#65793 ref: Rationalize Kafka topic config
  src/sentry/conf/server.py
  src/sentry/conf/types/consumer_definition.py
  src/sentry/conf/types/kafka_definition.py
  src/sentry/consumers/__init__.py
  src/sentry/runner/commands/devserver.py
  tests/sentry/conf/test_consumer_definitions.py
  tests/sentry/conf/test_kafka_definition.py
  tests/sentry/consumers/test_run.py
Labels: Scope: Backend

#66230 feat(profiling): Support vertical scrolling on flamegraph preview
  static/app/components/profiling/flamegraph/flamegraphPreview.tsx
  static/app/components/profiling/flamegraph/interactions/useCanvasZoomOrScroll.tsx
Labels: Scope: Frontend

#66044 feat(daily summary): Slack daily summary notification
  src/sentry/integrations/slack/message_builder/notifications/__init__.py
  src/sentry/integrations/slack/message_builder/notifications/daily_summary.py
  src/sentry/notifications/notifications/daily_summary.py
  src/sentry/tasks/summaries/daily_summary.py
  src/sentry/tasks/summaries/utils.py
  tests/sentry/tasks/test_daily_summary.py
Labels: Scope: Backend

#66221 ref(typing): add types to locking/backends/redis
  pyproject.toml
  src/sentry/incidents/subscription_processor.py
  src/sentry/issues/grouptype.py
  src/sentry/utils/locking/backends/redis.py
Labels: Scope: Backend

#66179 chore(crons): Add feature to disable legacy ingestion endpoints
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_details.py
  src/sentry/monitors/endpoints/monitor_ingest_checkin_index.py
Labels: Scope: Backend

#64516 Debugging the Options module
  src/sentry/options/manager.py
Labels: Scope: Backend, Stale

#66218 test: Write missing tests for useFetchSequentialPages
  static/app/utils/api/useFetchSequentialPages.spec.tsx
  static/app/utils/api/useFetchSequentialPages.tsx
Labels: Scope: Frontend

#66177 perf(projects): optionally emit metrics for killswitch
  src/sentry/api/serializers/models/project.py
  src/sentry/killswitches.py
  src/sentry/tasks/symbolication.py
Labels: Scope: Backend

#65932 feat(crons): Add broken monitor detection feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#65837 conditional Activated AlertRule creation
  src/sentry/incidents/logic.py
  src/sentry/incidents/models.py
  src/sentry/incidents/receivers.py
  src/sentry/incidents/tasks.py
  src/sentry/incidents/utils/constants.py
  src/sentry/incidents/utils/types.py
  src/sentry/models/release.py
  src/sentry/models/releases/release_project.py
  src/sentry/models/releases/util.py
  src/sentry/snuba/models.py
  src/sentry/snuba/subscriptions.py
  src/sentry/snuba/tasks.py
  src/sentry/testutils/factories.py
  tests/sentry/incidents/test_logic.py
  tests/sentry/incidents/test_models.py
  tests/sentry/incidents/test_tasks.py
  tests/sentry/models/releases/test_release_project.py
  tests/sentry/snuba/test_subscriptions.py
  tests/sentry/snuba/test_tasks.py
  tests/snuba/incidents/test_tasks.py
Labels: Scope: Backend

#66045 ref(ui): Convert projectIssueGrouping to FC
  static/app/views/settings/projectIssueGrouping/index.spec.tsx
  static/app/views/settings/projectIssueGrouping/index.tsx
Labels: Scope: Frontend

#66233 fix(ui): Add children to RouteProps
  static/app/types/react-router.d.ts
Labels: Scope: Frontend

#66235 Reapply "perf: enable dogstatsd buffering (#66039)"
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/metrics/dogstatsd.py
Labels: Scope: Backend

#66160 feat(feedback): show widget setup banner if all projects have only crash reports
  static/app/components/feedback/feedbackOnboarding/feedbackWidgetBanner.tsx
  static/app/views/feedback/feedbackListPage.tsx
Labels: Scope: Frontend

#65346 feat(commit-context): Allow all orgs access to suspect commits via blame
  src/sentry/conf/server.py
  tests/sentry/api/serializers/test_organization.py
Labels: Scope: Backend

#66192 feat(autofix): Use active event + invoking user and issue shortid in payload
  src/sentry/api/endpoints/group_ai_autofix.py
  static/app/components/events/aiAutofix/index.spec.tsx
  static/app/components/events/aiAutofix/index.tsx
  static/app/components/events/aiAutofix/useAiAutofix.tsx
  static/app/views/issueDetails/resourcesAndMaybeSolutions.tsx
  tests/sentry/api/endpoints/test_group_ai_autofix.py
Labels: Scope: Frontend, Scope: Backend

#66186 perf(projects): improve get_access_by_project speed by not serializing teams
  src/sentry/api/serializers/models/project.py
Labels: Scope: Backend

#66155 ref(trace): render multiple autogrouped bars
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
Labels: Scope: Frontend

#66066 chore(hybridcloud) Remove shims for getsentry
  src/sentry/integrations/opsgenie/client.py
  src/sentry/integrations/pagerduty/client.py
Labels: Scope: Backend

#66185 fix(crons): Correct cron monitors that have an org id that doesn't match the org of their project
  migrations_lockfile.txt
  src/sentry/migrations/0660_fix_cron_monitor_invalid_orgs.py
  tests/sentry/migrations/test_0660_fix_cron_monitor_invalid_orgs.py
Labels: Scope: Backend

#66231 fix(hybridcloud) Attempt to deliver more messages from deep backlogs
  src/sentry/hybridcloud/tasks/deliver_webhooks.py
  tests/sentry/hybridcloud/tasks/test_deliver_webhooks.py
Labels: Scope: Backend

#66242 ref: Rationalize kafka config - take 2
  src/sentry/conf/server.py
  src/sentry/conf/types/consumer_definition.py
  src/sentry/conf/types/kafka_definition.py
  src/sentry/consumers/__init__.py
  src/sentry/runner/commands/devserver.py
  tests/sentry/conf/test_consumer_definitions.py
  tests/sentry/conf/test_kafka_definition.py
  tests/sentry/consumers/test_run.py
Labels: Scope: Backend

#66193 feat(trace): add loading state for promises
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
Labels: Scope: Frontend

#66121 test(ui): Catch error in hook using try/catch
  static/app/utils/useLocalStorageState.spec.tsx
Labels: Scope: Frontend

#66244 perf: enable datadog buffering
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/metrics/dogstatsd.py
Labels: Scope: Backend

#66251 styles(metrics): Make samples list table a little more compact
  static/app/components/ddm/metricSamplesTable.tsx
  static/app/utils/metrics/useMetricsSamples.tsx
Labels: Scope: Frontend

#66190 feat(trace): add search
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphSearch.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceSearch.tsx
  static/app/views/performance/newTraceDetails/traceSearchInput.tsx
  static/app/views/performance/newTraceDetails/virtualizedViewManager.tsx
Labels: Scope: Frontend

#66173 fix(ui): Cast more objects to ReactNode
  static/app/components/compactSelect/gridList/index.tsx
  static/app/components/compactSelect/listBox/index.tsx
  static/app/components/events/interfaces/request/richHttpContentClippedBoxKeyValueList.tsx
  static/app/components/events/interfaces/spans/newTraceDetailsSpanTree.tsx
  static/app/components/events/interfaces/spans/profilingMeasurements.tsx
  static/app/components/externalIssues/abstractExternalIssueForm.tsx
  static/app/components/hookOrDefault.tsx
  static/app/components/lazyLoad.tsx
  static/app/components/organizations/hybridFilter.tsx
  static/app/components/search/index.tsx
  static/app/components/search/sources/index.tsx
  static/app/components/stories/matrix.tsx
  static/app/components/structuredEventData/index.tsx
  static/app/locale.tsx
  static/app/utils/isRenderFunc.tsx
  static/app/views/admin/options.tsx
  static/app/views/performance/database/noDataMessage.tsx
  static/app/views/projectDetail/projectScoreCards/projectStabilityScoreCard.tsx
  static/app/views/releases/detail/index.tsx
  static/app/views/settings/account/notifications/notificationSettings.tsx
  static/app/views/starfish/index.tsx
Labels: Scope: Frontend

#66238 feat(performance): Allow querying INP scores in metrics and adds some tags to spans indexed
  src/sentry/relay/config/measurements.py
  src/sentry/search/events/constants.py
  src/sentry/search/events/datasets/metrics.py
  src/sentry/testutils/cases.py
  src/sentry/utils/snuba.py
  tests/snuba/api/endpoints/test_organization_events_mep.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#66246 feat(performance): Add organizations:deprecate-fid-from-performance-score feature flag option control
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#66249 feat(performance): Add feature flag control to enable INP in the webvitals ui
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#66257 feat(replay): remove organizations:session-replay-event-linking feature flag
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#66256 fix(metrics-extraction): Fix meta lookup in factory
  src/sentry/api/endpoints/organization_events.py
Labels: Scope: Backend

#66259 fix(metrics-extraction): Allow overriding split decision
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/endpoints/organization_events_stats.py
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#66194 feat(new-trace): Added logic for red errored rows.
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceTree.tsx
Labels: Scope: Frontend

#66253 feat(replay): adds current user to replay in header
  static/app/components/events/eventReplay/constants.tsx
  static/app/components/events/eventReplay/index.tsx
  static/app/components/events/eventReplay/replayClipPreview.tsx
  static/app/components/events/eventReplay/replayPreview.tsx
  static/app/components/events/eventReplay/staticReplayPreview.tsx
  static/app/utils/analytics/replayAnalyticsEvents.tsx
  static/app/views/replays/replayTable/tableCell.tsx
Labels: Scope: Frontend

#66265 fix(crons): Remove db constraint from historical migrations for monitor environment
  src/sentry/migrations/0001_squashed_0484_break_org_member_user_fk.py
  src/sentry/migrations/0361_monitor_environment.py
Labels: Scope: Backend

#66248 feat(backup): Enable shimming deleted fields
  src/sentry/backup/imports.py
Labels: Scope: Backend

#66271 ref: Move topics to new-style of Kafka topic definition
  src/sentry/consumers/__init__.py
Labels: Scope: Backend

#66279 fix(performance): Turn off INP on the browser integration sdk
  static/app/bootstrap/initializeSdk.tsx
Labels: Scope: Frontend

#66284 ref(crons): Remove unused code branch in mark_failed
  src/sentry/monitors/logic/mark_failed.py
Labels: Scope: Backend

#66199 chore(ddm): Remove formula feature flag in BE
  src/sentry/conf/server.py
  src/sentry/features/__init__.py
Labels: Scope: Backend

#66245 ref(dynamic-sampling): Remove capture message for timing
  src/sentry/dynamic_sampling/tasks/utils.py
Labels: Scope: Backend

#66213 feat(ddm): Add support for units normalization in formulas
  src/sentry/sentry_metrics/querying/data_v2/execution.py
  src/sentry/sentry_metrics/querying/data_v2/plan.py
  src/sentry/sentry_metrics/querying/data_v2/preparation.py
  src/sentry/sentry_metrics/querying/data_v2/preparation/__init__.py
  src/sentry/sentry_metrics/querying/data_v2/preparation/base.py
  src/sentry/sentry_metrics/querying/data_v2/preparation/units_normalization.py
  src/sentry/sentry_metrics/querying/data_v2/transformation/__init__.py
  src/sentry/sentry_metrics/querying/data_v2/transformation/metrics_api.py
  src/sentry/sentry_metrics/querying/errors.py
  src/sentry/sentry_metrics/querying/units.py
  src/sentry/sentry_metrics/querying/visitors/__init__.py
  src/sentry/sentry_metrics/querying/visitors/query_expression.py
  tests/sentry/sentry_metrics/querying/data_v2/test_api.py
Labels: Scope: Backend

#66296 fix(ddm): Sample uniformly the list of requested code locations
  src/sentry/api/endpoints/organization_ddm.py
  src/sentry/api/endpoints/organization_metrics.py
  src/sentry/sentry_metrics/querying/errors.py
  src/sentry/sentry_metrics/querying/metadata/metrics_code_locations.py
  tests/sentry/api/endpoints/test_organization_ddm_meta.py
  tests/sentry/api/endpoints/test_organization_metrics_metadata.py
Labels: Scope: Backend

#66207 Clean up `ArtifactBundle(FlatFile)Index`, step 2
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/migrations/0661_artifactbundleindex_cleanup_step2.py
  src/sentry/models/artifactbundle.py
Labels: Scope: Backend

#66132 ref(ddm): Remove normalization logic
  static/app/utils/metrics/normalizeMetricValue.spec.tsx
  static/app/utils/metrics/normalizeMetricValue.tsx
  static/app/views/ddm/chart/chart.tsx
  static/app/views/ddm/chart/types.tsx
  static/app/views/ddm/chart/useFocusArea.tsx
  static/app/views/ddm/chart/useMetricChartSamples.tsx
  static/app/views/ddm/summaryTable.tsx
  static/app/views/ddm/widget.tsx
Labels: Scope: Frontend

#66298 feat(ddm): Allow multiple use case ids to be queried at once and parallelize
  src/sentry/api/endpoints/organization_metrics.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/fields/base.py
  tests/sentry/snuba/metrics/test_datasource.py
Labels: Scope: Backend

#64428 perf: use pipeline for redis rate limiter
  src/sentry/ratelimits/redis.py
  tests/sentry/ratelimits/test_redis_cluster.py
Labels: Scope: Backend

#66232 perf: do not include projects and teams
  src/sentry/api/bases/sentryapps.py
  src/sentry/api/endpoints/auth_index.py
  src/sentry/api/endpoints/integrations/sentry_apps/details.py
  src/sentry/integrations/slack/webhooks/action.py
  src/sentry/integrations/slack/webhooks/event.py
  src/sentry/integrations/utils/scope.py
  src/sentry/pipeline/base.py
  src/sentry/runner/commands/createuser.py
Labels: Scope: Backend

#66301 fix(ddm): Duplicate chart sample ids
  static/app/types/metrics.tsx
  static/app/views/dashboards/metrics/table.tsx
  static/app/views/ddm/chart/useMetricChartSamples.tsx
  static/app/views/ddm/widget.tsx
Labels: Scope: Frontend

#66297 Remove `FileBlob` locking entirely
  src/sentry/models/files/abstractfileblob.py
  src/sentry/models/files/utils.py
  src/sentry/tasks/files.py
  tests/sentry/models/test_file.py
Labels: Scope: Backend

#66254 ref(perf): Introduce `MetricReadout` component
  static/app/utils/discover/fields.tsx
  static/app/views/performance/metricReadout.spec.tsx
  static/app/views/performance/metricReadout.tsx
Labels: Scope: Frontend

#66052 Bump Sentry Python SDK to version 2.0.0a2
  .github/actions/setup-sentry/action.yml
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-dev.txt
  requirements-frozen.txt
  src/sentry/auth/helper.py
  src/sentry/cache/base.py
  src/sentry/data_export/tasks.py
  src/sentry/scim/endpoints/utils.py
  src/sentry/utils/sdk.py
  src/sentry/utils/snuba.py
  src/sentry/web/frontend/organization_integration_setup.py
  tests/relay_integration/test_sdk.py
  tests/sentry/utils/test_sdk.py
Labels: Do Not Merge, Scope: Backend

#66306 fix(metrics-extraction): Fix attribute vs dict lookup
  src/sentry/api/endpoints/organization_events.py
Labels: Scope: Backend

#66304 fix(ddm): Fix units normalization when * and / are used
  src/sentry/sentry_metrics/querying/visitors/query_expression.py
  tests/sentry/sentry_metrics/querying/data_v2/test_api.py
Labels: Scope: Backend

#66273 fix(performance): Fix a typo in the mri of measurements.inp
  src/sentry/search/events/constants.py
Labels: Scope: Backend

#66311 fix(ddm): Handle division by zero
  src/sentry/sentry_metrics/querying/data_v2/transformation/metrics_api.py
  src/sentry/sentry_metrics/querying/data_v2/utils.py
  tests/sentry/sentry_metrics/querying/data_v2/test_api.py
Labels: Scope: Backend

#66309 fix(profiling): Add missing transaction condition for profile digest
  static/app/views/profiling/profileSummary/index.tsx
Labels: Scope: Frontend

#66064 feat(proguard): Add Symbolicator.process_jvm method
  src/sentry/lang/native/symbolicator.py
Labels: Scope: Backend

#66295 fix(hybridcloud) Add visiblity to region configuration
  src/sentry/types/region.py
  src/sentry/web/client_config.py
  tests/sentry/types/test_region.py
  tests/sentry/web/test_client_config.py
Labels: Scope: Backend

#66291 fix(hybrid-cloud): Prevent API gateway from resolving redirects
  src/sentry/hybridcloud/apigateway/proxy.py
  src/sentry/testutils/helpers/apigateway.py
  tests/sentry/hybridcloud/apigateway/test_apigateway.py
Labels: Scope: Backend

#66318 fix padding
  static/app/views/performance/browser/resources/resourceView/index.tsx
Labels: Scope: Frontend

#66317 feat(sdk): bumps js sdk to 7.103.0 and updates browsertracingintegration
  package.json
  static/app/bootstrap/initializeSdk.tsx
  tests/js/setup.ts
  yarn.lock
Labels: Scope: Frontend

#66178 feat(indexed-spans): Support profile.id on indexed spans
  src/sentry/utils/snuba.py
  tests/sentry/search/events/builder/test_spans_indexed.py
Labels: Scope: Backend

#66011 fix(perf): Fix HTTP widget documentation link
  static/app/utils/docs.tsx
  static/app/views/performance/landing/widgets/components/selectableList.tsx
  static/app/views/performance/transactionDetails/quickTraceMeta.tsx
Labels: Scope: Frontend

#66168 feat(processing) Move redis operations in reprocessing to servicewrapper
  pyproject.toml
  src/sentry/conf/server.py
  src/sentry/eventstore/reprocessing/__init__.py
  src/sentry/eventstore/reprocessing/base.py
  src/sentry/eventstore/reprocessing/redis.py
  src/sentry/options/defaults.py
  src/sentry/reprocessing2.py
  tests/sentry/tasks/test_reprocessing2.py
Labels: Scope: Backend

#65666 ref(metrics): Change aggregation options to be a dictionary
  src/sentry/sentry_metrics/aggregation_option_registry.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  tests/sentry/sentry_metrics/test_batch.py
  tests/sentry/sentry_metrics/test_gen_metrics_multiprocess_steps.py
Labels: Scope: Backend

#66250 ref(crons): Remove legacy fingerprint generation
  src/sentry/monitors/logic/mark_failed.py
  src/sentry/monitors/models.py
  tests/sentry/monitors/logic/test_mark_ok.py
Labels: Scope: Backend

#66261 fix(daily summary): Fix subquery, exit early if no users
  src/sentry/tasks/summaries/daily_summary.py
Labels: Scope: Backend

#66283 ref: Move more code to the new way of defining kafka topics and overrides
  src/sentry/conf/server.py
  src/sentry/conf/types/kafka_definition.py
  src/sentry/conf/types/topic_definition.py
  src/sentry/consumers/__init__.py
  src/sentry/eventstream/kafka/backend.py
  src/sentry/issues/attributes.py
  src/sentry/issues/producer.py
  src/sentry/monitors/tasks.py
  src/sentry/replays/lib/kafka.py
  src/sentry/replays/usecases/ingest/dom_index.py
  src/sentry/runner/commands/devserver.py
  src/sentry/sentry_metrics/configuration.py
  src/sentry/sentry_metrics/consumers/indexer/multiprocess.py
  src/sentry/usage_accountant/accountant.py
  src/sentry/utils/kafka_config.py
  src/sentry/utils/outcomes.py
  tests/sentry/utils/test_outcomes.py
  tests/snuba/incidents/test_tasks.py
Labels: Scope: Backend

#66275 feat(performance): Updates useIndexedSpans to accept an optional fields array
  static/app/views/starfish/components/spanDescription.tsx
  static/app/views/starfish/queries/useFullSpanFromTrace.tsx
  static/app/views/starfish/queries/useIndexedSpans.tsx
Labels: Scope: Frontend

#66331 ref(feedback): toggles are false by default
  static/app/components/feedback/feedbackOnboarding/feedbackOnboardingLayout.tsx
Labels: Scope: Frontend

#66272 feat(issue-priority): Use 'Med' label in priority pills
  static/app/components/group/groupPriority.tsx
  static/app/components/issues/groupListHeader.tsx
  static/app/components/stream/group.spec.tsx
  static/app/components/stream/group.tsx
  static/app/views/issueList/actions/headers.tsx
Labels: Scope: Frontend

#66287 ref: Move query subscriptions over to new-style kafka config
  src/sentry/consumers/__init__.py
  src/sentry/snuba/query_subscriptions/constants.py
  src/sentry/snuba/query_subscriptions/run.py
  tests/sentry/snuba/test_query_subscription_consumer.py
Labels: Scope: Backend

#66341 styles(metrics): Use disabled button for no profile
  static/app/components/ddm/metricSamplesTable.tsx
Labels: Scope: Frontend

#66093 ref(issues): Add typing to issue status and issue platform files
  pyproject.toml
  src/sentry/api/helpers/group_index/update.py
  src/sentry/issues/occurrence_consumer.py
  src/sentry/issues/status_change.py
  src/sentry/issues/status_change_consumer.py
  tests/sentry/issues/test_occurrence_consumer.py
  tests/sentry/issues/test_status_change.py
  tests/sentry/issues/test_status_change_consumer.py
Labels: Scope: Backend

#66330 ref(feedback): update links and system default for onboarding
  static/app/components/onboarding/gettingStartedDoc/utils/feedbackOnboarding.tsx
  static/app/gettingStartedDocs/capacitor/capacitor.tsx
  static/app/gettingStartedDocs/electron/electron.tsx
  static/app/gettingStartedDocs/javascript/angular.tsx
  static/app/gettingStartedDocs/javascript/astro.tsx
  static/app/gettingStartedDocs/javascript/ember.tsx
  static/app/gettingStartedDocs/javascript/gatsby.tsx
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/react.tsx
  static/app/gettingStartedDocs/javascript/remix.tsx
  static/app/gettingStartedDocs/javascript/svelte.tsx
  static/app/gettingStartedDocs/javascript/sveltekit.tsx
  static/app/gettingStartedDocs/javascript/vue.tsx
Labels: Scope: Frontend

#66345 chore(commit-context): Remove unused feature flag
  src/sentry/conf/server.py
  src/sentry/features/permanent.py
  src/sentry/tasks/post_process.py
  tests/sentry/api/endpoints/test_event_committers.py
  tests/sentry/api/serializers/test_organization.py
  tests/sentry/notifications/utils/test_participants.py
  tests/sentry/tasks/test_post_process.py
  tests/sentry/utils/test_committers.py
Labels: Scope: Backend

#66328 ref(crons): Remove usage of last_state_change
  src/sentry/monitors/logic/mark_failed.py
  src/sentry/monitors/logic/mark_ok.py
  tests/sentry/monitors/logic/test_mark_failed.py
  tests/sentry/monitors/logic/test_mark_ok.py
Labels: Scope: Backend

#66266 fix(staff): Set access by calling parent method before checking staff
  src/sentry/api/permissions.py
Labels: Scope: Backend
