Repository getsentry/sentry, pull requests merged in 2024-06, with the labels that each got.

#71493 feat(metrics): Enable gauge alerts
  static/app/utils/metrics/index.tsx
  static/app/views/alerts/rules/metric/mriField.tsx
  static/app/views/metrics/metricQueryContextMenu.tsx
Labels: Scope: Frontend

#71900 feat(onboarding): Add go-fiber BE
  src/sentry/models/project.py
  src/sentry/utils/platform_categories.py
Labels: Scope: Backend

#71486 chore(options): Remove unused options
  src/sentry/options/defaults.py
  tests/sentry/sentry_metrics/test_gen_metrics_multiprocess_steps.py
Labels: Scope: Backend

#71865 feat(insights): Improve Insights sidebar upsells
  static/app/components/sidebar/sidebarItem.tsx
Labels: Scope: Frontend

#71876 ref: don't hold a django transaction while doing a bunch of redis operations
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
Labels: Scope: Backend

#71872 ref: remove safe_execute in send_confirmation_notification
  src/sentry/api/endpoints/project_rules.py
Labels: Scope: Backend

#71902 fix(related_issues): Use noticeable background color on hover
  static/app/views/issueDetails/traceTimeline/traceIssue.tsx
Labels: Scope: Frontend

#71885 feat(chartcuterie): Revert the revert of refactory
  src/sentry/integrations/issue_alert_image_builder.py
  src/sentry/integrations/slack/message_builder/image_block_builder.py
  tests/acceptance/chartcuterie/test_image_block_builder.py
Labels: Scope: Backend

#71750 chore(perf): Add referrer to span metrics table
  static/app/views/performance/transactionSummary/transactionSpans/spanMetricsTable.tsx
Labels: Scope: Frontend

#71903 ref: use relay image from artifact registry
  src/sentry/conf/server.py
  src/sentry/testutils/pytest/relay.py
Labels: Scope: Backend

#71910 feat(sidebar): expand nested items if parent has no link
  static/app/components/sidebar/sidebarAccordion.tsx
  static/app/components/sidebar/sidebarItem.tsx
Labels: Scope: Frontend

#71828 feat(features) Allow defining default value for features during registration
  src/sentry/conf/server.py
  src/sentry/features/manager.py
  src/sentry/features/temporary.py
  tests/sentry/features/test_manager.py
Labels: Scope: Backend

#71840 ref(record-backfill): Query snuba per group
  src/sentry/tasks/backfill_seer_grouping_records.py
  tests/sentry/tasks/test_backfill_seer_grouping_records.py
Labels: Scope: Backend

#71909 feat(query-builder): Improve focus management after new tokens are created
  static/app/components/searchQueryBuilder/context.tsx
  static/app/components/searchQueryBuilder/filter.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/input.tsx
  static/app/components/searchQueryBuilder/tokenizedQueryGrid.tsx
  static/app/components/searchQueryBuilder/types.tsx
  static/app/components/searchQueryBuilder/useQueryBuilderState.tsx
Labels: Scope: Frontend

#71915 fix(query-builder): Some minor behavior fixes when editing filter values
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/valueCombobox.tsx
Labels: Scope: Frontend

#71874 ref: don't hold a transaction while sending user report notifications
  src/sentry/tasks/user_report.py
Labels: Scope: Backend

#71878 ref: avoid holding a django transaction while sending notifications
  src/sentry/notifications/notifications/base.py
Labels: Scope: Backend

#71868 ref(rules): Make an enum for trigger action methods
  src/sentry/incidents/models/alert_rule.py
  src/sentry/incidents/subscription_processor.py
  src/sentry/incidents/tasks.py
Labels: Scope: Backend

#71886 nit(slack): updated github name in slack threads
  src/sentry/integrations/slack/threads/activity_notifications.py
  tests/sentry/integrations/slack/threads/activity_notifications/test_external_issue_created_activity_notification.py
Labels: Scope: Backend

#71917 ref(crons): Advise users to enable monitors after editing subscription settings
  static/app/views/monitors/components/processingErrors/processingErrorItem.tsx
  static/app/views/monitors/components/processingErrors/processingErrorTitle.tsx
Labels: Scope: Frontend

#71921 fix(insights): Use module URL helper in special widgets
  static/app/views/performance/landing/widgets/widgets/mobileReleaseComparisonListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/performanceScoreListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/performanceScoreWidget.tsx
Labels: Scope: Frontend

#71925 docs: Improve the <Confirm> story so it shows what you clicked
  static/app/components/confirm.stories.tsx
Labels: Scope: Frontend

#71926 fix: Improve "Add Member" dropdown alignment on Team Members settings page
  static/app/views/settings/organizationTeams/teamMembers.tsx
Labels: Scope: Frontend

#71538 ref(insights): create useSpansIndexed
  static/app/components/events/interfaces/llm-monitoring/llmMonitoringSection.tsx
  static/app/views/llmMonitoring/pipelineSpansTable.tsx
  static/app/views/performance/browser/webVitals/utils/queries/useInpSpanSamplesWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/types.tsx
  static/app/views/performance/cache/samplePanel/samplePanel.tsx
  static/app/views/performance/cache/tables/cacheHitMissCell.tsx
  static/app/views/performance/cache/tables/spanSamplesTable.tsx
  static/app/views/performance/http/data/useSpanSamples.spec.tsx
  static/app/views/performance/http/data/useSpanSamples.tsx
  static/app/views/performance/http/httpSamplesPanel.tsx
  static/app/views/performance/http/tables/spanSamplesTable.tsx
  static/app/views/performance/queues/destinationSummary/messageSpanSamplesTable.tsx
  static/app/views/performance/traces/fieldRenderers.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanSummary/spanSummaryTable.tsx
  static/app/views/starfish/components/spanDescription.tsx
  static/app/views/starfish/queries/useDiscover.spec.tsx
  static/app/views/starfish/queries/useDiscover.ts
  static/app/views/starfish/queries/useFullSpanFromTrace.tsx
  static/app/views/starfish/queries/useIndexedSpans.spec.tsx
  static/app/views/starfish/queries/useIndexedSpans.tsx
  static/app/views/starfish/types.tsx
  static/app/views/starfish/views/spanSummaryPage/sampleList/durationChart/useSampleScatterPlotSeries.tsx
Labels: Scope: Frontend

#71918 ref(feedback): remove refs to feedback.ingest-inline-attachments option
  src/sentry/options/defaults.py
  src/sentry/relay/globalconfig.py
  tests/sentry/api/endpoints/test_relay_globalconfig_v3.py
Labels: Scope: Backend

#71927 fix(similarity): dont let non elegible events acrrue rate limits
  src/sentry/grouping/ingest/seer.py
Labels: Scope: Backend

#71932 ref: Move <Flex> into components/container/
  static/app/components/container/flex.tsx
  static/app/components/events/eventReplay/replayClipPreviewPlayer.tsx
  static/app/components/events/eventReplay/replayPreview.tsx
  static/app/components/feedback/feedbackItem/feedbackActions.tsx
  static/app/components/feedback/feedbackItem/feedbackItemHeader.tsx
  static/app/components/feedback/feedbackItem/feedbackItemUsername.tsx
  static/app/components/feedback/feedbackItem/feedbackShortId.tsx
  static/app/components/feedback/feedbackItem/messageSection.tsx
  static/app/components/feedback/list/feedbackListBulkSelection.tsx
  static/app/components/feedback/list/feedbackListItem.tsx
  static/app/components/feedback/list/mailboxPicker.tsx
  static/app/components/metrics/metricSamplesTable.tsx
  static/app/components/profiling/aggregateFlamegraphPanel.tsx
  static/app/components/profiling/flamegraph/deprecatedAggregateFlamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphContextMenu.tsx
  static/app/components/profiling/functionsMiniGrid.tsx
  static/app/components/profiling/profilingTransactionHovercard.tsx
  static/app/components/replays/breadcrumbs/breadcrumbItem.tsx
  static/app/components/replays/breadcrumbs/replayComparisonModal.tsx
  static/app/components/sidebar/sidebarItem.tsx
  static/app/stories/storyBook.tsx
  static/app/styles/typography.stories.tsx
  static/app/views/performance/mobile/screenload/screens/platformSelector.tsx
  static/app/views/profiling/landing/profilingSlowestTransactionsPanel.tsx
  static/app/views/replays/deadRageClick/deadRageSelectorCards.tsx
  static/app/views/replays/detail/accessibility/accessibilityRefetchBanner.tsx
  static/app/views/replays/detail/network/details/sections.tsx
  static/app/views/replays/details.tsx
  static/app/views/settings/organizationTeams/teamMembers.tsx
  static/app/views/stories/storyHeader.tsx
Labels: Scope: Frontend

#71929 feat(insights): show is new badge insights/explore
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/sidebarItem.tsx
Labels: Scope: Frontend

#71783 feat(hybridcloud) Add method to fetch sentryapp installs with caching
  src/sentry/db/models/outboxes.py
  src/sentry/models/integrations/sentry_app.py
  src/sentry/models/integrations/sentry_app_installation.py
  src/sentry/receivers/outbox/control.py
  src/sentry/services/hybrid_cloud/app/service.py
  src/sentry/tasks/sentry_apps.py
  tests/sentry/models/test_sentryapp.py
  tests/sentry/models/test_sentryappinstallation.py
  tests/sentry/receivers/outbox/test_control.py
Labels: Scope: Backend

#71934 ref: Move getPeriod() into utils/duration/
  static/app/actionCreators/events.tsx
  static/app/utils/duration/getPeriod.spec.tsx
  static/app/utils/duration/getPeriod.tsx
  static/app/views/performance/browser/webVitals/components/pageOverviewSidebar.tsx
  static/app/views/projectDetail/charts/projectSessionsAnrRequest.tsx
  static/app/views/projectDetail/charts/projectSessionsChartRequest.tsx
  static/app/views/projectDetail/projectScoreCards/projectAnrScoreCard.tsx
  static/app/views/projectDetail/projectScoreCards/projectApdexScoreCard.tsx
  static/app/views/projectDetail/projectScoreCards/projectStabilityScoreCard.tsx
  static/app/views/projectDetail/projectScoreCards/projectVelocityScoreCard.tsx
Labels: Scope: Frontend

#71880 ref: remove _with_transaction=... from safe_execute (always False)
  src/sentry/api/endpoints/project_rule_actions.py
  src/sentry/api/serializers/models/group.py
  src/sentry/api/serializers/models/group_stream.py
  src/sentry/datascrubbing.py
  src/sentry/event_manager.py
  src/sentry/grouping/result.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/integrations/mixins/issues.py
  src/sentry/interfaces/base.py
  src/sentry/notifications/notifications/base.py
  src/sentry/plugins/base/manager.py
  src/sentry/plugins/bases/issue.py
  src/sentry/plugins/bases/issue2.py
  src/sentry/rules/__init__.py
  src/sentry/rules/actions/notify_event.py
  src/sentry/rules/actions/notify_event_service.py
  src/sentry/rules/processing/delayed_processing.py
  src/sentry/rules/processing/processor.py
  src/sentry/stacktraces/processing.py
  src/sentry/tasks/activity.py
  src/sentry/tasks/post_process.py
  src/sentry/tasks/store.py
  src/sentry/tasks/user_report.py
  src/sentry/templatetags/sentry_plugins.py
  src/sentry/utils/email/message_builder.py
  src/sentry/utils/safe.py
Labels: Scope: Backend

#71936 ref: Move getExactDuration() into utils/duration/
  static/app/components/duration.tsx
  static/app/utils/duration/getExactDuration.spec.tsx
  static/app/utils/duration/getExactDuration.tsx
  static/app/utils/formatters.spec.tsx
  static/app/utils/formatters.tsx
  static/app/views/settings/project/projectKeys/details/keyRateLimitsForm.tsx
Labels: Scope: Frontend

#71821 feat(insights): Granular frontend feature flags
  static/app/components/events/interfaces/spans/newTraceDetailsSpanDetails.tsx
  static/app/components/events/interfaces/spans/spanDetail.spec.tsx
  static/app/components/events/interfaces/spans/spanSummaryButton.tsx
  static/app/components/sidebar/index.tsx
  static/app/views/performance/browser/resources/index.spec.tsx
  static/app/views/performance/browser/resources/index.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/index.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.spec.tsx
  static/app/views/performance/browser/resources/resourceView/index.tsx
  static/app/views/performance/browser/webVitals/pageOverview.spec.tsx
  static/app/views/performance/browser/webVitals/pageOverview.tsx
  static/app/views/performance/browser/webVitals/webVitalsLandingPage.spec.tsx
  static/app/views/performance/browser/webVitals/webVitalsLandingPage.tsx
  static/app/views/performance/cache/cacheLandingPage.tsx
  static/app/views/performance/database/databaseLandingPage.tsx
  static/app/views/performance/database/databaseSpanSummaryPage.tsx
  static/app/views/performance/http/httpDomainSummaryPage.tsx
  static/app/views/performance/http/httpLandingPage.tsx
  static/app/views/performance/landing/views/allTransactionsView.tsx
  static/app/views/performance/landing/views/backendView.tsx
  static/app/views/performance/landing/views/frontendOtherView.tsx
  static/app/views/performance/landing/views/mobileView.tsx
  static/app/views/performance/mobile/appStarts/index.tsx
  static/app/views/performance/mobile/appStarts/screenSummary/index.tsx
  static/app/views/performance/mobile/screenload/index.spec.tsx
  static/app/views/performance/mobile/screenload/index.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/index.spec.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/index.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/table.spec.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/table.tsx
  static/app/views/performance/mobile/ui/index.tsx
  static/app/views/performance/mobile/ui/screenSummary/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/description.tsx
  static/app/views/performance/queues/destinationSummary/destinationSummaryPage.spec.tsx
  static/app/views/performance/queues/destinationSummary/destinationSummaryPage.tsx
  static/app/views/performance/queues/queuesLandingPage.spec.tsx
  static/app/views/performance/queues/queuesLandingPage.tsx
  static/app/views/performance/transactionSummary/aggregateSpanWaterfall/index.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/transactionSpans/content.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#71688 feat(data-consent): Backend changes for data consent on org creation
  src/sentry/analytics/events/__init__.py
  src/sentry/analytics/events/data_consent_org_creation.py
  src/sentry/api/endpoints/organization_index.py
  tests/sentry/api/endpoints/test_organization_index.py
Labels: Scope: Backend

#71941 test(ui): Project teams test fails locally
  static/app/views/settings/project/projectTeams.spec.tsx
Labels: Scope: Frontend

#71702 feat(crons): Allow for deleting processing error by type
  src/sentry/monitors/processing_errors/manager.py
  tests/sentry/monitors/processing_errors/test_manager.py
Labels: Scope: Backend

#71804 feat(crons): Show detailed check-in payload hovercard for processing errors
  static/app/views/monitors/components/processingErrors/monitorProcessingErrors.tsx
Labels: Scope: Frontend

#71787 feat(self-hosted): Errors only self-hosted sidebar
  static/app/components/sidebar/index.spec.tsx
  static/app/components/sidebar/index.tsx
  static/app/types/system.tsx
  tests/js/fixtures/config.ts
Labels: Scope: Frontend

#71913 ref(crons): Ignore in progress check-in coming in after OK, ERROR
  src/sentry/monitors/consumers/monitor_consumer.py
  tests/sentry/monitors/consumers/test_monitor_consumer.py
Labels: Scope: Backend

#71704 feat(perf): Add span searchbar to Spans tab
  static/app/views/performance/transactionSummary/transactionSpans/content.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanMetricsTable.tsx
Labels: Scope: Frontend

#71948 feat(self-hosted): Errors only self-hosted sidebar
  static/app/components/sidebar/index.spec.tsx
  static/app/components/sidebar/index.tsx
  static/app/types/system.tsx
  tests/js/fixtures/config.ts
Labels: Scope: Frontend

#71946 feat(query-builder): Add alias for the 'is' key
  static/app/components/searchQueryBuilder/filter.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/input.tsx
  static/app/components/searchQueryBuilder/utils.tsx
  static/app/stores/tagStore.tsx
  static/app/types/group.tsx
Labels: Scope: Frontend

#71286 chore(api): Publish `OrganizationReleaseDetailsEndpoint`
  api-docs/openapi.json
  api-docs/paths/releases/organization-release.json
  src/sentry/api/endpoints/organization_release_details.py
  src/sentry/api/serializers/models/release.py
  src/sentry/api/serializers/release_details_types.py
  src/sentry/api/serializers/rest_framework/release.py
  src/sentry/api/serializers/types.py
  src/sentry/apidocs/examples/organization_examples.py
  src/sentry/apidocs/parameters.py
Labels: Scope: Backend

#71958 chore(api): Set two APIs to private
  src/sentry/api/endpoints/team_stats.py
  src/sentry/scim/endpoints/schemas.py
Labels: Scope: Backend

#71959 ref: Move valueIsEqual() into utils/object/ and replace arrayIsEqual
  static/app/actionCreators/pageFilters.tsx
  static/app/components/deprecatedAssigneeSelectorDropdown.tsx
  static/app/stores/pageFiltersStore.tsx
  static/app/utils.tsx
  static/app/utils/object/valueIsEqual.spec.tsx
  static/app/utils/object/valueIsEqual.tsx
  static/app/utils/utils.spec.tsx
  static/app/views/discover/resultsChart.tsx
Labels: Scope: Frontend

#71960 ref: Move parsePeriodToHours() into utils/duration/
  static/app/components/charts/intervalSelector.tsx
  static/app/components/charts/utils.tsx
  static/app/components/performance/searchBar.tsx
  static/app/components/timeRangeSelector/index.tsx
  static/app/utils/dates.spec.tsx
  static/app/utils/dates.tsx
  static/app/utils/duration/parsePeriodToHours.spec.tsx
  static/app/utils/duration/parsePeriodToHours.tsx
  static/app/utils/metrics/useMetricsQuery.tsx
  static/app/utils/performance/contexts/metricsCardinality.tsx
  static/app/views/alerts/rules/metric/constants.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
  static/app/views/dashboards/utils.tsx
  static/app/views/metrics/createAlertModal.tsx
  static/app/views/metrics/utils/useMetricsIntervalParam.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/app/views/organizationStats/usageChart/utils.tsx
  static/app/views/organizationStats/usageStatsOrg.tsx
  static/app/views/organizationStats/utils.tsx
  static/app/views/performance/trends/changeExplorerUtils/functionsList.tsx
  static/app/views/performance/trends/changeExplorerUtils/metricsTable.tsx
  static/app/views/performance/trends/changeExplorerUtils/spansList.tsx
Labels: Scope: Frontend

#71961 ref: Move formatSecondsToClock & parseClockToSeconds into utils/duration/
  static/app/components/replays/utils.tsx
  static/app/utils/duration/formatDuration.tsx
  static/app/utils/duration/formatSecondsToClock.spec.tsx
  static/app/utils/duration/formatSecondsToClock.tsx
  static/app/utils/duration/parseClockToSeconds.spec.tsx
  static/app/utils/duration/parseClockToSeconds.tsx
  static/app/utils/formatters.spec.tsx
  static/app/utils/formatters.tsx
  static/app/utils/replays/hooks/useShareReplayAtTimestamp.tsx
Labels: Scope: Frontend

#71963 ref: Move trimSlug() & middleEllipsis() into utils/string/
  static/app/components/organizations/environmentPageFilter/trigger.tsx
  static/app/components/organizations/projectPageFilter/trigger.tsx
  static/app/utils/middleEllipsis.spec.tsx
  static/app/utils/string/middleEllipsis.tsx
  static/app/utils/string/trimSlug.spec.tsx
  static/app/utils/string/trimSlug.tsx
  static/app/views/alerts/rules/metric/mriField.tsx
  static/app/views/metrics/customMetricsEventData.tsx
  static/app/views/metrics/pageHeaderActions.tsx
  static/app/views/metrics/queryBuilder.tsx
  static/app/views/settings/projectMetrics/projectMetrics.tsx
Labels: Scope: Frontend

#71957 chore(billing): Update slack test helpers
  src/sentry/testutils/helpers/slack.py
Labels: Scope: Backend

#71968 feat(metrics): Big number equations
  static/app/components/modals/metricWidgetViewerModal.tsx
  static/app/components/modals/metricWidgetViewerModal/queries.tsx
  static/app/views/dashboards/metrics/utils.tsx
Labels: Scope: Frontend

#71897 Add Go Fiber documentation
  static/app/components/onboarding/frameworkSuggestionModal.tsx
  static/app/data/platformCategories.tsx
  static/app/data/platformPickerCategories.tsx
  static/app/data/platforms.tsx
  static/app/gettingStartedDocs/go/fiber.spec.tsx
  static/app/gettingStartedDocs/go/fiber.tsx
  static/app/types/project.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#71977 Fix reprocessing not finishing with two Activities
  src/sentry/tasks/reprocessing2.py
  tests/sentry/tasks/test_reprocessing2.py
Labels: Scope: Backend

#67576 feat: PowerShell support (frontend)
  README.md
  static/app/components/events/interfaces/frame/usePrismTokensSourceContext.tsx
  static/app/data/platformCategories.tsx
  static/app/data/platformPickerCategories.tsx
  static/app/data/platforms.tsx
  static/app/gettingStartedDocs/powershell/powershell.spec.tsx
  static/app/gettingStartedDocs/powershell/powershell.tsx
  static/app/types/project.tsx
  static/app/utils/docs.tsx
  static/app/utils/fileExtension.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#71974 Update Sentry SDK to version 2.4.0
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#71982 chore(stats): remove metric hour category
  src/sentry/api/endpoints/organization_stats_v2.py
  src/sentry/sentry_metrics/querying/stats.py
  tests/snuba/api/endpoints/test_organization_stats_v2.py
Labels: Scope: Backend

#71920 fix(.NET): Txn snippet for ASP.NET wizard
  static/app/gettingStartedDocs/dotnet/aspnet.tsx
Labels: Scope: Frontend

#71652 perf: move sentry/backup to orjson
  src/sentry/backup/crypto.py
  src/sentry/backup/imports.py
  src/sentry/backup/sanitize.py
  tests/sentry/backup/test_dependencies.py
  tests/sentry/backup/test_imports.py
  tests/sentry/backup/test_releases.py
  tests/sentry/backup/test_rpc.py
  tests/sentry/backup/test_sanitize.py
  tests/sentry/backup/test_snapshots.py
  tests/sentry/backup/test_validate.py
Labels: Scope: Backend

#71985 fix(dashboards): hide add widget card behind feature flag
  static/app/views/dashboards/addWidget.tsx
Labels: Scope: Frontend

#71986 fix(onboarding): Escape newline in go-fiber snippet
  static/app/gettingStartedDocs/go/fiber.tsx
Labels: Scope: Frontend

#71939 ref: remove expected_errors= from safe_execute
  src/sentry/tasks/post_process.py
  src/sentry/utils/safe.py
  tests/sentry/utils/test_safe.py
Labels: Scope: Backend

#65075 ref: upgrade sentry to python 3.12
  .github/actions/setup-sentry/action.yml
  .github/workflows/backend.yml
  .github/workflows/development-environment.yml
  .github/workflows/pre-commit.yml
  .github/workflows/react-to-product-owners-yml-changes.yml
  .github/workflows/self-hosted.yml
  .python-version
  devenv/config.ini
  pyproject.toml
  requirements-dev-frozen.txt
  requirements-frozen.txt
  scripts/lib.sh
  self-hosted/Dockerfile
  tests/sentry/test_devimports.py
Labels: Scope: Backend

#71904 feat(insights): rename Processing Time column to Span Duration
  static/app/views/performance/queues/destinationSummary/messageSpanSamplesTable.spec.tsx
  static/app/views/performance/queues/destinationSummary/messageSpanSamplesTable.tsx
Labels: Scope: Frontend

#71938 chore(hybridcloud) Introduce caching to installation reads
  src/sentry/options/defaults.py
  src/sentry/tasks/sentry_apps.py
  tests/sentry/tasks/test_sentry_apps.py
Labels: Scope: Backend

#71922 chore(features) Remove redundant feature defaults
  src/sentry/conf/server.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#72001 feat(insights): Granular frontend feature flags II
  static/app/components/events/interfaces/spans/newTraceDetailsSpanDetails.tsx
  static/app/components/events/interfaces/spans/spanDetail.spec.tsx
  static/app/components/events/interfaces/spans/spanSummaryButton.tsx
  static/app/components/sidebar/index.tsx
  static/app/views/performance/browser/resources/index.spec.tsx
  static/app/views/performance/browser/resources/index.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/index.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/sampleImages.spec.tsx
  static/app/views/performance/browser/resources/resourceView/index.tsx
  static/app/views/performance/browser/webVitals/pageOverview.spec.tsx
  static/app/views/performance/browser/webVitals/pageOverview.tsx
  static/app/views/performance/browser/webVitals/webVitalsLandingPage.spec.tsx
  static/app/views/performance/browser/webVitals/webVitalsLandingPage.tsx
  static/app/views/performance/cache/cacheLandingPage.tsx
  static/app/views/performance/database/databaseLandingPage.tsx
  static/app/views/performance/database/databaseSpanSummaryPage.tsx
  static/app/views/performance/http/httpDomainSummaryPage.tsx
  static/app/views/performance/http/httpLandingPage.tsx
  static/app/views/performance/landing/views/allTransactionsView.tsx
  static/app/views/performance/landing/views/backendView.tsx
  static/app/views/performance/landing/views/frontendOtherView.tsx
  static/app/views/performance/landing/views/mobileView.tsx
  static/app/views/performance/mobile/appStarts/index.tsx
  static/app/views/performance/mobile/appStarts/screenSummary/index.tsx
  static/app/views/performance/mobile/screenload/index.spec.tsx
  static/app/views/performance/mobile/screenload/index.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/index.spec.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/index.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/table.spec.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/table.tsx
  static/app/views/performance/mobile/ui/index.tsx
  static/app/views/performance/mobile/ui/screenSummary/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/description.tsx
  static/app/views/performance/queues/destinationSummary/destinationSummaryPage.spec.tsx
  static/app/views/performance/queues/destinationSummary/destinationSummaryPage.tsx
  static/app/views/performance/queues/queuesLandingPage.spec.tsx
  static/app/views/performance/queues/queuesLandingPage.tsx
  static/app/views/performance/transactionSummary/aggregateSpanWaterfall/index.tsx
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/transactionSpans/content.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#72002 Avoid creating new `RawEvent`s and `ProcessingIssue`s
  src/sentry/lang/java/plugin.py
  src/sentry/lang/native/error.py
  src/sentry/models/debugfile.py
  src/sentry/receivers/__init__.py
  src/sentry/receivers/reprocessing.py
  src/sentry/reprocessing.py
  src/sentry/tasks/assemble.py
  src/sentry/tasks/store.py
  tests/sentry/tasks/test_reprocessing2.py
Labels: Scope: Backend

#71823 feat(insights): Granular backend feature flags
  src/sentry/api/endpoints/organization_event_details.py
  src/sentry/api/endpoints/organization_spans_aggregation.py
  tests/snuba/api/endpoints/test_organization_event_details.py
  tests/snuba/api/endpoints/test_organization_spans_aggregation.py
Labels: Scope: Backend

#71796 feat(replay-new-trace): Adding replay timestamp indicators.
  static/app/components/replays/replayContext.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/traceTreeNodeDetails.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/traceDrawer.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/performance/newTraceDetails/traceRenderers/virtualizedViewManager.spec.tsx
  static/app/views/performance/newTraceDetails/traceRenderers/virtualizedViewManager.tsx
  static/app/views/replays/detail/layout/focusArea.tsx
  static/app/views/replays/detail/layout/index.tsx
  static/app/views/replays/detail/trace/index.tsx
  static/app/views/replays/detail/trace/trace.tsx
  static/app/views/replays/details.tsx
Labels: Scope: Frontend

#72003 ref: make safe_execute typesafe
  src/sentry/api/serializers/models/group_stream.py
  src/sentry/plugins/bases/issue2.py
  src/sentry/reprocessing2.py
  src/sentry/rules/processing/delayed_processing.py
  src/sentry/rules/processing/processor.py
  src/sentry/utils/safe.py
Labels: Scope: Backend

#71944 feat(query-builder): Remove interface switch from query builder
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/index.tsx
Labels: Scope: Frontend

#71945 feat(trace-explorer): Return slice index and width for timeline break…
  src/sentry/api/endpoints/organization_traces.py
  tests/sentry/api/endpoints/test_organization_traces.py
Labels: Scope: Backend

#71999 ref(related_issues): Make the code a bit more clear
  static/app/views/issueDetails/groupEventCarousel.tsx
  static/app/views/issueDetails/groupEventHeader.tsx
Labels: Scope: Frontend

#72007 ref: upgrade pyuwsgi
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#71955 ref(messaging): Cleanup `integration/__init__.py`
  src/sentry/api/endpoints/group_integration_details.py
  src/sentry/api/endpoints/group_integrations.py
  src/sentry/api/endpoints/project_plugin_details.py
  src/sentry/api/endpoints/project_repo_path_parsing.py
  src/sentry/api/serializers/models/group.py
  src/sentry/api/serializers/models/integration.py
  src/sentry/integrations/__init__.py
  src/sentry/integrations/aws_lambda/integration.py
  src/sentry/integrations/bitbucket/integration.py
  src/sentry/integrations/bitbucket_server/integration.py
  src/sentry/integrations/discord/integration.py
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/github/repository.py
  src/sentry/integrations/github_enterprise/integration.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/jira_server/integration.py
  src/sentry/integrations/manager.py
  src/sentry/integrations/msteams/integration.py
  src/sentry/integrations/slack/integration.py
  src/sentry/integrations/vercel/integration.py
  src/sentry/integrations/vsts/integration.py
  src/sentry/issues/endpoints/project_stacktrace_link.py
  src/sentry/models/integrations/integration.py
  src/sentry/models/integrations/utils.py
  src/sentry/notifications/utils/__init__.py
  src/sentry/plugins/providers/integration_repository.py
  src/sentry/plugins/sentry_webhooks/plugin.py
  src/sentry/plugins/utils.py
  src/sentry/rules/actions/integrations/create_ticket/utils.py
  src/sentry/tasks/integrations/__init__.py
  src/sentry_plugins/amazon_sqs/plugin.py
  src/sentry_plugins/asana/plugin.py
  src/sentry_plugins/bitbucket/plugin.py
  src/sentry_plugins/github/plugin.py
  src/sentry_plugins/gitlab/plugin.py
  src/sentry_plugins/heroku/plugin.py
  src/sentry_plugins/jira/plugin.py
  src/sentry_plugins/opsgenie/plugin.py
  src/sentry_plugins/pagerduty/plugin.py
  src/sentry_plugins/phabricator/plugin.py
  src/sentry_plugins/pivotal/plugin.py
  src/sentry_plugins/pushover/plugin.py
  src/sentry_plugins/redmine/plugin.py
  src/sentry_plugins/segment/plugin.py
  src/sentry_plugins/sessionstack/plugin.py
  src/sentry_plugins/slack/plugin.py
  src/sentry_plugins/splunk/plugin.py
  src/sentry_plugins/trello/plugin.py
  src/sentry_plugins/twilio/plugin.py
  src/sentry_plugins/victorops/plugin.py
  tests/sentry/integrations/test_base.py
Labels: Scope: Backend

#71924 feat(remote config): Add a settings page for remote config basics
  static/app/actionCreators/modal.tsx
  static/app/components/modals/remoteConfigCreateFeatureModal.tsx
  static/app/routes.tsx
  static/app/types/remoteConfig.ts
  static/app/utils/queryClient.tsx
  static/app/views/settings/project/navigationConfiguration.tsx
  static/app/views/settings/project/projectRemoteConfig.tsx
  static/app/views/settings/project/remoteConfig/useRemoteConfigSettings.tsx
Labels: Scope: Frontend

#71923 feat(performance): Update webvitals module to exclude unparameterized transactions
  static/app/views/performance/browser/webVitals/pageOverview.spec.tsx
  static/app/views/performance/browser/webVitals/pagePerformanceTable.tsx
  static/app/views/performance/browser/webVitals/settings.ts
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useProjectRawWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useProjectRawWebVitalsValuesTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useTransactionRawSamplesWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/rawWebVitalsQueries/useTransactionRawWebVitalsQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useProjectWebVitalsScoresQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useProjectWebVitalsScoresTimeseriesQuery.tsx
  static/app/views/performance/browser/webVitals/utils/queries/storedScoreQueries/useTransactionWebVitalsScoresQuery.tsx
  static/app/views/performance/browser/webVitals/webVitalsDetailPanel.spec.tsx
  static/app/views/performance/browser/webVitals/webVitalsLandingPage.spec.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
Labels: Scope: Frontend

#71881 feat(slack): add slack-sdk
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#71962 ref: Move statsPeriodToDays() into utils/duration/
  static/app/utils/dates.tsx
  static/app/utils/discover/eventView.tsx
  static/app/utils/duration/statsPeriodToDays.tsx
  static/app/utils/metrics/index.tsx
  static/app/views/dashboards/datasetConfig/releases.tsx
  static/app/views/metrics/createAlertModal.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/app/views/performance/utils/index.tsx
Labels: Scope: Frontend

#71928 fix: Only format less files, no eslint
  .github/file-filters.yml
  .github/workflows/frontend.yml
Labels: Scope: Frontend

#71964 ref: Combine promptsActivity.tsx into promptIsDismissed.tsx & remove dead code.
  static/app/utils/promptIsDismissed.tsx
  static/app/utils/promptsActivity.tsx
Labels: Scope: Frontend

#71966 ref: Move <Redirect> into components/
  static/app/components/redirect.tsx
  static/app/utils/withDomainRedirect.tsx
  static/app/views/onboarding/onboarding.tsx
  static/app/views/projects/redirectDeprecatedProjectRoute.tsx
  static/app/views/relocation/relocation.tsx
Labels: Scope: Frontend

#71563 fix(feedback/issues): check if latest_event is None before filtering attachments
  src/sentry/api/endpoints/group_details.py
  src/sentry/api/serializers/models/group_stream.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#72016 fix(gridEditable): Remove vertical scrollbar from Grid
  static/app/components/gridEditable/styles.tsx
Labels: Scope: Frontend

#72009 fix(query-builder): Improve detection of filter keys that support multiple values
  static/app/components/searchQueryBuilder/valueCombobox.tsx
Labels: Scope: Frontend

#71817 ref(pageFilters): Return stable reference from getState
  static/app/actionCreators/pageFilters.tsx
  static/app/stores/pageFiltersStore.spec.tsx
  static/app/stores/pageFiltersStore.tsx
Labels: Scope: Frontend

#71875 ref(replays): update videoReplayer code to match new rrweb logic & bump rrweb version
  package.json
  static/app/components/replays/videoReplayerWithInteractions.tsx
  yarn.lock
Labels: Scope: Frontend

#72018 fix(insights): failure to fetch full span description
  static/app/views/performance/database/databaseSpanSummaryPage.spec.tsx
  static/app/views/starfish/queries/useFullSpanFromTrace.tsx
Labels: Scope: Frontend

#71947 ref(js): Introduce ProjectContext to replace project legacy context
  static/app/components/acl/feature.spec.tsx
  static/app/sentryPropTypeValidators.tsx
  static/app/utils/withProject.tsx
  static/app/views/performance/vitalDetail/index.spec.tsx
  static/app/views/projects/projectContext.spec.tsx
  static/app/views/projects/projectContext.tsx
  static/app/views/settings/projectGeneralSettings/index.spec.tsx
  tests/js/fixtures/routerContextFixture.ts
  tests/js/sentry-test/initializeOrg.tsx
Labels: Scope: Frontend

#72008 feat(contexts): Add laravel as known platform context
  static/app/components/events/contexts/contextCard.tsx
  static/app/components/events/contexts/platform/index.spec.tsx
  static/app/components/events/contexts/platform/index.tsx
  static/app/components/events/contexts/utils.tsx
Labels: Scope: Frontend

#71882 feat(profileHours): Add profile hours to org stats
  static/app/views/organizationStats/index.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/app/views/organizationStats/usageStatsOrg.tsx
Labels: Scope: Frontend

#72024 feat(empty-states): Update arcade for issue stream empty state
  static/app/components/updatedEmptyState.tsx
Labels: Scope: Frontend

#72022 fix(similarity): use get_primary_hash in backfill
  src/sentry/tasks/backfill_seer_grouping_records.py
  tests/sentry/tasks/test_backfill_seer_grouping_records.py
Labels: Scope: Backend

#72027 chore(login): update the login banners
  src/sentry/templates/sentry/partial/alerts.html
Labels: Scope: Backend

#71773 feat(remote-config): Add proxy endpoint for configurations
  src/sentry/api/urls.py
  src/sentry/remote_config/docs/api.md
  src/sentry/remote_config/endpoints.py
  tests/sentry/remote_config/endpoints/test_configuration.py
Labels: Scope: Frontend, Scope: Backend

#72010 ref: remove wrapping RawEvent payload with CanonicalKeyView
  src/sentry/models/rawevent.py
Labels: Scope: Backend

#71930 fix(relocation): Clean up relocation serializer
  src/sentry/api/serializers/models/relocation.py
  tests/sentry/api/endpoints/relocations/test_index.py
  tests/sentry/api/endpoints/relocations/test_retry.py
  tests/sentry/api/serializers/test_relocation.py
Labels: Scope: Backend

#72012 feat(self-hosted): Errors only self-hosted sidebar
  static/app/components/sidebar/index.spec.tsx
  static/app/components/sidebar/index.tsx
  static/app/types/system.tsx
  tests/js/fixtures/config.ts
Labels: Scope: Frontend

#72013 fix(context): Address a few small context bugs
  static/app/components/events/contexts/contextCard.spec.tsx
  static/app/components/events/contexts/contextIcon.tsx
  static/app/components/events/contexts/operatingSystem/index.spec.tsx
  static/app/components/events/contexts/utils.spec.tsx
  static/app/components/events/contexts/utils.tsx
  static/app/components/events/meta/annotatedText/valueElement.tsx
Labels: Scope: Frontend

#72034 feat(traces): Use new slice quantization from backend
  static/app/views/performance/traces/content.tsx
  static/app/views/performance/traces/fieldRenderers.tsx
Labels: Scope: Frontend

#72028 ref(test): Remove location from context
  static/app/components/sidebar/index.spec.tsx
  static/app/views/performance/vitalDetail/index.spec.tsx
  tests/js/fixtures/routerContextFixture.ts
  tests/js/sentry-test/initializeOrg.tsx
Labels: Scope: Frontend

#72039 fix(insights): Fix flag name in Spans tab UI
  static/app/views/performance/transactionSummary/transactionSpans/content.tsx
Labels: Scope: Frontend

#72038 fix(traceview): Allow raw text on additional data when set
  static/app/components/events/contexts/contextCard.tsx
  static/app/components/events/highlights/editHighlightsModal.tsx
  static/app/components/keyValueData/card.stories.tsx
  static/app/components/keyValueData/card.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/sections/additionalData.tsx
Labels: Scope: Frontend

#72036 fix(related_issues): Prevent race condition
  static/app/views/issueDetails/groupEventHeader.tsx
Labels: Scope: Frontend

#72045 fix(contexts): Fix casing for known context
  static/app/components/events/contexts/utils.tsx
Labels: Scope: Frontend

#72019 ref: fix types for sentry.utils.snowflake
  pyproject.toml
  src/sentry/utils/snowflake.py
Labels: Scope: Backend

#72029 fix(new-trace): Fixing scrollbar offset.
  static/app/views/performance/newTraceDetails/traceRenderers/virtualizedViewManager.tsx
Labels: Scope: Frontend

#72046 fix(spanMetrics): Don't mark avg as a percentile
  src/sentry/search/events/datasets/spans_metrics.py
Labels: Scope: Backend

#72015 feat(insights): show update SDK banner cache module
  static/app/utils/performance/contexts/pageAlert.tsx
  static/app/views/performance/cache/cacheLandingPage.tsx
Labels: Scope: Frontend

#72048 ref(js): Fix a few biome warnings
  static/app/components/assigneeSelectorDropdown.tsx
  static/app/components/group/externalIssuesList/useExternalIssueData.tsx
  static/app/components/group/externalIssuesList/useFetchSentryAppData.tsx
  static/app/components/group/sentryAppExternalIssueForm.tsx
  static/app/components/pullRequestLink.tsx
  static/app/components/quickTrace/index.tsx
  static/app/components/quickTrace/utils.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/components/replaysOnboarding/useLoadOnboardingDoc.tsx
  static/app/components/replaysOnboarding/utils.tsx
Labels: Scope: Frontend

#72033 ref(messaging): Removing Integration Namespace Imports
  src/sentry/api/endpoints/group_integrations.py
  src/sentry/api/endpoints/integrations/index.py
  src/sentry/api/endpoints/integrations/install_request.py
  src/sentry/api/endpoints/project_repo_path_parsing.py
  src/sentry/api/serializers/models/user_identity_config.py
  src/sentry/integrations/__init__.py
  src/sentry/integrations/manager.py
  src/sentry/integrations/pipeline.py
  src/sentry/models/integrations/utils.py
  src/sentry/notifications/utils/__init__.py
  src/sentry/runner/initializer.py
  src/sentry/testutils/pytest/sentry.py
  src/sentry/web/frontend/integration_extension_configuration.py
  tests/sentry/integrations/test_manager.py
Labels: Scope: Backend

#72053 fix(remote-config): Add trailing slash to configuration proxy URL
  src/sentry/api/urls.py
Labels: Scope: Backend

#72055 ref: add typing for eventstore bind_nodes
  src/sentry/eventstore/base.py
  src/sentry/models/processingissue.py
  src/sentry/nodestore/README.rst
  tests/sentry/eventstore/test_base.py
  tests/sentry/eventstore/test_models.py
Labels: Scope: Backend

#72054 test(js): Remove RouterContextFixture
  static/app/views/issueList/overview.spec.tsx
  tests/js/fixtures/routerContextFixture.ts
  tests/js/sentry-test/initializeOrg.tsx
  tests/js/sentry-test/onboarding/renderWithOnboardingLayout.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#71627 feat(utils): Add `with_circuit_breaker` helper
  src/sentry/utils/circuit_breaker.py
  tests/sentry/utils/test_circuit_breaker.py
Labels: Scope: Backend

#72058 chore(similarity): remove unused options
  src/sentry/options/defaults.py
Labels: Scope: Backend

#72069 chore(staff): Add staff option logs
  src/sentry/auth/staff.py
Labels: Scope: Backend

#70810 metrics(feedback): Track source emitted by SDK fxs
  src/sentry/feedback/usecases/create_feedback.py
Labels: Scope: Backend, Stale

#72074 fix(query-builder): Fix selecting filter operator with keyboard
  static/app/components/searchQueryBuilder/useQueryBuilderGrid.tsx
Labels: Scope: Frontend

#72063 fix(new-trace): Tag heat map event target url missing traceSlug.
  static/app/views/performance/transactionSummary/transactionTags/tagsHeatMap.tsx
Labels: Scope: Frontend

#72070 feat(replay): Only show hydration errors project setting if the feature is enabled
  static/app/data/forms/replay.tsx
  static/app/views/settings/project/projectReplays.tsx
Labels: Scope: Frontend

#72079 fix(replay): check payload keys exist for hydrate-error breadcrumbs
  src/sentry/replays/usecases/ingest/dom_index.py
Labels: Scope: Backend

#72080 feat(metrics): Prevent constant equations
  static/app/views/metrics/formulaInput.tsx
Labels: Scope: Frontend

#71649 perf: move sentry/monitors to orjson
  src/sentry/monitors/consumers/monitor_consumer.py
  src/sentry/monitors/processing_errors/manager.py
Labels: Scope: Backend

#71994 chore(dashboards): remove unused metric context provider
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetCard/metricsContext.tsx
Labels: Scope: Frontend

#72083 feat(metrics): Register create-metrics-alert-tooltip hook
  static/app/types/hooks.tsx
Labels: Scope: Frontend

#72084 fix(dropdown-menu): Disabled prop not working
  static/app/components/dropdownMenu/index.spec.tsx
  static/app/components/dropdownMenu/index.tsx
Labels: Scope: Frontend

#72004 ref(metrics): streamline metrics api files
  src/sentry/api/endpoints/organization_metric_details.py
  src/sentry/api/endpoints/organization_metrics_details.py
  src/sentry/api/endpoints/organization_metrics_tag_details.py
  src/sentry/api/endpoints/organization_metrics_tags.py
  src/sentry/api/endpoints/organization_on_demand_metrics_estimation_stats.py
  src/sentry/api/endpoints/organization_release_health_data.py
  src/sentry/api/urls.py
  src/sentry/sentry_metrics/use_case_utils.py
  tests/sentry/api/endpoints/test_organization_metric_details.py
  tests/sentry/api/endpoints/test_organization_metrics.py
  tests/sentry/api/endpoints/test_organization_on_demand_metrics_estimation_stats.py
  tests/sentry/api/endpoints/test_organization_release_health_data.py
Labels: Scope: Backend

#72087 feat(metrics): Check alerts feature when rendering create button
  static/app/components/metrics/createMetricAlertFeature.tsx
  static/app/components/modals/metricWidgetViewerModal/queries.tsx
  static/app/utils/metrics/features.tsx
  static/app/views/metrics/metricQueryContextMenu.tsx
  static/app/views/metrics/pageHeaderActions.tsx
Labels: Scope: Frontend

#72086 chore(metrics): remove rollout flag
  static/app/components/sidebar/index.tsx
  static/app/utils/metrics/features.tsx
  static/app/views/dashboards/addWidget.tsx
  static/app/views/metrics/billing.tsx
  static/app/views/metrics/layout.tsx
  static/app/views/metrics/metricFeatureBadge.tsx
  static/app/views/metrics/optInModal.tsx
  static/app/views/settings/project/navigationConfiguration.tsx
Labels: Scope: Frontend

#72090 Cleaned up code and api owners for owners-native
  .github/CODEOWNERS
  src/sentry/api/api_owners.py
  src/sentry/api/endpoints/builtin_symbol_sources.py
  src/sentry/api/endpoints/chunk.py
  src/sentry/api/endpoints/debug_files.py
  src/sentry/api/endpoints/event_apple_crash_report.py
  src/sentry/api/endpoints/project_app_store_connect_credentials.py
  src/sentry/api/endpoints/project_symbol_sources.py
Labels: Scope: Backend

#71996 fix(metrics): 404 instead of 500 if metric is not found in /metrics/meta/tags/{metric}
  src/sentry/api/endpoints/organization_metrics_tags.py
  src/sentry/snuba/metrics/datasource.py
  tests/sentry/api/endpoints/test_organization_metrics_tags.py
Labels: Scope: Backend

#71549 fix(grouping): Mark Dart SDK frames as non inApp
  src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt
  tests/sentry/grouping/grouping_inputs/frame-ignores-sentry-dart-sdk.json
  tests/sentry/grouping/grouping_inputs/frame-ignores-sentry-flutter-sdk.json
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/legacy@2019_03_12/frame_ignores_sentry_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/mobile@2021_02_12/frame_ignores_sentry_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_05/frame_ignores_sentry_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_04_17/frame_ignores_sentry_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/frame_ignores_sentry_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/frame_ignores_sentry_flutter_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_sentry_dart_sdk.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/frame_ignores_sentry_flutter_sdk.pysnap
Labels: Scope: Backend

#72097 fix(metrics): Add missing trailing item keys
  static/app/views/metrics/queryBuilder.tsx
Labels: Scope: Frontend

#72098 fix(metrics): Tab list text value console warning
  static/app/views/metrics/widgetDetails.tsx
Labels: Scope: Frontend

#72026 ref: Remove LPQ scanning
  src/sentry/api/serializers/models/project.py
  src/sentry/conf/server.py
  src/sentry/processing/realtime_metrics/__init__.py
  src/sentry/processing/realtime_metrics/base.py
  src/sentry/processing/realtime_metrics/dummy.py
  src/sentry/processing/realtime_metrics/pb.py
  src/sentry/processing/realtime_metrics/redis.py
  src/sentry/tasks/low_priority_symbolication.py
  tests/sentry/processing/realtime_metrics/test_redis.py
  tests/sentry/tasks/test_low_priority_symbolication.py
Labels: Scope: Backend

#72104 ref: Remove LPQ scanning, the third
  src/sentry/api/serializers/models/project.py
  src/sentry/processing/realtime_metrics/__init__.py
  src/sentry/processing/realtime_metrics/base.py
  src/sentry/processing/realtime_metrics/dummy.py
  src/sentry/processing/realtime_metrics/pb.py
  src/sentry/processing/realtime_metrics/redis.py
  src/sentry/tasks/low_priority_symbolication.py
  tests/sentry/processing/realtime_metrics/test_redis.py
  tests/sentry/tasks/test_low_priority_symbolication.py
Labels: Scope: Backend

#72107 docs(metrics): Make note during onboarding more clear
  static/app/components/onboarding/gettingStartedDoc/utils/metricsOnboarding.tsx
  static/app/gettingStartedDocs/apple/apple-ios.tsx
  static/app/gettingStartedDocs/bun/bun.tsx
  static/app/gettingStartedDocs/dart/dart.tsx
  static/app/gettingStartedDocs/deno/deno.tsx
  static/app/gettingStartedDocs/electron/electron.tsx
  static/app/gettingStartedDocs/flutter/flutter.tsx
  static/app/gettingStartedDocs/php/laravel.tsx
  static/app/gettingStartedDocs/php/php.tsx
  static/app/gettingStartedDocs/rust/rust.tsx
  static/app/gettingStartedDocs/unity/unity.tsx
Labels: Scope: Frontend

#72006 chore(features) Move feature defaults into permanent.py
  src/sentry/conf/server.py
  src/sentry/features/permanent.py
Labels: Scope: Backend

#72106 fix(metrics): Duplicate metrics name detection performance
  static/app/views/metrics/queryBuilder.spec.tsx
  static/app/views/metrics/queryBuilder.tsx
Labels: Scope: Frontend

#71674 feat(insights): Increase main site sidebar width slightly
  static/app/utils/theme.tsx
  static/less/variables.less
Labels: Scope: Frontend

#72108 fix(dashboard): Metric widget modal performance
  static/app/components/modals/metricWidgetViewerModal/queries.tsx
Labels: Scope: Frontend

#72111 fix(metrics): Metrics meta hook performance
  static/app/utils/metrics/useMetricsMeta.tsx
Labels: Scope: Frontend

#72112 feat(sdk-crashes): Add dart packages to config
  src/sentry/utils/sdk_crashes/sdk_crash_detection_config.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection_dart.py
Labels: Scope: Backend

#72060 test(js): Simplify test provider creation
  static/app/views/settings/project/projectKeys/details/index.spec.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#72056 fix(spans): Handle time column for grahing indexed spans
  src/sentry/search/events/builder/profile_functions.py
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/search/events/fields.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#72032 perf(trace-explorer): Add additional conditions to trace query
  src/sentry/api/endpoints/organization_traces.py
  tests/sentry/api/endpoints/test_organization_traces.py
Labels: Scope: Backend

#71689 feat(data-consent): Add data consent check to organization creation
  static/app/types/hooks.tsx
  static/app/views/organizationCreate/index.tsx
Labels: Scope: Frontend

#72120 ref(grid-editable): Remove unused location prop
  static/app/components/events/eventStatisticalDetector/eventRegressionTable.tsx
  static/app/components/events/eventStatisticalDetector/spanOpBreakdown.tsx
  static/app/components/gridEditable/index.stories.tsx
  static/app/components/gridEditable/index.tsx
  static/app/components/metrics/metricSamplesTable.tsx
  static/app/components/modals/widgetViewerModal.tsx
  static/app/components/profiling/profileEventsTable.tsx
  static/app/components/profiling/suspectFunctions/functionsTable.tsx
  static/app/views/alerts/rules/metric/details/relatedTransactions.tsx
  static/app/views/discover/table/tableView.tsx
  static/app/views/llmMonitoring/pipelineSpansTable.tsx
  static/app/views/llmMonitoring/pipelinesTable.tsx
  static/app/views/performance/browser/resources/resourceSummaryPage/resourceSummaryTable.tsx
  static/app/views/performance/browser/resources/resourceView/resourceTable.tsx
  static/app/views/performance/browser/webVitals/pageOverviewWebVitalsDetailPanel.tsx
  static/app/views/performance/browser/webVitals/pagePerformanceTable.tsx
  static/app/views/performance/browser/webVitals/pageSamplePerformanceTable.tsx
  static/app/views/performance/browser/webVitals/webVitalsDetailPanel.tsx
  static/app/views/performance/cache/tables/spanSamplesTable.tsx
  static/app/views/performance/cache/tables/transactionsTable.tsx
  static/app/views/performance/database/queriesTable.tsx
  static/app/views/performance/database/queryTransactionsTable.tsx
  static/app/views/performance/http/tables/domainTransactionsTable.tsx
  static/app/views/performance/http/tables/domainsTable.tsx
  static/app/views/performance/http/tables/spanSamplesTable.tsx
  static/app/views/performance/mobile/appStarts/screenSummary/spanOperationTable.tsx
  static/app/views/performance/mobile/components/screensTable.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/eventSamplesTable.tsx
  static/app/views/performance/mobile/screenload/screenLoadSpans/table.tsx
  static/app/views/performance/mobile/screenload/screens/screensTable.tsx
  static/app/views/performance/queues/destinationSummary/messageSpanSamplesTable.tsx
  static/app/views/performance/queues/destinationSummary/transactionsTable.tsx
  static/app/views/performance/queues/queuesTable.tsx
  static/app/views/performance/table.tsx
  static/app/views/performance/transactionSummary/transactionAnomalies/anomaliesTable.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
  static/app/views/performance/transactionSummary/transactionOverview/tagExplorer.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/spanDetailsTable.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanMetricsTable.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanSummary/spanSummaryTable.tsx
  static/app/views/performance/transactionSummary/transactionSpans/suspectSpansTable.tsx
  static/app/views/performance/transactionSummary/transactionTags/tagValueTable.tsx
  static/app/views/performance/trends/changeExplorerUtils/metricsTable.tsx
  static/app/views/performance/vitalDetail/table.tsx
  static/app/views/replays/deadRageClick/selectorTable.tsx
  static/app/views/starfish/components/samplesTable/spanSamplesTable.tsx
Labels: Scope: Frontend

#72126 fix(metrics): Add to dashboard disabled state
  static/app/views/metrics/metricQueryContextMenu.tsx
Labels: Scope: Frontend

#72044 fix(query-builder): Make filter key non-editable
  static/app/components/searchQueryBuilder/filter.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
Labels: Scope: Frontend
