Repository getsentry/sentry, pull requests merged in 2024-11, with the labels that each got.

#80121 fix(autofix): update autofix setup url
  static/app/components/events/autofix/autofixSetupModal.tsx
  static/app/components/events/autofix/autofixSetupWriteAccessModal.spec.tsx
  static/app/components/events/autofix/autofixSetupWriteAccessModal.tsx
Labels: Scope: Frontend

#80103 fix(dashboards): Fix unable to plot top N chart if query data is missing
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/genericWidgetQueries.tsx
Labels: Scope: Frontend

#80104 feat(dashboards): Add EAP search bar for filtering step
  static/app/views/dashboards/datasetConfig/spans.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/spansSearchBar.spec.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/spansSearchBar.tsx
Labels: Scope: Frontend

#79427 feat(dashboards): Add Edit Access Selector to Dashbaords
  static/app/actionCreators/dashboards.tsx
  static/app/components/menuListItem.tsx
  static/app/views/dashboards/controls.tsx
  static/app/views/dashboards/detail.spec.tsx
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/editAccessSelector.spec.tsx
  static/app/views/dashboards/editAccessSelector.tsx
  static/app/views/dashboards/types.tsx
Labels: Scope: Frontend

#80083 feat(ml_grouping): Add a few Java platforms to backfill
  src/sentry/seer/similarity/utils.py
  tests/sentry/tasks/test_backfill_seer_grouping_records.py
Labels: Scope: Backend

#80043 feat(profiling) Add context menu to flamechart page
  static/app/components/profiling/flamegraph/flamegraphContextMenu.tsx
  static/app/components/profiling/flamegraph/flamegraphSpans.tsx
  static/app/components/profiling/flamegraph/flamegraphSpansContextMenu.tsx
  static/app/utils/profiling/spanTree.tsx
  static/app/views/performance/newTraceDetails/traceHeader/breadcrumbs.tsx
  static/app/views/performance/traceDetails/utils.tsx
Labels: Scope: Frontend

#79992 feat(insights): enforce query date range limit
  static/app/components/organizations/datePageFilter.tsx
  static/app/views/insights/common/components/modulePageFilterBar.tsx
  static/app/views/insights/settings.ts
Labels: Scope: Frontend

#80086 fix(new-trace): Use correct billing terminology
  static/app/views/performance/newTraceDetails/traceTypeWarnings/errorsOnlyWarnings.tsx
Labels: Scope: Frontend

#80081 feat(issue-details): Add solution center to streamlined issue details page
  static/app/views/issueDetails/streamline/groupDetailsLayout.spec.tsx
  static/app/views/issueDetails/streamline/sidebar.spec.tsx
  static/app/views/issueDetails/streamline/sidebar.tsx
  static/app/views/issueDetails/streamline/solutionsDrawer.tsx
  static/app/views/issueDetails/streamline/solutionsSection.tsx
Labels: Scope: Frontend

#80102 fix(issues): Add min interval to issues yAxis
  static/app/views/issueDetails/streamline/eventGraph.tsx
Labels: Scope: Frontend

#80119 feat(issues): Preserve previous suspect commit
  static/app/components/events/suspectCommits.tsx
  static/app/components/group/assignedTo.tsx
  static/app/utils/useCommitters.tsx
  static/app/views/issueDetails/streamline/assigneeSelector.tsx
Labels: Scope: Frontend

#80128 fix(dashboards): Ensure release health widgets have the same meta
  static/app/views/dashboards/datasetConfig/releases.spec.tsx
  static/app/views/dashboards/datasetConfig/releases.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/releaseWidgetQueries.spec.tsx
Labels: Scope: Frontend

#80120 feat(oauth): send feature flag to frontend
  src/sentry/features/temporary.py
  src/sentry/web/client_config.py
Labels: Scope: Backend

#80114 chore(invite-members): enable settings toggle for all plans
  static/app/data/forms/organizationGeneralSettings.tsx
Labels: Scope: Frontend

#80123 feat(oauth): add organization to ApiToken
  src/sentry/models/apitoken.py
  src/sentry/web/frontend/oauth_token.py
  tests/sentry/web/frontend/test_oauth_token.py
Labels: Scope: Backend

#80098 ref(trace) increase precision of container width
  static/app/views/performance/newTraceDetails/traceRenderers/virtualizedViewManager.tsx
Labels: Scope: Frontend

#80130 chore(issue-details): Clean up requests section formatting
  static/app/components/events/eventTags/eventTagsTree.tsx
  static/app/components/events/interfaces/request/index.tsx
  static/app/components/events/interfaces/request/richHttpContentClippedBoxBodySection.tsx
  static/app/components/keyValueData/index.tsx
Labels: Scope: Frontend

#80127 fix(nav): submenu highlight spacing
  static/app/components/nav/index.tsx
  static/app/components/nav/submenu.tsx
Labels: Scope: Frontend

#80101 feat(rollback): /rollback route should resolve to React app
  src/sentry/web/urls.py
Labels: Scope: Backend

#80134 chore(dashboards): Remove unused getColoredWidgetIndicator function
  static/app/views/dashboards/utils.tsx
Labels: Scope: Frontend

#79860 ref(dashboards): Remove feature flag for Big Number Equations (backend)
  src/sentry/features/temporary.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
  tests/sentry/api/endpoints/test_organization_dashboard_widget_details.py
  tests/sentry/api/endpoints/test_organization_dashboards.py
Labels: Scope: Backend

#80138 chore(vscode): Turn on --reuse-db flag for vscode debugger
  .vscode/launch.json
Labels: Scope: Frontend

#80110 fix(eap): Auto complete for sentry fields
  src/sentry/api/endpoints/organization_spans_fields.py
  src/sentry/search/eap/columns.py
  src/sentry/search/eap/spans.py
  src/sentry/search/events/builder/spans_indexed.py
  src/sentry/search/events/constants.py
  tests/sentry/api/endpoints/test_organization_spans_fields.py
  tests/sentry/search/eap/test_spans.py
Labels: Scope: Backend

#80137 feat(trace) trigger search on icon click
  static/app/components/idBadge/baseBadge.tsx
  static/app/components/idBadge/projectBadge.tsx
  static/app/views/explore/tables/tracesTable/fieldRenderers.tsx
  static/app/views/performance/newTraceDetails/traceHeader/index.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchEvaluator.spec.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchEvaluator.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchInput.tsx
Labels: Scope: Frontend

#80131 fix(insights): domain views not showing setup project screen
  static/app/views/insights/pages/ai/aiOverviewPage.tsx
  static/app/views/insights/pages/backend/backendOverviewPage.tsx
  static/app/views/insights/pages/domainOverviewPageProviders.tsx
  static/app/views/insights/pages/frontend/frontendOverviewPage.tsx
  static/app/views/insights/pages/mobile/mobileOverviewPage.tsx
Labels: Scope: Frontend

#80132 feat(dashboards): Remove suspect commit from popover
  static/app/views/discover/table/quickContext/issueContext.spec.tsx
  static/app/views/discover/table/quickContext/issueContext.tsx
  static/app/views/discover/table/quickContext/quickContextHovercard.spec.tsx
Labels: Scope: Frontend

#80022 feat(rollback): Add rollback settings
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/constants.py
  tests/sentry/api/endpoints/test_organization_details.py
Labels: Scope: Backend

#80100 chore(issues): remove option to collapse activity serialiser
  src/sentry/api/serializers/models/activity.py
  src/sentry/options/defaults.py
  tests/sentry/api/serializers/test_activity.py
Labels: Scope: Backend

#80145 fix(issues): Increase buckets on issue graph
  static/app/views/issueDetails/streamline/eventGraph.spec.tsx
  static/app/views/issueDetails/streamline/useIssueDetailsDiscoverQuery.tsx
Labels: Scope: Frontend

#80133 feat(issue-details): Add resources from config to solutions center
  static/app/views/issueDetails/streamline/resources.tsx
  static/app/views/issueDetails/streamline/solutionsDrawer.tsx
Labels: Scope: Frontend

#80142 fix(dashboard): Only update permission if not none
  src/sentry/api/serializers/rest_framework/dashboard.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
Labels: Scope: Backend

#80157 fix(trace) do not autofocus unless we have a truthy value
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchInput.tsx
Labels: Scope: Frontend

#80154 fix(issues): Remove falsy values from user
  static/app/components/events/contexts/contextCard.tsx
  static/app/components/events/contexts/user/index.tsx
  static/app/components/events/contexts/utils.tsx
  static/app/components/events/interfaces/utils.spec.tsx
  static/app/components/events/interfaces/utils.tsx
Labels: Scope: Frontend

#80030 feat(devservices): Add sentry config
  devservices/config.yml
  src/sentry/runner/commands/devserver.py
Labels: Scope: Frontend, Scope: Backend

#80165 fix(flags): hide feature flag series legend if not under ff
  static/app/views/issueDetails/streamline/eventGraph.tsx
Labels: Scope: Frontend

#80169 fix(quick-start): Add missing file import
  src/sentry/analytics/events/__init__.py
Labels: Scope: Backend

#79957 feat(issues): add enhancement rules utility filtering for profiling
  src/sentry/grouping/enhancer/__init__.py
  tests/sentry/grouping/test_enhancer.py
Labels: Scope: Backend

#80175 feat(demo-mode): display demo components
  static/app/actionCreators/guides.tsx
  static/app/components/acl/demoModeGate.tsx
  static/app/components/assistant/getGuidesContent.tsx
  static/app/components/demo/demoHeader.tsx
  static/app/components/events/interfaces/spans/header.tsx
  static/app/components/events/interfaces/spans/newTraceDetailsHeader.tsx
  static/app/components/onboardingWizard/newSidebar.tsx
  static/app/components/onboardingWizard/progressHeader.tsx
  static/app/components/onboardingWizard/sidebar.tsx
  static/app/components/onboardingWizard/task.tsx
  static/app/components/onboardingWizard/taskConfig.tsx
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/newOnboardingStatus.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/components/stream/group.tsx
  static/app/main.tsx
  static/app/utils/demoMode.tsx
  static/app/views/app/index.tsx
Labels: Scope: Frontend

#80064 chore(eap-spans): Add feature to control span ingestion in EAP
  src/sentry/features/temporary.py
  src/sentry/relay/config/__init__.py
  src/sentry/testutils/cases.py
Labels: Scope: Backend

#80177 feat(dynamic-sampling): Add rate input for each project
  static/app/views/settings/dynamicSampling/organizationSampleRateField.tsx
  static/app/views/settings/dynamicSampling/projectSampling.tsx
  static/app/views/settings/dynamicSampling/projectsEditTable.tsx
  static/app/views/settings/dynamicSampling/projectsPreviewTable.tsx
  static/app/views/settings/dynamicSampling/projectsTable.tsx
  static/app/views/settings/dynamicSampling/utils/formContext.tsx
  static/app/views/settings/dynamicSampling/utils/organizationSamplingForm.tsx
  static/app/views/settings/dynamicSampling/utils/projectSamplingForm.tsx
Labels: Scope: Frontend

#80099 ref: upgrade pyuwsgi
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#80143 move upsell hook under header
  static/app/views/insights/browser/resources/views/resourceSummaryPage.tsx
  static/app/views/insights/browser/resources/views/resourcesLandingPage.tsx
  static/app/views/insights/browser/webVitals/views/pageOverview.tsx
  static/app/views/insights/browser/webVitals/views/webVitalsLandingPage.tsx
  static/app/views/insights/cache/views/cacheLandingPage.tsx
  static/app/views/insights/common/components/modulePageProviders.tsx
  static/app/views/insights/common/components/moduleUpsellHookWrapper.tsx
  static/app/views/insights/database/views/databaseLandingPage.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.tsx
  static/app/views/insights/http/views/httpDomainSummaryPage.tsx
  static/app/views/insights/http/views/httpLandingPage.tsx
  static/app/views/insights/llmMonitoring/views/llmMonitoringDetailsPage.tsx
  static/app/views/insights/llmMonitoring/views/llmMonitoringLandingPage.tsx
  static/app/views/insights/mobile/common/components/screensTemplate.tsx
  static/app/views/insights/mobile/screenRendering/screenRenderingLandingPage.tsx
  static/app/views/insights/mobile/screenRendering/screenRenderingSummaryPage.tsx
  static/app/views/insights/mobile/screenload/views/screenloadLandingPage.tsx
  static/app/views/insights/queues/views/destinationSummaryPage.tsx
  static/app/views/insights/queues/views/queuesLandingPage.tsx
Labels: Scope: Frontend

#80186 ref: fix typing for request_change bases
  pyproject.toml
  src/sentry/api/bases/organization_request_change.py
  src/sentry/api/bases/project_request_change.py
Labels: Scope: Backend

#80187 ref: fix typing for slack digest notification
  pyproject.toml
  src/sentry/integrations/slack/message_builder/notifications/digest.py
Labels: Scope: Backend

#80146 fix(profiling): Onboarding type check for python
  static/app/gettingStartedDocs/python/aiohttp.tsx
  static/app/gettingStartedDocs/python/asgi.tsx
  static/app/gettingStartedDocs/python/awslambda.tsx
  static/app/gettingStartedDocs/python/bottle.tsx
  static/app/gettingStartedDocs/python/celery.tsx
  static/app/gettingStartedDocs/python/chalice.tsx
  static/app/gettingStartedDocs/python/django.tsx
  static/app/gettingStartedDocs/python/falcon.tsx
  static/app/gettingStartedDocs/python/fastapi.tsx
  static/app/gettingStartedDocs/python/flask.tsx
  static/app/gettingStartedDocs/python/gcpfunctions.tsx
  static/app/gettingStartedDocs/python/python.tsx
  static/app/gettingStartedDocs/python/quart.tsx
  static/app/gettingStartedDocs/python/rq.tsx
  static/app/gettingStartedDocs/python/serverless.tsx
  static/app/gettingStartedDocs/python/starlette.tsx
  static/app/gettingStartedDocs/python/tornado.tsx
  static/app/gettingStartedDocs/python/tryton.tsx
  static/app/gettingStartedDocs/python/wsgi.tsx
Labels: Scope: Frontend

#80190 ref: fix types for api.endpoints.chunk
  pyproject.toml
  src/sentry/api/endpoints/chunk.py
Labels: Scope: Backend

#80159 ref(dashboards): Extract helper to create request data for timeseries
  static/app/actionCreators/events.tsx
  static/app/views/dashboards/datasetConfig/errors.tsx
  static/app/views/dashboards/datasetConfig/transactions.tsx
  static/app/views/dashboards/datasetConfig/utils/getSeriesRequestData.spec.tsx
  static/app/views/dashboards/datasetConfig/utils/getSeriesRequestData.tsx
Labels: Scope: Frontend

#80163 fix(dashboards): Prevent widget modal crash when `query=` URL parameter is too high
  static/app/components/modals/widgetViewerModal.spec.tsx
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboards/detail.tsx
Labels: Scope: Frontend

#80034 feat(explore): Supporting more aggregate functions and params in search.
  static/app/components/performance/spanSearchQueryBuilder.tsx
  static/app/components/searchQueryBuilder/context.tsx
  static/app/components/searchQueryBuilder/tokens/filter/parametersCombobox.tsx
  static/app/utils/fields/index.ts
  static/app/views/explore/content.tsx
  static/app/views/explore/tables/spansTable.tsx
  static/app/views/insights/common/queries/useSpansQuery.tsx
Labels: Scope: Frontend

#79799 fix(alerts): avoid AttributeError in EventAttributeCondition
  src/sentry/rules/conditions/event_attribute.py
  tests/sentry/rules/conditions/test_event_attribute.py
Labels: Scope: Backend

#80192 fix: Align deletedproject.slug with project.slug
  migrations_lockfile.txt
  src/sentry/api/endpoints/project_details.py
  src/sentry/api/endpoints/team_projects.py
  src/sentry/constants.py
  src/sentry/migrations/0782_align_deletedproject_slug_length.py
  src/sentry/models/deletedproject.py
  src/sentry/models/project.py
Labels: Scope: Backend

#80196 feat(dashboards-eap): Add alpha flag to dataset option
  static/app/views/dashboards/widgetBuilder/buildSteps/dataSetStep.tsx
Labels: Scope: Frontend

#80199 feat(issues): Update attachment screenshot modal, cards
  static/app/components/events/attachmentViewers/jsonViewer.spec.tsx
  static/app/components/events/attachmentViewers/utils.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/modal.spec.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/modal.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/screenshotDataSection.tsx
  static/app/components/events/eventViewHierarchy.tsx
  static/app/components/feedback/feedbackItem/feedbackScreenshot.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachments.spec.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachments.tsx
  static/app/views/issueDetails/groupEventAttachments/inlineEventAttachment.tsx
  static/app/views/issueDetails/groupEventAttachments/screenshotCard.tsx
Labels: Scope: Frontend

#80026 chore(anomaly detection): feedback banner
  static/app/components/banner.tsx
  static/app/views/alerts/rules/metric/details/anomalyDetectionFeedbackBanner.spec.tsx
  static/app/views/alerts/rules/metric/details/anomalyDetectionFeedbackBanner.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
Labels: Scope: Frontend

#80204 feat(issues): Add custom issues granularity
  static/app/components/charts/utils.tsx
  static/app/views/issueDetails/streamline/useIssueDetailsDiscoverQuery.tsx
Labels: Scope: Frontend

#80195 fix(similarity): Filter same group out of response
  src/sentry/issues/endpoints/group_similar_issues_embeddings.py
  tests/sentry/issues/endpoints/test_group_similar_issues_embeddings.py
Labels: Scope: Backend

#80202 fix(issue-details): Style function evidence and hydration diff sections
  static/app/components/events/eventHydrationDiff/replayDiffContent.tsx
  static/app/components/events/eventHydrationDiff/replayDiffSection.tsx
  static/app/components/events/eventStatisticalDetector/eventFunctionRegressionEvidence.tsx
  static/app/components/events/profileEventEvidence.tsx
Labels: Scope: Frontend

#80193 perf(warmup): set active language so resolver warms up correctly
  src/sentry/api/endpoints/warmup.py
  tests/sentry/test_wsgi.py
Labels: Scope: Backend

#80167 fix(autofix): Prevent overflow for rethink input and diff editing overlays
  static/app/components/events/autofix/autofixDiff.tsx
  static/app/components/events/autofix/autofixInsightCards.tsx
Labels: Scope: Frontend

#80126 chore(eap): updates sentry protos to 0.1.32
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#80188 feat(dashboards): Add timeseries support for EAP widgets
  static/app/views/dashboards/datasetConfig/spans.spec.tsx
  static/app/views/dashboards/datasetConfig/spans.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/sortByStep/sortBySelectors.tsx
  static/app/views/dashboards/widgetBuilder/widgetBuilderSortBy.spec.tsx
Labels: Scope: Frontend

#80210 feat(settings): Remove DropdownLink from project debug
  static/app/views/settings/projectDebugFiles/sources/customRepositories/actions.tsx
  static/app/views/settings/projectDebugFiles/sources/customRepositories/index.tsx
  static/app/views/settings/projectDebugFiles/sources/customRepositories/repository.tsx
Labels: Scope: Frontend

#80205 feat(crons): Improve schedule sanitization
  src/sentry/monitors/validators.py
  tests/sentry/monitors/endpoints/test_organization_monitor_index.py
Labels: Scope: Backend

#80217 feat(issue-details): Use detailed latency tooltip for event timestamp
  static/app/views/issueDetails/streamline/eventTitle.tsx
Labels: Scope: Frontend

#80207 chore(slack): add logging for slack options load filtering
  src/sentry/integrations/slack/webhooks/options_load.py
Labels: Scope: Backend

#80211 feat(issues): Remove deprecated DropdownLink from debug
  static/app/components/events/interfaces/debugMeta/debugImageDetails/candidate/actions.tsx
Labels: Scope: Frontend

#80021 chore(sentry apps): update apidocs for new create ext issue functionality
  api-docs/paths/integration-platform/sentry-app-external-issues.json
Labels: Scope: Frontend

#80206 fix(settings): Fix project stats search
  static/app/utils/project/sortProjects.tsx
  static/app/views/settings/organizationProjects/index.spec.tsx
  static/app/views/settings/organizationProjects/index.tsx
Labels: Scope: Frontend

#80221 fix(issue-details): Update resources section for streamlined experience
  static/app/views/issueDetails/resourcesAndPossibleSolutions.tsx
Labels: Scope: Frontend

#80066 feat(ds): Support project sample rates in the bias tasks
  src/sentry/dynamic_sampling/rules/base.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_transactions.py
  src/sentry/dynamic_sampling/tasks/helpers/sample_rate.py
  src/sentry/dynamic_sampling/tasks/utils.py
  tests/sentry/dynamic_sampling/tasks/test_boost_low_volume_projects.py
  tests/sentry/dynamic_sampling/test_generate_rules.py
Labels: Scope: Backend

#80238 ref(ds): Change sample rate of DS batch tasks to 100%
  src/sentry/dynamic_sampling/tasks/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_transactions.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#80242 chore(snuba): Add new referrer
  src/sentry/snuba/referrer.py
Labels: Scope: Backend

#80245 fix(dashboards): Add custom field renderer
  static/app/views/dashboards/datasetConfig/spans.tsx
Labels: Scope: Frontend

#80009 ref: upgrade orjson
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#80219 ref(ownership): Convert ProjectOwnership to FC
  static/app/views/settings/project/projectOwnership/index.spec.tsx
  static/app/views/settings/project/projectOwnership/index.tsx
Labels: Scope: Frontend

#80246 fix(new-trace): Rounding transaction durations with 2 dec. precision.
  static/app/components/events/interfaces/spans/newTraceDetailsSpanDetails.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/generalInfo.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/sections/generalInfo.tsx
  static/app/views/performance/newTraceDetails/traceRow/traceBar.tsx
Labels: Scope: Frontend

#80209 fix(dashboards): filter out undefined values for legend unselectedSeries query
  static/app/views/dashboards/widgetLegendSelectionState.tsx
Labels: Scope: Frontend

#80248 fix(insights): backend overview page should not show frontend/mobile ops
  static/app/views/insights/pages/backend/backendOverviewPage.tsx
Labels: Scope: Frontend

#80252 ref(profiling) polish examples of traces
  static/app/views/profiling/landing/slowestFunctionsTable.tsx
Labels: Scope: Frontend

#80227 fix(alert): display custom time in date dropdown
  static/app/views/alerts/rules/metric/details/anomalyDetectionFeedbackBanner.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
Labels: Scope: Frontend

#79932 chore(similarity): Remove message_distance from seer response
  src/sentry/seer/similarity/types.py
  tests/sentry/event_manager/grouping/test_seer_grouping.py
  tests/sentry/grouping/ingest/test_seer.py
  tests/sentry/issues/endpoints/test_group_similar_issues_embeddings.py
  tests/sentry/seer/similarity/test_similar_issues.py
  tests/sentry/seer/similarity/test_types.py
  tests/sentry/tasks/test_backfill_seer_grouping_records.py
Labels: Scope: Backend

#80229 feat(ui): Constant HookOrDefault usage
  static/app/views/organizationCreate/index.tsx
  static/app/views/settings/components/settingsNavItem.tsx
Labels: Scope: Frontend

#80149 feat(rollback): Add new endpoint to retrieve rollback data
  src/sentry/api/endpoints/organization_user_rollback.py
  src/sentry/api/serializers/models/userrollback.py
  src/sentry/api/urls.py
  tests/sentry/api/endpoints/test_organization_user_rollback.py
Labels: Scope: Backend

#80072 feat(taskworker) Add TaskRegistry and namespace routing
  .github/CODEOWNERS
  src/sentry/conf/server.py
  src/sentry/taskworker/registry.py
  src/sentry/taskworker/router.py
  tests/sentry/taskworker/test_registry.py
  tests/sentry/taskworker/test_task.py
Labels: Scope: Backend

#80224 feat(performance): Swap DropdownLink in trends
  static/app/views/performance/trends/changedTransactions.tsx
  static/app/views/performance/trends/index.spec.tsx
Labels: Scope: Frontend

#79947 feature(workflow_engine): Fetch condition group and conditions and evaluate them
  src/sentry/testutils/fixtures.py
  src/sentry/utils/function_cache.py
  src/sentry/workflow_engine/models/data_condition.py
  src/sentry/workflow_engine/models/detector.py
  tests/sentry/workflow_engine/models/test_detector.py
Labels: Scope: Backend

#80200 fix(issues): Fix links with attachment filters
  static/app/components/events/eventAttachments.spec.tsx
  static/app/components/events/eventAttachmentsCrashReportsNotice.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/screenshotDataSection.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachmentsFilter.tsx
Labels: Scope: Frontend

#80228 feat(issues): Remove escalating issues feedback
  static/app/types/hooks.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.tsx
Labels: Scope: Frontend

#80223 fix(anomaly detection): add anomaly detection feedback key to analytics map
  static/app/utils/analytics/alertsAnalyticsEvents.tsx
  static/app/views/alerts/rules/metric/details/anomalyDetectionFeedbackBanner.spec.tsx
  static/app/views/alerts/rules/metric/details/anomalyDetectionFeedbackBanner.tsx
Labels: Scope: Frontend

#80220 feat(admin): Swap DropdownLink out in ResultsGrid
  static/app/components/resultGrid.tsx
  static/less/result-grid.less
Labels: Scope: Frontend

#80259 feat(issue-details): Add provider specific icon to activities
  static/app/views/issueDetails/streamline/activitySection.tsx
  static/app/views/issueDetails/streamline/groupActivityIcons.tsx
Labels: Scope: Frontend

#80261 build(ui): Support last 4 major safari versions
  package.json
  yarn.lock
Labels: Scope: Frontend

#80008 feat(workflow_engine): Store state updates in stateful detector in the handler, rather than results.
  src/sentry/workflow_engine/models/detector.py
  src/sentry/workflow_engine/processors/detector.py
  src/sentry/workflow_engine/types.py
  tests/sentry/workflow_engine/models/test_detector.py
  tests/sentry/workflow_engine/processors/test_detector.py
Labels: Scope: Backend

#78719 fix(dashboards): Accommodate larger screens on dashboards overview
  static/app/views/dashboards/detail.spec.tsx
  static/app/views/dashboards/manage/dashboardList.spec.tsx
  static/app/views/dashboards/manage/dashboardList.tsx
  static/app/views/dashboards/manage/index.spec.tsx
  static/app/views/dashboards/manage/index.tsx
  static/app/views/dashboards/manage/utils.tsx
Labels: Scope: Frontend

#79999 chore(integrations): RepositoryIntegration metrics
  src/sentry/integrations/source_code_management/metrics.py
  src/sentry/integrations/source_code_management/repository.py
  tests/sentry/integrations/github/test_client.py
Labels: Scope: Backend

#80156 feat(perf): make N+1 DB Query count user-configurable
  src/sentry/api/endpoints/project_performance_issue_settings.py
  tests/sentry/api/endpoints/test_project_performance_issue_settings.py
Labels: Scope: Backend

#80256 fix(celery): fix recursion guard in holds_bad_pickle_object
  src/sentry/celery.py
Labels: Scope: Backend

#80262 fix(dashboards): Increase size of Widget Frame description tooltip icon
  static/app/views/dashboards/widgets/common/widgetFrame.tsx
Labels: Scope: Frontend

#80041 fix(status): Kickoff outbound status sync when updating group statuses
  src/sentry/issues/escalating.py
  src/sentry/issues/status_change_consumer.py
  tests/sentry/issues/test_status_change_consumer.py
Labels: Scope: Backend

#80255 feat(profiling): Add function to query profile examples of different …
  src/sentry/search/events/builder/profile_functions.py
  src/sentry/search/events/datasets/profile_functions.py
  src/sentry/testutils/cases.py
  tests/snuba/api/endpoints/test_organization_events.py
Labels: Scope: Backend

#80266 fix(dashboards): Add explanation tooltip for "Latest Release" in release selector
  static/app/views/dashboards/releasesSelectControl.tsx
Labels: Scope: Frontend

#79950 ref(crons): Prefer passing `ret_type` in croniter constructor
  src/sentry/monitors/schedule.py
Labels: Scope: Backend

#80013 chore(workflow_engine): Move detector handlers to processors
  src/sentry/incidents/grouptype.py
  src/sentry/issues/grouptype.py
  src/sentry/workflow_engine/models/__init__.py
  src/sentry/workflow_engine/models/detector.py
  src/sentry/workflow_engine/processors/detector.py
  tests/sentry/workflow_engine/models/test_detector.py
  tests/sentry/workflow_engine/processors/test_detector.py
Labels: Scope: Backend

#78881 devenv: upgrade colima to 0.7.5
  devenv/config.ini
  devenv/sync.py
Labels: Scope: Backend

#80233 feat(crons): Add cronsim options
  src/sentry/options/defaults.py
Labels: Scope: Backend

#80090 feature(workflow_engine): Add path for producing occurrences/status updates in `process_detectors`
  src/sentry/workflow_engine/processors/detector.py
  tests/sentry/workflow_engine/processors/test_detector.py
Labels: Scope: Backend

#80277 fix(alerts): Remove extra paren
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
Labels: Scope: Frontend

#80151 ref(releases): remove deprecated project_id column from model
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/migrations/0783_remove_release_project_id.py
  src/sentry/models/release.py
  tests/sentry/backup/snapshots/ReleaseTests/test_at_head.pysnap
  tests/sentry/backup/snapshots/ReleaseTests/test_at_head.pysnap.new
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap.new
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap.new
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap.new
Labels: Scope: Frontend, Scope: Backend

#80264 fix(issues): Prevent new icon row from shrinking
  static/app/components/events/highlights/highlightsIconSummary.tsx
Labels: Scope: Frontend

#80118 feat(workflow_engine): Implement basic evaluation in `DataCondition`
  src/sentry/workflow_engine/models/data_condition.py
  tests/sentry/workflow_engine/models/test_data_condition.py
  tests/sentry/workflow_engine/processors/test_detector.py
Labels: Scope: Backend

#80274 feat(trace-explorer): Sort traces by timestamp in EAP
  src/sentry/api/endpoints/organization_traces.py
Labels: Scope: Backend

#80281 fix(anomaly detection): add alerts analytics reqs to utils/analytics.tsx
  static/app/utils/analytics.tsx
Labels: Scope: Frontend

#80271 feat(crons): Add cronsim behind an option
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/monitors/schedule.py
  src/sentry/monitors/validators.py
  tests/sentry/monitors/test_schedule.py
Labels: Scope: Backend

#80270 feat(issue summary) Update issue summary model
  src/sentry/api/endpoints/group_ai_summary.py
  tests/sentry/api/endpoints/test_group_ai_summary.py
Labels: Scope: Backend

#80284 feat(issue-details): Hide merged/similar issues for non-error issues
  static/app/views/issueDetails/streamline/sidebar.tsx
Labels: Scope: Frontend

#80278 ref(crons): Switch to cronsim in sample data generator
  src/sentry/monitors/endpoints/organization_monitor_schedule_sample_data.py
Labels: Scope: Backend

#80276 feat(insights): Add insights query date range footer hook
  static/app/types/hooks.tsx
  static/app/views/insights/common/components/modulePageFilterBar.tsx
Labels: Scope: Frontend

#80122 feat(workflow_engine): Return status change messages when a stateful detector resolves
  src/sentry/workflow_engine/models/detector.py
  src/sentry/workflow_engine/processors/detector.py
  tests/sentry/workflow_engine/processors/test_detector.py
Labels: Scope: Backend

#80273 feat(issue summary) New structured issue summary design
  static/app/components/group/groupSummary.spec.tsx
  static/app/components/group/groupSummary.tsx
  static/app/views/issueDetails/streamline/solutionsDrawer.tsx
  static/app/views/issueDetails/streamline/solutionsSection.tsx
Labels: Scope: Frontend

#80168 feat(workflow_engine): Add in hook for producing occurrences from the stateful detector
  src/sentry/incidents/grouptype.py
  src/sentry/workflow_engine/models/detector.py
  src/sentry/workflow_engine/processors/detector.py
  tests/sentry/workflow_engine/processors/test_detector.py
Labels: Scope: Backend

#80295 fix(issues): Preserve query parameters on all events close
  static/app/views/issueDetails/streamline/eventNavigation.tsx
Labels: Scope: Frontend

#80297 fix(issues): All event table pagination counts
  static/app/views/issueDetails/streamline/eventList.spec.tsx
  static/app/views/issueDetails/streamline/eventList.tsx
Labels: Scope: Frontend

#80296 feat(issues): Rearrange all events columns, sizes
  static/app/views/issueDetails/allEventsTable.tsx
  static/app/views/issueDetails/streamline/eventList.tsx
Labels: Scope: Frontend

#80201 chore(broadcasts): remove cta column from broadcast model
  migrations_lockfile.txt
  src/sentry/api/endpoints/broadcast_index.py
  src/sentry/api/serializers/models/broadcast.py
  src/sentry/migrations/0784_remove_broadcasts_cta_column.py
  src/sentry/models/broadcast.py
  tests/sentry/api/endpoints/test_broadcast_index.py
Labels: Scope: Backend

#80236 feat(profiling): add organizations:continuous-profiling to the list of exposable features
  src/sentry/features/temporary.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#80304 feat(dynamic-sampling): Sampling breakdown
  static/app/views/settings/dynamicSampling/organizationSampleRateField.tsx
  static/app/views/settings/dynamicSampling/percentInput.tsx
  static/app/views/settings/dynamicSampling/projectsEditTable.tsx
  static/app/views/settings/dynamicSampling/projectsTable.tsx
  static/app/views/settings/dynamicSampling/samplingBreakdown.tsx
Labels: Scope: Frontend

#80203 fix(releases): check project-level access for actions on existing releases
  src/sentry/api/endpoints/organization_releases.py
  tests/sentry/api/endpoints/test_organization_releases.py
Labels: Scope: Backend

#80307 fix(dynamic-sampling): Loop over paginated results
  static/app/views/settings/dynamicSampling/utils/useSamplingProjectRates.tsx
Labels: Scope: Frontend

#80286 chore(profiling): Update wording to match nodejs continuous profiling
  static/app/gettingStartedDocs/python/celery.tsx
  static/app/gettingStartedDocs/python/python.tsx
  static/app/gettingStartedDocs/python/rq.tsx
Labels: Scope: Frontend

#80147 feat(profiling): Add continuous profiling onboarding for cocoa
  static/app/gettingStartedDocs/apple/ios.spec.tsx
  static/app/gettingStartedDocs/apple/ios.tsx
  static/app/gettingStartedDocs/apple/macos.spec.tsx
  static/app/gettingStartedDocs/apple/macos.tsx
  static/app/utils/profiling/platforms.spec.tsx
  static/app/utils/profiling/platforms.tsx
Labels: Scope: Frontend

#80314 chore(profiling): pofiler -> profiler
  static/app/gettingStartedDocs/python/celery.tsx
  static/app/gettingStartedDocs/python/python.tsx
  static/app/gettingStartedDocs/python/rq.tsx
Labels: Scope: Frontend

#80302 ref(py): Replace usage of croniter with cronsim
  src/sentry/api/helpers/deprecation.py
  tests/sentry/helpers/test_deprecation.py
Labels: Scope: Backend

#80244 chore: Bump sentry-protos to 0.1.33
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#80023 feat(backpressure): split ingest-transactions out from ingest
  src/sentry/conf/server.py
  src/sentry/ingest/consumer/factory.py
  src/sentry/processing/backpressure/arroyo.py
  src/sentry/processing/backpressure/monitor.py
  src/sentry/processing/backpressure/topology.py
  tests/sentry/processing/backpressure/test_checking.py
  tests/sentry/processing/backpressure/test_monitoring.py
Labels: Scope: Backend

#80247 feat(perf): expose N+1 DB Query count threshold in settings
  static/app/views/settings/projectPerformance/projectPerformance.spec.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#80316 fix(profiling): Handle malformed debug file ids in profiles
  src/sentry/profiles/task.py
Labels: Scope: Backend

#80301 fix(autofix): Add null check for root cause code context
  static/app/components/events/autofix/autofixRootCause.tsx
Labels: Scope: Frontend

#80319 perf(warmup): warmup url resolver for all supported languages
  src/sentry/api/endpoints/warmup.py
  tests/sentry/test_wsgi.py
Labels: Scope: Backend

#80321 feat(explore): wider breakpoint
  static/app/views/explore/content.tsx
Labels: Scope: Frontend

#80272 ref(replay): add flutter onboarding to sidebar
  static/app/components/onboarding/gettingStartedDoc/utils/replayOnboarding.tsx
  static/app/data/platformCategories.tsx
  static/app/gettingStartedDocs/flutter/flutter.tsx
  static/app/utils/replays/projectSupportsReplay.spec.tsx
Labels: Scope: Frontend

#80318 ref: GHA ubuntu 22.04 -> ubuntu 24.04
  .github/workflows/acceptance.yml
  .github/workflows/backend.yml
  .github/workflows/bump-sentry-in-getsentry.yml
  .github/workflows/codecov_ats.yml
  .github/workflows/codecov_per_test_coverage.yml
  .github/workflows/development-environment.yml
  .github/workflows/frontend-lint-burndown.yml
  .github/workflows/frontend.yml
  .github/workflows/getsentry-dispatch.yml
  .github/workflows/jest-balance.yml
  .github/workflows/label-pullrequest.yml
  .github/workflows/meta-deploys-detect-change-type.yml
  .github/workflows/migrations.yml
  .github/workflows/openapi-diff.yml
  .github/workflows/openapi.yml
  .github/workflows/pre-commit.yml
  .github/workflows/publish-dockerhub.yml
  .github/workflows/sentry-pull-request-bot.yml
  .github/workflows/shuffle-tests.yml
  .github/workflows/test_docker_compose_acceptance.yml
  .github/workflows/test_docker_compose_backend.yml
Labels: Scope: Frontend, Scope: Backend

#80269 fix(discover): Account for measurement units in events-meta
  src/sentry/api/endpoints/organization_events_meta.py
  src/sentry/data_export/endpoints/data_export.py
  tests/snuba/api/endpoints/test_organization_events_meta.py
Labels: Scope: Backend

#80136 ref(dashboards): Add new attribute to Dashboards Perms Model #79909
  fixtures/backup/model_dependencies/detailed.json
  fixtures/backup/model_dependencies/flat.json
  fixtures/backup/model_dependencies/sorted.json
  fixtures/backup/model_dependencies/truncate.json
  migrations_lockfile.txt
  src/sentry/api/serializers/models/dashboard.py
  src/sentry/api/serializers/rest_framework/dashboard.py
  src/sentry/apidocs/examples/dashboard_examples.py
  src/sentry/migrations/0785_add_new_field_to_dashboard_permissions.py
  src/sentry/models/dashboard_permissions.py
  src/sentry/testutils/helpers/backups.py
  tests/sentry/api/endpoints/test_organization_dashboard_details.py
  tests/sentry/api/endpoints/test_organization_dashboards.py
  tests/sentry/backup/snapshots/ReleaseTests/test_at_head.pysnap
  tests/sentry/backup/snapshots/SanitizationExhaustiveTests/test_clean_pks.pysnap
  tests/sentry/backup/snapshots/test_comparators/test_default_comparators.pysnap
  tests/sentry/tasks/snapshots/PreprocessingTransferTest/test_success.pysnap
Labels: Scope: Frontend, Scope: Backend

#80288 feat(crons): Remove usage of croniter
  src/sentry/monitors/schedule.py
  src/sentry/monitors/validators.py
  tests/sentry/monitors/endpoints/test_organization_monitor_index.py
  tests/sentry/monitors/test_schedule.py
Labels: Scope: Backend

#80324 fix(context): Display expected OS fields nicely
  static/app/components/events/contexts/operatingSystem/getOperatingSystemKnownDataDetails.spec.tsx
  static/app/components/events/contexts/operatingSystem/getOperatingSystemKnownDataDetails.tsx
  static/app/components/events/contexts/operatingSystem/index.spec.tsx
  static/app/components/events/contexts/operatingSystem/index.tsx
  static/app/components/events/contexts/operatingSystem/types.tsx
Labels: Scope: Frontend

#80323 feat(issue-details): Add better conditions for solution center
  static/app/views/issueDetails/streamline/sidebar.tsx
  static/app/views/issueDetails/streamline/solutionsDrawer.tsx
  static/app/views/issueDetails/streamline/solutionsSection.tsx
Labels: Scope: Frontend

#80303 ref(py): Remove unused croniter library
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-dev.txt
  requirements-frozen.txt
Labels: Scope: Backend

#80292 feat(crons): Remove cronsim option
  src/sentry/options/defaults.py
Labels: Scope: Backend

#80158 test(trace) remove test skip and stop mocking console error
  static/app/utils/useDispatchingReducer.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/trace.spec.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTraceRootEvent.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTransaction.tsx
  static/app/views/performance/newTraceDetails/traceHeader/index.tsx
  static/app/views/performance/newTraceDetails/tracePreferencesDropdown.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchInput.tsx
  static/app/views/performance/newTraceDetails/traceState/traceRovingTabIndex.tsx
  static/app/views/performance/newTraceDetails/traceState/traceSearch.tsx
  static/app/views/performance/newTraceDetails/traceState/traceTabs.tsx
Labels: Scope: Frontend

#80152 feat(profiling) add continuous profiling docs
  static/app/gettingStartedDocs/node/awslambda.spec.tsx
  static/app/gettingStartedDocs/node/azurefunctions.spec.tsx
  static/app/gettingStartedDocs/node/connect.spec.tsx
  static/app/gettingStartedDocs/node/express.spec.tsx
  static/app/gettingStartedDocs/node/fastify.spec.tsx
  static/app/gettingStartedDocs/node/gcpfunctions.spec.tsx
  static/app/gettingStartedDocs/node/hapi.spec.tsx
  static/app/gettingStartedDocs/node/koa.spec.tsx
  static/app/gettingStartedDocs/node/nestjs.spec.tsx
  static/app/gettingStartedDocs/node/node.spec.tsx
  static/app/utils/gettingStartedDocs/node.ts
  tests/js/sentry-test/onboarding/renderWithOnboardingLayout.tsx
Labels: Scope: Frontend
