Repository getsentry/sentry, pull requests merged in 2025-07, with the labels that each got.

#94627 fix(replay): Improve usability of the tooltip for Network Url column
  static/app/views/replays/detail/network/networkTableCell.tsx
Labels: Scope: Frontend

#94586 chore(integrations): Add SLOs to finish_pipeline
  src/sentry/integrations/base.py
  src/sentry/integrations/pipeline.py
  src/sentry/integrations/utils/metrics.py
  tests/sentry/integrations/test_pipeline.py
Labels: Scope: Backend

#94516 feat: Remove quick start opening automatically on second visit
  static/app/components/performanceOnboarding/sidebar.spec.tsx
  static/app/components/sidebar/index.spec.tsx
  static/app/components/sidebar/onboardingStatus.spec.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/types/user.tsx
  static/app/utils/analytics/quickStartAnalyticsEvents.tsx
  static/app/views/nav/primary/onboarding.spec.tsx
  static/app/views/nav/primary/onboarding.tsx
  tests/js/fixtures/activityFeed.ts
  tests/js/fixtures/commitAuthor.ts
  tests/js/fixtures/user.ts
  tests/js/fixtures/userDetails.ts
Labels: Scope: Frontend

#94517 ref: Remove quick start user option
  src/sentry/users/api/endpoints/user_details.py
  src/sentry/users/api/serializers/user.py
  src/sentry/users/models/user_option.py
  tests/sentry/users/api/endpoints/test_user_details.py
Labels: Scope: Backend

#94628 gsapp: remove use of linkStyles
  static/gsApp/components/powerFeatureHovercard.tsx
Labels: Scope: Frontend

#94534 ref: convert AuditLogEntry.data to django JSONField
  migrations_lockfile.txt
  src/sentry/migrations/0940_auditlog_json_field.py
  src/sentry/models/auditlogentry.py
  tests/sentry/api/endpoints/test_organization_auditlogs.py
Labels: Scope: Backend

#94681 fix(feedback): Fix padding in crash report dialog
  src/sentry/templates/sentry/error-page-embed.html
Labels: Scope: Backend

#94671 fix(organizations): Improve autocomplete on org creation
  static/app/views/organizationCreate/index.tsx
Labels: Scope: Frontend

#94458 chore(launchpad): allow for easy local testing, set default secret for dev
  src/sentry/conf/server.py
Labels: Scope: Backend

#94674 feat(aci): handle special case for issue priority deescalating data condition
  static/app/types/workflowEngine/dataConditions.tsx
  static/app/views/automations/components/dataConditionNodeList.tsx
Labels: Scope: Frontend

#94699 fix(issues): Fix issue error title overflow
  static/app/views/issueDetails/streamline/header/header.tsx
Labels: Scope: Frontend

#94210 chore(detectors): Add settings for Query Injection Detectors FE
  static/app/types/group.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#94643 fix(aci): Use activity time for regression open periods
  src/sentry/event_manager.py
  tests/sentry/event_manager/test_event_manager.py
Labels: Scope: Backend

#94703 fix(provisioning): Don't include test plans
  static/gsAdmin/components/provisionSubscriptionAction.tsx
Labels: Scope: Frontend

#94698 fix(aci): Retry process_workflows_event tasks
  src/sentry/workflow_engine/tasks.py
Labels: Scope: Backend

#94599 bootstrap: remove bootstrap buttons from react
  static/app/components/resultGrid.tsx
  static/app/plugins/components/issueActions.tsx
  static/app/plugins/jira/components/settings.tsx
  static/app/plugins/sessionstack/components/settings.tsx
  static/app/plugins/sessionstack/contexts/sessionstack.tsx
  static/gsApp/components/gsBanner.tsx
  static/gsApp/components/helpSearchFooter.tsx
  static/gsApp/components/replayZendeskFeedback.tsx
  static/gsApp/components/zendeskLink.tsx
  static/gsApp/hooks/sidebarHelpMenu.tsx
Labels: Scope: Frontend

#94636 feat(launchpad): Add launchpad RPC authentication support to the chunking endpoint
  src/sentry/api/endpoints/chunk.py
  tests/sentry/api/endpoints/test_chunk_upload.py
Labels: Scope: Backend

#94653 feat(replay): Create an Audit Log for bulk Replay Deletes inside /settings
  static/app/components/replays/bulkDelete/replayBulkDeleteAuditLog.tsx
  static/app/components/replays/bulkDelete/replayBulkDeleteAuditLogTable.tsx
  static/app/components/replays/bulkDelete/types.tsx
  static/app/components/replays/bulkDelete/useFetchBulkDeleteLogs.tsx
  static/app/views/settings/project/projectReplays.tsx
Labels: Scope: Frontend

#94673 feat(replay): add feedback buttons on replay ai tab
  static/app/views/replays/detail/ai/index.tsx
Labels: Scope: Frontend

#94723 fix(auth-v2): Get secret from env var
  src/sentry/conf/server.py
Labels: Scope: Backend

#94702 feat(issues): Add support for AWS trace parameterization
  src/sentry/grouping/parameterization.py
  tests/sentry/grouping/test_parameterization.py
Labels: Scope: Backend

#94677 feat(aci): add issue category data condition
  static/app/views/automations/components/actionFilters/issueCategory.tsx
  static/app/views/automations/components/dataConditionNodes.tsx
Labels: Scope: Frontend

#94725 chore(launchpad): make artifact upload task idempotent
  src/sentry/preprod/tasks.py
Labels: Scope: Backend

#94590 ref(replay): Convert ReplayTable to use SimpleTable under the hood
  static/app/components/events/eventReplay/replayPreviewPlayer.tsx
  static/app/components/replays/table/replayTable.tsx
  static/app/components/replays/table/replayTableColumns.tsx
  static/app/components/replays/table/useReplayTableSort.tsx
  static/app/utils/replays/hooks/useFetchReplayList.ts
  static/app/views/issueDetails/groupReplays/groupReplays.spec.tsx
  static/app/views/issueDetails/groupReplays/groupReplays.tsx
  static/app/views/performance/transactionSummary/transactionReplays/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionReplays/transactionReplays.tsx
  static/app/views/replays/deadRageClick/exampleReplaysList.tsx
  static/app/views/replays/jetpackComposePiiNotice.tsx
  static/app/views/replays/list/listContent.spec.tsx
  static/app/views/replays/list/listContent.tsx
  static/app/views/replays/list/replaysList.tsx
  static/app/views/replays/replayTable/headerCell.tsx
  static/app/views/replays/replayTable/index.tsx
  static/app/views/replays/replayTable/sortableHeader.tsx
  static/app/views/replays/replayTable/tableCell.tsx
  static/app/views/replays/replayTable/types.tsx
  static/app/views/replays/table/replayIndexTable.tsx
Labels: Scope: Frontend

#94569 feat(replay): Update design of Replay Summaries
  static/app/views/replays/detail/ai/ai.tsx
  static/app/views/replays/detail/ai/chapterList.tsx
  static/app/views/replays/detail/ai/index.tsx
  static/app/views/replays/detail/ai/useFetchReplaySummary.tsx
  static/app/views/replays/detail/layout/focusArea.tsx
Labels: Scope: Frontend

#94733 fix(replay): fix feedbackId casing in breadcrumb endpoint
  src/sentry/replays/endpoints/project_replay_summarize_breadcrumbs.py
  tests/sentry/replays/test_project_replay_summarize_breadcrumbs.py
Labels: Scope: Backend

#94676 feat(aci): Add support for logs metric detectors
  static/app/types/workflowEngine/detectors.tsx
  static/app/views/detectors/components/forms/metric/getDatasetConfig.tsx
  static/app/views/detectors/components/forms/metric/metric.tsx
  static/app/views/detectors/components/forms/metric/metricFormData.tsx
  static/app/views/detectors/components/forms/metric/useCustomMeasurements.tsx
  static/app/views/detectors/components/forms/metric/visualize.tsx
  static/app/views/detectors/list.spec.tsx
  tests/js/fixtures/detectors.ts
Labels: Scope: Frontend

#94740 fix(dropdownmenu): Make submenu dismissable
  static/app/components/dropdownMenu/index.spec.tsx
  static/app/components/dropdownMenu/list.tsx
Labels: Scope: Frontend

#94741 ref: Move hooks `useQueryParamState()` and `urlParamBatchContext()` into `utils/`
  static/app/utils/url/urlParamBatchContext.spec.tsx
  static/app/utils/url/urlParamBatchContext.tsx
  static/app/utils/url/useQueryParamState.spec.tsx
  static/app/utils/url/useQueryParamState.tsx
  static/app/views/dashboards/widgetBuilder/contexts/widgetBuilderContext.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.tsx
Labels: Scope: Frontend

#94716 chore(billing): Cleanup NextPlanInfo interface and related tests
  static/gsApp/types/index.tsx
  static/gsApp/views/subscriptionPage/planMigrationActive/index.spec.tsx
  static/gsApp/views/subscriptionPage/planMigrationActive/planMigrationTable.tsx
  tests/js/getsentry-test/fixtures/planMigration.ts
Labels: Scope: Frontend

#94749 ref: Colocate sentry/utils tests with the implementation
  static/app/utils.spec.tsx
  static/app/utils/utils.spec.tsx
Labels: Scope: Frontend

#94746 ref: Move `<Accordion>` into components/containers/ where it can be found and re-used by others
  static/app/components/container/accordion.spec.tsx
  static/app/components/container/accordion.tsx
  static/app/views/replays/deadRageClick/deadRageSelectorCards.tsx
  static/app/views/replays/list/replayOnboardingPanel.tsx
Labels: Scope: Frontend

#94635 ref(trace): Remove `Detecting missing instrumentation` error
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
Labels: Scope: Frontend

#94742 ref: Move useUrlParams() to utls/url/ with simiar hooks
  static/app/components/events/featureFlags/onboarding/featureFlagOnboardingSidebar.tsx
  static/app/components/feedback/feedbackOnboarding/sidebar.tsx
  static/app/components/feedback/list/feedbackListHeader.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/useCurrentProjectState.ts
  static/app/components/replays/table/useReplayTableSort.tsx
  static/app/components/replays/virtualizedGrid/useDetailsSplit.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/utils/replays/hooks/useActiveReplayTab.tsx
  static/app/utils/replays/hooks/useReplayLayout.tsx
  static/app/utils/url/useUrlParams.spec.tsx
  static/app/utils/url/useUrlParams.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useDashboardWidgetSource.tsx
  static/app/views/issueDetails/groupDistributions/useDrawerTab.tsx
  static/app/views/replays/detail/errorList/useSortErrors.spec.tsx
  static/app/views/replays/detail/errorList/useSortErrors.tsx
  static/app/views/replays/detail/network/details/index.tsx
  static/app/views/replays/detail/network/details/tabs.tsx
  static/app/views/replays/detail/network/networkTableCell.tsx
  static/app/views/replays/detail/network/useSortNetwork.spec.tsx
  static/app/views/replays/detail/network/useSortNetwork.tsx
  static/app/views/settings/project/projectReplays.tsx
Labels: Scope: Frontend

#94612 fix(onboarding): removing some unknown attributes from python sample event
  src/sentry/data/samples/python-modern.json
Labels: Scope: Backend

#94685 chore(demo-mode): remove unused options
  src/sentry/options/defaults.py
Labels: Scope: Backend

#94769 ref: Introduce useApiQuery in stats admin for fetching statsv2
  static/gsAdmin/components/customers/customerStats.tsx
Labels: Scope: Frontend

#94689 feat: Add visual feedback for loader script & describe defaults
  static/app/components/onboarding/gettingStartedDoc/types.ts
  static/app/components/onboarding/productSelection.spec.tsx
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/jsLoader/updateDynamicSdkLoaderOptions.ts
Labels: Scope: Frontend

#94771 fix: layout of old llm monitoring callout
  static/app/views/insights/agentMonitoring/components/legacyLlmMonitoringAlert.tsx
Labels: Scope: Frontend

#94665 fix(flutter): glob of dart file in `stack.abs_path`
  src/sentry/grouping/enhancer/enhancement-configs/newstyle@2023-01-11.txt
Labels: Scope: Backend

#94770 test(unreal): Enable unreal e2e tests again
  tests/symbolicator/snapshots/SymbolicatorUnrealIntegrationTest/test_unreal_crash_with_attachments.pysnap
  tests/symbolicator/snapshots/SymbolicatorUnrealIntegrationTest/test_unreal_crash_with_attachments_new.pysnap
  tests/symbolicator/test_unreal_full.py
Labels: Do Not Merge, Scope: Backend

#94715 fix: trace waterfall colors
  static/app/views/performance/newTraceDetails/trace.tsx
Labels: Scope: Frontend

#94765 fix: missing `api.performance.browser.web-vitals.project-scores.metrics-enhanced.primary` referrer enum from snuba
  src/sentry/snuba/referrer.py
Labels: Scope: Backend, Trigger: getsentry tests

#94773 feat(agent-monitoring): Allow filtering by span attributes
  static/app/views/insights/agentMonitoring/components/llmGenerationsWidget.tsx
  static/app/views/insights/agentMonitoring/components/modelsTable.tsx
  static/app/views/insights/agentMonitoring/components/tokenUsageWidget.tsx
  static/app/views/insights/agentMonitoring/components/toolUsageWidget.tsx
  static/app/views/insights/agentMonitoring/components/toolsTable.tsx
  static/app/views/insights/agentMonitoring/components/tracesTable.tsx
  static/app/views/insights/agentMonitoring/hooks/useCombinedQuery.tsx
  static/app/views/insights/agentMonitoring/utils/query.tsx
  static/app/views/insights/agentMonitoring/views/agentsOverviewPage.tsx
  static/app/views/insights/common/components/widgets/overviewAgentsDurationChartWidget.tsx
  static/app/views/insights/common/components/widgets/overviewAgentsRunsChartWidget.tsx
  static/app/views/insights/common/components/widgets/overviewPageloadsChartWidget.tsx
  static/app/views/insights/common/components/widgets/overviewRequestsChartWidget.tsx
  static/app/views/insights/pages/platform/shared/baseLatencyWidget.tsx
  static/app/views/insights/pages/platform/shared/baseTrafficWidget.tsx
Labels: Scope: Frontend

#94597 feat(uptime): Use EAP to query in `organization_uptime_stats`
  src/sentry/features/temporary.py
  src/sentry/uptime/endpoints/organization_uptime_stats.py
  tests/sentry/uptime/endpoints/test_organization_uptime_stats.py
  tests/snuba/api/endpoints/test_organization_events_uptime_results.py
Labels: Scope: Backend

#94754 fix(detectors): Fix redis key deletion in `should_create_group`
  src/sentry/issues/grouptype.py
Labels: Scope: Backend

#94789 chore(explore): Render trace start timestamp
  static/app/views/explore/tables/tracesTable/index.tsx
Labels: Scope: Frontend

#94787 perf(uptime): Wrap item process w/ a span
  src/sentry/remote_subscriptions/consumers/result_consumer.py
Labels: Scope: Backend

#94712 :wrench: chore(data-secrecy v2): set up FF
  src/sentry/features/temporary.py
Labels: Scope: Backend

#94784 typing: A few modules
  pyproject.toml
  src/sentry/eventstore/processing/bigtable.py
  src/sentry/eventstore/processing/redis.py
  tests/sentry/nodestore/bigtable/test_backend.py
  tests/sentry/utils/kvstore/test_bigtable.py
Labels: Scope: Backend

#94573 feat(replay): Set AI tab as default for eligible users
  static/app/utils/replays/hooks/useActiveReplayTab.spec.tsx
  static/app/utils/replays/hooks/useActiveReplayTab.tsx
Labels: Scope: Frontend

#94498 feat(replay): add trace connected error context to LLM
  src/sentry/replays/endpoints/project_replay_summarize_breadcrumbs.py
  src/sentry/snuba/referrer.py
  tests/sentry/replays/test_project_replay_summarize_breadcrumbs.py
Labels: Scope: Backend

#94801 feat(replay): add seer branding to ai summary tab
  static/app/views/replays/detail/ai/ai.tsx
Labels: Scope: Frontend

#94785 fix(spans): Allow trace ids of length 8 to 31
  src/sentry/search/eap/spans/filter_aliases.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#94799 fix(seer): Check gen ai toggle before running automation
  src/sentry/integrations/utils/issue_summary_for_alerts.py
  src/sentry/seer/autofix.py
  src/sentry/seer/issue_summary.py
  src/sentry/tasks/post_process.py
  tests/sentry/integrations/utils/test_issue_summary_for_alerts.py
  tests/sentry/seer/test_autofix.py
  tests/sentry/seer/test_issue_summary.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#94788 fix(insights): Updates transaction summary tabs to show old web vitals for am1 customers
  static/app/views/performance/transactionSummary/header.tsx
  static/app/views/performance/transactionSummary/pageLayout.tsx
Labels: Scope: Frontend

#94811 ref(aci) add missing feature flags to temp.py
  src/sentry/features/temporary.py
Labels: Scope: Backend

#94696 quality(apidocs): use drf_spectacular for documenting org eventid endpoint
  api-docs/openapi.json
  api-docs/paths/organizations/event-id-lookup.json
  src/sentry/apidocs/examples/organization_examples.py
  src/sentry/apidocs/parameters.py
  src/sentry/issues/endpoints/organization_eventid.py
Labels: Scope: Backend

#94814 fix(ourlogs): Make body grow to full height if possible
  static/app/views/explore/logs/styles.tsx
Labels: Scope: Frontend

#94813 fix(seer): typo in seer flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#94751 feat(detectors): Update fingerprint + description for query injection issues
  src/sentry/performance_issues/detectors/query_injection_detector.py
  src/sentry/performance_issues/detectors/sql_injection_detector.py
  tests/sentry/performance_issues/test_query_injection_detector.py
  tests/sentry/performance_issues/test_sql_injection_detector.py
Labels: Scope: Backend

#94791 ref(aci): clean up `updateIfAction` reducer action
  static/app/views/automations/components/actions/email.tsx
  static/app/views/automations/components/actions/integrationField.tsx
  static/app/views/automations/components/actions/sentryApp.tsx
  static/app/views/automations/components/actions/serviceField.tsx
  static/app/views/automations/components/actions/slack.tsx
  static/app/views/automations/components/actions/tagsField.tsx
  static/app/views/automations/components/actions/targetDisplayField.tsx
  static/app/views/automations/components/actions/webhook.tsx
  static/app/views/automations/components/automationBuilderContext.tsx
Labels: Scope: Frontend

#94755 feat(uptime): Use EAP to query in `project_uptime_alert_checks_index`
  src/sentry/search/eap/uptime_results/attributes.py
  src/sentry/uptime/endpoints/project_uptime_alert_checks_index.py
  tests/sentry/uptime/endpoints/__init__.py
  tests/sentry/uptime/endpoints/test_base.py
  tests/sentry/uptime/endpoints/test_organization_uptime_stats.py
  tests/sentry/uptime/endpoints/test_project_uptime_alert_check_index.py
  tests/snuba/api/endpoints/test_organization_events_uptime_results.py
Labels: Scope: Backend

#94821 fix(uptime): Reduce queries in uptime consumer.
  src/sentry/uptime/models.py
Labels: Scope: Backend

#94825 chore(auth-v2): Find missing headers
  src/sentry/auth_v2/endpoints/base.py
Labels: Scope: Backend

#94559 chore(gitlab): Mark ApiHostError as halt
  src/sentry/integrations/gitlab/blame.py
  src/sentry/integrations/source_code_management/commit_context.py
  tests/sentry/integrations/gitlab/test_client.py
  tests/sentry/integrations/source_code_management/test_commit_context.py
Labels: Scope: Backend

#94828 fix(uptime): Pass request.user to feature flag check
  src/sentry/uptime/endpoints/organization_uptime_stats.py
  src/sentry/uptime/endpoints/project_uptime_alert_checks_index.py
Labels: Scope: Backend

#94836 fix(uptime): Fix uptime eap result queries to use correct subscriptio…
  src/sentry/uptime/endpoints/organization_uptime_stats.py
  src/sentry/uptime/endpoints/project_uptime_alert_checks_index.py
  tests/sentry/uptime/endpoints/test_organization_uptime_stats.py
  tests/sentry/uptime/endpoints/test_project_uptime_alert_check_index.py
Labels: Scope: Backend

#94845 feat(agent-monitoring): Enable project selector persistence
  static/app/views/insights/agentMonitoring/settings.ts
  static/app/views/insights/agentMonitoring/views/agentsOverviewPage.tsx
  static/app/views/insights/common/utils/moduleTitles.tsx
  static/app/views/insights/pages/platform/shared/layout.tsx
  static/app/views/insights/pages/settings.ts
  static/app/views/insights/pages/types.ts
  static/app/views/insights/pages/useFilters.tsx
  static/app/views/insights/sessions/components/chartMap.tsx
Labels: Scope: Frontend

#93425 feat(outcomes): add invalid signature as discard reason
  static/app/views/organizationStats/getReasonGroupName.spec.ts
  static/app/views/organizationStats/getReasonGroupName.ts
Labels: Scope: Frontend

#94843 fix(agent-insights): Prevent double counting tokens and cost
  static/app/views/insights/agentMonitoring/components/aiSpanList.tsx
  static/app/views/insights/agentMonitoring/components/tracesTable.tsx
  static/app/views/insights/agentMonitoring/utils/query.tsx
Labels: Scope: Frontend

#94852 feat(insights): Redirect to last used domain view
  static/app/routes.tsx
  static/app/views/insights/common/utils/domainRedirect.tsx
  static/app/views/insights/index.tsx
  static/app/views/insights/pages/useFilters.tsx
  static/app/views/nav/primary/index.tsx
  static/app/views/organizationLayout/index.tsx
Labels: Scope: Frontend

#94854 fix(ai): Strip provider from the model name
  src/sentry/tasks/ai_agent_monitoring.py
  tests/sentry/tasks/test_ai_agent_monitoring.py
Labels: Scope: Backend

#94798 feat(search-bar): Add search Ask Seer button
  static/app/components/searchQueryBuilder/askSeer.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/combobox.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/index.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/types.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/utils.tsx
  static/app/components/searchQueryBuilder/tokens/useSortedFilterKeyItems.tsx
Labels: Scope: Frontend

#94697 ref(span-buffer): Make join() faster by dropping idempotent work
  src/sentry/spans/consumers/process/factory.py
  src/sentry/utils/arroyo.py
  tests/sentry/spans/consumers/process/test_consumer.py
Labels: Scope: Backend

#94859 feat(agent-monitoring): open 2 charts in explore
  static/app/views/insights/agentMonitoring/components/modelsTable.tsx
  static/app/views/insights/agentMonitoring/components/toolsTable.tsx
  static/app/views/insights/agentMonitoring/components/tracesTable.tsx
Labels: Scope: Frontend

#94865 fix(log-alert): Use correct query param in open in logs
  static/app/views/alerts/rules/utils.tsx
Labels: Scope: Frontend

#94577 feat(explore): Allow separate sort bys in samples and aggregates
  static/app/views/explore/contexts/pageParamsContext/aggregateSortBys.tsx
  static/app/views/explore/contexts/pageParamsContext/index.spec.tsx
  static/app/views/explore/contexts/pageParamsContext/index.tsx
  static/app/views/explore/contexts/pageParamsContext/sortBys.tsx
  static/app/views/explore/multiQueryMode/locationUtils.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  static/app/views/explore/toolbar/index.tsx
  static/app/views/explore/toolbar/toolbarSortBy.tsx
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#94867 feat(ourlogs): Increase max allowed results in logs to 9999
  src/sentry/api/endpoints/organization_events.py
  src/sentry/api/endpoints/organization_trace_logs.py
Labels: Scope: Backend

#94871 fix(dashboards): Add debugging for errors in dashboards reordering
  src/sentry/api/endpoints/organization_dashboards_starred.py
  src/sentry/models/dashboard.py
Labels: Scope: Backend

#94616 profiling: fix small overlapping on corner
  static/app/views/performance/transactionSummary/transactionProfiles/content.tsx
  static/app/views/profiling/profileSummary/index.tsx
Labels: Scope: Frontend

#94817 ref(traces): Remove `hiddenAttributes` prop from `AttributeTree`
  static/app/views/explore/components/traceItemAttributes/attributesTree.tsx
  static/app/views/explore/logs/tables/logsTableRow.spec.tsx
  static/app/views/explore/logs/tables/logsTableRow.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/eapSections/attributes.tsx
Labels: Scope: Frontend

#94870 feat(insights): adds empty state onboarding to mobile vitals
  static/app/views/insights/common/components/modulesOnboarding.tsx
  static/app/views/insights/common/queries/useHasFirstSpan.tsx
  static/app/views/insights/mobile/screens/settings.ts
  static/app/views/insights/mobile/screens/views/screensLandingPage.spec.tsx
  static/app/views/insights/mobile/screens/views/screensLandingPage.tsx
Labels: Scope: Frontend

#94824 feat(explore): Autocomplete equations with different types
  static/app/components/arithmeticBuilder/context.tsx
  static/app/components/arithmeticBuilder/index.spec.tsx
  static/app/components/arithmeticBuilder/index.tsx
  static/app/components/arithmeticBuilder/token/freeText.tsx
  static/app/components/arithmeticBuilder/token/function.tsx
  static/app/components/arithmeticBuilder/token/index.spec.tsx
  static/app/components/arithmeticBuilder/types.tsx
  static/app/utils/fields/index.ts
  static/app/views/explore/components/schemaHints/schemaHintsList.spec.tsx
  static/app/views/explore/tables/aggregateColumnEditorModal.tsx
  static/app/views/explore/toolbar/toolbarVisualize.tsx
Labels: Scope: Frontend

#94884 feat(dashboards): add sorting to non-issues table widgets
  static/app/views/dashboards/dashboard.tsx
  static/app/views/dashboards/sortableWidget.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetPreview.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/index.tsx
  static/app/views/dashboards/widgetCard/widgetCardChartContainer.tsx
Labels: Scope: Frontend

#94858 feat(ai): Options for custom model cost mappings
  src/sentry/options/defaults.py
  src/sentry/tasks/ai_agent_monitoring.py
  tests/sentry/tasks/test_ai_agent_monitoring.py
Labels: Scope: Backend

#94897 feat: Add image/avif type support to attachments
  static/app/components/events/attachmentViewers/previewAttachmentTypes.tsx
Labels: Scope: Frontend

#94899 ref: Make video render comp. more generic by renaming it
  static/app/components/events/attachmentViewers/previewAttachmentTypes.tsx
  static/app/components/events/attachmentViewers/webmViewer.tsx
Labels: Scope: Frontend

#94900 fix(agent-insights): Correctly set feedback source and owner
  static/app/views/insights/pages/domainViewHeader.tsx
  static/app/views/insights/pages/platform/laravel/features.tsx
  static/app/views/insights/pages/platform/nextjs/features.tsx
  static/app/views/projectDetail/projectQuickLinks.tsx
Labels: Scope: Frontend

#94903 feat: Add more video types support
  static/app/components/events/attachmentViewers/previewAttachmentTypes.tsx
  static/app/components/events/eventTagsAndScreenshot/screenshot/index.tsx
Labels: Scope: Frontend

#94862 feat(nextjs-insights): allow custom transactions in client table
  static/app/views/insights/pages/platform/nextjs/clientTable.tsx
Labels: Scope: Frontend

#94907 fix(ai): Fix pricing - prices are fetched per 1M token, but used as per token
  src/sentry/tasks/ai_agent_monitoring.py
  tests/sentry/tasks/test_ai_agent_monitoring.py
Labels: Scope: Backend

#94864 fix(taskworker) Add metric to see how long we wait
  src/sentry/taskworker/workerchild.py
Labels: Scope: Backend

#94782 tooltip: improve shadow tooltips
  static/app/components/overlay.tsx
  static/app/components/overlayArrow.tsx
Labels: Scope: Frontend

#94890 fix(taskworker) Extend deadline for sentry.tasks.statistical_detectors.run_detection
  src/sentry/tasks/statistical_detectors.py
Labels: Scope: Backend

#94885 fix(taskworker) Improve shutdown of taskworkers
  src/sentry/taskworker/worker.py
  src/sentry/taskworker/workerchild.py
Labels: Scope: Backend

#94915 fix(discover): Extend export task deadline
  src/sentry/data_export/tasks.py
Labels: Scope: Backend

#94913 fix(taskworker) extend deadline for assemble_dif
  src/sentry/tasks/assemble.py
  src/sentry/tasks/auto_resolve_issues.py
Labels: Scope: Backend

#94916 feat(dashboards): Add reordering to starred sidebar
  static/app/views/dashboards/hooks/useReorderStarredDashboards.tsx
  static/app/views/nav/secondary/sections/dashboards/dashboardsNavItems.spec.tsx
  static/app/views/nav/secondary/sections/dashboards/dashboardsNavItems.tsx
  static/app/views/nav/secondary/sections/dashboards/dashboardsSecondaryNav.spec.tsx
  static/app/views/nav/secondary/sections/dashboards/dashboardsSecondaryNav.tsx
Labels: Scope: Frontend

#94917 feat(trace-details): Improve span attributes filtering in trace drawer
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/eapSections/attributes.tsx
Labels: Scope: Frontend

#94918 fix(explore): Always render column for incomplete equations
  static/app/views/explore/multiQueryMode/queryVisualizations/table.tsx
  static/app/views/explore/tables/aggregateColumnEditorModal.tsx
  static/app/views/explore/tables/aggregatesTable.tsx
  static/app/views/explore/tables/fieldRenderer.spec.tsx
  static/app/views/explore/tables/fieldRenderer.tsx
  static/app/views/explore/tables/spansTable.tsx
Labels: Scope: Frontend

#94924 fix(eap): Normal mode should be default if no sampling mode defined
  src/sentry/search/eap/utils.py
Labels: Scope: Backend

#94919 feat(explore): Add support for apdex and user misery
  src/sentry/search/eap/spans/formulas.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#94958 chore(dashboards): Remove table view feature flag
  static/app/views/dashboards/manage/dashboardTable.spec.tsx
  static/app/views/dashboards/manage/index.spec.tsx
  static/app/views/dashboards/manage/index.tsx
Labels: Scope: Frontend

#94959 chore(dashboards): Remove table view FF from backend
  src/sentry/api/endpoints/organization_dashboards.py
  src/sentry/features/temporary.py
  tests/sentry/api/endpoints/test_organization_dashboards.py
Labels: Scope: Backend

#94940 chore(seer): Settings improvements
  static/app/views/issueDetails/streamline/sidebar/seerNotices.tsx
  static/app/views/settings/projectSeer/index.tsx
  static/gsApp/views/seerAutomation/index.spec.tsx
  static/gsApp/views/seerAutomation/index.tsx
  static/gsApp/views/seerAutomation/seerAutomationProjectList.tsx
Labels: Scope: Frontend

#94354 fix(uniq): Handle non-array cases
  static/app/components/events/interfaces/frame/stacktraceLinkModal.spec.tsx
  static/app/components/events/interfaces/frame/stacktraceLinkModal.tsx
  static/app/utils/array/uniq.spec.ts
  static/app/utils/array/uniq.ts
Labels: Scope: Frontend

#94830 test(performance): Remove deprecated router mocks
  static/app/views/performance/table.spec.tsx
  static/app/views/performance/transactionSummary/transactionEvents/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/spanDetails/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/suspectSpansTable.spec.tsx
  tests/js/sentry-test/performance/initializePerformanceData.ts
Labels: Scope: Frontend

#94768 fix(seer-ux): Remove confusing 'Try Seer' guard
  static/app/components/events/autofix/useAutofixSetup.tsx
  static/app/components/events/autofix/useOrganizationSeerSetup.tsx
  static/app/views/issueDetails/streamline/hooks/useAiConfig.tsx
  static/app/views/issueDetails/streamline/sidebar/seerDrawer.tsx
  static/app/views/issueDetails/streamline/sidebar/seerSection.tsx
  static/app/views/issueDetails/streamline/sidebar/seerSectionCtaButton.tsx
  static/app/views/settings/projectSeer/index.tsx
  static/gsApp/views/seerAutomation/index.tsx
Labels: Scope: Frontend

#94351 deps(ui): Rspack 1.4
  package.json
  pnpm-lock.yaml
Labels: Scope: Frontend

#94961 feat: Add apdex and user misery to translation layer
  src/sentry/discover/translation/mep_to_eap.py
  tests/sentry/discover/test_compare_tables.py
  tests/sentry/discover/translation/test_mep_to_eap.py
Labels: Scope: Backend

#94962 quality(apidocs): document shortid lookup using drf spectacular
  api-docs/openapi.json
  api-docs/paths/organizations/shortid.json
  src/sentry/api/serializers/models/group.py
  src/sentry/api/serializers/models/group_stream.py
  src/sentry/apidocs/examples/issue_examples.py
  src/sentry/issues/endpoints/organization_shortid.py
  tests/apidocs/endpoints/organizations/test_shortid.py
Labels: Scope: Backend

#94955 ref: ensure Authenticator is exportable
  src/sentry/testutils/helpers/backups.py
  src/sentry/users/models/authenticator.py
Labels: Scope: Backend

#94978 feat(issues-trace-meta): Removing redundant /events-trace-meta/ requests
  static/app/components/events/interfaces/performance/eventTraceView.tsx
  static/app/components/events/interfaces/performance/spanEvidenceTraceView.tsx
  static/app/views/performance/newTraceDetails/issuesTraceWaterfall.tsx
  static/app/views/performance/newTraceDetails/traceApi/useIssuesTraceTree.tsx
Labels: Scope: Frontend

#94939 feat(explore-suspect-attrs): Positioning floating trigger to the bottom right
  static/app/views/explore/components/suspectTags/floatingTrigger.tsx
  static/app/views/explore/hooks/useChartBoxSelect.spec.tsx
  static/app/views/explore/hooks/useChartBoxSelect.tsx
Labels: Scope: Frontend

#94935 ref(ui): Add `ellipsize` string helper
  static/app/components/events/breadcrumbs/breadcrumbItemContent.tsx
  static/app/utils/string/ellipsize.spec.tsx
  static/app/utils/string/ellipsize.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/traceProfiles.tsx
  static/app/views/performance/newTraceDetails/traceRow/traceSpanRow.tsx
Labels: Scope: Frontend

#94760 feat(ACI): Enable ACI processing for dynamic alerts
  src/sentry/incidents/subscription_processor.py
  src/sentry/seer/anomaly_detection/get_anomaly_data.py
  src/sentry/seer/anomaly_detection/types.py
  tests/sentry/incidents/subscription_processor/test_subscription_processor_workflow_engine.py
Labels: Scope: Backend

#94956 feat(dashboards): Expose filtering for owned and shared dashboards
  src/sentry/api/endpoints/organization_dashboards.py
  tests/sentry/api/endpoints/test_organization_dashboards.py
Labels: Scope: Backend

#94927 feat: Add name field to OrganizationTraceEndpoint span data
  src/sentry/api/endpoints/organization_trace.py
  src/sentry/snuba/spans_rpc.py
  tests/sentry/api/endpoints/test_organization_trace_summary.py
  tests/sentry/seer/test_trace_summary.py
Labels: Scope: Backend

#94887 feat(ourlogs): Add auto-refresh to logs
  static/app/components/searchQueryBuilder/context.tsx
  static/app/views/explore/contexts/logs/logsPageParams.tsx
  static/app/views/explore/logs/constants.tsx
  static/app/views/explore/logs/logsAutoRefresh.spec.tsx
  static/app/views/explore/logs/logsAutoRefresh.tsx
  static/app/views/explore/logs/useLogsQuery.spec.tsx
  static/app/views/explore/logs/useLogsQuery.tsx
  static/app/views/explore/logs/useVirtualStreaming.spec.tsx
  static/app/views/explore/logs/useVirtualStreaming.tsx
  static/app/views/explore/logs/utils.tsx
Labels: Scope: Frontend

#94966 ref(replays): Remove dead code from ingest module
  src/sentry/replays/constants.py
  src/sentry/replays/endpoints/project_replay_recording_segment_details.py
  src/sentry/replays/endpoints/project_replay_recording_segment_index.py
  src/sentry/replays/feature.py
  src/sentry/replays/lib/consumer.py
  src/sentry/replays/lib/kafka.py
  src/sentry/replays/types.py
  src/sentry/replays/usecases/ingest/__init__.py
  src/sentry/replays/usecases/ingest/dom_index.py
  src/sentry/replays/usecases/ingest/event_logger.py
  src/sentry/replays/usecases/ingest/events.py
  src/sentry/replays/usecases/segment.py
  tests/sentry/replays/consumers/test_recording.py
  tests/sentry/replays/endpoints/__init__.py
  tests/sentry/replays/endpoints/test_organization_replay_count.py
  tests/sentry/replays/endpoints/test_organization_replay_details.py
  tests/sentry/replays/endpoints/test_organization_replay_events_meta.py
  tests/sentry/replays/endpoints/test_organization_replay_index.py
  tests/sentry/replays/endpoints/test_organization_selector_index.py
  tests/sentry/replays/endpoints/test_project_replay_clicks_index.py
  tests/sentry/replays/endpoints/test_project_replay_details.py
  tests/sentry/replays/endpoints/test_project_replay_jobs_delete.py
  tests/sentry/replays/endpoints/test_project_replay_recording_segment_details.py
  tests/sentry/replays/endpoints/test_project_replay_recording_segment_index.py
  tests/sentry/replays/endpoints/test_project_replay_summarize_breadcrumbs.py
  tests/sentry/replays/endpoints/test_project_replay_video_details.py
  tests/sentry/replays/endpoints/test_project_replay_viewed_by.py
  tests/sentry/replays/unit/test_event_logger.py
  tests/sentry/replays/unit/test_ingest_dom_index.py
Labels: Scope: Backend

#94928 feat(otlp): Render the span waterfall using `span.name`
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/performance/newTraceDetails/traceRow/traceSpanRow.tsx
Labels: Scope: Frontend

#94986 fix(crons): Move gridlines behind timeline
  static/app/components/checkInTimeline/checkInTimeline.tsx
Labels: Scope: Frontend

#94988 fix(uptime): Allow failures in broken_monitor_checker task
  src/sentry/uptime/subscriptions/tasks.py
  tests/sentry/uptime/subscriptions/test_tasks.py
Labels: Scope: Backend

#94759 chore(aci): add tests for data condition list component
  static/app/types/workflowEngine/dataConditions.tsx
  static/app/views/automations/components/actionFilters/ageComparison.tsx
  static/app/views/automations/components/actionFilters/assignedTo.tsx
  static/app/views/automations/components/actionFilters/comparisonBranches.tsx
  static/app/views/automations/components/actionFilters/eventAttribute.tsx
  static/app/views/automations/components/actionFilters/eventFrequency.tsx
  static/app/views/automations/components/actionFilters/eventUniqueUserFrequency.tsx
  static/app/views/automations/components/actionFilters/issueOccurrences.tsx
  static/app/views/automations/components/actionFilters/issuePriority.tsx
  static/app/views/automations/components/actionFilters/latestAdoptedRelease.tsx
  static/app/views/automations/components/actionFilters/level.tsx
  static/app/views/automations/components/actionFilters/percentSessions.tsx
  static/app/views/automations/components/actionFilters/subfiltersList.tsx
  static/app/views/automations/components/actionFilters/taggedEvent.tsx
  static/app/views/automations/components/automationBuilderRow.tsx
  static/app/views/automations/components/dataConditionNodeList.spec.tsx
  static/app/views/automations/components/dataConditionNodeList.tsx
  tests/js/fixtures/automations.ts
  tests/js/fixtures/workflowEngine.ts
Labels: Scope: Frontend

#94728 feat(launchpad): ensure artifact assembly task retries in case of kafka error
  src/sentry/preprod/producer.py
  src/sentry/preprod/tasks.py
  tests/sentry/preprod/test_tasks.py
Labels: Scope: Backend

#94800 feat(aci): Add custom datasets for detectors
  static/app/views/detectors/components/forms/metric/getDatasetConfig.tsx
  static/app/views/detectors/components/forms/metric/metric.tsx
  static/app/views/detectors/components/forms/metric/queryFilterBuilder.tsx
  static/app/views/detectors/components/forms/metric/visualize.tsx
  static/app/views/detectors/datasetConfig/base.tsx
  static/app/views/detectors/datasetConfig/components/eventSearchBar.tsx
  static/app/views/detectors/datasetConfig/components/releaseSearchBar.tsx
  static/app/views/detectors/datasetConfig/components/traceSearchBar.tsx
  static/app/views/detectors/datasetConfig/errors.tsx
  static/app/views/detectors/datasetConfig/getDatasetConfig.tsx
  static/app/views/detectors/datasetConfig/logs.tsx
  static/app/views/detectors/datasetConfig/releases.tsx
  static/app/views/detectors/datasetConfig/spans.tsx
  static/app/views/detectors/datasetConfig/transactions.tsx
  static/app/views/detectors/datasetConfig/useCustomMeasurements.tsx
  static/app/views/detectors/datasetConfig/useTraceItemAttributes.tsx
  static/app/views/explore/hooks/useGetTraceItemAttributeKeys.tsx
Labels: Scope: Frontend

#94995 fix(ui): Make self-hosted setup wizard page wider
  static/app/views/admin/installWizard/index.tsx
Labels: Scope: Frontend

#94822 ref(uptime): Default writing snuba results to true
  src/sentry/options/defaults.py
  tests/sentry/uptime/consumers/test_results_consumer.py
Labels: Scope: Backend

#94678 feat(workflow_engine): Hook up activity updates to process_workflows
  src/sentry/workflow_engine/processors/workflow.py
  src/sentry/workflow_engine/tasks.py
  tests/sentry/workflow_engine/test_task.py
  tests/sentry/workflow_engine/test_task_integration.py
Labels: Scope: Backend

#91100 feat(member merge): merge account endpoint GET
  src/sentry/api/endpoints/auth_merge_user_accounts.py
  src/sentry/api/urls.py
  src/sentry/users/api/serializers/user.py
  static/app/data/controlsiloUrlPatterns.ts
  tests/sentry/api/endpoints/test_auth_merge_user_accounts.py
Labels: Scope: Frontend, Scope: Backend

#94485 chore(sentry apps): add and test slos for installation creation
  src/sentry/sentry_apps/installations.py
  src/sentry/sentry_apps/metrics.py
  tests/sentry/sentry_apps/tasks/test_sentry_apps.py
  tests/sentry/sentry_apps/test_sentry_app_installation_creator.py
  tests/sentry/sentry_apps/test_sentry_app_updater.py
  tests/sentry/sentry_apps/token_exchange/test_grant_exchanger.py
  tests/sentry/sentry_apps/token_exchange/test_refresher.py
Labels: Scope: Backend

#94990 chore(explore): Migrate explore off old feature flag
  static/app/components/sidebar/index.spec.tsx
  static/app/components/sidebar/index.tsx
  static/app/views/explore/utils.tsx
  static/app/views/nav/index.spec.tsx
  static/app/views/nav/secondary/sections/explore/exploreSecondaryNav.tsx
  static/app/views/traces/index.tsx
Labels: Scope: Frontend

#94936 feat(explore): Support functions with no arguments
  static/app/components/arithmeticBuilder/grammar.pegjs
  static/app/components/arithmeticBuilder/token/freeText.tsx
  static/app/components/arithmeticBuilder/token/function.tsx
  static/app/components/arithmeticBuilder/token/index.spec.tsx
  static/app/components/arithmeticBuilder/tokenizer.spec.tsx
  static/app/components/arithmeticBuilder/tokenizer.tsx
  static/app/components/tokenizedInput/grid/useGridListItem.tsx
  static/app/components/tokenizedInput/token/deletableToken.tsx
Labels: Scope: Frontend

#95010 chore(eap): make seer tests not sample
  src/sentry/api/endpoints/seer_rpc.py
  tests/snuba/api/endpoints/test_seer_attributes.py
Labels: Scope: Backend

#94948 ref(platform-insights): Convert issues widget to func component
  static/app/views/insights/pages/platform/shared/issuesWidget.tsx
Labels: Scope: Frontend

#94942 feat: Remove video/quicktime support
  static/app/components/events/attachmentViewers/previewAttachmentTypes.tsx
Labels: Scope: Frontend

#95015 chore(ondemand-metrics): switch from capture_exception to capture_message to reduce noise
  src/sentry/relay/config/metric_extraction.py
  src/sentry/tasks/on_demand_metrics.py
Labels: Scope: Backend

#94949 fix(sourcemaps): list rather than concatenate release IDs
  static/less/group-detail.less
Labels: Scope: Frontend, Trigger: getsentry tests

#95016 fix(platform-insights): Remove issues checkbox
  static/app/views/insights/pages/platform/shared/issuesWidget.tsx
Labels: Scope: Frontend

#95028 profiling: fix this access by binding function to this
  static/app/utils/profiling/flamegraph.ts
Labels: Scope: Frontend

#95000 styles(explore): Make arithmetic operators smaller
  static/app/components/arithmeticBuilder/token/operator.tsx
Labels: Scope: Frontend

#94691 :wrench: chore(integrations): use IntegrationProviderSlug.GithubEnterprise instead of magic str
  src/sentry/identity/github_enterprise/provider.py
  src/sentry/integrations/github_enterprise/actions/create_ticket.py
  src/sentry/integrations/github_enterprise/integration.py
  src/sentry/integrations/github_enterprise/repository.py
  src/sentry/integrations/github_enterprise/webhook.py
  src/sentry/middleware/integrations/parsers/github.py
  src/sentry/middleware/integrations/parsers/github_enterprise.py
Labels: Scope: Backend

#94888 feat(replay): add time duration for each playback speed
  static/app/components/replays/preferences/replayPreferenceDropdown.tsx
Labels: Scope: Frontend

#94991 chore(aci): add tests for action list component
  static/app/views/automations/components/actionNodeList.spec.tsx
  static/app/views/automations/components/actionNodeList.tsx
  static/app/views/automations/components/actions/email.tsx
  static/app/views/automations/components/actions/integrationField.tsx
  static/app/views/automations/components/actions/opsgenie.tsx
  static/app/views/automations/components/actions/pagerduty.tsx
  static/app/views/automations/components/actions/serviceField.tsx
  static/app/views/automations/components/actions/slack.tsx
  static/app/views/automations/components/actions/tagsField.tsx
  static/app/views/automations/components/actions/targetDisplayField.tsx
  static/app/views/automations/components/actions/webhook.tsx
  static/app/views/automations/components/automationBuilder.tsx
  static/app/views/automations/components/automationBuilderContext.tsx
  tests/js/fixtures/automations.ts
  tests/js/fixtures/workflowEngine.ts
Labels: Scope: Frontend

#94977 feat(detectors): Add sorting spans to issue detection
  src/sentry/performance_issues/performance_detection.py
Labels: Scope: Backend

#94976 feat(preprod): Handle installable app assembling
  src/sentry/preprod/api/endpoints/project_preprod_artifact_assemble_generic.py
  src/sentry/preprod/tasks.py
  tests/sentry/preprod/api/endpoints/test_project_preprod_artifact_assemble_generic.py
  tests/sentry/preprod/test_tasks.py
Labels: Scope: Backend

#95041 ref: remove the need for `MIGRATIONS_LOCKFILE_APP_WHITELIST`
  src/sentry/conf/server.py
  src/sentry/insights/__init__.py
  src/sentry/management/commands/makemigrations.py
Labels: Scope: Backend

#95005 style(replay): update tooltip for release bubble
  static/app/components/charts/baseChart.tsx
Labels: Scope: Frontend

#95053 feat(events-util): Relocating getEventTimestamp util
  static/app/components/events/interfaces/performance/eventTraceView.tsx
  static/app/components/events/interfaces/performance/spanEvidenceTraceView.tsx
  static/app/components/events/interfaces/performance/utils.tsx
  static/app/components/events/interfaces/utils.tsx
  static/app/components/quickTrace/utils.tsx
  static/app/views/performance/traceDetails/TraceDetailsRouting.tsx
Labels: Scope: Frontend
