Repository getsentry/sentry, pull requests merged in 2025-02, with the labels that each got.

#84400 fix(anomaly detection): restore correct alert reasons for anomaly detection alerts
  static/app/views/alerts/rules/metric/details/metricHistory.tsx
Labels: Scope: Frontend

#84411 ref(onboarding): Open quick start sidebar on skip onboarding
  static/app/views/onboarding/components/firstEventFooter.tsx
  static/app/views/onboarding/onboarding.tsx
  static/app/views/onboarding/useOnboardingSidebar.tsx
  static/app/views/onboarding/welcome.tsx
Labels: Scope: Frontend

#84414 ref(issue-guides-content): Add quick start pendo item to issue
  static/app/components/assistant/getGuidesContent.tsx
  static/app/components/sidebar/onboardingStatus.tsx
Labels: Scope: Frontend

#84395 ref: ProjectCodeOwners.schema is never null
  migrations_lockfile.txt
  src/sentry/migrations/0824_projectcodeowners_schema_non_null.py
  src/sentry/models/projectcodeowners.py
Labels: Scope: Backend

#84379 ref: delete phabricator plugin
  pyproject.toml
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  setup.cfg
  src/sentry/apidocs/api_publish_status_allowlist_dont_modify.py
  src/sentry/plugins/__init__.py
  src/sentry/runner/importer.py
  src/sentry/runner/initializer.py
  src/sentry/static/sentry/images/logos/logo-phabricator.svg
  src/sentry_plugins/phabricator/__init__.py
  src/sentry_plugins/phabricator/plugin.py
  static/app/plugins/components/pluginIcon.tsx
  static/app/views/settings/organizationIntegrations/constants.tsx
  tests/acceptance/sentry_plugins/test_phabricator.py
  tests/sentry/api/endpoints/test_organization_plugins_configs.py
  tests/sentry/plugins/base/test_group_api_urls.py
  tests/sentry/plugins/test_plugins.py
  tests/sentry_plugins/phabricator/__init__.py
  tests/sentry_plugins/phabricator/test_plugin.py
Labels: Scope: Frontend, Scope: Backend

#84405 chore: bump h2 to 4.2.0
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#84418 fix(tempest): Make `poll_tempest` not propagate trace
  src/sentry/tempest/tasks.py
  tests/sentry/tempest/test_tempest.py
Labels: Scope: Backend

#84385 fix(widget-builder): Allow duplicate aggregates in spans charts preview
  static/app/views/dashboards/widgetBuilder/components/widgetPreview.tsx
Labels: Scope: Frontend

#84270 fix(insights): remove extra filters when navigating to transaction summary
  static/app/views/performance/table.tsx
Labels: Scope: Frontend

#84342 fix(widget-builder): Make table preview columns more visible
  static/app/components/charts/simpleTableChart.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetPreview.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/index.tsx
  static/app/views/dashboards/widgetCard/widgetCardChartContainer.tsx
Labels: Scope: Frontend

#84421 ref: avoid an out-of-order teardown of auth provider
  src/sentry/testutils/cases.py
Labels: Scope: Backend

#84398 feat(dashboards): Improve `WidgetLayout` `Caption` prop
  static/app/views/dashboards/widgets/widgetLayout/widgetLayout.stories.tsx
  static/app/views/dashboards/widgets/widgetLayout/widgetLayout.tsx
Labels: Scope: Frontend

#84354 feat(new-trace) Adding trace level ops breakdown
  static/app/views/performance/newTraceDetails/trace.spec.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceLevelOpsBreakdown.tsx
  static/app/views/performance/newTraceDetails/useTraceEventView.tsx
Labels: Scope: Frontend

#84362 fix(relocation) Add skip for stuck relocation outbox
  src/sentry/receivers/outbox/control.py
Labels: Scope: Backend

#84317 feat(flags): Target events dataset when searching errors
  src/sentry/issues/search.py
  src/sentry/search/snuba/executors.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#84428 ref(crons): Fix spacing of detailsTimeline header
  static/app/views/monitors/components/detailsTimeline.tsx
Labels: Scope: Frontend

#84429 ref(crons): Consistent empty message state
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/components/monitorStats.tsx
Labels: Scope: Frontend

#84430 feat(new-trace): Updating key value action text
  static/app/components/events/eventTags/eventTagsTreeRow.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
Labels: Scope: Frontend

#84401 fix(issue-details): Remove extra divider from tags preview
  static/app/views/issueDetails/streamline/eventDetailsHeader.tsx
  static/app/views/issueDetails/streamline/issueTagsPreview.tsx
Labels: Scope: Frontend

#84435 fix(testing): Test collection typo for acceptance tests
  .github/workflows/acceptance.yml
Labels: Scope: Frontend

#84403 storybook: create contents index
  static/app/components/stories/matrix.tsx
  static/app/components/stories/themeSwitcher.tsx
  static/app/icons/icons.stories.tsx
  static/app/stories/storyBook.tsx
  static/app/styles/typography.stories.tsx
  static/app/views/stories/index.tsx
  static/app/views/stories/storyExports.tsx
  static/app/views/stories/storyFile.tsx
  static/app/views/stories/storyHeader.tsx
  static/app/views/stories/storySourceLinks.tsx
  static/app/views/stories/storyTableOfContents.tsx
  static/app/views/stories/storyTree.tsx
  static/app/views/stories/storyTypes.tsx
  static/app/views/stories/useStoriesLoader.tsx
Labels: Scope: Frontend

#84382 fix(grouping): Make system frames not contribute to app variant
  src/sentry/grouping/enhancer/__init__.py
  src/sentry/grouping/strategies/legacy.py
  src/sentry/grouping/strategies/newstyle.py
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/contributing_system_and_app_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_05_08/contributing_system_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/contributing_system_and_app_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2019_10_29/contributing_system_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/contributing_system_and_app_frames.pysnap
  tests/sentry/grouping/snapshots/test_grouphash_metadata/test_metadata_from_variants/newstyle@2023_01_11/contributing_system_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/contributing_system_and_app_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_05_08/contributing_system_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/contributing_system_and_app_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2019_10_29/contributing_system_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/contributing_system_and_app_frames.pysnap
  tests/sentry/grouping/snapshots/test_variants/test_event_hash_variant/newstyle@2023_01_11/contributing_system_frames.pysnap
  tests/sentry/grouping/test_components.py
  tests/sentry/grouping/test_enhancer.py
  tests/sentry/seer/similarity/test_utils.py
Labels: Scope: Backend

#84372 feat(nav): Duplicate feedback route under /issues/feedback/
  static/app/routes.tsx
  static/app/views/issues/navigation.tsx
Labels: Scope: Frontend

#84406 feat(autofix): New root cause design
  static/app/components/events/autofix/autofixChanges.tsx
  static/app/components/events/autofix/autofixInsightCards.tsx
  static/app/components/events/autofix/autofixRootCause.spec.tsx
  static/app/components/events/autofix/autofixRootCause.tsx
  static/app/components/events/autofix/autofixSteps.spec.tsx
  static/app/components/events/autofix/autofixTimeline.tsx
  static/app/components/events/autofix/types.ts
  tests/js/fixtures/autofixRootCauseCodeContext.ts
  tests/js/fixtures/autofixRootCauseData.ts
Labels: Scope: Frontend

#84255 feat(insights): add routes for insights transaction summary
  static/app/routes.tsx
  static/app/views/performance/transactionSummary/utils.tsx
Labels: Scope: Frontend

#84443 ref(uptime): Move checks index API under projects tree
  src/sentry/api/urls.py
Labels: Scope: Backend

#84286 :sparkles: feat(aci): migration util for email actions
  src/sentry/notifications/models/notificationaction.py
  src/sentry/workflow_engine/typings/notification_action.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_rule_action.py
Labels: Scope: Backend

#84440 feat(crons): Quantize timeline component to intervals
  static/app/components/checkInTimeline/checkInTimeline.tsx
  static/app/components/checkInTimeline/checkInTooltip.spec.tsx
  static/app/components/checkInTimeline/gridLines.tsx
  static/app/components/checkInTimeline/types.tsx
  static/app/components/checkInTimeline/utils/getAggregateStatusFromMultipleBuckets.spec.tsx
  static/app/components/checkInTimeline/utils/getAggregateStatusFromMultipleBuckets.tsx
  static/app/components/checkInTimeline/utils/getConfigFromTimeRange.spec.tsx
  static/app/components/checkInTimeline/utils/getConfigFromTimeRange.tsx
  static/app/components/checkInTimeline/utils/mergeBuckets.spec.tsx
  static/app/components/checkInTimeline/utils/mergeBuckets.tsx
  static/app/components/checkInTimeline/utils/mergeStats.tsx
  static/app/views/monitors/utils/useMonitorStats.tsx
Labels: Scope: Frontend

#84376 fix(Jira-Server): Adds fallback email match for Jira Server users
  src/sentry/integrations/jira_server/integration.py
  src/sentry/integrations/tasks/sync_assignee_outbound.py
  tests/sentry/integrations/jira_server/test_integration.py
Labels: Scope: Backend

#84442 chore(issue-stream): Remove feature flag for issue stream refactor
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84258 chore: bump Sentry SDK to v9 alpha
  build-utils/sentry-instrumentation.ts
  package.json
  static/app/main.tsx
  static/app/utils/performanceForSentry/index.tsx
  tests/js/fixtures/team.ts
  tests/js/instrumentedEnv/userEventIntegration.ts
  yarn.lock
Labels: Scope: Frontend

#84431 fix(widget-builder): Change release interval fidelity to medium
  static/app/views/dashboards/datasetConfig/releases.tsx
  static/app/views/dashboards/widgetCard/releaseWidgetQueries.spec.tsx
Labels: Scope: Frontend

#84453 chore(uptime): Add feature flag to allow for detailed logging for an organization's uptime results
  src/sentry/features/temporary.py
  src/sentry/uptime/consumers/results_consumer.py
Labels: Scope: Backend

#84368 feat(issue-details): All check-ins page enabled for uptime
  static/app/routes.tsx
  static/app/utils/issueTypeConfig/uptimeConfig.tsx
  static/app/views/issueDetails/groupCheckIns.tsx
  static/app/views/issueDetails/groupOpenPeriods.tsx
  static/app/views/issueDetails/queries/useUptimeCheckIns.tsx
  static/app/views/issueDetails/streamline/eventList.tsx
  static/app/views/issueDetails/streamline/eventListTable.tsx
Labels: Scope: Frontend

#84335 chore(billing): Add app_service.get_internal_integrations
  src/sentry/sentry_apps/services/app/impl.py
  src/sentry/sentry_apps/services/app/service.py
  tests/sentry/sentry_apps/services/test_app.py
Labels: Scope: Backend

#84459 fix(replay): Disable pointer events when resizing replay panels
  static/app/components/splitPanel.tsx
Labels: Scope: Frontend

#84460 ref: delete some misc dead code
  fixtures/emails/digest.txt
  src/bitfield/admin.py
  src/sentry/api/event_search.py
  src/sentry/api/helpers/actionable_items_helper.py
  src/sentry/feedback/usecases/spam_detection.py
  src/sentry/tasks/summaries/utils.py
  src/sentry/tasks/summaries/weekly_reports.py
  src/sentry/templates/sentry/emails/reports/body.html
  src/sentry/web/frontend/debug/mail.py
Labels: Scope: Backend

#84463 ref: move sentry.{features,options}.rollout
  pyproject.toml
  src/sentry/features/rollout.py
  src/sentry/grouping/ingest/hashing.py
  src/sentry/grouping/strategies/message.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/lang/native/processing.py
  src/sentry/models/counter.py
  src/sentry/options/rollout.py
  src/sentry/relay/config/metric_extraction.py
  src/sentry/search/events/builder/discover.py
  src/sentry/sentry_metrics/consumers/indexer/batch.py
  src/sentry/snuba/metrics/extraction.py
  src/sentry/utils/json.py
  src/sentry/utils/sdk.py
  tests/sentry/options/test_rollout.py
Labels: Scope: Backend

#84458 fix(issue-stream): Prevent current tab count from being overridden
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#84434 ref(issue-details): Configuration changes for pages
  static/app/utils/issueTypeConfig/cronConfig.tsx
  static/app/utils/issueTypeConfig/errorConfig.tsx
  static/app/utils/issueTypeConfig/index.tsx
  static/app/utils/issueTypeConfig/metricIssueConfig.tsx
  static/app/utils/issueTypeConfig/performanceConfig.tsx
  static/app/utils/issueTypeConfig/replayConfig.tsx
  static/app/utils/issueTypeConfig/types.tsx
  static/app/utils/issueTypeConfig/uptimeConfig.tsx
  static/app/views/issueDetails/groupSidebar.tsx
  static/app/views/issueDetails/header.tsx
  static/app/views/issueDetails/streamline/eventNavigation.tsx
  static/app/views/issueDetails/streamline/header/replayBadge.tsx
  static/app/views/issueDetails/streamline/header/userFeedbackBadge.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsSection.spec.tsx
Labels: Scope: Frontend

#84454 feat(crons): Debounce recomputing timeWindowConfig
  static/app/views/monitors/components/detailsTimeline.tsx
  static/app/views/monitors/components/overviewTimeline/index.tsx
Labels: Scope: Frontend

#84276 feat(aci): prepare data from buffer hash to query snuba in delayed processing
  src/sentry/workflow_engine/processors/delayed_workflow.py
  tests/sentry/workflow_engine/processors/test_delayed_workflow.py
  tests/sentry/workflow_engine/test_base.py
Labels: Scope: Backend

#84452 feat(uptime): Add timelines to overview page
  static/app/views/insights/uptime/components/overviewTimeline/index.tsx
  static/app/views/insights/uptime/components/overviewTimeline/overviewRow.tsx
  static/app/views/insights/uptime/timelineConfig.tsx
  static/app/views/insights/uptime/utils/useUptimeMonitorStats.tsx
Labels: Scope: Frontend

#84468 ref: git rm src/sentry/features/rollout.py
  src/sentry/features/manager.py
  src/sentry/features/rollout.py
Labels: Scope: Backend

#84472 fix(ui): Hide gridline overflow in checkInTimeline
  static/app/components/checkInTimeline/gridLines.tsx
Labels: Scope: Frontend

#84205 feat(metric-issues): Add a chart to show the metric alert values
  static/app/utils/issueTypeConfig/metricIssueConfig.tsx
  static/app/views/alerts/rules/metric/details/body.tsx
  static/app/views/alerts/rules/metric/details/utils.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.tsx
  static/app/views/issueDetails/streamline/metricIssueChart.tsx
Labels: Scope: Frontend

#84464 flag(new-trace): Registering flag.
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84471 chore(eslint): Fix no-unsafe-optional-chaining and enable rule
  eslint.config.mjs
  static/app/bootstrap/initializeSdk.tsx
  static/app/components/events/eventStatisticalDetector/spanOpBreakdown.tsx
  static/app/components/events/interfaces/spans/header.tsx
  static/app/components/superuserStaffAccessForm.tsx
  static/app/views/issueList/issueViews/issueViews.tsx
  static/app/views/issueList/issueViewsHeader.tsx
Labels: Scope: Frontend

#84456 fix(issues): only search if not given a id's
  src/sentry/api/helpers/group_index/update.py
Labels: Scope: Backend

#84477 feat(new-trace): Updating more samples action from span drawer description
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/description.tsx
Labels: Scope: Frontend

#84392 chore(devservices): Bump devservices to 1.0.14
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#84479 chore(eslint): Fix no-case-declarations and enable the rule
  eslint.config.mjs
  static/app/components/deprecatedforms/genericField.tsx
  static/app/components/events/breadcrumbs/utils.tsx
  static/app/components/events/contexts/knownContext/cloudResource.tsx
  static/app/components/events/contexts/knownContext/device.tsx
  static/app/components/events/contexts/utils.tsx
  static/app/components/events/eventEntry.tsx
  static/app/components/events/eventTags/eventTagsTreeRow.tsx
  static/app/components/events/groupingInfo/groupingVariant.tsx
  static/app/components/group/sentryAppExternalIssueForm.tsx
  static/app/components/modals/widgetViewerModal/widgetViewerTableCell.tsx
  static/app/components/profiling/profileEventsTable.tsx
  static/app/components/searchQueryBuilder/hooks/useQueryBuilderState.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filter.tsx
  static/app/components/searchQueryBuilder/tokens/filter/valueCombobox.tsx
  static/app/components/searchQueryBuilder/tokens/filter/valueSuggestions/utils.tsx
  static/app/components/searchSyntax/utils.tsx
  static/app/utils/duration/axisDuration.tsx
  static/app/utils/duration/formatDuration.tsx
  static/app/utils/events.tsx
  static/app/utils/integrationUtil.tsx
  static/app/utils/performance/histogram/utils.tsx
  static/app/utils/replays/playback/providers/replayPlayerStateContext.tsx
  static/app/views/alerts/rules/metric/triggers/actionsPanel/actionTargetSelector.tsx
  static/app/views/dashboards/utils.tsx
  static/app/views/dashboards/widgetBuilder/hooks/useWidgetBuilderState.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/formatTooltipValue.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/formatYAxisValue.tsx
  static/app/views/issueDetails/groupActivityItem.tsx
  static/app/views/issueDetails/groupCheckIns.tsx
  static/app/views/issueDetails/groupEventCarousel.tsx
  static/app/views/issueDetails/streamline/sidebar/groupActivityItem.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/newTraceDetails/traceHeader/breadcrumbs.tsx
  static/app/views/performance/newTraceDetails/traceRenderers/traceTextMeasurer.tsx
  static/app/views/replays/detail/console/format.tsx
Labels: Scope: Frontend

#84283 feat(workflow_engine): Add ability to enqueue slow conditions
  src/sentry/workflow_engine/processors/workflow.py
  tests/sentry/workflow_engine/processors/test_workflow.py
Labels: Scope: Backend

#84285 chore(aci milestone 3): refactor migration helper tests
  src/sentry/workflow_engine/migration_helpers/alert_rule.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_alert_rule.py
Labels: Scope: Backend

#84455 feat(nav): Duplicate /projects/ routes under /insights/projects/
  static/app/routes.tsx
  static/app/views/insights/navigation.tsx
Labels: Scope: Frontend

#84491 chore(eslint): Fix no-array-constructor and enable rule
  eslint.config.mjs
  static/app/views/insights/mobile/screens/components/screensOverview.tsx
  static/app/views/insights/mobile/screens/views/screensLandingPage.tsx
Labels: Scope: Frontend

#84415 ref(quick-start): Add animation to the progress bar ring
  static/app/components/progressRing.tsx
  static/app/components/sidebar/onboardingStatus.tsx
Labels: Scope: Frontend

#84413 ref(project-install): Update logic to open quick start sidebar without hash
  static/app/components/sidebar/index.tsx
  static/app/components/sidebar/utils.tsx
  static/app/views/projectInstall/platform.tsx
Labels: Scope: Frontend

#84504 storybook: fix titles
  static/app/components/alert.stories.tsx
  static/app/components/alertLink.stories.tsx
  static/app/components/alerts/pageBanner.stories.tsx
  static/app/components/avatar/avatarList.stories.tsx
  static/app/components/avatar/seenByList.stories.tsx
  static/app/components/badge/alertBadge.stories.tsx
  static/app/components/badge/badge.stories.tsx
  static/app/components/badge/deployBadge.stories.tsx
  static/app/components/badge/featureBadge.stories.tsx
  static/app/components/badge/groupPriority.stories.tsx
  static/app/components/badge/tag.stories.tsx
  static/app/components/button.stories.tsx
  static/app/components/buttonBar.stories.tsx
  static/app/components/charts/groupStatusChart.stories.tsx
  static/app/components/checkInTimeline/checkInTimeline.stories.tsx
  static/app/components/clippedBox.stories.tsx
  static/app/components/codeSnippet.stories.tsx
  static/app/components/collapsePanel.stories.tsx
  static/app/components/collapsible.stories.tsx
  static/app/components/compactSelect/composite.stories.tsx
  static/app/components/compactSelect/index.stories.tsx
  static/app/components/confirm.stories.tsx
  static/app/components/container/negativeSpaceContainer.stories.tsx
  static/app/components/copyToClipboardButton.stories.tsx
  static/app/components/duration/duration.stories.tsx
  static/app/components/emptyStateWarning.stories.tsx
  static/app/components/events/contexts/contextIcon.stories.tsx
  static/app/components/forms/fields/index.stories.tsx
  static/app/components/gridEditable/index.stories.tsx
  static/app/components/guidedSteps/guidedSteps.stories.tsx
  static/app/components/idBadge/index.stories.tsx
  static/app/components/interactionStateLayer.stories.tsx
  static/app/components/loadingError.stories.tsx
  static/app/components/loadingIndicator.stories.tsx
  static/app/components/loadingTriangle.stories.tsx
  static/app/components/logoSentry.stories.tsx
  static/app/components/nav/secondary.stories.tsx
  static/app/components/onboardingPanel.stories.tsx
  static/app/components/progrssBar.stories.tsx
  static/app/components/questionTooltip.stories.tsx
  static/app/components/replays/alerts/missingReplayAlert.stories.tsx
  static/app/components/replays/alerts/replayUnsupportedAlert.stories.tsx
  static/app/components/replays/player/replayCurrentTime.stories.tsx
  static/app/components/replays/player/replayPlayPauseButton.stories.tsx
  static/app/components/replays/player/replayPlayer.stories.tsx
  static/app/components/replays/player/replayPlayerMeasurer.stories.tsx
  static/app/components/replays/preferences/replayPreferenceDropdown.stories.tsx
  static/app/components/scrollCarousel.stories.tsx
  static/app/components/searchQueryBuilder/index.stories.tsx
  static/app/components/segmentedControl.stories.tsx
  static/app/components/structuredEventData/index.stories.tsx
  static/app/components/tabs/index.stories.tsx
  static/app/stories/storyBook.tsx
  static/app/views/dashboards/widgetCard/autoSizedText.stories.tsx
  static/app/views/dashboards/widgets/areaChartWidget/areaChartWidget.stories.tsx
  static/app/views/dashboards/widgets/barChartWidget/barChartWidget.stories.tsx
  static/app/views/dashboards/widgets/bigNumberWidget/bigNumberWidget.stories.tsx
  static/app/views/dashboards/widgets/common/widgetFrame.stories.tsx
  static/app/views/dashboards/widgets/lineChartWidget/lineChartWidget.stories.tsx
  static/app/views/dashboards/widgets/widgetLayout/widgetLayout.stories.tsx
Labels: Scope: Frontend

#84330 fix(github): Always fetch max number of pages
  src/sentry/integrations/github/client.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/github/tasks/link_all_repos.py
  src/sentry/integrations/github_enterprise/integration.py
  src/sentry/options/defaults.py
  tests/sentry/integrations/github/test_integration.py
Labels: Component: Integrations, Do Not Merge, Scope: Backend

#84433 ref: fix [return-value] mypy errors
  pyproject.toml
  src/sentry/api/base.py
  src/sentry/api/endpoints/organization_events_facets_performance.py
  src/sentry/api/endpoints/organization_events_meta.py
  src/sentry/auth/helper.py
  src/sentry/eventstore/models.py
  src/sentry/integrations/github/blame.py
  src/sentry/integrations/github/client.py
  src/sentry/integrations/github/issues.py
  src/sentry/integrations/jira/integration.py
  src/sentry/integrations/metric_alerts.py
  src/sentry/integrations/utils/sync.py
  src/sentry/issues/search.py
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/search/events/builder/metrics.py
  src/sentry/search/events/datasets/filter_aliases.py
  src/sentry/search/events/filter.py
  src/sentry/search/snuba/executors.py
  src/sentry/snuba/metrics/datasource.py
  src/sentry/snuba/metrics/query_builder.py
  src/sentry/testutils/cases.py
  src/sentry/web/frontend/auth_login.py
  src/sentry/web/frontend/base.py
  tests/sentry/search/events/builder/test_metrics.py
Labels: Scope: Backend

#84461 fix(widget-builder): Add error messaging to threshold fields
  static/app/views/dashboards/widgetBuilder/components/thresholds.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/thresholds.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetBuilderSlideout.tsx
Labels: Scope: Frontend

#84383 feat(aci): get unique condition queries in delayed workflow processing
  src/sentry/workflow_engine/handlers/condition/event_frequency_base_handler.py
  src/sentry/workflow_engine/handlers/condition/event_frequency_handlers.py
  src/sentry/workflow_engine/models/data_condition.py
  src/sentry/workflow_engine/models/data_condition_group.py
  src/sentry/workflow_engine/processors/delayed_workflow.py
  tests/sentry/workflow_engine/processors/test_delayed_workflow.py
Labels: Scope: Backend

#84467 feat(aci): create actions in issue alert dual write
  src/sentry/workflow_engine/migration_helpers/rule.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_rule.py
Labels: Scope: Backend

#84489 chore(issue-details): Show tag button after search
  static/app/views/issueDetails/streamline/issueTagsPreview.tsx
Labels: Scope: Frontend

#84519 fix(dashboards): Switch `Add Widget` dropdown order
  static/app/views/dashboards/addWidget.tsx
  static/app/views/dashboards/controls.tsx
Labels: Scope: Frontend

#84473 fix(widget-builder): Make entrance/exit animations smoother
  static/app/views/dashboards/widgetBuilder/components/common/animationSettings.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.tsx
  static/app/views/dashboards/widgetBuilder/components/widgetBuilderSlideout.tsx
Labels: Scope: Frontend

#84451 fix(nav): Better detection of the active link
  static/app/components/nav/primary.tsx
  static/app/components/nav/secondary.tsx
  static/app/components/nav/utils.tsx
  static/app/views/settings/components/settingsNavItem.tsx
Labels: Scope: Frontend

#84523 ref: upgrade action-setup-venv
  .github/actions/setup-sentry/action.yml
  .github/workflows/backend.yml
  .github/workflows/development-environment.yml
  .github/workflows/pre-commit.yml
  .github/workflows/react-to-product-owners-yml-changes.yml
  .github/workflows/self-hosted.yml
Labels: Scope: Frontend, Scope: Backend

#84498 :recycle: ref(threads): remove notification message unique constraint
  migrations_lockfile.txt
  src/sentry/migrations/0825_remove_notificationmessage_unique_ag_constraint.py
  src/sentry/notifications/models/notificationmessage.py
  tests/sentry/notifications/test_notificationmessage_table_constraints.py
Labels: Scope: Backend

#84518 feat(taskworker): Loadbalance workers onto brokers
  src/sentry/runner/commands/run.py
  src/sentry/taskworker/client.py
  src/sentry/taskworker/worker.py
  tests/sentry/taskworker/test_client.py
  tests/sentry/taskworker/test_worker.py
Labels: Scope: Backend

#84526 feat(new-trace): Using fetaure flag for trace level ops breakdown
  static/app/views/performance/newTraceDetails/traceLevelOpsBreakdown.tsx
Labels: Scope: Frontend

#84484 feat(aci): issue alert dual create in API
  src/sentry/features/temporary.py
  src/sentry/projects/project_rules/creator.py
  src/sentry/workflow_engine/migration_helpers/rule.py
  tests/sentry/api/endpoints/test_project_rules.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_rule.py
Labels: Scope: Backend

#84525 feat(flags): Add support for legacy queries on issues search
  src/sentry/search/snuba/executors.py
  src/sentry/utils/snuba.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
  tests/snuba/search/test_backend.py
Labels: Scope: Backend

#84527 chore(sdk): Revert sentry sdk v9.0.0-alpha.1
  build-utils/sentry-instrumentation.ts
  package.json
  static/app/main.tsx
  static/app/utils/performanceForSentry/index.tsx
  tests/js/fixtures/team.ts
  tests/js/instrumentedEnv/userEventIntegration.ts
  yarn.lock
Labels: Scope: Frontend

#84531 feat(new-trace): Filtering query results by project id when searching…
  static/app/components/events/eventTags/eventTagsTreeRow.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/index.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/ancestry.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/description.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/generalInfo.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/keys.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/measurements.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/tags.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/sections/measurements.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/utils.tsx
Labels: Scope: Frontend

#84532 chore(seer grouping): Remove old excess frames check debug logging
  src/sentry/grouping/ingest/seer.py
  src/sentry/seer/similarity/utils.py
Labels: Scope: Backend

#83943 feat (aci milestone 3): dual update helpers for triggers and trigger actions
  src/sentry/workflow_engine/migration_helpers/alert_rule.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_alert_rule.py
Labels: Scope: Backend

#84492 :recycle: ref(sentry-apps): make sentryapp uuid unique
  migrations_lockfile.txt
  src/sentry/migrations/0826_make_sentryapp_uuid_unique.py
  src/sentry/sentry_apps/models/sentry_app.py
Labels: Scope: Backend

#84462 fix(taskworker): Add support for gRPC service config file
  src/sentry/options/defaults.py
  src/sentry/taskworker/client.py
  tests/sentry/taskworker/test_client.py
Labels: Scope: Backend

#84480 feat(insights): remove ai overview page
  static/app/components/sidebar/index.tsx
  static/app/routes.tsx
  static/app/views/insights/pages/ai/aiOverviewPage.tsx
  static/app/views/insights/pages/ai/aiPageHeader.tsx
  static/app/views/insights/pages/domainViewHeader.spec.tsx
  static/app/views/insights/pages/domainViewHeader.tsx
Labels: Scope: Frontend

#84517 fix(explore): Clear cursor on certain explore navigation
  static/app/views/explore/contexts/pageParamsContext/groupBys.tsx
  static/app/views/explore/contexts/pageParamsContext/mode.tsx
  static/app/views/explore/contexts/pageParamsContext/query.tsx
  static/app/views/explore/contexts/pageParamsContext/sortBys.tsx
Labels: Scope: Frontend

#84497 chore(explore): Add tooltip to explore project badge
  static/app/views/explore/tables/fieldRenderer.tsx
Labels: Scope: Frontend

#84537 tests(expore): Add missing clear mock responses to explore tests
  static/app/views/explore/spans/spansTab.spec.tsx
Labels: Scope: Frontend

#84534 fix(new-trace): Updating trace header padding to be consistent with o…
  static/app/views/performance/newTraceDetails/traceHeader/index.tsx
Labels: Scope: Frontend

#84535 feat(trace): Add span op count to the trace meta
  src/sentry/api/endpoints/organization_events_trace.py
  src/sentry/testutils/cases.py
  tests/snuba/api/endpoints/test_organization_events_trace.py
Labels: Scope: Backend

#84475 ref(crons): Always useOrganization
  static/app/views/alerts/rules/crons/details.tsx
  static/app/views/monitors/components/monitorCheckIns.tsx
  static/app/views/monitors/components/monitorIssues.tsx
  static/app/views/monitors/components/monitorStats.tsx
  static/app/views/monitors/details.tsx
Labels: Scope: Frontend

#84545 ref(ui): Disable selecting labels in checkInTimeline
  static/app/components/checkInTimeline/gridLines.tsx
Labels: Scope: Frontend

#84529 fix(dashboards): Change widget titles from add to dashboard flows
  static/app/components/modals/widgetBuilder/addToDashboardModal.tsx
  static/app/views/discover/utils.tsx
Labels: Scope: Frontend

#84427 ref(ui): Simplify getAggregateStatus in checkInTimeline
  static/app/components/checkInTimeline/utils/getAggregateStatus.tsx
  static/app/components/checkInTimeline/utils/testUtils.tsx
  static/app/views/monitors/utils.tsx
Labels: Scope: Frontend

#84547 chore(uptime): Add stats about which mode the result consumer is starting in
  src/sentry/remote_subscriptions/consumers/result_consumer.py
Labels: Scope: Backend

#84542 chore(flags): put feature flags back into proper spot
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84351 ref(tsc): convert orgDashboards to FC
  static/app/utils/useParams.tsx
  static/app/views/dashboards/detail.spec.tsx
  static/app/views/dashboards/index.tsx
  static/app/views/dashboards/orgDashboards.spec.tsx
  static/app/views/dashboards/orgDashboards.tsx
  static/app/views/dashboards/view.tsx
Labels: Scope: Frontend

#84496 chore(issue-views): Create feature flag for page filters
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84540 fix(widget-builder): Do not await dashboard save on submit
  static/app/views/dashboards/detail.tsx
Labels: Scope: Frontend

#84552 fix(taskworker): Add some logging for debugging
  src/sentry/taskworker/client.py
Labels: Scope: Backend

#84553 chore(devservices): Bump devservices to 1.0.15
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#84560 chore(gitlab): add logging for `fetch_file_blame`
  src/sentry/integrations/gitlab/blame.py
Labels: Scope: Backend

#84558 ref(taskworker): add a sleep for simple task
  src/sentry/taskworker/tasks/examples.py
Labels: Scope: Backend

#84520 fix(uptime): add epoch cutoff padding
  src/sentry/options/defaults.py
  src/sentry/uptime/endpoints/organization_uptime_stats.py
  tests/sentry/uptime/endpoints/test_organization_uptime_stats.py
Labels: Scope: Backend

#84437 feat(issue-details): Add uptime specific data for header
  static/app/routes.tsx
  static/app/types/event.tsx
  static/app/utils/issueTypeConfig/types.tsx
  static/app/utils/issueTypeConfig/uptimeConfig.tsx
  static/app/views/issueDetails/groupUptimeChecks.tsx
  static/app/views/issueDetails/queries/useUptimeCheckIns.tsx
  static/app/views/issueDetails/streamline/context.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.spec.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.tsx
  static/app/views/issueDetails/streamline/eventNavigation.spec.tsx
  static/app/views/issueDetails/streamline/eventNavigation.tsx
  static/app/views/issueDetails/streamline/eventTitle.spec.tsx
  static/app/views/issueDetails/streamline/issueCheckInTimeline.tsx
  static/app/views/issueDetails/streamline/occurrenceSummary.tsx
  static/app/views/issueDetails/streamline/sidebar/detectorSection.tsx
  static/app/views/issueDetails/streamline/sidebar/sidebar.tsx
  static/app/views/issueDetails/types.tsx
Labels: Scope: Frontend

#82434 chore(seer grouping): Remove older stacktrace length filtering code
  src/sentry/grouping/ingest/seer.py
  src/sentry/issues/endpoints/group_similar_issues_embeddings.py
  src/sentry/seer/similarity/utils.py
  src/sentry/tasks/embeddings_grouping/utils.py
  tests/sentry/grouping/ingest/test_seer.py
  tests/sentry/issues/endpoints/test_group_similar_issues_embeddings.py
  tests/sentry/seer/similarity/test_utils.py
Labels: Scope: Backend

#84551 chore(releases): add flag for new insights charts
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84544 chore(replay): create a project blocklist for viewed by endpoint and filters (inc-1024)
  src/sentry/options/defaults.py
  src/sentry/replays/query.py
  src/sentry/replays/usecases/query/__init__.py
  tests/sentry/replays/test_organization_replay_index.py
  tests/sentry/replays/test_project_replay_viewed_by.py
Labels: Scope: Backend

#84543 ref(uptime): Consistent type usage
  static/app/views/alerts/rules/uptime/types.tsx
  static/app/views/insights/uptime/components/overviewTimeline/index.tsx
  static/app/views/insights/uptime/components/overviewTimeline/overviewRow.tsx
  static/app/views/insights/uptime/timelineConfig.tsx
  static/app/views/insights/uptime/types.tsx
  static/app/views/insights/uptime/utils/useUptimeMonitorStats.tsx
  static/app/views/insights/uptime/views/overview.tsx
Labels: Scope: Frontend

#84573 fix(projects): Attach projects to teams from projects
  static/app/views/projectsDashboard/index.spec.tsx
  static/app/views/projectsDashboard/index.tsx
Labels: Scope: Frontend

#84568 dev(uptime): allowlist endpoints for metric
  src/sentry/conf/server.py
Labels: Scope: Backend

#84555 feat(uptime): Add alert for uptime monitoring data storage acknowledgment
  static/app/views/alerts/rules/uptime/uptimeAlertForm.tsx
Labels: Scope: Frontend

#84575 fix(flag): Fix typo in flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84572 feat(uptime): Add timeline to details view
  static/app/views/alerts/rules/uptime/details.tsx
  static/app/views/alerts/rules/uptime/detailsTimeline.tsx
  static/app/views/insights/uptime/components/overviewTimeline/overviewRow.tsx
Labels: Scope: Frontend

#84554 ref(ui): Clean up checkInTooltip
  static/app/components/checkInTimeline/checkInTooltip.tsx
Labels: Scope: Frontend

#84507 ref(onboarding): Render platforms in the same order defined in the popular set
  static/app/components/platformPicker.tsx
Labels: Scope: Frontend

#84506 chore: Bump platformicons
  package.json
  yarn.lock
Labels: Scope: Frontend

#84485 ref(dashboards): Remove duplicated `SeriesWithOrdering` type
  static/app/views/dashboards/datasetConfig/errors.tsx
  static/app/views/dashboards/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboards/datasetConfig/transactions.tsx
  static/app/views/dashboards/utils/transformEventsResponseToSeries.tsx
Labels: Scope: Frontend

#84578 ref: fix typing for auth_provider serializer
  pyproject.toml
  src/sentry/api/serializers/models/auth_provider.py
Labels: Scope: Backend

#84482 fix(insights): adds Web Vitals loading placeholders to page overview vital meters
  static/app/views/insights/browser/webVitals/views/pageOverview.tsx
  static/app/views/insights/browser/webVitals/views/webVitalsLandingPage.tsx
Labels: Scope: Frontend

#84564 webpack: remove asset size reporting
  .github/workflows/acceptance.yml
  build-utils/sentry-instrumentation.ts
Labels: Scope: Frontend

#84425 fix(dashboards): Cache project for ondemand evaluation
  src/sentry/api/serializers/rest_framework/dashboard.py
  src/sentry/tasks/on_demand_metrics.py
Labels: Scope: Backend

#84587 feat(query-builder): Add support for size filters in search query builder
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/filter/parsers/duration/parser.tsx
  static/app/components/searchQueryBuilder/tokens/filter/parsers/size/grammar.pegjs
  static/app/components/searchQueryBuilder/tokens/filter/parsers/size/parser.tsx
  static/app/components/searchQueryBuilder/tokens/filter/valueSuggestions/size.tsx
  static/app/components/searchQueryBuilder/tokens/filter/valueSuggestions/utils.tsx
  static/app/components/searchQueryBuilder/tokens/utils.tsx
  static/app/components/searchQueryBuilder/utils.tsx
  static/app/components/searchSyntax/parser.tsx
  static/app/utils/fields/index.ts
  static/app/views/metrics/utils/index.spec.tsx
Labels: Scope: Frontend

#84570 storybook: open sidebar to linked story
  static/app/views/stories/storyTree.tsx
Labels: Scope: Frontend

#84550 feat(insights): Adds feature flag for standalone lcp and cls ui
  src/sentry/features/temporary.py
Labels: Scope: Backend

#84469 ref(dashboards): Move padding control into `WidgetLayout`
  static/app/views/dashboards/widgetCard/index.tsx
  static/app/views/dashboards/widgets/bigNumberWidget/bigNumberWidget.tsx
  static/app/views/dashboards/widgets/bigNumberWidget/bigNumberWidgetVisualization.tsx
  static/app/views/dashboards/widgets/common/widgetFrame.stories.tsx
  static/app/views/dashboards/widgets/common/widgetFrame.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/timeSeriesWidget.tsx
  static/app/views/dashboards/widgets/widgetLayout/widgetLayout.stories.tsx
  static/app/views/dashboards/widgets/widgetLayout/widgetLayout.tsx
  static/app/views/projectDetail/projectScoreCards/actionWrapper.tsx
Labels: Scope: Frontend

#84571 ref(issues): Use uptime types from alerts
  static/app/views/alerts/rules/uptime/types.tsx
  static/app/views/issueDetails/groupUptimeChecks.tsx
  static/app/views/issueDetails/queries/useUptimeCheckIns.tsx
Labels: Scope: Frontend

#84426 :sparkles: fea(aci): util to migrate sentry apps
  src/sentry/workflow_engine/typings/notification_action.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_rule_action.py
Labels: Scope: Backend

#84530 :wrench: chore: remove old data secrecy flags and code
  src/sentry/api/permissions.py
  src/sentry/features/temporary.py
  tests/sentry/api/test_data_secrecy.py
Labels: Scope: Backend

#84606 chore: upgrade sentry-kafka-schemas
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#84614 fix(uptime): add automator modifiable arg
  src/sentry/options/defaults.py
Labels: Scope: Backend

#84582 feat(nav): Display secondary nav in mobile menu
  static/app/components/nav/constants.tsx
  static/app/components/nav/context.tsx
  static/app/components/nav/index.spec.tsx
  static/app/components/nav/index.tsx
  static/app/components/nav/mobileTopbar.tsx
  static/app/components/nav/primary.tsx
  static/app/components/nav/secondary.stories.tsx
  static/app/components/nav/secondary.tsx
  static/app/components/nav/secondaryMobile.tsx
  static/app/components/nav/types.tsx
  static/app/views/explore/navigation.tsx
  static/app/views/insights/navigation.tsx
  static/app/views/issues/navigation.tsx
  static/app/views/settings/components/settingsNavigation.tsx
Labels: Scope: Frontend

#84598 ref: ban dateutil.parse in tests
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/backup/test_sanitize.py
  tests/sentry/rules/history/endpoints/test_project_rule_preview.py
  tests/sentry/snuba/test_query_subscription_consumer.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
  tests/tools/test_flake8_plugin.py
  tools/flake8_plugin.py
Labels: Scope: Backend

#84583 ref(taskworker): add parsing for taskworker run cmd to support no sharding
  src/sentry/runner/commands/run.py
  src/sentry/taskworker/client.py
  src/sentry/taskworker/worker.py
Labels: Scope: Backend

#84592 chore(seer grouping): Remove redundant empty stacktrace string check
  src/sentry/grouping/ingest/seer.py
  tests/sentry/grouping/ingest/test_seer.py
Labels: Scope: Backend

#84619 chore(slack): add `restricted_action` halt error category
  src/sentry/integrations/slack/actions/notification.py
  src/sentry/integrations/slack/utils/errors.py
Labels: Scope: Backend

#84620 ref(uptime): Move useUptime{CheckIns -> Checks} to uptime insight utils
  static/app/views/insights/uptime/utils/useUptimeChecks.tsx
  static/app/views/issueDetails/groupUptimeChecks.tsx
Labels: Scope: Frontend

#84584 fix(jira-server): Removes additional validation if Jira Server API only returns a single user
  src/sentry/integrations/jira_server/integration.py
  tests/sentry/integrations/jira_server/test_integration.py
Labels: Scope: Backend

#84259 deps(ui): Upgrade emotion
  package.json
  static/app/components/events/interfaces/spans/scrollbarManager.tsx
  static/app/utils/discover/genericDiscoverQuery.tsx
  static/app/utils/errorHandler.tsx
  static/app/utils/routeAnalytics/withRouteAnalytics.tsx
  static/app/utils/withApi.tsx
  static/app/utils/withConfig.tsx
  static/app/utils/withLatestContext.tsx
  static/app/utils/withOrganization.tsx
  static/app/utils/withOrganizations.tsx
  static/app/utils/withPageFilters.tsx
  static/app/utils/withPlugins.tsx
  static/app/utils/withProject.tsx
  static/app/utils/withProjects.tsx
  static/app/utils/withSentryAppComponents.tsx
  static/app/utils/withSentryRouter.tsx
  static/app/utils/withTags.tsx
  yarn.lock
Labels: Scope: Frontend

#84569 feat(flags): Clean up flags search query re-writes
  src/sentry/utils/snuba.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
  tests/sentry/issues/endpoints/test_organization_issues_count.py
Labels: Scope: Backend

#84608 feat(solutions hub): Integrate resources into the summary
  static/app/components/group/groupSummary.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsHubDrawer.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsHubDrawer.tsx
Labels: Scope: Frontend

#82442 feat(seer grouping): Add platform to ingest metrics
  src/sentry/grouping/ingest/seer.py
  src/sentry/seer/similarity/utils.py
  tests/sentry/grouping/ingest/test_seer.py
Labels: Scope: Backend

#84476 ref(rpc): Move confidence to meta
  src/sentry/api/bases/organization_events.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#84625 feat(icons): Add double chevron
  static/app/icons/iconChevron.tsx
  static/app/icons/icons.stories.tsx
  static/app/views/issueDetails/streamline/sidebar/toggleSidebar.tsx
Labels: Scope: Frontend

#84538 fix(insights): view all button broken on self hosted
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
Labels: Scope: Frontend

#84626 feat(new-trace): Added a feedback button
  static/app/views/performance/newTraceDetails/traceHeader/index.tsx
Labels: Scope: Frontend

#84613 ref(dashboards): Remove stray references to `TimeseriesData` type
  static/app/views/dashboards/contexts/widgetSyncContext.stories.tsx
  static/app/views/dashboards/widgets/areaChartWidget/areaChartWidget.spec.tsx
  static/app/views/dashboards/widgets/areaChartWidget/areaChartWidget.stories.tsx
  static/app/views/dashboards/widgets/areaChartWidget/fixtures/sampleLatencyTimeSeries.ts
  static/app/views/dashboards/widgets/areaChartWidget/fixtures/sampleSpanDurationTimeSeries.ts
  static/app/views/dashboards/widgets/areaChartWidget/sampleLatencyTimeSeries.json
  static/app/views/dashboards/widgets/areaChartWidget/sampleSpanDurationTimeSeries.json
  static/app/views/dashboards/widgets/barChartWidget/barChartWidget.spec.tsx
  static/app/views/dashboards/widgets/barChartWidget/barChartWidget.stories.tsx
  static/app/views/dashboards/widgets/barChartWidget/fixtures/sampleLatencyTimeSeries.ts
  static/app/views/dashboards/widgets/barChartWidget/fixtures/sampleSpanDurationTimeSeries.ts
  static/app/views/dashboards/widgets/barChartWidget/sampleLatencyTimeSeries.json
  static/app/views/dashboards/widgets/barChartWidget/sampleSpanDurationTimeSeries.json
  static/app/views/dashboards/widgets/lineChartWidget/fixtures/sampleDurationTimeSeries.ts
  static/app/views/dashboards/widgets/lineChartWidget/fixtures/sampleThroughputTimeSeries.ts
  static/app/views/dashboards/widgets/lineChartWidget/lineChartWidget.spec.tsx
  static/app/views/dashboards/widgets/lineChartWidget/lineChartWidget.stories.tsx
  static/app/views/dashboards/widgets/lineChartWidget/sampleDurationTimeSeries.json
  static/app/views/dashboards/widgets/lineChartWidget/sampleThroughputTimeSeries.json
  static/app/views/dashboards/widgets/timeSeriesWidget/scaleTimeSeriesData.spec.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/splitSeriesIntoCompleteAndIncomplete.spec.tsx
  static/app/views/dashboards/widgets/widgetLayout/widgetLayout.stories.tsx
Labels: Scope: Frontend

#84622 fix(rpc): Remove incorrect group by in other series
  src/sentry/snuba/spans_rpc.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#84623 fix(issue-views): Do not remove query and page from query params
  static/app/views/issueList/issueViewsHeader.tsx
Labels: Scope: Frontend

#84628 fix(widget-builder): Aggregate selector dropdown misplaced
  static/app/views/dashboards/widgetBuilder/components/visualize.tsx
Labels: Scope: Frontend

#84636 fix(dashboards): Skip load last used page filters
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetBuilder/components/filtersBar.tsx
  static/app/views/dashboards/widgetBuilder/widgetBuilder.tsx
Labels: Scope: Frontend

#84562 feat(taskworker) Add more documentation context to schedules
  src/sentry/conf/types/taskworker.py
  src/sentry/runner/commands/run.py
  src/sentry/taskworker/scheduler/runner.py
  src/sentry/taskworker/scheduler/schedules.py
Labels: Scope: Backend

#84589 feat(replay): Add an error message when network response body is blob
  static/app/views/replays/detail/network/details/content.tsx
  static/app/views/replays/detail/network/details/getOutputType.tsx
Labels: Scope: Frontend

#84629 fix(issues): Support group pluginActions integrations
  static/app/components/feedback/list/issueTrackingSignals.tsx
  static/app/components/group/externalIssuesList/hooks/types.tsx
  static/app/components/group/externalIssuesList/hooks/usePluginExternalIssues.tsx
  static/app/components/group/externalIssuesList/index.tsx
  static/app/types/group.tsx
  static/app/views/issueDetails/streamline/sidebar/externalIssueList.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/externalIssueList.tsx
Labels: Scope: Frontend
