Repository getsentry/sentry, pull requests merged in 2025-10, with the labels that each got.

#100594 feat(onboarding): Simplify android doc
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/android/android.spec.tsx
  static/app/gettingStartedDocs/android/android.tsx
Labels: Scope: Frontend

#100631 feat(replays): Add support for null and not null translation
  src/sentry/replays/lib/new_query/utils.py
Labels: Scope: Backend

#100449 feat(replay): Create link to search for replays by user
  static/app/views/replays/detail/header/replayDetailsUserBadge.tsx
Labels: Scope: Frontend

#98429 ref(quotas): Remove legacy project and org quotas
  src/sentry/api/endpoints/internal/__init__.py
  src/sentry/api/endpoints/internal/quotas.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/api/urls.py
  src/sentry/constants.py
  src/sentry/core/endpoints/organization_details.py
  src/sentry/options/defaults.py
  src/sentry/quotas/base.py
  src/sentry/quotas/redis.py
  src/sentry/runner/initializer.py
  src/sentry/testutils/helpers/backups.py
  static/app/data/controlsiloUrlPatterns.ts
  static/app/routes.tsx
  static/app/views/admin/adminQuotas.spec.tsx
  static/app/views/admin/adminQuotas.tsx
  static/app/views/admin/adminSettings.spec.tsx
  static/app/views/admin/adminSettings.tsx
  static/app/views/admin/options.tsx
  tests/sentry/api/endpoints/test_system_options.py
  tests/sentry/core/endpoints/test_organization_details.py
  tests/sentry/models/test_organization.py
  tests/sentry/quotas/test_base.py
  tests/sentry/quotas/test_redis.py
  tests/sentry/runner/test_initializer.py
Labels: Do Not Merge, Scope: Frontend, Scope: Backend

#100009 feat(replays): Add data export
  pyproject.toml
  src/sentry/api/urls.py
  src/sentry/replays/data_export.py
  src/sentry/replays/endpoints/data_export_notifications.py
  src/sentry/snuba/referrer.py
  static/app/data/controlsiloUrlPatterns.ts
  tests/sentry/replays/conftest.py
  tests/sentry/replays/endpoints/test_data_export_notifications.py
  tests/sentry/replays/integration/test_data_export.py
  tests/sentry/replays/test_data_export.py
  tests/sentry/replays/unit/test_data_export.py
  uv.lock
Labels: Scope: Frontend, Scope: Backend

#99984 fix(preprod): Validate all required VCS params are provided
  src/sentry/preprod/api/endpoints/organization_preprod_artifact_assemble.py
  tests/sentry/preprod/api/endpoints/test_organization_preprod_artifact_assemble.py
  tests/sentry/preprod/test_tasks.py
Labels: Scope: Backend

#100672 fix: Account for discover widget split
  src/sentry/explore/translation/dashboards_translation.py
Labels: Scope: Backend

#100622 ref: bump relay version to 0.9.16
  pyproject.toml
  tests/sentry/api/endpoints/test_relay_globalconfig_v3.py
  uv.lock
Labels: Scope: Backend

#100649 chore(search): Add mixed wildcard/non-wildcard test
  tests/sentry/search/events/test_filter.py
Labels: Scope: Backend

#100686 fix(dashboards): Increase timeouts and retry count
  static/app/utils/discover/genericDiscoverQuery.tsx
  static/app/views/dashboards/datasetConfig/errors.tsx
  static/app/views/dashboards/datasetConfig/errorsAndTransactions.tsx
  static/app/views/dashboards/datasetConfig/logs.tsx
  static/app/views/dashboards/datasetConfig/spans.tsx
  static/app/views/dashboards/datasetConfig/transactions.tsx
Labels: Scope: Frontend

#100688 fix(deletions): Try smaller batches when bulk deleting rows
  src/sentry/runner/commands/cleanup.py
Labels: Scope: Backend

#100685 ref(prevent): Update config option schema
  src/sentry/types/prevent_config.py
  tests/sentry/core/endpoints/test_organization_details.py
Labels: Scope: Backend

#100536 feat(tasks) Add parameters to instrumented_task()
  src/sentry/sentry_apps/tasks/sentry_apps.py
  src/sentry/tasks/base.py
  tests/sentry/tasks/test_base.py
Labels: Scope: Backend

#100629 feat(uptime/crons): Add disable / enable toast
  static/app/actionCreators/monitors.tsx
  static/app/actionCreators/uptime.tsx
Labels: Scope: Frontend

#100636 chore(aci milestone 3): remove open period flags
  src/sentry/features/temporary.py
Labels: Scope: Backend

#100568 fix(alerts): Remove threshold for apdex when using metrics dataset
  static/app/views/alerts/rules/metric/metricField.tsx
  static/app/views/alerts/rules/metric/ruleForm.spec.tsx
  static/app/views/alerts/wizard/options.tsx
Labels: Scope: Frontend

#100703 fix(aci): fix incorrect level condition match options
  static/app/views/automations/components/actionFilters/constants.tsx
Labels: Scope: Frontend

#100612 ref(grouping): add date updated to grouphash metadata table
  migrations_lockfile.txt
  src/sentry/grouping/ingest/grouphash_metadata.py
  src/sentry/migrations/0995_add_date_updated_to_grouphash_metadata.py
  src/sentry/models/grouphashmetadata.py
Labels: Scope: Backend

#100634 feat(detectors): Improve Large HTTP Payload Detector
  src/sentry/performance_issues/detectors/large_payload_detector.py
  src/sentry/performance_issues/performance_detection.py
  tests/sentry/performance_issues/test_large_http_payload_detector.py
Labels: Scope: Backend

#100546 chore(logs): Remove logs page params
  static/app/components/events/ourlogs/ourlogsSection.tsx
  static/app/views/explore/contexts/logs/fields.tsx
  static/app/views/explore/contexts/logs/logsPageParams.tsx
  static/app/views/explore/contexts/logs/sortBys.tsx
  static/app/views/explore/logs/content.tsx
  static/app/views/explore/logs/logsAutoRefresh.spec.tsx
  static/app/views/explore/logs/logsExport.spec.tsx
  static/app/views/explore/logs/logsTab.spec.tsx
  static/app/views/explore/logs/logsToolbar.spec.tsx
  static/app/views/explore/logs/tables/logsAggregateTable.spec.tsx
  static/app/views/explore/logs/tables/logsInfiniteTable.spec.tsx
  static/app/views/explore/logs/tables/logsTableRow.spec.tsx
  static/app/views/explore/logs/useLogsQuery.spec.tsx
  static/app/views/explore/logs/useSaveAsItems.spec.tsx
  static/app/views/explore/logs/useStreamingTimeseriesResult.spec.tsx
  static/app/views/explore/logs/useVirtualStreaming.spec.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/index.tsx
  static/app/views/performance/newTraceDetails/traceOurlogs.tsx
  static/app/views/replays/detail/ourlogs/index.tsx
Labels: Scope: Frontend

#100704 fix(replay): fix useEffect to start initial timeouts
  static/app/utils/useTimeout.spec.tsx
  static/app/utils/useTimeout.tsx
  static/app/views/replays/detail/ai/useReplaySummary.tsx
Labels: Scope: Frontend

#100698 chore(preprod): Add new GET comparison run endpoint
  src/sentry/preprod/analytics.py
  src/sentry/preprod/api/endpoints/size_analysis/project_preprod_size_analysis_compare_run.py
  src/sentry/preprod/api/endpoints/urls.py
  src/sentry/preprod/api/models/size_analysis/project_preprod_size_analysis_compare_models.py
  tests/sentry/preprod/api/endpoints/size_analysis/test_project_preprod_size_analysis_compare_run.py
Labels: Scope: Backend

#100713 fix(replay): loosen date condition for cancelling start timeout
  static/app/views/replays/detail/ai/useReplaySummary.tsx
Labels: Scope: Frontend

#100716 feat(crons): Add a button to see setup docs
  static/app/views/insights/crons/components/detailsSidebar.tsx
  static/app/views/insights/crons/components/monitorQuickStartGuide.tsx
  static/app/views/insights/crons/components/onboarding.tsx
Labels: Scope: Frontend

#100699 chore(preprod): Use comparison run GET from manual compare frontend
  static/app/views/preprod/buildComparison/main/sizeCompareSelectionContent.tsx
Labels: Scope: Frontend

#100722 Revert "chore(preprod): Use comparison run GET from manual compare frontend"
  static/app/views/preprod/buildComparison/main/sizeCompareSelectionContent.tsx
Labels: Scope: Frontend

#100726 fix(explore): disable alert creation for equations
  static/app/views/explore/components/chartContextMenu.tsx
  static/app/views/explore/spans/charts/index.tsx
Labels: Scope: Frontend

#100378 :sparkles: feat(ticketing): sync group assignee using external user mapping
  src/sentry/integrations/utils/sync.py
  tests/sentry/integrations/utils/test_sync.py
Labels: Scope: Backend, Trigger: getsentry tests

#100732 chore(projects): Add comment for deprecated `has_high_priority_alerts` flag
  src/sentry/models/project.py
Labels: Scope: Backend

#100666 feat(replay): add polling using same pattern as timeSince component
  static/app/views/replays/detail/header/replayDetailsUserBadge.tsx
Labels: Scope: Frontend

#100741 fix(aci): Remove threshold from apdex() in monitor form
  static/app/views/detectors/datasetConfig/transactions.tsx
Labels: Scope: Frontend

#100742 feat(ui): Support interval / window focus refresh of useTimeWindowConfig
  static/app/components/checkInTimeline/hooks/useDateNavigation.tsx
  static/app/components/checkInTimeline/hooks/useMonitorDates.tsx
  static/app/components/checkInTimeline/hooks/useTimeWindowConfig.tsx
Labels: Scope: Frontend

#99525 feat(billing): support per category retention and downsampled retention
  src/sentry/quotas/base.py
  src/sentry/relay/config/__init__.py
  src/sentry/relay/globalconfig.py
  tests/sentry/api/endpoints/test_relay_projectconfigs.py
  tests/sentry/api/endpoints/test_relay_projectconfigs_v2.py
  tests/sentry/relay/snapshots/test_config/test_get_project_config/REGION.pysnap
  tests/sentry/relay/snapshots/test_config/test_get_project_config/REGION.pysnap.new
Labels: Scope: Backend

#100753 chore(cleanup): Change ReleaseFile deletion to use BulkModelDeletionTask
  src/sentry/deletions/__init__.py
Labels: Scope: Backend

#100647 feat(aci): Add support for nested dataSource error messages
  static/app/components/forms/form.tsx
  static/app/views/detectors/components/forms/editDetectorLayout.tsx
  static/app/views/detectors/components/forms/metric/metric.tsx
  static/app/views/detectors/components/forms/newDetectorLayout.tsx
  static/app/views/insights/crons/components/monitorCreateForm.tsx
  static/app/views/insights/crons/components/monitorForm.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.tsx
Labels: Scope: Frontend

#100619 fix(aci): handle createdBy for default automations
  static/app/views/automations/detail.tsx
  static/app/views/automations/new-settings.tsx
Labels: Scope: Frontend

#100764 ref(feedback): remove AI title gen skipped metrics
  src/sentry/feedback/usecases/ingest/create_feedback.py
Labels: Scope: Backend

#97675 feat(ui): introduce nuqs on the Project Details page for the issueType filter
  jest.config.ts
  package.json
  pnpm-lock.yaml
  static/app/components/feedback/decodeMailbox.ts
  static/app/components/feedback/list/feedbackListBulkSelection.tsx
  static/app/components/feedback/list/feedbackListHeader.tsx
  static/app/components/feedback/list/mailboxPicker.tsx
  static/app/components/feedback/useFeedbackListQueryKey.tsx
  static/app/components/feedback/useMailbox.ts
  static/app/main.tsx
  static/app/views/projectDetail/projectIssues.tsx
  static/gsAdmin/init.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: WIP, Scope: Frontend

#100663 ref(relay): Removes sessions rollout option
  src/sentry/options/defaults.py
  src/sentry/relay/globalconfig.py
Labels: Scope: Backend

#100769 ref(analytics): unify analytics imports
  src/sentry/analytics/events/api_token_created.py
  src/sentry/analytics/events/api_token_deleted.py
  src/sentry/analytics/events/auth_v2.py
  src/sentry/analytics/events/org_auth_token_created.py
  src/sentry/analytics/events/org_auth_token_deleted.py
  src/sentry/analytics/events/organization_removed.py
  src/sentry/analytics/events/release_created.py
  src/sentry/web/frontend/analytics.py
Labels: Scope: Backend

#100773 fix(agent-insights): Hide IO alert for agent spans
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/eapSections/aiIOAlert.tsx
Labels: Scope: Frontend

#100690 feat(user-feedback): Use new wildcard contains op for categories
  static/app/components/feedback/summaryCategories/feedbackCategories.spec.tsx
  static/app/components/feedback/summaryCategories/feedbackCategories.tsx
Labels: Scope: Frontend

#100532 ref(explore): Improve conversion to `TimeSeries`
  static/app/utils/timeSeries/isTimeSeriesOther.spec.tsx
  static/app/utils/timeSeries/isTimeSeriesOther.tsx
  static/app/utils/timeSeries/parseGroupBy.spec.tsx
  static/app/utils/timeSeries/parseGroupBy.tsx
  static/app/views/dashboards/widgets/common/types.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/formatters/formatTimeSeriesName.spec.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/formatters/formatTimeSeriesName.tsx
  static/app/views/explore/components/chart/chartVisualization.tsx
  static/app/views/insights/common/queries/useSortedTimeSeries.tsx
Labels: Scope: Frontend

#100750 fix(logs): Order logs by item id if needed
  src/sentry/snuba/ourlogs.py
  src/sentry/testutils/cases.py
  tests/snuba/api/endpoints/test_organization_events_ourlogs.py
Labels: Scope: Backend

#100735 feat(sub v3): Update spend notifications
  static/app/views/settings/components/settingsPageHeader.tsx
  static/gsApp/hooks/settingsRoutes.tsx
  static/gsApp/utils/billing.tsx
  static/gsApp/views/subscriptionPage/notifications.spec.tsx
  static/gsApp/views/subscriptionPage/notifications.tsx
Labels: Scope: Frontend

#100778 feat(replays): Add data export
  pyproject.toml
  src/sentry/api/urls.py
  src/sentry/replays/data_export.py
  src/sentry/replays/endpoints/data_export_notifications.py
  src/sentry/snuba/referrer.py
  static/app/data/controlsiloUrlPatterns.ts
  tests/sentry/replays/conftest.py
  tests/sentry/replays/endpoints/test_data_export_notifications.py
  tests/sentry/replays/integration/test_data_export.py
  tests/sentry/replays/test_data_export.py
  tests/sentry/replays/unit/test_data_export.py
  uv.lock
Labels: Scope: Frontend, Scope: Backend

#100749 feat(crons): Improve polling
  static/app/components/checkInTimeline/hooks/useMonitorDates.tsx
  static/app/components/checkInTimeline/hooks/useTimeWindowConfig.tsx
  static/app/views/alerts/rules/crons/details.tsx
  static/app/views/alerts/rules/crons/utils.spec.tsx
  static/app/views/alerts/rules/crons/utils.tsx
  static/app/views/insights/crons/components/detailsSidebar.tsx
  static/app/views/insights/crons/components/detailsTimeline.tsx
  static/app/views/insights/crons/components/monitorCheckIns.tsx
  static/app/views/insights/crons/utils/useMonitorStats.tsx
Labels: Scope: Frontend

#100719 fix(translation): Set measurement tags as numeric
  src/sentry/discover/translation/mep_to_eap.py
  tests/sentry/discover/translation/test_mep_to_eap.py
Labels: Scope: Backend

#100718 typing(event_user): Stronger typing
  pyproject.toml
  src/sentry/search/utils.py
  src/sentry/utils/eventuser.py
Labels: Scope: Backend

#100779 ref(insights): replace `useTopNSpanMultiSeries`
  static/app/views/insights/common/components/insightsTimeSeriesWidget.tsx
  static/app/views/insights/common/queries/useTopNDiscoverMultiSeries.ts
  static/app/views/insights/mobile/screenload/components/charts/screenCharts.tsx
Labels: Scope: Frontend

#100793 chore: consolidate transaction deprecation flags (backend)
  src/sentry/incidents/grouptype.py
Labels: Scope: Backend

#100791 chore: consolidate transaction deprecation flags (frontend)
  static/app/views/alerts/rules/metric/details/index.spec.tsx
  static/app/views/alerts/rules/metric/ruleForm.spec.tsx
  static/app/views/alerts/wizard/index.spec.tsx
  static/app/views/insights/common/utils/hasEAPAlerts.tsx
Labels: Scope: Frontend

#100799 typing(unmerge): Fix failing type issue
  src/sentry/tasks/unmerge.py
Labels: Scope: Backend

#100748 feat(prevent): Add feedback widget to Tests page
  static/app/views/prevent/tests/testsWrapper.tsx
Labels: Scope: Frontend

#100431 chore(msteams): add renderer payload to previewer endpt
  src/sentry/notifications/platform/api/endpoints/internal_registered_templates.py
Labels: Scope: Backend

#100743 fix(detectors): exclude `gen_ai.chat` spans from consecutive http detector
  src/sentry/performance_issues/detectors/consecutive_http_detector.py
  tests/sentry/performance_issues/test_consecutive_http_detector.py
Labels: Scope: Backend

#100797 fix(crons): Correctly handle partial updates
  src/sentry/monitors/validators.py
  tests/sentry/monitors/test_validators.py
Labels: Scope: Backend

#100358 chore(msteams): Add msteams to the previewer ui
  static/app/debug/notifications/components/debugNotificationsPreview.tsx
  static/app/debug/notifications/previews/teamsPreview.tsx
  static/app/debug/notifications/types.ts
  static/app/debug/notifications/views/index.tsx
Labels: Scope: Frontend

#100792 feat(crons): Pass incident resolution time in status update
  src/sentry/monitors/logic/incident_occurrence.py
  src/sentry/monitors/logic/incidents.py
  tests/sentry/monitors/logic/test_mark_ok.py
Labels: Scope: Backend

#99793 core(flex): migrate styled components to Flex or Stack
  static/app/components/core/layout/index.tsx
  static/app/data/forms/projectGeneralSettings.tsx
  static/app/plugins/components/settings.tsx
  static/app/stories/layout.tsx
  static/app/views/feedback/feedbackListPage.tsx
Labels: Scope: Frontend

#100745 feat(issues): Remove tags from issue query sanitization
  static/app/components/groupPreviewTooltip/utils.tsx
  static/app/views/issueDetails/groupEventAttachments/groupEventAttachments.tsx
  static/app/views/issueDetails/groupEventAttachments/useGroupEventAttachments.tsx
  static/app/views/issueDetails/groupEvents.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.tsx
  static/app/views/issueDetails/streamline/eventList.tsx
  static/app/views/issueDetails/streamline/eventSearch.spec.tsx
  static/app/views/issueDetails/streamline/eventSearch.tsx
  static/app/views/issueDetails/streamline/hooks/useEventQuery.spec.tsx
  static/app/views/issueDetails/streamline/hooks/useEventQuery.tsx
  static/app/views/issueDetails/streamline/hooks/useIssueDetailsDiscoverQuery.tsx
  static/app/views/issueDetails/streamline/issueTagsPreview.tsx
  static/app/views/issueDetails/useGroupEvent.tsx
  static/app/views/issueDetails/utils.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#100817 dev: bump to devservices 1.2.2
  pyproject.toml
  uv.lock
Labels: Scope: Backend

#100738 feat(grouping): Add `key` property to components and variants
  src/sentry/grouping/component.py
  src/sentry/grouping/variants.py
  tests/sentry/grouping/test_grouphash_metadata.py
Labels: Scope: Backend

#100815 test(ui): Hook up nuqs testing adapter to test router
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#100239 chore(np): Add slack link to block kit builder to notification previewer
  static/app/debug/notifications/previews/slackPreview.tsx
  static/app/debug/notifications/types.ts
  static/app/debug/notifications/views/index.tsx
Labels: Scope: Frontend

#100802 feat(pr-page): add files list components
  static/app/views/pullRequest/details/main/prFilesList.tsx
  static/app/views/pullRequest/details/main/pullRequestDetailsMainContent.tsx
Labels: Scope: Frontend

#100828 fix(crons): Fix check-in chart colors
  static/app/views/insights/crons/components/monitorStats.tsx
Labels: Scope: Frontend

#100835 fix(detectors): Fix typo in performance issue settings
  static/app/views/settings/projectPerformance/projectPerformance.spec.tsx
  static/app/views/settings/projectPerformance/projectPerformance.tsx
Labels: Scope: Frontend

#100632 ref(tables): Refactor a swath of GridEditable tables to use shared column resize strategies
  static/app/components/tables/gridEditable/index.stories.tsx
  static/app/components/tables/gridEditable/index.tsx
  static/app/components/tables/gridEditable/useQueryBasedColumnResize.tsx
  static/app/components/tables/gridEditable/useStateBasedColumnResize.tsx
  static/app/views/alerts/rules/metric/details/relatedTransactions.tsx
  static/app/views/discover/table/tableView.tsx
  static/app/views/discover/utils.spec.tsx
  static/app/views/discover/utils.tsx
  static/app/views/insights/agents/components/modelsTable.tsx
  static/app/views/insights/agents/components/toolsTable.tsx
  static/app/views/insights/agents/components/tracesTable.tsx
  static/app/views/insights/agents/hooks/useColumnOrder.tsx
  static/app/views/insights/browser/resources/components/tables/resourceSummaryTable.tsx
  static/app/views/insights/browser/resources/components/tables/resourceTable.tsx
  static/app/views/insights/cache/components/tables/transactionsTable.tsx
  static/app/views/insights/crons/components/monitorCheckInsGrid.tsx
  static/app/views/insights/database/components/tables/queriesTable.tsx
  static/app/views/insights/database/components/tables/queryTransactionsTable.tsx
  static/app/views/insights/http/components/tables/domainTransactionsTable.tsx
  static/app/views/insights/http/components/tables/domainsTable.tsx
  static/app/views/insights/mcp/components/mcpPromptsTable.tsx
  static/app/views/insights/mcp/components/mcpResourcesTable.tsx
  static/app/views/insights/mcp/components/mcpToolsTable.tsx
  static/app/views/insights/mobile/appStarts/components/tables/spanOperationTable.tsx
  static/app/views/insights/mobile/common/components/tables/screensTable.tsx
  static/app/views/insights/mobile/screenload/components/tables/eventSamplesTable.tsx
  static/app/views/insights/mobile/screenload/components/tables/screenLoadSpansTable.tsx
  static/app/views/insights/pages/backend/backendTable.tsx
  static/app/views/insights/pages/frontend/frontendOverviewTable.tsx
  static/app/views/insights/pages/mobile/mobileOverviewTable.tsx
  static/app/views/insights/pages/platform/laravel/commandsTable.tsx
  static/app/views/insights/pages/platform/laravel/jobsTable.tsx
  static/app/views/insights/pages/platform/laravel/pathsTable.tsx
  static/app/views/insights/pages/platform/nextjs/apiTable.tsx
  static/app/views/insights/pages/platform/nextjs/clientTable.tsx
  static/app/views/insights/pages/platform/shared/table/index.tsx
  static/app/views/insights/queues/components/tables/queuesTable.tsx
  static/app/views/insights/queues/components/tables/transactionsTable.tsx
  static/app/views/insights/sessions/components/tables/releaseHealthTable.tsx
  static/app/views/performance/transactionSummary/transactionEvents/eventsTable.tsx
  static/app/views/performance/transactionSummary/transactionTags/tagValueTable.tsx
  static/app/views/performance/vitalDetail/table.tsx
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsAuditLogTable.tsx
Labels: Scope: Frontend

#100847 fix(search): Avoid double-wildcards in search
  src/sentry/api/event_search.py
Labels: Scope: Backend

#100852 chore(aci): Add timer to track Detector evaluation duration
  src/sentry/workflow_engine/processors/detector.py
Labels: Scope: Backend

#100658 feat(ui): Set Select's menuReplacement prop default to 'auto'
  static/app/components/core/select/index.tsx
  static/app/components/forms/controls/reactSelectWrapper.tsx
  static/app/components/modals/projectCreationModal.tsx
  static/app/components/modals/widgetBuilder/addToDashboardModal.tsx
  static/app/views/alerts/rules/uptime/uptimeAlertForm.tsx
  static/app/views/dashboards/widgetBuilder/components/sortBySelector.tsx
  static/app/views/dashboards/widgetBuilder/components/sortBySelectors.tsx
  static/app/views/dashboards/widgetBuilder/components/visualize/aggregateParameterField.tsx
  static/app/views/discover/table/queryField.tsx
  static/app/views/insights/crons/components/monitorCreateForm.tsx
  static/app/views/insights/crons/components/monitorForm.tsx
  static/app/views/projectInstall/createProject.tsx
Labels: Scope: Frontend

#100862 ref(gaming): Remove 'project-creation-games-tab' feature flag
  static/app/components/onboarding/frameworkSuggestionModal.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/consoleExtensions.tsx
  static/app/components/platformPicker.spec.tsx
  static/app/components/platformPicker.tsx
  static/app/data/platformPickerCategories.tsx
  static/app/views/onboarding/onboarding.tsx
  static/app/views/settings/projectGeneralSettings/index.spec.tsx
  static/app/views/settings/projectGeneralSettings/index.tsx
  static/gsApp/utils/broadcasts.tsx
Labels: Scope: Frontend

#100775 ref(profiling): add platform to the eap metrics tags
  src/sentry/profiles/task.py
Labels: Scope: Backend

#100872 ref(test): disallow location as a string
  static/app/components/globalDrawer/index.spec.tsx
  static/app/views/explore/logs/content.spec.tsx
  static/gsAdmin/views/customerDetails.spec.tsx
  tests/js/sentry-test/reactTestingLibrary.spec.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#100870 ref(analytics): Simplify event recording method by removing deprecated overloads
  src/sentry/analytics/base.py
  src/sentry/notifications/notifications/base.py
  tests/sentry/analytics/test_base.py
Labels: Scope: Backend

#100673 chore(iOS): Add new apple devices (iPhone 17, Watch 11, SE 3 and Ultra 3) (frontend)
  static/app/constants/ios-device-list.tsx
Labels: Scope: Frontend, Scope: Backend

#100671 feat(spans): Add more user.geo.* fields to shared sentry attributes
  src/sentry/spans/consumers/process_segments/enrichment.py
Labels: Scope: Backend

#100707 feat(explore): Handle group bys as managed fields
  static/app/views/explore/contexts/pageParamsContext/index.spec.tsx
  static/app/views/explore/contexts/pageParamsContext/index.tsx
  static/app/views/explore/hooks/useAddToDashboard.spec.tsx
  static/app/views/explore/hooks/useTab.spec.tsx
  static/app/views/explore/hooks/useTab.tsx
  static/app/views/explore/queryParams/managedFields.spec.tsx
  static/app/views/explore/queryParams/managedFields.tsx
  static/app/views/explore/spans/spansExport.tsx
  static/app/views/explore/toolbar/index.spec.tsx
Labels: Scope: Frontend

#100781 chore(tasks) Remove usage of taskworker_config pt2
  src/sentry/middleware/integrations/tasks.py
  src/sentry/releases/tasks.py
  src/sentry/tasks/activity.py
  src/sentry/tasks/auth/auth.py
  src/sentry/tasks/auto_enable_codecov.py
  src/sentry/tasks/auto_ongoing_issues.py
  src/sentry/tasks/auto_source_code_config.py
  src/sentry/tasks/clear_expired_resolutions.py
  src/sentry/tasks/clear_expired_rulesnoozes.py
  src/sentry/tasks/clear_expired_snoozes.py
  src/sentry/tasks/codeowners/code_owners_auto_sync.py
  src/sentry/tasks/codeowners/update_code_owners_schema.py
  src/sentry/tasks/commit_context.py
  src/sentry/tasks/commits.py
  src/sentry/tasks/delete_seer_grouping_records.py
  src/sentry/tasks/digests.py
  src/sentry/tasks/merge.py
  src/sentry/tasks/options.py
  src/sentry/tasks/release_registry.py
  src/sentry/tasks/reprocessing2.py
  src/sentry/tasks/store.py
  src/sentry/tasks/user_report.py
  src/sentry/tasks/weekly_escalating_forecast.py
Labels: Scope: Backend

#99595 fix(auth): allow assigning SSO default role to current user's role or below
  src/sentry/web/frontend/organization_auth_settings.py
  tests/sentry/web/frontend/test_organization_auth_settings.py
Labels: Scope: Backend

#100854 feat(features): add vercel log drain endpoint feature flag
  src/sentry/features/temporary.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#100818 feat(sub v3): new Billing Info page
  static/gsApp/components/billingDetails/panel.tsx
  static/gsApp/components/creditCardEdit/panel.tsx
  static/gsApp/hooks/settingsRoutes.tsx
  static/gsApp/views/amCheckout/steps/checkoutV3/addBillingInfo.tsx
  static/gsApp/views/subscriptionPage/billingInformation.spec.tsx
  static/gsApp/views/subscriptionPage/billingInformation.tsx
Labels: Scope: Frontend

#100669 chore(explore): Migrate traces to use query params for query
  static/app/views/explore/components/schemaHints/schemaHintsList.spec.tsx
  static/app/views/explore/contexts/pageParamsContext/index.spec.tsx
  static/app/views/explore/contexts/pageParamsContext/index.tsx
  static/app/views/explore/hooks/useAddToDashboard.tsx
  static/app/views/explore/hooks/useAnalytics.tsx
  static/app/views/explore/spans/spansQueryParams.tsx
  static/app/views/explore/spans/spansTab.tsx
  static/app/views/explore/tables/aggregatesTable.tsx
  static/app/views/explore/tables/fieldRenderer.spec.tsx
  static/app/views/explore/tables/fieldRenderer.tsx
  static/app/views/explore/tables/tracesTable/index.tsx
  static/app/views/explore/tables/tracesTable/spansTable.tsx
  static/app/views/explore/toolbar/toolbarSaveAs.tsx
Labels: Scope: Frontend

#99796 core(flex): migrate styled components to Flex or Stack
  static/app/components/errorBoundary.tsx
  static/app/components/replaysOnboarding/replayOnboardingLayout.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/views/projectDetail/projectQuickLinks.tsx
Labels: Scope: Frontend

#100875 feat(sub v3): Create remaining subpages
  static/gsApp/views/subscriptionPage/usageHistory.spec.tsx
  static/gsApp/views/subscriptionPage/usageHistory.tsx
  static/gsApp/views/subscriptionPage/usageLog.spec.tsx
  static/gsApp/views/subscriptionPage/usageLog.tsx
Labels: Scope: Frontend

#100810 chore(cleanup): Add File cleanup task
  src/sentry/deletions/defaults/file.py
  tests/sentry/deletions/test_file.py
Labels: Scope: Backend

#100861 fix(feedback): dont track categories error response if no seer ack
  static/app/components/feedback/summaryCategories/feedbackCategories.tsx
Labels: Scope: Frontend

#100701 ci(jest): Read jest-balance.json from github artifacts dynamically during frontend CI Jest tests
  .github/workflows/frontend.yml
  .github/workflows/jest-balance.yml
  tests/js/test-balancer/jest-balance.json
Labels: Scope: Frontend

#100894 chore(eslint): Remove await rule exclusion
  eslint.config.mjs
Labels: Scope: Frontend

#100159 fix(aci): Expose json validation errors in detectors
  src/sentry/workflow_engine/endpoints/validators/base/detector.py
  src/sentry/workflow_engine/models/detector.py
  tests/sentry/uptime/endpoints/test_detector.py
Labels: Scope: Backend

#100811 fix(insights) Fix timestamp for web vital issue creation
  static/app/components/events/interfaces/performance/eventTraceView.tsx
  static/app/views/insights/browser/webVitals/utils/useRunSeerAnalysis.tsx
Labels: Scope: Frontend

#100889 feat(eap): Support numeric values in eap count_unique
  src/sentry/search/eap/spans/aggregates.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#100886 ref(prevent): Config update schema
  src/sentry/types/prevent_config.py
  tests/sentry/core/endpoints/test_organization_details.py
Labels: Scope: Backend

#100825 feat(sub v3): Billing Info header card
  static/gsApp/components/billingDetails/panel.tsx
  static/gsApp/components/creditCardEdit/panel.tsx
  static/gsApp/components/partnerPlanEndingBanner.tsx
  static/gsApp/views/subscriptionPage/billingInformation.spec.tsx
  static/gsApp/views/subscriptionPage/headerCards/billingInfoCard.spec.tsx
  static/gsApp/views/subscriptionPage/headerCards/billingInfoCard.tsx
  static/gsApp/views/subscriptionPage/headerCards/headerCards.tsx
  static/gsApp/views/subscriptionPage/headerCards/subscriptionCard.tsx
  static/gsApp/views/subscriptionPage/headerCards/subscriptionHeaderCard.tsx
  static/gsApp/views/subscriptionPage/managedNote.tsx
  static/gsApp/views/subscriptionPage/pendingChanges.tsx
  static/gsApp/views/subscriptionPage/subscriptionHeader.spec.tsx
  static/gsApp/views/subscriptionPage/subscriptionHeader.tsx
  static/gsApp/views/subscriptionPage/trialAlert.tsx
Labels: Scope: Frontend

#100848 chore(aci): add index on Action.config fields for sentry apps
  migrations_lockfile.txt
  src/sentry/workflow_engine/migrations/0093_add_action_config_index.py
  src/sentry/workflow_engine/models/action.py
Labels: Scope: Backend

#100884 feat(detectors): Ignore consecutive http issues with 3 or more hosts
  src/sentry/issue_detection/detectors/consecutive_http_detector.py
Labels: Scope: Backend

#100554 chore: Rollout feature.organizations:new-page-filter for all
  .cursor/rules/typescript_tests.mdc
  static/app/actionCreators/pageFilters.spec.tsx
  static/app/actionCreators/pageFilters.tsx
  static/app/components/events/ourlogs/ourlogsSection.spec.tsx
  static/app/components/modals/widgetViewerModal.spec.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/useCurrentProjectState.spec.tsx
  static/app/components/organizations/datePageFilter.spec.tsx
  static/app/components/organizations/environmentPageFilter/index.spec.tsx
  static/app/components/organizations/pageFilters/container.spec.tsx
  static/app/components/organizations/projectPageFilter/index.spec.tsx
  static/app/stores/pageFiltersStore.tsx
  static/app/views/alerts/list/header.spec.tsx
  static/app/views/automations/list.spec.tsx
  static/app/views/dashboards/detail.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.spec.tsx
  static/app/views/detectors/list.spec.tsx
  static/app/views/explore/hooks/useGetTraceItemAttributeValues.spec.tsx
  static/app/views/explore/hooks/useTraceItemAttributeKeys.spec.tsx
  static/app/views/explore/hooks/useTraces.spec.tsx
  static/app/views/explore/logs/tables/logsAggregateTable.spec.tsx
  static/app/views/explore/logs/tables/logsInfiniteTable.spec.tsx
  static/app/views/explore/logs/tables/logsTableRow.spec.tsx
  static/app/views/explore/multiQueryMode/content.spec.tsx
  static/app/views/explore/spans/spansTab.spec.tsx
  static/app/views/insights/browser/webVitals/components/pageOverviewSidebar.spec.tsx
  static/app/views/insights/browser/webVitals/views/pageOverview.spec.tsx
  static/app/views/issueDetails/groupUptimeChecks.spec.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.spec.tsx
  static/app/views/issueDetails/streamline/eventGraph.spec.tsx
  static/app/views/issueList/index.spec.tsx
  static/app/views/issueList/issueViews/issueViewSaveButton.spec.tsx
  static/app/views/issueList/overview.spec.tsx
  static/app/views/organizationStats/index.spec.tsx
  static/app/views/performance/newTraceDetails/trace.spec.tsx
  static/app/views/performance/onboarding.spec.tsx
  static/app/views/releases/list/index.spec.tsx
  static/app/views/replays/list.spec.tsx
  static/app/views/settings/components/dataScrubbing/modals/form/attributeField.spec.tsx
  tests/js/fixtures/log.ts
Labels: Scope: Frontend

#100888 chore(notif-platform): UI Updates for Previews
  static/app/debug/notifications/components/debugNotificationsPreview.tsx
  static/app/debug/notifications/previews/slackPreview.tsx
  static/app/debug/notifications/previews/teamsPreview.tsx
  static/app/debug/notifications/views/index.tsx
Labels: Scope: Frontend

#100906 feat(eap-alerts): Add apdex to span alerts allowlist
  src/sentry/incidents/logic.py
Labels: Scope: Backend

#100876 feat(pr-page): add endpoint to fetch Github comments
  src/sentry/integrations/github/client.py
  src/sentry/integrations/source_code_management/metrics.py
  src/sentry/preprod/api/endpoints/organization_pullrequest_comments.py
  src/sentry/preprod/api/endpoints/organization_pullrequest_details.py
  src/sentry/preprod/api/endpoints/urls.py
  src/sentry/preprod/integration_utils.py
  src/sentry/preprod/pull_request/comment_types.py
  tests/sentry/preprod/api/endpoints/test_organization_pullrequest_comments.py
  tests/sentry/preprod/pull_request/test_comment_types.py
Labels: Scope: Backend

#100827 ref(replay): add analytic when ai tab is rendered
  static/app/utils/analytics/replayAnalyticsEvents.tsx
  static/app/views/replays/detail/layout/focusTabs.tsx
Labels: Scope: Frontend

#100556 chore: Cleanup feature.organizations:new-page-filter
  src/sentry/features/temporary.py
  tests/sentry/api/serializers/test_organization.py
Labels: Scope: Backend

#100541 chore(dashboards): Decouple search bar data providers from context wrappers
  static/app/utils/customMeasurements/customMeasurementsProvider.tsx
  static/app/views/dashboards/datasetConfig/base.tsx
  static/app/views/dashboards/datasetConfig/errors.tsx
  static/app/views/dashboards/datasetConfig/logs.tsx
  static/app/views/dashboards/datasetConfig/spans.tsx
  static/app/views/explore/contexts/traceItemAttributeContext.tsx
Labels: Scope: Frontend

#100794 ref(ts): typings for data-test-id
  static/app/components/eventOrGroupHeader.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issueSummary.tsx
  static/gsAdmin/components/dropdownActions.tsx
  static/gsApp/types/index.tsx
Labels: Scope: Frontend

#100829 core(layout): migrate components to layout primitives
  static/app/components/checkInTimeline/checkInTooltip.tsx
  static/app/components/onboarding/gettingStartedDoc/onboardingLayout.tsx
  static/app/components/pluginConfig.tsx
  static/app/components/replaysOnboarding/replayOnboardingLayout.tsx
  static/app/components/replaysOnboarding/sidebar.tsx
  static/app/components/scoreCard.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filterOperator.tsx
  static/app/components/tables/simpleTable/index.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/views/admin/adminQueue.tsx
  static/app/views/admin/installWizard/index.tsx
  static/app/views/discover/table/quickContext/quickContextHovercard.tsx
  static/app/views/issueDetails/groupTags/tagDetailsDrawerContent.tsx
  static/app/views/organizationStats/teamInsights/styles.tsx
  static/app/views/performance/transactionSummary/transactionProfiles/content.tsx
  static/app/views/performance/transactionSummary/transactionVitals/vitalCard.tsx
  static/app/views/profiling/landingAggregateFlamegraph.tsx
  static/app/views/relocation/uploadBackup.tsx
  static/app/views/setupWizard/waitingForWizardToConnect.tsx
  static/app/views/setupWizard/wizardProjectSelection.tsx
Labels: Scope: Frontend

#100900 fix(ourlogs): Let existing queries be saved
  static/app/views/explore/logs/useSaveAsItems.tsx
Labels: Scope: Frontend

#100913 fix(insights): Fix Web Vitals performance score chart always using 12h intervals
  static/app/views/insights/common/components/widgets/performanceScoreBreakdownChartWidget.tsx
Labels: Scope: Frontend

#100914 chore(uptime): Move EAP testcase to testutils
  src/sentry/testutils/cases.py
  tests/sentry/uptime/endpoints/test_base.py
  tests/sentry/uptime/endpoints/test_organization_uptime_stats.py
  tests/sentry/uptime/endpoints/test_organization_uptime_summary.py
  tests/sentry/uptime/endpoints/test_project_uptime_alert_check_index.py
  tests/snuba/api/endpoints/test_organization_events_uptime_results.py
  tests/snuba/api/endpoints/test_organization_trace.py
  tests/snuba/api/endpoints/test_organization_trace_meta.py
Labels: Scope: Backend

#100917 fix(aci): Cleanly handle date parse failures
  src/sentry/workflow_engine/endpoints/organization_workflow_stats.py
  tests/sentry/workflow_engine/endpoints/test_organization_workflow_stats.py
Labels: Scope: Backend

#100904 ref(uptime): Move subscription limit check to validator
  src/sentry/uptime/endpoints/validators.py
  src/sentry/uptime/subscriptions/subscriptions.py
Labels: Scope: Backend

#100627 feat(open periods): Add activities to open period serializer
  src/sentry/models/groupopenperiodactivity.py
  src/sentry/workflow_engine/endpoints/serializers/group_open_period_serializer.py
  tests/sentry/workflow_engine/endpoints/test_organization_open_periods.py
Labels: Scope: Backend

#100933 fix(issues): Wrap + compress event nav based on container size
  static/app/views/issueDetails/streamline/eventNavigation.tsx
  static/app/views/issueDetails/streamline/issueDetailsEventNavigation.spec.tsx
  static/app/views/issueDetails/streamline/issueDetailsEventNavigation.tsx
Labels: Scope: Frontend

#100932 fix(autofix): Truncate commit sha on source card
  static/app/components/events/autofix/insights/autofixInsightSources.tsx
Labels: Scope: Frontend

#100931 feat(deletions): Add query filter for commits so that we can start deleting them
  src/sentry/deletions/defaults/commit.py
  tests/sentry/deletions/test_commit.py
Labels: Scope: Backend

#100342 feat(releases): add resolve in latest semver version dropdown option on issue details
  static/app/components/actions/resolve.tsx
  static/app/views/issueDetails/actions/index.tsx
  static/app/views/issueDetails/useProjectLatestSemverRelease.tsx
  static/app/views/issueDetails/useProjectReleaseVersionIsSemver.tsx
Labels: Scope: Frontend

#100940 fix(releases): null check on versionInfo
  static/app/views/issueDetails/actions/index.tsx
Labels: Scope: Frontend

#100851 feat(pr-page): Add size analysis info to PR page if available
  static/app/views/preprod/buildDetails/buildDetails.tsx
  static/app/views/preprod/buildDetails/main/buildDetailsMainContent.tsx
  static/app/views/preprod/buildDetails/sidebar/buildDetailsSidebarAppInfo.tsx
  static/app/views/preprod/buildDetails/sidebar/buildDetailsSidebarContent.spec.tsx
  static/app/views/preprod/buildDetails/sidebar/buildDetailsSidebarContent.tsx
  static/app/views/pullRequest/details/main/pullRequestDetailsSizeContent.tsx
  static/app/views/pullRequest/details/pullRequestDetails.tsx
  static/app/views/pullRequest/index.tsx
  static/app/views/pullRequest/types/pullRequestDetailsTypes.ts
Labels: Scope: Frontend

#100867 feat(profiling): add data export for profiles
  src/sentry/profiles/data_export.py
Labels: Scope: Backend

#100864 fix(gaming): Disable icon and label of a disabled platform
  static/app/components/forms/fields/selectField.tsx
  static/app/views/settings/projectGeneralSettings/index.tsx
Labels: Scope: Frontend

#100667 fix(demo-mode): Treat demo user as unauthenticated user in auth pipelines
  src/sentry/auth/helper.py
  src/sentry/options/defaults.py
  tests/sentry/web/frontend/test_auth_organization_login.py
Labels: Scope: Backend

#100951 fix(project-creation): Search being reset on patform select
  static/app/components/platformPicker.tsx
  static/app/views/projectInstall/createProject.tsx
Labels: Scope: Frontend

#100838 feat(sub v3): Receipts page + component updates
  static/gsApp/views/subscriptionPage/paymentHistory.spec.tsx
  static/gsApp/views/subscriptionPage/paymentHistory.tsx
Labels: Scope: Frontend

#100298 ref(cleanup): Some minor changes
  src/sentry/runner/commands/cleanup.py
  tests/sentry/deletions/test_cleanup.py
Labels: Scope: Backend

#100950 fix(ui): always render tabs in insights/backend to avoid flash during first navigation
  static/app/routes.tsx
  static/app/views/insights/cache/views/cacheLandingPage.tsx
  static/app/views/insights/database/views/databaseLandingPage.tsx
  static/app/views/insights/http/views/httpLandingPage.spec.tsx
  static/app/views/insights/http/views/httpLandingPage.tsx
  static/app/views/insights/pages/backend/am1BackendOverviewPage.tsx
  static/app/views/insights/pages/backend/backendOverviewPage.spec.tsx
  static/app/views/insights/pages/backend/backendOverviewPage.tsx
  static/app/views/insights/pages/backend/layout.tsx
  static/app/views/insights/pages/frontend/frontendOverviewPage.tsx
  static/app/views/insights/pages/platform/laravel/index.tsx
  static/app/views/insights/pages/platform/nextjs/index.tsx
  static/app/views/insights/pages/platform/shared/layout.tsx
  static/app/views/insights/queues/views/queuesLandingPage.tsx
Labels: Scope: Frontend

#100952 chore: remove custom metrics option/feature registrations
  src/sentry/options/defaults.py
Labels: Scope: Backend

#100916 fix(insights): Properly display no value on the Web Vitals transaction table when missing value
  static/app/views/insights/browser/webVitals/components/tables/pagePerformanceTable.tsx
Labels: Scope: Frontend

#100935 feat(aci): Add marker for previous interval to metric detector chart
  static/app/views/detectors/components/details/metric/chart.tsx
  static/app/views/detectors/components/forms/metric/metricDetectorChart.tsx
  static/app/views/detectors/hooks/useIncidentMarkers.spec.tsx
  static/app/views/detectors/hooks/useIncidentMarkers.tsx
Labels: Scope: Frontend

#100955 chore(search-bar): Break down query state actions
  static/app/components/searchQueryBuilder/hooks/useQueryBuilderState.tsx
  static/app/components/searchQueryBuilder/selectionKeyHandler.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filterKeyCombobox.tsx
  static/app/components/searchQueryBuilder/tokens/freeText.tsx
Labels: Scope: Frontend

#100908 ref(grouping): Use `variant.contributes` value in grouping info section
  static/app/components/events/groupingInfo/groupingInfo.tsx
  static/app/components/events/groupingInfo/groupingInfoSection.spec.tsx
  static/app/components/events/groupingInfo/groupingSummary.tsx
  static/app/components/events/groupingInfo/groupingVariant.spec.tsx
  static/app/components/events/groupingInfo/groupingVariant.tsx
  static/app/components/events/groupingInfo/useEventGroupingInfo.tsx
  static/app/types/event.tsx
Labels: Scope: Frontend

#100981 chore(aci milestone 3): add timestamps to open period activity serializer
  src/sentry/workflow_engine/endpoints/serializers/group_open_period_serializer.py
  tests/sentry/workflow_engine/endpoints/test_organization_open_periods.py
Labels: Scope: Backend

#100957 fix(ui): make sure drawer headers don't shrink
  static/app/components/globalDrawer/components.tsx
Labels: Scope: Frontend

#100882 chore(tasks) Remove usage of taskworker_config pt4
  src/sentry/data_export/tasks.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_transactions.py
  src/sentry/dynamic_sampling/tasks/custom_rule_notifications.py
  src/sentry/dynamic_sampling/tasks/recalibrate_orgs.py
  src/sentry/dynamic_sampling/tasks/sliding_window_org.py
  src/sentry/hybridcloud/tasks/deliver_from_outbox.py
  src/sentry/hybridcloud/tasks/deliver_webhooks.py
  src/sentry/integrations/slack/tasks/find_channel_id_for_alert_rule.py
  src/sentry/integrations/slack/tasks/find_channel_id_for_rule.py
  src/sentry/integrations/slack/tasks/link_slack_user_identities.py
  src/sentry/integrations/slack/tasks/post_message.py
  src/sentry/integrations/slack/tasks/send_notifications_on_activity.py
  src/sentry/integrations/vsts/tasks/kickoff_subscription_check.py
  src/sentry/issues/escalating/forecasts.py
  src/sentry/notifications/utils/tasks.py
  src/sentry/profiles/task.py
  src/sentry/release_health/tasks.py
  src/sentry/relocation/tasks/process.py
  src/sentry/relocation/tasks/transfer.py
  src/sentry/replays/data_export.py
  src/sentry/replays/tasks.py
  src/sentry/rules/processing/delayed_processing.py
  src/sentry/seer/autofix/issue_summary.py
  src/sentry/sentry_apps/tasks/sentry_apps.py
  src/sentry/sentry_apps/tasks/service_hooks.py
  src/sentry/tasks/auto_resolve_issues.py
  src/sentry/tasks/ping.py
  src/sentry/uptime/detectors/tasks.py
  src/sentry/uptime/rdap/tasks.py
  src/sentry/uptime/subscriptions/tasks.py
  src/sentry/workflow_engine/tasks/actions.py
  src/sentry/workflow_engine/tasks/delayed_workflows.py
  src/sentry/workflow_engine/tasks/workflows.py
  tests/sentry/workflow_engine/migrations/test_0092_repair_workflow_cron_conditions.py
Labels: Scope: Backend

#100646 feat(core): add `InlineCode` component
  static/app/components/confirmDelete.tsx
  static/app/components/core/inlineCode/index.mdx
  static/app/components/core/inlineCode/index.tsx
  static/app/components/core/text/prose.mdx
  static/app/components/core/text/prose.tsx
  static/app/stories/view/index.tsx
  static/app/stories/view/storyMdxComponent.tsx
Labels: Scope: Frontend

#100994 chore(comparative workflows): Change default sort
  static/app/views/explore/components/suspectTags/drawer.tsx
  static/app/views/explore/components/suspectTags/sortingToggle.tsx
Labels: Scope: Frontend

#100985 fix(ui): cut-off feedback button in chonk
  static/app/components/events/groupingInfo/groupingInfo.tsx
  static/app/components/events/groupingInfo/groupingSummary.tsx
Labels: Scope: Frontend

#100992 chore(aci): Stop using workflow_engine.scheduler.use_conditional_delete
  src/sentry/options/defaults.py
  src/sentry/workflow_engine/processors/schedule.py
  tests/sentry/workflow_engine/processors/test_schedule.py
Labels: Scope: Backend

#100968 feat(spans-migration): make explore URL in widget serializer
  src/sentry/api/serializers/models/dashboard.py
  src/sentry/apidocs/examples/dashboard_examples.py
  src/sentry/discover/arithmetic.py
  src/sentry/explore/translation/dashboards_translation.py
  tests/sentry/dashboards/endpoints/test_organization_dashboard_details.py
Labels: Scope: Backend

#100937 ref(releases): encode release version in useFinalizeRelease
  static/app/views/releases/components/useFinalizeRelease.tsx
Labels: Scope: Frontend

#100907 feat(eap-alerts): Add support for span apdex alerts
  static/app/utils/fields/index.ts
  static/app/views/alerts/rules/metric/eapField.spec.tsx
  static/app/views/alerts/rules/metric/eapField.tsx
  static/app/views/alerts/rules/metric/utils/onDemandMetricAlert.tsx
  static/app/views/explore/contexts/pageParamsContext/visualizes.tsx
Labels: Scope: Frontend

#100995 fix: Add validation for span alert time window
  src/sentry/incidents/serializers/alert_rule.py
  src/sentry/snuba/snuba_query_validator.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Scope: Backend

#100980 feat(workflow_engine): Add priority_level getter on detector_state
  src/sentry/workflow_engine/models/detector_state.py
  tests/sentry/workflow_engine/models/test_detector_state.py
Labels: Scope: Backend

#101025 fix(aci): Add OK to the list of supported metric detector conditions
  src/sentry/incidents/metric_issue_detector.py
Labels: Scope: Backend

#100971 fix(checkout v3): Retain query params on redirect
  static/gsApp/views/amCheckout/index.tsx
Labels: Scope: Frontend

#100160 chore(eco): Adds integrations throttled task namespace for larger batch jobs
  src/sentry/integrations/github/tasks/codecov_account_link.py
  src/sentry/taskworker/namespaces.py
Labels: Scope: Backend

#100744 feat(np cli): Add Slack & list integrations commands to CLI
  src/sentry/integrations/slack/integration.py
  src/sentry/notifications/platform/slack/provider.py
  src/sentry/options/defaults.py
  src/sentry/runner/commands/notifications.py
  tests/sentry/notifications/platform/api/endpoints/test_internal_registered_templates.py
  tests/sentry/notifications/platform/slack/test_provider.py
Labels: Scope: Backend

#100258 feat(integrations): add inbound serializers
  src/sentry/integrations/api/serializers/rest_framework/data_forwarder.py
  src/sentry/integrations/types.py
  tests/sentry/integrations/api/serializers/rest_framework/test_data_forwarder.py
Labels: Scope: Backend

#101043 fix(issues): Set stats loading state on early exit
  static/app/views/issueList/overview.spec.tsx
  static/app/views/issueList/overview.tsx
Labels: Scope: Frontend

#101037 bug(pr-page): Add leading / to pr size analysis query
  static/app/views/pullRequest/details/main/pullRequestDetailsSizeContent.tsx
Labels: Scope: Frontend

#101051 fix(cleanup): Fix commit cleanup to order by `id`
  src/sentry/runner/commands/cleanup.py
Labels: Scope: Backend
