Repository getsentry/sentry, pull requests merged in 2025-08, with the labels that each got.

#96840 ref(ourlogs): Default logs sample rate to 100%
  src/sentry/options/defaults.py
Labels: Scope: Backend

#96939 fix(ai): Move model attribute to tag so it is indexed
  static/app/views/performance/newTraceDetails/traceDrawer/details/highlightedAttributes.spec.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/highlightedAttributes.tsx
Labels: Scope: Frontend

#96931 chore(seer): Delete seer automation feature flag
  static/app/views/issueDetails/streamline/sidebar/seerNotices.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/seerNotices.tsx
  static/app/views/settings/organization/navigationConfiguration.tsx
  static/app/views/settings/organization/userOrgNavigationConfiguration.tsx
  static/app/views/settings/projectSeer/index.spec.tsx
  static/app/views/settings/projectSeer/index.tsx
  static/gsApp/views/seerAutomation/index.spec.tsx
  static/gsApp/views/seerAutomation/index.tsx
  static/gsApp/views/subscriptionPage/headerCards/seerAutomationAlert.spec.tsx
  static/gsApp/views/subscriptionPage/seerAutomationAlert.tsx
Labels: Scope: Frontend

#96930 chore(seer): delete usage of seer automation feature flag
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/endpoints/project_details.py
  src/sentry/integrations/utils/issue_summary_for_alerts.py
  src/sentry/seer/autofix/issue_summary.py
  src/sentry/tasks/post_process.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/api/endpoints/test_project_details.py
  tests/sentry/integrations/slack/test_message_builder.py
  tests/sentry/integrations/utils/test_issue_summary_for_alerts.py
  tests/sentry/seer/autofix/test_issue_summary.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#96925 bugbot: add examples to bugbot.md
  static/.cursor/BUGBOT.md
Labels: Scope: Frontend

#96949 feat(logs): Add hasLogs to project type
  static/app/types/project.tsx
  tests/js/fixtures/project.ts
Labels: Scope: Frontend

#96950 feat(preprod): Add check for updates API
  src/sentry/preprod/api/endpoints/project_preprod_check_for_updates.py
  src/sentry/preprod/api/endpoints/urls.py
Labels: Scope: Backend

#96911 docs(avatar): create combined avatar doc
  static/app/components/core/avatar/avatarList.stories.tsx
  static/app/components/core/avatar/index.mdx
  static/app/components/core/avatar/index.stories.tsx
Labels: Scope: Frontend

#96913 fix(grouping): Make grouping info stacktrace order match main stacktrace
  src/sentry/api/endpoints/event_grouping_info.py
  src/sentry/grouping/component.py
  src/sentry/grouping/strategies/newstyle.py
  tests/sentry/api/endpoints/test_event_grouping_info.py
Labels: Scope: Backend

#96612 :sparkles: feat(aci): rpc service to delete actions when integration is deleted
  src/sentry/workflow_engine/service/__init__.py
  src/sentry/workflow_engine/service/action/__init__.py
  src/sentry/workflow_engine/service/action/impl.py
  src/sentry/workflow_engine/service/action/service.py
  tests/sentry/workflow_engine/service/test_action_service.py
Labels: Scope: Backend

#96929 feat(explore): New query params context for explore
  static/app/types/utils.tsx
  static/app/views/explore/logs/content.tsx
  static/app/views/explore/logs/logsQueryParams.spec.tsx
  static/app/views/explore/logs/logsQueryParams.tsx
  static/app/views/explore/logs/logsQueryParamsProvider.tsx
  static/app/views/explore/queryParams/aggregateField.ts
  static/app/views/explore/queryParams/aggregateSortBy.ts
  static/app/views/explore/queryParams/context.tsx
  static/app/views/explore/queryParams/cursor.ts
  static/app/views/explore/queryParams/field.ts
  static/app/views/explore/queryParams/groupBy.ts
  static/app/views/explore/queryParams/mode.ts
  static/app/views/explore/queryParams/query.ts
  static/app/views/explore/queryParams/readableQueryParams.ts
  static/app/views/explore/queryParams/sortBy.ts
  static/app/views/explore/queryParams/visualize.ts
  static/app/views/explore/queryParams/writableQueryParams.ts
  static/app/views/explore/spans/content.tsx
  static/app/views/explore/spans/spansQueryParams.spec.tsx
  static/app/views/explore/spans/spansQueryParams.tsx
  static/app/views/explore/spans/spansQueryParamsProvider.tsx
Labels: Scope: Frontend

#96751 fix(dashboards): do not persist sort into builder preview
  static/app/views/dashboards/dashboard.tsx
  static/app/views/dashboards/sortableWidget.tsx
  static/app/views/dashboards/widgetCard/index.tsx
Labels: Scope: Frontend

#96961 ref: collapse redundant stronglist entries
  pyproject.toml
  tests/tools/mypy_helpers/test_check_stronglist.py
  tools/mypy_helpers/check_stronglist.py
Labels: Scope: Backend

#96968 fix: broken tsc
  static/app/views/insights/pages/frontend/newFrontendOverviewPage.tsx
Labels: Scope: Frontend

#96958 fix(deletions): Do not query for groups and projects from the DB
  src/sentry/deletions/tasks/nodestore.py
  tests/sentry/deletions/test_group.py
Labels: Scope: Backend

#96970 :wrench: chore(tasks): update retry handler so that ignore errors more important than retry state
  src/sentry/tasks/base.py
Labels: Scope: Backend

#96806 chore(billing): Remove conflicting transaction and spans abuse quotas
  src/sentry/quotas/base.py
  tests/sentry/quotas/test_redis.py
Labels: Scope: Backend

#96969 ref: upgrade black to 25.x
  fixtures/schema_validation.py
  requirements-dev-frozen.txt
  requirements-dev.txt
  src/sentry/api/event_search.py
  src/sentry/apidocs/api_ownership_allowlist_dont_modify.py
  src/sentry/apidocs/api_publish_status_allowlist_dont_modify.py
  src/sentry/conf/api_pagination_allowlist_do_not_modify.py
  src/sentry/db/postgres/base.py
  src/sentry/debug_files/artifact_bundles.py
  src/sentry/digests/utils.py
  src/sentry/eventstream/kafka/protocol.py
  src/sentry/hybridcloud/rpc/__init__.py
  src/sentry/incidents/endpoints/organization_alert_rule_details.py
  src/sentry/ingest/transaction_clusterer/__init__.py
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/ingest/transaction_clusterer/meta.py
  src/sentry/ingest/transaction_clusterer/tree.py
  src/sentry/issues/ownership/grammar.py
  src/sentry/middleware/access_log.py
  src/sentry/middleware/env.py
  src/sentry/notifications/helpers.py
  src/sentry/notifications/platform/discord/provider.py
  src/sentry/notifications/platform/email/provider.py
  src/sentry/notifications/platform/msteams/provider.py
  src/sentry/notifications/platform/renderer.py
  src/sentry/notifications/platform/slack/provider.py
  src/sentry/relay/config/measurements.py
  src/sentry/release_health/metrics_sessions_v2.py
  src/sentry/rules/actions/sentry_apps/utils.py
  src/sentry/rules/actions/utils.py
  src/sentry/snuba/metrics/fields/base.py
  src/sentry/snuba/metrics/query.py
  src/sentry/tagstore/snuba/backend.py
  src/sentry/testutils/pytest/fixtures.py
  src/sentry/testutils/silo.py
  src/sentry/utils/arroyo.py
  src/sentry/utils/committers.py
  src/sentry/utils/concurrent.py
  src/sentry/utils/options.py
  src/sentry/utils/query.py
  src/sentry/utils/services.py
  src/sentry/utils/types.py
  src/sentry/workflow_engine/endpoints/utils/filters.py
  src/sentry/workflow_engine/processors/data_packet.py
  src/sentry/workflow_engine/processors/data_source.py
  src/sentry/workflow_engine/processors/delayed_workflow.py
  src/sentry/workflow_engine/processors/detector.py
  tests/sentry/backup/__init__.py
  tests/sentry/grouping/test_components.py
Labels: Scope: Backend

#96963 :wrench: chore(vsts subscription task): log more info about identity invalid errors and prevent retries
  src/sentry/integrations/vsts/tasks/subscription_check.py
Labels: Scope: Backend

#96959 ref: convert monitor json fields to django JSONField / LegacyTextJSONField
  migrations_lockfile.txt
  src/sentry/db/models/fields/jsonfield.py
  src/sentry/monitors/migrations/0007_monitors_json_field.py
  src/sentry/monitors/models.py
Labels: Scope: Backend

#96922 feat(Codecov): expand codecov context to save repos/branches per org
  static/app/components/codecov/branchSelector/branchSelector.tsx
  static/app/components/codecov/container/codecovParamsProvider.tsx
  static/app/components/codecov/context/codecovContext.tsx
  static/app/components/codecov/integratedOrgSelector/integratedOrgSelector.tsx
  static/app/components/codecov/repoSelector/repoSelector.tsx
Labels: Scope: Frontend

#96478 feat(replay): update frontend async polling for breadcrumb summaries
  static/app/views/replays/detail/ai/ai.tsx
  static/app/views/replays/detail/ai/chapterList.tsx
  static/app/views/replays/detail/ai/useFetchReplaySummary.spec.tsx
  static/app/views/replays/detail/ai/useFetchReplaySummary.tsx
  static/app/views/replays/detail/ai/utils.tsx
Labels: Scope: Frontend

#96606 TA Onboarding Responsiveness
  static/app/views/codecov/tests/onboarding.tsx
  static/app/views/codecov/tests/onboardingSteps/onboardingStep.tsx
  static/app/views/codecov/tests/preOnboarding.tsx
Labels: Scope: Frontend

#96827 test(trace-waterfall): Adding acceptance tests
  fixtures/page_objects/explore_spans.py
  fixtures/page_objects/trace_view.py
  tests/acceptance/test_explore_spans.py
  tests/acceptance/test_trace_view_from_explore.py
  tests/acceptance/test_trace_view_waterfall.py
Labels: Scope: Backend

#96977 chore(issues): Clean up parameterization experiment
  src/sentry/grouping/parameterization.py
  tests/sentry/grouping/test_parameterization.py
Labels: Scope: Backend

#96991 fix(insights): incorrect span metrics ribbon values in db summary
  static/app/views/insights/database/components/tables/queryTransactionsTable.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.spec.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.tsx
Labels: Scope: Frontend

#96993 chore(explore): Remove legacy trace explorer ui
  static/app/views/explore/hooks/useTraceSpans.spec.tsx
  static/app/views/explore/hooks/useTraceSpans.tsx
  static/app/views/explore/logs/tables/logsInfiniteTable.tsx
  static/app/views/explore/logs/tables/logsTable.tsx
  static/app/views/explore/tables/tracesTable/fieldRenderers.tsx
  static/app/views/explore/tables/tracesTable/spansTable.tsx
  static/app/views/explore/tables/tracesTable/types.tsx
  static/app/views/explore/tables/tracesTable/utils.tsx
  static/app/views/insights/database/settings.ts
  static/app/views/performance/newTraceDetails/traceRow/traceBar.tsx
  static/app/views/traces/content.tsx
  static/app/views/traces/data.tsx
  static/app/views/traces/fieldRenderers.spec.tsx
  static/app/views/traces/fieldRenderers.tsx
  static/app/views/traces/hooks/usePageParams.spec.tsx
  static/app/views/traces/hooks/usePageParams.tsx
  static/app/views/traces/hooks/useTraceSpans.spec.tsx
  static/app/views/traces/hooks/useTraceSpans.tsx
  static/app/views/traces/hooks/useTraces.spec.tsx
  static/app/views/traces/hooks/useTraces.tsx
  static/app/views/traces/spansTable.tsx
  static/app/views/traces/styles.tsx
  static/app/views/traces/tracesChart.tsx
  static/app/views/traces/tracesSearchBar.tsx
  static/app/views/traces/tracesTable.tsx
  static/app/views/traces/utils.tsx
Labels: Scope: Frontend

#96999 ref(replay): add note about segment count limit
  static/app/views/replays/detail/ai/ai.tsx
Labels: Scope: Frontend

#96971 feat(aci): Add cron create/edit form
  static/app/components/workflowEngine/ui/section.tsx
  static/app/types/workflowEngine/detectors.tsx
  static/app/views/detectors/components/forms/common/assignSection.tsx
  static/app/views/detectors/components/forms/cron/detect.tsx
  static/app/views/detectors/components/forms/cron/fields.tsx
  static/app/views/detectors/components/forms/cron/index.tsx
  static/app/views/detectors/components/forms/cron/resolve.tsx
  static/app/views/detectors/components/forms/editDetectorLayout.tsx
  static/app/views/detectors/components/forms/index.tsx
  static/app/views/detectors/components/forms/metric/metric.tsx
  static/app/views/detectors/components/forms/newDetectorLayout.tsx
  static/app/views/detectors/components/forms/uptime/fields.tsx
  static/app/views/detectors/components/forms/uptime/index.tsx
Labels: Scope: Frontend

#96995 fix(ourlogs): Add another guard for timestamp precise being missing
  static/app/views/explore/logs/useVirtualStreaming.spec.tsx
  static/app/views/explore/logs/useVirtualStreaming.tsx
Labels: Scope: Frontend

#96853 feat(search): added subtitles to monitor_check_in_failure and uptime_…
  static/app/types/group.tsx
Labels: Scope: Frontend

#96928 feat(replay): use summary provider
  static/app/views/replays/detail/ai/ai.tsx
  static/app/views/replays/detail/ai/replaySummaryContext.tsx
  static/app/views/replays/detail/ai/useFetchReplaySummary.spec.tsx
  static/app/views/replays/detail/ai/useFetchReplaySummary.tsx
  static/app/views/replays/detail/body/replayDetailsProviders.tsx
Labels: Scope: Frontend

#97012 test(ui): Attempt to fix flake in dropdown menu test
  static/app/components/dropdownMenu/index.spec.tsx
Labels: Scope: Frontend

#96964 fix(detectors): Add filtering for Zend1 framework queries
  fixtures/events/performance_problems/sql-injection/sql-injection-event-zf1.json
  src/sentry/performance_issues/detectors/sql_injection_detector.py
  tests/sentry/performance_issues/test_sql_injection_detector.py
Labels: Scope: Backend

#97013 test(ui): Extend spansTab test
  static/app/views/explore/spans/spansTab.spec.tsx
Labels: Scope: Frontend

#97009 fix(replay): don't reset time on tab change
  static/app/utils/replays/hooks/useReplayData.tsx
Labels: Scope: Frontend

#97018 nit(aci): add word break to prevent conditions panel overflow
  static/app/views/automations/components/conditionsPanel.tsx
Labels: Scope: Frontend

#97014 ref(grouping): Clarify `has_url_origin` parameter
  src/sentry/grouping/strategies/newstyle.py
  src/sentry/grouping/strategies/utils.py
Labels: Scope: Backend

#97017 ref(grouping): Small grouping refactors
  src/sentry/grouping/api.py
  src/sentry/grouping/strategies/base.py
  src/sentry/grouping/strategies/configurations.py
  src/sentry/grouping/variants.py
  tests/sentry/grouping/test_enhancer.py
  tests/sentry/grouping/test_enhancer_dart_flutter_javascript.py
  tests/sentry/grouping/test_enhancer_dart_flutter_native.py
Labels: Scope: Backend

#97019 ref(grouping): Clean up variant handling in grouping strategy base
  src/sentry/grouping/strategies/base.py
Labels: Scope: Backend

#97025 fix(issues): Align "in this issue"
  static/app/views/issueDetails/streamline/eventNavigation.tsx
Labels: Scope: Frontend

#97023 feat(integrations): Refetch code mappings on delete
  static/app/views/settings/organizationIntegrations/integrationCodeMappings.spec.tsx
  static/app/views/settings/organizationIntegrations/integrationCodeMappings.tsx
Labels: Scope: Frontend

#97029 ref(grouping): Refactor context line handling
  src/sentry/grouping/strategies/newstyle.py
Labels: Scope: Backend

#97030 ref(grouping): Refactor `register_strategy_config`
  src/sentry/grouping/strategies/configurations.py
Labels: Scope: Backend

#96953 feat(seer): Add advanced seer org settings
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/apidocs/examples/organization_examples.py
  src/sentry/constants.py
  src/sentry/integrations/utils/issue_summary_for_alerts.py
  src/sentry/seer/autofix/autofix.py
  tests/sentry/api/endpoints/test_organization_details.py
  tests/sentry/integrations/slack/test_message_builder.py
  tests/sentry/integrations/utils/test_issue_summary_for_alerts.py
  tests/sentry/seer/autofix/test_autofix.py
Labels: Scope: Backend

#97020 chore(autofix): Random UI polish
  static/app/components/events/autofix/autofixChanges.tsx
  static/app/components/events/autofix/autofixDiff.tsx
  static/app/components/events/autofix/autofixRootCause.tsx
  static/app/components/events/autofix/autofixSolution.tsx
  static/app/components/events/autofix/autofixSolutionEventItem.tsx
  static/app/components/events/autofix/autofixTimelineItem.tsx
Labels: Scope: Frontend

#96983 fix: not-allowed cursor on buttons
  static/app/components/core/button/styles.chonk.tsx
Labels: Scope: Frontend

#97028 ref(issues): decrease rate limits for GroupTagKeyValues endpoint again
  src/sentry/api/endpoints/group_tagkey_values.py
  tests/sentry/api/endpoints/test_group_tagkey_values.py
Labels: Scope: Backend

#97051 ref: mark monitors migration as post deploy
  src/sentry/monitors/migrations/0007_monitors_json_field.py
Labels: Scope: Backend

#96954 feat(seer): Add advanced settings section
  static/app/components/events/autofix/autofixSolution.tsx
  static/app/components/events/autofix/autofixSteps.tsx
  static/app/types/organization.tsx
  static/gsApp/views/seerAutomation/seerAutomationDefault.tsx
  tests/js/fixtures/organization.ts
Labels: Scope: Frontend

#96938 feat: Add console section to unreal and native docs
  static/app/components/onboarding/consoleModal.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/consoleExtensions.tsx
  static/app/constants/consolePlatforms.ts
  static/app/gettingStartedDocs/native/native.tsx
  static/app/gettingStartedDocs/unreal/unreal.tsx
Labels: Scope: Frontend

#96942 ref(dynamic-sampling): replace model factory with direct calls
  src/sentry/dynamic_sampling/models/factory.py
  src/sentry/dynamic_sampling/models/projects_rebalancing.py
  src/sentry/dynamic_sampling/models/transactions_rebalancing.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_projects.py
  src/sentry/dynamic_sampling/tasks/boost_low_volume_transactions.py
  tests/sentry/dynamic_sampling/models/test_base.py
  tests/sentry/dynamic_sampling/models/test_projects_rebalancing.py
  tests/sentry/dynamic_sampling/models/test_transactions_rebalancing.py
  tests/sentry/dynamic_sampling/tasks/test_tasks.py
Labels: Scope: Backend

#97058 feat: Replace captureFeedback with sendFeedback api & show error if happens
  static/app/components/modals/privateGamingSdkAccessModal.tsx
Labels: Scope: Frontend

#96962 fix: styling of input in settings breadcrumbs menu
  static/app/components/dropdownAutoComplete/menu.tsx
Labels: Scope: Frontend

#96936 ref(relay): Cleanup never used log options
  src/sentry/options/defaults.py
  src/sentry/relay/globalconfig.py
Labels: Scope: Backend

#97060 ref(dynamic-sampling): remove model type enum
  src/sentry/dynamic_sampling/models/base.py
Labels: Scope: Backend

#97066 feat(mcp-insights): link errors to trace explorer
  static/app/views/insights/mcp/components/mcpPromptsTable.tsx
  static/app/views/insights/mcp/components/mcpResourcesTable.tsx
  static/app/views/insights/mcp/components/mcpToolsTable.tsx
Labels: Scope: Frontend

#97068 feat(agents-insights): backend analytics
  src/sentry/analytics/events/agent_monitoring_events.py
  src/sentry/api/endpoints/organization_events_stats.py
Labels: Scope: Backend

#96990 Make breakpoint type partial record
  static/app/components/core/layout/styles.tsx
Labels: Scope: Frontend

#97021 feat(replay): update states of ai summaries
  static/app/views/replays/detail/ai/ai.tsx
Labels: Scope: Frontend

#97090 ref(aci): Remove 'retry_timeouts' decorator
  src/sentry/tasks/summaries/weekly_reports.py
  src/sentry/workflow_engine/tasks/utils.py
  src/sentry/workflow_engine/tasks/workflows.py
Labels: Scope: Backend

#96941 feat(ui): apiOptions
  static/app/api/apiDefinition.ts
  static/app/api/apiOptions.spec.tsx
  static/app/api/apiOptions.ts
  static/app/api/getApiUrl.ts
  static/app/utils/useRelease.tsx
Labels: Scope: Frontend

#97098 fix(assignment): move rate limiting after debounce checks
  src/sentry/tasks/post_process.py
  tests/sentry/tasks/test_post_process.py
Labels: Scope: Backend

#96923 fix(aci): fix delayed workflow after evaluating all fast conditions first
  src/sentry/workflow_engine/processors/delayed_workflow.py
  src/sentry/workflow_engine/processors/workflow.py
  tests/sentry/workflow_engine/processors/test_delayed_workflow.py
  tests/sentry/workflow_engine/processors/test_workflow.py
  tests/sentry/workflow_engine/test_integration.py
  tests/sentry/workflow_engine/test_task.py
Labels: Scope: Backend

#97111 fix(workflow_engine): Update the `comparison` key on a DataCondition to be CamelCased
  src/sentry/workflow_engine/endpoints/serializers.py
  tests/sentry/workflow_engine/endpoints/test_serializers.py
Labels: Scope: Backend

#96908 ref(groupingInfo): move feedback button inline with groupInfoSummary
  static/app/components/events/groupingInfo/groupingInfo.tsx
Labels: Scope: Frontend

#97112 fix(router): Silence react router warnings in tests
  package.json
  pnpm-lock.yaml
  static/app/components/codecov/summary.spec.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/useCurrentProjectState.spec.tsx
Labels: Scope: Frontend

#97120 fix(router): Silence react router warnings in tests (#97112)
  package.json
  pnpm-lock.yaml
  static/app/components/codecov/summary.spec.tsx
  static/app/components/onboarding/gettingStartedDoc/utils/useCurrentProjectState.spec.tsx
Labels: Scope: Frontend

#97108 feat(prevent): Initial prevent AI onboarding routes + enum update
  static/app/routes.tsx
  static/app/views/codecov/pathnames.spec.ts
  static/app/views/codecov/preventAI/onboarding.tsx
  static/app/views/codecov/preventAI/wrapper.spec.tsx
  static/app/views/codecov/preventAI/wrapper.tsx
  static/app/views/codecov/settings.tsx
  static/app/views/nav/primary/config.tsx
  static/app/views/nav/primary/index.tsx
  static/app/views/nav/secondary/secondaryNavContent.tsx
  static/app/views/nav/secondary/sections/codecov/codecovSecondaryNav.spec.tsx
  static/app/views/nav/secondary/sections/codecov/codecovSecondaryNav.tsx
  static/app/views/nav/types.tsx
  static/app/views/nav/useActiveNavGroup.spec.tsx
Labels: Scope: Frontend

#97125 fix(aci): handle deleted Workflows and DataConditionGroups in delayed workflow task
  src/sentry/workflow_engine/processors/delayed_workflow.py
  tests/sentry/workflow_engine/processors/test_delayed_workflow.py
Labels: Scope: Backend

#97133 chore(sidebar): Update my/all project icon sizes
  static/app/views/nav/projectIcon.tsx
Labels: Scope: Frontend

#97132 ref(issues): remove project event date limit flag
  src/sentry/issues/endpoints/project_events.py
  tests/snuba/api/endpoints/test_project_events.py
Labels: Scope: Backend

#97122 feat(emerge): Add treemap search
  static/app/views/preprod/buildDetails.tsx
  static/app/views/preprod/components/visualizations/appSizeTreemap.tsx
  static/app/views/preprod/main/buildDetailsMainContent.tsx
  static/app/views/preprod/utils/treemapFiltering.spec.tsx
  static/app/views/preprod/utils/treemapFiltering.ts
  tests/js/fixtures/preProdAppSize.ts
Labels: Scope: Frontend

#97094 ref(access-logs): use `entity_id` instead of `auth_id` in access logs
  src/sentry/middleware/access_log.py
  tests/sentry/middleware/test_access_log_middleware.py
Labels: Scope: Backend

#97100 ref(replay): update AI tab disabled state, analytics, and too short conditions
  static/app/utils/analytics/replayAnalyticsEvents.tsx
  static/app/views/replays/detail/ai/ai.tsx
Labels: Scope: Frontend

#96952 fix(search): MutableSearch stripping quotes from escaped values
  static/app/utils/tokenizeSearch.spec.tsx
  static/app/utils/tokenizeSearch.tsx
Labels: Scope: Frontend

#97158 feat(mcp-insights): onboarding instructions
  static/app/components/onboarding/gettingStartedDoc/types.ts
  static/app/gettingStartedDocs/node/awslambda.tsx
  static/app/gettingStartedDocs/node/azurefunctions.tsx
  static/app/gettingStartedDocs/node/cloudflare-pages.tsx
  static/app/gettingStartedDocs/node/cloudflare-workers.tsx
  static/app/gettingStartedDocs/node/connect.tsx
  static/app/gettingStartedDocs/node/express.tsx
  static/app/gettingStartedDocs/node/fastify.tsx
  static/app/gettingStartedDocs/node/gcpfunctions.tsx
  static/app/gettingStartedDocs/node/hapi.tsx
  static/app/gettingStartedDocs/node/koa.tsx
  static/app/gettingStartedDocs/node/nestjs.tsx
  static/app/gettingStartedDocs/node/node.tsx
  static/app/utils/gettingStartedDocs/node.tsx
  static/app/views/insights/mcp/views/onboarding.tsx
  static/app/views/insights/mcp/views/overview.tsx
Labels: Scope: Frontend

#97115 ref: convert discover models to use django JSONField
  migrations_lockfile.txt
  src/sentry/discover/migrations/0003_discover_json_field.py
  src/sentry/discover/models.py
  tests/sentry/deletions/tasks/test_hybrid_cloud.py
  tests/snuba/api/endpoints/test_discover_saved_queries.py
Labels: Scope: Backend

#96546 fix(ProjectPageFilter): FeatureDisabled link was not clickable
  static/app/components/organizations/projectPageFilter/index.tsx
Labels: Scope: Frontend

#97174 chore(autofix): Collapse issue summary by default if autofix run has started
  static/app/components/group/groupSummary.spec.tsx
  static/app/components/group/groupSummary.tsx
  static/app/views/issueDetails/streamline/sidebar/seerDrawer.tsx
Labels: Scope: Frontend

#97142 fix(nav): Correctly use new nav for route not found page
  static/app/views/routeNotFound.tsx
Labels: Scope: Frontend

#96984 feat(aci): Improved search config for detectors
  static/app/views/detectors/components/detectorSearch.tsx
  static/app/views/detectors/constants.tsx
  static/app/views/detectors/list.spec.tsx
  static/app/views/detectors/utils/useDetectorFilterKeys.tsx
Labels: Scope: Frontend

#97000 feat(tasks) Add a simpler control for taskworker tasks
  src/sentry/options/defaults.py
  src/sentry/tasks/base.py
  src/sentry/taskworker/task.py
  src/sentry/testutils/helpers/task_runner.py
  tests/sentry/tasks/test_relay.py
  tests/sentry/tasks/test_taskworker_rollout.py
Labels: Scope: Backend

#97177 chore(issues): remove registration for project event date flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#97181 fix(grid-editable): remove grid-template-columns style
  static/app/components/tables/gridEditable/styles.tsx
Labels: Scope: Frontend

#97137 fix(stats): Better links for stats tabs
  static/app/views/nav/useRedirectNavV2Routes.spec.tsx
  static/app/views/nav/useRedirectNavV2Routes.tsx
  static/app/views/organizationStats/organizationStatsWrapper.tsx
  static/app/views/organizationStats/pathname.tsx
Labels: Scope: Frontend

#93396 feat(member merge): frontend for manual merge
  static/app/routes.tsx
  static/app/views/settings/account/mergeAccounts.spec.tsx
  static/app/views/settings/account/mergeAccounts.tsx
  tests/js/fixtures/mergeAccounts.ts
Labels: Scope: Frontend

#96830 feat(errors): Support error upsampling on Number of Errors alert
  src/sentry/incidents/endpoints/serializers/alert_rule.py
  src/sentry/incidents/serializers/alert_rule.py
  src/sentry/search/events/fields.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
  tests/sentry/incidents/endpoints/test_serializers.py
  tests/sentry/incidents/subscription_processor/test_subscription_processor.py
  tests/sentry/search/events/builder/test_errors.py
Labels: Scope: Backend

#97178 fix(typing): add return types to "special" methods
  src/bitfield/models.py
  src/bitfield/types.py
  src/sentry/api/client.py
  src/sentry/api/endpoints/project_artifact_bundle_files.py
  src/sentry/api/endpoints/project_release_files.py
  src/sentry/db/models/fields/node.py
  src/sentry/eventstore/models.py
  src/sentry/exceptions.py
  src/sentry/integrations/messaging/commands.py
  src/sentry/interfaces/base.py
  src/sentry/interfaces/exception.py
  src/sentry/lang/native/applecrashreport.py
  src/sentry/lang/native/error.py
  src/sentry/models/apiapplication.py
  src/sentry/models/apigrant.py
  src/sentry/models/apikey.py
  src/sentry/models/apiscopes.py
  src/sentry/models/apitoken.py
  src/sentry/models/authidentity.py
  src/sentry/models/authidentityreplica.py
  src/sentry/models/authprovider.py
  src/sentry/models/authproviderreplica.py
  src/sentry/models/group.py
  src/sentry/models/organization.py
  src/sentry/models/orgauthtoken.py
  src/sentry/models/project.py
  src/sentry/models/projectkey.py
  src/sentry/models/team.py
  src/sentry/net/http.py
  src/sentry/plugins/providers/integration_repository.py
  src/sentry/relocation/models/relocation.py
  src/sentry/rules/processing/delayed_processing.py
  src/sentry/sentry_apps/models/servicehook.py
  src/sentry/snuba/sessions_v2.py
  src/sentry/stacktraces/processing.py
  src/sentry/tasks/summaries/utils.py
  src/sentry/utils/datastructures.py
  src/sentry/utils/marketo_client.py
  src/sentry/utils/retries.py
  src/social_auth/exceptions.py
  src/social_auth/models.py
  tests/sentry/api/test_utils.py
Labels: Scope: Backend

#96893 :sparkles: feat(aci): trigger resolved activity for metric issues
  src/sentry/incidents/action_handlers.py
  src/sentry/incidents/typings/metric_detector.py
  src/sentry/integrations/metric_alerts.py
  src/sentry/notifications/notification_action/types.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_discord_metric_alert_handler.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_email_metric_alert_handler.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_msteams_metric_alert_handler.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_opsgenie_metric_alert_handler.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_pagerduty_metric_alert_handler.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_sentry_app_metric_alert_handler.py
  tests/sentry/notifications/notification_action/metric_alert_registry/test_slack_metric_alert_handler.py
  tests/sentry/notifications/notification_action/test_metric_alert_registry_handlers.py
Labels: Scope: Backend

#97109 chore(detectors): Remove `is_span_eligible` class methods
  src/sentry/performance_issues/detectors/experiments/n_plus_one_api_calls_detector.py
  src/sentry/performance_issues/detectors/n_plus_one_api_calls_detector.py
  src/sentry/performance_issues/detectors/query_injection_detector.py
  src/sentry/performance_issues/detectors/slow_db_query_detector.py
  src/sentry/performance_issues/detectors/sql_injection_detector.py
  tests/sentry/performance_issues/experiments/test_n_plus_one_api_calls_detector.py
  tests/sentry/performance_issues/test_n_plus_one_api_calls_detector.py
Labels: Scope: Backend

#97131 feat(aci): add hits to detector/workflow GET response headers
  src/sentry/workflow_engine/endpoints/organization_detector_index.py
  src/sentry/workflow_engine/endpoints/organization_workflow_index.py
  tests/sentry/workflow_engine/endpoints/test_organization_detector_index.py
  tests/sentry/workflow_engine/endpoints/test_organization_workflow_index.py
Labels: Scope: Backend

#96992 feat(trace-eap-waterfall): Fixing link to profile from trace drawer
  static/app/views/performance/newTraceDetails/traceDrawer/details/missingInstrumentation.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/profiling/profilePreview.tsx
Labels: Scope: Frontend

#97140 fix(crons): backfill migration for check-in processing error IDs
  migrations_lockfile.txt
  src/sentry/monitors/migrations/0008_fix_processing_error_keys.py
  tests/sentry/monitors/migrations/__init__.py
  tests/sentry/monitors/migrations/test_0008_fix_processing_error_keys.py
Labels: Scope: Backend

#97141 feat(replay): Refetch the replay list after all bulk-delete tasks complete
  static/app/components/replays/bulkDelete/useReplayBulkDeleteAuditLog.tsx
  static/app/views/replays/list.spec.tsx
  static/app/views/replays/list.tsx
  static/app/views/replays/list/bulkDeleteAlert.tsx
  static/app/views/replays/list/listContent.tsx
  static/app/views/replays/list/replayIndexTable.tsx
Labels: Scope: Frontend

#96821 feat(uptime): Allow uptime spans to be fetched from the `organiation_trace` endpoint.
  src/sentry/api/endpoints/organization_trace.py
  src/sentry/search/eap/uptime_results/attributes.py
  src/sentry/snuba/trace.py
  src/sentry/uptime/endpoints/project_uptime_alert_checks_index.py
  tests/sentry/uptime/endpoints/test_base.py
  tests/snuba/api/endpoints/test_organization_trace.py
Labels: Scope: Backend

#97011 chore(spans): Remove indexed spans variant of span fields endpoint
  src/sentry/api/endpoints/organization_spans_fields.py
  tests/sentry/api/endpoints/test_organization_spans_fields.py
Labels: Scope: Backend

#97022 feat(uptime): Optionally include uptime stats in `organization_trace_meta`
  src/sentry/api/endpoints/organization_trace_meta.py
  tests/snuba/api/endpoints/test_organization_trace_meta.py
Labels: Scope: Backend

#96967 feat(explore): Swap mode hook to query params context
  static/app/views/explore/contexts/pageParamsContext/index.tsx
  static/app/views/explore/hooks/useAddToDashboard.spec.tsx
  static/app/views/explore/hooks/useAddToDashboard.tsx
  static/app/views/explore/queryParams/context.tsx
  static/app/views/explore/spans/charts/index.spec.tsx
  static/app/views/explore/spans/spansTab.spec.tsx
  static/app/views/explore/spans/spansTab.tsx
  static/app/views/explore/tables/index.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  static/app/views/explore/toolbar/toolbarSaveAs.tsx
  static/app/views/explore/toolbar/toolbarSortBy.tsx
Labels: Scope: Frontend

#97211 fix(search): Convert search syntax error to log
  static/app/components/searchSyntax/parser.tsx
Labels: Scope: Frontend

#97210 feat(onboarding): Add logs to java onboarding
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/java/java.tsx
  static/app/gettingStartedDocs/java/log4j2.tsx
  static/app/gettingStartedDocs/java/logback.tsx
  static/app/gettingStartedDocs/java/spring-boot.tsx
  static/app/gettingStartedDocs/java/spring.spec.tsx
  static/app/gettingStartedDocs/java/spring.tsx
Labels: Scope: Frontend

#97110 ref: unconvert some JSONField to LegacyTextJSONField
  migrations_lockfile.txt
  src/sentry/db/models/fields/jsonfield.py
  src/sentry/migrations/0962_json_fields_too_big.py
  src/sentry/models/auditlogentry.py
  src/sentry/models/options/project_option.py
  src/sentry/testutils/asserts.py
Labels: Scope: Backend

#97147 ref(grouping): Naming and docs tweaks
  src/sentry/api/endpoints/grouping_configs.py
  src/sentry/api/endpoints/project_grouping_configs.py
  src/sentry/grouping/__init__.py
  src/sentry/grouping/api.py
  src/sentry/grouping/enhancer/__init__.py
  src/sentry/grouping/enhancer/actions.py
  src/sentry/grouping/ingest/config.py
  src/sentry/grouping/strategies/base.py
  src/sentry/grouping/strategies/configurations.py
  src/sentry/grouping/strategies/message.py
  src/sentry/grouping/strategies/newstyle.py
  src/sentry/grouping/strategies/security.py
  src/sentry/grouping/strategies/template.py
  src/sentry/grouping/strategies/utils.py
  tests/sentry/grouping/__init__.py
  tests/sentry/grouping/test_benchmark.py
  tests/sentry/grouping/test_grouphash_metadata.py
  tests/sentry/grouping/test_hashing.py
  tests/sentry/issues/endpoints/test_group_similar_issues_embeddings.py
Labels: Scope: Backend

#97187 fix(apis): fix api owner test
  .github/CODEOWNERS
  src/sentry/api/api_owners.py
  src/sentry/api/bases/organization_events.py
  src/sentry/api/endpoints/organization_dashboard_details.py
  src/sentry/api/endpoints/organization_dashboard_widget_details.py
  src/sentry/api/endpoints/organization_dashboards.py
  src/sentry/api/endpoints/organization_dashboards_starred.py
  src/sentry/api/endpoints/organization_events_histogram.py
  src/sentry/api/endpoints/organization_spans_fields.py
  src/sentry/api/endpoints/organization_spans_fields_stats.py
  src/sentry/api/endpoints/organization_tags.py
  src/sentry/api/endpoints/organization_trace_item_attributes.py
  src/sentry/api/endpoints/organization_trace_item_attributes_ranked.py
  src/sentry/api/endpoints/organization_traces.py
  src/sentry/api/endpoints/project_create_sample_transaction.py
  src/sentry/api/endpoints/project_performance_general_settings.py
  src/sentry/api/endpoints/project_performance_issue_settings.py
  src/sentry/api/endpoints/project_trace_item_details.py
  src/sentry/api/endpoints/project_transaction_threshold.py
  src/sentry/data_export/endpoints/data_export_details.py
  src/sentry/discover/endpoints/discover_homepage_query.py
  src/sentry/discover/endpoints/discover_saved_queries.py
  src/sentry/discover/endpoints/discover_saved_query_detail.py
  src/sentry/explore/endpoints/explore_saved_queries.py
  src/sentry/explore/endpoints/explore_saved_query_detail.py
  src/sentry/explore/endpoints/explore_saved_query_starred.py
  src/sentry/explore/endpoints/explore_saved_query_starred_order.py
  src/sentry/insights/endpoints/starred_segments.py
  src/sentry/seer/endpoints/organization_page_web_vitals_summary.py
  tests/sentry/api/test_api_owners.py
Labels: Scope: Backend

#97213 feat(ui): Switch to mobx-react-lite, upgrade mobx
  package.json
  pnpm-lock.yaml
  static/app/components/events/interfaces/spans/index.tsx
  static/app/components/events/interfaces/spans/traceView.tsx
  static/app/components/forms/form.tsx
  static/app/components/forms/formField/controlState.tsx
  static/app/components/forms/formField/index.tsx
  static/app/views/alerts/rules/uptime/uptimeAlertForm.tsx
  static/app/views/insights/crons/components/monitorCreateForm.tsx
  static/app/views/insights/crons/components/monitorForm.tsx
  static/app/views/integrationPipeline/awsLambdaFunctionSelect.tsx
  static/app/views/integrationPipeline/awsLambdaProjectSelect.tsx
  static/app/views/performance/traceDetails/newTraceDetailsTransactionBar.tsx
  static/app/views/settings/account/notifications/notificationSettingsByType.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDetails.tsx
Labels: Scope: Frontend

#97209 fix(events): Handle nulls in arrays
  src/sentry/snuba/discover.py
  tests/snuba/api/endpoints/test_organization_events_stats.py
Labels: Scope: Backend

#97220 fix(search): Release builde filter use recents
  src/sentry/search/eap/spans/filter_aliases.py
  src/sentry/search/events/datasets/filter_aliases.py
Labels: Scope: Backend

#97218 ref(issues): decrease rate limits for GroupTagKeyValues endpoint 3
  src/sentry/api/endpoints/group_tagkey_values.py
  tests/sentry/api/endpoints/test_group_tagkey_values.py
Labels: Scope: Backend

#97114 feat(issues): move merge button out of dropdown
  fixtures/page_objects/issue_list.py
  static/app/views/issueList/actions/actionSet.tsx
  static/app/views/issueList/actions/index.spec.tsx
Labels: Scope: Frontend, Scope: Backend

#97216 fix(stories): Improve checkInTimeline cursor position
  static/app/components/checkInTimeline/checkInTimeline.stories.tsx
Labels: Scope: Frontend

#97225 feat(emerge): Android use uncompressed size
  static/app/views/preprod/sidebar/buildDetailsSidebarAppInfo.tsx
Labels: Scope: Frontend

#97203 feat(aci): Add detector sorting by latest group
  src/sentry/workflow_engine/endpoints/organization_detector_index.py
  tests/sentry/workflow_engine/endpoints/test_organization_detector_index.py
Labels: Scope: Backend

#97232 fix(aci): Add more properties to SimpleGroupSerializer
  src/sentry/api/serializers/models/group.py
  tests/sentry/api/serializers/test_group.py
Labels: Scope: Backend

#97233 chore(aci): throw log when delayed workflow task starts
  src/sentry/workflow_engine/processors/delayed_workflow.py
Labels: Scope: Backend

#97240 ref(settings): Use useParams in ApiTokenDetails
  static/app/routes.tsx
  static/app/utils/useParams.tsx
  static/app/views/settings/account/apiTokenDetails.spec.tsx
  static/app/views/settings/account/apiTokenDetails.tsx
Labels: Scope: Frontend

#97237 ref(ecosystem): Use new router hooks in sentryAppExternalInstallation
  static/app/views/sentryAppExternalInstallation/index.spec.tsx
  static/app/views/sentryAppExternalInstallation/index.tsx
Labels: Scope: Frontend

#97239 fix(integrations): Fix typo in comment
  src/sentry/integrations/tasks/sync_status_inbound.py
Labels: Scope: Backend

#97251 fix(explorer): Attempt fix at profile execution tree construction
  src/sentry/seer/autofix/autofix.py
  src/sentry/seer/explorer/index_data.py
Labels: Scope: Backend

#97252 fix: Improve copy above project name based on permission
  static/app/views/projectInstall/createProject.tsx
Labels: Scope: Frontend

#97259 feat(spanv2): Add experimental span v2 processing feature flag
  src/sentry/features/temporary.py
  src/sentry/relay/config/__init__.py
Labels: Scope: Backend

#97260 fix(mcp-insights): manual instrumentation link
  static/app/views/insights/agentMonitoring/views/onboarding.tsx
  static/app/views/insights/mcp/views/onboarding.tsx
Labels: Scope: Frontend

#97231 fix(discover): Hide any from discover chart options
  static/app/utils/discover/eventView.tsx
Labels: Scope: Frontend

#97047 chore(trace ai queries): Display unsupported reason and mode
  static/app/views/explore/components/seerComboBox/hooks.ts
  static/app/views/explore/components/seerComboBox/seerComboBox.tsx
Labels: Scope: Frontend

#97113 ref: convert notificationmessage to LegacyTextJSONField
  migrations_lockfile.txt
  src/sentry/notifications/migrations/0002_notificationmessage_jsonfield.py
  src/sentry/notifications/models/notificationmessage.py
Labels: Scope: Backend

#97223 feat(trace-eap-waterfall): Mitigating layout shift in the trace view page
  static/app/views/performance/newTraceDetails/traceHeader/index.tsx
  static/app/views/performance/newTraceDetails/traceHeader/styles.tsx
  static/app/views/performance/newTraceDetails/traceTabsAndVitals.tsx
Labels: Scope: Frontend

#97226 chore(spans-migration): Add flag for banner
  src/sentry/features/temporary.py
Labels: Scope: Backend

#97050 chore(trace ai queries): Human readable queries
  static/app/views/explore/components/seerComboBox/queryTokens.tsx
  static/app/views/explore/components/seerComboBox/seerComboBox.tsx
  static/app/views/explore/components/seerComboBox/seerSearchListBox.tsx
  static/app/views/explore/components/seerComboBox/utils.ts
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#97242 ref(insights): Use useParams in DatabaseSpanSummaryPage
  static/app/routes.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.spec.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.tsx
Labels: Scope: Frontend

#97275 feat(logs): Enable the sampling param
  src/sentry/api/endpoints/organization_trace_logs.py
  src/sentry/search/eap/constants.py
  src/sentry/snuba/ourlogs.py
Labels: Scope: Backend

#97281 fix(preprod): update insight text color
  static/app/views/preprod/main/insights/appSizeInsights.tsx
Labels: Scope: Frontend

#97205 chore(tasks) Stop checking namespace rollout options
  src/sentry/tasks/base.py
  tests/sentry/tasks/test_base.py
  tests/sentry/tasks/test_taskworker_rollout.py
Labels: Scope: Backend

#96965 feat(feedback): Generate AI user feedback titles
  src/sentry/features/temporary.py
  src/sentry/feedback/usecases/ingest/create_feedback.py
  src/sentry/feedback/usecases/title_generation.py
  tests/sentry/feedback/usecases/ingest/test_create_feedback.py
  tests/sentry/feedback/usecases/test_title_generation.py
Labels: Scope: Backend

#97256 feat(trace-eap-waterfall): Updating eap span row children count
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/performance/newTraceDetails/traceRow/traceSpanRow.tsx
Labels: Scope: Frontend

#97197 feat(trace-eap-waterfall): Searching through full tree
  static/app/views/performance/newTraceDetails/trace.spec.tsx
  static/app/views/performance/newTraceDetails/trace.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchEvaluator.spec.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchEvaluator.tsx
  static/app/views/performance/newTraceDetails/traceSearch/traceSearchInput.tsx
Labels: Scope: Frontend

#96916 feat(aci): add bulk update detectors endpoint
  src/sentry/workflow_engine/endpoints/organization_detector_index.py
  src/sentry/workflow_engine/endpoints/validators/detector_workflow.py
  tests/sentry/workflow_engine/endpoints/test_organization_detector_index.py
Labels: Scope: Backend

#97257 feat(trace-eap-waterfall): Adding spans count and issues count to tra…
  static/app/utils/analytics/tracingEventMap.tsx
  static/app/views/performance/newTraceDetails/issuesTraceWaterfall.tsx
  static/app/views/performance/newTraceDetails/traceAnalytics.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/issues/issues.tsx
  static/app/views/performance/newTraceDetails/traceHeader/meta.tsx
  static/app/views/performance/newTraceDetails/traceModels/issuesTraceTree.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
Labels: Scope: Frontend

#97274 feat(onboarding): Add logs to angular verify step
  static/app/gettingStartedDocs/javascript/angular.spec.tsx
  static/app/gettingStartedDocs/javascript/angular.tsx
Labels: Scope: Frontend

#97295 fix(aci): Narrow starvation window in buffer_processing
  src/sentry/rules/processing/buffer_processing.py
Labels: Scope: Backend

#97247 feat(aci): Add latest group to detector tables
  static/app/components/group/inboxBadges/shortId.tsx
  static/app/components/workflowEngine/gridCell/issueCell.tsx
  static/app/types/group.tsx
  static/app/types/workflowEngine/detectors.tsx
  static/app/utils/events.tsx
  static/app/views/automations/components/connectedMonitorsList.tsx
  static/app/views/detectors/components/details/error/index.spec.tsx
  static/app/views/detectors/components/detectorListTable/detectorListRow.tsx
  static/app/views/detectors/list.spec.tsx
  tests/js/fixtures/detectors.ts
  tests/js/fixtures/group.ts
Labels: Scope: Frontend

#97298 ref: convert scheduleddeletion models to django JSONField
  migrations_lockfile.txt
  src/sentry/deletions/models/scheduleddeletion.py
  src/sentry/migrations/0963_scheduleddeletion_json_field.py
Labels: Scope: Backend

#97300 feat(sdk): Upgrade Sentry SDKs to 10.2.0
  package.json
  pnpm-lock.yaml
Labels: Scope: Frontend

#97302 feat(issues): Add flag to enable workflow notifications for a group type
  src/sentry/incidents/grouptype.py
  src/sentry/issues/grouptype.py
  src/sentry/models/activity.py
  tests/sentry/models/test_activity.py
Labels: Scope: Backend

#97217 feat(onboarding): Add logs to php onboarding
  static/app/components/onboarding/productSelection.tsx
  static/app/gettingStartedDocs/php/laravel.spec.tsx
  static/app/gettingStartedDocs/php/laravel.tsx
  static/app/gettingStartedDocs/php/php.spec.tsx
  static/app/gettingStartedDocs/php/php.tsx
  static/app/gettingStartedDocs/php/symfony.spec.tsx
Labels: Scope: Frontend

#97297 Update token colors on summary.tsx
  static/app/components/codecov/summary.tsx
Labels: Scope: Frontend

#97306 fix(access-logs): rate limit type not correctly set to snuba
  src/sentry/middleware/access_log.py
  tests/sentry/middleware/test_access_log_middleware.py
Labels: Scope: Backend

#97312 feat(aci): Add latest group sorting to frontend
  static/app/views/detectors/components/detectorListTable/index.tsx
  static/app/views/detectors/list.spec.tsx
  static/app/views/detectors/list.tsx
Labels: Scope: Frontend

#97316 Add s4s regions to reserved org slugs
  src/sentry/constants.py
Labels: Scope: Backend

#97313 feat(aci): Add disabled text to list views and properly apply system created icon
  static/app/components/workflowEngine/gridCell/automationTitleCell.tsx
  static/app/components/workflowEngine/gridCell/titleCell.tsx
  static/app/views/detectors/components/detectorLink.tsx
Labels: Scope: Frontend

#97317 ref(issues): Move group stats endpoint and tests to issues folder
  src/sentry/api/urls.py
  src/sentry/issues/endpoints/group_stats.py
  tests/sentry/issues/endpoints/test_group_stats.py
Labels: Scope: Backend

#97323 ref: Move some NOT_AVAILABLE_MESSAGES closer to their callsites
  static/app/constants/notAvailableMessages.tsx
  static/app/views/projectDetail/projectCharts.tsx
Labels: Scope: Frontend
