Repository getsentry/sentry, pull requests merged in 2025-06, with the labels that each got.

#92286 feat(source-maps): Introduce new empty state copies and react-native callout
  static/app/components/events/interfaces/sourceMapsDebuggerModal.tsx
  static/app/views/settings/projectSourceMaps/sourceMapsList.spec.tsx
  static/app/views/settings/projectSourceMaps/sourceMapsList.tsx
Labels: Scope: Frontend

#92613 feat(agent-insights): Handle new keys
  static/app/views/insights/agentMonitoring/utils/highlightedSpanAttributes.tsx
  static/app/views/insights/agentMonitoring/utils/query.tsx
Labels: Scope: Frontend

#92186 ref(project-creation): Introduce useCreateProjectRules hook
  static/app/components/onboarding/useCreateProjectRules.ts
  static/app/views/projectInstall/createProject.tsx
  static/app/views/projectInstall/issueAlertNotificationOptions.tsx
Labels: Scope: Frontend

#92287 feat(source-maps): Do not show pagination together with empty state
  static/app/views/settings/projectSourceMaps/sourceMapsList.tsx
Labels: Scope: Frontend

#92393 feat(spans): Evict spans during insert
  src/sentry/scripts/spans/add-buffer.lua
  src/sentry/spans/buffer.py
  src/sentry/spans/consumers/process/factory.py
  tests/sentry/spans/consumers/process/test_consumer.py
  tests/sentry/spans/consumers/process/test_flusher.py
  tests/sentry/spans/test_buffer.py
Labels: Scope: Backend

#92575 ref(insights): replace `span.module` with `span.category` everywhere
  static/app/utils/fields/index.ts
  static/app/views/explore/constants.tsx
  static/app/views/insights/browser/resources/views/resourcesLandingPage.spec.tsx
  static/app/views/insights/cache/settings.ts
  static/app/views/insights/common/utils/buildEventViewQuery.tsx
  static/app/views/insights/common/utils/getAlertsUrl.spec.tsx
  static/app/views/insights/common/views/spans/selectors/domainSelector.spec.tsx
  static/app/views/insights/constants.tsx
  static/app/views/insights/database/settings.ts
  static/app/views/insights/database/views/databaseLandingPage.spec.tsx
  static/app/views/insights/http/components/httpSamplesPanel.spec.tsx
  static/app/views/insights/http/settings.ts
  static/app/views/insights/http/views/httpDomainSummaryPage.spec.tsx
  static/app/views/insights/http/views/httpLandingPage.spec.tsx
  static/app/views/insights/types.tsx
  static/app/views/performance/landing/widgets/components/widgetContainer.spec.tsx
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
Labels: Scope: Frontend

#91921 ref(onboarding): centralize project flags & signals
  src/sentry/event_manager.py
  src/sentry/feedback/usecases/create_feedback.py
  src/sentry/monitors/utils.py
  src/sentry/profiles/task.py
  src/sentry/receivers/onboarding.py
  src/sentry/replays/usecases/ingest/__init__.py
  src/sentry/signals.py
  src/sentry/spans/consumers/process_segments/message.py
  src/sentry/tasks/post_process.py
  src/sentry/utils/projectflags.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/feedback/usecases/test_create_feedback.py
  tests/sentry/profiles/test_task.py
  tests/sentry/receivers/test_onboarding.py
  tests/sentry/utils/test_projectflags.py
Labels: Scope: Backend

#91613 fix(search-bar) Constrain width of list box
  static/app/components/searchQueryBuilder/tokens/filter/valueCombobox.tsx
  static/app/components/searchQueryBuilder/tokens/filter/valueListBox.tsx
Labels: Scope: Frontend

#92392 feat(ingest): Feature flag for ingestion through trusted relays only
  src/sentry/features/temporary.py
Labels: Scope: Backend

#92581 fix(similarity): dont use backfill url for deletions
  src/sentry/seer/similarity/grouping_records.py
  tests/sentry/seer/similarity/test_grouping_records.py
  tests/sentry/tasks/test_backfill_seer_grouping_records.py
Labels: Scope: Backend

#92554 chore(aci): add db constraint on WorkflowActionGroupStatus Group FK
  migrations_lockfile.txt
  src/sentry/workflow_engine/migrations/0067_workflow_action_group_status_group_db_constraint.py
  src/sentry/workflow_engine/models/workflow_action_group_status.py
Labels: Scope: Backend

#92446 ref(feedback): remove associated_event_id, has_linked_error from feedback search exclude list
  static/app/components/feedback/feedbackSearch.tsx
Labels: Scope: Frontend

#92171 ref(replay): redirect based on referrer after replay deletion
  static/app/components/events/eventReplay/replayPreviewPlayer.tsx
  static/app/utils/replays/hooks/useDeleteReplay.tsx
Labels: Scope: Frontend

#92298 ref(eslint): enable import/no-extraneous-dependencies
  eslint.config.mjs
  package.json
  static/app/__mocks__/react-date-range.tsx
  static/app/components/deprecatedSmartSearchBar/searchBarDatePicker.tsx
Labels: Scope: Frontend

#92634 ref: simplify knip config
  knip.config.ts
Labels: Scope: Frontend

#92640 ref(ui): Remove extraneous string template
  static/app/components/replays/replayTooltipTime.tsx
Labels: Scope: Frontend

#92130 chore(icon): remove brackets from folder icon
  static/app/icons/iconProject.tsx
Labels: Scope: Frontend

#92449 feat(searchbar): Add tooltip descriptions to filter keys
  static/app/components/searchQueryBuilder/formattedQuery.spec.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filterKey.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filterOperator.tsx
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#92516 fix(issues): Set resolution time if updating groups via update_group_status
  src/sentry/models/group.py
  tests/sentry/integrations/test_issues.py
Labels: Scope: Backend

#92489 fix(aci): Clean up the update logic for open periods
  src/sentry/api/helpers/group_index/update.py
  src/sentry/event_manager.py
  src/sentry/issues/status_change.py
  src/sentry/models/group.py
  src/sentry/models/groupopenperiod.py
  src/sentry/tasks/auto_resolve_issues.py
  tests/sentry/event_manager/test_event_manager.py
  tests/sentry/integrations/test_issues.py
Labels: Scope: Backend

#87821 deps(ui): Upgrade react aria April 2025
  package.json
  static/app/components/arithmeticBuilder/token/index.spec.tsx
  static/app/components/core/compactSelect/gridList/index.tsx
  static/app/components/core/compactSelect/utils.tsx
  static/app/components/core/tabs/index.spec.tsx
  static/app/components/core/tabs/tabPanels.tsx
  static/app/components/dropdownButton.tsx
  static/app/components/dropdownMenu/index.spec.tsx
  static/app/components/events/eventTags/eventTagsTree.spec.tsx
  static/app/components/events/highlights/highlightsDataSection.spec.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/combobox.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/index.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/useFilterKeyListBox.tsx
  static/app/components/searchQueryBuilder/tokens/freeText.tsx
  static/app/components/tokenizedInput/token/comboBox.tsx
  static/app/utils/useOverlay.tsx
  static/app/views/alerts/rules/metric/ruleForm.spec.tsx
  static/app/views/issueDetails/actions/index.spec.tsx
  static/app/views/issueList/issueViews/createIssueViewModal.spec.tsx
  static/app/views/profiling/landing/slowestFunctionsWidget.spec.tsx
  static/app/views/profiling/landing/slowestFunctionsWidget.tsx
  yarn.lock
Labels: Scope: Frontend

#92156 feat(Codecov): adjust codecov time selector to use codecov context
  static/app/components/codecov/datePicker/datePicker.spec.tsx
  static/app/components/codecov/datePicker/datePicker.tsx
  static/app/components/codecov/datePicker/dateSelector.spec.tsx
  static/app/components/codecov/datePicker/dateSelector.tsx
  static/app/components/codecov/utils.spec.tsx
  static/app/components/codecov/utils.tsx
  static/app/views/codecov/tests/tests.tsx
Labels: Scope: Frontend

#92653 ref(js): Use DateTime over getFormattedDate where applicable
  static/app/components/replays/replayTooltipTime.tsx
  static/app/views/dashboards/widgetCard/index.tsx
  static/app/views/insights/common/components/releaseSelector.tsx
  static/gsAdmin/views/instanceLevelOAuth/instanceLevelOAuth.tsx
  static/gsApp/components/upgradeNowModal/planTable.tsx
Labels: Scope: Frontend

#92563 fix(aci): add `createdBy` and `owner` to detector/workflow serializers
  src/sentry/workflow_engine/endpoints/serializers.py
  tests/sentry/workflow_engine/endpoints/test_serializers.py
Labels: Scope: Backend

#92650 fix(search-bar): Autocompolete as aggregate filter when it looks like…
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/freeText.tsx
Labels: Scope: Frontend

#92658 feat(issues): Add "unsupported" debug image status
  static/app/components/events/interfaces/debugMeta/debugImage/processingIcon.tsx
  static/app/components/events/interfaces/debugMeta/debugImage/status.tsx
  static/app/types/debugImage.tsx
Labels: Scope: Frontend

#92593 feat(cache): Add batch method to cached functions
  src/sentry/utils/function_cache.py
  tests/sentry/utils/test_function_cache.py
Labels: Scope: Backend

#92645 fix(replay): don't reset search bar after replay index loads
  static/app/views/replays/list/listContent.tsx
Labels: Scope: Frontend

#92427 build(ui): Use swc-plugin-component-annotate instead of babel
  package.json
  rspack.config.ts
  yarn.lock
Labels: Scope: Frontend

#92662 fix(billing): Check plan string exists
  static/gsApp/components/labelWithPowerIcon.tsx
Labels: Scope: Frontend

#92664 fix(api): Correct team member counts
  src/sentry/api/serializers/models/team.py
  tests/sentry/api/serializers/test_team.py
Labels: Scope: Backend

#92599 fix(search): Remove quotes from tags and flags
  src/sentry/api/event_search.py
  static/app/components/searchSyntax/grammar.pegjs
  tests/sentry/api/test_event_search.py
Labels: Scope: Backend

#92624 feat(dashboards): custom title when create widget via traces
  static/app/components/modals/widgetBuilder/addToDashboardModal.tsx
  static/app/views/dashboards/types.tsx
  static/app/views/discover/utils.tsx
  static/app/views/explore/hooks/useAddToDashboard.tsx
  static/app/views/explore/multiQueryMode/hooks/useAddCompareQueryToDashboard.tsx
Labels: Scope: Frontend

#92666 ref(replays): Increase thread-pool queue depth
  src/sentry/replays/consumers/recording.py
Labels: Scope: Backend

#92628 fix(insights): pass in `groupBy` for queue throughput chart
  static/app/views/insights/queues/charts/throughputChart.tsx
Labels: Scope: Frontend

#92673 ref(settings): don't show qmark tooltip if no text
  static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
Labels: Scope: Frontend

#92651 fix(issue-stream): Replace checks for issue-stream-custom-views with prefersStackedNav
  static/app/components/assistant/getGuidesContent.tsx
  static/app/components/badge/groupPriority.tsx
  static/app/views/issueDetails/streamline/sidebar/seerNotices.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/seerNotices.tsx
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/index.tsx
  static/app/views/issueList/issueSearchWithSavedSearches.tsx
  static/app/views/issueList/overview.tsx
  static/app/views/issueList/savedIssueSearches.tsx
  static/app/views/nav/index.spec.tsx
  static/app/views/nav/usePrefersStackedNav.tsx
Labels: Scope: Frontend

#92669 fix(replay): only show tooltip over selectors tab when the tab is disabled
  static/app/views/replays/tabs.tsx
Labels: Scope: Frontend

#92676 fix(admin): user booleans should not be required
  static/app/views/admin/adminUserEdit.tsx
Labels: Scope: Frontend

#92665 fix(ui): Do not apply PanelHeader styles to button / overlays
  static/app/components/panels/panelHeader.tsx
  static/app/views/settings/components/teamSelect/utils.tsx
  static/app/views/settings/organizationIntegrations/integrationReposAddRepository.tsx
Labels: Scope: Frontend

#92603 feat(workflow_engine): DataConditionHandlerTestMixin
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  tests/sentry/workflow_engine/models/test_data_condition.py
  tests/sentry/workflow_engine/test_base.py
Labels: Scope: Backend

#92582 feat(nav): Add animations for collapsable sections
  static/app/views/nav/collapsible.tsx
  static/app/views/nav/secondary/secondary.tsx
Labels: Scope: Frontend

#92001 ref(issue-views): Update backend endpoints with new packaging logic
  src/sentry/issues/endpoints/organization_group_search_view_details.py
  src/sentry/issues/endpoints/organization_group_search_view_details_starred.py
  src/sentry/issues/endpoints/organization_group_search_view_starred_order.py
  src/sentry/issues/endpoints/organization_group_search_view_visit.py
  src/sentry/issues/endpoints/organization_group_search_views.py
  src/sentry/issues/endpoints/organization_group_search_views_starred.py
  tests/sentry/issues/endpoints/test_organization_group_search_view_details.py
  tests/sentry/issues/endpoints/test_organization_group_search_view_details_starred.py
  tests/sentry/issues/endpoints/test_organization_group_search_view_visit.py
  tests/sentry/issues/endpoints/test_organization_group_search_views.py
Labels: Scope: Backend

#92675 fix(crons): Broken Monitors -> Broken Cron Monitors
  static/app/views/settings/account/notifications/fields.tsx
  static/app/views/settings/account/notifications/fields2.tsx
Labels: Scope: Frontend

#92690 fix(seer): Adjust bar colors
  static/gsApp/views/subscriptionPage/usageTotals.tsx
Labels: Scope: Frontend

#92053 ref(issue-views): Implement FE packaging logic for issue views
  static/app/views/issueList/issueViews/issueViewSaveButton.spec.tsx
  static/app/views/issueList/issueViews/issueViewSaveButton.tsx
  static/app/views/issueList/issueViews/issueViewsList/issueViewsList.spec.tsx
  static/app/views/issueList/issueViews/issueViewsList/issueViewsList.tsx
  static/app/views/issueList/issueViews/issueViewsList/issueViewsTable.tsx
  static/app/views/issueList/issueViewsHeader.tsx
  static/app/views/nav/secondary/sections/issues/issueViews/useHasIssueViews.tsx
Labels: Scope: Frontend

#92699 ref(aci): Use sentry_sdk.trace to simplify scope in delayed_workflow
  src/sentry/workflow_engine/processors/delayed_workflow.py
Labels: Scope: Backend

#92594 chore(billing): Set default values for Seer budget checkbox
  static/gsAdmin/components/changePlanAction.spec.tsx
  static/gsAdmin/components/changePlanAction.tsx
Labels: Scope: Frontend

#92709 ref(onboarding): Add persistInFlight to all mutations
  static/app/components/onboarding/useCreateProject.tsx
  static/app/components/onboarding/useMutateOnboardingTasks.tsx
Labels: Scope: Frontend

#90810 fix(crash-detection): JS `sentryWrapped` frames are not detected as a crash
  fixtures/sdk_crash_detection/crash_event_react_native.py
  src/sentry/utils/sdk_crashes/sdk_crash_detection_config.py
  tests/sentry/utils/sdk_crashes/test_sdk_crash_detection_react_native.py
Labels: Scope: Backend

#92585 feat(derived_code_mappings): Support filenames that start with backslash
  src/sentry/issues/auto_source_code_config/code_mapping.py
  src/sentry/issues/auto_source_code_config/frame_info.py
  tests/sentry/issues/auto_source_code_config/test_code_mapping.py
  tests/sentry/issues/auto_source_code_config/test_frame_info.py
Labels: Scope: Backend

#92721 feat(agents-insights): add model provider icons
  static/app/icons/iconClaude.tsx
  static/app/icons/iconGemini.tsx
  static/app/icons/iconOpenAI.tsx
  static/app/icons/index.tsx
  static/app/views/insights/agentMonitoring/components/llmGenerationsWidget.tsx
  static/app/views/insights/agentMonitoring/components/modelName.spec.tsx
  static/app/views/insights/agentMonitoring/components/modelName.tsx
  static/app/views/insights/agentMonitoring/components/modelsTable.tsx
  static/app/views/insights/agentMonitoring/components/tokenUsageWidget.tsx
Labels: Scope: Frontend

#92723 ref(span-buffer): Make lua script batched
  src/sentry/scripts/spans/add-buffer.lua
  src/sentry/spans/buffer.py
Labels: Scope: Backend

#92671 feat(alerts): Use timeseries results to compute confidence footer
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.spec.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
  static/app/views/alerts/rules/metric/utils/determineSeriesConfidence.tsx
  static/app/views/alerts/rules/metric/utils/determineSeriesSampleCount.tsx
Labels: Scope: Frontend

#92686 fix(ourlogs): Fix 24 hour time in logs
  static/app/components/dateTime.spec.tsx
  static/app/components/dateTime.tsx
  static/app/utils/dates.tsx
  static/app/views/explore/logs/fieldRenderers.spec.tsx
  static/app/views/explore/logs/fieldRenderers.tsx
Labels: Scope: Frontend

#92688 ref(feedback): infer user fields from event in v1 shims
  src/sentry/feedback/usecases/create_feedback.py
  tests/sentry/feedback/usecases/test_create_feedback.py
Labels: Scope: Backend

#92727 ref(span-buffer): Simplify script calls and queue updates
  src/sentry/scripts/spans/add-buffer.lua
  src/sentry/spans/buffer.py
Labels: Scope: Backend

#92622 chore: Option to allow switching entity key for eap alerts
  src/sentry/incidents/logic.py
  src/sentry/options/defaults.py
  src/sentry/search/events/builder/base.py
  src/sentry/snuba/entity_subscription.py
  src/sentry/snuba/tasks.py
  tests/sentry/snuba/test_tasks.py
Labels: Scope: Backend

#92408 search: fix delete token button background color
  static/app/components/searchQueryBuilder/tokens/deletableToken.tsx
  static/app/components/tokenizedInput/token/deletableToken.tsx
Labels: Scope: Frontend

#92401 theme: change mini bar chart colors
  static/app/components/charts/groupStatusChart.tsx
  static/app/components/charts/miniBarChart.tsx
Labels: Scope: Frontend

#92722 fix(ui): alignment issues in searchQueryBuilder
  static/app/components/searchQueryBuilder/index.tsx
  static/app/components/searchQueryBuilder/tokenizedQueryGrid.tsx
Labels: Scope: Frontend

#92729 fix(span-buffer): Fix bad metric
  src/sentry/spans/buffer.py
Labels: Scope: Backend

#92683 fix(detectors): Fix type error in SQL Injection Detector
  src/sentry/utils/performance_issues/detectors/sql_injection_detector.py
Labels: Scope: Backend

#92689 :wrench: chore(msteams): mark resolve in upcoming release errors as halt
  src/sentry/integrations/msteams/webhook.py
Labels: Scope: Backend

#92596 fix(anomaly detection): handle anomaly detection edge case
  static/app/views/alerts/rules/metric/ruleForm.tsx
Labels: Scope: Frontend

#92706 feat(aci): Add additional detector query types
  static/app/types/workflowEngine/dataConditions.tsx
  static/app/types/workflowEngine/detectors.tsx
  static/app/views/automations/components/connectedMonitorsList.tsx
  static/app/views/detectors/components/detailsPanel.tsx
  static/app/views/detectors/detail.spec.tsx
  static/app/views/detectors/detail.tsx
  tests/js/fixtures/detectors.ts
Labels: Scope: Frontend

#92687 fix(aci): Delete rows from GroupOpenPeriod
  migrations_lockfile.txt
  src/sentry/migrations/0916_delete_open_period_rows.py
Labels: Scope: Backend

#92670 feat(trace-eap-waterfall): Adding no instrumentation nodes to eap waterfall
  static/app/views/performance/newTraceDetails/traceApi/useIssuesTraceTree.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTraceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTraceTree.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/missingInstrumentation.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/profiling/profilePreview.tsx
  static/app/views/performance/newTraceDetails/traceModels/__snapshots__/traceTree.missinginstrumentation.spec.tsx.snap
  static/app/views/performance/newTraceDetails/traceModels/issuesTraceTree.tsx
  static/app/views/performance/newTraceDetails/traceModels/missingInstrumentationNode.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.missinginstrumentation.spec.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
Labels: Scope: Frontend

#92506 docs: Add Objective C examples to cocoa onboarding + non UI verification options
  static/app/gettingStartedDocs/apple/ios.spec.tsx
  static/app/gettingStartedDocs/apple/ios.tsx
Labels: Scope: Frontend

#92755 ref: fix prettier hook name
  .pre-commit-config.yaml
Labels: Scope: Backend

#92758 feat(ourlogs): Hide the border on the infinite scroll page
  static/app/views/explore/logs/tables/logsInfiniteTable.tsx
Labels: Scope: Frontend

#92726 chore(explore): Expose semver attributes to search
  static/app/components/performance/spanSearchQueryBuilder.tsx
Labels: Scope: Frontend

#92757 fix(forms): Do not duplicate handleInput calls
  static/app/components/forms/controls/rangeSlider/index.tsx
Labels: Scope: Frontend

#92354 feat(explore): Add equation support to the spans dataset
  src/sentry/api/endpoints/organization_events.py
  src/sentry/search/eap/columns.py
  src/sentry/search/eap/constants.py
  src/sentry/search/eap/resolver.py
  src/sentry/snuba/rpc_dataset_common.py
  src/sentry/snuba/spans_rpc.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#92766 ref: fix annotation of sentry.stacktraces.processing
  src/sentry/stacktraces/processing.py
Labels: Scope: Backend

#92753 feat(ourlogs): Implement visualize sidebar
  static/app/views/explore/contexts/logs/logsPageParams.tsx
  static/app/views/explore/logs/logsGraph.tsx
  static/app/views/explore/logs/logsTab.tsx
  static/app/views/explore/logs/logsToolbar.tsx
Labels: Scope: Frontend

#92767 ref: remove some unnecessary casts
  src/sentry/eventstore/models.py
  src/sentry/search/eap/resolver.py
  src/sentry/search/eap/utils.py
  src/sentry/search/events/builder/base.py
  src/sentry/users/api/serializers/user.py
Labels: Scope: Backend

#92657 Codecov use organization claim
  src/sentry/codecov/client.py
  src/sentry/codecov/helper.py
  tests/sentry/codecov/test_client.py
  tests/sentry/codecov/test_helper.py
Labels: Scope: Backend

#92660 ref(insights): convert web vitals chart to widget platform
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/thresholds.tsx
  static/app/views/insights/browser/webVitals/components/charts/webVitalStatusLineChart.tsx
  static/app/views/insights/browser/webVitals/components/pageOverviewWebVitalsDetailPanel.tsx
  static/app/views/insights/browser/webVitals/components/webVitalDescription.tsx
  static/app/views/insights/browser/webVitals/components/webVitalsDetailPanel.spec.tsx
  static/app/views/insights/browser/webVitals/components/webVitalsDetailPanel.tsx
  static/app/views/insights/common/components/insightsTimeSeriesWidget.tsx
Labels: Scope: Frontend

#92760 fix(nav): Update new stats & usage page with settings styles
  static/app/views/organizationStats/header.tsx
  static/app/views/organizationStats/index.tsx
  static/app/views/organizationStats/teamInsights/health.tsx
  static/app/views/organizationStats/teamInsights/issues.tsx
  static/app/views/settings/components/settingsLayout.tsx
Labels: Scope: Frontend

#92754 chore(seer): billing fixes
  static/app/views/issueDetails/streamline/hooks/useAiConfig.tsx
  static/app/views/issueDetails/streamline/sidebar/seerDrawer.tsx
  static/gsApp/components/ai/AiSetupDataConsent.tsx
Labels: Scope: Frontend

#92769 feat(ourlogs): Add top n querying
  src/sentry/api/endpoints/organization_events_stats.py
  src/sentry/api/endpoints/organization_events_timeseries.py
  src/sentry/snuba/ourlogs.py
  src/sentry/snuba/rpc_dataset_common.py
  src/sentry/snuba/spans_rpc.py
Labels: Scope: Backend

#92738 feat(seer): Add super low automation setting and super high search field
  static/app/types/group.tsx
  static/app/utils/fields/index.ts
  static/app/views/issueDetails/streamline/sidebar/seerNotices.tsx
  static/app/views/issueList/utils/useFetchIssueTags.tsx
  static/app/views/settings/projectSeer/index.tsx
  static/gsApp/views/seerAutomation/index.spec.tsx
Labels: Scope: Frontend

#92668 chore(gitlab): try to make gitlab not decode /oauth/token response
  src/sentry/identity/oauth2.py
Labels: Scope: Backend

#92778 fix(ourlogs): Add ourlogs to whitelisted datasets for top n
  src/sentry/api/endpoints/organization_events_stats.py
Labels: Scope: Backend

#92759 fix(settings): Do not double-save key rate limits field
  static/app/views/settings/project/projectKeys/details/keyRateLimitsForm.tsx
Labels: Scope: Frontend

#92768 ref: make is_active_supseruser preserve Request type
  src/sentry/auth/superuser.py
  src/sentry/types/request.py
Labels: Scope: Backend

#92775 fix(nav): Settings nav preview should always show org settings
  static/app/views/nav/secondary/sections/settings/settingsSecondaryNav.tsx
Labels: Scope: Frontend

#92772 feat(aci): Display detector assignee/owner
  static/app/views/detectors/detail.spec.tsx
  static/app/views/detectors/detail.tsx
Labels: Scope: Frontend

#92781 feat(aci): set up automation details conditions panel
  static/app/views/automations/components/actionFilters/ageComparison.tsx
  static/app/views/automations/components/actionFilters/eventAttribute.tsx
  static/app/views/automations/components/actionFilters/issuePriority.tsx
  static/app/views/automations/components/actionNodes.tsx
  static/app/views/automations/components/conditionsPanel.tsx
  static/app/views/automations/components/dataConditionNodes.tsx
  static/app/views/automations/detail.tsx
Labels: Scope: Frontend

#92786 feat(aci): Add connected automations to detector details
  static/app/views/automations/hooks/index.tsx
  static/app/views/detectors/components/connectedAutomationList.tsx
  static/app/views/detectors/detail.tsx
Labels: Scope: Frontend

#92311 fix(ui): make sure button labels can overflow
  static/app/components/core/button/index.tsx
  static/app/components/core/button/linkButton.tsx
Labels: Scope: Frontend

#92805 feat(tempest): Add endpoint for Tempest outbound IPs
  src/sentry/api/urls.py
  src/sentry/options/defaults.py
  src/sentry/tempest/endpoints/tempest_ips.py
  tests/sentry/tempest/endpoints/test_tempest_ips.py
Labels: Scope: Backend

#92807 feat(agents-monitoring): add other series
  static/app/views/insights/agentMonitoring/components/llmGenerationsWidget.tsx
  static/app/views/insights/agentMonitoring/components/tokenUsageWidget.tsx
  static/app/views/insights/agentMonitoring/components/toolUsageWidget.tsx
Labels: Scope: Frontend

#92812 fix(issue-onboarding): Fix disabled button without disable styles
  static/app/components/core/button/linkButton.tsx
Labels: Scope: Frontend

#92815 feat(agent-insights): Highlight tool args and result
  static/app/views/insights/agentMonitoring/utils/highlightedSpanAttributes.tsx
Labels: Scope: Frontend

#92774 typing: Stronger typing for ProjectRepoPathParsingEndpoint
  pyproject.toml
  src/sentry/api/endpoints/project_repo_path_parsing.py
  tests/sentry/api/endpoints/test_project_repo_path_parsing.py
Labels: Scope: Backend

#92816 fix(agent-insights): Check for all ai descriptions
  static/app/views/insights/agentMonitoring/utils/query.tsx
Labels: Scope: Frontend

#92803 ref(settings): Rename auth tokens and merge nav sections
  static/app/components/sidebar/sidebarDropdown/index.tsx
  static/app/gettingStartedDocs/java/java.tsx
  static/app/gettingStartedDocs/java/log4j2.tsx
  static/app/gettingStartedDocs/java/logback.tsx
  static/app/gettingStartedDocs/java/spring-boot.tsx
  static/app/gettingStartedDocs/java/spring.tsx
  static/app/gettingStartedDocs/kotlin/kotlin.tsx
  static/app/routes.tsx
  static/app/types/hooks.tsx
  static/app/views/settings/account/apiNewToken.tsx
  static/app/views/settings/account/apiTokenDetails.tsx
  static/app/views/settings/account/apiTokens.tsx
  static/app/views/settings/account/navigationConfiguration.tsx
  static/app/views/settings/organization/navigationConfiguration.tsx
  static/app/views/settings/organization/userOrgNavigationConfiguration.tsx
  static/app/views/settings/organizationApiKeys/organizationApiKeysList.tsx
  static/app/views/settings/organizationAuthTokens/authTokenDetails.tsx
  static/app/views/settings/organizationAuthTokens/index.spec.tsx
  static/app/views/settings/organizationAuthTokens/index.tsx
  static/app/views/settings/organizationAuthTokens/newAuthToken.spec.tsx
  static/app/views/settings/organizationAuthTokens/newAuthToken.tsx
  static/app/views/settings/settingsIndex.tsx
Labels: Scope: Frontend

#92479 feat(dashboards-eap): Add comparison script for dashboards -> EAP migration
  src/sentry/discover/compare_tables.py
  tests/sentry/discover/test_compare_tables.py
Labels: Scope: Backend

#92833 fix(agents-insights): empty token usage widget
  static/app/views/insights/agentMonitoring/components/tokenUsageWidget.tsx
Labels: Scope: Frontend

#92832 style(sp): Spelling in processing_errors.errors
  src/sentry/monitors/processing_errors/errors.py
Labels: Scope: Backend

#92834 ref(crons): Include item_ts and start_time in debug log
  src/sentry/monitors/consumers/monitor_consumer.py
Labels: Scope: Backend

#92836 fix(ourlogs): Fix regular table chevron movement
  static/app/views/explore/logs/tables/logsInfiniteTable.tsx
  static/app/views/explore/logs/tables/logsTableRow.tsx
Labels: Scope: Frontend

#92823 fix(insights): fixes perf score function calculating incorrectly when there is a groupby
  src/sentry/search/eap/spans/formulas.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#92826 ref(ui): cleanup featureBadge
  static/app/components/core/badge/featureBadge.stories.tsx
  static/app/components/core/badge/featureBadge.tsx
  static/app/components/core/badge/index.chonk.tsx
  static/app/views/codecov/coverage/commits/commitWrapper.tsx
  static/app/views/codecov/coverage/coverageWrapper.tsx
  static/app/views/codecov/coverage/pulls/pullWrapper.tsx
  static/app/views/codecov/tests/testsWrapper.tsx
  static/app/views/codecov/tokens/tokensWrapper.tsx
Labels: Scope: Frontend

#92840 fix(ourlogs): Fix colspan count
  static/app/views/explore/logs/tables/logsTableRow.tsx
Labels: Scope: Frontend

#92842 fix(crons): Specify checkinId on Go quickstart
  static/app/views/insights/crons/components/quickStartEntries.tsx
Labels: Scope: Frontend, Trigger: getsentry tests

#92798 fix(search): Fix errant selection after cmd+a and typing
  static/app/components/searchQueryBuilder/selectionKeyHandler.tsx
Labels: Scope: Frontend

#92841 ref: Project.slug is non-nullable
  migrations_lockfile.txt
  src/sentry/api/endpoints/organization_projects_experiment.py
  src/sentry/migrations/0919_project_slug_non_null.py
  src/sentry/models/project.py
  tests/sentry/ingest/test_transaction_clusterer.py
Labels: Scope: Backend

#92831 ref(js): Use title prop for event nav buttons
  static/app/views/issueDetails/streamline/issueDetailsEventNavigation.tsx
Labels: Scope: Frontend

#92844 ref(crons): Use pink400 to match perf onboarding waiter
  static/app/views/insights/crons/components/onboarding.tsx
Labels: Scope: Frontend

#92703 feat(errors) - Handle client sample rate on error events
  src/sentry/event_manager.py
  src/sentry/options/defaults.py
  tests/sentry/event_manager/test_event_manager.py
Labels: Scope: Backend

#92799 test(ui): Remove deprecated router mocks from createAlertButton
  static/app/components/createAlertButton.spec.tsx
Labels: Scope: Frontend

#92588 ref(aci): factor out processing WorkflowActionGroupStatus from updating them
  src/sentry/workflow_engine/processors/action.py
  tests/sentry/workflow_engine/processors/test_action.py
Labels: Scope: Backend

#92850 ref: improve types of snuba.sessions_v2
  src/sentry/snuba/sessions_v2.py
Labels: Scope: Backend

#92851 test(js): Render notice if route does not match
  static/app/views/issueList/overview.spec.tsx
  tests/js/sentry-test/reactTestingLibrary.tsx
Labels: Scope: Frontend

#92522 ref(aci): dual write workflow group action status
  src/sentry/workflow_engine/processors/action.py
  src/sentry/workflow_engine/processors/delayed_workflow.py
  src/sentry/workflow_engine/processors/workflow.py
  tests/sentry/workflow_engine/processors/test_action.py
  tests/sentry/workflow_engine/processors/test_workflow.py
Labels: Scope: Backend

#92570 feat(search-bar): Add string filter wildcard operators
  static/app/components/searchQueryBuilder/formattedQuery.tsx
  static/app/components/searchQueryBuilder/hooks/useQueryBuilderState.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filterOperator.tsx
  static/app/components/searchQueryBuilder/tokens/filter/parsers/string/parser.spec.tsx
  static/app/components/searchQueryBuilder/tokens/filter/utils.tsx
  static/app/components/searchQueryBuilder/types.tsx
  static/app/components/searchSyntax/parser.tsx
Labels: Scope: Frontend

#92858 ref(js): Remove custom styling on join request tag
  static/app/views/settings/organizationMembers/inviteRequestRow.tsx
Labels: Scope: Frontend

#92854 ref(span-buffer): Crash consumer if flusher is hanging
  src/sentry/options/defaults.py
  src/sentry/spans/consumers/process/flusher.py
  tests/sentry/spans/consumers/process/test_consumer.py
Labels: Scope: Backend

#92508 ref(releases): Bulk read and update on the happy path
  src/sentry/options/defaults.py
  src/sentry/release_health/tasks.py
  tests/sentry/release_health/test_tasks.py
Labels: Scope: Backend

#92820 ref: simplify tabs interface
  static/app/components/core/tabs/index.stories.tsx
  static/app/components/core/tabs/item.tsx
  static/app/components/core/tabs/tabList.tsx
  static/app/components/core/tabs/tabPanels.tsx
Labels: Scope: Frontend

#92692 feat(search): Make `first_release` autocomplete
  static/app/views/issueList/searchBar.tsx
  static/app/views/issueList/utils/useFetchIssueTags.tsx
Labels: Scope: Frontend

#92605 docs(replays): Add incident report for INC-1184
  src/sentry/replays/_case_studies/INC_1184_consumer_backlog_from_increased_threads/report.py
  src/sentry/replays/_case_studies/README.md
Labels: Scope: Backend

#92792 js: yarn v1 to pnpm (rollout stage 3 of 3, delete yarn)
  .github/workflows/acceptance.yml
  .github/workflows/backend.yml
  .github/workflows/frontend.yml
  .github/workflows/jest-balance.yml
  .github/workflows/openapi-diff.yml
  .github/workflows/openapi.yml
  .github/workflows/pre-commit.yml
  .github/workflows/self-hosted.yml
  .github/workflows/sync-labels.yml
  devenv/sync.py
  package.json
  yarn.lock
Labels: Scope: Frontend, Scope: Backend

#92863 feat(aci): add remaining conditions to automation details conditions panel
  static/app/views/automations/components/actionFilters/assignedTo.tsx
  static/app/views/automations/components/actionFilters/eventFrequency.tsx
  static/app/views/automations/components/actionFilters/eventUniqueUserFrequency.tsx
  static/app/views/automations/components/actionFilters/issueOccurrences.tsx
  static/app/views/automations/components/actionFilters/latestAdoptedRelease.tsx
  static/app/views/automations/components/actionFilters/latestRelease.tsx
  static/app/views/automations/components/actionFilters/level.tsx
  static/app/views/automations/components/actionFilters/percentSessions.tsx
  static/app/views/automations/components/actionFilters/subfiltersList.tsx
  static/app/views/automations/components/actionFilters/taggedEvent.tsx
  static/app/views/automations/components/conditionsPanel.tsx
  static/app/views/automations/components/dataConditionNodes.tsx
Labels: Scope: Frontend

#92494 perf(aci): Load slow conditions via standard caching method
  src/sentry/workflow_engine/models/data_condition_group.py
  src/sentry/workflow_engine/processors/data_condition_group.py
  src/sentry/workflow_engine/processors/delayed_workflow.py
  tests/sentry/workflow_engine/processors/test_data_condition_group.py
Labels: Scope: Backend

#92883 fix(nav): Add default gap on the secondary nav item component
  static/app/views/nav/secondary/secondary.tsx
  static/app/views/nav/secondary/sections/explore/exploreSavedQueryNavItems.tsx
  static/app/views/nav/secondary/sections/insights/insightsSecondaryNav.tsx
  static/app/views/nav/secondary/sections/issues/issueViews/issueViewItem.tsx
Labels: Scope: Frontend

#92869 fix(ourlogs): More aggressive row loading and fix back to top hover
  static/app/views/explore/logs/constants.tsx
  static/app/views/explore/logs/styles.tsx
  static/app/views/explore/logs/tables/logsInfiniteTable.tsx
  static/app/views/explore/logs/useLogsQuery.tsx
  static/app/views/explore/logs/utils.tsx
Labels: Scope: Frontend

#92864 ref(span-buffer): Crash consumer if flusher is hanging (reapply)
  src/sentry/options/defaults.py
  src/sentry/spans/consumers/process/flusher.py
  tests/sentry/spans/consumers/process/test_consumer.py
Labels: Scope: Backend

#92894 dev: reformat pnpm lockfile
  package.json
  pnpm-lock.yaml
Labels: Scope: Frontend

#92900 fix(ACI): Increment metric once per rule
  src/sentry/incidents/subscription_processor.py
  tests/sentry/incidents/test_subscription_processor.py
Labels: Scope: Backend

#92899 feat(emerge-size): add FF to gate usage of new endpoint to just test orgs
  src/sentry/features/temporary.py
  src/sentry/preprod/api/endpoints/organization_preprod_artifact_assemble.py
  tests/sentry/preprod/api/endpoints/test_organization_preprod_artifact_assemble.py
Labels: Scope: Backend

#92898 feat(issue-views): Re-revised migration for saved searches conversion
  migrations_lockfile.txt
  src/sentry/migrations/0921_convert_org_saved_searches_to_views_rerevised.py
  tests/sentry/migrations/test_0921_convert_org_saved_searches_to_views_rerevised.py
Labels: Scope: Backend

#92855 ref(aci): Switch open period deletion to use bulk_delete_objects
  src/sentry/migrations/0916_delete_open_period_rows.py
Labels: Scope: Backend

#92813 fix(onboarding): Replace trace examples to fix indentation issues
  static/app/gettingStartedDocs/javascript/javascript.tsx
  static/app/gettingStartedDocs/javascript/nextjs.tsx
  static/app/gettingStartedDocs/javascript/react.tsx
Labels: Scope: Frontend

#92917 ref(platform-insights): Table refactoring
  static/app/views/insights/agentMonitoring/components/common.tsx
  static/app/views/insights/agentMonitoring/components/headSortCell.tsx
  static/app/views/insights/agentMonitoring/components/modelsTable.tsx
  static/app/views/insights/agentMonitoring/components/toolsTable.tsx
  static/app/views/insights/agentMonitoring/components/tracesTable.tsx
  static/app/views/insights/pages/platform/shared/pagesTable.tsx
  static/app/views/insights/pages/platform/shared/pathsTable.tsx
  static/app/views/insights/pages/platform/shared/table/DurationCell.tsx
  static/app/views/insights/pages/platform/shared/table/ErrorRateCell.tsx
  static/app/views/insights/pages/platform/shared/table/NumberCell.tsx
  static/app/views/insights/pages/platform/shared/table/ThresholdCell.tsx
  static/app/views/insights/pages/platform/shared/table/TransactionCell.tsx
  static/app/views/insights/pages/platform/shared/table/UserCell.tsx
  static/app/views/insights/pages/platform/shared/table/index.tsx
  static/app/views/insights/pages/platform/shared/table/useTableData.tsx
Labels: Scope: Frontend

#92717 ref(project-creation): Improve types
  static/app/components/modals/projectCreationModal.tsx
  static/app/views/projectInstall/createProject.tsx
  static/app/views/projectInstall/issueAlertNotificationOptions.tsx
  static/app/views/projectInstall/issueAlertOptions.tsx
Labels: Scope: Frontend

#92920 ref(spans): Polish buffer flush restarts and streamline metrics
  src/sentry/spans/buffer.py
  src/sentry/spans/consumers/process/flusher.py
Labels: Scope: Backend

#92921 feat(span-buffer): Add killswitch for dropping spans
  src/sentry/killswitches.py
  src/sentry/options/defaults.py
  src/sentry/spans/consumers/process/factory.py
Labels: Scope: Backend

#92923 feat(getting-started-docs): Make source maps section collapsible and optional
  static/app/components/onboarding/gettingStartedDoc/utils/index.tsx
  static/app/gettingStartedDocs/javascript/angular.spec.tsx
  static/app/gettingStartedDocs/javascript/ember.spec.tsx
  static/app/gettingStartedDocs/javascript/gatsby.spec.tsx
  static/app/gettingStartedDocs/javascript/javascript.spec.tsx
  static/app/gettingStartedDocs/javascript/react.spec.tsx
  static/app/gettingStartedDocs/javascript/solid.spec.tsx
  static/app/gettingStartedDocs/javascript/solidstart.tsx
  static/app/gettingStartedDocs/javascript/svelte.spec.tsx
  static/app/gettingStartedDocs/javascript/vue.spec.tsx
  static/app/gettingStartedDocs/node/awslambda.spec.tsx
  static/app/gettingStartedDocs/node/awslambda.tsx
  static/app/gettingStartedDocs/node/azurefunctions.spec.tsx
  static/app/gettingStartedDocs/node/cloudflare-pages.spec.tsx
  static/app/gettingStartedDocs/node/cloudflare-workers.spec.tsx
  static/app/gettingStartedDocs/node/connect.spec.tsx
  static/app/gettingStartedDocs/node/express.spec.tsx
  static/app/gettingStartedDocs/node/fastify.spec.tsx
  static/app/gettingStartedDocs/node/gcpfunctions.spec.tsx
  static/app/gettingStartedDocs/node/hapi.spec.tsx
  static/app/gettingStartedDocs/node/koa.spec.tsx
  static/app/gettingStartedDocs/node/nestjs.spec.tsx
  static/app/gettingStartedDocs/node/node.spec.tsx
Labels: Scope: Frontend

#92927 fix(spans): After flusher hangs, debounce restarts
  src/sentry/spans/consumers/process/flusher.py
Labels: Scope: Backend

#92929 chore(spans): Emit warnings instead of errors on large segments
  src/sentry/spans/buffer.py
Labels: Scope: Backend

#91330 [BUGFIX] Update celery version to fix error with Sentry Worker reconnection to MQBroker
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend, Trigger: getsentry tests

#92829 feat(derived_code_mappings): Support single file
  src/sentry/issues/auto_source_code_config/code_mapping.py
  src/sentry/issues/auto_source_code_config/frame_info.py
  tests/sentry/issues/auto_source_code_config/test_frame_info.py
  tests/sentry/issues/auto_source_code_config/test_process_event.py
Labels: Scope: Backend

#92893 feat(insights): add links to explore/alerts from screen load device distribution charts
  static/app/views/dashboards/widgets/widget/widget.tsx
  static/app/views/insights/common/components/chart.tsx
  static/app/views/insights/common/components/insightsChartContainer.tsx
  static/app/views/insights/common/components/insightsTimeSeriesWidget.tsx
  static/app/views/insights/common/components/miniChartPanel.tsx
  static/app/views/insights/mobile/appStarts/components/charts/deviceClassBreakdownBarChart.tsx
  static/app/views/insights/mobile/screenload/components/charts/screenBarChart.tsx
  static/app/views/insights/mobile/screenload/components/charts/screenCharts.tsx
Labels: Scope: Frontend

#92888 ref(js): Convert removeProject to async
  static/app/actionCreators/projects.tsx
Labels: Scope: Frontend

#92879 feat(trace-eap-waterfall): Standalone spans detail panel loads indefnitely
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/index.tsx
Labels: Scope: Frontend

#92876 feat(nav): Tighten secondary nav animations slightly
  static/app/views/nav/constants.tsx
  static/app/views/nav/secondary/secondarySidebar.tsx
Labels: Scope: Frontend
