Repository getsentry/sentry, pull requests merged in 2025-03, with the labels that each got.

#86153 feat(view-sharing): Double write position to new table in PUT endpoint
  src/sentry/issues/endpoints/organization_group_search_views.py
  tests/sentry/issues/endpoints/test_organization_group_search_views.py
Labels: Scope: Backend

#86149 feat(autofix): Pass data down on update endpoint
  src/sentry/api/endpoints/group_autofix_update.py
Labels: Scope: Backend

#86082 chore(uptime): Drop `migrated` column from `UptimeSubscription`
  migrations_lockfile.txt
  src/sentry/uptime/migrations/0028_drop_migrated_column.py
Labels: Scope: Backend

#86150 feat(autofix): Surface error on pr creation
  static/app/components/events/autofix/autofixChanges.tsx
  static/app/components/events/autofix/types.ts
Labels: Scope: Frontend

#86162 fix(tests): Attempt to fix flaky user creation again
  src/sentry/testutils/fixtures.py
Labels: Scope: Backend

#85829 feat(assemble): Add ownership check for file blobs
  src/sentry/models/files/abstractfileblob.py
  src/sentry/tasks/assemble.py
  tests/sentry/api/endpoints/test_dif_assemble.py
  tests/sentry/api/endpoints/test_organization_release_assemble.py
  tests/sentry/api/endpoints/test_project_artifact_lookup.py
  tests/sentry/debug_files/test_artifact_bundles.py
  tests/sentry/tasks/test_assemble.py
Labels: Scope: Backend

#85926 ref(quick-start): Update mark onboarding as complete logic
  src/sentry/onboarding_tasks/backends/organization_onboarding_task.py
  src/sentry/receivers/onboarding.py
  tests/sentry/receivers/test_onboarding.py
Labels: Scope: Backend

#86176 fix(dynamic-sampling): Array length being rendered
  static/app/views/settings/dynamicSampling/projectsTable.tsx
Labels: Scope: Frontend

#86170 fix(quick-start): Fix sidebar opening after creating a new org and project
  static/app/components/nav/primary/onboarding.tsx
  static/app/components/sidebar/onboardingStatus.tsx
  static/app/views/onboarding/useOnboardingSidebar.tsx
Labels: Scope: Frontend

#86181 feat(dynamic-sampling): Improve empty breakdown state
  static/app/views/settings/dynamicSampling/samplingBreakdown.tsx
Labels: Scope: Frontend

#86180 fix(sdk): Sample /api/0/auth/validate/ at 0%
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#86020 feat(sourcemaps-debugger-modal): Display specific docs links
  static/app/components/events/interfaces/crashContent/exception/content.tsx
  static/app/components/events/interfaces/crashContent/exception/useSourceMapDebuggerData.tsx
  static/app/components/events/interfaces/crashContent/index.spec.tsx
  static/app/components/events/interfaces/sourceMapsDebuggerModal.spec.tsx
  static/app/components/events/interfaces/sourceMapsDebuggerModal.tsx
  static/app/views/sharedGroupDetails/index.spec.tsx
Labels: Scope: Frontend

#86182 feat(assemble): Improve error message for assemble
  src/sentry/tasks/assemble.py
Labels: Scope: Backend

#86185 fix(onboarding): remove superfluous whitespace in flask onboarding
  static/app/gettingStartedDocs/python/flask.tsx
Labels: Scope: Frontend

#86184 ref(quick-start): Add acceptance test to make sure sidebar does not open automatically
  tests/acceptance/test_quick_start.py
Labels: Scope: Backend

#86148 ref: fix types for organization_member.index
  pyproject.toml
  src/sentry/api/endpoints/organization_member/index.py
  src/sentry/ratelimits/utils.py
  tests/sentry/utils/test_ratelimits.py
Labels: Scope: Backend

#86142 ref: fix types for integrations.jira.client
  pyproject.toml
  src/sentry/integrations/jira/client.py
Labels: Scope: Backend

#86141 ref: fix typing for sentry.snuba.errors
  pyproject.toml
  src/sentry/snuba/errors.py
Labels: Scope: Backend

#86190 ref(debugger-modal): Hide debug ids tab if sdk does not support it
  static/app/components/events/interfaces/sourceMapsDebuggerModal.spec.tsx
  static/app/components/events/interfaces/sourceMapsDebuggerModal.tsx
Labels: Scope: Frontend

#86145 ref: fix typing for organization_member.requests.invite.details
  pyproject.toml
  src/sentry/api/bases/organizationmember.py
  src/sentry/api/endpoints/organization_member/details.py
  src/sentry/api/endpoints/organization_member/requests/invite/details.py
  tests/sentry/api/endpoints/test_organization_invite_request_details.py
Labels: Scope: Backend

#86168 stories: sort children of categories
  static/app/views/stories/storyTree.tsx
Labels: Scope: Frontend

#86171 fix(flags): Add statsig to webhook provider form options
  static/app/views/settings/featureFlags/newProviderForm.tsx
Labels: Scope: Frontend

#86144 feat(dashboards-eap): Convert to new confidence sample counts
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetBuilder/utils/getTopEvents.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/confidenceWarning.tsx
  static/app/views/dashboards/widgetCard/genericWidgetQueries.tsx
  static/app/views/dashboards/widgetCard/index.tsx
  static/app/views/dashboards/widgetCard/spansWidgetQueries.tsx
  static/app/views/dashboards/widgetCard/widgetCardChartContainer.tsx
  static/app/views/dashboards/widgetCard/widgetCardDataLoader.tsx
  static/app/views/dashboards/widgetViewer/widgetViewerContext.tsx
  static/app/views/insights/common/queries/useSortedTimeSeries.tsx
Labels: Scope: Frontend

#86197 ref(spans): Introduce an option to disable perf issue detection
  src/sentry/options/defaults.py
  src/sentry/spans/consumers/process_segments/message.py
  tests/sentry/spans/consumers/process_segments/test_message.py
Labels: Scope: Backend

#86114 fix(aci): force negative value event frequency conditions to 0 in migration
  src/sentry/workflow_engine/handlers/condition/event_frequency_handlers.py
  src/sentry/workflow_engine/migration_helpers/issue_alert_conditions.py
  tests/sentry/workflow_engine/handlers/condition/test_event_frequency_handlers.py
Labels: Scope: Backend

#86119 fix(aci): force age comparison filter values to >= 0
  src/sentry/workflow_engine/migration_helpers/issue_alert_conditions.py
  tests/sentry/workflow_engine/handlers/condition/test_age_comparison_handler.py
Labels: Scope: Backend

#85691 chore(issue-views): delete page filters flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#86155 fix(api): better error message return to the client
  src/sentry/api/handlers.py
  tests/sentry/api/test_handlers.py
Labels: Scope: Backend

#86133 feat(replay): Add a tooltip to the Replay List page Error column
  static/app/views/replays/replayTable/headerCell.tsx
Labels: Scope: Frontend

#86204 fix(issue-views): Fix views jumping after scroll and page navigation
  static/app/components/nav/issueViews/issueViewNavItemContent.tsx
Labels: Scope: Frontend

#86131 feat(issues-stream): Mark cached issue stream group as seen when viewed
  static/app/stores/IssueListCacheStore.tsx
  static/app/views/issueDetails/utils.tsx
Labels: Scope: Frontend

#86128 analytics(performance): Adding analytics for quota exceeded banner
  static/app/types/hooks.tsx
  static/app/views/explore/spans/spansTab.tsx
  static/app/views/performance/quotaExceededAlert.tsx
  static/gsApp/components/performance/quotaExceededAlert.spec.tsx
  static/gsApp/components/performance/quotaExceededAlert.tsx
  static/gsApp/registerHooks.tsx
  static/gsApp/utils/trackGetsentryAnalytics.tsx
Labels: Scope: Frontend

#86156 feat(crons): Make per-monitor rate limit configurable
  src/sentry/monitors/rate_limit.py
  src/sentry/options/defaults.py
  tests/sentry/monitors/test_rate_limit.py
Labels: Scope: Backend

#86137 feat(issue-stream): Move first/last seen columns to left of chart
  static/app/components/stream/group.tsx
  static/app/views/issueList/actions/headers.tsx
Labels: Scope: Frontend

#86086 fix(uptime): Enforce domain limits everywhere
  migrations_lockfile.txt
  src/sentry/uptime/detectors/ranking.py
  src/sentry/uptime/detectors/tasks.py
  src/sentry/uptime/endpoints/validators.py
  src/sentry/uptime/migrations/0029_uptime_subscription_index_domain_cols.py
  src/sentry/uptime/models.py
  src/sentry/uptime/subscriptions/subscriptions.py
  tests/sentry/uptime/detectors/test_ranking.py
  tests/sentry/uptime/endpoints/test_project_uptime_alert_details.py
Labels: Scope: Backend

#86208 ref: match signature of has_permission / has_object_permission
  src/sentry/api/permissions.py
  src/sentry/integrations/api/bases/doc_integrations.py
  src/sentry/users/api/bases/user.py
  tests/sentry/api/bases/test_organization.py
  tests/sentry/api/bases/test_project.py
  tests/sentry/api/bases/test_team.py
  tests/sentry/api/test_permissions.py
  tests/sentry/sentry_apps/api/bases/test_sentryapps.py
  tests/sentry/users/api/bases/test_user.py
Labels: Scope: Backend

#85900 feat(tours): Introduce a Tours API via hooks/context
  static/app/components/tours/components.spec.tsx
  static/app/components/tours/components.tsx
  static/app/components/tours/testUtils.tsx
  static/app/components/tours/tour.stories.tsx
  static/app/components/tours/tourContext.spec.tsx
  static/app/components/tours/tourContext.tsx
  static/app/utils/theme/theme.tsx
  static/app/views/issueDetails/issueDetailsTour.tsx
Labels: Scope: Frontend

#86205 feat(dashboards): Add documentation for widget state management
  static/app/views/dashboards/widgets/widget/widget.stories.tsx
Labels: Scope: Frontend

#86213 fix(dynamic sampling): Correct spans nomenclature based on DS
  static/gsApp/views/subscriptionPage/usageAlert.tsx
Labels: Scope: Frontend

#86216 chore(gen-ai): Rename Sentry AI to Seer
  static/app/components/events/autofix/autofixRootCause.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsHubDrawer.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsHubDrawer.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsSection.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsSection.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsSectionCtaButton.tsx
Labels: Scope: Frontend

#86070 ref(flags): split FF settings into eval/change tracking
  static/app/components/events/featureFlags/featureFlagOnboardingLayout.tsx
  static/app/components/events/featureFlags/featureFlagOnboardingSidebar.tsx
  static/app/components/events/featureFlags/onboardingAdditionalInfo.tsx
  static/app/components/events/featureFlags/onboardingIntegrationSection.tsx
  static/app/components/events/featureFlags/useFeatureFlagOnboarding.tsx
  static/app/routes.tsx
  static/app/views/settings/featureFlags/changeTracking/index.spec.tsx
  static/app/views/settings/featureFlags/changeTracking/index.tsx
  static/app/views/settings/featureFlags/changeTracking/newProviderForm.spec.tsx
  static/app/views/settings/featureFlags/changeTracking/newProviderForm.tsx
  static/app/views/settings/featureFlags/changeTracking/newSecretHandler.spec.tsx
  static/app/views/settings/featureFlags/changeTracking/newSecretHandler.tsx
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsAuditLogTable.tsx
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsNewSecret.spec.tsx
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsNewSecret.tsx
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsProviderRow.spec.tsx
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsProviderRow.tsx
  static/app/views/settings/featureFlags/index.tsx
  static/app/views/settings/organization/navigationConfiguration.tsx
  static/app/views/settings/organization/userOrgNavigationConfiguration.tsx
  tests/js/fixtures/secret.ts
Labels: Scope: Frontend

#85483 ref(grouping): Clean up fingerprinting helpers
  src/sentry/grouping/fingerprinting/__init__.py
  src/sentry/grouping/utils.py
Labels: Scope: Backend

#86219 ref(dashboards): Remove usage of `BigNumberWidget` from Dashboards
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/index.tsx
Labels: Scope: Frontend

#86157 feat(view-sharing): Add new endpoint to delete single view
  src/sentry/api/urls.py
  src/sentry/issues/endpoints/__init__.py
  src/sentry/issues/endpoints/organization_group_search_view_details.py
  tests/sentry/issues/endpoints/test_organization_group_search_view_details.py
Labels: Scope: Backend

#86050 fix(rpc): Handle wildcard free text search
  src/sentry/api/event_search.py
  src/sentry/search/eap/resolver.py
  tests/snuba/api/endpoints/test_organization_events_ourlogs.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#86104 chore(issue-details): Update All Events copy
  static/app/views/issueDetails/streamline/eventNavigation.tsx
Labels: Scope: Frontend

#85662 feat(insights): add custom function support to EAP
  src/sentry/search/eap/columns.py
  src/sentry/search/eap/constants.py
  src/sentry/search/eap/ourlog_columns.py
  src/sentry/search/eap/resolver.py
  src/sentry/search/eap/span_columns.py
  src/sentry/search/eap/uptime_check_columns.py
  src/sentry/snuba/rpc_dataset_common.py
  src/sentry/snuba/spans_rpc.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#86199 ref(insights): remove performance-landing-page-stats-period flag
  static/app/views/insights/pages/backend/backendOverviewPage.tsx
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
  static/app/views/insights/pages/frontend/frontendOverviewPage.tsx
  static/app/views/performance/content.tsx
  static/app/views/performance/data.tsx
  static/app/views/performance/landing/index.spec.tsx
  static/app/views/performance/vitalDetail/index.tsx
Labels: Scope: Frontend

#86172 fix(issue-summary) Show possible cause loading
  static/app/components/group/groupSummary.spec.tsx
  static/app/components/group/groupSummary.tsx
  static/app/views/issueDetails/streamline/sidebar/solutionsSection.spec.tsx
Labels: Scope: Frontend

#86188 tests(derived_code_mappings): Do not create object in parametrization section
  src/sentry/issues/auto_source_code_config/stacktraces.py
  tests/sentry/issues/auto_source_code_config/test_code_mapping.py
Labels: Scope: Backend

#86116 ref(dashboards): Move unit scaling into `Plottable`
  static/app/views/dashboards/widgets/common/types.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/aggregateTimeSeries.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/area.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/bars.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/line.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/plottable.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/timeSeriesWidgetVisualization.tsx
Labels: Scope: Frontend

#86206 feat(explore): Hide Confidence footer with 100% sample rate
  static/app/views/alerts/rules/metric/ruleForm.tsx
  static/app/views/alerts/rules/metric/triggers/chart/index.tsx
  static/app/views/alerts/rules/metric/utils/determineSeriesConfidence.tsx
  static/app/views/alerts/rules/metric/utils/determineSeriesSampleCount.tsx
  static/app/views/dashboards/widgetCard/spansWidgetQueries.tsx
  static/app/views/explore/charts/index.tsx
  static/app/views/explore/multiQueryMode/queryVisualizations/chart.tsx
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#86129 ref(insights): Replace usage of `<ReleaseSeries>` in `<InsightsTimeSeriesWidget>`
  static/app/utils/queryClient.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/useReleaseStats.tsx
  static/app/views/insights/browser/resources/views/resourcesLandingPage.spec.tsx
  static/app/views/insights/cache/views/cacheLandingPage.spec.tsx
  static/app/views/insights/common/components/insightsTimeSeriesWidget.tsx
  static/app/views/insights/database/views/databaseLandingPage.spec.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.spec.tsx
  static/app/views/insights/http/views/httpDomainSummaryPage.spec.tsx
  static/app/views/insights/http/views/httpLandingPage.spec.tsx
  static/app/views/insights/queues/charts/latencyChart.spec.tsx
  static/app/views/insights/queues/charts/throughputChart.spec.tsx
  static/app/views/insights/queues/views/destinationSummaryPage.spec.tsx
  static/app/views/insights/queues/views/queuesLandingPage.spec.tsx
Labels: Scope: Frontend

#86198 fix(insights): Filter span samples by environment
  static/app/views/insights/common/queries/useSpanSamples.tsx
  static/app/views/insights/http/queries/useSpanSamples.spec.tsx
  static/app/views/insights/http/queries/useSpanSamples.tsx
Labels: Scope: Frontend

#86200 ref(insights): remove performance-landing-page-stats-period flag
  src/sentry/features/temporary.py
Labels: Scope: Backend

#86223 fix(replay): Remove extra border & padding from replay snippets
  static/app/components/events/eventReplay/replayPreviewPlayer.tsx
Labels: Scope: Frontend

#86224 ref(flags): fix audit log table badge style
  static/app/views/settings/featureFlags/changeTracking/organizationFeatureFlagsAuditLogTable.tsx
Labels: Scope: Frontend

#86237 chore(dashboards): Remove chart from Releases drawer
  static/app/components/releases/releasesDrawer.tsx
Labels: Scope: Frontend

#86239 feat(ourlogs): Add alpha js sdk for adding logging
  package.json
  static/app/bootstrap/initializeSdk.tsx
  static/app/components/charts/utils.tsx
Labels: Scope: Frontend

#86161 fix(nav): Show same nav items when user is in org or user settings.
  static/app/views/settings/account/accountSettingsNavigation.tsx
Labels: Scope: Frontend

#86152 fix(billing): update billing details tab
  static/gsApp/views/subscriptionPage/subscriptionHeader.spec.tsx
  static/gsApp/views/subscriptionPage/subscriptionHeader.tsx
Labels: Scope: Frontend

#86227 feat(compare queries): tightened padding, added tooltips, and fixed panel heights
  static/app/views/explore/multiQueryMode/components/miniTable.tsx
  static/app/views/explore/multiQueryMode/content.tsx
  static/app/views/explore/multiQueryMode/queryConstructors/groupBy.tsx
  static/app/views/explore/multiQueryMode/queryConstructors/search.tsx
  static/app/views/explore/multiQueryMode/queryConstructors/sortBy.tsx
  static/app/views/explore/multiQueryMode/queryConstructors/styles.tsx
  static/app/views/explore/multiQueryMode/queryConstructors/visualize.tsx
  static/app/views/explore/multiQueryMode/queryRow.tsx
  static/app/views/explore/multiQueryMode/queryVisualizations/table.tsx
  static/app/views/explore/toolbar/toolbarSaveAs.tsx
Labels: Scope: Frontend

#86158 feat(crons): Improve wording for project field in validator
  src/sentry/monitors/validators.py
Labels: Scope: Backend

#86246 feat(workflow_engine): Add DELETE Workflow Endpoint
  src/sentry/audit_log/register.py
  src/sentry/workflow_engine/endpoints/organization_workflow_details.py
  tests/sentry/workflow_engine/endpoints/test_organization_workflow_details.py
Labels: Scope: Backend

#86264 fix(issue-views): Fix buggy dragging
  static/app/components/nav/issueViews/issueViewNavItemContent.tsx
  static/app/components/nav/issueViews/issueViewNavItems.tsx
Labels: Scope: Frontend

#85614 feat(assemble): Implement new query for finding missing chunk
  src/sentry/debug_files/upload.py
Labels: Scope: Frontend, Scope: Backend

#86273 fix(laravel-insights): fix seconds vs milliseconds in jobs widget
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
Labels: Scope: Frontend

#86269 feat(login): partner sign in banner
  src/sentry/templates/sentry/partial/alerts.html
  src/sentry/web/frontend/auth_login.py
  src/sentry/web/frontend/setup_wizard.py
Labels: Scope: Backend

#86270 fix(demo-mode): remove remaining usages of `IsAuthenticated`
  src/sentry/api/endpoints/email_capture.py
  src/sentry/api/endpoints/system_health.py
  src/sentry/discover/endpoints/discover_homepage_query.py
  src/sentry/integrations/github/installation.py
  src/sentry/relocation/api/endpoints/public_key.py
  src/sentry/users/api/endpoints/authenticator_index.py
Labels: Scope: Backend

#86196 test(derived_code_mappings): Prevent not updating the list of extensions
  src/sentry/integrations/source_code_management/repo_trees.py
  tests/sentry/issues/auto_source_code_config/test_process_event.py
Labels: Scope: Backend

#86090 feat(ui): stories for inputGroup component
  static/app/components/core/input/inputGroup.stories.tsx
Labels: Scope: Frontend

#86192 ref(debugger-modal): Display specific sentry-cli copy for react-native
  static/app/components/events/interfaces/sourceMapsDebuggerModal.tsx
Labels: Scope: Frontend

#86265 radio: move to components/core and add story
  static/app/components/core/radio/index.stories.tsx
  static/app/components/core/radio/index.tsx
  static/app/components/forms/controls/radioGroup.tsx
  static/app/components/forms/fields/segmentedRadioField.tsx
  static/app/components/onboarding/frameworkSuggestionModal.tsx
  static/app/components/radio.tsx
  static/app/components/replays/diff/picker/mutationOption.tsx
  static/app/views/alerts/wizard/radioPanelGroup.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/yAxisStep/yAxisSelector/index.tsx
  static/app/views/dashboards/widgetBuilder/components/visualize/index.tsx
  static/app/views/performance/landing/widgets/components/selectableList.tsx
  static/app/views/performance/transactionSummary/transactionEvents/operationSort.tsx
  static/app/views/performance/transactionSummary/transactionTags/content.tsx
  static/app/views/performance/trends/changedTransactions.tsx
  static/app/views/releases/detail/overview/releaseComparisonChart/releaseComparisonChartRow.tsx
  static/app/views/settings/organizationMembers/inviteMember/orgRoleSelect.tsx
  static/gsApp/views/amCheckout/steps/addPaymentMethod.tsx
  static/gsApp/views/amCheckout/steps/planSelectRow.tsx
  static/gsApp/views/onDemandBudgets/onDemandBudgetEdit.tsx
  static/gsApp/views/subscriptionPage/overviewDisplayModeToggle.tsx
Labels: Scope: Frontend

#86250 fix(crons): Make disable-check-in option FLAG_AUTOMATOR_MODIFIABLE
  src/sentry/options/defaults.py
Labels: Scope: Backend

#86228 ref: fix types for sentry.api.permissions
  pyproject.toml
  src/sentry/api/bases/organization.py
  src/sentry/api/bases/organizationmember.py
  src/sentry/api/bases/project.py
  src/sentry/api/permissions.py
  src/sentry/auth/access.py
  src/sentry/users/api/bases/user.py
  tests/sentry/api/bases/test_organization.py
  tests/sentry/api/test_permissions.py
Labels: Scope: Backend

#86214 checkbox: move inside components/core
  static/app/components/checkbox.spec.tsx
  static/app/components/checkbox.tsx
  static/app/components/compactSelect/gridList/option.tsx
  static/app/components/compactSelect/listBox/option.tsx
  static/app/components/core/checkbox/index.spec.tsx
  static/app/components/core/checkbox/index.stories.tsx
  static/app/components/core/checkbox/index.tsx
  static/app/components/deprecatedSmartSearchBar/searchBarDatePicker.tsx
  static/app/components/feedback/list/feedbackListHeader.tsx
  static/app/components/feedback/list/feedbackListItem.tsx
  static/app/components/forms/controls/multipleCheckbox.tsx
  static/app/components/forms/fields/checkboxField.tsx
  static/app/components/modals/bulkEditMonitorsModal.tsx
  static/app/components/modals/inviteMissingMembersModal/index.tsx
  static/app/components/onboarding/productSelection.tsx
  static/app/components/organizations/hybridFilter.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/differentialFlamegraphDrawer.tsx
  static/app/components/profiling/flamegraph/flamegraphDrawer/flamegraphDrawer.tsx
  static/app/components/searchQueryBuilder/tokens/filter/specificDatePicker.tsx
  static/app/components/searchQueryBuilder/tokens/filter/valueCombobox.tsx
  static/app/components/sidebar/onboardingStep.tsx
  static/app/components/stream/group.tsx
  static/app/components/timeRangeSelector/dateRange.tsx
  static/app/components/workflowEngine/useBulkActions.tsx
  static/app/views/alerts/rules/issue/index.tsx
  static/app/views/automations/components/automationListRow.tsx
  static/app/views/detectors/components/detectorListRow.tsx
  static/app/views/issueDetails/actions/shareModal.tsx
  static/app/views/issueDetails/groupMerged/mergedItem.tsx
  static/app/views/issueDetails/groupSimilarIssues/similarStackTrace/item.tsx
  static/app/views/issueList/actions/index.tsx
  static/app/views/settings/account/accountClose.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationDashboard/requestLog.tsx
  static/app/views/settings/organizationDeveloperSettings/subscriptionBox.tsx
  static/app/views/settings/projectDebugFiles/index.tsx
Labels: Scope: Frontend

#86281 feat(ourlogs): Add more examples of using log sdk
  static/app/views/explore/hooks/useAnalytics.tsx
Labels: Scope: Frontend

#86175 feat(project): ProjectOverview endpoint
  src/sentry/api/endpoints/project_overview.py
  src/sentry/api/urls.py
  src/sentry/apidocs/examples/project_examples.py
  tests/sentry/api/endpoints/test_project_overview.py
Labels: Scope: Backend

#86232 ref(search): improve confusing `span.action` tooltip
  static/app/utils/fields/index.ts
Labels: Scope: Frontend

#86233 feat(dashboards-eap): Extract top events count from response
  static/app/views/dashboards/widgetBuilder/utils/getTopEvents.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/spansWidgetQueries.tsx
Labels: Scope: Frontend

#86284 feat(aws-lambda): Add Node 20.x, 22.x, and Python 3.12, 3.13 runtime support
  src/sentry/integrations/aws_lambda/utils.py
Labels: Scope: Backend

#86254 ref(seer grouping): Tweak seer grouphash handling
  src/sentry/grouping/ingest/seer.py
  tests/sentry/grouping/ingest/test_seer.py
Labels: Scope: Backend

#86202 ref(dashboards): Remove usage of `BigNumberWidget` from Project Details views
  static/app/views/projectDetail/projectScoreCards/projectAnrScoreCard.tsx
  static/app/views/projectDetail/projectScoreCards/projectApdexScoreCard.tsx
  static/app/views/projectDetail/projectScoreCards/projectStabilityScoreCard.tsx
  static/app/views/projectDetail/projectScoreCards/projectVelocityScoreCard.tsx
Labels: Scope: Frontend

#86201 ref(spans): Add an ingest-spans topic for the spans pipeline
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/conf/server.py
  src/sentry/conf/types/kafka_definition.py
  src/sentry/consumers/__init__.py
  src/sentry/spans/consumers/process/factory.py
  src/sentry/spans/consumers/process_segments/factory.py
  src/sentry/spans/consumers/process_segments/message.py
  tests/sentry/spans/consumers/process/test_factory.py
  tests/sentry/spans/consumers/process_segments/test_factory.py
  tests/sentry/spans/consumers/process_segments/test_message.py
Labels: Scope: Backend

#86236 ref(dashboards): Simplify `Plottable` types and inheritance
  static/app/views/dashboards/widgets/common/types.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/aggregateTimeSeries.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/area.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/bars.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/continuousTimeSeries.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/line.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/plottable.tsx
Labels: Scope: Frontend

#86287 switch: move to components/core
  static/app/components/core/switch/index.stories.tsx
  static/app/components/core/switch/index.tsx
  static/app/components/devtoolbar/components/featureFlags/customOverride.tsx
  static/app/components/devtoolbar/components/featureFlags/featureFlagItem.tsx
  static/app/components/feedback/feedbackOnboarding/feedbackConfigToggle.tsx
  static/app/components/forms/fields/booleanField.tsx
  static/app/components/profiling/flamegraph/deprecatedAggregateFlamegraph.tsx
  static/app/components/replaysOnboarding/replayConfigToggle.tsx
  static/app/utils/performance/contexts/onDemandControl.tsx
  static/app/views/dashboards/manage/index.tsx
  static/app/views/discover/landing.tsx
  static/app/views/integrationPipeline/awsLambdaFunctionSelect.tsx
  static/app/views/issueDetails/actions/publishModal.tsx
  static/app/views/organizationStats/usageStatsOrg.tsx
  static/app/views/settings/account/accountSubscriptions.tsx
  static/app/views/settings/dynamicSampling/samplingModeSwitch.tsx
  static/app/views/settings/organizationIntegrations/installedPlugin.tsx
  static/app/views/settings/organizationIntegrations/integrationServerlessRow.tsx
  static/app/views/settings/project/projectFilters/projectFiltersSettings.tsx
  static/app/views/settings/project/projectServiceHooks.tsx
  static/app/views/settings/projectPlugins/projectPluginRow.tsx
Labels: Scope: Frontend

#86257 feat(issue-stream): Better truncation of 3rd line details
  static/app/components/eventOrGroupExtraDetails.tsx
Labels: Scope: Frontend

#86242 chore(aci): success logs for issue alert dual write
  src/sentry/api/endpoints/project_rule_details.py
  src/sentry/projects/project_rules/creator.py
  src/sentry/projects/project_rules/updater.py
  src/sentry/workflow_engine/migration_helpers/issue_alert_dual_write.py
  src/sentry/workflow_engine/migration_helpers/issue_alert_migration.py
  tests/sentry/api/endpoints/test_project_rule_details.py
Labels: Scope: Backend

#86293 ref(dashboards): Remove `BigNumberWidget`
  static/app/views/dashboards/widgets/bigNumberWidget/bigNumberWidget.stories.tsx
  static/app/views/dashboards/widgets/bigNumberWidget/bigNumberWidget.tsx
  static/app/views/dashboards/widgets/bigNumberWidget/bigNumberWidgetVisualization.spec.tsx
Labels: Scope: Frontend

#86212 fix(taskworker) Don't drop results when broker is unavailable
  src/sentry/taskworker/worker.py
  tests/sentry/taskworker/test_worker.py
Labels: Scope: Backend

#86268 :wrench: chore: remove uptime slack refactor flag
  src/sentry/features/temporary.py
  src/sentry/integrations/slack/actions/notification.py
  src/sentry/integrations/slack/service.py
Labels: Scope: Backend

#86295 ref: fix types for slack.actions.form
  pyproject.toml
  src/sentry/integrations/slack/actions/form.py
Labels: Scope: Backend

#86299 ref: fix types for api.endpoints.event_attachments
  pyproject.toml
  src/sentry/api/endpoints/event_attachments.py
Labels: Scope: Backend

#86305 feat(dashboards-eap): Hide extrapolation warning if not sampling
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetCard/chart.tsx
  static/app/views/dashboards/widgetCard/genericWidgetQueries.tsx
  static/app/views/dashboards/widgetCard/index.tsx
  static/app/views/dashboards/widgetCard/spansWidgetQueries.tsx
  static/app/views/dashboards/widgetCard/widgetCardChartContainer.tsx
  static/app/views/dashboards/widgetCard/widgetCardDataLoader.tsx
  static/app/views/dashboards/widgetViewer/widgetViewerContext.tsx
Labels: Scope: Frontend

#86260 feat(issue-stream): Smaller message text
  static/app/components/events/errorLevel.tsx
  static/app/components/stream/group.tsx
Labels: Scope: Frontend

#86225 fix(usefeedbackform): Prevent loss of feedback when form is closed
  static/app/utils/useFeedbackForm.spec.tsx
  static/app/utils/useFeedbackForm.tsx
Labels: Scope: Frontend

#86256 ref(seer grouping): Mark race-condition-losing hashes as Seer skips
  src/sentry/eventstore/models.py
  src/sentry/grouping/ingest/grouphash_metadata.py
  src/sentry/grouping/ingest/seer.py
  tests/sentry/grouping/ingest/test_seer.py
Labels: Scope: Backend

#86226 fix(grouping): Stop overwriting newer grouping config in grouphash metadata
  src/sentry/grouping/ingest/grouphash_metadata.py
  tests/sentry/event_manager/grouping/test_grouphash_metadata.py
Labels: Scope: Backend

#86267 :wrench: chore(aci): skip creating broken actions if not in a dry run
  src/sentry/workflow_engine/migration_helpers/rule_action.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_rule_action.py
Labels: Scope: Backend

#86235 feat(ourlogs): Add a trace item details endpoint + tests
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/api/endpoints/project_trace_item_details.py
  src/sentry/api/urls.py
  src/sentry/snuba/referrer.py
  src/sentry/testutils/cases.py
  src/sentry/utils/snuba_rpc.py
  tests/snuba/api/endpoints/test_project_trace_item_details.py
Labels: Scope: Backend

#85953 feat(relocation) Implement relocation transfer task
  src/sentry/relocation/services/relocation_export/impl.py
  src/sentry/relocation/tasks/process.py
  src/sentry/relocation/tasks/transfer.py
  tests/sentry/relocation/tasks/test_transfer.py
Labels: Scope: Backend

#86238 fix(trace): Add more fields
  src/sentry/api/endpoints/organization_spans_trace.py
  src/sentry/snuba/spans_rpc.py
Labels: Scope: Backend

#86234 fix(trace): Ignore project param
  src/sentry/api/endpoints/organization_spans_trace.py
  tests/snuba/api/endpoints/test_organization_spans_trace.py
Labels: Scope: Backend

#86297 ref: fix types for sentry.integrations.metric_alerts
  pyproject.toml
  src/sentry/integrations/metric_alerts.py
Labels: Scope: Backend

#86315 fix(crons): Fix api permissions to match alert permissions
  src/sentry/monitors/endpoints/base.py
  src/sentry/monitors/endpoints/organization_monitor_index.py
  src/sentry/monitors/endpoints/project_processing_errors_details.py
  src/sentry/monitors/endpoints/project_processing_errors_index.py
Labels: Scope: Backend

#86307 feat(issue-views): Only send mutation request on reorder completion
  static/app/components/nav/issueViews/issueViewNavEllipsisMenu.spec.tsx
  static/app/components/nav/issueViews/issueViewNavEllipsisMenu.tsx
  static/app/components/nav/issueViews/issueViewNavItemContent.tsx
  static/app/components/nav/issueViews/issueViewNavItems.tsx
Labels: Scope: Frontend

#86240 feat(ourlogs): Show all log details when expanding a row
  static/app/views/explore/contexts/logs/fields.tsx
  static/app/views/explore/contexts/logs/logsPageParams.tsx
  static/app/views/explore/logs/fieldRenderers.tsx
  static/app/views/explore/logs/logFieldsTree.tsx
  static/app/views/explore/logs/logsTable.tsx
  static/app/views/explore/logs/styles.tsx
  static/app/views/explore/logs/types.tsx
  static/app/views/explore/logs/useLogsQuery.tsx
Labels: Scope: Frontend

#86292 fix(explore): Sync chart and table colours when the number of series is fewer than 5
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/area.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/bars.tsx
  static/app/views/dashboards/widgets/timeSeriesWidget/plottables/line.tsx
  static/app/views/explore/multiQueryMode/queryVisualizations/table.tsx
  static/app/views/explore/tables/aggregatesTable.tsx
Labels: Scope: Frontend

#86217 feat(traces): Add schema hints list UI
  static/app/components/performance/spanSearchQueryBuilder.tsx
  static/app/views/explore/components/schemaHintsList.tsx
  static/app/views/explore/spans/spansTab.spec.tsx
  static/app/views/explore/spans/spansTab.tsx
Labels: Scope: Frontend

#86329 fix(issues): Context frames can contain null
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.tsx
  static/app/components/events/interfaces/frame/context.tsx
  static/app/components/events/interfaces/frame/stacktraceLink.tsx
  static/app/components/events/interfaces/frame/usePrismTokensSourceContext.tsx
  static/app/types/event.tsx
Labels: Scope: Frontend

#86052 fix(rpc): Validate trace_id queries on INs
  src/sentry/search/eap/span_columns.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#86313 chore(sentry apps) clean up FF for publish flow endpoint
  src/sentry/sentry_apps/api/endpoints/sentry_app_publish_request.py
  tests/sentry/sentry_apps/api/endpoints/test_sentry_app_publish_request.py
Labels: Scope: Backend

#86333 feat: Tag snuba retry errors
  src/sentry/utils/snuba.py
Labels: Scope: Backend

#86336 fix(flags): fix link in onboarding defaultMessage
  static/app/components/events/featureFlags/featureFlagOnboardingSidebar.tsx
Labels: Scope: Frontend

#86325 fix(ui): Releases legend color different when empty
  static/app/views/issueDetails/streamline/hooks/useReleaseMarkLineSeries.tsx
Labels: Scope: Frontend

#86339 fix(ourlogs): Use correct severity text setting
  static/app/views/explore/logs/logsTable.tsx
Labels: Scope: Frontend

#86337 flag(trace-eap-waterfall): Setting api_expose to True
  src/sentry/features/temporary.py
Labels: Scope: Backend

#86316 ref(ui): Do not round checkInTimeline ticks at edges
  static/app/components/checkInTimeline/checkInTimeline.tsx
Labels: Scope: Frontend

#86261 :wrench: chore: fix sentry app notification action for bug found in dry run
  src/sentry/workflow_engine/handlers/action/notification/issue_alert.py
  src/sentry/workflow_engine/typings/notification_action.py
  tests/sentry/workflow_engine/handlers/action/notification/test_issue_alert.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_alert_rule.py
  tests/sentry/workflow_engine/migration_helpers/test_migrate_rule_action.py
Labels: Scope: Backend

#86344 fix(aci): workflow name should allow 256 chars
  migrations_lockfile.txt
  src/sentry/workflow_engine/migrations/0033_workflow_name_256_char.py
  src/sentry/workflow_engine/models/workflow.py
Labels: Scope: Backend

#86253 chore(ACI): Make functions reusable, update tests
  src/sentry/incidents/endpoints/serializers/alert_rule_trigger_action.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_details.py
  tests/sentry/incidents/endpoints/test_serializers.py
Labels: Scope: Backend

#86340 feat(releases): add session health breakdown chart to insights
  static/app/views/insights/sessions/charts/sessionHealthCountChart.tsx
  static/app/views/insights/sessions/charts/sessionHealthRateChart.tsx
  static/app/views/insights/sessions/queries/useSessionHealthBreakdown.tsx
  static/app/views/insights/sessions/views/overview.tsx
Labels: Scope: Frontend

#86348 ref: fix types for endpoints.internal.mail
  pyproject.toml
  src/sentry/api/endpoints/internal/mail.py
Labels: Scope: Backend

#86319 ref(releases): add ProjectBadge to release tables on insights
  static/app/views/insights/sessions/components/tables/releaseAdoptionTable.tsx
  static/app/views/insights/sessions/components/tables/releaseHealthTable.tsx
  static/app/views/insights/sessions/queries/useOrganizationReleases.tsx
Labels: Scope: Frontend

#86317 chore(sentry app): update tests and remove FF for frontend publish flow
  static/app/components/modals/sentryAppPublishRequestModal/sentryAppPublishRequestModal.spec.tsx
  static/app/components/modals/sentryAppPublishRequestModal/sentryAppPublishRequestModal.tsx
  static/app/views/settings/organizationDeveloperSettings/index.spec.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationRow/sentryApplicationRowButtons.spec.tsx
  static/app/views/settings/organizationDeveloperSettings/sentryApplicationRow/sentryApplicationRowButtons.tsx
Labels: Scope: Frontend

#86357 chore(sentry apps): write out the categories for publishing emails
  static/app/components/modals/sentryAppPublishRequestModal/sentryAppUtils.tsx
Labels: Scope: Frontend

#86041 fix(issue-details): Fix edge case with sidebar
  static/app/views/issueDetails/streamline/groupDetailsLayout.tsx
  static/app/views/issueDetails/streamline/sidebar/toggleSidebar.tsx
Labels: Scope: Frontend

#86342 ref(aci): misc fixes for issue alert migration
  src/sentry/workflow_engine/migration_helpers/issue_alert_conditions.py
  src/sentry/workflow_engine/migration_helpers/issue_alert_dual_write.py
  src/sentry/workflow_engine/migration_helpers/issue_alert_migration.py
  tests/sentry/projects/project_rules/test_updater.py
  tests/sentry/workflow_engine/handlers/condition/test_event_frequency_handlers.py
  tests/sentry/workflow_engine/migration_helpers/test_issue_alert_migration.py
Labels: Scope: Backend

#85985 chore(stacktrace): Convert `RawContent` to functional component
  static/app/components/events/interfaces/crashContent/exception/rawContent.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.tsx
  static/app/components/events/interfaces/threads.spec.tsx
Labels: Scope: Frontend

#86364 fix(seer-issues-patch) Loosen issues first_seen_at to 52 weeks
  src/sentry/seer/fetch_issues_given_patches.py
Labels: Scope: Backend

#86173 fix(seer-issues-patch) More logs
  src/sentry/seer/fetch_issues_given_patches.py
  tests/sentry/seer/test_fetch_issues_given_patches.py
Labels: Scope: Backend

#86279 feat(laravel-insights): New queries widget
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
Labels: Scope: Frontend

#86272 chore(shellmayr): remove metrics endpoints from api publish list
  src/sentry/apidocs/api_publish_status_allowlist_dont_modify.py
Labels: Scope: Backend

#86271 fix(api): fix error in OrganizationSamplingProjectSpanCountsEndpoint when metric not set for projects
  src/sentry/api/endpoints/organization_sampling_project_span_counts.py
  tests/sentry/api/endpoints/test_organization_sampling_project_span_counts.py
Labels: Scope: Backend

#86367 feat(laravel-insights): New caches widget
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
Labels: Scope: Frontend

#86282 feat(ui): chonkify InputGroup
  static/app/components/core/input/index.chonk.tsx
  static/app/components/core/input/index.tsx
  static/app/components/core/input/inputGroup.chonk.tsx
  static/app/components/core/input/inputGroup.stories.tsx
  static/app/components/core/input/inputGroup.tsx
Labels: Scope: Frontend

#86368 fix(laravel-insights): fix display when 100% of jobs fail
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
Labels: Scope: Frontend

#86302 feat(demo-mode): artifact bundle sync
  src/sentry/conf/server.py
  src/sentry/demo_mode/tasks.py
  src/sentry/options/defaults.py
  src/sentry/utils/demo_mode.py
  tests/demo_mode/test_tasks.py
  tests/sentry/utils/test_demo_mode.py
Labels: Scope: Backend

#86373 feat(demo-mode): enable create alert button
  static/app/components/createAlertButton.tsx
Labels: Scope: Frontend

#86280 feat(derived_code_mappings): Support Java
  src/sentry/integrations/source_code_management/repo_trees.py
  src/sentry/issues/auto_source_code_config/code_mapping.py
  src/sentry/issues/auto_source_code_config/constants.py
  src/sentry/issues/auto_source_code_config/stacktraces.py
  src/sentry/issues/auto_source_code_config/task.py
  src/sentry/issues/auto_source_code_config/utils.py
  src/sentry/options/defaults.py
  src/sentry/tasks/post_process.py
  tests/sentry/issues/auto_source_code_config/test_code_mapping.py
  tests/sentry/issues/auto_source_code_config/test_process_event.py
  tests/sentry/issues/auto_source_code_config/test_stacktraces.py
Labels: Scope: Backend

#86375 fix(laravel-insights): Fix EAP query intervals
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
Labels: Scope: Frontend

#86374 chore(hybrid-cloud): Add logging to release registry
  src/sentry/integrations/aws_lambda/utils.py
  src/sentry/tasks/release_registry.py
Labels: Scope: Backend

#86347 ref: fix types for endpoints.organization_incident_index
  pyproject.toml
  src/sentry/incidents/endpoints/organization_incident_index.py
Labels: Scope: Backend

#86346 ref: fix types for organization_request_project_creation
  pyproject.toml
  src/sentry/api/endpoints/auth_index.py
  src/sentry/api/endpoints/organization_request_project_creation.py
Labels: Scope: Backend

#86296 ref: fix types for api.bases.organization_events
  pyproject.toml
  src/sentry/api/bases/organization.py
  src/sentry/api/bases/organization_events.py
  src/sentry/api/serializers/snuba.py
  src/sentry/replays/endpoints/organization_replay_index.py
Labels: Scope: Backend

#86283 fix(code_mappings): Do not append extension
  src/sentry/utils/event_frames.py
  tests/sentry/issues/auto_source_code_config/test_code_mapping.py
Labels: Scope: Backend

#86363 help: change to use input component
  static/app/components/modals/helpSearchModal.tsx
Labels: Scope: Frontend

#86358 commandpalette: use input component
  static/app/components/modals/commandPalette.tsx
Labels: Scope: Frontend

#86355 settings: use input component
  static/app/views/settings/components/settingsSearch/index.tsx
Labels: Scope: Frontend

#86378 feat(laravel-insights): Improve table responsiveness
  static/app/views/insights/pages/backend/laravelOverviewPage.tsx
Labels: Scope: Frontend
