Repository getsentry/sentry, pull requests merged in 2025-09, with the labels that each got.

#98507 fix: Update go back deletion in project install
  static/app/components/onboarding/useRecentCreatedProject.ts
Labels: Scope: Frontend

#98560 fix(ui): Hide consoles from platforms if not available
  static/app/views/settings/projectGeneralSettings/index.spec.tsx
  static/app/views/settings/projectGeneralSettings/index.tsx
Labels: Scope: Frontend

#98562 feat(loader): Rename debug bundles option to not be confused with logs
  static/app/views/settings/project/loaderScript.spec.tsx
  static/app/views/settings/project/projectKeys/details/loaderSettings.spec.tsx
  static/app/views/settings/project/projectKeys/details/loaderSettings.tsx
Labels: Scope: Frontend

#98567 fix(agent-monitoring): update min SDK version
  static/app/utils/gettingStartedDocs/node.tsx
Labels: Scope: Frontend

#98561 feat(loader): Make js loader v10 the default
  src/sentry/projectoptions/defaults.py
Labels: Scope: Frontend, Scope: Backend

#98402 feat(analytics): refactor integration notification analytics events (2)
  src/sentry/analytics/events/inapp_request.py
  src/sentry/analytics/events/integration_failed_to_fetch_commit_context.py
  src/sentry/analytics/events/integration_pipeline_step.py
  src/sentry/analytics/events/missing_members_nudge.py
  src/sentry/integrations/discord/analytics.py
  src/sentry/integrations/discord/views/link_identity.py
  src/sentry/integrations/discord/views/unlink_identity.py
  src/sentry/integrations/discord/webhooks/message_component.py
  src/sentry/integrations/messaging/linkage.py
  src/sentry/integrations/msteams/analytics.py
  src/sentry/integrations/msteams/webhook.py
  src/sentry/integrations/opsgenie/analytics.py
  src/sentry/integrations/pagerduty/analytics.py
  src/sentry/integrations/pipeline.py
  src/sentry/integrations/slack/analytics.py
  src/sentry/mail/analytics.py
  src/sentry/notifications/notifications/activity/release.py
  src/sentry/notifications/notifications/base.py
  src/sentry/notifications/notifications/missing_members_nudge.py
  src/sentry/notifications/notifications/organization_request/invite_request.py
  src/sentry/notifications/notifications/organization_request/join_request.py
  src/sentry/pipeline/base.py
  src/sentry/users/models/identity.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/notifications/notifications/test_digests.py
  tests/sentry/notifications/test_notifications.py
Labels: Scope: Backend

#98581 fix(ai): adds missing referrers
  src/sentry/snuba/referrer.py
Labels: Scope: Backend

#98585 fix(sandbox): add image to the dist output
  rspack.config.ts
Labels: Scope: Frontend

#98243 ref(kafka): Add get_arroyo_producer
  src/sentry/issues/attributes.py
  src/sentry/issues/producer.py
  src/sentry/monitors/clock_dispatch.py
  src/sentry/monitors/clock_tasks/producer.py
  src/sentry/monitors/logic/incident_occurrence.py
  src/sentry/monitors/tasks/clock_pulse.py
  src/sentry/options/defaults.py
  src/sentry/preprod/producer.py
  src/sentry/profiles/task.py
  src/sentry/replays/lib/kafka.py
  src/sentry/sentry_metrics/client/kafka.py
  src/sentry/spans/consumers/process_segments/factory.py
  src/sentry/taskworker/registry.py
  src/sentry/uptime/consumers/eap_producer.py
  src/sentry/uptime/consumers/results_consumer.py
  src/sentry/usage_accountant/accountant.py
  src/sentry/utils/arroyo_producer.py
  tests/sentry/replays/unit/test_event_logger.py
  tests/sentry/spans/consumers/process_segments/test_factory.py
Labels: Scope: Backend

#98589 feat(agent-monitoring): don't restrict message role names
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/eapSections/aiInput.tsx
Labels: Scope: Frontend

#98546 chore(performance): removes unused page web vitals summary endpoint
  src/sentry/api/urls.py
  src/sentry/seer/endpoints/organization_page_web_vitals_summary.py
  src/sentry/seer/models.py
  src/sentry/seer/page_web_vitals_summary.py
  tests/sentry/seer/endpoints/test_organization_page_web_vitals_summary.py
  tests/sentry/seer/test_page_web_vitals_summary.py
Labels: Scope: Backend

#98596 fix(insights): `transaction.op:all` filter applied from frontend
  static/app/views/insights/pages/frontend/frontendOverviewTable.tsx
  static/app/views/insights/pages/frontend/newFrontendOverviewPage.tsx
  static/app/views/insights/pages/frontend/utils/pageSpanOp.ts
Labels: Scope: Frontend

#98537 chore(profiling): Add more analytics to flamegraph
  static/app/components/profiling/flamegraph/continuousFlamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraph.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphOptionsMenu.tsx
  static/app/components/profiling/flamegraph/flamegraphToolbar/flamegraphThreadSelector.tsx
  static/app/utils/analytics/profilingAnalyticsEvents.tsx
  static/app/views/performance/transactionSummary/transactionProfiles/content.tsx
  static/app/views/profiling/continuousProfileFlamegraph.tsx
  static/app/views/profiling/landingAggregateFlamegraph.tsx
  static/app/views/profiling/profileFlamechart.tsx
Labels: Scope: Frontend

#98524 feat(logs): Use query params for fields and sort bys
  static/app/utils/analytics/logsAnalyticsEvent.tsx
  static/app/views/explore/contexts/logs/logsPageParams.tsx
  static/app/views/explore/hooks/useAnalytics.tsx
  static/app/views/explore/logs/logsAutoRefresh.tsx
  static/app/views/explore/logs/logsTab.tsx
  static/app/views/explore/logs/tables/logsAggregateTable.tsx
  static/app/views/explore/logs/tables/logsInfiniteTable.tsx
  static/app/views/explore/logs/tables/logsTableRow.tsx
  static/app/views/explore/logs/useLogAttributesTreeActions.tsx
  static/app/views/explore/logs/useLogsQuery.tsx
  static/app/views/explore/logs/useLogsSearchQueryBuilderProps.tsx
  static/app/views/explore/logs/utils.tsx
  static/app/views/explore/queryParams/context.tsx
Labels: Scope: Frontend

#98446 feat(bug-prediction): Get more issue details
  src/sentry/seer/fetch_issues/fetch_issues_given_exception_type.py
  tests/sentry/seer/fetch_issues/test_fetch_issues_given_exception_type.py
Labels: Scope: Backend

#98597 feat(checkout v3): Collapsible steps
  static/gsApp/views/amCheckout/steps/checkoutV3/buildYourPlan.tsx
  static/gsApp/views/amCheckout/steps/stepHeader.spec.tsx
  static/gsApp/views/amCheckout/steps/stepHeader.tsx
Labels: Scope: Frontend

#98503 :bug: fix(aci): fix slack interactions during rollout
  src/sentry/integrations/slack/webhooks/action.py
  tests/sentry/integrations/slack/webhooks/actions/__init__.py
  tests/sentry/integrations/slack/webhooks/actions/test_status.py
Labels: Scope: Backend

#98488 chore(releases): Add function to detect unused `PullRequest` rows, and remove fk to commit
  migrations_lockfile.txt
  src/sentry/migrations/0970_remove_pullrequestcommit_fk_constraint.py
  src/sentry/models/pullrequest.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  tests/sentry/models/test_pullrequest.py
Labels: Scope: Backend

#98559 feat(taskworker): add grpc healthcheck for worker
  src/sentry/runner/commands/run.py
  src/sentry/taskworker/client/client.py
  src/sentry/taskworker/constants.py
  src/sentry/taskworker/worker.py
  tests/sentry/taskworker/test_client.py
Labels: Scope: Backend

#97896 fix(aci): limit Github repository choices fetched for create issue config
  src/sentry/features/temporary.py
  src/sentry/integrations/bitbucket/integration.py
  src/sentry/integrations/bitbucket_server/integration.py
  src/sentry/integrations/example/integration.py
  src/sentry/integrations/github/client.py
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/github/issues.py
  src/sentry/integrations/github_enterprise/integration.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/integrations/source_code_management/issues.py
  src/sentry/integrations/source_code_management/repository.py
  src/sentry/integrations/vsts/integration.py
Labels: Scope: Backend

#98619 feat(replay): Switch to new pod with fallback
  src/sentry/replays/endpoints/project_replay_summary.py
  src/sentry/replays/usecases/delete.py
  tests/sentry/replays/unit/usecases/test_delete_seer_replay_data.py
Labels: Scope: Backend

#98300 ref(grouping): Make stacktrace order in issue diff reflect user setting
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.tsx
  static/app/components/issueDiff/index.tsx
  static/app/utils/getStacktraceBody.tsx
Labels: Scope: Frontend

#98610 fix(trace-eap-waterfall): Don't render JSON btn if transactionid is not defined
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
Labels: Scope: Frontend

#98624 feat(feedback): Move feedback summaries to new Seer pod
  src/sentry/feedback/endpoints/organization_feedback_summary.py
  src/sentry/feedback/usecases/label_generation.py
  src/sentry/feedback/usecases/title_generation.py
  tests/sentry/feedback/endpoints/test_organization_feedback_summary.py
  tests/sentry/feedback/usecases/test_label_generation.py
  tests/sentry/feedback/usecases/test_title_generation.py
Labels: Scope: Backend

#98394 feat(checkout v3): Cart diff
  static/gsApp/types/index.tsx
  static/gsApp/views/amCheckout/billingCycleSelectCard.tsx
  static/gsApp/views/amCheckout/cart.spec.tsx
  static/gsApp/views/amCheckout/cart.tsx
  static/gsApp/views/amCheckout/cartDiff.tsx
  static/gsApp/views/amCheckout/reserveAdditionalVolume.tsx
Labels: Scope: Frontend

#98543 feat(insights): Web Vitals initiate Seer Suggestions flow
  static/app/views/insights/browser/webVitals/components/pageOverviewSidebar.spec.tsx
  static/app/views/insights/browser/webVitals/components/pageOverviewSidebar.tsx
  static/app/views/insights/browser/webVitals/components/pageOverviewWebVitalsDetailPanel.spec.tsx
  static/app/views/insights/browser/webVitals/components/pageOverviewWebVitalsDetailPanel.tsx
  static/app/views/insights/browser/webVitals/components/webVitalDescription.tsx
  static/app/views/insights/browser/webVitals/queries/useWebVitalsIssuesQuery.tsx
  static/app/views/insights/browser/webVitals/utils/useCreateIssue.tsx
  static/app/views/insights/browser/webVitals/utils/useRunSeerAnalysis.tsx
Labels: Scope: Frontend

#98636 fix(insights): remove db module denylist message
  static/app/views/insights/database/components/noDataMessage.spec.tsx
  static/app/views/insights/database/components/noDataMessage.tsx
  static/app/views/insights/database/queries/useDenylistedProjects.tsx
Labels: Scope: Frontend

#98483 fix(taskworker): Add associated brokers to task execution metric
  src/sentry/taskworker/workerchild.py
Labels: Scope: Backend

#98298 ref(ourlogs): Cleanup feature flags for ourlogs (BE)
  src/sentry/explore/utils.py
  src/sentry/features/temporary.py
  src/sentry/relay/globalconfig.py
  src/sentry/snuba/snuba_query_validator.py
  tests/acceptance/test_explore_logs.py
  tests/sentry/incidents/endpoints/test_organization_alert_rule_index.py
Labels: Scope: Backend

#98640 feat(billing): Update quota docs link for Logs
  static/app/views/settings/account/notifications/utils.tsx
Labels: Scope: Frontend

#98638 feat(logs): Add advanced to expand buttons
  static/app/views/explore/logs/logsTab.tsx
  static/app/views/explore/spans/spansTab.tsx
Labels: Scope: Frontend

#98644 chore(ui): Disallow IIFEs inside jsx
  eslint.config.mjs
Labels: Scope: Frontend

#98499 ref(replay): cleanup unused options
  src/sentry/options/defaults.py
Labels: Scope: Backend

#98401 feat(aci): Update cron monitors to use correct config shape
  static/app/types/workflowEngine/detectors.tsx
  static/app/views/detectors/components/details/cron/index.tsx
  static/app/views/detectors/components/detectorLink.tsx
  static/app/views/detectors/components/forms/cron/fields.tsx
  static/app/views/detectors/detail.spec.tsx
  static/app/views/detectors/utils/getDetectorEnvironment.tsx
  static/app/views/insights/crons/types.tsx
  tests/js/fixtures/detectors.ts
Labels: Scope: Frontend

#98482 fix(replays): add more robust as_log_message tests
  src/sentry/replays/endpoints/project_replay_summary.py
  src/sentry/replays/usecases/ingest/event_parser.py
  src/sentry/replays/usecases/summarize.py
  tests/sentry/replays/lib/test_summarize.py
  tests/sentry/replays/usecases/test_summarize.py
Labels: Scope: Backend

#98650 feat(prevent): adjust all branches behavior
  static/app/components/prevent/branchSelector/branchSelector.tsx
  static/app/components/prevent/container/preventParamsProvider.tsx
  static/app/components/prevent/context/preventContext.tsx
  static/app/views/prevent/tests/queries/useGetTestResults.ts
  static/app/views/prevent/tests/queries/useTestResultsAggregates.ts
  static/app/views/prevent/tests/tests.tsx
Labels: Scope: Frontend

#98663 ref(alerts): Move incident redirect off of router props
  static/app/routes.tsx
  static/app/utils/useParams.tsx
  static/app/views/alerts/incidentRedirect.spec.tsx
  static/app/views/alerts/incidentRedirect.tsx
Labels: Scope: Frontend

#98643 fix(integrations): Populate default branch for code path mapping repos
  static/app/views/settings/organizationIntegrations/repositoryProjectPathConfigForm.tsx
Labels: Scope: Frontend

#98671 feat(aci): Continue delayed_workflows with partial Snuba results on last attempt
  src/sentry/workflow_engine/tasks/delayed_workflows.py
  tests/sentry/workflow_engine/tasks/test_delayed_workflows.py
Labels: Scope: Backend

#98664 ref(feedback): Refactor `<MessageSection>` into two parts
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/messageSection.tsx
  static/app/components/feedback/feedbackItem/messageTitle.tsx
Labels: Scope: Frontend

#98484 fix(replays): add `timestamp_ms` to issue platform in snuba event columns
  src/sentry/snuba/events.py
  tests/sentry/replays/endpoints/test_organization_replay_events_meta.py
Labels: Scope: Backend

#98666 fix(discover-event-details): Re-routing links pointing to legacy discover event details
  static/app/routes.tsx
  static/app/views/discover/eventDetails.tsx
Labels: Scope: Frontend

#98515 chore(search-bar): Remove previous wildcard ops
  static/app/components/searchQueryBuilder/formattedQuery.tsx
  static/app/components/searchQueryBuilder/hooks/useQueryBuilderState.spec.tsx
  static/app/components/searchQueryBuilder/hooks/useQueryBuilderState.tsx
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filter.tsx
  static/app/components/searchQueryBuilder/tokens/filter/filterOperator.tsx
  static/app/components/searchQueryBuilder/tokens/filter/utils.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/types.tsx
  static/app/components/searchQueryBuilder/tokens/filterKeyListBox/utils.tsx
  static/app/components/searchQueryBuilder/tokens/freeText.tsx
  static/app/components/searchQueryBuilder/tokens/useSortedFilterKeyItems.tsx
  static/app/components/searchQueryBuilder/types.tsx
Labels: Scope: Frontend

#98432 fix(search-bar): Convert negated text input to filters
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/components/searchQueryBuilder/tokens/freeText.tsx
Labels: Scope: Frontend

#98692 fix(ai): generation counts
  static/app/views/insights/agents/utils/query.tsx
Labels: Scope: Frontend

#98641 ref: fix typing in sentry.issues.search
  pyproject.toml
  src/sentry/issues/search.py
Labels: Scope: Backend

#98687 Added: isChonk Flag with path clause
  static/app/icons/iconBuilding.tsx
  static/app/icons/iconCompass.tsx
  static/app/icons/iconPrevent.tsx
  static/app/icons/icons.stories.tsx
Labels: Scope: Frontend

#98634 Reapply "icons: offset by whole numbers (#97467)"
  static/app/icons/svgIcon.tsx
Labels: Scope: Frontend

#98542 chore(dashboards): Make order nullable on widgets
  migrations_lockfile.txt
  src/sentry/migrations/0971_make_dashboard_widget_order_optional_field.py
  src/sentry/models/dashboard_widget.py
Labels: Scope: Backend

#98700 fix(notif-platform): Allow debugger to load in production
  src/sentry/web/debug_urls.py
  src/sentry/web/urls.py
Labels: Scope: Backend

#98505 build(ui): rspack 1.5
  package.json
  pnpm-lock.yaml
  rspack.config.ts
Labels: Scope: Frontend

#98660 ref(settings): Remove router props from audit log
  static/app/routes.tsx
  static/app/views/settings/organizationAuditLog/auditLogView.spec.tsx
  static/app/views/settings/organizationAuditLog/index.spec.tsx
  static/app/views/settings/organizationAuditLog/index.tsx
Labels: Scope: Frontend

#98669 feat(feedback): Show event evidence inside the Feedback Details > Context section
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
Labels: Scope: Frontend

#98674 chore(prevent-ai): Fix prevent AI toggle copy
  static/app/data/forms/organizationGeneralSettings.tsx
  static/app/views/settings/organizationGeneralSettings/organizationSettingsForm.spec.tsx
Labels: Scope: Frontend

#98673 fix(typing): Remove sentry.web.frontend.auth_login from problem list
  pyproject.toml
  src/sentry/api/invite_helper.py
  src/sentry/web/frontend/auth_login.py
  src/sentry/web/frontend/auth_organization_login.py
  src/sentry/web/frontend/base.py
  src/sentry/web/frontend/oauth_authorize.py
Labels: Scope: Backend

#98623 feat(releases): Add ability to filter deletions when performing bulk deletions in `ModelDeletionTask.chunk`, and filter `PullRequest` deletions
  src/sentry/deletions/base.py
  src/sentry/deletions/defaults/group.py
  src/sentry/deletions/defaults/grouphistory.py
  src/sentry/deletions/defaults/pullrequest.py
  src/sentry/models/pullrequest.py
  src/sentry/runner/commands/cleanup.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  tests/sentry/deletions/test_pullrequest.py
Labels: Scope: Backend

#98690 chore(ask-seer): Remove Ask Seer suggestions
  static/app/components/searchQueryBuilder/index.spec.tsx
  static/app/utils/analytics/tracingEventMap.tsx
  static/app/views/explore/components/seerComboBox/seerComboBox.spec.tsx
  static/app/views/explore/components/seerComboBox/seerComboBox.tsx
  static/app/views/explore/components/seerComboBox/seerSearchHeader.tsx
  static/app/views/explore/components/seerComboBox/seerSearchListBox.tsx
  static/app/views/explore/components/seerComboBox/seerSearchSkeleton.tsx
Labels: Scope: Frontend

#98407 ref(billing): Modern Stripe Implementation using react-stripe-js and stripe-js
  knip.config.ts
  package.json
  pnpm-lock.yaml
  static/gsApp/components/creditCardForm.tsx
  static/gsApp/components/creditCardSetup.tsx
  static/gsApp/hooks/useStripeInstance.tsx
  static/gsApp/types/index.tsx
  static/gsApp/utils/stripe.tsx
  static/gsApp/views/amCheckout/cart.tsx
  static/gsApp/views/amCheckout/index.tsx
  static/gsApp/views/amCheckout/steps/addBillingDetails.spec.tsx
  static/gsApp/views/amCheckout/steps/addPaymentMethod.spec.tsx
  static/gsApp/views/amCheckout/steps/reviewAndConfirm.spec.tsx
  static/gsApp/views/amCheckout/steps/reviewAndConfirm.tsx
  static/gsApp/views/amCheckout/utils.tsx
  static/gsApp/views/invoiceDetails/paymentForm.spec.tsx
  static/gsApp/views/invoiceDetails/paymentForm.tsx
  static/gsApp/views/subscriptionPage/billingDetails.spec.tsx
  tests/js/setup.ts
Labels: Scope: Frontend

#97356 chore(severity): Fix some typos
  src/sentry/event_manager.py
  src/sentry/options/defaults.py
  tests/sentry/event_manager/test_severity.py
Labels: Scope: Backend

#98255 ref(groupingInfo): Fix contributing frame hidden when showing all values
  static/app/components/events/groupingInfo/groupingComponentFrames.tsx
  static/app/components/events/groupingInfo/groupingComponentStacktrace.tsx
Labels: Scope: Frontend

#98653 ref(replay): hide summaries tab for mobile
  static/app/views/replays/detail/layout/focusTabs.tsx
Labels: Scope: Frontend

#98715 fix(replay): Remove profiling from replay recording consumer and tests
  src/sentry/replays/consumers/recording.py
  tests/sentry/replays/integration/consumers/test_recording.py
  tests/sentry/replays/unit/consumers/test_recording.py
Labels: Scope: Backend

#98712 ref(performance): Remove router props from `TransactionSpans`
  static/app/routes.tsx
  static/app/views/performance/transactionSummary/transactionSpans/index.spec.tsx
  static/app/views/performance/transactionSummary/transactionSpans/index.tsx
Labels: Scope: Frontend

#98041 feat(session replay): sync times absolute and relative
  static/app/components/replays/replayBadge.tsx
  static/app/views/replays/list.tsx
  static/app/views/replays/list/replayListProviders.tsx
Labels: Scope: Frontend

#98716 fix: Add itms scheme for iOS install
  static/app/views/preprod/components/installModal.tsx
Labels: Scope: Frontend

#98706 chore(timeseries): Add feature flag for spot-checking `/events-timeseries/` output
  src/sentry/features/temporary.py
Labels: Scope: Backend

#98398 fix(perms): default member project creation to false on org creation
  src/sentry/models/organization.py
  tests/sentry/core/endpoints/test_organization_projects_experiment.py
  tests/sentry/models/test_organization.py
Labels: Scope: Backend

#98678 feat(aci): Add next/last checkin to cron details page
  static/app/views/detectors/components/details/cron/index.tsx
  static/app/views/detectors/detail.spec.tsx
  tests/js/fixtures/detectors.ts
Labels: Scope: Frontend

#98677 fix: 421 misdirected status code when forwarding webhooks
  src/sentry/hybridcloud/tasks/deliver_webhooks.py
Labels: Scope: Backend

#98731 feat(ourlogs): Re-add setup logs
  static/app/utils/analytics/logsAnalyticsEvent.tsx
  static/app/views/explore/logs/content.tsx
Labels: Scope: Frontend

#98713 chore(summarization): Remove rollout option from issue summarization
  src/sentry/options/defaults.py
  src/sentry/seer/autofix/issue_summary.py
Labels: Scope: Backend

#98733 feat(aci): Add cron detector search alias
  src/sentry/workflow_engine/endpoints/organization_detector_index.py
  tests/sentry/workflow_engine/endpoints/test_organization_detector_index.py
Labels: Scope: Backend

#98738 fix(logs): Add length check to filtered
  static/app/views/explore/logs/content.tsx
Labels: Scope: Frontend

#98735 fix(explore): Fix trace item details race condition
  static/app/views/explore/hooks/useTraceItemDetails.tsx
Labels: Scope: Frontend

#98736 feat(explorer): New minified mode
  static/app/views/seerExplorer/explorerPanel.tsx
  static/app/views/seerExplorer/hooks/usePanelSizing.tsx
  static/app/views/seerExplorer/minimizedStrip.tsx
  static/app/views/seerExplorer/panelContainers.tsx
Labels: Scope: Frontend

#98743 feat(ourlogs): Change header button colors
  static/app/views/explore/logs/content.tsx
  static/app/views/explore/logs/logsTab.tsx
Labels: Scope: Frontend

#98655 fix(eap): Handle vcc filtering
  src/sentry/search/eap/resolver.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#98748 ref(preprod): Remove router props from preprod routes
  static/app/routes.tsx
  static/app/views/preprod/index.tsx
Labels: Scope: Frontend

#98681 feat(aci): Add upserting warning to cron details page
  static/app/views/detectors/components/details/cron/index.tsx
  static/app/views/detectors/components/forms/cron/index.tsx
Labels: Scope: Frontend

#98606 feat(trace-eap-waterfall): Ensuring onTraceLoad runs on re-renders
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
  static/app/views/performance/newTraceDetails/useTraceOnLoad.tsx
  static/app/views/performance/newTraceDetails/useTraceScrollToPath.tsx
Labels: Scope: Frontend

#98604 feat(trace-eap-waterfall): Relocating tracewaterfall models instantiation
  static/app/components/events/interfaces/performance/eventTraceView.tsx
  static/app/components/events/interfaces/performance/spanEvidenceTraceView.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/issuesTraceWaterfall.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/traceAiSpans.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
  static/app/views/performance/newTraceDetails/useTraceOnLoad.tsx
  static/app/views/performance/newTraceDetails/useTraceScrollToPath.tsx
  static/app/views/replays/detail/trace/trace.tsx
Labels: Scope: Frontend

#98745 fix(autofix-state): Check org-id in autofix get function
  src/sentry/seer/autofix/autofix.py
  src/sentry/seer/autofix/issue_summary.py
  src/sentry/seer/autofix/utils.py
  src/sentry/seer/endpoints/group_ai_autofix.py
  src/sentry/seer/models.py
  src/sentry/tasks/autofix.py
  tests/sentry/autofix/test_utils.py
  tests/sentry/autofix/test_webhooks.py
  tests/sentry/seer/autofix/test_autofix.py
  tests/sentry/seer/endpoints/test_group_ai_autofix.py
  tests/sentry/tasks/test_autofix.py
Labels: Scope: Backend

#98620 fix(issue details): Add exhaustive(-ish) platform support for raw stack traces
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.spec.tsx
  static/app/components/events/interfaces/crashContent/stackTrace/rawContent.tsx
  static/app/components/issueDiff/index.tsx
  static/app/utils/getStacktraceBody.spec.tsx
  static/app/utils/getStacktraceBody.tsx
Labels: Scope: Frontend

#98757 fix(replay): fix feedback replay context not resetting
  static/app/components/feedback/feedbackItem/replaySection.tsx
Labels: Scope: Frontend

#98504 ref(suspect commits): Simplify event file committers to GroupOwner-only behavior
  src/sentry/api/endpoints/event_file_committers.py
  src/sentry/integrations/utils/commit_context.py
  src/sentry/utils/committers.py
  tests/sentry/api/endpoints/test_event_committers.py
  tests/sentry/mail/test_adapter.py
  tests/sentry/tasks/test_commit_context.py
  tests/sentry/tasks/test_groupowner.py
  tests/sentry/utils/test_committers.py
Labels: Scope: Backend

#98758 chore(ACI): Add logs for triggers to compare both systems
  src/sentry/incidents/subscription_processor.py
  src/sentry/workflow_engine/processors/workflow.py
  tests/sentry/workflow_engine/processors/test_workflow.py
Labels: Scope: Backend

#98781 fix(explorer): Fix optimistic messages
  static/app/views/seerExplorer/hooks/useSeerExplorer.tsx
Labels: Scope: Frontend

#98693 ref(spans): Separate span tree enrichment from shimming
  src/sentry/spans/consumers/process_segments/convert.py
  src/sentry/spans/consumers/process_segments/enrichment.py
  src/sentry/spans/consumers/process_segments/factory.py
  src/sentry/spans/consumers/process_segments/message.py
  src/sentry/spans/consumers/process_segments/shim.py
  src/sentry/spans/consumers/process_segments/types.py
  src/sentry/testutils/cases.py
  tests/sentry/spans/consumers/process_segments/test_convert.py
  tests/sentry/spans/consumers/process_segments/test_enrichment.py
Labels: Scope: Backend

#98784 feat(ai): Generate fuzzy matching model names in pricing dict
  src/sentry/tasks/ai_agent_monitoring.py
  tests/sentry/tasks/test_ai_agent_monitoring.py
Labels: Scope: Backend

#98527 ref(uptime): Use detectorId for uptime rules on the frontend
  static/app/actionCreators/uptime.tsx
  static/app/components/events/interfaces/uptime/uptimeDataSection.spec.tsx
  static/app/components/events/interfaces/uptime/uptimeDataSection.tsx
  static/app/routes.tsx
  static/app/views/alerts/list/rules/alertRulesList.spec.tsx
  static/app/views/alerts/list/rules/alertRulesList.tsx
  static/app/views/alerts/list/rules/row.tsx
  static/app/views/alerts/rules/uptime/details.spec.tsx
  static/app/views/alerts/rules/uptime/details.tsx
  static/app/views/alerts/rules/uptime/detailsTimeline.tsx
  static/app/views/alerts/rules/uptime/edit.spec.tsx
  static/app/views/alerts/rules/uptime/edit.tsx
  static/app/views/alerts/rules/uptime/existingOrCreate.spec.tsx
  static/app/views/alerts/rules/uptime/existingOrCreate.tsx
  static/app/views/alerts/rules/uptime/types.tsx
  static/app/views/alerts/rules/uptime/uptimeAlertForm.spec.tsx
  static/app/views/alerts/rules/uptime/uptimeAlertForm.tsx
  static/app/views/alerts/rules/uptime/uptimeChecksTable.tsx
  static/app/views/alerts/rules/uptime/uptimeIssues.tsx
  static/app/views/insights/uptime/components/overviewTimeline/index.tsx
  static/app/views/insights/uptime/components/overviewTimeline/overviewRow.tsx
  static/app/views/insights/uptime/utils/useUptimeChecks.tsx
  static/app/views/insights/uptime/utils/useUptimeMonitorStats.tsx
  static/app/views/insights/uptime/utils/useUptimeMonitorSummary.tsx
  static/app/views/insights/uptime/utils/useUptimeRule.tsx
  static/app/views/insights/uptime/views/overview.spec.tsx
  static/app/views/issueDetails/groupUptimeChecks.spec.tsx
  static/app/views/issueDetails/groupUptimeChecks.tsx
  static/app/views/issueDetails/streamline/eventDetailsHeader.spec.tsx
  static/app/views/issueDetails/streamline/issueUptimeCheckTimeline.spec.tsx
  static/app/views/issueDetails/streamline/issueUptimeCheckTimeline.tsx
  static/app/views/issueDetails/streamline/occurrenceSummary.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/detectorSection.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/detectorSection.tsx
  tests/js/fixtures/uptimeRule.ts
Labels: Scope: Frontend

#98535 ref(uptime): Stop using ProjectUptimeSubscription in checks_index
  src/sentry/uptime/endpoints/project_uptime_alert_checks_index.py
  src/sentry/uptime/endpoints/serializers.py
  src/sentry/uptime/types.py
  tests/sentry/uptime/endpoints/test_project_uptime_alert_check_index.py
Labels: Scope: Backend

#98680 :mag: nit(integrations): update integration deletion copy to emphasize disabling of actions
  static/app/views/settings/organizationIntegrations/installedIntegration.tsx
Labels: Scope: Frontend

#98675 :sparkles: feat(aci): default to issue alert handler in NOA if grouptype is not registered
  src/sentry/notifications/notification_action/utils.py
  tests/sentry/notifications/notification_action/test_group_type_notification_registry_handlers.py
  tests/sentry/workflow_engine/handlers/action/test_action_handlers.py
Labels: Scope: Backend

#98730 fix(typing): Remove sentry_plugins.jira.plugin from problem list
  pyproject.toml
  src/sentry/plugins/bases/issue2.py
  src/sentry_plugins/jira/plugin.py
Labels: Scope: Backend

#98480 feat(ourlogs): Add usage exceeded banner
  static/app/views/explore/hooks/useAnalytics.tsx
  static/app/views/explore/logs/logsTab.tsx
  static/app/views/explore/spans/spansTab.tsx
  static/app/views/performance/newTraceDetails/issuesTraceWaterfall.tsx
  static/app/views/performance/newTraceDetails/traceTypeWarnings/errorsOnlyWarnings.tsx
  static/app/views/performance/newTraceDetails/traceTypeWarnings/usePerformanceSubscriptionDetails.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
  static/gsApp/components/performance/quotaExceededAlert.spec.tsx
  static/gsApp/components/performance/quotaExceededAlert.tsx
  static/gsApp/hooks/performance/usePerformanceUsageStats.tsx
  static/gsApp/utils/trackGetsentryAnalytics.tsx
Labels: Scope: Frontend

#98796 ref(insights): remove module upsells
  static/app/types/hooks.tsx
  static/app/views/insights/agents/views/overview.tsx
  static/app/views/insights/browser/resources/views/resourceSummaryPage.tsx
  static/app/views/insights/browser/resources/views/resourcesLandingPage.tsx
  static/app/views/insights/browser/webVitals/views/pageOverview.tsx
  static/app/views/insights/browser/webVitals/views/webVitalsLandingPage.tsx
  static/app/views/insights/cache/views/cacheLandingPage.tsx
  static/app/views/insights/common/components/moduleFeature.spec.tsx
  static/app/views/insights/common/components/moduleFeature.tsx
  static/app/views/insights/database/views/databaseLandingPage.tsx
  static/app/views/insights/database/views/databaseSpanSummaryPage.tsx
  static/app/views/insights/http/views/httpDomainSummaryPage.tsx
  static/app/views/insights/http/views/httpLandingPage.tsx
  static/app/views/insights/mcp/views/overview.tsx
  static/app/views/insights/mobile/screens/views/screensLandingPage.tsx
  static/app/views/insights/queues/views/destinationSummaryPage.tsx
  static/app/views/insights/queues/views/queuesLandingPage.tsx
  static/gsApp/components/features/insightsUpsellPage.spec.tsx
  static/gsApp/components/features/insightsUpsellPage.tsx
  static/gsApp/components/sidebarNavigationItem.tsx
  static/gsApp/components/upsellModal/footer.tsx
  static/gsApp/registerHooks.tsx
Labels: Scope: Frontend

#98160 chore: delete dashbaord widget snapshot table
  migrations_lockfile.txt
  src/sentry/migrations/0973_safe_del_dashboardwidgetsnapshot.py
Labels: Scope: Backend

#98762 feat(billing): Move TrialStarter to FC
  static/gsApp/components/trialStarter.tsx
Labels: Scope: Frontend

#98771 feat(ui): Capture `tctCode` translations
  .github/CODEOWNERS
  build-utils/ts-extract-gettext.ts
Labels: Scope: Frontend

#98580 analytics(trace-eap-waterfall): Centralizing trace state analytics
  static/app/components/events/interfaces/performance/anrRootCause.spec.tsx
  static/app/components/events/interfaces/performance/anrRootCause.tsx
  static/app/components/events/interfaces/performance/eventTraceView.tsx
  static/app/components/events/interfaces/performance/spanEvidenceTraceView.tsx
  static/app/utils/analytics/tracingEventMap.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetails.spec.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/issuesTraceWaterfall.tsx
  static/app/views/performance/newTraceDetails/traceAnalytics.tsx
  static/app/views/performance/newTraceDetails/traceApi/useIssuesTraceTree.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTraceTree.spec.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTraceTree.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/tabs/traceAiSpans.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
  static/app/views/performance/newTraceDetails/useTraceOnLoad.tsx
  static/app/views/performance/newTraceDetails/useTraceScrollToPath.tsx
  static/app/views/performance/newTraceDetails/useTraceStateAnalytics.tsx
  static/app/views/replays/detail/trace/trace.tsx
Labels: Scope: Frontend

#98813 chore(dashboards): Move edit perm check helper to util file
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboards/controls.tsx
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/filtersBar.tsx
  static/app/views/dashboards/sortableWidget.tsx
  static/app/views/dashboards/utils/checkUserHasEditAccess.tsx
Labels: Scope: Frontend

#98778 feat(preprod): Use new fields for app metadata
  src/sentry/preprod/api/endpoints/project_installable_preprod_artifact_download.py
  tests/sentry/preprod/api/endpoints/test_project_installable_preprod_artifact_download.py
Labels: Scope: Backend

#97681 fix(uptime): allow uptime subscription updates on active subs
  src/sentry/uptime/subscriptions/tasks.py
  tests/sentry/uptime/subscriptions/test_tasks.py
Labels: Scope: Backend

#98830 feat(preprod): Add download count
  src/sentry/preprod/api/endpoints/project_preprod_artifact_install_details.py
Labels: Scope: Backend

#98829 feat(insights): add full screen button to time spent widgets
  static/app/components/modals/insightChartModal.tsx
  static/app/views/insights/common/components/widgets/overviewSlowAssetsWidget.tsx
  static/app/views/insights/common/components/widgets/overviewTimeConsumingRequestsWidget.tsx
  static/app/views/insights/pages/platform/shared/styles.tsx
Labels: Scope: Frontend

#98804 feat(dashboards): Clean up unused functions
  static/app/components/modals/widgetViewerModal.tsx
  static/app/views/dashboards/detail.spec.tsx
  static/app/views/dashboards/detail.tsx
Labels: Scope: Frontend

#98838 chore(nav): Remove opt-out option from help menu
  static/app/views/nav/primary/help.tsx
  static/app/views/nav/tour/tour.tsx
Labels: Scope: Frontend

#98626 bugbot: suggest decoupling typography from layout
  static/.cursor/BUGBOT.md
Labels: Scope: Frontend

#98841 fix(typing): Remove sentry.notifications.notifications.activity.base from problem list
  pyproject.toml
  src/sentry/notifications/notifications/activity/base.py
  src/sentry/notifications/utils/avatar.py
Labels: Scope: Backend

#98837 chore(aci milestone 3): log workflow trigger group type so we can filter by it
  src/sentry/workflow_engine/processors/workflow.py
  tests/sentry/workflow_engine/processors/test_workflow.py
Labels: Scope: Backend

#98835 feat(issues): Convert similar stack trace to fc
  static/app/views/issueDetails/groupSimilarIssues/similarStackTrace/item.tsx
  static/app/views/issueDetails/groupSimilarIssues/similarStackTrace/list.tsx
Labels: Scope: Frontend

#98843 ref(seer): Fixability only GPU
  src/sentry/options/defaults.py
  src/sentry/seer/autofix/issue_summary.py
  tests/sentry/seer/autofix/test_issue_summary.py
Labels: Scope: Backend

#98834 feat(aci): Add check-ins table to cron monitor details page
  static/app/views/alerts/rules/crons/details.tsx
  static/app/views/detectors/components/details/cron/index.spec.tsx
  static/app/views/detectors/components/details/cron/index.tsx
  static/app/views/detectors/detail.spec.tsx
  static/app/views/insights/crons/components/monitorCheckIns.tsx
  static/app/views/insights/crons/components/monitorQuickStartGuide.tsx
  static/app/views/insights/crons/components/onboarding.tsx
Labels: Scope: Frontend

#98859 chore(pr comment reactions): exempt task from sampling
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#98770 fix(stories): hash scroll behavior
  static/app/stories/view/storyTableOfContents.tsx
Labels: Scope: Frontend

#98857 fix(preprod): build info can be missing for processing builds
  static/app/views/preprod/buildDetails/sidebar/buildDetailsSidebarAppInfo.tsx
  static/app/views/preprod/types/buildDetailsTypes.ts
  static/app/views/preprod/utils/labelUtils.tsx
Labels: Scope: Frontend

#98858 fix(preprod): make app fields nullable
  src/sentry/preprod/api/models/project_preprod_build_details_models.py
Labels: Scope: Backend

#98867 ref(uptime): Remove unused feature flags
  src/sentry/features/temporary.py
Labels: Scope: Backend

#98840 fix(prevent) attempt to fix redirection in prevent route
  static/app/routes.tsx
  static/app/views/prevent/index.tsx
Labels: Scope: Frontend

#98873 chore(explorer): Get more spans
  src/sentry/seer/explorer/index_data.py
Labels: Scope: Backend, Trigger: getsentry tests

#98850 ref: Move datascrubbing module to relay package
  src/sentry/core/endpoints/organization_details.py
  src/sentry/core/endpoints/project_details.py
  src/sentry/relay/config/__init__.py
  src/sentry/relay/datascrubbing.py
  src/sentry/tasks/store.py
  tests/sentry/relay/test_datascrubbing.py
Labels: Scope: Backend

#98797 fix(agents-insights): explore links
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/insights/agents/components/modelsTable.tsx
  static/app/views/insights/agents/components/tokenTypesWidget.tsx
  static/app/views/insights/common/components/tableCells/currencyCell.tsx
  static/app/views/insights/common/components/widgets/overviewAgentsDurationChartWidget.tsx
Labels: Scope: Frontend

#98888 feat(ai): Allow disabling model cost fetching task
  src/sentry/options/defaults.py
  src/sentry/relay/config/ai_model_costs.py
  src/sentry/tasks/ai_agent_monitoring.py
  tests/sentry/api/endpoints/test_relay_globalconfig_v3.py
Labels: Scope: Backend

#98592 ref(analytics): introduce EventEnvelope class to store timestamp and UUID of an event to not clash with any fields
  src/sentry/analytics/__init__.py
  src/sentry/analytics/base.py
  src/sentry/analytics/event.py
  src/sentry/analytics/pubsub.py
  src/sentry/testutils/helpers/analytics.py
  tests/sentry/analytics/test_base.py
  tests/sentry/analytics/test_event.py
  tests/sentry/incidents/test_logic.py
Labels: Scope: Backend

#98815 feat(deletions): Add IssuePlatform batching back
  src/sentry/deletions/defaults/group.py
  src/sentry/deletions/tasks/nodestore.py
  tests/sentry/deletions/tasks/test_nodestore.py
  tests/sentry/deletions/test_group.py
Labels: Scope: Backend

#98899 chore(deletions): Remove sequential approach to deleting events
  src/sentry/deletions/defaults/group.py
  src/sentry/options/defaults.py
  tests/sentry/deletions/tasks/test_groups.py
  tests/sentry/deletions/test_group.py
Labels: Scope: Backend

#97842 layout: add properties to container
  static/app/components/core/layout/container.tsx
  static/app/components/core/layout/styles.tsx
  static/app/components/core/text/text.mdx
  static/app/components/replays/table/replayTableColumns.tsx
  static/app/debug/notifications/components/debugNotificationsHeader.tsx
  static/app/stories/view/storyHeader.tsx
  static/app/views/detectors/components/details/metric/chart.tsx
  static/app/views/detectors/components/forms/metric/metricDetectorChart.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
  static/app/views/preprod/buildDetails/header/buildDetailsHeaderContent.tsx
  static/app/views/preprod/buildDetails/sidebar/buildDetailsSidebarAppInfo.tsx
  static/app/views/preprod/components/installModal.tsx
  static/gsApp/views/seerAutomation/seerAutomationProjectList.tsx
Labels: Scope: Frontend

#98848 fix(replays): Correct environment key extraction
  src/sentry/replays/usecases/ingest/__init__.py
Labels: Scope: Backend

#98905 text: remove usage of deprecated text component
  static/app/components/checkInTimeline/checkInTooltip.tsx
  static/app/components/modals/bulkEditMonitorsModal.tsx
  static/app/components/modals/redirectToProject.tsx
  static/app/views/alerts/rules/uptime/uptimeAlertForm.tsx
  static/app/views/insights/crons/components/detailsSidebar.tsx
  static/app/views/insights/crons/components/detailsTimeline.tsx
  static/app/views/insights/crons/components/monitorForm.tsx
Labels: Scope: Frontend

#98768 feat(explore): Use query params for spans group bys
  static/app/views/explore/contexts/pageParamsContext/index.tsx
  static/app/views/explore/hooks/useAddToDashboard.tsx
  static/app/views/explore/hooks/useExploreTimeseries.spec.tsx
  static/app/views/explore/hooks/useExploreTimeseries.tsx
  static/app/views/explore/hooks/useGroupByFields.tsx
  static/app/views/explore/hooks/useSortByFields.tsx
  static/app/views/explore/hooks/useTopEvents.tsx
  static/app/views/explore/logs/logsToolbar.spec.tsx
  static/app/views/explore/multiQueryMode/locationUtils.tsx
  static/app/views/explore/queryParams/context.tsx
  static/app/views/explore/spans/spansQueryParams.tsx
  static/app/views/explore/spans/spansTab.spec.tsx
  static/app/views/explore/tables/aggregatesTable.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  static/app/views/explore/toolbar/index.tsx
  static/app/views/explore/toolbar/toolbarGroupBy.tsx
  static/app/views/explore/toolbar/toolbarSaveAs.tsx
  static/app/views/explore/toolbar/toolbarSortBy.tsx
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#98904 perf(deletions): Optimize GroupHash queries by avoiding unnecessary JOIN
  src/sentry/tasks/delete_seer_grouping_records.py
Labels: Scope: Backend

#98600 stories: add insights vertical poc
  static/app/stories/view/storySearch.tsx
  static/app/stories/view/storySidebar.tsx
  static/app/stories/view/storyTree.tsx
  static/app/stories/view/useStoryRedirect.tsx
Labels: Scope: Frontend

#98855 feat(explore): Support managed fields to query params
  static/app/views/explore/logs/logsLocationQueryParamsProvider.tsx
  static/app/views/explore/logs/logsQueryParams.tsx
  static/app/views/explore/logs/logsStateQueryParamsProvider.tsx
  static/app/views/explore/queryParams/context.tsx
  static/app/views/explore/queryParams/managedFields.spec.tsx
  static/app/views/explore/queryParams/managedFields.tsx
  static/app/views/explore/queryParams/visualize.ts
  static/app/views/explore/spans/spansQueryParams.tsx
  static/app/views/explore/spans/spansQueryParamsProvider.tsx
Labels: Scope: Frontend

#98913 ref(scim): Move SCIM endpoints and tests to core folder
  src/sentry/api/serializers/models/organization_member/scim.py
  src/sentry/api/serializers/models/team.py
  src/sentry/api/urls.py
  src/sentry/core/endpoints/scim/__init__.py
  src/sentry/core/endpoints/scim/constants.py
  src/sentry/core/endpoints/scim/members.py
  src/sentry/core/endpoints/scim/schemas.py
  src/sentry/core/endpoints/scim/teams.py
  src/sentry/core/endpoints/scim/utils.py
  tests/sentry/core/endpoints/scim/__init__.py
  tests/sentry/core/endpoints/scim/test_scim_schema.py
  tests/sentry/core/endpoints/scim/test_scim_team_details.py
  tests/sentry/core/endpoints/scim/test_scim_team_index.py
  tests/sentry/core/endpoints/scim/test_scim_user_details.py
  tests/sentry/core/endpoints/scim/test_scim_user_index.py
Labels: Scope: Backend

#98845 feat(trace-eap-waterfall): Updating occurence id from /trace/ endpoint
  src/sentry/snuba/trace.py
  tests/snuba/api/endpoints/test_organization_trace.py
Labels: Scope: Backend

#98747 ref(discover): Remove router props from container routes
  static/app/routes.tsx
  static/app/views/discover/index.tsx
  static/app/views/explore/logs/index.tsx
  static/app/views/profiling/index.tsx
  static/app/views/releases/index.tsx
  static/app/views/traces/index.tsx
Labels: Scope: Frontend

#98832 fix(aci milestone 3): correctly update incident activity if group status doesn't change on new open period
  src/sentry/issues/priority.py
  src/sentry/workflow_engine/models/incident_groupopenperiod.py
  tests/sentry/issues/test_ingest_incident_integration.py
Labels: Scope: Backend

#98918 ref: remove unused import checker file and gitignore entries
  .gitignore
  src/sentry/__init__.py
  src/sentry/_importchecker.py
  tests/sentry/conf/types/test_imports.py
Labels: Scope: Backend

#98881 chore(ACI): Filter alert trigger logs to rules w/o a global snooze
  src/sentry/incidents/subscription_processor.py
  tests/sentry/incidents/subscription_processor/test_subscription_processor_workflow_engine.py
Labels: Scope: Backend

#98852 ref(replay): use timestamp_ms in trace connected IP query
  src/sentry/replays/usecases/summarize.py
Labels: Scope: Backend

#98769 fix(replay): add env to selector endpoint validator
  src/sentry/replays/validators.py
Labels: Scope: Backend

#98928 fix(groupingInfo): Fix feedback button loading outside container.
  static/app/components/events/groupingInfo/groupingInfo.tsx
Labels: Scope: Frontend

#98774 feat(aci): Add transactions deprecation warnings
  static/app/views/detectors/components/details/metric/index.tsx
  static/app/views/detectors/components/details/metric/transactionsDatasetWarning.tsx
  static/app/views/detectors/components/forms/metric/metric.tsx
Labels: Scope: Frontend

#98883 fix(feedback): dont show missing spam evidence
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
Labels: Scope: Frontend

#98802 feat(performance): updates user issue endpoint to accept a trace id
  src/sentry/issues/endpoints/project_user_issue.py
  tests/sentry/issues/endpoints/test_project_user_issue.py
Labels: Scope: Backend

#98931 fix(checkout v3): Don't show Seer categories in reserved diff
  static/gsApp/views/amCheckout/cartDiff.tsx
Labels: Scope: Frontend

#98772 feat(ui): Prevent "undo" toast with no undo callback
  static/app/actionCreators/indicator.tsx
  static/app/components/forms/formIndicators.tsx
Labels: Scope: Frontend

#98910 feat(uptime): Add avg duration metrics
  static/app/views/alerts/rules/uptime/detailsSidebar.tsx
  static/app/views/alerts/rules/uptime/types.tsx
  static/app/views/insights/uptime/components/duration.spec.tsx
  static/app/views/insights/uptime/components/duration.tsx
  static/app/views/insights/uptime/components/overviewTimeline/overviewRow.tsx
  tests/js/fixtures/uptimeSummary.ts
Labels: Scope: Frontend

#98872 chore(aci): Make workflow_engine.buffer.use_new_buffer permanently True
  .vscode/settings.json
  src/sentry/options/defaults.py
  src/sentry/workflow_engine/buffer/__init__.py
  tests/sentry/workflow_engine/processors/test_workflow.py
  tests/sentry/workflow_engine/tasks/test_delayed_workflows.py
  tests/sentry/workflow_engine/test_integration.py
Labels: Scope: Backend

#98941 ref(ui): Remove iconSize from CopyToClipboardButton
  static/app/components/copyToClipboardButton.stories.tsx
  static/app/components/copyToClipboardButton.tsx
  static/app/components/events/interfaces/frame/stacktraceLinkModal.tsx
  static/app/components/replays/diff/replayTextDiff.tsx
  static/app/components/structuredEventData/index.tsx
  static/app/components/textCopyInput.tsx
  static/app/components/version.tsx
  static/app/components/versionHoverCard.tsx
  static/app/views/discover/table/quickContext/quickContextHovercard.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/eapSections/description.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/sections/description.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/transaction/sections/highlights.tsx
  static/app/views/performance/newTraceDetails/traceHeader/breadcrumbs.tsx
  static/app/views/settings/project/projectToolbar.tsx
  static/app/views/settings/projectProguard/associations.tsx
Labels: Scope: Frontend
