Repository getsentry/sentry, pull requests merged in 2025-05, with the labels that each got.

#90716 fix(releases): Fix finalize button size
  static/app/views/releases/detail/overview/sidebar/projectReleaseDetails.tsx
Labels: Scope: Frontend

#90696 feat(insights): eap starred transaction column updates
  static/app/views/insights/common/utils/useStarredSegment.tsx
  static/app/views/insights/pages/backend/backendTable.tsx
  static/app/views/insights/pages/frontend/frontendOverviewTable.tsx
  static/app/views/insights/pages/mobile/mobileOverviewTable.tsx
Labels: Scope: Frontend

#90429 chore(ci): Handle artifacts should continue on error
  .github/actions/artifacts/action.yml
Labels: Scope: Backend

#90722 chore(perf-issues): Increase rollout to 0.5 for HTTP Detectors
  src/sentry/options/defaults.py
Labels: Scope: Backend

#90721 fix(api): Make trace item details rename type=double to type=float
  src/sentry/api/endpoints/project_trace_item_details.py
Labels: Scope: Backend

#90705 fix(taskworker) Update cluster_projects so it can not use pickle
  src/sentry/ingest/transaction_clusterer/tasks.py
  tests/sentry/ingest/test_transaction_clusterer.py
Labels: Scope: Backend

#90727 feat(explore): Add pagination analytics
  static/app/utils/analytics/tracingEventMap.tsx
  static/app/views/explore/hooks/usePaginationAnalytics.tsx
  static/app/views/explore/tables/aggregatesTable.tsx
  static/app/views/explore/tables/spansTable.tsx
  static/app/views/explore/tables/tracesTable/index.tsx
Labels: Scope: Frontend

#90725 feat(insights): add user column to overview pages, remove slow op charts
  static/app/views/insights/common/components/tableCells/renderHeadCell.tsx
  static/app/views/insights/pages/backend/backendOverviewPage.tsx
  static/app/views/insights/pages/backend/backendTable.tsx
  static/app/views/insights/pages/frontend/frontendOverviewPage.tsx
  static/app/views/insights/pages/frontend/frontendOverviewTable.tsx
  static/app/views/insights/pages/mobile/mobileOverviewPage.tsx
  static/app/views/insights/pages/mobile/mobileOverviewTable.tsx
  static/app/views/insights/types.tsx
Labels: Scope: Frontend

#90255 feat(ACI): Create Detector serializer for old rule endpoints
  src/sentry/incidents/endpoints/serializers/workflow_engine_detector.py
  tests/sentry/incidents/serializers/test_workflow_engine_detector.py
  tests/sentry/notifications/notification_action/test_metric_alert_registry_handlers.py
Labels: Scope: Backend

#90521 drop(munging): Drop original Java munging logic
  src/sentry/features/temporary.py
  src/sentry/integrations/utils/commit_context.py
  src/sentry/integrations/utils/stacktrace_link.py
  src/sentry/issues/auto_source_code_config/code_mapping.py
  src/sentry/utils/event_frames.py
  tests/sentry/issues/auto_source_code_config/test_code_mapping.py
  tests/sentry/issues/endpoints/test_project_stacktrace_link.py
  tests/sentry/ownership/test_grammar.py
  tests/sentry/utils/test_event_frames.py
Labels: Scope: Backend

#86639 feat(bitbucket-server): CODEOWNERS support and stacktrace linking
  src/sentry/integrations/bitbucket_server/client.py
  src/sentry/integrations/bitbucket_server/integration.py
  src/sentry/integrations/bitbucket_server/utils.py
  src/sentry/models/commitfilechange.py
  tests/sentry/integrations/bitbucket_server/test_client.py
  tests/sentry/integrations/bitbucket_server/test_integration.py
Labels: Scope: Backend, Trigger: getsentry tests

#90739 fix(saved-searches): Fix saved search sidebar button styles
  static/app/views/issueList/savedIssueSearches.tsx
Labels: Scope: Frontend

#90734 fix(ui): optIn banner styling in chonk
  static/app/components/sidebar/help.tsx
  static/app/views/nav/optInBanner.tsx
Labels: Scope: Frontend

#90714 ref(workflow_engine): Add indices to the alert_rule_id and rule_id fields on the AlertRuleWorkflow table
  migrations_lockfile.txt
  src/sentry/workflow_engine/migrations/0053_add_legacy_rule_indices.py
  src/sentry/workflow_engine/models/alertrule_workflow.py
Labels: Scope: Backend

#90654 fix(ui): give focused button in the group a higher zIndex
  static/app/components/organizations/pageFilterBar.tsx
Labels: Scope: Frontend

#90249 feat(gitlab): Suspect PR comments - Backend
  src/sentry/api/endpoints/organization_details.py
  src/sentry/api/serializers/models/organization.py
  src/sentry/apidocs/examples/organization_examples.py
  src/sentry/constants.py
  src/sentry/integrations/github/client.py
  src/sentry/integrations/gitlab/client.py
  src/sentry/integrations/gitlab/integration.py
  src/sentry/integrations/gitlab/utils.py
  src/sentry/integrations/source_code_management/commit_context.py
  src/sentry/snuba/referrer.py
  src/sentry/tasks/commit_context.py
  src/sentry/types/referrer_ids.py
  tests/sentry/integrations/github/test_client.py
  tests/sentry/integrations/gitlab/tasks/test_pr_comment.py
  tests/sentry/integrations/gitlab/test_client.py
Labels: Scope: Backend, Trigger: getsentry tests

#90741 feat(eap-spans): add tpm function
  src/sentry/search/eap/spans/formulas.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#90704 feat(eap): Default unspecified sampling mode to high accuracy
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
  src/sentry/search/eap/constants.py
  src/sentry/search/eap/utils.py
  src/sentry/search/events/types.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
Labels: Scope: Backend

#90700 ref(ourlogs): Change default (24h) and max (14d) period for logs
  static/app/views/explore/logs/index.tsx
  static/app/views/explore/logs/logsTab.tsx
  static/app/views/explore/logs/utils.tsx
  static/app/views/explore/spans/spansTab.tsx
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#90731 fix(taskworker) Switch cluster_projects to use project_ids
  src/sentry/ingest/transaction_clusterer/datasource/redis.py
  src/sentry/ingest/transaction_clusterer/tasks.py
  tests/sentry/ingest/test_transaction_clusterer.py
Labels: Scope: Backend

#90181 fix(autofix): Use org-prefixed urls for autofix
  static/app/components/events/autofix/autofixChanges.analytics.spec.tsx
  static/app/components/events/autofix/autofixChanges.tsx
  static/app/components/events/autofix/autofixDiff.spec.tsx
  static/app/components/events/autofix/autofixDiff.tsx
  static/app/components/events/autofix/autofixHighlightPopup.tsx
  static/app/components/events/autofix/autofixInsightCards.spec.tsx
  static/app/components/events/autofix/autofixInsightCards.tsx
  static/app/components/events/autofix/autofixOutputStream.spec.tsx
  static/app/components/events/autofix/autofixOutputStream.tsx
  static/app/components/events/autofix/autofixRootCause.spec.tsx
  static/app/components/events/autofix/autofixRootCause.tsx
  static/app/components/events/autofix/autofixSetupWriteAccessModal.spec.tsx
  static/app/components/events/autofix/autofixSolution.spec.tsx
  static/app/components/events/autofix/autofixSolution.tsx
  static/app/components/events/autofix/autofixThumbsUpDownButtons.tsx
  static/app/components/events/autofix/useAutofix.tsx
  static/app/components/events/autofix/useAutofixSetup.tsx
  static/app/components/group/groupSummary.spec.tsx
  static/app/components/group/groupSummary.tsx
  static/app/views/issueDetails/groupSidebar.spec.tsx
  static/app/views/issueDetails/streamline/groupDetailsLayout.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/seerDrawer.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/seerSection.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/sidebar.spec.tsx
  static/gsApp/components/ai/AiSetupDataConsent.tsx
  static/gsApp/components/ai/aiSetupDataConsent.spec.tsx
Labels: Scope: Frontend

#90717 ref(github): Open PR Comment Workflow
  src/sentry/integrations/github/integration.py
  src/sentry/integrations/github/tasks/open_pr_comment.py
  src/sentry/integrations/github/tasks/utils.py
  src/sentry/integrations/source_code_management/commit_context.py
  src/sentry/seer/fetch_issues/fetch_issues.py
  tests/sentry/integrations/github/tasks/test_open_pr_comment.py
  tests/sentry/integrations/github/tasks/test_pr_comment.py
Labels: Scope: Backend, Trigger: getsentry tests

#90736 feat(insights): add perf score column to frontend overview
  static/app/utils/discover/fieldRenderers.tsx
  static/app/views/insights/common/components/tableCells/renderHeadCell.tsx
  static/app/views/insights/pages/frontend/frontendOverviewPage.tsx
  static/app/views/insights/pages/frontend/frontendOverviewTable.tsx
  static/app/views/insights/pages/frontend/settings.ts
  static/app/views/insights/types.tsx
Labels: Scope: Frontend

#90730 chore(issues): Remove streamline experiment
  pyproject.toml
  src/sentry/api/endpoints/organization_index.py
  src/sentry/hybridcloud/services/region_organization_provisioning/impl.py
  src/sentry/issues/streamline.py
  src/sentry/options/defaults.py
  tests/sentry/api/endpoints/test_organization_index.py
  tests/sentry/hybridcloud/services/test_region_organization_provisioning.py
Labels: Scope: Backend

#90428 feat(releases): Release links that use hovercard will open in drawer
  static/app/components/version.tsx
  static/app/views/insights/common/utils/useSamplesDrawer.tsx
  static/app/views/nav/secondary/sections/insights/insightsSecondaryNav.tsx
  static/app/views/organizationLayout/index.tsx
  static/app/views/releases/drawer/useReleasesDrawer.tsx
  static/app/views/releases/utils/pathnames.tsx
Labels: Scope: Frontend

#90744 chore(autofix): Restyle insight cards
  static/app/components/events/autofix/autofixInsightCards.tsx
  static/app/components/events/autofix/autofixOutputStream.tsx
  static/app/components/events/autofix/autofixSteps.tsx
Labels: Scope: Frontend

#90609 ref(shared-views): Add feature flag check to prefersStackedNav checks
  static/app/types/user.tsx
  static/app/utils/profiling/routes.tsx
  static/app/views/admin/adminLayout.tsx
  static/app/views/alerts/pathnames.tsx
  static/app/views/dashboards/manage/index.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.tsx
  static/app/views/discover/pathnames.tsx
  static/app/views/explore/content.tsx
  static/app/views/explore/logs/index.tsx
  static/app/views/explore/multiQueryMode/index.tsx
  static/app/views/feedback/feedbackListPage.tsx
  static/app/views/issueDetails/streamline/eventDetails.tsx
  static/app/views/issueList/index.tsx
  static/app/views/issueList/leftNavViewsHeader.tsx
  static/app/views/issueList/overview.tsx
  static/app/views/issueList/savedIssueSearches.tsx
  static/app/views/nav/prefersStackedNav.tsx
  static/app/views/nav/usePrefersStackedNav.tsx
  static/app/views/nav/useRedirectNavV2Routes.tsx
  static/app/views/organizationLayout/index.tsx
  static/app/views/organizationStats/pathname.tsx
  static/app/views/performance/traceDetails/utils.tsx
  static/app/views/profiling/content.tsx
  static/app/views/projectDetail/projectDetail.tsx
  static/app/views/projects/pathname.tsx
  static/app/views/projectsDashboard/index.tsx
  static/app/views/releases/components/header.tsx
  static/app/views/releases/utils/pathnames.tsx
  static/app/views/replays/pathnames.tsx
  static/app/views/settings/account/accountSettingsLayout.tsx
  static/app/views/settings/account/navigationConfiguration.tsx
  static/app/views/settings/components/settingsNavigation.tsx
  static/app/views/settings/organization/navigationConfiguration.tsx
  static/app/views/settings/organization/organizationSettingsLayout.tsx
  static/app/views/settings/project/projectSettingsLayout.tsx
  static/app/views/settings/settingsIndex.tsx
  static/app/views/traces/pathnames.tsx
  static/app/views/userFeedback/pathnames.tsx
  static/gsApp/components/gsBanner.tsx
  static/gsApp/components/navBillingStatus.tsx
  static/gsApp/components/trialStartedSidebarItem.tsx
  static/gsApp/components/tryBusinessSidebarItem.tsx
  static/gsApp/hooks/disabledMemberView.tsx
Labels: Scope: Frontend

#90753 fix(explore): Pass type properly for analytics
  static/app/views/explore/hooks/usePaginationAnalytics.tsx
  static/app/views/explore/tables/aggregatesTable.tsx
  static/app/views/explore/tables/spansTable.tsx
  static/app/views/explore/tables/tracesTable/index.tsx
Labels: Scope: Frontend

#90340 feat(taskworker): Make ingest errors taskworker compatible
  src/sentry/conf/server.py
  src/sentry/options/defaults.py
  src/sentry/tasks/base.py
  src/sentry/tasks/post_process.py
  src/sentry/tasks/store.py
  src/sentry/taskworker/namespaces.py
Labels: Scope: Backend

#90695 chore(shared-views): Swap out issue-view-sharing flag for enforce-stacked-navigation
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/index.spec.tsx
  static/app/views/issueList/index.tsx
  static/app/views/issueList/issueViews/issueViewsList/issueViewsList.spec.tsx
  static/app/views/issueList/issueViews/issueViewsList/issueViewsList.tsx
  static/app/views/issueList/leftNavViewsHeader.spec.tsx
  static/app/views/issueList/leftNavViewsHeader.tsx
  static/app/views/issueList/overview.tsx
  static/app/views/nav/secondary/sections/issues/issueViews/issueViewAddViewButton.tsx
  static/app/views/nav/secondary/sections/issues/issueViews/issueViewNavItemContent.tsx
  static/app/views/nav/secondary/sections/issues/issueViews/issueViewNavItems.tsx
Labels: Scope: Frontend

#90748 feat(trace-explorer-ai): Add setup endpoint to create LLM state
  src/sentry/api/endpoints/trace_explorer_ai_setup.py
  src/sentry/api/urls.py
Labels: Scope: Backend

#90750 feat(ourlogs): Lock columns to 1 in trace view
  static/app/views/explore/components/traceItemAttributes/attributesTree.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/span/index.tsx
Labels: Scope: Frontend

#90752 feat(insights): add percentile_if and sum_if functions
  src/sentry/search/eap/spans/aggregates.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#90711 feat(explore): Use trace item search query builder
  static/app/components/performance/spanSearchQueryBuilder.tsx
  static/app/views/alerts/rules/metric/eapField.spec.tsx
  static/app/views/alerts/rules/metric/ruleConditionsForm.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/spansSearchBar.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/groupBySelector.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/sortBySelector.spec.tsx
  static/app/views/dashboards/widgetBuilder/widgetBuilderSortBy.spec.tsx
  static/app/views/explore/components/traceItemSearchQueryBuilder.tsx
  static/app/views/explore/constants.tsx
  static/app/views/explore/contexts/spanTagsContext.tsx
  static/app/views/explore/contexts/traceItemAttributeContext.tsx
  static/app/views/explore/hooks/useSortByFields.spec.tsx
  static/app/views/explore/hooks/useTraceItemAttributeKeys.spec.tsx
  static/app/views/explore/hooks/useTraceItemAttributeKeys.tsx
  static/app/views/explore/hooks/useTraceItemAttributeValues.spec.tsx
  static/app/views/explore/hooks/useTraceItemAttributeValues.tsx
  static/app/views/explore/hooks/useVisualizeFields.spec.tsx
  static/app/views/explore/multiQueryMode/content.spec.tsx
  static/app/views/explore/spans/spansTab.spec.tsx
  static/app/views/performance/newTraceDetails/traceDrawer/details/styles.tsx
Labels: Scope: Frontend

#90760 feat(ai): Add an endpoint which lets you convert freetext into trace explorer parameters
  src/sentry/api/endpoints/trace_explorer_ai_query.py
  src/sentry/api/urls.py
Labels: Scope: Backend

#90766 feat(taskworker): Make ingest transactions taskworker compatible
  src/sentry/options/defaults.py
  src/sentry/tasks/store.py
  src/sentry/taskworker/namespaces.py
Labels: Scope: Backend

#90759 feat(eap-spans): create failure_rate_if function
  src/sentry/search/eap/spans/formulas.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#90758 ref: fix organization_stats_v2 test flakiness
  src/sentry/testutils/helpers/datetime.py
  tests/snuba/api/endpoints/test_organization_stats_summary.py
  tests/snuba/api/endpoints/test_organization_stats_v2.py
Labels: Scope: Backend

#90733 ref(flags): add analytic to track read more clicks in CTA
  static/app/components/events/featureFlags/featureFlagInlineCTA.tsx
  static/app/utils/analytics/featureFlagAnalyticsEvents.tsx
Labels: Scope: Frontend

#90747 feat(autofix): Scroll to section when clicking on sidebar cards
  static/app/components/events/autofix/autofixSteps.tsx
  static/app/components/group/groupSummaryWithAutofix.tsx
  static/app/views/issueDetails/streamline/sidebar/seerDrawer.tsx
Labels: Scope: Frontend

#90434 ref(uptime): Read uptime_status from uptime_subscription
  src/sentry/incidents/endpoints/organization_alert_rule_index.py
  src/sentry/testutils/factories.py
  src/sentry/testutils/fixtures.py
  src/sentry/uptime/consumers/results_consumer.py
  src/sentry/uptime/endpoints/serializers.py
  src/sentry/uptime/subscriptions/subscriptions.py
  tests/sentry/uptime/consumers/test_results_consumer.py
  tests/sentry/uptime/endpoints/test_serializers.py
  tests/sentry/uptime/subscriptions/test_subscriptions.py
  tests/sentry/uptime/subscriptions/test_tasks.py
Labels: Scope: Backend

#90772 fix(explore): Add back is_transaction
  static/app/views/explore/constants.tsx
Labels: Scope: Frontend

#90777 fix(ourlogs): Fix trace id link in attributes being broken
  static/app/views/explore/logs/logsTableRow.tsx
Labels: Scope: Frontend

#90743 fix(aci): Add open periods to project deletion
  src/sentry/deletions/defaults/project.py
  tests/sentry/deletions/test_project.py
Labels: Scope: Backend

#90781 fix(releases): Fix Release Drawer on reload
  static/app/views/organizationLayout/index.tsx
Labels: Scope: Frontend

#90770 fix(shared-views): Center star and ellipsis buttons
  static/app/views/issueList/leftNavViewsHeader.tsx
Labels: Scope: Frontend

#90773 style(flags): fix alignment on ff section in issues
  static/app/components/events/featureFlags/featureFlagDrawer.tsx
Labels: Scope: Frontend

#90749 feat(ui): Add `error.cause` to `<ErrorHandler>`
  static/app/components/errorBoundary.tsx
  static/app/components/lazyLoad.tsx
  static/app/utils/errorHandler.tsx
Labels: Scope: Frontend

#90771 feat(ui): Fix `/settings/` when user is not part of any orgs
  static/app/views/settings/settingsIndex.tsx
Labels: Scope: Frontend

#90769 ref(issue-types): Remove unused issue types from frontend
  static/app/components/events/eventStatisticalDetector/eventRegressionSummary.tsx
  static/app/components/events/eventStatisticalDetector/eventThroughput.tsx
  static/app/components/events/interfaces/performance/spanEvidenceKeyValueList.tsx
  static/app/types/group.tsx
  static/app/utils/issueTypeConfig/performanceConfig.tsx
  static/app/utils/issueTypeConfig/performanceRegressionConfig.tsx
  static/app/utils/issueTypeConfig/responsivenessConfig.tsx
  static/app/views/issueDetails/allEventsTable.tsx
  static/app/views/issueDetails/groupDetails.tsx
  static/app/views/issueDetails/streamline/eventList.tsx
Labels: Scope: Frontend

#90790 chore(alerts): Add more logging in fire_rules
  src/sentry/rules/processing/delayed_processing.py
Labels: Scope: Backend

#90783 fix(insights): Fix prevent same chart from being picked twice in Session Health when names have changed
  static/app/views/insights/sessions/components/chartMap.tsx
  static/app/views/insights/sessions/components/chartPlacement.tsx
Labels: Scope: Frontend

#90728 ref(discover): Move views/discover/results.tsx direct deps into their own folder
  static/app/components/createAlertButton.spec.tsx
  static/app/views/alerts/rules/metric/incompatibleAlertQuery.spec.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/eventsSearchBar.tsx
  static/app/views/discover/eventDetails/index.spec.tsx
  static/app/views/discover/homepage.spec.tsx
  static/app/views/discover/results.spec.tsx
  static/app/views/discover/results.tsx
  static/app/views/discover/results/chartFooter.spec.tsx
  static/app/views/discover/results/chartFooter.tsx
  static/app/views/discover/results/data.tsx
  static/app/views/discover/results/resultsChart.spec.tsx
  static/app/views/discover/results/resultsChart.tsx
  static/app/views/discover/results/resultsHeader.tsx
  static/app/views/discover/results/resultsSearchQueryBuilder.tsx
  static/app/views/discover/results/sampleDataAlert.spec.tsx
  static/app/views/discover/results/sampleDataAlert.tsx
  static/app/views/discover/results/tags.spec.tsx
  static/app/views/discover/results/tags.tsx
  static/app/views/discover/savedQuery/index.spec.tsx
  static/app/views/discover/savedQuery/index.tsx
  static/app/views/discover/savedQuery/utils.spec.tsx
  static/app/views/discover/utils.tsx
  static/app/views/performance/traceDetails/content.spec.tsx
  static/app/views/performance/traceDetails/newTraceDetailsContent.tsx
  static/app/views/performance/transactionSummary/transactionOverview/content.tsx
  static/app/views/replays/detail/trace/trace.spec.tsx
Labels: Scope: Frontend

#90787 feat(ui): Force type declaration on let variables
  eslint.config.mjs
  static/app/utils/replays/replayReader.tsx
  static/app/views/dashboards/widgetCard/spansWidgetQueries.tsx
  static/app/views/discover/table/queryField.tsx
  static/app/views/explore/charts/widgetExtrapolationFooter.tsx
  static/app/views/explore/components/schemaHints/schemaHintsList.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  static/app/views/insights/sessions/queries/useOrganizationReleases.tsx
  static/app/views/organizationStats/usageStatsOrg.tsx
  static/app/views/performance/newTraceDetails/traceActionsMenu.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/releases/drawer/newIssues.tsx
  static/gsApp/views/amCheckout/steps/reviewAndConfirm.tsx
  static/gsApp/views/spendAllocations/index.tsx
Labels: Scope: Frontend

#90793 ref(workflow_engine): Rename the StatefulDetectorHandler to StatefulGroupingDetectorHandler
  src/sentry/incidents/grouptype.py
  src/sentry/workflow_engine/handlers/detector/__init__.py
  src/sentry/workflow_engine/handlers/detector/stateful.py
  tests/sentry/workflow_engine/handlers/detector/test_base.py
Labels: Scope: Backend

#90677 feat(seer): Add seer automation fields to Group
  migrations_lockfile.txt
  src/sentry/api/endpoints/group_autofix_update.py
  src/sentry/migrations/0879_add_seer_fields_to_group.py
  src/sentry/models/group.py
  src/sentry/seer/autofix.py
  src/sentry/seer/issue_summary.py
  tests/sentry/api/endpoints/test_group_autofix_update.py
  tests/sentry/migrations/test_0879_add_seer_fields_to_group.py
  tests/sentry/seer/test_autofix.py
  tests/sentry/seer/test_issue_summary.py
Labels: Scope: Backend

#90789 feat(releases): Add new resizable drawer for Releases Drawer
  static/app/components/globalDrawer/index.tsx
  static/app/views/releases/drawer/useReleasesDrawer.tsx
Labels: Scope: Frontend

#90795 fix(shared-views): Fix issue view sharing check in some places
  static/app/views/issueList/filters.tsx
  static/app/views/issueList/index.tsx
  static/app/views/issueList/issueSearchWithSavedSearches.tsx
  static/app/views/issueList/savedIssueSearches.tsx
  static/app/views/nav/usePrefersStackedNav.tsx
Labels: Scope: Frontend

#90571 feat(laravel-nextjs-insights): Show release bubbles
  static/app/views/insights/pages/platform/laravel/cachesWidget.tsx
  static/app/views/insights/pages/platform/laravel/index.tsx
  static/app/views/insights/pages/platform/laravel/jobsWidget.tsx
  static/app/views/insights/pages/platform/laravel/queriesWidget.tsx
  static/app/views/insights/pages/platform/nextjs/index.tsx
  static/app/views/insights/pages/platform/nextjs/slowSsrWidget.tsx
  static/app/views/insights/pages/platform/shared/durationWidget.tsx
  static/app/views/insights/pages/platform/shared/getReleaseBubbleProps.tsx
  static/app/views/insights/pages/platform/shared/trafficWidget.tsx
Labels: Scope: Frontend

#90655 fix(insights): Improving recommended issues header optics
  static/app/views/insights/pages/platform/laravel/index.tsx
  static/app/views/insights/pages/platform/nextjs/index.tsx
  static/app/views/insights/pages/platform/shared/issuesWidget.tsx
Labels: Scope: Frontend

#90774 typing(deletion): Stronger typing
  pyproject.toml
  src/sentry/api/helpers/group_index/delete.py
  src/sentry/issues/endpoints/group_details.py
Labels: Scope: Backend

#90802 fix(explore): Update progressive loading message copy
  static/app/views/explore/charts/index.tsx
Labels: Scope: Frontend

#90809 feat(deletion): Create audit entries get created earlier
  src/sentry/api/helpers/group_index/delete.py
  tests/snuba/api/endpoints/test_project_group_index.py
Labels: Scope: Backend

#90785 fix(taskworker) Remove pickle parameters from delete_groups
  src/sentry/api/helpers/group_index/delete.py
  src/sentry/eventstream/snuba.py
  tests/sentry/issues/endpoints/test_organization_group_index.py
Labels: Scope: Backend

#90754 chore(taskworker) Remove projects parmaeter from cluster_projects
  src/sentry/ingest/transaction_clusterer/tasks.py
Labels: Scope: Backend

#90811 feat(deletions): Delete fewer group history at a time
  src/sentry/deletions/defaults/grouphistory.py
Labels: Scope: Backend

#90723 chore(perf-issues): Increase rollout to 0.75 for HTTP Detectors
  src/sentry/options/defaults.py
Labels: Scope: Backend

#90808 chore(eap): Use the right entity to insert spans
  src/sentry/testutils/cases.py
Labels: Scope: Backend

#90794 feat: Track alert misfires on EAP
  src/sentry/discover/compare_timeseries.py
  tests/sentry/discover/test_compare_timeseries.py
Labels: Scope: Backend

#90815 feat(insights): use conditional functions frontend overview
  static/app/views/insights/common/components/tableCells/renderHeadCell.tsx
  static/app/views/insights/constants.tsx
  static/app/views/insights/pages/frontend/frontendOverviewPage.tsx
  static/app/views/insights/pages/frontend/frontendOverviewTable.tsx
  static/app/views/insights/pages/frontend/settings.ts
  static/app/views/insights/types.tsx
Labels: Scope: Frontend

#90817 OPS-6010: bump bigtable > 2.27
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#90788 feat(replay): Capture replays for users without org in context
  static/gsApp/components/organizationHeader.tsx
  static/gsApp/utils/useReplayInit.tsx
Labels: Scope: Frontend

#90821 feat(insights): set sampling mode widget queries
  static/app/views/performance/landing/widgets/widgets/lineChartListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/mobileReleaseComparisonListWidget.tsx
  static/app/views/performance/landing/widgets/widgets/settings.ts
  static/app/views/performance/landing/widgets/widgets/singleFieldAreaWidget.tsx
Labels: Scope: Frontend

#90797 feat(issue-taxonomy): Update taxonomy labels
  static/app/routes.tsx
  static/app/views/issueList/pages/errorsOutages.tsx
  static/app/views/issueList/pages/regressions.tsx
  static/app/views/issueList/pages/warnings.tsx
  static/app/views/issueList/taxonomies.tsx
  static/app/views/nav/secondary/sections/issues/issuesSecondaryNav.tsx
Labels: Scope: Frontend

#90778 feat(ourlogs): Change period limits based on plan
  static/app/views/explore/logs/index.tsx
  static/app/views/explore/logs/utils.tsx
Labels: Scope: Frontend

#90779 fix(taskworker) Fix more pickle parameter usage in send_async_notification
  src/sentry/notifications/utils/tasks.py
  tests/sentry/notifications/utils/test_tasks.py
Labels: Scope: Backend

#90776 fix(taskworker) Remove pickle parameters from relocation tasks
  src/sentry/relocation/api/endpoints/index.py
  src/sentry/relocation/tasks/process.py
  src/sentry/relocation/utils.py
  tests/sentry/relocation/api/endpoints/test_index.py
  tests/sentry/relocation/tasks/test_process.py
  tests/sentry/relocation/test_utils.py
Labels: Scope: Backend

#90826 fix(aci): optimize querying to orphaned AlertRuleWorkflows
  src/sentry/workflow_engine/migrations/0050_remove_orphaned_rule_workflows.py
Labels: Scope: Backend

#90742 feat(group_deletion): Ask Seer to only delete error ids
  src/sentry/api/helpers/group_index/delete.py
Labels: Scope: Backend

#90827 ref: add migration to widen created_by_id in OrgAuthToken
  migrations_lockfile.txt
  src/sentry/migrations/0880_orgauthtoken_bigint.py
Labels: Scope: Backend

#90825 feat(billing): Upgrade to Relay 0.9.9
  requirements-base.txt
  requirements-dev-frozen.txt
  requirements-frozen.txt
Labels: Scope: Backend

#90837 chore(explore): Move explore spans content into spans folder
  static/app/views/explore/spans/content.tsx
  static/app/views/traces/content.tsx
Labels: Scope: Frontend

#90268 ✨ feat(aci): refactor issue digests for ACI
  src/sentry/digests/notifications.py
  src/sentry/digests/types.py
  src/sentry/notifications/notifications/digest.py
  tests/sentry/digests/test_utilities.py
Labels: Scope: Backend

#90796 fix(aci milestone 3): clean up orphaned objects from workflow engine
  migrations_lockfile.txt
  src/sentry/workflow_engine/migrations/0054_clean_up_orphaned_metric_alert_objects.py
  tests/sentry/workflow_engine/migrations/test_0054_clean_up_orphaned_metric_alert_objects.py
Labels: Scope: Backend

#90746 🐛 fix(slack): fix slack metric alert threading behavior
  src/sentry/integrations/slack/utils/notifications.py
  tests/sentry/incidents/action_handlers/test_slack.py
Labels: Scope: Backend

#90676 linkbutton: links cannot be disabled
  static/app/components/core/button/linkButton.tsx
  static/app/components/modals/widgetViewerModal.spec.tsx
  static/app/components/noProjectMessage.spec.tsx
  static/app/components/updatedEmptyState.spec.tsx
  static/app/views/alerts/list/rules/alertRulesList.spec.tsx
  static/app/views/alerts/rules/issue/details/ruleDetails.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/seerSectionCtaButton.tsx
  static/app/views/performance/otlp/overviewSpansTable.tsx
  static/app/views/projectDetail/projectTeamAccess.spec.tsx
  static/app/views/settings/organizationIntegrations/integrationDetailedView.spec.tsx
  static/app/views/traces/fieldRenderers.spec.tsx
  static/gsApp/hooks/orgStatsProfilingBanner.tsx
Labels: Scope: Frontend

#90840 fix(trace): Handle falsey parent span in get trace rpc
  src/sentry/api/endpoints/organization_trace.py
Labels: Scope: Backend

#90813 feat(story): add story for SearchQueryBuilderProvider
  static/app/components/searchQueryBuilder/index.stories.tsx
Labels: Scope: Frontend

#90557 ref(grouping): Add split enhancements to enhancement bases
  src/sentry/grouping/enhancer/__init__.py
  src/sentry/grouping/enhancer/rules.py
  tests/sentry/grouping/test_enhancer.py
Labels: Scope: Backend

#90818 feat(ui): Fix error in `SeerDrawer` when moving to settings
  static/app/views/issueDetails/streamline/sidebar/seerDrawer.tsx
Labels: Scope: Frontend

#90844 fix(aci): optimize query for unmigrated Rules in backfill migration
  src/sentry/workflow_engine/migrations/0051_migrate_remaining_issue_alerts.py
Labels: Scope: Backend

#90845 fix(dashboards): Updates edit permissions check
  static/app/views/dashboards/controls.tsx
  static/app/views/dashboards/detail.tsx
Labels: Scope: Frontend

#90545 chore(billing): Reduce hardcoding of data categories in ondemand budget utility functions
  static/gsApp/views/onDemandBudgets/utils.tsx
Labels: Scope: Frontend

#90847 fix(aci): Add other resolution activities to open period backfill
  src/sentry/migrations/0878_backfill_open_periods.py
Labels: Scope: Backend

#90849 fix(quota-exceeded-banner): Prevent infinite useEffect loop when quota banner is opened automatically
  static/gsApp/components/navBillingStatus.tsx
Labels: Scope: Frontend

#90850 fix(aci milestone 3): remove backfill key from migration to migrate rules with errors
  src/sentry/workflow_engine/migrations/0052_migrate_errored_metric_alerts.py
  tests/sentry/workflow_engine/migrations/test_0052_migrate_errored_metric_alerts.py
Labels: Scope: Backend

#90854 tests(trace): Ensure no db access in thread pool in trace endpoint
  src/sentry/api/endpoints/organization_trace.py
Labels: Scope: Backend

#90830 feat(issue-taxonomy): Recategorize warning categories in frontend config
  static/app/types/group.tsx
  static/app/utils/issueTypeConfig/dbQueryConfig.tsx
  static/app/utils/issueTypeConfig/frontendConfig.tsx
  static/app/utils/issueTypeConfig/httpClientConfig.tsx
  static/app/utils/issueTypeConfig/index.tsx
  static/app/utils/issueTypeConfig/mobileConfig.tsx
Labels: Scope: Frontend

#90823 feat(explore): removes frontend hard coded prebuilt explore queries
  static/app/views/explore/savedQueries/prebuiltQueries.tsx
  static/app/views/nav/secondary/sections/explore/exploreSecondaryNav.spec.tsx
  static/app/views/nav/secondary/sections/explore/exploreSecondaryNav.tsx
Labels: Scope: Frontend

#90831 feat(explore): Expand hidden tokens in saved explore query params
  static/app/views/explore/savedQueries/exploreParams.tsx
Labels: Scope: Frontend

#90841 feat(explore): updates sort options and updates response types to closer reflect backend response
  static/app/views/explore/hooks/useGetSavedQueries.tsx
  static/app/views/explore/savedQueries/savedQueriesLandingContent.spec.tsx
  static/app/views/explore/savedQueries/savedQueriesLandingContent.tsx
  static/app/views/explore/savedQueries/savedQueriesTable.tsx
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#90672 feat/chonkUI/tokens graphics
  static/app/utils/theme/theme.chonk.tsx
  static/app/utils/theme/theme.tsx
Labels: Scope: Frontend

#90855 fix(aci): fixes to migrate remaining issue alerts
  src/sentry/workflow_engine/migrations/0051_migrate_remaining_issue_alerts.py
  tests/sentry/workflow_engine/migrations/test_0051_migrate_remaining_issue_alerts.py
Labels: Scope: Backend

#90859 feat(aci): Move alert_id to evidence data for metric issue poc
  src/sentry/incidents/utils/metric_issue_poc.py
Labels: Scope: Backend

#90836 chore(devservices): Bump devservices to 1.1.4
  requirements-dev-frozen.txt
  requirements-dev.txt
Labels: Scope: Backend

#90871 fix(aci): Minor fixes for the open period backfill
  src/sentry/migrations/0878_backfill_open_periods.py
Labels: Scope: Backend

#90667 button: separate href and props
  static/app/components/core/button/linkButton.tsx
  static/app/components/createAlertButton.spec.tsx
  static/app/components/demoSandboxButton.tsx
  static/app/components/modals/widgetViewerModal.spec.tsx
  static/app/components/noProjectMessage.spec.tsx
  static/app/components/updatedEmptyState.spec.tsx
  static/app/views/alerts/list/rules/alertRulesList.spec.tsx
  static/app/views/alerts/rules/issue/details/ruleDetails.spec.tsx
  static/app/views/issueDetails/streamline/sidebar/seerSectionCtaButton.tsx
  static/app/views/performance/otlp/overviewSpansTable.tsx
  static/app/views/projectDetail/projectTeamAccess.spec.tsx
  static/app/views/settings/organizationIntegrations/exampleIntegrationButton.tsx
  static/app/views/settings/organizationIntegrations/integrationDetailedView.spec.tsx
  static/app/views/traces/fieldRenderers.spec.tsx
  static/gsApp/components/addEventsCTA.tsx
  static/gsApp/hooks/orgStatsProfilingBanner.tsx
Labels: Scope: Frontend

#90877 fix: handle deleted org in ingest pipelines
  src/sentry/ingest/consumer/processors.py
Labels: Scope: Backend

#90755 feat(trace-eap-waterfall): Building trace highlights from eap trace-item attrs
  static/app/views/performance/newTraceDetails/traceHeader/highlights.tsx
  static/app/views/performance/newTraceDetails/traceHeader/scrollToSectionLinks.tsx
Labels: Scope: Frontend

#89857 feat(nextjs-insights): web vitals
  static/app/views/insights/pages/platform/laravel/referrers.ts
  static/app/views/insights/pages/platform/nextjs/index.tsx
  static/app/views/insights/pages/platform/nextjs/webVitalsWidget.tsx
  static/app/views/insights/types.tsx
Labels: Scope: Frontend

#90852 OPS-6010: reduce read_row timeout to 5s
  src/sentry/utils/kvstore/bigtable.py
  tests/sentry/nodestore/bigtable/test_backend.py
  tests/sentry/utils/kvstore/test_bigtable.py
Labels: Scope: Backend

#90612 feat(trace-eap-waterfall) Loading eap trace-item details in useTraceR…
  static/app/components/events/interfaces/performance/eventTraceView.tsx
  static/app/components/events/interfaces/performance/spanEvidenceTraceView.tsx
  static/app/views/explore/hooks/useTraceItemDetails.tsx
  static/app/views/performance/newTraceDetails/index.tsx
  static/app/views/performance/newTraceDetails/traceActionsMenu.tsx
  static/app/views/performance/newTraceDetails/traceApi/useTraceRootEvent.tsx
  static/app/views/performance/newTraceDetails/traceApi/utils.tsx
  static/app/views/performance/newTraceDetails/traceContextPanel.tsx
  static/app/views/performance/newTraceDetails/traceContextVitals.tsx
  static/app/views/performance/newTraceDetails/traceHeader/highlights.tsx
  static/app/views/performance/newTraceDetails/traceHeader/index.tsx
  static/app/views/performance/newTraceDetails/traceHeader/meta.tsx
  static/app/views/performance/newTraceDetails/traceHeader/projects.tsx
  static/app/views/performance/newTraceDetails/traceHeader/scrollToSectionLinks.tsx
  static/app/views/performance/newTraceDetails/traceHeader/title.tsx
  static/app/views/performance/newTraceDetails/traceModels/traceTree.tsx
  static/app/views/performance/newTraceDetails/traceWaterfall.tsx
  static/app/views/performance/newTraceDetails/useTraceContextSections.tsx
  static/app/views/replays/detail/trace/trace.tsx
Labels: Scope: Frontend

#90890 feat(eap-spans): allow percentage fields in percentile functions
  src/sentry/search/eap/spans/aggregates.py
Labels: Scope: Backend

#90701 feat(replay): add hovercard to release tag and filter dropdown
  static/app/components/replays/releaseDropdownFilter.tsx
  static/app/components/replays/replayTagsTableRow.tsx
  static/app/views/replays/replayTable/tableCell.tsx
Labels: Scope: Frontend

#90684 feat(feedback): add release hover to tags
  static/app/components/feedback/feedbackItem/feedbackItem.tsx
  static/app/components/feedback/feedbackItem/tagsSection.tsx
  static/app/components/feedback/hydrateFeedbackTags.tsx
  static/app/components/feedback/useFetchFeedbackData.tsx
Labels: Scope: Frontend

#90829 fix(releases): Fix when project not yet loaded yet and drawer is opened
  static/app/views/releases/utils/useReleaseDeploys.tsx
Labels: Scope: Frontend

#90891 chore(alerts-comparison): Optionally get confidence
  src/sentry/discover/compare_timeseries.py
Labels: Scope: Backend

#90833 feat(explore): Removes breadcrumbs from the all queries view and adds a create query button
  static/app/views/alerts/rules/utils.spec.tsx
  static/app/views/dashboards/utils/getWidgetExploreUrl.spec.tsx
  static/app/views/explore/savedQueries/index.tsx
  static/app/views/explore/savedQueries/savedQueriesTable.spec.tsx
  static/app/views/explore/utils.tsx
Labels: Scope: Frontend

#90782 ref(flags): reorganize flag files into folders
  static/app/components/events/featureFlags/cta/featureFlagInlineCTA.spec.tsx
  static/app/components/events/featureFlags/cta/featureFlagInlineCTA.tsx
  static/app/components/events/featureFlags/eventFeatureFlagDrawer.spec.tsx
  static/app/components/events/featureFlags/eventFeatureFlagDrawer.tsx
  static/app/components/events/featureFlags/eventFeatureFlagSection.spec.tsx
  static/app/components/events/featureFlags/eventFeatureFlagSection.tsx
  static/app/components/events/featureFlags/onboarding/featureFlagOnboardingLayout.tsx
  static/app/components/events/featureFlags/onboarding/featureFlagOnboardingSidebar.tsx
  static/app/components/events/featureFlags/onboarding/featureFlagOtherPlatformOnboarding.tsx
  static/app/components/events/featureFlags/onboarding/onboardingAdditionalFeatures.tsx
  static/app/components/events/featureFlags/onboarding/useFeatureFlagOnboarding.tsx
  static/app/components/sidebar/index.tsx
  static/app/views/issueDetails/groupDistributions/flagsDistributionDrawer.tsx
  static/app/views/issueDetails/groupDistributions/suspectTable.tsx
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
  static/app/views/issueDetails/groupFeatureFlags/details/flagDetailsDrawerContent.spec.tsx
  static/app/views/issueDetails/groupFeatureFlags/details/flagDetailsDrawerContent.tsx
  static/app/views/issueDetails/groupFeatureFlags/details/flagDetailsLink.tsx
  static/app/views/issueDetails/groupFeatureFlags/flagDrawerCTA.tsx
  static/app/views/issueDetails/groupFeatureFlags/flagDrawerContent.tsx
  static/app/views/issueDetails/groupFeatureFlags/hooks/useGroupFeatureFlags.tsx
  static/app/views/issueDetails/groupFeatureFlags/hooks/useGroupFlagDrawerData.tsx
  static/app/views/issueDetails/groupFeatureFlags/hooks/useGroupSuspectFlagScores.tsx
  static/app/views/organizationLayout/index.tsx
  static/app/views/settings/featureFlags/index.tsx
Labels: Scope: Frontend

#90892 fix(issue summary): Remove org acknowledgement check for issue summary
  src/sentry/seer/issue_summary.py
  tests/sentry/seer/test_issue_summary.py
Labels: Scope: Backend

#90851 feat(widget-builder): Clean up feature flag
  static/app/components/modals/widgetBuilder/addToDashboardModal.spec.tsx
  static/app/components/modals/widgetBuilder/addToDashboardModal.tsx
  static/app/views/dashboards/addWidget.tsx
  static/app/views/dashboards/controls.tsx
  static/app/views/dashboards/dashboard.spec.tsx
  static/app/views/dashboards/dashboard.tsx
  static/app/views/dashboards/detail.spec.tsx
  static/app/views/dashboards/detail.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/filterResultsStep/index.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/groupByStep/groupBySelector.tsx
  static/app/views/dashboards/widgetBuilder/buildSteps/sortByStep/sortBySelectors.tsx
  static/app/views/dashboards/widgetBuilder/components/groupBySelector.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/newWidgetBuilder.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/queryFilterBuilder.spec.tsx
  static/app/views/dashboards/widgetBuilder/components/visualize/index.spec.tsx
  static/app/views/dashboards/widgetBuilder/widgetBuilderDataset.spec.tsx
  static/app/views/dashboards/widgetBuilder/widgetBuilderSortBy.spec.tsx
  static/app/views/discover/queryList.spec.tsx
  static/app/views/discover/savedQuery/index.spec.tsx
  static/app/views/discover/utils.spec.tsx
  static/app/views/discover/utils.tsx
  static/app/views/explore/hooks/useAddToDashboard.spec.tsx
  static/app/views/explore/hooks/useAddToDashboard.tsx
  static/app/views/explore/multiQueryMode/hooks/useAddCompareQueryToDashboard.tsx
  static/app/views/explore/toolbar/index.spec.tsx
  tests/acceptance/test_organization_dashboards.py
Labels: Scope: Frontend

#90893 feat(trace-eap-waterfall): Triggering capture exception only when query is enabled
  static/app/views/explore/hooks/useTraceItemDetails.tsx
Labels: Scope: Frontend

#90897 fix(mobile-vitals): Typo in TTID description
  static/app/views/insights/mobile/screens/views/screensLandingPage.tsx
Labels: Scope: Frontend

#90786 feat(uptime): Add feature flag for processing via detectors
  src/sentry/features/temporary.py
Labels: Scope: Backend

#90775 ref(uptime): Stop writing uptime_status on ProjectUptimeSubscription
  src/sentry/uptime/consumers/results_consumer.py
  src/sentry/uptime/subscriptions/subscriptions.py
Labels: Scope: Backend

#90828 chore(sentry_sdk): Include full stack for captured errors
  src/sentry/conf/types/sdk_config.py
  src/sentry/options/defaults.py
  src/sentry/utils/sdk.py
Labels: Scope: Backend

#90896 feat(workflow_engine): Allow stateful detector values beside int
  src/sentry/incidents/grouptype.py
  src/sentry/workflow_engine/handlers/detector/base.py
  src/sentry/workflow_engine/handlers/detector/stateful.py
  tests/sentry/workflow_engine/handlers/detector/test_base.py
Labels: Scope: Backend

#90856 fix(profiling): Convert task to use JSON encodable values
  src/sentry/profiles/consumers/process/factory.py
  src/sentry/profiles/task.py
  tests/sentry/profiles/consumers/test_process.py
  tests/sentry/profiles/test_task.py
Labels: Scope: Backend

#90903 fix(attributes-tree): Make actions appear in nested values too
  static/app/views/explore/components/traceItemAttributes/attributesTree.spec.tsx
  static/app/views/explore/components/traceItemAttributes/attributesTree.tsx
Labels: Scope: Frontend

#90848 build(ui): Use esbuild to build charcuterie config
  config/build-chartcuterie.ts
  config/webpack.chartcuterie.config.ts
  package.json
  yarn.lock
Labels: Scope: Frontend, Scope: Backend

#90904 fix(issue-views): remove gap on issue view nav item in chonk ui
  static/app/views/nav/secondary/sections/issues/issueViews/issueViewNavItemContent.tsx
Labels: Scope: Frontend

#90913 fix(issues): Reduce interval for 3 to 6 hour graphs
  static/app/components/charts/utils.tsx
Labels: Scope: Frontend

#90889 feat(explore): Adds new columns to Explore Saved Queries model to support prebuilt queries
  migrations_lockfile.txt
  src/sentry/explore/migrations/0003_add_prebuilt_column_to_explore_saved_queries.py
  src/sentry/explore/models.py
Labels: Scope: Backend

#90915 feat(eap-spans): add app start fields
  src/sentry/search/eap/spans/attributes.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#90857 ref(stats): Better typing
  static/app/constants/index.tsx
  static/app/types/core.tsx
  static/app/views/organizationStats/index.tsx
  static/app/views/organizationStats/usageChart/index.tsx
  static/gsAdmin/components/customers/customerStats.tsx
  static/gsAdmin/components/customers/customerStatsFilters.tsx
  static/gsAdmin/views/customerDetails.tsx
  static/gsAdmin/views/projectDetails.tsx
  static/gsApp/components/gsBanner.tsx
  static/gsApp/components/navBillingStatus.tsx
Labels: Scope: Frontend

#90914 fix(billing): Retain capitalization in customerHistory
  static/gsAdmin/components/customers/customerHistory.tsx
Labels: Scope: Frontend

#90912 chore(anomaly detection): increase historical anomaly detection timeout
  src/sentry/conf/server.py
  src/sentry/seer/anomaly_detection/get_historical_anomalies.py
Labels: Scope: Backend

#90894 fix(ui): Dropdown button chevron colour
  static/app/components/dropdownButton.tsx
Labels: Scope: Frontend

#90834 feat(insights): update mobile overview columns
  static/app/views/insights/common/components/tableCells/renderHeadCell.tsx
  static/app/views/insights/pages/mobile/mobileOverviewPage.tsx
  static/app/views/insights/pages/mobile/mobileOverviewTable.tsx
  static/app/views/insights/pages/mobile/settings.ts
  static/app/views/insights/types.tsx
Labels: Scope: Frontend

#90860 feat(aci): Check issue evidence data to get alert id
  static/app/views/issueDetails/groupEventDetails/groupEventDetailsContent.tsx
  static/app/views/issueDetails/metricIssues/utils.tsx
  static/app/views/issueDetails/streamline/sidebar/detectorSection.tsx
Labels: Scope: Frontend

#90920 fix(gs-hooks): Memoize <Hook /> to prevent infinite rerenders
  static/app/components/hook.tsx
Labels: Scope: Frontend

#90923 fix(assisted queries): Ensure query only strings
  src/sentry/api/endpoints/seer_rpc.py
  tests/snuba/api/endpoints/test_seer_attributes.py
Labels: Scope: Backend

#90858 ref(explore): Clean up explore spans tab wrappers
  static/app/views/explore/spans/content.tsx
  static/app/views/explore/spans/spansTab.spec.tsx
  static/app/views/explore/spans/spansTab.tsx
Labels: Scope: Frontend

#90838 feat(workflow): Support sorting in the Detectors index api
  src/sentry/apidocs/parameters.py
  src/sentry/workflow_engine/endpoints/project_detector_index.py
  src/sentry/workflow_engine/endpoints/serializers.py
  tests/sentry/workflow_engine/endpoints/test_project_detector_index.py
  tests/sentry/workflow_engine/endpoints/test_serializers.py
Labels: Scope: Backend

#90924 feat(docs): Update stories to show the comitter date of the story file
  static/app/components/timeline/index.stories.tsx
  static/app/views/stories/storyExports.tsx
  static/app/views/stories/storySourceLinks.tsx
Labels: Scope: Frontend

#90193 feat(new-trace): Removing trace-view-new-ui flag from the backend
  src/sentry/features/temporary.py
Labels: Scope: Backend

#89901 fix(timeseries): Handle small intervals
  src/sentry/api/bases/organization_events.py
  src/sentry/api/endpoints/organization_events_timeseries.py
  tests/snuba/api/endpoints/test_organization_events_stats_span_indexed.py
  tests/snuba/api/endpoints/test_organization_events_timeseries_spans.py
Labels: Scope: Backend

#90927 feat(eap-spans): support conditional aggregates in eap resolver queries
  src/sentry/search/eap/resolver.py
  tests/snuba/api/endpoints/test_organization_events_span_indexed.py
Labels: Scope: Backend

#90930 style(explore): Refactor layout a little
  static/app/views/explore/spans/spansTab.tsx
  static/app/views/explore/toolbar/toolbarSuggestedQueries.tsx
Labels: Scope: Frontend

#90937 fix(migrations): Fix monitor migrations move dependencies
  src/sentry/monitors/migrations/0001_initial.py
Labels: Scope: Backend
